### ISSUE TITLE
rssguard: segfault in libQtGui.so.4.8.6

### ISSUE THREAD

**Issue by 666threesixes666** [martinrotter/rssguard#1]
first of all, thanks, major thanks...  this is the only rss client that suits all of my needs.  i watch funtoo.org via rss.  this error occurred when loading the funtoo.opml located @ https://bugs.funtoo.org/secure/attachment/12820/funtoo.opml

funtoo.org

dev-qt/qtgui
Properties for version: 4.8.6-r2
Final environment Use flags: +accessibility, +cups, +exceptions, +glib, +mng, +qt3support, +tiff, +xv, -egl, -gtkstyle, -nas, -nis, -trace, -xinerama, -abi_x86_32, -debug, -pch

[  888.212195] rssguard[4154]: segfault at 1e9000000ec ip 00007ff31f6774f6 sp 00007ffff50ae1f0 error 4 in libQtGui.so.4.8.6[7ff31ef16000+a91000]

if you want me to do anything feel free to shout at me @ #funtoo freenode.net user name: threesixes

**Comment by martinrotter** [comment]
Hello. OK. Thanks for bug report. I will investigate it on Sunday, I am not at home right now. Soo the crash happens only with this opnl file? Does it happens with other opml files too?

Which version of code you used? Please could you test latest code from https://bitbucket.org/skunkos/rssguard . This github repository is sometimes behind code on bitbucket.

**Comment by 666threesixes666** [comment]
this issues from 2.3.0, ill revbump the overlay for 2.3.1 i haven't tried any other opml's, and it was just once.  but occurring infrequently can mean security issues or build deps not satisfied.  (i don't know how to make live ebuilds yet, this is like week 1 of dev for me.)  =)  sorry about forgetting the version of your code.

**Comment by martinrotter** [comment]
So issue happened when you "loaded" opml file are after you clicked "Import" button?

**Comment by martinrotter** [comment]
@666threesixes666 Could you please run rssguard in terminal and reproduce the bug? Paste the output of terminal when bug occurs here via pastebin or gist.

**Comment by 666threesixes666** [comment]
uhhh sure...  
rm -rf $HOME/.rssguard
import funtoo.opml
select category (also highlights all feeds)
ok
(dialog doesn't disappear)
ok again: 
https://gist.github.com/666threesixes666/6ec16ca25241cc695898

**Comment by martinrotter** [comment]
Give here the exact OPML file you used to trigger the crash. It seems that file in link changes from time to time.

I am not able to reproduce, how often does that happen?

**Comment by martinrotter** [comment]
Would you be able to compile rssguard in debug mode and provide crash dump?

cmake -DCMAKE_BUILD_TYPE=debug ......

**Comment by 666threesixes666** [comment]
it happens 75ish % or more.

https://github.com/666threesixes666/local_overlay/blob/master/funtoo.opml

ok actually looking at the ebuild & sources it looks like i could compile it in source outside of portage and be ok about its accuracy  id still like to be able to enable debugs from the portage compile, but for now ill compile by hand.

**Comment by martinrotter** [comment]
The core dump is unusable. Double-check that you really COMPILE rssguard code in DEBUG mode. Your dump does not contain any stack metadata, thus stack trace does not display names of called methods nor lines in code.

**Comment by 666threesixes666** [comment]
yeah im positive it was in debug mode, the segfault had (debug) in the lines next to it.  thanks again for all of this. =)  ill recompile it & send updates...  did you try the opml from the git overlay?

**Comment by martinrotter** [comment]
Yes because you must issue "make install" too. RSS Guard is not able to find its skins, and will not even launch that way.

**Comment by 666threesixes666** [comment]
so is this dump not correct also?  if i must issue make install then it must be getting tainted with previous system install stuff.  could you send exact procedures so i guess absolutely nothing.  :+1:

**Comment by martinrotter** [comment]
OK.

1. Obtain the code (in your case 3.2.0, https://bitbucket.org/skunkos/rssguard/get/2.3.0.zip).
2. Unpack the code. Create build directory.
3. Use cmake -DCMAKE_BUILD_TYPE=debug -DCMAKE_INSTALL_PREFIX=/path/to/store/compiled/contents (for example I use cmake -DCMAKE_BUILD_TYPE=debug -DUSE_QT_5=on -DCMAKE_INSTALL_PREFIX=/home/user/compilation).
4. Run make and make install.
5. Now your /path/to/store/compiled/contents contains directory structure of compiled rssguard, go to bin subdirectory.
6. Now run rssguard binary from that subdirectory and make core dump of it. You must provide me the dump from rssguard session where you reproduced the bug.

@666threesixes666  :)

**Comment by martinrotter** [comment]
Note that "make install" only copies all necessary files to -DCMAKE_INSTALL_PREFIX, so you can basically use any directory and then just delete it. I even use tmpfs for target directory.

**Comment by 666threesixes666** [comment]
cmake -DCMAKE_BUILD_TYPE=debug -DCMAKE_INSTALL_PREFIX=/home/mkultra/rssgurrddd && make && make install
cd $HOME/rssgurrddd/
ulimit -c unlimited
ls
cd bin/
ls
./rssguard
mv core ../../overlays/local/core.rssguarddump3
cd ../../overlays/local/
push (which is a script of git add . && git commit -m 'updates' && git push origin master because idk git well)
https://github.com/666threesixes666/local_overlay/blob/master/core.rssguarddump3

**Comment by 666threesixes666** [comment]
is it possible that the amdfam10 gcc flag being set on the majority of my system conflicts with the qt qmake stuff which i do not think has those optimizations enabled, clashing optimized/generic against each other causing problems?  if you want to make a funtoo virtual machine to test with i can walk you through that.

**Comment by martinrotter** [comment]
I see. I will try the core dump. Alternatively, you can provide just backtrace.

Simply use gdb or qtcreator. "gdb ./rssguard", then gdb starts. Then write into gdb console "run". Your program now starts. Now reproduce the issue, until segfault is visible in gdb - gdb automatically pauses. Then you can write command "bt" which will print backtrace, then copy backtrace here.

But I will try dump first.

**Comment by 666threesixes666** [comment]
ping: do you need more interaction from me?  would you like a longer break? ill give you a few more days before i return with backtraces.  =D

**Comment by martinrotter** [comment]
Hi.

I was pretty busy (job/school/wife/kid). I will have time to work on RSS Guard today evening again.

**Comment by martinrotter** [comment]
I made some changes. Please get latest code from this repository (https://bitbucket.org/skunkos/rssguard/), compile and try to reproduce bug again.

If you hit the bug again, create coredump and provide backtrace if possible. :)

**Comment by 666threesixes666** [comment]
sorry ive been super busy, rewriting mediawiki bootstrap skins, font awesome, for funtoo, writing a csprng ebuild, etc.  im only doing release tarballs of rssguard for funtoo because i dont know how to make git ebuilds yet.

**Comment by 666threesixes666** [comment]
2.3.1 looks good to go, thanks sir =D

**Comment by martinrotter** [comment]
So fixed? Nice to hear that. :)
