### ISSUE TITLE
[BUG]: RSS Guard Not Fetching Feeds since few days.

### ISSUE THREAD

**Issue by bsudhir6** [martinrotter/rssguard#1000]
### Brief description of the issue

Since few days my RSS Guard is not fetching any feeds.

### How to reproduce the bug?

Open RSS Guard click fetch button
Feeds not appearing

### What was the expected result?

Latest feeds should show up.

### What actually happened?

Nothing happens RSS Guard reports no feeds all the listed feeds shown as red.

### Debug log

Don't know where to find the logs.

### Operating system and version

* OS: Windows 10 64 bit
* RSS Guard version: 4.4.0

**Comment by martinrotter** [comment]
You need to provide RSS Guard log file, see docs for more info.
