### ISSUE TITLE
[BUG]: Clicking on a notification from other apps brings up the RSS Guard about dialog or update dialog

### ISSUE THREAD

**Issue by gianmarcogg03** [martinrotter/rssguard#1001]
### Brief description of the issue

Under KDE Plasma 5.27.6 (Wayland) when I click on a notification from any application, RSS Guard opens up its about dialog or, in case I'm not using the latest version of RSS Guard, its update dialog.

### How to reproduce the bug?

1. Get a notification from some application.
2. Click on the notification.

### What was the expected result?

RSS Guard should not interfere at all.

### What actually happened?

RSS Guard brings up the about dialog or the update dialog.

### Debug log

The log doesn't show anything when this bug happens.

### Operating system and version

* OS: Arch Linux
* RSS Guard version: 4.4.0

**Comment by martinrotter** [comment]
What. How is this possible. Provide some video.

**Comment by gianmarcogg03** [comment]
The bug doesn't occur for months until it comes again. It's really strange, the next time around I'll try to record it.

**Comment by martinrotter** [comment]
I see. Well, I need some simle steps to be able to reproduce the bug, otherwise hard to fix at all.

**Comment by gianmarcogg03** [comment]
Here we are again, it's happening again and now I have caught it on video.

https://github.com/martinrotter/rssguard/assets/28053717/009f0fd3-524d-4ee8-a062-b913fa399afc

**Comment by martinrotter** [comment]
This is clearly upstream bug.
