### ISSUE TITLE
[FR]: Dowload multiple RSS feeds at the same time

### ISSUE THREAD

**Issue by shoulders** [martinrotter/rssguard#1002]
### Brief description of the feature request

I have a lot of RSS feeds and they all all parsed one after the other which can take a bit of time.

Is it possible to download multiple RSS feeds at the same time?

I would also put the number of download threads as shown below;

![image](https://github.com/martinrotter/rssguard/assets/319997/ffc69262-a48b-406d-ad4f-b8c899e9d523)

**Comment by martinrotter** [comment]
This feature is already there and is enabled by default. Can be tweaked with CLI parameters, to see CLI parameters, launch RSS Guard from console like this: "rssguard --help"
