### ISSUE TITLE
[FR]: automatic search function 

### ISSUE THREAD

**Issue by daf121** [martinrotter/rssguard#1006]
### Brief description of the feature request

I have many feeds I follow, I'd like an automatic search folder, where all items containing one or more keywords land.  (like late RSSOwl)

**Comment by martinrotter** [comment]
Yes, I plan to add this. Individual "searches" will appear as separate items in feed list.

I plan to add searching according to regular expressions.

**Comment by martinrotter** [comment]
Working on this feature which will be called "Article probes" in RSS Guard. A "probe" will be permanent regexp-based filter selectable in feed list which will display all articles matching your regular expression.

![rssguard_uEE4pqNXJT](https://github.com/martinrotter/rssguard/assets/1255302/d6d5812b-4bd9-47c0-a31c-abe45b4d264a)
![rssguard_QwghD9hxTD](https://github.com/martinrotter/rssguard/assets/1255302/a18f702f-76aa-4bbf-8cb2-f0f755bf2b3b)
![rssguard_DAeYmHTxxl](https://github.com/martinrotter/rssguard/assets/1255302/e3fb4664-f884-4079-95fc-3d4eed58e4f3)

**Comment by martinrotter** [comment]
Also, note that this functionality can also be done with using already existing features - Labels + Article filters.

**Comment by martinrotter** [comment]
THis feature is now pushed but is semi-completed, so far only for testing and changes are not persistently saved. Pls test.
