### ISSUE TITLE
[FR]: Ability to apply post-process script to all feeds within a feed category

### ISSUE THREAD

**Issue by RetroAbstract** [martinrotter/rssguard#1010]
### Brief description of the feature request

This feature would allow the user to apply all feeds within a feed category a post-process script by right clicking a feed category > Edit selected item > Post-process script.

**Comment by martinrotter** [comment]
Yes. I plan to add some reasonably good multi-select feed editing capabilities, this is on my internal todo list, but that todo list, my man, is veeeeeery long. There is just too many other things to do in rssguard.

**Comment by martinrotter** [comment]
Fixed with https://github.com/martinrotter/rssguard/commit/5d7cb9dfcdc983b60ea708bacadc1b57676dd244.
