### ISSUE TITLE
[BUG]: Application is crashing when jump to next unread article in new folder

### ISSUE THREAD

**Issue by Crandel** [martinrotter/rssguard#1011]
### Brief description of the issue

As vim user I use keyboard shortcuts everywhere. Since last update rssguard starts crashing when I jump to next unread article in next folder. In current folder no new articles left.
It's happens only if I use keyboard shortcut. If I switch to next folder via mouse everything works fine.

### How to reproduce the bug?

1. Read all articles in current folder
2. Jump to next unread article in next folder via keyboard shortcut `Jump to next unread article`

### What was the expected result?

Next unread article should be opened

### What actually happened?

Application always crashing

### Debug log

https://gist.github.com/Crandel/55955faf42f13f413d5df0d67fbebfe2

### Operating system and version

* OS:Arch Linux, Swaywm (Wayland)
* RSS Guard version: 4.4.0-1

**Comment by martinrotter** [comment]
Just tried it and cannot reproduce. Provide the actually stack-trace when app crashes pls. Will test tonight on my Arch instance.

**Comment by Crandel** [comment]
This is the actual stacktrace made by command `rssguard --log '/tmp/rssguard.log'`. I have no more output or any additional information

**Comment by martinrotter** [comment]
https://wiki.archlinux.org/title/Debugging/Getting_traces

**Comment by Crandel** [comment]
I add stacktrace [here](https://gist.github.com/Crandel/55955faf42f13f413d5df0d67fbebfe2#file-coredump)

**Comment by martinrotter** [comment]
Managed to reproduce but have no idea why it happens and what to actually fix. :D

**Comment by Crandel** [comment]
Cursor jumps to new article, but old one still on view screen. Maybe issue with refreshing view screen?

**Comment by martinrotter** [comment]
Well, kind of, it has apparently something to do with "scrolling". Also, in the area of code there are really no real changes at all. Maybe this is some kind of upstream regression in Qt?

**Comment by martinrotter** [comment]
Are you able to also reproduce the issue on "rssguard-lite" package?

**Comment by Crandel** [comment]
No, I have no `rssguard-lite` installed

**Comment by martinrotter** [comment]
Could you try it?

**Comment by martinrotter** [comment]
Dont worry about your data, they are completely portable between those variants.

**Comment by Crandel** [comment]
Exactly the same crash on `rssguard-lite`

**Comment by martinrotter** [comment]
ok

**Comment by martinrotter** [comment]
Does this issue still persists by chance? I was trying to reproduce on my home Arch machine (/w Mate) but was not successful.

**Comment by Crandel** [comment]
Yes, still the same behavior.

**Comment by martinrotter** [comment]
Could you perhaps run git bisect to find the commit which introduced the bug?

**Comment by Crandel** [comment]
I have no idea how to do it

**Comment by Crandel** [comment]
Was fixed in latest release

**Comment by martinrotter** [comment]
okay, thanks for checking
