### ISSUE TITLE
Support LABELS

### ISSUE THREAD

**Issue by martinrotter** [martinrotter/rssguard#102]
Add general support for message labels, Each label will have:

* color,
* title.

Sub-features:
* [x] there will be "root" item in feed's list called "Labels" which will have subitem for each label,
* [x] each "label" item will display the color instead of icon,
* [x] selecting of "Label" item will display all messages which have that label assigned,
* [x] selecting of "Label**s**" will display all messages which have at least some label assigned,
* [x] "Labels" item will offer "Create label" action in its context menu,
* [x] each "label" item will support "Edit" context menu item and "Delete" (remove label) context menu item,
* [x] each message should be assignable to multiple labels,
* [x] unify C++ interfaces of both WebEngine and Non-WebEngine message previewers,
* [x] display list of all labels in message "previewer" and allow to activate new labels or deselect active labels for the message,
* [x] "sync-in" action of each account type will also synchronize labels,
* [x] changed message-label assignments will be also cached and pushed to servers the same way as read/unread/important state changes,
* [x] Add interface to ServiceRoot to check if account even supports adding feeds, editing feeds and deleting labels. Then disable according actions,
* [x] add "Labels" menu item to messages view context menu,
* [x] make "Label" item respond correctly to "newspaper" request,
* [x] make labels available (**read-only**) in "MessageObject" for filtering,
    * [x] make labels assignments also changeable in filtering scripts (will appear in 3.8.1),
* [x] Implement label/tag functionality for plugins:
    * [x] TT-RSS (fetch all labels, (de)assign labels to/from messages),
    * [x] Inoreader (fetch all labels, (de)assign labels to/from messages).

Related tickets: #260.

Related documentation:
* TT-RSS - https://git.tt-rss.org/fox/tt-rss/wiki/ApiReference#setarticlelabel-since-api-level-1
* Inoreader - https://www.inoreader.com/developers/edit-tag

**Comment by pcause** [comment]
great spec

**Comment by martinrotter** [comment]
Initial version of add/edit label dialog:

![image](https://user-images.githubusercontent.com/1255302/95331116-cc005080-08a9-11eb-8a52-84d108f191eb.png)

**Comment by pcause** [comment]
great.  went to bintray and the newest build and didn't see this.  will check back later and give it a try

**Comment by martinrotter** [comment]
It is not yet commited, just in my working copy. Programming it RN.

**Comment by martinrotter** [comment]
Sample "Labels" in feed list:
![image](https://user-images.githubusercontent.com/1255302/95334417-5c409480-08ae-11eb-9953-7506e2356d77.png)

**Comment by pcause** [comment]
nice.

**Comment by martinrotter** [comment]
@pcause What about more minimal "add/edit" dialog setup? Is it better then original one?

![image](https://user-images.githubusercontent.com/1255302/95335192-5f885000-08af-11eb-9837-502b8585d25b.png)

**Comment by pcause** [comment]
simpler is better.  can the user choose color by clicking the color box?

**Comment by martinrotter** [comment]
Yes, he can.

**Comment by pcause** [comment]
great.  what someone would expect.. if the color box looks more like a button would be obvious but OK for me the way it is.

**Comment by martinrotter** [comment]
I is "animated" when user hovers with mouse cursor over it. It is in fact button, just specifically colored (rounded borders) and to text inside.

**Comment by martinrotter** [comment]
OK, it is possible to add labels and display messages with given label or any label (when clicked on "Labels"). It is not yet possible to assign labels to msgs, or remove/edit label. WIll work on that.

![image](https://user-images.githubusercontent.com/1255302/95349251-2ce65380-08bf-11eb-9e1f-b9fa9d147ffc.png)

**Comment by pcause** [comment]
that is terrific.  thanks.  looking forward to it.

**Comment by martinrotter** [comment]
@pcause OK, now, I need to add "labels" to message preview so that user can add/remove labels from displayed message.

I am thinking about inserting available labels to marked position into the toolbar vertically. Each label would be represented with colored "button" which would be toggleable. Or perhaps toolbar button "Labels" with dropdown menu for labels? 

![image](https://user-images.githubusercontent.com/1255302/95456488-afc6e700-096f-11eb-9769-a3489343fef2.png)

**Comment by pcause** [comment]
think button with a fly out would be ideal but not sure if the qt toolkit supports.  it would show list of labels and an add label entry.   other idea is to put the lables and add label button under title.

**Comment by martinrotter** [comment]
well it is difficult (very) to embed labels directly into "web view" (under message title) because I would have to somehow deal with non-webengine version of rss guard which displays message differently

i will go with toolbar and think about best way if displaying labels

**Comment by martinrotter** [comment]
@pcause Well, what about this?

Bonus will be that the layout of "label" buttons would be changeable (text beside icon, text under icon, just icon with tooltip, ...). When label is "active" then it is visible, in screenshot Test and Test3 labels are active, Test2 label is configured but inactive for this particular message. What you think?

![image](https://user-images.githubusercontent.com/1255302/95613776-c3547980-0a65-11eb-88f8-5548fe85e8fd.png)

**Comment by martinrotter** [comment]
Or perhaps the toolbar from message previewer could be horizontal (vertical suits me personally better):

![image](https://user-images.githubusercontent.com/1255302/95614786-5cd05b00-0a67-11eb-92eb-9646f3d0ad4a.png)

**Comment by martinrotter** [comment]
@pcause and others, I added very basic implementation (so far without synchronization, only off-line labels can be added). Can you please rougly test it? So far you can: create, edit, delete labels and (de)assign labels to/from messages.

Pls test.

**Comment by martinrotter** [comment]
https://github.com/martinrotter/rssguard/commit/93721ac9e0d5694dec490d91252f65ec1d7e0f11

**Comment by martinrotter** [comment]
Working on it guys, some code for online-synchronization is underway.

![image](https://user-images.githubusercontent.com/1255302/96365256-937d3400-113f-11eb-8e0c-87d8bef3d6b9.png)

**Comment by pcause** [comment]
was offline but will be on later today and tomorrow and will test

**Comment by martinrotter** [comment]
@pcause Sure, at this point, almost all operations with labels should "work" for standard XML-based offline account type. As for TT-RSS -> labels should be fetched when you run "Sync in" action. RN I work on fetching message/label assignments when getting new messages and logic around it.

**Comment by pcause** [comment]
great.  is there an element in the message object for filters?  can we change/add/assign labels there?

PS:  Remember that in tt-rss an item can have multiple labels.

**Comment by martinrotter** [comment]
No, at this point no. It is separate ticket which I will implement after base label/tag implementation is done.

**Comment by martinrotter** [comment]
I added checkboxes for labels in filtering availability to have all labels-related tickets in one ticket here.

**Comment by pcause** [comment]
martin, first THANKS.  terrific work.  almost there.

I deleted my existing version and installed the newest.  It was  rssguard-3.7.2-6ed79f5-win64.7z.  I started and added my tt-rss site.  Started a sync and got memory fault.  Sorry lost the screenshot.

restarted.  I can see some labels so i started a sync again.  Finished.  server web interface showing 16 labels (17 after refresh) and rssgaurd showing 18.  when i expand "labels" on each side if i add the item counts rssguard matches 18 but ttrss shows 17 andn counts add to 18.

selected a label and can see the items.  clicked on the left part of the message display and unset the label.   i waited and then set as unread.  shows as unread in web interface but label still there.  also adding label to an item without one doesn't sync back.

right click on a label in the tree and the popup doesn't have mark read/mark unread.

can you make the web engine settings part of the tools/settings?  i have to click and open to change each web browser option.  annoying.  you should not allow the web engine to access local files by default.  VERY insecure. 

also i used to be able to sort by feed and then by time within feed.  this seems to have gone away.  if a feed is a discussion you need to have time order.  in a category display you then need to sort by feed then date.

will keep testing today.

**Comment by pcause** [comment]
I have a feed with 1 article.  read it.  changed from bold to normal font so read, but feed /category count still shows 1

**Comment by martinrotter** [comment]
@pcause Yes, this is unfinished works, many things are not just there. Almost all things you noted are on my mind and I know they are not yet implemented. Consider this phase to be pre-alpha, it is really just to see some progress.

Propagation of label changes is not yet sent to server, in other words label changes from/to messages are not yet synchronised back to server. Of course I will add this sub-feature soon. Of course that label items and parent "Labels" item will offer "mark read/unread" action and also "clean items" action.

"can you make the web engine settings part of the tools/settings? i have to click and open to change each web browser option. annoying. you should not allow the web engine to access local files by default. VERY insecure." - **can you ellaborate** on this, I probably not understand really correctly what exactly you mean.

"also i used to be able to sort by feed and then by time" - multicolumn sorting should still work, but I will check

**Comment by pcause** [comment]
web browser and tabs/wen engine settings.  for each item you want to check/uncheck, when you do the flyout closes.  so you have to click the web browser and tabs and then web engine settings again for each web browser option.  the local content/local files creates a back door to access files and possible send, depending on the exact details of the implementation and strength of the sandbox.  but since this is a browser for looking at feed content i'd think for security you'd want this off by default.

btw, there is a checkbox for "plugins enabled".  what plugins?  there is just adblock which isn't controlled by this, right?

**Comment by pcause** [comment]
not sure if i should put issues i find in general issues or here given this is alpha code.  in key assignment i can assign a key to 2 different things without knwoing.  i'd suggest you not allow this as i almost filed a report about something not working but it was because the action was assigned to the same key as another action

**Comment by martinrotter** [comment]
Put issues which are related to labels functionality here.

**Comment by martinrotter** [comment]
> not sure if i should put issues i find in general issues or here given this is alpha code. in key assignment i can assign a key to 2 different things without knwoing. i'd suggest you not allow this as i almost filed a report about something not working but it was because the action was assigned to the same key as another action

Yes, you can assign single keyboard shortcut to multiple actions - this is a bug - file new ticket for it please because it is not related to labels feature...

**Comment by martinrotter** [comment]
> web browser and tabs/wen engine settings. for each item you want to check/uncheck, when you do the flyout closes. so you have to click the web browser and tabs and then web engine settings again for each web browser option. the local content/local files creates a back door to access files and possible send, depending on the exact details of the implementation and strength of the sandbox. but since this is a browser for looking at feed content i'd think for security you'd want this off by default.
> 
> btw, there is a checkbox for "plugins enabled". what plugins? there is just adblock which isn't controlled by this, right?

Yes, create ticket for these suggestions, I will look into it later.

By "plugins" in this context we mean "webengine plugins" which are plugins written specifically for webengine component by 3rd-parties and they have to be probably installed separately. AFAIK there are at this point no specific plugins available - the only one available is Pepper Flash plugin - https://wiki.debian.org/PepperFlashPlayer - which must be downloaded/compiled by hand. Practically, the option use useless in RSS Guard.

**Comment by pcause** [comment]
got a build,  432f63a, and the sorting of messages by feed seems to be case sensitive.  thought you'd changed that per a previous issue i filed

**Comment by pcause** [comment]
using 432f63a i went through all my labels and marked read.  had opened a number of articles in the internal browser,  was reading each in it tab, and while clicking on one the app crashed.    btw, looks like when i marked articles read in a label the read status synced back.  didn't get a chance to fully check because of crash.

BTW, open tabs not remembered after crash/restart

**Comment by martinrotter** [comment]
> btw, looks like when i marked articles read in a label the read status synced back
Impossible, code for that is not yet written.

> reading each in it tab, and while clicking on one the app crashed
Possible, currently, the state of the app is little fragile. Will work on stabilizing new features and adding sync for it tomorrow. It will take some weeks to get everything into good shape, but then RSS Guard will have probably all main features one would expect from RSS reader.

**Comment by pcause** [comment]
here is the screen shot from the crash i reported earlier

![image](https://user-images.githubusercontent.com/1071479/96770079-8bd3be80-13cf-11eb-9320-e550981391cc.png)

**Comment by martinrotter** [comment]
@pcause OK, TT-RSS plugin now supports syncing "labels" with revision b1de49fb. So please try this:
1. Get latest revision build.
2. Perform "sync-in" for your TT-RSS account in RSS Guard.
3. Display some message and click on label in its preview sub-window.
4. Wait one minute.
5. Check in TT-RSS web interface if label was assigned/removed/etc.

**Comment by pcause** [comment]
worked to add label and remove   using  b1de49f

**Comment by pcause** [comment]
not sure if i should file as issue so putting here.

downloaded the 3.8 version.  i had updated yesterday and left a bunch of articles in rssguard unread.  i download unread only.  when i loaded this this morning and updated there are more articles unread by a lot than server and some that are read on server are shown as unread in rssguard.  i know you can't get a changed since type update from the tt-rss api.  i thought you'd get the id's of unread articles you have locally and then any that aren't in the unread article update list from the server would be marked as read locally.  so the logic would be:

- get unread ids from database.  keep in memory or temporary table
- use tt-rss api to get unread articles.  remember ids.
- for ids not in list of fetched id's but in list of articles from first step, mark read.

the only issue is that if an article is changed on server (starred/labeled) you can miss the change for local.  but you can fetch the starred feed and see what has changed and also the labels feeds.  even without that it is no worse than what happens when i set fetch unread only right now.  my problem is that i have 150+ feeds and keep 30-45 days history so a full sync would be really slow.

**Comment by martinrotter** [comment]
@pcause 

RSS Guard (if not bugged) should do this, regarding syncing messages:
1. If you mark message read/unread/starred/unstarred in RSS Guard, then **all** these changes will get synced back to server in **ONE MINUTE**.
2. If message's state gets changed ON the server (for example you mark it starred via web interface), then after feed gets updated in RSS Guard, these new states will get downloaded and will overwrite local state.

But, if you have "only unread" messages enabled to be downloaded, then of course if your message is read, then it will not be downloaded at all by RSS Guard, therefore changes made ON the server will not be propagated back to you.¨

There is could be a way to solve this problem with message filters. You could simply uncheck the "Download only unread..." checkbox, let RSS Guard download all messages and then setup message filter to somehow check if you need those particular *read* messages.

**Comment by martinrotter** [comment]
OK, working on labels availability in message filtering subsystem. Looks promising. For now, labels are available in **read-only** manner in `assignedLabel` property of `msg` object. Each `Label` offers these properties: `title` (title of label), `customId` ("ID" of label as stated in respective API), `color` (foreground color of the Label).

Here is example if message filter script which utilises assigned labels:

```js
function filterMessage() {
  var labels = msg.assignedLabels;

  console.log("Message '" + msg.title + "' has " + labels.length + " labels.");

  for (index = 0; index < labels.length; ++index) {
    console.log("We have label '" + labels[index].title + "' and with ID '" + labels[index].customId + "'.");
  }

  return 1;
}
```

Here is sample RSS Guard console output, performed by the above script, which just prints out information about assigned labels to just downloaded messages (pay special attention to last lines of this log output):
```ini
time="   299.573" type="debug" -> Message 'Server Upgrade 2020-10-12' has 0 labels.
time="   299.575" type="debug" -> Message 'First Lighting Payment 20200925' has 0 labels.
time="   299.577" type="debug" -> Message 'Happy Third Birthday!' has 0 labels.
time="   299.578" type="debug" -> Message 'Instagram Bridge Fix 20200817' has 0 labels.
time="   299.580" type="debug" -> Message 'Twitter Bridge Interruptions 20200724' has 0 labels.
time="   299.582" type="debug" -> Message 'Newsboat' has 0 labels.
time="   299.584" type="debug" -> Message 'Instagram bridge issues 20200627' has 0 labels.
time="   299.586" type="debug" -> Message 'Twitter Bridge Broken 20200602' has 0 labels.
time="   299.588" type="debug" -> Message 'Plugin: Force Article to the Top' has 0 labels.
time="   299.590" type="debug" -> Message 'tt-rss-feedly-theme v2.5.0' has 2 labels.
time="   299.590" type="debug" -> We have label 'Label1' and with ID '-1071'.
time="   299.590" type="debug" -> We have label 'Label2' and with ID '-1072'.
```

**Comment by pcause** [comment]
awesome progress.  will pay with this later today.

**Comment by martinrotter** [comment]
At this point, I believe that the ticket is almost ready, of course I will give it a week or two for testing and also will fix some other tickets, optimize it a bit and 3.8.0 can be released.

**Comment by pcause** [comment]
does setting tags in filters work?

**Comment by martinrotter** [comment]
At this point, no. The array of labels is read-only. Is setting of labels really needed?

**Comment by pcause** [comment]
no, guess not as i filter at server. i have some use cases where it would be helpful.  right click to set/remove a label/labels to a selected set of items is needed more.

**Comment by martinrotter** [comment]
@pcause Working on it: 
![image](https://user-images.githubusercontent.com/1255302/97563754-cb0f9a00-19e3-11eb-9400-486c881775e3.png)

I need to support "tri-state" checkboxes in that menu (assigned to all messages, assigned to only some messages, unassigned) and as there are some problems with GUI library and "native" tri-state checkboxes I decided to draw "checkboxes" with colored little rectangles: green rectangle (label is assigned currently to all selected messages), orange rectangle (label is assigned only to some assigned messages), no rectangle (label is not assigned to any messages).

**Comment by martinrotter** [comment]
@pcause OK, in latest commit, this menu can now also change labels! Pls test. I will eventually add also ability to (de)assign labels from withing message filters, but will add this in some future versions.

**Comment by pcause** [comment]
sorry was away from pc and only on mobile.  will test today/tomorrow and give feedback

**Comment by martinrotter** [comment]
@pcause and others, can you please verify, that so far implemented labels functionality works OK? I plan to release 3.8.0 soon.

**Comment by pcause** [comment]
sorry to be late.  things seem to be working.  i also did a filter on a category where i marked items read is labels.length == 0 and that worked and synced back.  could right click and add label.  unset label in the internal browser.  

also thanks for fixing internal browser tab display.

**Comment by pcause** [comment]
btw, the filters test doesn't include labels.  can be useful to allow user to define labels to be added to test so they cna test filters that use labels and label values.  could be in a future release.

**Comment by martinrotter** [comment]
@pcause Working on assigning/removing labels via filters:

```
time="    31.594" type="debug" -> feed-downloader: Running filter script, it took 1435 microseconds.
time="    31.594" type="debug" -> feed-downloader: Hooking message took 5 microseconds.
time="    31.595" type="debug" -> Number of assigned labels 0
time="    31.595" type="debug" -> Number of available labels 2
time="    31.595" type="debug" -> First available label ID user/1006517989/label/Test 1
time="    31.595" type="debug" -> Assigning this label to message...
time="    31.595" type="debug" -> Number of assigned labels 1
time="    31.595" type="debug" -> feed-downloader: Running filter script, it took 860 microseconds.
time="    31.595" type="debug" -> feed-downloader: Hooking message took 5 microseconds.
time="    31.596" type="debug" -> Number of assigned labels 0
time="    31.596" type="debug" -> Number of available labels 2
time="    31.596" type="debug" -> First available label ID user/1006517989/label/Test 1
time="    31.596" type="debug" -> Assigning this label to message...
time="    31.596" type="debug" -> Number of assigned labels 1
time="    31.596" type="debug" -> feed-downloader: Running filter script, it took 820 microseconds.
time="    31.596" type="debug" -> feed-downloader: Hooking message took 5 microseconds.
time="    31.596" type="debug" -> Number of assigned labels 0
time="    31.597" type="debug" -> Number of available labels 2
time="    31.597" type="debug" -> First available label ID user/1006517989/label/Test 1
time="    31.597" type="debug" -> Assigning this label to message...
time="    31.597" type="debug" -> Number of assigned labels 1
```

Not yet synced back, implementing rn. Will update documentation when done.

**Comment by martinrotter** [comment]
OK, labels can now be assigned or DEassigned via message filters.

6fc590a7

I will enhance documentation and write relevant info here.

**Comment by martinrotter** [comment]
OK, documentation now includes complete JavaScript API for Message and Label objects.

https://github.com/martinrotter/rssguard/blob/master/resources/docs/Message-filters.md#api-reference
