### ISSUE TITLE
[FR]: Read a full article directly by clicking on a single button

### ISSUE THREAD

**Issue by Cronos-lab** [martinrotter/rssguard#1021]
### Brief description of the feature request

Hello,

I'm reopening the subject of this possible improvement.

The idea would be to press a single button to read the article in reading mode without an external browser. The software could fetch the text as in the Feeder application (Android).

Example :
https://s.42l.fr/Feeder-example

App Feeder, available here:
https://f-droid.org/en/packages/com.nononsenseapps.feeder/

In this application, there is a function to read the article directly in the application and the application loads the text from the site. Just by pressing only one button ! It's a pleasure to read.

We have already discussed about this problem here:
https://github.com/martinrotter/rssguard/issues/916

Thank you

**Comment by martinrotter** [comment]
Well. How exactly and what exactly the feature does?

It simply downloads WHOLE (?) webpage linked from article preview? Or also applies some kind of "reader mode" HTML enhancements?

As written before, there is "reader mode" available which simply does that you provide it some HTML webpage and it returns the same webpage but with nicer formatting for reading.

So hyphotethically, you select your article from list of articles and article preview displays. Then you hit your "key" and what exactly should happen now?

**Comment by martinrotter** [comment]
Done.
