### ISSUE TITLE
[BUG]: Critical error trying to delete probe

### ISSUE THREAD

**Issue by slalaurette** [martinrotter/rssguard#1028]
### Brief description of the issue

I have created a bunch of article probes. When trying to delete any of them, I get this error: 

"This item cannot be deleted because something critically failed." 

### How to reproduce the bug?

1. Create a probe.
2. Press Del to delete the probe.
3. When the dialog appears, click "Yes". 

### What was the expected result?

I expected the probe to be deleted. 

### What actually happened?

I got a critical error and the probe was not deleted. 

### Debug log

time="113306.474" type="debug" -> database: SQLite connection 'Search' is already active.
time="113306.474" type="debug" -> database: SQLite database connection 'Search' to file 'C:/bin/inet/RSSGuard/data4/database/database.db' seems to be established.
time="113306.474" type="debug" -> core: Filter accepts row 'Recycle bin' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row 'Important articles' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row 'Unread articles' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row 'Labels' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row 'Article probes' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row 'Noticias' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row 'Escribamos' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row 'Lecturillas' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row 'Pensadores' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row 'Palabristas' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row 'Pentagramas' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row 'Maravillas' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row 'Celuloide' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row 'QuiteRSS' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row 'Sebastian (RSS/ATOM/JSON)' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0A 80 Avellaneda' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row 'Kirchner' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row 'Brown' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row 'test' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0 -- PICANTES' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0A 22 Alberti' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '3 -- STANDARD' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '2 -- MEDIUM' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '1E 55 Escobar' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '1A 10 Almirante Brown' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '1 -- PREMIUM' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0Z 11 Zárate' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0V 11 Villa Gesell' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0T 22 Tres Arroyos' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0T 11 Tandil' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0S 55 San Vicente' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0S 44 San Nicolás' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0S 33 San Miguel' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0S 22 San Cayetano' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0S 11 Salliqueló' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0S 00 Saavedra' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0R 55 Rauch' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0P 57 Punta Indio' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0P 55 Punta Alta' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0P 44 Presidente Perón' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0P 33 Pinamar' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0P 22 Pila' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0O 55 Olavarría' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0N 55 Nueve de Julio' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0M 66 Moreno' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0M 55 Monte Hermoso' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0M 50 Monte' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0M 44 Mercedes' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0M 33 Mar Chiquita' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0M 22 Maipú' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0M 11 Magdalena' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0L 44 Lobos' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0L 40 Lobería' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0L 33 Lincoln' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0L 22 Las Flores' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0L 11 La Plata' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0J 77 Junín' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0H 50 Hurlingham' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0G 30 General La Madrid' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0G 20 General Belgrano' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0G 10 General Arenales' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0F 10 Florentino Ameghino' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0E 90 Ezeiza' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0E 50 Ensenada' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0C 90 Coronel Pringles' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0C 80 Coronel Dorrego' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0C 70 Chascomús' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0C 66 Carmen de Patagones' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0C 60 Capitán Sarmiento' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0C 30 Campana' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0B 66 Brandsen' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0B 60 Bragado' and filter result is: 'true'.
time="113306.474" type="debug" -> core: Filter accepts row '0B 33 Berisso' and filter result is: 'true'.
time="113306.475" type="debug" -> core: Filter accepts row '0B 11 Baradero' and filter result is: 'true'.
time="113306.475" type="debug" -> core: Filter accepts row '0A 90 Azul' and filter result is: 'true'.
time="113306.475" type="debug" -> core: Filter accepts row '0A 88 Ayacucho' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row 'Nacionales' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row 'La región' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row 'La provincia' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row 'Insólitas' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row 'Alertas' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row 'Agendas particulares' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row 'Télam' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row 'elDiarioAR' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row 'Política y Medios' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row 'Periodismo y Punto' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row 'Identidad Colectiva' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row '
	Comentarios en: Rosenkrantz giró 650 mil dólares a EE UU al día siguiente de las PASO	' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row 'Tiempo Judicial' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row 'InfoBerisso' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row 'El Correo Gráfico' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row 'INFOLAPLATA' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row 'Radio Universidad' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row 'Oeste Platense' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row 'El Editor Platense' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row 'Diario El Dia - RSS' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row '0221.com.ar' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row 'Info Blanco Sobre Negro' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row 'VIVE La Plata' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row 'Municipalidad de Berisso' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row 'Diagonales' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row 'El Observador Informativo' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row 'Últimas Noticias de Info360>' and filter result is: 'true'.
time="113306.501" type="debug" -> core: Filter accepts row 'El Mundo de Berisso' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Pulso noticias' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Diario Full' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row '1ª sección' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row '2ª sección' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row '3ª sección' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row '4ª sección' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row '5ª sección' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row '6ª sección' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row '7ª sección' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Ultimas' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Diarios Bonaerenses' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Primera Plana' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Noticias de Municipales | Grupo La Provincia' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Municipios' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Impulsobaires' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'InfoBaires24' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'La Noticia Web' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'El Intransigente' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'BUENOS AIRES IMPACTO - NOTICIAS Y OPINION - WSP 5491169991968' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'El Bonaerense – Zona Norte' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Agencia NOVA' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'InfoMiBA Â» Municipios' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'InfoBAN Â» Municipios' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'INFO135' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'INFOZONA' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Provincia Noticias' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Todo Provincial' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'IntendenciasBA' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Tres LÃ­neas' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Cronos' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Diputados Bonaerenses' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'NQP -- Buenos Aires' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'ANDigital' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'dataconurbano.net' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Últimas Noticias de Buenos Aires Noticia>' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'El Teclado' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Andar' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Agencia Comunas' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Friki' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Alerta de Google - "Agustín Maspoli"' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Alerta de Google - "Anahí Bilbao"' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Alerta de Google - "Avelino Zurro"' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Alerta de Google - "Eugenia Brizzi"' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'ContrahegemoniaWeb' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Nota al Pie | Noticias en contexto' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Concursos por email' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Goins, Writer' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Concursos Literarios - Escritores.org' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'The Rejecter' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Cronoelipsis' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'WRITER on WRITING' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Premios literarios - Estandarte ' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Revista Cinosargo' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Buenos Aires Poetry' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Las lecturas de Guillermo' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row '.qualquier buenos aires' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'El jinete insomne' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Lecturia' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Vomité un Conejito' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'DESERTOR POR ESCRITO' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'A ver Richard...' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'kalais' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'lamicrobiblioteca' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Bitácora de (mis) lecturas' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'kalais          un retroblog marplatense' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Los demasiados libros de Jula' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'POETAS SIGLO XXI - ANTOLOGIA MUNDIAL + 20.000 POETAS: Editor: Fernando Sabido Sánchez #Poesía ' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'SFFaudio' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Solo Tempestad' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Astral Codex Ten' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Stories by Abril Chantal Collada on Medium' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Slate Star Codex' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'La Tecl@ Eñe Revista' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Seúl' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Rolando Astarita [Blog]' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'El blog de Subjuntivo' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'La lectora provisoria' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'NotiAR' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Rebelion' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'n+1Articles – n+1' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Relato del Presente' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Attack of the 50 Foot Blockchain' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Verbosa Mudez' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'PAULA MARTINI' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Caramelos de Violetas' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Fingertips' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Escuela de Rock' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Albums That Never Were' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'The Dictionary of Obscure Sorrows' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Open Culture' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'I have seen the whole of the internet' and filter result is: 'true'.
time="113306.502" type="debug" -> core: Filter accepts row 'Cinefilia Malversa (blog sin fines de lucro)' and filter result is: 'true'.

### Operating system and version

* OS: Windows 10
* RSS Guard version: 4.4.1

**Comment by martinrotter** [comment]
Yes, probe feature is not finished yet, wip.

Does the feature actually work except deleting now for you?

**Comment by slalaurette** [comment]
I thought about that after sending the report, because I couldn't find it in the documentation! I was eager to try it because they are a much more straightforward way to classify articles the way I need, instead of filters, like I was trying before. 

The other thing that happens is that probes aren't actually permanent as the legend says; they disappear as soon as I restart RSS Guard.

**Comment by martinrotter** [comment]
Yes that part of feature is not implemented yet too
