### ISSUE TITLE
[FR]: Looking for help to create a filter

### ISSUE THREAD

**Issue by ghost** [martinrotter/rssguard#1029]
### Brief description of the feature request

Greetings. I must ask for help to create a filter, since I don't know programming and with chatgpt I can't do much.
I'm trying to create a pseudo-blacklist that accepts all content, but marks as read those articles with keywords (so far so good) and applies a tag to them (I can't get there). Could someone do me a favor and give me a functional example?

PS: I'm not clear if this will even get any attention, but in case anyone else in my situation ended up here and is interested in my current filter (apparently functional), I'm leaving it down here:

```
var blacklist = ['abc', '123'];

function filterMessage() {
  if (blacklist.some(i => msg.title.indexOf(i) != -1)) {
    msg.isRead = true;
    return MessageObject.Accept;
  } else {
    return MessageObject.Accept;
  }
}
```

**Comment by martinrotter** [comment]
Hi:
1. Create sample label "Test".
2. Use this sample filter:
```js
var blacklist = ['Escape', 'Car'];

function filterMessage() {
  if (blacklist.some(i => msg.title.indexOf(i) != -1)) {
    msg.isRead = true;

    var lbl = msg.findLabelId("Test");
    msg.assignLabel(lbl);
  }

  return MessageObject.Accept;
}
```

![image](https://github.com/martinrotter/rssguard/assets/1255302/346ba333-6ff9-4b0e-845f-00d3abf16fd6)
