### ISSUE TITLE
[FR]: Contidional removal of old articles

### ISSUE THREAD

**Issue by wimverbruggen** [martinrotter/rssguard#1035]
### Brief description of the feature request

I would find it useful to (automatically) remove all articles older than 14 days **if** they are not marked as important or have any labels assigned. Would that work by implementing an article filter? If so, do you have any tips on how to do that? Maybe something like the following semi-pseudo-code? Thanks!

```
function filterMessage() {

  if( ! ( msg.isImportant() | length(msg.assignedLabels()) > 0 ) & msg.created > "14 days") {
      msg.isDeleted();
  }

}
```

**Comment by martinrotter** [comment]
Hi, sure. Note that this article filter must be run manually from "Article filters" dialog. Create the filter and check the feeds you want to executed, then run "Process checked feeds" and thats it. The article filter below does actually really "REMOVE" the articles from RSS Guard database. If you want to move them to recycle bin and mark as read, then the filter would have to be tweaked.

```js
function filterMessage() {
  var d = new Date();
  d.setDate(d.getDate() - 14);

  if (!msg.isImportant && msg.assignedLabels.length == 0 && msg.created < d) {
    return MessageObject.Purge;
  }
  else {
    return MessageObject.Accept;
  }
}
```

**Comment by wimverbruggen** [comment]
Perfect, thanks so much! I adapted the code to move them to the recycle bin instead, in case anyone ends up here with a similar question:

```
function filterMessage() {
  var d = new Date();
  d.setDate(d.getDate() - 14);

  if (!msg.isImportant && msg.assignedLabels.length == 0 && msg.created < d) {
    msg.isDeleted = 1; 
  }
  return MessageObject.Accept;
}
```
