### ISSUE TITLE
[FR]: Option to separately set sorting criteria for "important" & "non-important" articles

### ISSUE THREAD

**Issue by RetroAbstract** [martinrotter/rssguard#1039]
### Brief description of the feature request

This would allow the user to separately set a sorting criteria (Title, Feed, Date..) for "important" and "non-important" articles.

The desired outcome of this in my use case is to have all important articles sorted by date at the top of the article list (most recent to oldest), then all the other "non-important" articles (also sorted by date (most recent to oldest)) below the oldest "important" article.

Currently you can have this setup by first sorting articles by date, then sorting by importance. However when restarting or quitting RSS Guard, when it opens again it forgets the sorting mode set prior to sorting the articles by importance and defaults to sorting the "non-important" articles in a scattered manner (mix of sorting by feed, title, date all at the same time). The important articles are still sorted the way they were before restarting/quitting RSS Guard.

You can see what I mean by the "non-important" articles sorted in a scattered manner by doing as I mentioned above:

1. Sort articles by date (most recent to oldest)
2. Sort articles by importance (most recent to oldest)
3. Restarting / quitting & re-opening RSS Guard
4. Notice how all "non-important" articles are sorted in a scattered & inconsistent manner

Hesitated between a FR or a bug report for this, but given that this is not an official feature, I went with FR.

Thanks

**Comment by martinrotter** [comment]
> Currently you can have this setup by first sorting articles by date, then sorting by importance. However when restarting or quitting RSS Guard, when it opens again it forgets the sorting mode 

RSS Guard has what I call "multi-column sorting" feature for article list. Sadly, you discovered the bug that only the "last" sorting mode is remembered, not all of them. I will fix that.
