### ISSUE TITLE
Atom parsing

### ISSUE THREAD

**Issue by Cj-Malone** [martinrotter/rssguard#104]
You seem to [prioritise](https://github.com/martinrotter/rssguard/blob/master/src/core/parsingfactory.cpp#L46) `summary` over `content`. I think that should be the other way around.

The [last](https://github.com/martinrotter/rssguard/blob/master/src/core/parsingfactory.cpp#L82) link (that isn't rel=enclosure) is set as the URL, really that should be picking a link with rel=alternate (or null as alternate is default) and if there is multiple rel=alternate it should be the type=text/html

If the feed > entry > author is [null](https://github.com/martinrotter/rssguard/blob/master/src/core/parsingfactory.cpp#L105) you should fall back on feed > author, note there can be multiple authors so you should also be appending them.

**Comment by martinrotter** [comment]
That parsing is rather basic. This is all true, you wrote. :) I will enhance it hopefully soon. Maybe you can create some PR?

**Comment by martinrotter** [comment]
Fixed with https://github.com/martinrotter/rssguard/commit/95a583142460adcd60d04e09e02026fb31da96ef.
