### ISSUE TITLE
[BUG]: PC loads slow. I googled a solution and found that RssGuard is causing excessive 'Page Faults'

### ISSUE THREAD

**Issue by Starboy-Xo** [martinrotter/rssguard#1041]
### Brief description of the issue

My PC has been starting very slow at the start. It takes at least 5-7 minutes to load the desktop completely. So, I decided to check the usage of memory as well as CPU and found that they are working fine and are at a nominal level. I tried to google a solution for it and found out the following link:
[https://superuser.com/questions/1077801/my-windows-10-pc-got-really-slow-although-cpu-and-memory-usage-is-fine-what-els](url) and applied a solution from link, which is as follows:

> I had the same problem but the solution was different. My CPU, Memory usage and everything looked normal but it seems my system had high page faults which was slowing down the entire system. To check if this is a problem in your system
> 
> Start->Run->perfmon
> 
> Select "Performance monitor" and click on "Add a counter" (+ button)
> 
> In the list of counters shown, locate and expand Menory and select the "Page faults" counter
> 
> Watch the performance monitor to see if the page faults are high. In my case it was at 100 always
> 
> If you have confirmed that you have high page faults, now we need to find out which application is causing it. Follow the below listed steps.
> 
> Search google for "ProcessExplorer" from SysInternals.
> 
> Download ProcessExplorer and run as administrator
> 
> Under the "View" menu click on "Select Columnns"
> 
> Click on the "Process Memory" tab.
> 
> Enable "Page Faults" and click OK.
> 
> Now you will see the "Page Faults" column. Sort it in descending order. You will find out which one is causing high page faults. If it is a user installed application try uninstalling and re-installing it.
> 
> In my case, it was "KasperSky". My license got expired and I renewed it from the KasperSky app. Guess something got messed up with that. I uninstalled and re-installed KasperSky and my system was back to normal!

By following these instructions in the link, i found some frightening results regarding RSS Guard and Desktop Ticker. Which are attached in the picture below:
![image](https://github.com/martinrotter/rssguard/assets/15247707/3739660e-596f-4705-81d8-354e3e3ef31c)

It turns out that the RSS Guard is causing (generating or however it might be attributed to) page faults to ``8,375,000``.

### It should be noted that i applied the same instructions to my brother's PC and found that ``HP Support Assistant`` was causing more than ``2,000,000`` page faults. Soon as i uninstalled it, the PC started loading faster.

So, should we be concerned about RSSGuard Page Faults here?

### How to reproduce the bug?

> Start->Run->perfmon
> 
> Select "Performance monitor" and click on "Add a counter" (+ button)
> 
> In the list of counters shown, locate and expand Menory and select the "Page faults" counter
> 
> Watch the performance monitor to see if the page faults are high. In my case it was at 100 always
> 
> If you have confirmed that you have high page faults, now we need to find out which application is causing it. Follow the below listed steps.
> 
> Search google for "ProcessExplorer" from SysInternals.
> 
> Download ProcessExplorer and run as administrator
> 
> Under the "View" menu click on "Select Columnns"
> 
> Click on the "Process Memory" tab.
> 
> Enable "Page Faults" and click OK.
> 
> Now you will see the "Page Faults" column. Sort it in descending order. You will find out which one is causing high page faults. If it is a user installed application try uninstalling and re-installing it.
> 

### What was the expected result?

Load the desktop and desktop apps faster

### What actually happened?

Slowing down the loading of desktop application.

### Debug log

NULL. I think this issue doesn't concern it. Can be furnished on demand.

### Operating system and version

* OS: WIN 10
* RSS Guard version: 4.4.0

**Comment by Starboy-Xo** [comment]
RSS Guard version: 4.3.4 was doing the same which i just updated

**Comment by Starboy-Xo** [comment]
### After 15 hours of uptime out of which 8 hours of idling.
![image](https://github.com/martinrotter/rssguard/assets/15247707/a9e7f2ea-d0b7-47dc-b5cb-b75804c0ee2d)

**Comment by martinrotter** [comment]
Hi, well, this seems kind of weird. I do not explicitly call any C++ code which could do this but yes I use process-explorer too, so tested it and indeed page-faults are huge number.

That said, I do not really see any performance problems in RSS Guard and I of course use it like crazy every day. Also, it does not seem that performance problems are reported by other users.

I guess you use "-win10-" variant of RSS Guard. Can you install "-win7-" variant and re-test? You can keep your data, those variants are fully interchangeable. Also, perhaps try "-nowebengine-" subvariants? Test and check if your performance and/or page fault counts changes?

**Comment by Starboy-Xo** [comment]
i couldn't find Win7 variant with web engine. However, i used nowebengine. It has been 2 hours and this is how it looks:
## on start
![image](https://github.com/martinrotter/rssguard/assets/15247707/59be367a-070e-49fc-bef4-d71e53cb5764)

## At this moment
![image](https://github.com/martinrotter/rssguard/assets/15247707/e34b754c-f78a-401c-a317-b62f527b5503)

### I am also mentioning Quite RSS as a referential note for you to see that page faults seems to be handled more optimally by it. 
However, the page faults on RSS Feed application called Desktop Ticker by Battware is also concerning. Which is also concerning.
![image](https://github.com/martinrotter/rssguard/assets/15247707/046029af-f4a4-4c29-816d-2b82263fdb3c)

I wish that we had Desktop ticker system in RSSGuard too.
I also wish that we had proper notification system as in Quite RSS in RSSGuard too.

Regards,

**Comment by martinrotter** [comment]
So the issue is clearly connected to webengine component

**Comment by Starboy-Xo** [comment]
Yeah

**Comment by martinrotter** [comment]
Try the release you normally use and disable cookies in settings

**Comment by Starboy-Xo** [comment]
These results are literally under 15 seconds after launching the normal win10 version
##  At start
![image](https://github.com/martinrotter/rssguard/assets/15247707/e0b5e1a1-66fe-4649-83fd-11572fd2dc33)

## At 10-15 seconds
![image](https://github.com/martinrotter/rssguard/assets/15247707/600d3575-9965-4dc6-b556-1c20c0251a10)

## at this very exact moment
![image](https://github.com/martinrotter/rssguard/assets/15247707/40d658bf-ea56-426c-ab79-544f23f128fd)

**Comment by martinrotter** [comment]
So it does not seem to be connected to cookies

**Comment by Starboy-Xo** [comment]
Yeah

**Comment by martinrotter** [comment]
https://bugreports.qt.io/browse/QTBUG-115820

**Comment by Starboy-Xo** [comment]
I meant that the desktop loads slow. All applications become clickable right after the mentioned time, including start button. 
I am using 10 GB ram, i3. - 3.40 GHZ

The desktop loading time is affected drastically when page faults are high. As i mentioned about my brother's pc, quoting it below:
> It should be noted that i applied the same instructions to my brother's PC and found that HP Support Assistant was causing more than 2,000,000 page faults. Soon as i uninstalled it, the PC started loading faster.

Similarly, the RSSGuard was showing the same pattern, after using the nowebengine, i realized that the pc has started working much quciker.

**Comment by martinrotter** [comment]
Yes. Well, I myself have no idea what/how to fix this and if it even fixable, therefore I filed upstream bug report as it is clearly something to do with WebEngine (Chromium) component.

**Comment by Starboy-Xo** [comment]
Yeah, i will track the bug too there

**Comment by Starboy-Xo** [comment]
Chat GPT produces a list of potential reasons regarding Page Faults.

![image](https://github.com/martinrotter/rssguard/assets/15247707/f9cc992d-2146-4f8a-9fdb-ab06e90cd088)

They seem logical.

Pasting them below only for a read:

Excessive "page faults" in a Microsoft Windows application can lead to degraded performance and responsiveness. Page faults occur when a process tries to access memory that is currently not in physical RAM and needs to be fetched from the paging file on disk. Several factors can contribute to excessive page faults:
1.	Insufficient Physical RAM: When the physical RAM (Random Access Memory) is inadequate to accommodate the working set of active processes, the system will need to swap data between RAM and the paging file more frequently, causing page faults.
2.	High Memory Usage: If the application and/or the operating system itself consume a large amount of memory, there may not be enough free physical memory available to keep frequently accessed data in RAM, leading to more page faults.
3.	Memory Fragmentation: Memory fragmentation can cause the physical memory to be scattered in small, non-contiguous blocks. This can result in inefficient use of available RAM and potentially lead to more page faults.
4.	Memory Leaks: If an application has memory leaks, it can gradually consume more and more memory over time, increasing the likelihood of page faults as the available memory becomes exhausted.
5.	Demand Paging: Demand paging is a memory management technique where only the required portions of a program are loaded into memory. If an application has a large working set, it may lead to frequent page faults as different parts of the program are loaded on-demand.
6.	Multi-tasking and Context Switching: In a multitasking environment, where multiple processes are running concurrently, frequent context switching between processes can cause their working sets to be frequently swapped in and out of memory, resulting in more page faults.
7.	Disk I/O Bottlenecks: Slow disk I/O operations, either due to a slow hard drive or high disk activity from other processes, can lead to delays in loading data from the paging file, causing an increase in page faults.
8.	Virtual Memory Configuration: Incorrect or suboptimal virtual memory settings can impact page fault behavior. If the size of the paging file is too small or not properly managed, it can contribute to excessive page faults.
9.	Anti-Virus and Security Software: Some security software can perform real-time scanning of files, which may result in increased disk activity and potential page faults when accessing files.
10.	Large Data Sets: Applications dealing with large data sets that exceed the available physical memory can experience frequent page faults as they try to access data that is not currently in RAM.
11.	Network Activity: Applications that rely heavily on network communication might experience more page faults if they spend a significant amount of time waiting for data to arrive over the network.

To address excessive page faults, consider optimizing memory usage, upgrading physical RAM, addressing memory leaks, optimizing virtual memory settings, minimizing unnecessary multitasking, and improving disk performance. Profiling tools and performance monitoring utilities can help identify the specific causes of excessive page faults in a given scenario.

**Comment by martinrotter** [comment]
Well, the issue was responded by Qt devs in upsteram bug report and I agree with them. Page faults themselves are not directly cause by programmer error etc.

Problem is that QtWebEngine module (Chromium-based) is very RAM hungry and writes/reads RAM VERY OFTEN, resulting in frequent page faults.

If this is somehow problem for you, then perhaps switch to "nowebengine" version. At this point there is nothing I can do as this is not really "bug" in the RSS Guard source code base. If someone pinpoints some exact cause of this in code, then I would be happy to fix.
