### ISSUE TITLE
[FR]: Image wrapping for simple text-based article viewer

### ISSUE THREAD

**Issue by RetroAbstract** [martinrotter/rssguard#1046]
### Brief description of the feature request

This feature would make images wrap in the simple text-based article viewer the NoWebEngine builds have like they do in the WebEngine article viewer.

As shown in the screenshots below, images wrap nicely in the WebEngine article viewer, compared to how they clip in the simple text-based article viewer:

### WebEngine wrapping
![1](https://github.com/martinrotter/rssguard/assets/103272301/2e583db8-40fc-447e-817e-9bc41a05a5a8)
![2](https://github.com/martinrotter/rssguard/assets/103272301/de713fa0-a82a-4dde-97fe-b2de7ab3a32a)

### Simple text-based clipping

![3](https://github.com/martinrotter/rssguard/assets/103272301/8fb96068-c021-43d0-8660-3ec40812a00d)
![4](https://github.com/martinrotter/rssguard/assets/103272301/46197fe2-473a-4518-adc2-62135c91d536)

Side-note: URLs of image enclosures also do not wrap in the simple text-based article viewer as of now.

Thanks

**Comment by martinrotter** [comment]
This might be fixed by 1557bc9ff.
