### ISSUE TITLE
[FR]: Localization UI additions

### ISSUE THREAD

**Issue by RetroAbstract** [martinrotter/rssguard#1047]
### Brief description of the feature request

As first suggested by @RonnyTNL, these additions would let users whom set their RSS Guard to incompletely translated languages know that they can help translate by going to the [RSS Guard Transifex page](https://app.transifex.com/martinrotter/rssguard) by:

- 1: Adding a prompt everytime a user applies an incompletely translated language that would look something like this:

![1](https://github.com/martinrotter/rssguard/assets/103272301/e40c48fb-d338-477c-82cb-6b3cf6908bbd)

This new prompt would appear before the already existing prompt to restart after applying a new language:

![2](https://github.com/martinrotter/rssguard/assets/103272301/10892f59-ca3b-4b76-bb26-d0b942abebcd)

- 2: Adding a clickable line in the Localization menu, would look something like this:

![3](https://github.com/martinrotter/rssguard/assets/103272301/f13a470b-324d-4737-8491-461d5ffe1a8f)

- 3: Adding a "Translated" list between the already existing "Code" and "Author" lists which would display the percentage of how much each language has been translated.

The percentages aspect of addition 1 & 2 depend on if it's possible to keep them synced with Transifex. 
If not, then simply not including "[LANG_NAME] is X% translated" in addition 1 and scrapping addition 3 altogether would do fine. 

Thanks

**Comment by martinrotter** [comment]
added the label, as for percentages warning, that is technically possible but seems like a too much work for this type of feature

if any users want to have fuller localizations, there are already links in documentation, in contributing.md file and can ask in disussions or here or on discord any time
