### ISSUE TITLE
[BUG]: RSS Guard forgets view settings

### ISSUE THREAD

**Issue by slalaurette** [martinrotter/rssguard#1048]
### Brief description of the issue

Upon restarting RSS Guard (latest dev build), all view settings are forgotten, and the title column ends up being too narrow so every item occupies a lot of space. See screenshot. 

![clip_20230810_18 09 21](https://github.com/martinrotter/rssguard/assets/12722382/4f938e66-da94-443a-a95f-bb3925e9c329)

### How to reproduce the bug?

1. Start RSS Guard.
2. Configure your view settings: disable the "Read", "Author" and "Assigned label IDs" columns, and drag the "Important" column border until it's just right to display the icon.
3. Keep using RSS Guard normally.
4. Close and restart RSS Guard.

### What was the expected result?

I expected my changes to be kept.

### What actually happened?

All default columns appear again, with the "Important" column being too wide and the "Title" column being too narrow.

### Debug log

(partially cut because it was too long to post)

time="    15.071" type="debug" -> gui: Message list got focus with reason 'Qt::MouseFocusReason'.
time="    15.072" type="debug" -> gui: Current row changed - proxy 'QModelIndex(1,2,0x11b2c63a920,MessagesProxyModel(0x11b27311dc0, name = MessagesProxyModel))', source 'QModelIndex(1,2,0x0,MessagesModel(0x11b24b27d80))'.
time="    15.073" type="debug" -> database: SQLite database connection 'StandardFeed' to file 'C:/bin/inet/RSSGuard/data4/database/database.db' seems to be established.
time="    15.077" type="debug" -> database: SQLite connection 'RootItem' is already active.
time="    15.077" type="debug" -> database: SQLite database connection 'RootItem' to file 'C:/bin/inet/RSSGuard/data4/database/database.db' seems to be established.
time="    15.081" type="debug" -> database: SQLite connection 'StandardServiceRoot' is already active.
time="    15.081" type="debug" -> database: SQLite database connection 'StandardServiceRoot' to file 'C:/bin/inet/RSSGuard/data4/database/database.db' seems to be established.
time="    15.081" type="debug" -> feed-model: There is request to reload feed model, reloading the 2 items individually.
time="    15.122" type="debug" -> database: SQLite connection 'ImportantNode' is already active.
time="    15.122" type="debug" -> database: SQLite database connection 'ImportantNode' to file 'C:/bin/inet/RSSGuard/data4/database/database.db' seems to be established.
time="    15.125" type="debug" -> feed-model: There is request to reload feed model, reloading the 1 items individually.
time="    15.253" type="debug" -> gui: Hovered link: 'QUrl()'.
time="    16.459" type="debug" -> feed-downloader: Starting feed updates from worker in thread '0x42c8'.
time="    16.460" type="debug" -> feed-downloader: All caches synchronized.
time="    16.460" type="debug" -> database: SQLite database connection 'db_connection_17096' to file 'C:/bin/inet/RSSGuard/data4/database/database.db' seems to be established.
time="    16.464" type="debug" -> feed-downloader: Downloading new messages for feed ID '98' URL: 'https://www.lamanana.com.ar/feed/' title: 'La Mañana' in thread  '13992'.
time="    16.464" type="debug" -> database: SQLite database connection 'db_connection_13992' to file 'C:/bin/inet/RSSGuard/data4/database/database.db' seems to be established.
time="    16.465" type="debug" -> core: Downloading URL 'https://www.lamanana.com.ar/feed/' to obtain feed data.
time="    16.465" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="    16.474" type="debug" -> feed-downloader: Downloading new messages for feed ID '97' URL: 'https://enlineanoticias.com.ar/feed/' title: 'En Linea Noticias' in thread  '6812'.
time="    16.475" type="debug" -> database: SQLite database connection 'db_connection_6812' to file 'C:/bin/inet/RSSGuard/data4/database/database.db' seems to be established.
time="    16.475" type="debug" -> feed-downloader: Downloading new messages for feed ID '96' URL: 'https://radiofmamistad.com.ar/feed/' title: 'Radio Fm Amistad' in thread  '15744'.
time="    16.475" type="debug" -> core: Downloading URL 'https://enlineanoticias.com.ar/feed/' to obtain feed data.
time="    16.475" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="    16.475" type="debug" -> feed-downloader: Downloading new messages for feed ID '95' URL: 'https://www.diariolamanana.com.ar/feed/' title: 'Diario La Mañana' in thread  '17300'.
time="    16.476" type="debug" -> database: SQLite database connection 'db_connection_15744' to file 'C:/bin/inet/RSSGuard/data4/database/database.db' seems to be established.
time="    16.476" type="debug" -> database: SQLite database connection 'db_connection_17300' to file 'C:/bin/inet/RSSGuard/data4/database/database.db' seems to be established.
time="    16.476" type="debug" -> core: Downloading URL 'https://www.diariolamanana.com.ar/feed/' to obtain feed data.
time="    16.476" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.

(...) 

time="    22.565" type="debug" -> database: Checking if message with feed-specific custom ID 'https://pinamardiario.com.ar/?p=12871' is present in DB.
time="    22.565" type="debug" -> database: Message with custom ID 'https://pinamardiario.com.ar/?p=12871' is already present in DB and has DB ID '680'.
time="    22.565" type="debug" -> database: Checking if message with feed-specific custom ID 'https://pinamardiario.com.ar/?p=12860' is present in DB.
time="    22.566" type="debug" -> database: Message with custom ID 'https://pinamardiario.com.ar/?p=12860' is already present in DB and has DB ID '681'.
time="    22.566" type="debug" -> database: Checking if message with feed-specific custom ID 'https://pinamardiario.com.ar/?p=12850' is present in DB.
time="    22.566" type="debug" -> database: Message with custom ID 'https://pinamardiario.com.ar/?p=12850' is already present in DB and has DB ID '682'.
time="    22.566" type="debug" -> database: Checking if message with feed-specific custom ID 'https://pinamardiario.com.ar/?p=12845' is present in DB.
time="    22.566" type="debug" -> database: Message with custom ID 'https://pinamardiario.com.ar/?p=12845' is already present in DB and has DB ID '683'.
time="    22.566" type="debug" -> database: Checking if message with feed-specific custom ID 'https://pinamardiario.com.ar/?p=12839' is present in DB.
time="    27.305" type="debug" -> database: Message with custom ID 'https://laurbedigital.com.ar/noticias/?p=94438' is already present in DB and has DB ID '11510'.
time="    27.305" type="debug" -> database: Checking if message with feed-specific custom ID 'https://laurbedigital.com.ar/noticias/?p=80644' is present in DB.
time="    27.308" type="debug" -> database: Message with custom ID 'https://laurbedigital.com.ar/noticias/?p=80644' is already present in DB and has DB ID '11511'.
time="    27.308" type="debug" -> database: Checking if message with feed-specific custom ID 'https://laurbedigital.com.ar/noticias/?p=94424' is present in DB.
time="    27.311" type="debug" -> database: Message with custom ID 'https://laurbedigital.com.ar/noticias/?p=94424' is already present in DB and has DB ID '10659'.
time="    27.311" type="debug" -> database: Checking if message with feed-specific custom ID 'https://laurbedigital.com.ar/noticias/?p=94421' is present in DB.
time="    27.314" type="debug" -> database: Message with custom ID 'https://laurbedigital.com.ar/noticias/?p=94421' is already present in DB and has DB ID '9757'.
time="    27.314" type="debug" -> database: Checking if message with feed-specific custom ID 'https://laurbedigital.com.ar/noticias/?p=94417' is present in DB.
time="    27.317" type="debug" -> database: Message with custom ID 'https://laurbedigital.com.ar/noticias/?p=94417' is already present in DB and has DB ID '9742'.
time="    27.323" type="debug" -> feed-downloader: Updating messages in DB took 39508 microseconds.
time="    27.323" type="debug" -> feed-downloader: std::pair(0,0) messages for feed 171 stored in DB.
time="    27.323" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 62/236 (id of feed is 171).
time="    27.384" type="debug" -> feed-downloader: Finished feed updates in thread '0x42c8'.
time="    27.412" type="debug" -> CTRL is NOT pressed while sorting articles - sorting with standard mode.
time="    27.799" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, Feeds.is_rtl, CASE WHEN LENGTH(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Messages.labels LIKE "%." || Labels.custom_id || ".%") as msg_labels, Messages.labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE Feeds.custom_id IN ('240', '241', '242', '243', '244', '245', '246', '247', '225', '226', '227', '228', '229', '230', '231', '232', '233', '234', '235', '236', '237', '238', '239', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '64', '60', '61', '62', '63', '58', '59', '204', '205', '206', '207', '208', '209', '210', '211', '212', '213', '214', '215', '216', '217', '218', '219', '220', '221', '222', '223', '224', '185', '186', '187', '188', '189', '190', '191', '192', '193', '194', '195', '196', '197', '198', '199', '200', '201', '202', '203', '150', '151', '152', '153', '154', '155', '156', '157', '158', '159', '160', '161', '162', '163', '164', '165', '166', '167', '168', '169', '170', '171', '172', '173', '174', '175', '176', '177', '178', '179', '180', '181', '182', '183', '184', '138', '139', '140', '141', '142', '143', '144', '145', '146', '147', '148', '149', '113', '114', '115', '116', '117', '118', '119', '120', '121', '122', '123', '124', '125', '126', '127', '128', '129', '130', '132', '133', '134', '135', '136', '137', '99', '100', '101', '102', '103', '104', '105', '106', '107', '109', '110', '111', '112', '93', '94', '95', '96', '97', '98') AND Messages.is_deleted = 0 AND Messages.is_pdeleted = 0 AND Messages.account_id = 1 ORDER BY Messages.id DESC;'.
time="    27.804" type="debug" -> gui: Current row changed - proxy 'QModelIndex(1,6,0x11b2be0f410,MessagesProxyModel(0x11b27311dc0, name = MessagesProxyModel))', source 'QModelIndex(1,6,0x0,MessagesModel(0x11b24b27d80))'.
time="    27.805" type="debug" -> gui: Reloading of msg selections took 393 miliseconds.
time="    27.851" type="debug" -> core: Silencing GUI message: 'Ecos Diarios Necochea: 1'.

### Operating system and version

* OS: Windows 10
* RSS Guard version: 4.5.0

**Comment by martinrotter** [comment]
Format of saving that "state" was changed, it is possible that it gets "forgotten" but only once. If you tweak your columns again and quit/start RSS Guard again, it should be saved.

**Comment by slalaurette** [comment]
Excellent!

I remember it happening three times before I submitted the bug report. Now it's not happening anymore.
