### ISSUE TITLE
Feature Request: Feedly Support

### ISSUE THREAD

**Issue by SyntaxualSugar** [martinrotter/rssguard#105]
#### Brief description of the issue.

We need feedly support so that we can sync with our mobile/web apps.

**Comment by martinrotter** [comment]
Feedly has totally ridiculous policy for OSS projects. I e-mailed with their developers and it is impossible for RSS Guard to get full-production client key/secret. So each and every user of rssguard/feedly would have to generate EACH MONTH new access key via special website - https://feedly.com/v3/auth/dev and enter it into rssguard. This is literally crazy.

Moreover, only 250 queries per day is allowed for each user, they are probably nuts.

If these conditions are okay, I will add feedly support to rssguard, but I am really unhappy about this situation.

**Comment by wokawoka** [comment]
That sounds a little strange to me as I'm using mobile third party clients to access to my feedly acount from mobile platforms (gnewsreader on blackberry OS10 and some other clients on android) and I never had to deal with access/API Keys nor I had any problem in reaching any limit with queries.
Are you sure that there's no other way to interface rssguard without having to deal with those limitations?
In every case, but that's only my humble opinion, being able to access to the feedly account with the limitations that you wrote about would be at least better than nothing.
Thanks for the great job you are doing for this project

**Comment by martinrotter** [comment]
Those applications probably obtained production API keys some time ago, when Feedly were giving those without problems or maybe those applications are "innovative" and closed-source.

I wrote them e-mail with request for production keys, they literally refused! Read [this](https://groups.google.com/forum/#!topic/feedly-cloud/esZXWq7NTCg). RSS Guard probably does not fit in either of those 3 options listed in section *Getting A Live Client Id*.

So we cannot have full production key in RSS Guard, which is not good. The only way to go is to use [developer access tokens](https://developer.feedly.com/v3/developer/), which are severely limited - they have to be MANUALLY obtained each 30 days and they only allow 250 (!!!) queries PER DAY.

Moreover Feedly is commercial organization and the software is proprietary. If you think, that *developer access tokens* are enough, OK, I can add Feedly plugin, but honestly, I think it is not enough and users will get mad at me with question "Why do I have to get some ridiculously long number from some URL all the time?".

**Comment by martinrotter** [comment]
Working on this now.

**Comment by martinrotter** [comment]
Some progress:

![image](https://user-images.githubusercontent.com/1255302/107984122-883ff500-6fc7-11eb-99d2-c7f848942671.png)
