### ISSUE TITLE
[BUG]: Pre-made remove duplicate filter does not work

### ISSUE THREAD

**Issue by Duvio** [martinrotter/rssguard#1053]
### Brief description of the issue

I have enabled the pre-made filter "remove duplicates" which is supposed to remove articles with a title that is already in the database. Using the test function in the article filters window shows two articles with the same title in red, meaning that they must have been removed, yet they are still included.

### How to reproduce the bug?

1. Enable said filter
2. Fetch articles
3. See duplicates not getting removed
I however cannot say how consistent it is in not working, as i remember it working properly rarely.

### What was the expected result?

See the duplicate articles get removed.

### What actually happened?

The duplicate articles were included.

### Debug log

[rssguard_log.txt](https://github.com/martinrotter/rssguard/files/12353768/rssguard_log.txt)

### Operating system and version

* OS: Debian stable
* RSS Guard version: 4.4.0

**Comment by martinrotter** [comment]
Premade filter is not supposed to remove already existing articles. It is supposed to:

> This filter ensures that there are no duplicate
> articles received across all feeds

If you want to remove, you need to change "MessageObject.Ignore" to "MessageObject.Purge".

**Comment by Duvio** [comment]
> Premade filter is not supposed to remove already existing articles. It is supposed to:
> 
> > This filter ensures that there are no duplicate
> > articles received across all feeds
> 
> If you want to remove, you need to change "MessageObject.Ignore" to "MessageObject.Purge".

Does not work.
![Screenshot_2023-08-21_00-38-30](https://github.com/martinrotter/rssguard/assets/29256280/9df2153a-ba17-4a16-a9b2-6d7d968817bd)

**Comment by martinrotter** [comment]
@Duvio OK please, upload here your/sample "database.db" file which shows the issue. Thanks.

**Comment by Duvio** [comment]
Zipped because GitHub wont let me upload .dbs

[database.zip](https://github.com/martinrotter/rssguard/files/12392154/database.zip)

**Comment by martinrotter** [comment]
OK, loaded your database which has 598 articles.

When hitting "Test", some articles are marked as duplicated (red color).

![image](https://github.com/martinrotter/rssguard/assets/1255302/f99339f0-04dc-475a-8561-d70df0e48839)

After hitting "Process checked feeds" some 16 articles got removed as duplicates. Now database has 583 articles.

![image](https://github.com/martinrotter/rssguard/assets/1255302/cf77392d-ce91-4278-a375-1e37145fc7f9)

After that i fetched all feeds and now I have 770 articles. After that if I go and disable the article filter and fetch again, additional 40 articles is fetched, meaning that filters do work.

**Comment by Duvio** [comment]
But articles from different feeds with the same title are all still shown even though they should not be shown.

**Comment by martinrotter** [comment]
> But articles from different feeds with the same title are all still shown even though they should not be shown.

Can you write exactly the title which you have more than 1 article for?

**Comment by Duvio** [comment]
See my screenshot above

For example:
Dating apps: Blessing or curse?

**Comment by martinrotter** [comment]
Yes, I managed to reproduce the issue.

**Comment by Duvio** [comment]
Can this somehow be fixed?

I would contribute a PR myself if i had the time.

**Comment by martinrotter** [comment]
looking into it

**Comment by martinrotter** [comment]
Could be fixed: 68764732a

Pls test when development build compiles in 20 minutes.

**Comment by martinrotter** [comment]
https://github.com/martinrotter/rssguard/releases/tag/devbuild
