### ISSUE TITLE
[FR]: Pointer inconsistency on Linux

### ISSUE THREAD

**Issue by crixer18** [martinrotter/rssguard#1068]
### Brief description of the feature request

I find an inconsistency with the pointer on Linux Mint, it appears to be different on the rss guard window than the system selected pointer. It's not a big deal but it's weird and also the pointer on the window is very small and not so agile.

https://github.com/martinrotter/rssguard/assets/78487066/93301a8c-74ed-4c72-b430-6c1a76eb005a

**Comment by martinrotter** [comment]
what file exactly you have installed, what distro, what de

**Comment by crixer18** [comment]
Not sure I can answer, sorry. These are the info I found:
Version: 4.4.0 (compiled in Linux / x86_64)
Revision: f1d98bb-nowebengine
Compilation date: 27/06/23 07:50
Qt: 5.15.10 (compiled with 5.15.10)

I installed it via flathub, tried both the regular and lite version and they do the same thing.
Hope these are useful.

**Comment by martinrotter** [comment]
I see, do you see similar mouse pointer problems on other Flathub apps?

**Comment by martinrotter** [comment]
@crixer18 This might be actually upstream Flathub/Flatpak "bug".

https://forums.linuxmint.com/viewtopic.php?t=380469

**Comment by martinrotter** [comment]
>flatpak --user override --filesystem=/home/$USER/.icons/:ro
>flatpak --user override --filesystem=/usr/share/icons/:ro
