### ISSUE TITLE
[BUG]: Size of the date field cannot be changed

### ISSUE THREAD

**Issue by Duvio** [martinrotter/rssguard#1079]
### Brief description of the issue

See in the video

If it say the video cannot be played because the file is corrupt, download and play it in VLC

https://github.com/martinrotter/rssguard/assets/29256280/4bd84d86-8fdf-4858-adf0-07c05c25fef9

### How to reproduce the bug?

See in the video

### What was the expected result?

See in the video

### What actually happened?

See in the video

### Debug log

See in the video

### Operating system and version

* OS: Debian Trixie
* RSS Guard version: rssguard-devbuild-1ba499c2d-nowebengine-linux64.AppImage

**Comment by martinrotter** [comment]
you are doing it wrong, you must drag from the right side of "date" column to change it, not from the left side

**Comment by Duvio** [comment]
Ok, that way it works. Peculiar and counterintuitive.

**Comment by martinrotter** [comment]
sadly this behavior is out of my hands, cannot be changed
