### ISSUE TITLE
Feature Request: Inoreader support

### ISSUE THREAD

**Issue by ForlornWongraven** [martinrotter/rssguard#108]
#### Brief description of the issue.

We need Inoreader support so that we can sync with our mobile apps. API is available at https://www.inoreader.com/developers/ .

**Comment by martinrotter** [comment]
I will add more plugins after #102 and #71 are done.

**Comment by martinrotter** [comment]
I find their API quite nice, starting to work on this.

**Comment by martinrotter** [comment]
THe changes are done in separate branch so far, https://github.com/martinrotter/rssguard/tree/stringify-custom-ids

**Comment by martinrotter** [comment]
Experimental version is probably done.
