### ISSUE TITLE
[BUG]: "Bring application window to front..." option doesn't work with Chrome

### ISSUE THREAD

**Issue by JamesBomd** [martinrotter/rssguard#1085]
### Brief description of the issue

When I use the _"Open in external browser"_ function, the focus stays on the Chrome and doesn't go back to RSS Guard. The _"Bring application window to front once article is opened in external web browser"_ option is enabled.

I have tried several Chrome-like browsers, Chrome, Iron, Vivaldi, everywhere the same thing.

On Firefox everything works correctly and the focus returns to RSS Guard.

### How to reproduce the bug?

1. Use Chrome as your default web browser.
2. Launch RSS Guard
3. Enable the "Bring application window to front once article is opened in external web browser" option.
4. Open any Article via "Open in external browser".

### What was the expected result?

RSS Guard window should appear on the front of Chrome.

### What actually happened?

Chrome stays active in front of RSS Guard.

### Debug log

[rssguard.log](https://github.com/martinrotter/rssguard/files/12500731/rssguard.log)

### Operating system and version

* OS: Windows 11
* RSS Guard version: 4.5.0.0

**Comment by martinrotter** [comment]
Managed to reproduce. Not sure why this is happening.

**Comment by martinrotter** [comment]
Well, I am lost, this seems to be connected only to Windows. Windows sometimes does NOT allow to programmatically put application own window on top of window chain.

**Comment by martinrotter** [comment]
EDIT: I retested with Edge (Chrome) now and it works with following workaround. Sadly it is needed for some cases on Windows 10+.

I will incorporate this fix to RSS Guard too and it will be applied when user goes to settings and re-checkes the feature again.

https://wiki.qt.io/Technical_FAQ#QWidget_::activateWindow.28.29_-_behavior_under_windows
