### ISSUE TITLE
[BUG]: ''Synchronize folders & other items' do not respect account proxy setting

### ISSUE THREAD

**Issue by io43** [martinrotter/rssguard#1087]
### Brief description of the issue

Direct connection is used instead of the proxy set in account proxy setting when you use Synchronize folders & other items

### How to reproduce the bug?

1. click Synchronize folders & Synchronize folders on an tiny tiny rss account folder for example
2. direct connection is used instead of proxy set in account proxy setting 

### What was the expected result?

Proxied connection to the ttrss server

### What actually happened?

Direct connection, proxy bypassed

### Debug log

?

### Operating system and version

* OS: win10
* RSS Guard version: 4.4.0

![111](https://github.com/martinrotter/rssguard/assets/125970146/2e647498-b816-4ffc-9fa7-ee8a4e963e6b)

![11](https://github.com/martinrotter/rssguard/assets/125970146/735cec70-8163-449a-b539-f49fe957612b)

**Comment by martinrotter** [comment]
pushed 01af7a2a3

could fix your problem, test and let me know

**Comment by io43** [comment]
it seems ok 👍
