### ISSUE TITLE
[BUG]: web cache directory stored with configuration

### ISSUE THREAD

**Issue by ehmry** [martinrotter/rssguard#1098]
### Brief description of the issue

On my machine there is a cache directory at `~/.config/RSS Guard 4/web/cache`. `$XDG_CACHE_HOME` is set but caches shouldn't be in configuration directories in any case.

### How to reproduce the bug?

1. Run RSS Guard

### What was the expected result?

Cache stored at `$HOME/.cache` or `$XDG_CACHE_HOME`.

### What actually happened?

Cache stored at  `~/.config/RSS Guard 4/web/cache`.

### Debug log

Not relevant.

### Operating system and version

* OS: Linux
* RSS Guard version: 4.5.0

**Comment by martinrotter** [comment]
should be fixed

**Comment by ehmry** [comment]
Excellent, thank you.
