### ISSUE TITLE
Not visible tray menu on Ubuntu

### ISSUE THREAD

**Issue by varlesh** [martinrotter/rssguard#11]
With new Qt5-version, tray menu not visible.

![2016-05-07 00-04-14](https://cloud.githubusercontent.com/assets/8083855/15086164/8acd79be-13e7-11e6-98aa-ea75637a688a.png)

rssguard-qt5-git_3.2.2.1462251283.e1742d8
Ubuntu 16.04 Unity amd64

**Comment by martinrotter** [comment]
In previous version it worked? I think this is rather Qt 5 bug.

**Comment by varlesh** [comment]
On previous Qt4-version worked fine. But on Qt5 not showing.

**Comment by martinrotter** [comment]
Yeah, Qt 5 is different when working with tray icons/menus. Report bug upstream.

https://bugs.launchpad.net/ubuntu/+source/sni-qt/+bug/1330444
