### ISSUE TITLE
[BUG]: Stop ongoing fetching freezes program

### ISSUE THREAD

**Issue by Motocycle347** [martinrotter/rssguard#1101]
### Brief description of the issue

when even i try to stop an ongoing fetch the program freezes. if i just let it alone the program is fine

### How to reproduce the bug?

start program
start fetch
goto feeds > stop on going feeds. the program nowsfreezes

### What was the expected result?

the feed stops

### What actually happened?

program freezes needs to force quit it

### Debug log

time="     0.164" type="debug" -> core: Initializing settings in 'C:\RSS Guard\data4\config\config.ini' (portable way).
time="     0.168" type="debug" -> core: Starting to load active localization. Desired localization is 'en_US'.
time="     0.173" type="debug" -> core: Application localization 'en_US' loaded successfully, specifically sublocalization 'en_US' was loaded.
time="     0.176" type="warning" -> core: Qt localization 'en_US' WAS NOT loaded successfully.
time="     0.756" type="debug" -> database: File-based SQLite database connection 'DatabaseFactory' to file 'C:\RSS Guard\data4\database\database.db' seems to be established.
time="     0.759" type="debug" -> database: File-based SQLite database has version '7'.
time="     0.769" type="debug" -> gui: Available icon theme paths: QList(:/icons, :/graphics, C:\RSS Guard\data4\icons, C:/RSS Guard\icons)
time="     0.772" type="debug" -> gui: Installed icon themes are: '', 'Breeze', 'Breeze Dark', 'Faenza', 'Numix'
time="     0.774" type="debug" -> gui: Loading icon theme 'Breeze'.
time="     0.777" type="debug" -> gui: Found path of base skin: ':\skins\nudus-base'.
time="     0.780" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_wrapper.html' for the skin.
time="     0.782" type="debug" -> gui: Local file ':\skins\nudus-light\html_style.css' exists, using it for the skin.
time="     0.784" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_enclosure_image.html' for the skin.
time="     0.786" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_single_message.html' for the skin.
time="     0.787" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_enclosure_every.html' for the skin.
time="     0.789" type="debug" -> gui: Local file ':\skins\nudus-light\qt_style.qss' exists, using it for the skin.
time="     0.791" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_adblocked.html' for the skin.
time="     0.793" type="debug" -> gui: OS defines color scheme: 'Qt::ColorScheme::Dark'.
time="     0.795" type="debug" -> gui: Setting style: 'Fusion'.
time="     0.799" type="debug" -> gui: Skin 'nudus-light' loaded.
time="     0.801" type="debug" -> network: Disabling application-wide proxy completely.
time="     0.804" type="debug" -> core: SQLite version: '3.42.0'.
time="     0.825" type="debug" -> core: OpenSSL version: 'Secure Channel, Windows 10.0.22621'.
time="     0.827" type="debug" -> core: OpenSSL supported: 'true'.
time="     0.828" type="debug" -> core: Global thread pool has 8 threads.
time="     0.831" type="debug" -> core: Starting RSS Guard 4.5.0.
time="     0.833" type="debug" -> core: Instantiated class  'Application'.
time="     0.837" type="warning" -> core: Another instance of the application is already running. Notifying it.
time="     0.839" type="debug" -> core: Destroying Application instance.
time="     0.840" type="debug" -> core: Destroying Mutex instance.
time="     1.216" type="debug" -> gui: Destroying IconFactory instance.

### Operating system and version

win 11 pro 22H2 build 22621.2283
4.5 7175578b6-nowebengine

**Comment by martinrotter** [comment]
not able to reproduce, does this happen all the time? does this happen on older versions?

**Comment by Motocycle347** [comment]
Happens all the time
--
Sent via Pony Express Friday, 15 September 2023, 00:58AM -04:00 from martinrotter  ***@***.*** :

**Comment by Motocycle347** [comment]
system gets stuck fetching https://www.neowin.net/news/rss/

**Comment by martinrotter** [comment]
I beleive this is the same as #1073
