### ISSUE TITLE
Selecting a feed takes too long

### ISSUE THREAD

**Issue by ckorn** [martinrotter/rssguard#111]
#### Brief description of the issue.

When selecting a feed it takes about two seconds until the feed is shown.
Having hundreds of feeds which I mostly want to mark as read by selecting them it becomes quite annoying.

#### Other information (logs, see Wiki)

All feeds come from my Nextcloud server.

**Comment by martinrotter** [comment]
Does this happen with clean profile and with standard "online feeds" account?

How many feeds do you have?

**Comment by ckorn** [comment]
No, standard feeds are not affected. Seems only to occur with feeds from Nextcloud.

There are about 300 feeds per day:
![My feeds]
(http://pix.toile-libre.org/upload/original/1492530826.jpg)

**Comment by martinrotter** [comment]
Can you provide application debug log? See wiki for more info.

1. Run RSS Guard with log generation enabled.
2. Simulate the bug.
3. Send me the log.

**Comment by ckorn** [comment]
In this log I clicked a few unread items and waited for them to get marked as read.
[click_single_items.txt](https://github.com/martinrotter/rssguard/files/944531/click_single_items.txt)
You can also give me a patch to enable further debugging. I know how to compile rssguard.

**Comment by martinrotter** [comment]
Can you try latest development version? See wiki on how to download it.

Test it and let me know.

**Comment by ckorn** [comment]
The current build does not have this problem any longer.

Thanks for fixing it.
