### ISSUE TITLE
[BUG] PC does not sleep automatically after a RSS Guard plays a notification sound

### ISSUE THREAD

**Issue by ale-carra** [martinrotter/rssguard#1118]
### Brief description of the issue

My PC will not sleep automatically as long as RSS Guard is running after it plays a notification sound. If I run `powercfg /requests` on Windows Terminal while RSS Guard is running then the USB Audio Device will appear on the list of processes preventing sleep. If I close RSS Guard, or if a notification sound is never played then the USB Audio Device will not appear on the list.

### How to reproduce the bug?

1. Open RSS Guard
2. Make RSS Guard play a notification sound
3. Close the window so RSS Guard remains on the system tray

### What was the expected result?

My PC should sleep automatically after it's unused for a while

### What actually happened?

My PC will never go to sleep automatically

### Debug log

[log.txt](https://github.com/martinrotter/rssguard/files/12778389/log.txt)

### Operating system and version

* OS: Windows 11
* RSS Guard version: 4.5.0

**Comment by martinrotter** [comment]
Well this must somehow be Windows-11-specific because I play tons of notifications in my RSS Guard instances and now such thing ever happened to me.

Will check the source code for some obvious fixes.

**Comment by ale-carra** [comment]
I've tried enabling only one notification with a MP3 sound, disabling sounds on all other notifications and restarting my PC, but unfortunately I still have this issue

**Comment by martinrotter** [comment]
So if you have all your sounds disabled, then all works? If so, do you have any log directly from Windows to somehow see, what is blocking the sleep?

https://www.howtogeek.com/131464/how-to-see-which-app-is-blocking-your-pc-from-going-into-sleep-mode/

**Comment by ale-carra** [comment]
Yes, if I have all of my sounds disabled the PC will sleep. This is the output of `powercfg /requests` after RSS Guard plays a notification sound

> DISPLAY:
> None.
> SYSTEM:
> [DRIVER] USB Audio Device (USB\VID_0001&PID_0201&MI_00\7&bbc3150&0&0000)
> An audio stream is being used.
> [DRIVER] Legacy kernel caller
> AWAYMODE:
> None
> EXECUTION:
> None.
> PERFBOOST:
> None.
> ACTIVELOCKSCREEN:
> None.

**Comment by martinrotter** [comment]
I managed to reproduce the problem.

**Comment by martinrotter** [comment]
Looks like upstream bug.

https://bugreports.qt.io/browse/QTBUG-118755

**Comment by martinrotter** [comment]
https://bugreports.qt.io/browse/QTBUG-117612

For me

**Comment by martinrotter** [comment]
This bug is caused by upstream behavior in Qt libraries. I added their recommended solution to RSS Guard, that's all I can do, hopefully it fixes the behavior your see.
