### ISSUE TITLE
[FR]: Notification balloon requires massive improvements

### ISSUE THREAD

**Issue by Starboy-Xo** [martinrotter/rssguard#1125]
### Brief description of the feature request

Hello,

I am happy to see that 4.5.1 finally has the notification balloon system and now we will not need to open the application to see the new feeds updates every time.
However, the current feed notification system is at its very initial stage. Which means, we cannot enjoy the immersive experience with it at this moment. You will need to give it a comprehensive writing in order to install multifarious features so we can curate it according to our mood.

Following is the list of features that the notification system requires at this stage:

Notification Settings
   - Dissect the notification settings into tabs
     -  **a) Notifications Sounds**
        - The sounds settings will be as it used to be before 4.5.1
     -  **b) Notification box Style**
         - The Styling will consist of **how** and **where** the notification box will look on-screen
            - The '**How**' factor includes the width and length of a notification feed title along with the desired theme selection for the notification. 
            - Ensure to add the ability to enable/disable strip new line if the feed title exceeds the notification box width. 
               - With that, also add enable/disable little description (first 20 words or something similar) -> [Plenary App](https://play.google.com/store/apps/details?id=com.spians.plenary&pcampaignid=web_share) as a reference has ability for its widgets to show the small description too.
            - Box transparency should also be added.
               - Font designing should also be the part of this tab.
            - The '**Where**' factor is already available in the tools. If it is possible, add the ability to drag the notification box to the desired positions/coordinates on screen (but it is an extra feature).
     -  **c) Notification View**
        - This tab should allow users to select through the list of all the feed items that we want to be shown as notification.
           - This feature should be added in the Add Feed dialog box where we directly select the feed behavior to be shown as notification
         - This tab should also allow users to limit feed messages to be shown in notifications. This will allow the users to be able to see the last **5** feed messages from every feed which can be extended to unlimited by putting in **-1** value (Default will be unlimited -1).

**Comment by expg** [comment]
Obviously, the new notification feature needs several improvement but I was amazed at how quickly the developer responded to this issue that [I commented on only 3 months ago](https://github.com/martinrotter/rssguard/issues/499#issuecomment-1621754941).
I think the configurable window size feature is the most urgent priority at the moment because the length of the article title is almost always longer than its window size.
and the displaying nofication structure should be changed to show multiple feeds together at the same time that is categorized by each feed in a single window instead of splitting them into different tabs or drop-down menus.
The more clicks it takes, the more hassle it is.

**Comment by martinrotter** [comment]
Added configurable width and margins.

![7pDTLiBoMm](https://github.com/martinrotter/rssguard/assets/1255302/17533c3b-e836-41a2-9d49-0a157ff95c62)

**Comment by martinrotter** [comment]
Some sub-features are now fixed: transparency, width, title will not elide longer text and not wrap (which indeed looked ugly).
Some sub-features i do not plan to address myself. PRs welcomed.

Please in the future do not post big tickets, split your request into more atomic simple feature requests.

**Comment by Starboy-Xo** [comment]
> Please in the future do not post big tickets, split your request into more atomic simple feature requests.

Acknowledged

Thanks a lot
