### ISSUE TITLE
View unread messages only

### ISSUE THREAD

**Issue by pcause** [martinrotter/rssguard#113]
Built from the git repo.  First, thanks for the sorting enhancements.  This gives me what I had asked for.

First the issue: I select a folder of feeds and update.  Even though I have selected show only unread items I see items on the right pane.  If there are no unread messages for a feed or folder I shouldn't see anything, correct.

Second issue is that I want to see folders/feeds on the left (whether they have unread items or not) and then when I select a folder or feed see only the unread items for that object on the right.  Doesn't seem to be a way to separate what is shown in each panel.

**Comment by martinrotter** [comment]
> Even though I have selected show only unread items I see items on the right pane

The "show only unread items" menu item is located in "Feeds" menu, isn't it? It is purposed to filter list of FEEDS not list of messages. So if you check it on, your list feed should only contain items which contain some unread messages.

Filtering of messages to show only unread items is not yet implemented, bud I am making changes to make this possible.

You can "highlight" unread messages, in "Messages" menu.

Yes, you cannot "filter" messages right now to only see unread messages on the right. It is not yet added.

So. this is not BUG report but you request new FEATURE insted? Adding a way to show only unread messages (the "show only unread items" is for showing only unread feeds -  on left tree).

?

**Comment by martinrotter** [comment]
It is planned to view only unread/highlighted messages. It is now fully possible. I will maybe add this in future releases.

**Comment by pcause** [comment]
any hope you'll add this?

**Comment by frizop** [comment]
Just started using Rss Guard, thanks for the awesome app, this is the one missing feature for me though! Any chance on adding it? I'd love to only see my unread items (without having to scroll a bunch)

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/84653631-11b99780-af0e-11ea-96b5-c983e7e423ae.png)

Please, test and latest dev builds and let me know.

**Comment by pcause** [comment]
quick test of 3.6.3 daad076 and it seems to work
