### ISSUE TITLE
update all items

### ISSUE THREAD

**Issue by ki00** [martinrotter/rssguard#114]
The option "update all items" does not work, you need to update feed by feed. And is hard, because sometimes update and sometimes not
.

#### How to reproduce the bug?

1. Add at least 20 or mores feeds
2. The first day the updating is easy
3. The next days will be harder to update. Also hard with imported feeds.

#### What is the expected result?

Although system gets slower, the feeds do not update

#### What actually happened?

No update

**Comment by martinrotter** [comment]
Attach logs. See Wiki on info how to get logs.

**Comment by ki00** [comment]
I have tried several times, with and without the dot, the log just is:

bash: /rssguard: No existe el fichero o el directorio
bash: ./rssguard: No existe el fichero o el directorio

from 
[user@user-pc RSS Guard]$ 
[user@user-pc ~]$

(I am not a programmer)

**Comment by martinrotter** [comment]
Try it without the leading slash like this `rssguard > ~/log.txt 2>&1`.

**Comment by ki00** [comment]
Now it gives this message:
[rssguard] DEBUG: Instantiated Application class.
[rssguard] WARNING: Another instance of the application is already running. Notifying it.
[rssguard] DEBUG: Destroying Application instance.


by the way, when I import feeds in a standard account, and I click on "ok", it is duplicated for each "ok" y submit, 
also, in the order of get an update of a feed I need to edit it and uploaded it from different feef type: first rss2, then atom, then back rss2 and it updates
or there is the possibility that it can load through atom one time, then through rss2, other day through rss1, and on.

**Comment by martinrotter** [comment]
Closing, inactivity, no log provided. Open new issue if you will be able to obtain logs in the future.

**Comment by ki00** [comment]
Hi, maybe this short video could give an idea of the issue https://vid.me/nutv
(need to update one by one and edit the feed type in order to update)
Thanks

**Comment by martinrotter** [comment]
Can you please provide the log? Turn off rss guard and then run it with log enabled like described in the wiki. It's easy. Without log, i cannot do anything.

The video looks clear, the issue is really there. But for me to fix, I need your cooperation and the log. :)

**Comment by ki00** [comment]
recently I learn for such log, just to write "rssguard" in konsole and run it
however, it do not show all the log, just the last part of it, the first part disappear as the input grows
both are for an update all items, for first one, try some items individually
https://pastebin.com/dP7BaRWU
https://pastebin.com/7EmSwYb1

**Comment by martinrotter** [comment]
1. Test on latest development build.
2. Send me the log.

Thank you.
