### ISSUE TITLE
[BUG]: Delete articles

### ISSUE THREAD

**Issue by inson1** [martinrotter/rssguard#1149]
### Brief description of the issue

If I right click on article. Menu appears. In that menu is "delete articles", even if I clicked only on one arcticle. It should say "delete article"

### How to reproduce the bug?

.

### What was the expected result?

.

### What actually happened?

.

### Debug log

.

### Operating system and version

* OS: Windows 10
* RSS Guard version: 4.5.1

**Comment by martinrotter** [comment]
Well, I do not generate titles of 98 % of menu items dynamically, because it is really just not needed, man. Dont be picky.

**Comment by inson1** [comment]
@martinrotter I wasnt even sure what happens if I click on it. I was worried, that I would delete all my articles. Its crazy bad for newcomers, at least change it to "delete". Plase.
