### ISSUE TITLE
No customize settings for feed panel

### ISSUE THREAD

**Issue by soredake** [martinrotter/rssguard#115]
#### Brief description of the issue.
Right now these columns take up a lot of space, and the column named 'feed' is shown everywhere (this column is useless in separate feeds, I already know from which feed these messages), not just in the general all-feeds feed (meaning the one that appears after clicking on mynickname @ rssguard). Plus position of columns resets after restart.

#### How to reproduce the bug?

1. try to find customize settings for this panel
![i68npi_hhc0ulidvwjwi4lz68h4](https://cloud.githubusercontent.com/assets/5204968/26685295/342dc5e8-46d9-11e7-9f17-5ebba93c8984.png)
2. ???

#### What is the expected result?

Ability to customize this panel (and make settings permanent), i want to remove author and feed from panel.

#### What actually happened?

No settings for this.

#### Other information (logs, see Wiki)

Latest rssguard from git.

**Comment by martinrotter** [comment]
Yes, those columns could not be tweakable but some latest changes were done and soon I will start working on this.

**Comment by martinrotter** [comment]
This and #102 are the last two issues to be solved before 3.4.1 gets out.

**Comment by martinrotter** [comment]
This will be remembered:
 - order of columns,
 - hidden columns, 
 - width of columns.

I will in a few days add a simple context menu (right click on column) to select visible columns.

**Comment by martinrotter** [comment]
Can you test d635c8a? See wiki on info how to obtain latest dev build for Windows.

**Comment by soredake** [comment]
>for Windows
I use gentoo, it's easy for me.

**Comment by soredake** [comment]
>order of columns,
>hidden columns,

Working.

>width of columns.

I wait when it will be possible to adjust it.

**Comment by martinrotter** [comment]
You can resize columns, simply by draggin edges of them. Does it work?

**Comment by soredake** [comment]
Sorry, but after the upgrade it does not work.

**Comment by martinrotter** [comment]
Wait so, you cannot take your mouse and drag column headers borders on some columns? No columns can be resized? In fact, there are no new changes for resizing of columns. Column "title" had resizin disabled by design, other columns should work bro.

**Comment by soredake** [comment]
I can resize now on https://github.com/martinrotter/rssguard/commit/1ff2316370da7c149a26a328ab6aef6dc3ffe4ae

**Comment by martinrotter** [comment]
Perfectos.
