### ISSUE TITLE
[DOCS] Create Translations section in Readme, add crowdin link and the table with translations  into it

### ISSUE THREAD

**Issue by inson1** [martinrotter/rssguard#1152]
### Brief description of the feature request

.

**Comment by martinrotter** [comment]
As per github "standards" there is CONTRIBUTING.md file which is exactly there for this purpose.

https://github.com/martinrotter/rssguard/blob/master/CONTRIBUTING.md

That has link to

https://rssguard.readthedocs.io/en/stable/contrib/localization.html

which has some useful information and directly links to list of translations.

https://crowdin.com/project/rssguard

**Comment by inson1** [comment]
@martinrotter Yes, its Github standard, but in Readme should at least be link

**Comment by inson1** [comment]
@martinrotter I meant link to CONTRIBUTING :)
