### ISSUE TITLE
Setting for auto-delete messages older than $days

### ISSUE THREAD

**Issue by soredake** [martinrotter/rssguard#116]
#### Brief description of the issue.

Global and per-feed plus delete from recycler bin.

#### How to reproduce the bug?

1. 
2. 
3.

**Comment by martinrotter** [comment]
You mean normal "delete" or complete purge from DB?

**Comment by soredake** [comment]
Complete purge, i have quite a lot of feeds, in due course the size of the database can greatly increase.

**Comment by martinrotter** [comment]
In that case, you could use MySQL database?

**Comment by soredake** [comment]
I really do not like MySQL, SQLite suits me, we already have manual removal in Tabs -> Cleanup database, I just want it to work automatically after the time set by me.

**Comment by martinrotter** [comment]
Yes, no problem. I think it can be done when program starts.

**Comment by martinrotter** [comment]
Should this be configurable per-feed or globally?

**Comment by soredake** [comment]
Maybe both?
