### ISSUE TITLE
[FR]: Add search to available actions

### ISSUE THREAD

**Issue by inson1** [martinrotter/rssguard#1160]
### Brief description of the feature request

I guess this is also low priority, but I think its useful
![image](https://github.com/martinrotter/rssguard/assets/75314629/48d1dbf2-889e-448d-a5b1-3104588a5a5f)

**Comment by martinrotter** [comment]
https://github.com/martinrotter/rssguard/issues/449
duplicate

**Comment by inson1** [comment]
@martinrotter Sorry for that
