### ISSUE TITLE
[FR]: Tree expanders should be shown in default settings

### ISSUE THREAD

**Issue by inson1** [martinrotter/rssguard#1161]
### Brief description of the feature request

Why it isnt in default settings?
You even show it in Readme
![image](https://github.com/martinrotter/rssguard/assets/75314629/d40865d6-7ddb-4b82-9e89-0165b10b07b4)

**Comment by martinrotter** [comment]
They are, this is excerpt from source code:

```
DKEY Feeds::ShowTreeBranches = "show_tree_branches";
DVALUE(bool) Feeds::ShowTreeBranchesDef = true;
```

**Comment by martinrotter** [comment]
This is RSS Guard launched for the first time with clean settings:

![image](https://github.com/martinrotter/rssguard/assets/1255302/c8d5f174-8925-4ced-b936-79bdda24e30e)

**Comment by inson1** [comment]
@martinrotter I meant this 
![Untitled3](https://github.com/martinrotter/rssguard/assets/75314629/0b3235dc-2a4f-4db3-b7fa-29f963dc101e)

**Comment by martinrotter** [comment]
Yes, so did I.

**Comment by inson1** [comment]
Well I meant the lines, they arent visible

**Comment by martinrotter** [comment]
I see. They are visible on some platforms and invisible on other platforms. This is platform dependent I believe.
