### ISSUE TITLE
[FR]: Option to name/rename account from network system proxy

### ISSUE THREAD

**Issue by inson1** [martinrotter/rssguard#1164]
### Brief description of the feature request

I maybe saw it somewhere, but I cant find it

**Comment by martinrotter** [comment]
I have no idea what you mean by this, please ellaborate.

**Comment by inson1** [comment]
If choose account from my network system proxy I cant edit the name
![image](https://github.com/martinrotter/rssguard/assets/75314629/0aaeaafc-457c-425e-b87a-1c679797ac32)

**Comment by inson1** [comment]
@martinrotter yes, sorry for the work

**Comment by martinrotter** [comment]
no prob.
