### ISSUE TITLE
[QUESTION]: Appearance - same level

### ISSUE THREAD

**Issue by inson1** [martinrotter/rssguard#1169]
### Brief description of the issue

How could I get rid of it? I want it on same level. Idk what I did wrong. Yes icons are deleted on the middle one.
![Untitled](https://github.com/martinrotter/rssguard/assets/75314629/af14f1fb-a14e-43e6-aacd-335bfe828b60)

### How to reproduce the bug?

.

### What was the expected result?

.

### What actually happened?

.

### Debug log

.

### Operating system and version

.

**Comment by martinrotter** [comment]
Yes, this indeed does not look nice. Will check that. It is likely consequence of having icons removed, indeed.

**Comment by martinrotter** [comment]
Fixed with 24cbeb949.

**Comment by inson1** [comment]
yes its fixed
