### ISSUE TITLE
Feed names are truncated in feed list

### ISSUE THREAD

**Issue by soredake** [martinrotter/rssguard#117]
#### How to reproduce the bug?

1. ![cmruvd_kzotocpfh39downnhauz](https://cloud.githubusercontent.com/assets/5204968/26685891/e0e0e008-46da-11e7-8a15-371ac173ae82.png)

#### Other information (logs, see Wiki)

Latest version from git.

**Comment by martinrotter** [comment]
What behavior do you prefer instead????

**Comment by soredake** [comment]
Print as many characters as you can? The screenshot shows that there is enough space there.

**Comment by martinrotter** [comment]
This is done internally by Qt, no way to tweak that.
