### ISSUE TITLE
[BUG]: Changelog in native notifications unusable

### ISSUE THREAD

**Issue by ReillyBrogan** [martinrotter/rssguard#1172]
### Brief description of the issue

If the user has native notifications enabled then the "click me for what's changed" notification is useless when it appears as it does not appear to map the click action to whatever it's supposed to be.

### How to reproduce the bug?

1. Install 4.5.1
2. Switch to native notifications
3. Update to 4.5.2
4. Try to click notification

### What was the expected result?

The notification should go to wherever the update notes are

### What actually happened?

Nothing

### Debug log

N/A

### Operating system and version

* OS: Solus Linux
* RSS Guard version: 4.5.2

**Comment by martinrotter** [comment]
I cannot reproduce, really.

When said notification appears, clickin "Click the bubble..." displays "update dialog".

![image](https://github.com/martinrotter/rssguard/assets/1255302/1a80847a-332e-4bab-8505-bc5d7429fc7a)

**Comment by martinrotter** [comment]
cannot reproduce, double-checked the code, all looks ok
