### ISSUE TITLE
[FR]: Option to set color to (all) important articles (in articles view)

### ISSUE THREAD

**Issue by inson1** [martinrotter/rssguard#1174]
### Brief description of the feature request

So you can find them faster

**Comment by martinrotter** [comment]
feeds view display list of FEEDS

article view display list of ARTICLES

You cannot have feed emphasised with some color when it contains starred articles at this point. You can do this in article list tho.

**Comment by inson1** [comment]
@martinrotter How can I do that? I didnt find it in setting

**Comment by martinrotter** [comment]
![image](https://github.com/martinrotter/rssguard/assets/1255302/29f07508-4b91-4818-9241-796811357bb9)

**Comment by inson1** [comment]
I did set it, but I cant see the color. Do I have to do also something else?

**Comment by inson1** [comment]
@martinrotter And Why this actions arent in the main menu?

**Comment by martinrotter** [comment]
you can set color in
![image](https://github.com/martinrotter/rssguard/assets/1255302/4433c3e0-c84f-4dfd-b91e-965b2859abb0)
"interesting..."

**Comment by inson1** [comment]
@martinrotter So it isnt set in default 🤔 shouldnt be there some color in default for that?

**Comment by martinrotter** [comment]
There is some color by default, each skin defines some default color. "nudus-light" skin defines default color #11204f (dark blue) which is similar to black bit clearly visibly different.
