### ISSUE TITLE
[BUG]: Adblock not starting.

### ISSUE THREAD

**Issue by chrisretusn** [martinrotter/rssguard#1178]
### Brief description of the issue

After upgrade to 4.5.2 I get "AdBlock is not configured properly. Go to "Settings" -> "Node.js" and check if your Node.js is properly configured." I have check settings, there is a check mark by each setting option. Node.js 20.9.0 is installed. Issue is same with 4.5.3.

### How to reproduce the bug?

1. Start RSS Guard
2. Enable AdBlock
3. Wait a few seconds get the above message in the description.

### What was the expected result?

AdBlock start.

### What actually happened?

Received this message: AdBlock is not configured properly. Go to "Settings" -> "Node.js" and check if your Node.js is properly configured.

### Debug log

~$ rssguard --debug
time="     0.000" type="debug" -> core: Starting RSS Guard 4.5.3.
time="     0.000" type="debug" -> core: Current UTC date/time is 2023-11-02T11:37:23Z.
time="     0.378" type="critical" -> core: Unknown option 'debug'.
time="     0.379" type="debug" -> core: Initializing settings in '/home/chris/.config/RSS Guard 4/config/config.ini' (non-portable way).
time="     0.379" type="debug" -> core: Starting to load active localization. Desired localization is 'en_US'.
time="     0.380" type="debug" -> core: Application localization 'en_US' loaded successfully, specifically sublocalization 'en_US' was loaded.
time="     0.380" type="warning" -> core: Qt localization 'en_US' WAS NOT loaded successfully.
time="     0.746" type="debug" -> database: File-based SQLite database connection 'DatabaseFactory' to file '/home/chris/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.746" type="debug" -> database: File-based SQLite database has version '7'.
time="     0.746" type="debug" -> gui: Available icon theme paths: (/home/chris/.local/share/icons, /usr/share/icons, :/icons, :/graphics, /home/chris/.config/RSS Guard 4/icons, /usr/bin/icons)
time="     0.748" type="debug" -> gui: Icon theme 'breeze' already loaded.
time="     0.748" type="debug" -> gui: Found path of base skin: ':/skins/nudus-base'.
time="     0.748" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_wrapper.html' for the skin.
time="     0.748" type="debug" -> gui: Local file ':/skins/nudus-light/html_style.css' exists, using it for the skin.
time="     0.748" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_enclosure_image.html' for the skin.
time="     0.748" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_single_message.html' for the skin.
time="     0.748" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_enclosure_every.html' for the skin.
time="     0.748" type="debug" -> gui: Local file ':/skins/nudus-light/qt_style.qss' exists, using it for the skin.
time="     0.748" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_adblocked.html' for the skin.
time="     0.749" type="debug" -> gui: Setting style: 'Fusion'.
time="     0.751" type="debug" -> gui: Skin 'nudus-light' loaded.
time="     0.781" type="warning" -> core: User CSS style was not provided in file '/home/chris/.config/RSS Guard 4/web/user-styles.css'.
time="     0.781" type="debug" -> network: Persistent web data storage path: '/home/chris/.config/RSS Guard 4/web/storage'.
time="     0.781" type="debug" -> network: Disabling application-wide proxy completely.
time="     0.782" type="debug" -> core: SQLite version: '3.43.2'.
time="     0.786" type="debug" -> core: OpenSSL version: 'OpenSSL 3.1.4 24 Oct 2023'.
time="     0.786" type="debug" -> core: OpenSSL supported: 'true'.
time="     0.786" type="debug" -> core: Global thread pool has 8 threads.
time="     0.786" type="debug" -> core: Instantiated class  'Application'.
time="     0.797" type="debug" -> database: SQLite database connection 'MessagesModel' to file '/home/chris/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.799" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, Feeds.is_rtl, CASE WHEN LENGTH(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Messages.labels LIKE "%." || Labels.custom_id || ".%") as msg_labels, Messages.labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1;'.
time="     0.799" type="debug" -> core: Auto-download timer started with interval 10000 ms.
time="     0.799" type="debug" -> core: Creating FeedDownloader singleton.
time="     0.806" type="debug" -> gui: Creating main application form in thread: '0x7fa83e1643c0'.
time="     0.816" type="debug" -> gui: Current row changed - proxy 'QModelIndex(-1,-1,0x0,QObject(0x0))', source 'QModelIndex(-1,-1,0x0,QObject(0x0))'.
time="     0.879" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     0.940" type="debug" -> gui: Creating tray icon menu.
time="     1.141" type="debug" -> core: OS asked application to save its state.
time="     1.146" type="debug" -> core: Hiding the main window when the application is starting.
time="     1.149" type="debug" -> gui: Main window's close event
time="     1.149" type="debug" -> database: SQLite database connection 'FeedReader' to file '/home/chris/.config/RSS Guard 4/database/database.db' seems to be established.
time="     1.150" type="debug" -> database: SQLite database connection 'FeedlyEntryPoint' to file '/home/chris/.config/RSS Guard 4/database/database.db' seems to be established.
time="     1.150" type="debug" -> database: SQLite database connection 'GmailEntryPoint' to file '/home/chris/.config/RSS Guard 4/database/database.db' seems to be established.
time="     1.150" type="debug" -> database: SQLite database connection 'GreaderEntryPoint' to file '/home/chris/.config/RSS Guard 4/database/database.db' seems to be established.
time="     1.151" type="debug" -> database: SQLite database connection 'OwnCloudServiceEntryPoint' to file '/home/chris/.config/RSS Guard 4/database/database.db' seems to be established.
time="     1.151" type="debug" -> database: SQLite database connection 'RedditEntryPoint' to file '/home/chris/.config/RSS Guard 4/database/database.db' seems to be established.
time="     1.151" type="debug" -> database: SQLite database connection 'StandardServiceEntryPoint' to file '/home/chris/.config/RSS Guard 4/database/database.db' seems to be established.
time="     1.152" type="debug" -> database: SQLite database connection 'StandardServiceRoot' to file '/home/chris/.config/RSS Guard 4/database/database.db' seems to be established.
time="     1.172" type="debug" -> core: Custom ID of feed when loading from DB is '1'.
time="     1.174" type="debug" -> core: Custom ID of feed when loading from DB is '2'.
time="     1.176" type="debug" -> core: Custom ID of feed when loading from DB is '3'.
time="     1.176" type="debug" -> core: Custom ID of feed when loading from DB is '4'.
time="     1.177" type="debug" -> core: Custom ID of feed when loading from DB is '5'.
time="     1.177" type="debug" -> core: Custom ID of feed when loading from DB is '7'.
time="     1.177" type="debug" -> core: Custom ID of feed when loading from DB is '8'.
time="     1.177" type="debug" -> core: Custom ID of feed when loading from DB is '9'.
time="     1.178" type="debug" -> core: Custom ID of feed when loading from DB is '10'.
time="     1.178" type="debug" -> core: Custom ID of feed when loading from DB is '11'.
time="     1.178" type="debug" -> core: Custom ID of feed when loading from DB is '12'.
time="     1.179" type="debug" -> core: Custom ID of feed when loading from DB is '13'.
time="     1.179" type="debug" -> core: Custom ID of feed when loading from DB is '14'.
time="     1.179" type="debug" -> core: Custom ID of feed when loading from DB is '15'.
time="     1.179" type="debug" -> core: Custom ID of feed when loading from DB is '16'.
time="     1.180" type="debug" -> core: Custom ID of feed when loading from DB is '17'.
time="     1.180" type="debug" -> core: Custom ID of feed when loading from DB is '18'.
time="     1.180" type="debug" -> core: Custom ID of feed when loading from DB is '19'.
time="     1.180" type="debug" -> core: Custom ID of feed when loading from DB is '22'.
time="     1.181" type="debug" -> core: Custom ID of feed when loading from DB is '23'.
time="     1.181" type="debug" -> core: Custom ID of feed when loading from DB is '24'.
time="     1.181" type="debug" -> core: Custom ID of feed when loading from DB is '25'.
time="     1.181" type="debug" -> core: Custom ID of feed when loading from DB is '26'.
time="     1.181" type="debug" -> core: Custom ID of feed when loading from DB is '27'.
time="     1.182" type="debug" -> core: Custom ID of feed when loading from DB is '30'.
time="     1.182" type="debug" -> core: Custom ID of feed when loading from DB is '31'.
time="     1.182" type="debug" -> core: Custom ID of feed when loading from DB is '32'.
time="     1.182" type="debug" -> core: Custom ID of feed when loading from DB is '33'.
time="     1.182" type="debug" -> core: Custom ID of feed when loading from DB is '34'.
time="     1.183" type="debug" -> core: Custom ID of feed when loading from DB is '35'.
time="     1.183" type="debug" -> core: Custom ID of feed when loading from DB is '36'.
time="     1.183" type="debug" -> core: Custom ID of feed when loading from DB is '37'.
time="     1.183" type="debug" -> core: Custom ID of feed when loading from DB is '38'.
time="     1.183" type="debug" -> core: Custom ID of feed when loading from DB is '39'.
time="     1.183" type="debug" -> core: Custom ID of feed when loading from DB is '41'.
time="     1.184" type="debug" -> core: Custom ID of feed when loading from DB is '42'.
time="     1.184" type="debug" -> core: Custom ID of feed when loading from DB is '43'.
time="     1.184" type="debug" -> core: Custom ID of feed when loading from DB is '44'.
time="     1.185" type="debug" -> core: Custom ID of feed when loading from DB is '45'.
time="     1.185" type="debug" -> core: Custom ID of feed when loading from DB is '46'.
time="     1.185" type="debug" -> core: Custom ID of feed when loading from DB is '47'.
time="     1.185" type="debug" -> core: Custom ID of feed when loading from DB is '48'.
time="     1.186" type="debug" -> core: Custom ID of feed when loading from DB is '49'.
time="     1.186" type="debug" -> core: Custom ID of feed when loading from DB is '50'.
time="     1.186" type="debug" -> core: Custom ID of feed when loading from DB is '52'.
time="     1.186" type="debug" -> core: Custom ID of feed when loading from DB is '53'.
time="     1.187" type="debug" -> core: Custom ID of feed when loading from DB is '54'.
time="     1.187" type="debug" -> core: Custom ID of feed when loading from DB is '55'.
time="     1.187" type="debug" -> core: Custom ID of feed when loading from DB is '56'.
time="     1.187" type="debug" -> core: Custom ID of feed when loading from DB is '57'.
time="     1.187" type="debug" -> core: Custom ID of feed when loading from DB is '58'.
time="     1.187" type="debug" -> core: Custom ID of feed when loading from DB is '59'.
time="     1.188" type="debug" -> core: Custom ID of feed when loading from DB is '60'.
time="     1.188" type="debug" -> core: Custom ID of feed when loading from DB is '62'.
time="     1.188" type="debug" -> core: Custom ID of feed when loading from DB is '65'.
time="     1.188" type="debug" -> core: Custom ID of feed when loading from DB is '67'.
time="     1.189" type="debug" -> core: Custom ID of feed when loading from DB is '68'.
time="     1.189" type="debug" -> core: Custom ID of feed when loading from DB is '70'.
time="     1.189" type="debug" -> core: Custom ID of feed when loading from DB is '71'.
time="     1.189" type="debug" -> core: Custom ID of feed when loading from DB is '72'.
time="     1.190" type="debug" -> core: Custom ID of feed when loading from DB is '73'.
time="     1.190" type="debug" -> core: Custom ID of feed when loading from DB is '74'.
time="     1.190" type="debug" -> core: Custom ID of feed when loading from DB is '75'.
time="     1.190" type="debug" -> core: Custom ID of feed when loading from DB is '76'.
time="     1.190" type="debug" -> core: Custom ID of feed when loading from DB is '77'.
time="     1.192" type="debug" -> core: Custom ID of feed when loading from DB is '78'.
time="     1.192" type="debug" -> core: Custom ID of feed when loading from DB is '79'.
time="     1.193" type="debug" -> core: Custom ID of feed when loading from DB is '80'.
time="     1.193" type="debug" -> core: Custom ID of feed when loading from DB is '81'.
time="     1.193" type="debug" -> core: Custom ID of feed when loading from DB is '82'.
time="     1.193" type="debug" -> core: Custom ID of feed when loading from DB is '83'.
time="     1.194" type="debug" -> core: Custom ID of feed when loading from DB is '84'.
time="     1.194" type="debug" -> core: Custom ID of feed when loading from DB is '85'.
time="     1.194" type="debug" -> core: Custom ID of feed when loading from DB is '86'.
time="     1.195" type="debug" -> core: Custom ID of feed when loading from DB is '87'.
time="     1.195" type="debug" -> core: Custom ID of feed when loading from DB is '89'.
time="     1.195" type="debug" -> core: Custom ID of feed when loading from DB is '91'.
time="     1.195" type="debug" -> core: Custom ID of feed when loading from DB is '92'.
time="     1.195" type="debug" -> core: Custom ID of feed when loading from DB is '93'.
time="     1.195" type="debug" -> core: Custom ID of feed when loading from DB is '94'.
time="     1.196" type="debug" -> core: Custom ID of feed when loading from DB is '95'.
time="     1.196" type="debug" -> core: Custom ID of feed when loading from DB is '96'.
time="     1.197" type="debug" -> core: Custom ID of feed when loading from DB is '98'.
time="     1.197" type="debug" -> core: Custom ID of feed when loading from DB is '99'.
time="     1.197" type="debug" -> core: Custom ID of feed when loading from DB is '100'.
time="     1.198" type="debug" -> core: Custom ID of feed when loading from DB is '101'.
time="     1.198" type="debug" -> core: Custom ID of feed when loading from DB is '102'.
time="     1.198" type="debug" -> core: Custom ID of feed when loading from DB is '104'.
time="     1.198" type="debug" -> core: Custom ID of feed when loading from DB is '107'.
time="     1.198" type="debug" -> core: Custom ID of feed when loading from DB is '108'.
time="     1.198" type="debug" -> core: Custom ID of feed when loading from DB is '109'.
time="     1.199" type="debug" -> core: Custom ID of feed when loading from DB is '110'.
time="     1.199" type="debug" -> core: Custom ID of feed when loading from DB is '111'.
time="     1.200" type="debug" -> core: Custom ID of feed when loading from DB is '112'.
time="     1.200" type="debug" -> core: Custom ID of feed when loading from DB is '113'.
time="     1.200" type="debug" -> core: Custom ID of feed when loading from DB is '114'.
time="     1.200" type="debug" -> core: Custom ID of feed when loading from DB is '116'.
time="     1.200" type="debug" -> core: Custom ID of feed when loading from DB is '117'.
time="     1.200" type="debug" -> core: Custom ID of feed when loading from DB is '118'.
time="     1.201" type="debug" -> core: Custom ID of feed when loading from DB is '120'.
time="     1.201" type="debug" -> core: Custom ID of feed when loading from DB is '121'.
time="     1.201" type="debug" -> core: Custom ID of feed when loading from DB is '124'.
time="     1.201" type="debug" -> core: Custom ID of feed when loading from DB is '125'.
time="     1.201" type="debug" -> core: Custom ID of feed when loading from DB is '126'.
time="     1.201" type="debug" -> core: Custom ID of feed when loading from DB is '127'.
time="     1.202" type="debug" -> core: Custom ID of feed when loading from DB is '128'.
time="     1.202" type="debug" -> core: Custom ID of feed when loading from DB is '129'.
time="     1.202" type="debug" -> core: Custom ID of feed when loading from DB is '130'.
time="     1.202" type="debug" -> core: Custom ID of feed when loading from DB is '131'.
time="     1.202" type="debug" -> core: Custom ID of feed when loading from DB is '132'.
time="     1.203" type="debug" -> core: Custom ID of feed when loading from DB is '133'.
time="     1.203" type="debug" -> core: Custom ID of feed when loading from DB is '134'.
time="     1.203" type="debug" -> core: Custom ID of feed when loading from DB is '135'.
time="     1.203" type="debug" -> core: Custom ID of feed when loading from DB is '136'.
time="     1.203" type="debug" -> core: Custom ID of feed when loading from DB is '137'.
time="     1.204" type="debug" -> core: Custom ID of feed when loading from DB is '138'.
time="     1.204" type="debug" -> core: Custom ID of feed when loading from DB is '140'.
time="     1.205" type="debug" -> core: Custom ID of feed when loading from DB is '141'.
time="     1.205" type="debug" -> core: Custom ID of feed when loading from DB is '142'.
time="     1.205" type="debug" -> core: Custom ID of feed when loading from DB is '143'.
time="     1.205" type="debug" -> core: Custom ID of feed when loading from DB is '144'.
time="     1.206" type="debug" -> core: Custom ID of feed when loading from DB is '145'.
time="     1.206" type="debug" -> core: Custom ID of feed when loading from DB is '146'.
time="     1.206" type="debug" -> core: Custom ID of feed when loading from DB is '147'.
time="     1.206" type="debug" -> core: Custom ID of feed when loading from DB is '148'.
time="     1.206" type="debug" -> core: Custom ID of feed when loading from DB is '149'.
time="     1.206" type="debug" -> core: Custom ID of feed when loading from DB is '150'.
time="     1.206" type="debug" -> core: Custom ID of feed when loading from DB is '152'.
time="     1.207" type="debug" -> core: Custom ID of feed when loading from DB is '153'.
time="     1.208" type="debug" -> core: Custom ID of feed when loading from DB is '154'.
time="     1.208" type="debug" -> core: Custom ID of feed when loading from DB is '155'.
time="     1.209" type="debug" -> core: Custom ID of feed when loading from DB is '156'.
time="     1.209" type="debug" -> core: Custom ID of feed when loading from DB is '157'.
time="     1.209" type="debug" -> core: Custom ID of feed when loading from DB is '158'.
time="     1.211" type="debug" -> core: Custom ID of feed when loading from DB is '159'.
time="     1.211" type="debug" -> core: Custom ID of feed when loading from DB is '160'.
time="     1.212" type="debug" -> core: Custom ID of feed when loading from DB is '161'.
time="     1.212" type="debug" -> core: Custom ID of feed when loading from DB is '165'.
time="     1.212" type="debug" -> core: Custom ID of feed when loading from DB is '166'.
time="     1.212" type="debug" -> core: Custom ID of feed when loading from DB is '167'.
time="     1.212" type="debug" -> core: Custom ID of feed when loading from DB is '168'.
time="     1.213" type="debug" -> core: Custom ID of feed when loading from DB is '169'.
time="     1.214" type="debug" -> core: Custom ID of feed when loading from DB is '170'.
time="     1.214" type="debug" -> core: Custom ID of feed when loading from DB is '172'.
time="     1.214" type="debug" -> core: Custom ID of feed when loading from DB is '173'.
time="     1.214" type="debug" -> core: Custom ID of feed when loading from DB is '174'.
time="     1.214" type="debug" -> core: Custom ID of feed when loading from DB is '177'.
time="     1.214" type="debug" -> core: Custom ID of feed when loading from DB is '178'.
time="     1.215" type="debug" -> core: Custom ID of feed when loading from DB is '179'.
time="     1.215" type="debug" -> core: Custom ID of feed when loading from DB is '181'.
time="     1.215" type="debug" -> core: Custom ID of feed when loading from DB is '182'.
time="     1.216" type="debug" -> core: Custom ID of feed when loading from DB is '184'.
time="     1.217" type="debug" -> core: Custom ID of feed when loading from DB is '185'.
time="     1.217" type="debug" -> core: Custom ID of feed when loading from DB is '186'.
time="     1.217" type="debug" -> core: Custom ID of feed when loading from DB is '188'.
time="     1.217" type="debug" -> core: Custom ID of feed when loading from DB is '189'.
time="     1.217" type="debug" -> core: Custom ID of feed when loading from DB is '190'.
time="     1.217" type="debug" -> core: Custom ID of feed when loading from DB is '191'.
time="     1.218" type="debug" -> core: Custom ID of feed when loading from DB is '192'.
time="     1.218" type="debug" -> core: Custom ID of feed when loading from DB is '193'.
time="     1.218" type="debug" -> core: Custom ID of feed when loading from DB is '194'.
time="     1.218" type="debug" -> core: Custom ID of feed when loading from DB is '195'.
time="     1.219" type="debug" -> core: Custom ID of feed when loading from DB is '196'.
time="     1.219" type="debug" -> core: Custom ID of feed when loading from DB is '198'.
time="     1.219" type="debug" -> core: Custom ID of feed when loading from DB is '199'.
time="     1.219" type="debug" -> core: Custom ID of feed when loading from DB is '200'.
time="     1.219" type="debug" -> core: Custom ID of feed when loading from DB is '202'.
time="     1.219" type="debug" -> core: Custom ID of feed when loading from DB is '203'.
time="     1.219" type="debug" -> core: Custom ID of feed when loading from DB is '204'.
time="     1.220" type="debug" -> core: Custom ID of feed when loading from DB is '205'.
time="     1.220" type="debug" -> core: Custom ID of feed when loading from DB is '206'.
time="     1.220" type="debug" -> core: Custom ID of feed when loading from DB is '207'.
time="     1.221" type="debug" -> core: Custom ID of feed when loading from DB is '208'.
time="     1.221" type="debug" -> core: Custom ID of feed when loading from DB is '209'.
time="     1.221" type="debug" -> core: Custom ID of feed when loading from DB is '210'.
time="     1.221" type="debug" -> core: Custom ID of feed when loading from DB is '212'.
time="     1.222" type="debug" -> core: Custom ID of feed when loading from DB is '213'.
time="     1.222" type="debug" -> core: Custom ID of feed when loading from DB is '214'.
time="     1.222" type="debug" -> core: Custom ID of feed when loading from DB is '215'.
time="     1.223" type="debug" -> core: Custom ID of feed when loading from DB is '216'.
time="     1.223" type="debug" -> core: Custom ID of feed when loading from DB is '217'.
time="     1.223" type="debug" -> core: Custom ID of feed when loading from DB is '218'.
time="     1.223" type="debug" -> core: Custom ID of feed when loading from DB is '219'.
time="     1.223" type="debug" -> core: Custom ID of feed when loading from DB is '220'.
time="     1.223" type="debug" -> core: Custom ID of feed when loading from DB is '221'.
time="     1.224" type="debug" -> core: Custom ID of feed when loading from DB is '222'.
time="     1.224" type="debug" -> core: Custom ID of feed when loading from DB is '223'.
time="     1.224" type="debug" -> core: Custom ID of feed when loading from DB is '224'.
time="     1.224" type="debug" -> core: Custom ID of feed when loading from DB is '225'.
time="     1.224" type="debug" -> core: Custom ID of feed when loading from DB is '226'.
time="     1.225" type="debug" -> core: Custom ID of feed when loading from DB is '227'.
time="     1.225" type="debug" -> core: Custom ID of feed when loading from DB is '228'.
time="     1.226" type="debug" -> core: Custom ID of feed when loading from DB is '229'.
time="     1.226" type="debug" -> core: Custom ID of feed when loading from DB is '230'.
time="     1.226" type="debug" -> core: Custom ID of feed when loading from DB is '231'.
time="     1.226" type="debug" -> core: Custom ID of feed when loading from DB is '232'.
time="     1.226" type="debug" -> core: Custom ID of feed when loading from DB is '233'.
time="     1.227" type="debug" -> core: Custom ID of feed when loading from DB is '234'.
time="     1.227" type="debug" -> core: Custom ID of feed when loading from DB is '236'.
time="     1.227" type="debug" -> core: Custom ID of feed when loading from DB is '237'.
time="     1.227" type="debug" -> core: Custom ID of feed when loading from DB is '238'.
time="     1.227" type="debug" -> core: Custom ID of feed when loading from DB is '239'.
time="     1.228" type="debug" -> core: Custom ID of feed when loading from DB is '240'.
time="     1.228" type="debug" -> core: Custom ID of feed when loading from DB is '241'.
time="     1.228" type="debug" -> core: Custom ID of feed when loading from DB is '242'.
time="     1.228" type="debug" -> core: Custom ID of feed when loading from DB is '243'.
time="     1.257" type="debug" -> core: Custom ID of feed when loading from DB is '244'.
time="     1.258" type="debug" -> core: Custom ID of feed when loading from DB is '245'.
time="     1.258" type="debug" -> core: Custom ID of feed when loading from DB is '246'.
time="     1.259" type="debug" -> database: SQLite database connection 'RecycleBin' to file '/home/chris/.config/RSS Guard 4/database/database.db' seems to be established.
time="     2.984" type="debug" -> database: SQLite database connection 'ImportantNode' to file '/home/chris/.config/RSS Guard 4/database/database.db' seems to be established.
time="     2.999" type="debug" -> database: SQLite database connection 'UnreadNode' to file '/home/chris/.config/RSS Guard 4/database/database.db' seems to be established.
time="     3.012" type="debug" -> database: SQLite database connection 'LabelsNode' to file '/home/chris/.config/RSS Guard 4/database/database.db' seems to be established.
time="     3.992" type="debug" -> database: SQLite connection 'StandardServiceRoot' is already active.
time="     3.992" type="debug" -> database: SQLite database connection 'StandardServiceRoot' to file '/home/chris/.config/RSS Guard 4/database/database.db' seems to be established.
time="     4.058" type="debug" -> database: SQLite database connection 'TtRssServiceEntryPoint' to file '/home/chris/.config/RSS Guard 4/database/database.db' seems to be established.
time="     4.058" type="debug" -> gui: User wants to have tray icon.
time="     4.058" type="warning" -> gui: Showing tray icon with little delay.
time="     4.058" type="debug" -> gui: Feed list item expanded - chris (RSS/ATOM/JSON)
time="     4.059" type="debug" -> gui: Feed list item expanded - Labels
time="     4.059" type="debug" -> gui: Feed list item expanded - Regex queries
time="     4.059" type="debug" -> gui: Feed list item expanded - RSS Guard
time="     4.059" type="debug" -> gui: Feed list item expanded - Technology
time="     4.059" type="debug" -> gui: Feed list item expanded - Misc
time="     4.059" type="debug" -> gui: Feed list item expanded - Climate
time="     4.059" type="debug" -> gui: Feed list item expanded - Computers
time="     4.059" type="debug" -> gui: Feed list item expanded - Entertainment
time="     4.059" type="debug" -> gui: Feed list item expanded - Friends
time="     4.059" type="debug" -> gui: Feed list item expanded - Health
time="     4.059" type="debug" -> gui: Feed list item expanded - News
time="     4.059" type="debug" -> gui: Feed list item expanded - Politics
time="     4.059" type="debug" -> gui: Feed list item expanded - Science
time="     4.059" type="debug" -> gui: Feed list item expanded - Sports
time="     4.059" type="debug" -> gui: Feed list item expanded - Terrorism
time="     4.059" type="debug" -> gui: Feed list item expanded - Weblogs
time="     4.059" type="debug" -> gui: Feed list item expanded - KDE
time="     4.059" type="debug" -> gui: Feed list item expanded - Mozilla
time="     4.059" type="debug" -> gui: Feed list item expanded - Slackware
time="     4.059" type="debug" -> gui: Feed list item expanded - Software
time="     4.059" type="debug" -> gui: Feed list item expanded - Unix
time="     4.059" type="debug" -> gui: Feed list item expanded - Windows
time="     4.059" type="debug" -> gui: Feed list item expanded - Games
time="     4.059" type="debug" -> gui: Feed list item expanded - Humor
time="     4.059" type="debug" -> gui: Feed list item expanded - Off The Wall
time="     4.059" type="debug" -> gui: Feed list item expanded - Philippines
time="     4.059" type="debug" -> gui: Feed list item expanded - The Epoch Times
time="     4.059" type="debug" -> core: No execution message received from other app instances.
time="     4.204" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     4.305" type="debug" -> gui: Hovered link: 'QUrl()'.
time="     4.306" type="debug" -> core: Silencing GUI message: ''.
time="     5.282" type="debug" -> network: Destroying Downloader instance.
time="     5.282" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="     6.998" type="warning" -> gui: Tray icon is available, showing now.
time="     7.006" type="debug" -> gui: Creating SystemTrayIcon instance.
time="     7.006" type="debug" -> gui: Showing tray icon immediately.
time="     7.017" type="debug" -> gui: Tray icon displayed.
time="    12.421" type="debug" -> gui: Message splitter moved.
time="    14.603" type="debug" -> gui: Message splitter moved.
time="    22.652" type="debug" -> nodejs: Packages '@cliqz/adblocker@1.26.7' are up-to-date.
time="    22.652" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="    23.584" type="debug" -> network: Destroying Downloader instance.
time="    23.584" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="    23.590" type="debug" -> adblock: Downloaded filter list from 'https://easylist.to/easylist/easylist.txt'.
time="    23.591" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="    24.426" type="debug" -> network: Destroying Downloader instance.
time="    24.426" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="    24.434" type="debug" -> adblock: Downloaded filter list from 'https://easylist.to/easylist/easyprivacy.txt'.
time="    24.502" type="debug" -> adblock: Attempting to start AdBlock server.
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE 127.0.0.1:48484
    at listenOnPrimaryHandle (node:net:1940:18)
    at rr (node:internal/cluster/child:163:12)
    at Worker.<anonymous> (node:internal/cluster/child:113:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:526:35)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on Server instance at:
    at listenOnPrimaryHandle (node:net:1941:21)
    at rr (node:internal/cluster/child:163:12)
    [... lines matching original stack trace ...]
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -98,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: '127.0.0.1',
  port: 48484
}

Node.js v20.9.0
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE 127.0.0.1:48484
    at listenOnPrimaryHandle (node:net:1940:18)
    at rr (node:internal/cluster/child:163:12)
    at Worker.<anonymous> (node:internal/cluster/child:113:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:526:35)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on Server instance at:
    at listenOnPrimaryHandle (node:net:1941:21)
    at rr (node:internal/cluster/child:163:12)
    [... lines matching original stack trace ...]
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -98,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: '127.0.0.1',
  port: 48484
}

Node.js v20.9.0
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE 127.0.0.1:48484
    at listenOnPrimaryHandle (node:net:1940:18)
    at rr (node:internal/cluster/child:163:12)
    at Worker.<anonymous> (node:internal/cluster/child:113:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:526:35)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on Server instance at:
    at listenOnPrimaryHandle (node:net:1941:21)
    at rr (node:internal/cluster/child:163:12)
    [... lines matching original stack trace ...]
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -98,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: '127.0.0.1',
  port: 48484
}

Node.js v20.9.0
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE 127.0.0.1:48484
    at listenOnPrimaryHandle (node:net:1940:18)
    at rr (node:internal/cluster/child:163:12)
    at Worker.<anonymous> (node:internal/cluster/child:113:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:526:35)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on Server instance at:
    at listenOnPrimaryHandle (node:net:1941:21)
    at rr (node:internal/cluster/child:163:12)
    [... lines matching original stack trace ...]
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -98,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: '127.0.0.1',
  port: 48484
}

Node.js v20.9.0
time="    27.791" type="critical" -> adblock: Process exited with exit code '0' so check application log for more details.
time="    49.026" type="debug" -> core: Saved data with auto-saver for 'CookieJar' and method 'saveCookies'.
time="   469.624" type="debug" -> gui: Main window's close event
time="   469.624" type="debug" -> gui: Main window's hide event
time="   731.724" type="debug" -> core: Silencing GUI message: 'Close opened modal dialogs first.'.

### Operating system and version

Operating System: Slackware64-current
KDE Plasma Version: 5.27.9
KDE Frameworks Version: 5.111.0
Qt Version: 5.15.11
Kernel Version: 6.1.60 (64-bit)
Graphics Platform: X11

RSS Guard version: 4.5.3

**Comment by martinrotter** [comment]
ime=" 24.502" type="debug" -> adblock: Attempting to start AdBlock server.
node:events:492
throw er; // Unhandled 'error' event
^

Error: bind EADDRINUSE [127.0.0.1:48484](http://127.0.0.1:48484/)


Meaning something is already blocking port 48484 on localhost. Restart PC.

**Comment by chrisretusn** [comment]
That did it. Lesson learned for me. Thanks!
