### ISSUE TITLE
Option to enable the old mode of deleting the messages

### ISSUE THREAD

**Issue by soredake** [martinrotter/rssguard#118]
#### Brief description of the issue.

Option to enable the direct removing immediately to the recycle bin, not just this
![png](https://cloud.githubusercontent.com/assets/5204968/26760887/c191a87e-4912-11e7-9f0c-35fac1db67e6.png) and delete after you switch the feed.
Like in old versions (3.3.5)

#### How to reproduce the bug?

1. 
2. 
3.

**Comment by martinrotter** [comment]
Will think about this. This is now in RSS Guard because of different way of handling the SQL connection to the list of displayed messages, which will allow for #102 and some other things.

I will think about if I will allow this to be switchable.

**Comment by martinrotter** [comment]
Btw, the message is of course moved to recycle bin immediately.

**Comment by martinrotter** [comment]
So, to explain:

1) New version of RSS Guard uses FASTER algorithm to work with list of messages. It allows for more complex operations (in regard with #102) with GREAT speed. Technically, when you do any destructive operation in list of displayed messages (like deleting, restoring etc.) the list is now NOT RELOADED -> this brings better performance, LESS DB traffic and little less of memory/hdd activity, which is good.
2) The consequences of point 1 are that it is more difficult to make some deleted/restored messages look disappear instantly, this cannot be done. It can be hacked (the row is not removed, it is only hidden), but that approach brings some difficulties into the source code and makes it harder to understand.

Therefore it is very unlikely that this can be implemented in the near future. I will make #102 before releasing new version and it is possible that something will change and this issue will be solvable by then. But now, it is no good to implement. I will enhance current solution to make it more pleasant to work with for now (the cursor will move to next item when current is "removed").
