### ISSUE TITLE
[FR]: Why are there 2 image links? Can we get rid of one?

### ISSUE THREAD

**Issue by inson1** [martinrotter/rssguard#1180]
### Brief description of the feature request

![image](https://github.com/martinrotter/rssguard/assets/75314629/860556eb-7a86-44e4-b9d0-46c0c5e41a09)

**Comment by martinrotter** [comment]
Yes, there is a number of related issues surrounding no-web-engine article previewer, I plan to merge look-layout of both viewers with new default skin I plan to make.

RSS Guard will then use same HTML layout in both variants (full, lite).

**Comment by martinrotter** [comment]
Fixed by merging layout of full/lite article viewer.
