### ISSUE TITLE
[BUG]: Adblock error - What is wrong? 

### ISSUE THREAD

**Issue by inson1** [martinrotter/rssguard#1182]
### Brief description of the issue

![image](https://github.com/martinrotter/rssguard/assets/75314629/994c034a-6204-42c6-91df-276df9f9201f)

![image](https://github.com/martinrotter/rssguard/assets/75314629/2bed1b97-3096-48f8-8dd5-5f0ef00d9266)

![image](https://github.com/martinrotter/rssguard/assets/75314629/d804e046-88b3-4c89-83f4-590df0c8ce19)

### How to reproduce the bug?

I cant start Adblock.

### What was the expected result?

.

### What actually happened?

.

### Debug log

No log

### Operating system and version

* OS: Windows 10
* RSS Guard version: 4.5.3

**Comment by inson1** [comment]
Its not duplicate #1178 , it doesnt have the log.

**Comment by martinrotter** [comment]
https://github.com/martinrotter/rssguard/issues/1187#issuecomment-1791940611
