### ISSUE TITLE
[FR]: Number of feeds & sub-categories indicators for feed categories and sub-categories

### ISSUE THREAD

**Issue by RetroAbstract** [martinrotter/rssguard#1183]
### Brief description of the feature request

This feature would add visual indicators to feed categories and sub-categories in the article viewer when either a feed category or sub-category are clicked on, letting the user know how many feeds & sub-categories are in their feed categories and sub-categories, expanding on the already present feed & category number indicators on the standard RSS accounts.

Visual example going from Category to Sub-category to Sub-sub-category:

![1](https://github.com/martinrotter/rssguard/assets/103272301/e8f8e65a-1294-4e36-ba82-c456627bc803)
![2](https://github.com/martinrotter/rssguard/assets/103272301/554dbd24-2409-4062-a0d7-3355605276b9)
![3](https://github.com/martinrotter/rssguard/assets/103272301/a62bd9f9-08ad-465e-9c94-990cc3911a55)

Thanks!

**Comment by martinrotter** [comment]
![image](https://github.com/martinrotter/rssguard/assets/1255302/560ad7f2-e95b-4e2b-8912-717588a776a3)

**Comment by RetroAbstract** [comment]
Thanks :)
