### ISSUE TITLE
Disable auto-updating notification

### ISSUE THREAD

**Issue by jluttine** [martinrotter/rssguard#119]
#### Brief description of the issue.

This is not an issue, just a feature request. When rssguard starts auto-updating the feeds it shows a pop-up notification. Can this be disabled? It is really annoying to get these notifications every hour. I do like notifications about new messages though.

**Comment by martinrotter** [comment]
I will make it switchable in settings. Is this ok?

**Comment by jluttine** [comment]
That would be awesome! Thanks.
