### ISSUE TITLE
[FR]: respect the date format from system

### ISSUE THREAD

**Issue by gpunktschmitz** [martinrotter/rssguard#1193]
### Brief description of the feature request

The list of articles shows date format in a "fixed"/language specific format. I'd prefer the app to respect the language format (shortdateformat) of the system beeing used, or make it editable so the language specific format could be overwritten.

examples:
setting languge to British English results in date format: 01/01/1970
setting languge to German results in date format: 01.01.1970

I would prefer the date format to either language to be 1970-01-01

**Comment by martinrotter** [comment]
language specific format can be overwritten in settings

![image](https://github.com/martinrotter/rssguard/assets/1255302/456f031b-2826-486b-8566-bc2767302a67)
