### ISSUE TITLE
[BUG]: FreshRSS connects to GReader API but doesn't update feeds

### ISSUE THREAD

**Issue by dCo3lh0** [martinrotter/rssguard#1196]
### Brief description of the issue

I have FreshRSS here, i've tried using the Google Reader API, and it connects, and the lateral feed list shows entirely, but, the feeds count is 0, i tried to refresh, resync feeds, but it keeps at 0.

### How to reproduce the bug?

1. Add Account
2. FreshRSS
3. Test Google Reader API, it shows "You are good to go"
4. Feed List shows, at the default of 0
5. Resync news, it keeps at 0.

### What was the expected result?

show all the news at my freshrss selfhosted instance.

### What actually happened?

keeps feeds at 0.

### Debug log

[rssguard.log](https://github.com/martinrotter/rssguard/files/13302866/rssguard.log)

### Operating system and version

* OS: LMDE 5 (Debian 11 - Bullseye)
* RSS Guard version: 4.5.3

**Comment by martinrotter** [comment]
This seems to be some kind of problem with your FreshRSS server because it reports `QNetworkReply::InternalServerError` when RSS Guard tries to fetch articles.

Could that FreshRSS instance be made available online for testing for me? If not, I am afraid there is nothing I can do as on my instance, all things work fine.

**Comment by martinrotter** [comment]
Just tested with official/latest FreshRSS docker image in clean RSS Guard environment. All works.

![image](https://github.com/martinrotter/rssguard/assets/1255302/af9408e0-9e14-4f42-a115-f4ed33bfa29c)

**Comment by dCo3lh0** [comment]
i think i discovered the issue martin, by pure luck, it seems that it has something to do with the option "intelligent synchronization algorithm", i've unmarked this option and chose to sync the last 200 articles, could be any number, but i did just only unmark this intelligent sync algorithm option, and it synced automatically.

**Comment by martinrotter** [comment]
Well, is this your local instance? I still think there is something wrong with the instance itself.

Also, perhaps this was problem with some feed which contains big/huge number of articles?

**Comment by dCo3lh0** [comment]
yeah its a local instance, its working fine now, but about the problem being with some feed with a big number of articles, absolutely, there is feeds here that may have in the 10s of thousands of articles, i think news outlets is a example of this. But even if there was a feed in the dozens of thousands, it didn't update any other feeds at all, not a single of of them, all of them kept at 0, but when i unmarked the algorithm option and market the last 200 it worked.
