### ISSUE TITLE
Not apply some icon themes

### ISSUE THREAD

**Issue by varlesh** [martinrotter/rssguard#12]
For example Numix Circle or Papirus GTK. libqt5svg5 installed
OS Ubuntu 16.04 Unity
rssguard-qt5-git_3.2.2.1462251283.e1742d8

![2016-05-07 00-18-27](https://cloud.githubusercontent.com/assets/8083855/15086403/44221b30-13e9-11e6-99dd-118fe876d30b.png)

LOG:
`rssguard
[rssguard] DEBUG: Instantiated Application class.
[rssguard] DEBUG: Available icon theme paths: '/usr/share/icons', '/usr/share/pixmaps', ':/icons', '/usr/share/rssguard/icons'.
[rssguard] DEBUG: Initializing settings in '/home/alex/.rssguard/data/config/config.ini' (non-portable way).
[rssguard] DEBUG: Installed icon themes are: '-', 'Numix', 'Numix Circle', 'Numix Circle Light', 'Numix Light', 'Hicolor', 'Ubuntu-Mono-Dark', 'Ubuntu-Mono-Light', 'GNOME', 'Papirus Dark GTK', 'Papirus GTK', 'HighContrast', 'unity-icon-theme', 'unity-webapps-applications', 'Suru', 'Ubuntu-Mobile', 'DMZ (Black)', 'DMZ (White)', 'Adwaita', 'Humanity', 'Humanity-Dark', 'LoginIcons'.
[rssguard] DEBUG: Loading icon theme 'Numix Circle'.
[rssguard] DEBUG: Loading skin 'base/vergilius.xml'.
[rssguard] DEBUG: Skin 'base/vergilius.xml' loaded.
[rssguard] WARNING: Application localization 'ru_RU' was not loaded.
[rssguard] WARNING: Qt localization 'en_GB' was not loaded.
[rssguard] DEBUG: Creating main application form in thread: '0x7f950ebb88c0'.
[rssguard] DEBUG: Creating tray icon menu.
[rssguard] DEBUG: Working database source was determined as SQLite file-based database.
[rssguard] DEBUG: File-based SQLite database connection 'MessagesModel' to file '/home/alex/.rssguard/data/database/local/database.db' seems to be established.
[rssguard] DEBUG: File-based SQLite database has version '6'.
[rssguard] DEBUG: Auto-update timer started with interval 60000.
[rssguard] DEBUG: Adjusting column resize modes for MessagesView.
[rssguard] DEBUG: Showing the main window when the application is starting.
[rssguard] DEBUG: Showing tray icon.
[rssguard] DEBUG: Creating SystemTrayIcon instance.
[rssguard] DEBUG: Showing tray icon with 1000 ms delay.
[rssguard] DEBUG: File-based SQLite database connection 'StandardServiceEntryPoint' to file '/home/alex/.rssguard/data/database/local/database.db' seems to be established.
[rssguard] DEBUG: File-based SQLite database connection 'StandardServiceRoot' to file '/home/alex/.rssguard/data/database/local/database.db' seems to be established.
[rssguard] DEBUG: File-based SQLite database connection 'RecycleBin' to file '/home/alex/.rssguard/data/database/local/database.db' seems to be established.
[rssguard] DEBUG: SQLite connection 'StandardServiceRoot' is already active.
[rssguard] DEBUG: File-based SQLite database connection 'StandardServiceRoot' to file '/home/alex/.rssguard/data/database/local/database.db' seems to be established.
[rssguard] DEBUG: File-based SQLite database connection 'TtRssServiceEntryPoint' to file '/home/alex/.rssguard/data/database/local/database.db' seems to be established.
[rssguard] DEBUG: File-based SQLite database connection 'OwnCloudServiceEntryPoint' to file '/home/alex/.rssguard/data/database/local/database.db' seems to be established.
[rssguard] DEBUG: Requesting update for all feeds on application startup.
[rssguard] WARNING: Failed to connect notifications to 'NotificationClosed' signal, last error: ''.
[rssguard] DEBUG: OS asked application to save its state.
[rssguard] DEBUG: Tray icon displayed.
[rssguard] DEBUG: Performing feed updates in thread: '0x7f94e6eda700'.
[rssguard] DEBUG: Settings of BaseNetworkAccessManager loaded.
[rssguard] DEBUG: Settings of BaseNetworkAccessManager loaded.
[rssguard] DEBUG: Destroying SilentNetworkAccessManager instance.
[rssguard] WARNING: QObject: Cannot create children for a parent that is in a different thread.
(Parent is Application(0x7ffe149f1328), parent's thread is QThread(0x1e7a7d0), current thread is QThread(0x245c240)
[rssguard] DEBUG: File-based SQLite database connection 'StandardFeed' to file '/home/alex/.rssguard/data/database/local/database.db' seems to be established.
[rssguard] DEBUG: SQLite connection 'StandardFeed' is already active.
[rssguard] DEBUG: File-based SQLite database connection 'StandardFeed' to file '/home/alex/.rssguard/data/database/local/database.db' seems to be established.
[rssguard] DEBUG: Made progress in feed updates: 1/1 (id of feed is 1).
[rssguard] DEBUG: There is request to reload feed model, reloading the 1 items individually.
[rssguard] DEBUG: Finished feed updates in thread: '0x7f94e6eda700'.
[rssguard] DEBUG: Destroying SilentNetworkAccessManager instance.
[rssguard] DEBUG: Settings of BaseNetworkAccessManager loaded.
[rssguard] DEBUG: Destroying SilentNetworkAccessManager instance.
[rssguard] DEBUG: Starting auto-update event, pass 39/40.
[rssguard] DEBUG: Starting auto-update event, pass 38/40.
[rssguard] WARNING: QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
[rssguard] WARNING: QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
[rssguard] DEBUG: Starting auto-update event, pass 37/40.
[rssguard] DEBUG: Starting auto-update event, pass 36/40.`

**Comment by martinrotter** [comment]
Thank you, will check soon. :)

**Comment by martinrotter** [comment]
Fixed in [master].

**Comment by varlesh** [comment]
Thx, working fine.
Maybe better add fallback or change icons name for some actions?
 
actionSwitchMainWindow - "focus-windows" ("window-close")
actionSettings - "document-properties"  ("emblem-system") 
actionEditSelectedItem and actionServiceEdit - "document-edit" ("text-x-script")
actionViewSelectedItemsNewspaperMode - "format-justify-fill" ("text-x-generic")
actionCheckForUpdates - "system-upgrade" ("applications-internet")

**Comment by martinrotter** [comment]
YES, if you feel some icons should be changed, post them here. I assigned icons which I felt were okay, but I can be wrong.

I will check those icons and replace them. Thank you.
