### ISSUE TITLE
message in blank

### ISSUE THREAD

**Issue by ki00** [martinrotter/rssguard#120]
#### Brief description of the issue.

Recently the messages suddenly do not load, and it stay blank (or black), need to restart laptop (does not know if it is because of linux KaOS or rss guard). I can not give a log, so if it is not enough info or already posted, close it). Thank you.

#### How to reproduce the bug?

1. Use the application
2. Suddenly it gets blank
3. 

#### What is the expected result?

Load the messages

#### What actually happened?

Do not load any messages anymore

#### Other information (logs, see Wiki)

this is all the log that gives (with wiki command): bash: ./rssguard: No existe el fichero o el directorio
a screenshot: https://ibb.co/d5MeDF

**Comment by ki00** [comment]
now is working, sorry for the post

**Comment by martinrotter** [comment]
Qt bug.
