### ISSUE TITLE
[BUG]: Crash when trying to access the localization menu

### ISSUE THREAD

**Issue by zipfile6209** [martinrotter/rssguard#1200]
### Brief description of the issue

When trying to access settings -> localization, rssguard crashes.

### How to reproduce the bug?

trying to access settings -> localization

### What was the expected result?

no crash

### What actually happened?

crash

### Debug log

time="     0.006" type="debug" -> core: Starting RSS Guard 4.5.4.
time="     0.007" type="debug" -> core: Current UTC date/time is 2023-11-13T14:17:54Z.
Gtk-Message: 15:17:54.904: Failed to load module "xapp-gtk3-module"
time="     0.608" type="warning" -> Qt: Session management error: Could not open network socket
time="     0.615" type="critical" -> core: Missing value after '--log'.
time="     0.616" type="debug" -> core: Initializing settings in '/home/user/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/config/config.ini' (non-portable way).
time="     0.616" type="debug" -> core: Starting to load active localization. Desired localization is 'es_ES'.
time="     0.625" type="debug" -> core: Application localization 'es_ES' loaded successfully, specifically sublocalization 'es_ES' was loaded.
time="     0.637" type="debug" -> core: Qt localization 'es_ES' loaded successfully.
time="     0.975" type="debug" -> database: File-based SQLite database connection 'DatabaseFactory' to file '/home/user/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.975" type="debug" -> database: File-based SQLite database has version '7'.
time="     0.976" type="debug" -> gui: Available icon theme paths: (/app/share/icons, /usr/share/icons, /usr/share/runtime/share/icons, /run/host/user-share/icons, /run/host/share/icons, :/icons, :/graphics, /home/user/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/icons, /app/bin/icons)
time="     1.053" type="debug" -> gui: Installed icon themes are: '', 'Breeze_Snow', 'breeze', 'breeze-dark', 'breeze_cursors', 'hicolor', 'default', 'Yaru-blue', 'Yaru-magenta', 'Yaru-olive', 'Yaru-prussiangreen', 'Yaru-purple', 'Yaru-red', 'Yaru-sage', 'Yaru-viridian', 'Yaru', 'Yaru-bark', 'Yaru-viridian-dark', 'Yaru-sage-dark', 'Yaru-red-dark', 'Yaru-purple-dark', 'Yaru-prussiangreen-dark', 'Yaru-olive-dark', 'Yaru-magenta-dark', 'Yaru-blue-dark', 'Yaru-dark', 'Yaru-bark-dark', 'GoogleDot-Black', 'GoogleDot-White', 'XCursor-Pro-Dark', 'XCursor-Pro-Light', 'Bibata-Modern-Classic', 'Bibata-Modern-Ice', 'Bibata-Original-Classic', 'Bibata-Original-Ice', 'Numix-Circle', 'gnome', 'HighContrast', 'Numix-Light', 'Numix', 'Mint-Y-Legacy-Dark-Blue', 'Mint-Y-Legacy-Dark-Brown', 'Mint-Y-Legacy-Dark-Grey', 'Mint-Y-Legacy-Dark-Orange', 'Mint-Y-Legacy-Dark-Pink', 'Mint-Y-Legacy-Dark-Purple', 'Mint-Y-Legacy-Dark-Red', 'Mint-Y-Legacy-Dark-Sand', 'Mint-Y-Legacy-Dark-Teal', 'Mint-Y-Legacy-Dark-Yellow', 'Mint-Y-Legacy', 'Mint-Y-Legacy-Aqua', 'Mint-Y-Legacy-Blue', 'Mint-Y-Legacy-Brown', 'Mint-Y-Legacy-Dark', 'Mint-Y-Legacy-Dark-Aqua', 'Mint-Y-Legacy-Grey', 'Mint-Y-Legacy-Orange', 'Mint-Y-Legacy-Pink', 'Mint-Y-Legacy-Purple', 'Mint-Y-Legacy-Red', 'Mint-Y-Legacy-Sand', 'Mint-Y-Legacy-Teal', 'Mint-Y-Legacy-Yellow', 'ePapirus-Dark', 'ePapirus', 'Papirus-Light', 'Papirus-Dark', 'Papirus', 'Mint-X', 'Mint-X-Aqua', 'Mint-X-Blue', 'Mint-X-Brown', 'Mint-X-Dark', 'Mint-X-Grey', 'Mint-X-Orange', 'Mint-X-Pink', 'Mint-X-Purple', 'Mint-X-Red', 'Mint-X-Sand', 'Mint-X-Teal', 'Mint-X-Yellow', 'Mint-Y-Dark-Teal', 'Mint-Y-Aqua', 'Mint-Y-Blue', 'Mint-Y-Brown', 'Mint-Y-Dark', 'Mint-Y-Dark-Aqua', 'Mint-Y-Dark-Blue', 'Mint-Y-Dark-Brown', 'Mint-Y-Dark-Grey', 'Mint-Y-Dark-Orange', 'Mint-Y-Dark-Pink', 'Mint-Y-Dark-Purple', 'Mint-Y-Dark-Red', 'Mint-Y-Dark-Sand', 'Mint-Y-Grey', 'Mint-Y-Orange', 'Mint-Y-Pink', 'Mint-Y-Purple', 'Mint-Y-Red', 'Mint-Y-Sand', 'Mint-Y-Teal', 'Mint-Y', 'Numix-Circle-Light', 'DMZ-Black', 'DMZ-White', 'Adwaita', 'Breeze', 'Breeze Dark', 'Faenza'
time="     1.053" type="debug" -> gui: Loading icon theme 'Breeze'.
time="     1.053" type="debug" -> gui: Found path of base skin: ':/skins/nudus-base'.
time="     1.053" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_wrapper.html' for the skin.
time="     1.053" type="debug" -> gui: Local file ':/skins/nudus-light/html_style.css' exists, using it for the skin.
time="     1.053" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_enclosure_image.html' for the skin.
time="     1.053" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_single_message.html' for the skin.
time="     1.053" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_enclosure_every.html' for the skin.
time="     1.053" type="debug" -> gui: Local file ':/skins/nudus-light/qt_style.qss' exists, using it for the skin.
time="     1.053" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_adblocked.html' for the skin.
time="     1.054" type="debug" -> gui: Setting style: 'Fusion'.
time="     1.054" type="debug" -> gui: Skin 'nudus-light' loaded.
time="     1.056" type="warning" -> core: User CSS style was not provided in file '/home/user/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/web/user-styles.css'.
time="     1.056" type="debug" -> network: Persistent web data storage path: '/home/user/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/web/storage'.
time="     1.056" type="debug" -> network: Disabling application-wide proxy completely.
time="     1.057" type="debug" -> core: SQLite version: '3.42.0'.
time="     1.071" type="debug" -> core: OpenSSL version: 'OpenSSL 3.1.4 24 Oct 2023'.
time="     1.071" type="debug" -> core: OpenSSL supported: 'true'.
time="     1.072" type="debug" -> core: Global thread pool has 6 threads.
time="     1.072" type="debug" -> core: Instantiated class  'Application'.
time="     1.074" type="debug" -> database: SQLite database connection 'MessagesModel' to file '/home/user/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     1.080" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, Feeds.is_rtl, CASE WHEN LENGTH(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Messages.labels LIKE "%." || Labels.custom_id || ".%") as msg_labels, Messages.labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1;'.
time="     1.080" type="debug" -> core: Auto-download timer started with interval 10000 ms.
time="     1.080" type="debug" -> core: Creating FeedDownloader singleton.
time="     1.114" type="debug" -> gui: Creating main application form in thread: '0x7ff40963cf40'.
time="     1.133" type="debug" -> gui: Current row changed - proxy 'QModelIndex(-1,-1,0x0,QObject(0x0))', source 'QModelIndex(-1,-1,0x0,QObject(0x0))'.
time="     1.156" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     1.240" type="debug" -> gui: Creating tray icon menu.
time="     1.261" type="debug" -> CTRL is NOT pressed while sorting articles - sorting with standard mode.
time="     1.261" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, Feeds.is_rtl, CASE WHEN LENGTH(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Messages.labels LIKE "%." || Labels.custom_id || ".%") as msg_labels, Messages.labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1 ORDER BY Messages.date_created DESC;'.
time="     1.265" type="debug" -> core: Showing the main window when the application is starting.
time="     1.322" type="debug" -> database: SQLite database connection 'FeedReader' to file '/home/user/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     1.324" type="debug" -> database: SQLite database connection 'FeedlyEntryPoint' to file '/home/user/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     1.326" type="debug" -> database: SQLite database connection 'GmailEntryPoint' to file '/home/user/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     1.327" type="debug" -> database: SQLite database connection 'GreaderEntryPoint' to file '/home/user/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     1.328" type="debug" -> database: SQLite database connection 'OwnCloudServiceEntryPoint' to file '/home/user/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     1.329" type="debug" -> database: SQLite database connection 'StandardServiceEntryPoint' to file '/home/user/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     1.330" type="debug" -> database: SQLite database connection 'StandardServiceRoot' to file '/home/user/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     1.332" type="debug" -> database: SQLite database connection 'RecycleBin' to file '/home/user/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     1.333" type="debug" -> database: SQLite database connection 'ImportantNode' to file '/home/user/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     1.333" type="debug" -> database: SQLite database connection 'UnreadNode' to file '/home/user/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     1.334" type="debug" -> database: SQLite database connection 'LabelsNode' to file '/home/user/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     1.337" type="debug" -> database: SQLite database connection 'TtRssServiceEntryPoint' to file '/home/user/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     1.338" type="debug" -> gui: User wants to have tray icon.
time="     1.338" type="warning" -> gui: Showing tray icon with little delay.
time="     1.338" type="debug" -> gui: Feed list item expanded - user (RSS/ATOM/JSON)
time="     1.339" type="debug" -> core: No execution message received from other app instances.
time="     1.463" type="debug" -> gui: Hovered link: 'QUrl()'.
time="     4.289" type="warning" -> gui: Tray icon is available, showing now.
time="     4.292" type="debug" -> gui: Creating SystemTrayIcon instance.
time="     4.299" type="debug" -> gui: Showing tray icon immediately.
time="     4.299" type="debug" -> gui: Tray icon displayed.
time="     7.837" type="debug" -> gui: Found path of base skin: ':/skins/nudus-base'.
time="     7.837" type="debug" -> gui: Local file ':/skins/nudus-dark/html_wrapper.html' exists, using it for the skin.
time="     7.837" type="debug" -> gui: Local file ':/skins/nudus-dark/html_style.css' exists, using it for the skin.
time="     7.837" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_enclosure_image.html' for the skin.
time="     7.837" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_single_message.html' for the skin.
time="     7.837" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_enclosure_every.html' for the skin.
time="     7.837" type="debug" -> gui: Local file ':/skins/nudus-dark/qt_style.qss' exists, using it for the skin.
time="     7.838" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_adblocked.html' for the skin.
time="     7.838" type="debug" -> gui: Found path of base skin: ':/skins/nudus-base'.
time="     7.838" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_wrapper.html' for the skin.
time="     7.838" type="debug" -> gui: Local file ':/skins/nudus-light/html_style.css' exists, using it for the skin.
time="     7.838" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_enclosure_image.html' for the skin.
time="     7.838" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_single_message.html' for the skin.
time="     7.838" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_enclosure_every.html' for the skin.
time="     7.838" type="debug" -> gui: Local file ':/skins/nudus-light/qt_style.qss' exists, using it for the skin.
time="     7.838" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_adblocked.html' for the skin.
time="     9.087" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     9.788" type="debug" -> network: Destroying Downloader instance.
time="     9.788" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="     9.788" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="    10.519" type="debug" -> network: Destroying Downloader instance.
time="    10.519" type="debug" -> network: Destroying SilentNetworkAccessManager instance.

### Operating system and version

* OS: Linux Mint 21.2 Cinnamon (I was able to replicate it on a VM with linux mint, but not with kubuntu 23.10)
* RSS Guard version: 4.5.4

**Comment by martinrotter** [comment]
Can you print stacktrace and paste here?

SOme general informatio on how to get traces, here.

https://wiki.archlinux.org/title/Debugging/Getting_traces

**Comment by darkshram** [comment]
Same issue in ALDOS 1.4 (Fedora derivative without SystemD).

```
(lldb) target create "rssguard"
Current executable set to 'rssguard' (x86_64).
(lldb) run
Process 6087 launched: '/usr/bin/rssguard' (x86_64)
time="     7.421" type="warning" -> core: User CSS style was not provided in file '/home/jbarrios/.config/RSS Guard 4/web/user-styles.css'.
time="     8.662" type="warning" -> gui: Showing tray icon with little delay.
time="    11.716" type="warning" -> gui: Tray icon is available, showing now.
Process 6087 stopped
* thread #1, name = 'rssguard', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
    frame #0: 0x00007ffff7450574 librssguard.so`SettingsLocalization::loadSettings() + 6308
librssguard.so`SettingsLocalization::loadSettings:
->  0x7ffff7450574 <+6308>: movq   0x0, %rax
    0x7ffff745057c <+6316>: movq   -0x2d8(%rbp), %rdi
    0x7ffff7450583 <+6323>: xorl   %edx, %edx
    0x7ffff7450585 <+6325>: movslq 0x4(%rax), %rbx
```

Environment:
- GCC 8.5.0 / Clang 14.0.5
- Glibc 2.27
- Qt5 5.15.11
- Kernel 5.4.259
- Sqlite 3.41.2

Build log as attachment.
[build.log](https://github.com/martinrotter/rssguard/files/13342437/build.log)

Relevant warnings from buildlog:

```
/builddir/build/BUILD/rssguard-4.5.4/src/librssguard/database/databasequeries.cpp:2574:10: warning: enumeration value 'Root' not handled in switch [-Wswitch]
/builddir/build/BUILD/rssguard-4.5.4/src/librssguard/database/databasequeries.cpp:2574:10: warning: enumeration value 'Bin' not handled in switch [-Wswitch]
/builddir/build/BUILD/rssguard-4.5.4/src/librssguard/database/databasequeries.cpp:2574:10: warning: enumeration value 'Labels' not handled in switch [-Wswitch]
/builddir/build/BUILD/rssguard-4.5.4/src/librssguard/database/databasequeries.cpp:2574:10: warning: enumeration value 'Important' not handled in switch [-Wswitch]
/builddir/build/BUILD/rssguard-4.5.4/src/librssguard/database/databasequeries.cpp:2574:10: warning: enumeration value 'Label' not handled in switch [-Wswitch]
/builddir/build/BUILD/rssguard-4.5.4/src/librssguard/database/databasequeries.cpp:2574:10: warning: enumeration value 'Unread' not handled in switch [-Wswitch]
/builddir/build/BUILD/rssguard-4.5.4/src/librssguard/database/databasequeries.cpp:2574:10: warning: enumeration value 'Probes' not handled in switch [-Wswitch]
/builddir/build/BUILD/rssguard-4.5.4/src/librssguard/database/databasequeries.cpp:2574:10: warning: enumeration value 'Probe' not handled in switch [-Wswitch]
/builddir/build/BUILD/rssguard-4.5.4/src/librssguard/services/greader/gui/greaderaccountdetails.cpp:244:10: warning: enumeration value 'FreshRss' not handled in switch [-Wswitch]
/builddir/build/BUILD/rssguard-4.5.4/src/librssguard/services/greader/gui/greaderaccountdetails.cpp:244:10: warning: enumeration value 'Other' not handled in switch [-Wswitch]
/builddir/build/BUILD/rssguard-4.5.4/src/librssguard/services/standard/standardfeedsimportexportmodel.h:68:10: warning: 'FeedsImportExportModel::m_mode' will be initialized after [-Wreorder]
/builddir/build/BUILD/rssguard-4.5.4/src/librssguard/services/standard/standardfeedsimportexportmodel.h:66:15: warning:   'RootItem* FeedsImportExportModel::m_newRoot' [-Wreorder]
/builddir/build/BUILD/rssguard-4.5.4/src/librssguard/services/standard/standardfeedsimportexportmodel.cpp:24:1: warning:   when initialized here [-Wreorder]
/builddir/build/BUILD/rssguard-4.5.4/src/librssguard/gui/webviewers/qtextbrowser/textbrowserviewer.h:107:13: warning: 'TextBrowserViewer::m_placeholderImageError' will be initialized after [-Wreorder]
/builddir/build/BUILD/rssguard-4.5.4/src/librssguard/gui/webviewers/qtextbrowser/textbrowserviewer.h:98:32: warning:   'QScopedPointer<Downloader> TextBrowserViewer::m_downloader' [-Wreorder]
/builddir/build/BUILD/rssguard-4.5.4/src/librssguard/gui/webviewers/qtextbrowser/textbrowserviewer.cpp:23:1: warning:   when initialized here [-Wreorder]
```

**Comment by martinrotter** [comment]
Tried to make a fix althought the issue does not reproduce on Windows.

**Comment by martinrotter** [comment]
Will release new version anyway for another issue, pls test.
