### ISSUE TITLE
[FR]: Fetch progress indicator animation on feeds

### ISSUE THREAD

**Issue by chromer030** [martinrotter/rssguard#1203]
### Brief description of the feature request

This is really useful to see what's going on, which one is fetched and which one is on progress.

**Comment by martinrotter** [comment]
Well. Let me explain one thing first.

Some months ago, RSS Guard got the ability of scaling feed fetching among multiple processor cores/threads. So, there could be like 6 (or more, depending on settings and other things) simultanneous feed fetches. If user has low PING and fast internet speed, RSS Guard is able to fetch hundreds of feeds in mere seconds.

If each of those hundred of feeds resulted in feed list updated (even if done technically correctly and only the single item is refreshed), it still results in visible GUI lagging on some platforms.

So for performance reasons currect behavior is that feed list is refreshed after all feeds finish fetching.

I made very basic implementation of your request, it simply shows "loading" icon when the given feed is fetching right now, and reloads feed item in feed list when fetching of that particular feed finishes. This would be visually enought for you? If so, I might include this feature, but it would have to be switchable in settings with default setting to be likely off.

![rssguard_akyhvaEcnz](https://github.com/martinrotter/rssguard/assets/1255302/7e9725ef-f200-4690-bb72-6f1541e00c4c)

**Comment by chromer030** [comment]
Thank you, it's OK, all the point is being of an indicator for progress.

**Comment by martinrotter** [comment]
![image](https://github.com/martinrotter/rssguard/assets/1255302/70390e4b-2ee1-4ec5-bd91-f573855e6ccb)

added to settings
