### ISSUE TITLE
[BUG]: Language code for spanish translation should be "es" instead of "es_ES"

### ISSUE THREAD

**Issue by darkshram** [martinrotter/rssguard#1205]
### Brief description of the issue

Do not know if this was something Crowdin did or something inherited before I took on the Spanish translation of RSSGuard. Because issue #1200 I realized this.

Currently the TS tag has this:

```
<TS version="2.1" language="es_ES" sourcelanguage="en">
```

Which corresponds to Spanish from Spain. It should be:

```
<TS version="2.1" language="es" sourcelanguage="en">
```

Which corresponds to international Spanish.

### How to reproduce the bug?

language="es_ES"

### What was the expected result?

language="es"

### What actually happened?

language="es_ES"

### Debug log

Not needed.

### Operating system and version

* OS: ALDOS 1.4
* RSS Guard version: 4.5.5

**Comment by martinrotter** [comment]
Hi. No, it should not, at least not on Crowdin.

On crowdin they have "es_ES" (Spain - Spanish) and "es_EM" (Modern - Spanish). In RSS Guard, "spanish" was meant to be spain spanish for a loooong time (spanish flag is there forever).

Are you saying that we should add another "spanish/modern" localization or that already existing "spain/spanish" is ACTUALLY really "modern" by looking at localized strings?

I have no idea how similar or different these localizations would be but given the fact that there are veeeery few translators who translate RSS Guard wouldn't it be better just have one complete spanish localization? Just askin. Please elalborate.

**Comment by darkshram** [comment]
Not really. Believe it or not, this was the first time I realized the Spanish translation says _Español de España_. Usually the Spanish flag will show anyway with either `es` or `es_ES` in any application.

Filename is `rssguard_es.ts`, not `rssguard_es_ES.ts`, so the language code should be just `es` (intended for international/neutral Spanish). Similar case as for `en` to `en_US` or `en_GB` or `en_CA`.

Translation can be used also as `es_ES` or `es_MX` or any other `es_*` variant (I am mexican and speak/write **international/neutral/non-regional** Spanish). Translation has been made (as far as I have done) to be **region neutral**. This means: I only use words and terms common to any Spanish speaking country and therefore can be used for any Spanish localization setup. There is really no need to create another variant.

For compatibility with current setups:

1. Copy `rssguard_es.ts` (without modifications) as `rssguard_es_ES.ts`. Language code will match the file name and Spaniards will load automatically that localization.
2. Modify `rssguard_es.ts` and change `language="es_ES"` for `language="es"`. Any other Spanish speaking country will load this localization.

I can maintain both files at Crowdin, same as you do with `en`, `en_US` and `en_GB`.

**Comment by martinrotter** [comment]
I see. OK I will convert it to "es".

**Comment by darkshram** [comment]
> I see. OK I will convert it to "es".

The same thing has to be done to `qtbase_es.ts`. I have checked it, and has a few mistypes, untranslated terms and at least one untranslated string tagged as translated. This file is not in Crowdin. Push request?

**Comment by martinrotter** [comment]
this is upstream Qt file taken directly from

https://github.com/qt/qttranslations/tree/dev/translations

make PR to change to "es"  in my repository if you feel it needs to be done
