### ISSUE TITLE
[FR]: An Home Page for RSSGuard

### ISSUE THREAD

**Issue by chromer030** [martinrotter/rssguard#1209]
### Brief description of the feature request

To enhance marketing efforts and broaden the user base for RSSGuard, it is highly beneficial to establish a dedicated website, an home page to RSSGuard.

This website would introduce the software through a combination of visually engaging screenshots and detailed descriptions, complemented by direct download links for referred users.

(Most ordinary users are just trying to find software through Google and are not familiar with Github and Github release)

Leveraging the power of Google search and its SEO would further amplify RSSGuard's visibility, potentially translating into increased support and donations for the project.

It can be a [Github Pages](https://pages.github.com/) or a static site with [hugo](https://github.com/gohugoio/hugo).

**Comment by martinrotter** [comment]
This is and likely will be waaaay out of my time possibilities. Sorry.
