### ISSUE TITLE
[BUG]: random network errors with tt-rss

### ISSUE THREAD

**Issue by io43** [martinrotter/rssguard#1210]
### Brief description of the issue

Hello, i have an issue since i have been using rssguard with tt-rss account, feeds randomly returns network errors and eventually get synced or not on the next sync, i have the timeout set to 40sec so i m not sure what is the problem because the sync is much faster than 40sec. and the server ping and load are good. 

Also if i manually sync each feed the same thing happen, sometimes it give network error

Thanks

![11](https://github.com/martinrotter/rssguard/assets/125970146/b7ea0d4c-9391-4a40-a49e-f089c7f76a46)

### How to reproduce the bug?

1. add tt-rss account
2. sync

### What was the expected result?

No errors

### What actually happened?

Random network errors

### Debug log

time="   105.089" type="warning" -> QIODevice::read (QNetworkReplyHttpImpl): device not open
time="   105.089" type="debug" -> network: Destroying Downloader instance.
time="   105.089" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="   105.090" type="warning" -> tt-rss: getHeadlines failed with error: 'QNetworkReply::OperationCanceledError'.
time="   105.090" type="critical" -> network: Error when fetching feed: 'Feed::Status::NetworkError' message: ''.

### Operating system and version

* OS: WIN 10
* RSS Guard version: 4.5.5
* Tiny Tiny RSS v20.09
* Localhost sock5 proxy

**Comment by martinrotter** [comment]
Hi. Well, hard to say. I will test on my tt-rss instance.

**Comment by martinrotter** [comment]
I am not really able to reproduce so far.

**Comment by io43** [comment]
ok i'll do some tests and provide a way to reproduce in the week

**Comment by martinrotter** [comment]
Thank you, really precise set of steps to reproduce would help me to eventually fix the problem.

**Comment by martinrotter** [comment]
closing until rigorous set of steps to reproduce are provided

I this is self-hosted, I strongly advise you to examine web server logs, which might yield some light on this situation.
