### ISSUE TITLE
[BUG]: Main tab disappears

### ISSUE THREAD

**Issue by slalaurette** [martinrotter/rssguard#1215]
### Brief description of the issue

Sometimes I open a new tab (Ctrl+click in a post) to listen to music in RSS Guard while I do other stuff. And sometimes (not always), after a while, the main tab of the program with all the feeds and articles disappears on its own. 

I notice this after using other programs for a while, and then returning to the RSS Guard window. I've never noticed the tab disappearing while I'm in the RSS Guard window itself. 

Sometimes the tab appears again. It all seems to be pretty random.

![clip_20231117_09 06 46](https://github.com/martinrotter/rssguard/assets/12722382/f8db3422-51b0-4da4-b498-eeb0254d1bce)

### How to reproduce the bug?

I'm not sure. It happens randomly. 

### What was the expected result?

The tab should stay.

### What actually happened?

The main tab sometimes disappears from view.

### Debug log

(I have enabled the log through the command line, but it's empty. I don't know why.)

### Operating system and version

* OS: Windows 10
* RSS Guard version: 4.5.3

**Comment by slalaurette** [comment]
Since there is no log, I thought I should specify that the feed is http://escueladerockradio.blogspot.com/feeds/posts/default and that I open the new tab by Ctrl+clicking on the album cover that appears in the post. This opens a Web player in a new tab.

**Comment by martinrotter** [comment]
Yes, that happened to me once or twice too. Will investigate.

**Comment by martinrotter** [comment]
Well, I have big trouble reproducing this. I will close this, as I was not able to reliably reproduce. if you find reliable way to actually reproduce, let me know.
