### ISSUE TITLE
[FR]: Internal Player for Podcasts

### ISSUE THREAD

**Issue by chromer030** [martinrotter/rssguard#1226]
### Brief description of the feature request

First mentioned in https://github.com/martinrotter/rssguard/discussions/1216, RSS guard has full potential for managing and playing podcasts, all it needs it's an internal player.

**Comment by martinrotter** [comment]
![TOTALCMD_LUCue1gH5H](https://github.com/martinrotter/rssguard/assets/1255302/a1c9df2a-c867-473a-897a-8b9263aeacd3)

**Comment by martinrotter** [comment]
https://github.com/martinrotter/rssguard/assets/1255302/e39a7977-af26-49c6-b97d-0327ba4b98bc

**Comment by chromer030** [comment]
It's seems great, another thing : One of most essential needs for Podcasts and Videos : Playback Speed.

**Comment by martinrotter** [comment]
I think about using libmpv as backend as this has much more features at really not real cost. Supports youtube and other things via yt-dlp plugin, subtitles, "mpv" configs etc.

**Comment by chromer030** [comment]
> I think about using libmpv as backend as this has much more features at really not real cost. Supports youtube and other things via yt-dlp plugin, subtitles, "mpv" configs etc.

Agree and will be great.
Almost all distros have ffmpeg and mpv.
Also it's ported on macOS and Windows and other OSes.

**Comment by martinrotter** [comment]
Yes. RSS Guard will support both backends 
* QtMultimedia (which uses FFMPEG usually)
* LibMPV.

Will work on implementation in coming days.

**Comment by chromer030** [comment]
Will be complete to have an option in settings to choose between available backends and a tooltip if there is no backend and how to install the appropriate package/software (qt6-multimedia, mpv) to have it.

**Comment by martinrotter** [comment]
Switching between available backends will not be possible, at least for now. In settings there is new section "media

---------
so, for now, windows only, for testing

all NON-lite variants have "libmpv" player activated
all LITE variants have "QtMultimedia/ffmpeg" player activated

**Comment by martinrotter** [comment]
working on the actual functionality in days to come

**Comment by martinrotter** [comment]
working On-screen-control interaction


https://github.com/martinrotter/rssguard/assets/1255302/92573d28-f442-4e2e-81b6-878b7a723c9c

**Comment by chromer030** [comment]
Using mpv is a wise decision, i tried almost every player, mpv is most powerfull among all, way powerful than vlc.

**Comment by martinrotter** [comment]
OK, initial implementation is done.

Development builds are building - at this point feature is only enabled for Windows builds -> lite variant has QtMultimedia backend, full variant has libmpv backend. Pls test.

**Comment by martinrotter** [comment]
OK, final summary:

- development builds:
    * LITE variants -> QtMultimedia backend
    * FULL variants -> libmpv backend
    * MACOSX builds -> not enabled yet, will have to test first

- QtMultimedia backend is simpler, binaries are smaller (about 15 mb on Windows), it is very very good implementation
- libmpv backend has huge potential, 90 mb binaries on Windows, supports direct youtube playing via yt-dl (which is bundled on Windows). I will add some options in ssettings to this backend like choosing "user data folder" for mpv from which configs will be automatically loaded etc.

**Comment by martinrotter** [comment]
Yes, I believe that mpv backend will work best for rssguard, let's see.

**Comment by chromer030** [comment]
Another recently big improvement of mpv is new, improved rendering backend (based on libplacebo).
mpv is really great.
