### ISSUE TITLE
[BUG]: feed not working

### ISSUE THREAD

**Issue by M1Aston** [martinrotter/rssguard#1229]
### Brief description of the issue

https://www.israelnieuws.nl/blog-feed.xml

### How to reproduce the bug?

Just add the feed.

### What was the expected result?

I would like to have seen some content.

### What actually happened?

Doesn't load anything.

### Debug log

What is that?

### Operating system and version

* OS: Windows 11
* RSS Guard version: 4.5.5

**Comment by martinrotter** [comment]
Tested and works here.

![image](https://github.com/martinrotter/rssguard/assets/1255302/3fb2a49b-7182-4ef1-8790-d1981c73b8cc)

Please, re-test with latest version of RSS Guard, otherwise it seems to be local network issue.
