### ISSUE TITLE
Adblocker

### ISSUE THREAD

**Issue by smaragdus** [martinrotter/rssguard#123]
You may consider adding an **adblocker** to the internal browser of **RSS Guard**.

**Comment by martinrotter** [comment]
@smaragdus  @phedlund

**Comment by martinrotter** [comment]
Based on [QupZilla](https://www.qupzilla.com/). Features:

 - full EasyList support,
 - switchable during runtime,
 - can disable on specific websites and on wildcard URLs,
 - user can add custom rules,
 - automatic updating of old subscriptions (5 days),
 - lazy loading,
 - accessible via custom toolbar/status bar actions (add to toolbar/statusbar in settings) and via web browser context menu.

For better performance, be VERY careful about what lists you enable! I strongly recommend only some very optimized lists specific for your country.

This feature is very experimental and I will work on it in next days to polish it more.

**Comment by martinrotter** [comment]
![screenshot 2017-07-20 12 26 32](https://user-images.githubusercontent.com/1255302/28413191-fe345b70-6d46-11e7-8661-9b507774bca8.png)

**Comment by martinrotter** [comment]
AdBlocker also works in internal message preview window.

**Comment by martinrotter** [comment]
I mark this as fixed and closing issue, enhancements incoming. Feel free to comment if you see some fatal errors.
