### ISSUE TITLE
[BUG]: Mediaplayer tab opens each time I choose Open in external browser

### ISSUE THREAD

**Issue by xmstspider** [martinrotter/rssguard#1241]
### Brief description of the issue

Hi Martin,

do you have any idea why the media player tab opens every time I right-click on feed article and choose Open in external browser?

### How to reproduce the bug?

1. Right-click on article
2. Choose Open in external browser
3. Media player tab with black screen opens

### What was the expected result?

Just open the article in external browser

### What actually happened?

Media player tab opens for each article

### Debug log

Don't use, I can produce one if required.

### Operating system and version

* OS: Fedora 38 KDE
* RSS Guard version: 4.6.0 lite (rssguard-4.6.0-64b739e85-lite-linux64.AppImage)

**Comment by martinrotter** [comment]
Will fix tomorrow.

**Comment by xmstspider** [comment]
In devel version (rssguard-devbuild-c1ada2fb2-lite-linux64.AppImage) but in 4.6.0 (rssguard-4.6.0-64b739e85-lite-linux64.AppImage) it is not working (I redownloaded the AppImage and compared SHA1 just to be sure).

Aha, you mean 4.6.1? Ok, I don't have a machine able to compile RSSguard now, so I can't test it but I can surely test AppImage, when it's built...

**Comment by xmstspider** [comment]
OK will test. Found another interesting problem, but will test 4.6.2 first...

**Comment by xmstspider** [comment]
OK, good news, 4.6.2 lite working as expected! Full version was crashing (that was the second problem), but it is fixed as well, so we are back on track :-D

Great job 👍🏻

**Comment by martinrotter** [comment]
> OK will test. Found another interesting problem, but will test 4.6.2 first...

sure, let me know about the problem if it persists

**Comment by xmstspider** [comment]
> sure, let me know about the problem if it persists

Not needed, the 4.6.2 fixed it as well :-)
