### ISSUE TITLE
[BUG]: Tiny images

### ISSUE THREAD

**Issue by ghost** [martinrotter/rssguard#1249]
### Brief description of the issue

Since some recent version (+4.6.0), the preview images of the article preview and internal browser are very small.

### How to reproduce the bug?

Go to any feed with images (there are several in the default feeds for a new account).
It can be replicated with a new clean install on VM.

### What was the expected result?

Visible images for not only Hawkeye.

### What actually happened?

Simulation of visual impairment.

### Debug log

(I would prefer to avoid it, if as it seems it is not necessary.)

### Operating system and version

* OS: Tested on both Windows 10 and ubuntu 22.04
* RSS Guard version: 4.6.2

**Comment by martinrotter** [comment]
Go to Settings -> Feeds&articles -> Articles and make screenshot and paste here pls.

**Comment by martinrotter** [comment]
go to settngs->feeds&articles->articles

make screenshot and paste here pls

**Comment by dlabaja** [comment]
thanks, that works

**Comment by KillyMXI** [comment]
Like, I suspect many others, I found myself here.
And there is another issue before this: #1175

I think current behavior is surprising and it is actually an issue, albeit a subtle one.

First, there is something that seems like a bad default. Default limit is so tiny, it is perceived as a bug every time you'd expect to see an image (like a webcomic).

Second, the actual setting seems to fall into some kind of a blind spot.
I was trying to find a setting myself but was unable to do so without the pointer in this thread. Even though it may seem logical after I know where it is. Something about settings layout messes with the brain.
