### ISSUE TITLE
Source distfile weighs 58MB for 4.6.2 vs 22MB for previous versions

### ISSUE THREAD

**Issue by danfe** [martinrotter/rssguard#1250]
I've noticed that source code `.tar.gz` download from GitHub takes too long and eventually found out that it weighs more than twice now.  Looking inside the contents, this is caused by bundled `resources/scripts/libmpv` which contains prebuilt Win32 DLL worth a little less than 100MB.  May I suggest this library code fetched from elsewhere and injected into Windows release only?  Having it inside the source code is conceptually wrong and is a gratuitous pessimization for users of Unix-like systems (larger distfile, longer download times).

P.S.  Seeing _is a (very) tiny feed reader_ in the About window now looks even more ironic.  You should probably reword it as QtWebEngine component typically eats several gigabytes, often more than total amount of RAM and swap combined on my laptop.

### Operating system and version

* OS: FreeBSD 13.2
* RSS Guard version: 4.6.2

**Comment by martinrotter** [comment]
Yes, i will move that into separate git submodule, sorry for that.

**Comment by martinrotter** [comment]
should be fixed in master branch, libmpv was added as submodule

**Comment by danfe** [comment]
> should be fixed in master branch

Distfile for v4.6.3 is back to normal size, thanks!
