### ISSUE TITLE
[BUG]: Can't sync with Nextcloud

### ISSUE THREAD

**Issue by kvibber** [martinrotter/rssguard#1259]
### Brief description of the issue

Attempting to sync with my Nextcloud News backend always fails unless I manually fetch a small number of feeds. I've had this happen with two accounts on the server, on Windows 10, macOS Ventura, and Linux (Fedora 39). Most of the feeds' names will turn red indicating an error, and will not retrieve any new articles. 

### How to reproduce the bug?

1. Connect to a Nextcloud News server backend.
2. Wait for the feed names and folders to populate.
3. Try to fetch all.

### What was the expected result?

New articles should be retrieved, updated feeds highlighted in blue.

### What actually happened?

Anywhere from one to five feeds might update, but the rest will be highlighted in red and not add any new articles. Debug logs indicate network errors.

### Debug log

time="   190.420" type="debug" -> feed-downloader: Starting feed updates from worker in thread '0x7f638affd6c0'.
time="   190.420" type="debug" -> feed-downloader: Synchronizing cache back to server on thread '0x7f638affd6c0'.
time="   190.420" type="debug" -> feed-downloader: All caches synchronized.
time="   190.420" type="debug" -> database: SQLite connection 'db_connection_140065510512320' is already active.
time="   190.420" type="debug" -> database: SQLite database connection 'db_connection_140065510512320' to file '/home/kelson/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="   190.420" type="debug" -> feed-downloader: Downloading new messages for feed ID '31' URL: 'http://blog.flickr.net/en/feed/atom' title: 'Flickr Blog' in thread  '140063757289152'.
time="   190.420" type="debug" -> feed-downloader: Downloading new messages for feed ID '16' URL: 'http://fedoramagazine.org/feed/' title: 'Fedora Magazine' in thread  '140064140379840'.
time="   190.420" type="debug" -> feed-downloader: Downloading new messages for feed ID '24' URL: 'https://www.11ty.dev/blog/feed.xml' title: 'Eleventy Blog' in thread  '140063748896448'.
time="   190.420" type="debug" -> database: SQLite connection 'db_connection_140063748896448' is already active.
time="   190.420" type="debug" -> feed-downloader: Downloading new messages for feed ID '22' URL: 'https://blog.joinmastodon.org/index.xml' title: 'Official Mastodon Blog' in thread  '140065644730048'.
time="   190.420" type="debug" -> database: SQLite connection 'db_connection_140064140379840' is already active.
time="   190.421" type="debug" -> database: SQLite connection 'db_connection_140065644730048' is already active.
time="   190.420" type="debug" -> feed-downloader: Downloading new messages for feed ID '69' URL: 'https://blog.chromium.org/feeds/posts/default' title: 'Chromium Blog' in thread  '140065493726912'.
time="   190.421" type="debug" -> database: SQLite database connection 'db_connection_140065644730048' to file '/home/kelson/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="   190.420" type="debug" -> feed-downloader: Downloading new messages for feed ID '82' URL: 'https://keepassxc.org/blog/feed.xml' title: 'KeePassXC' in thread  '140064131987136'.
time="   190.421" type="debug" -> database: SQLite connection 'db_connection_140065493726912' is already active.
time="   190.421" type="debug" -> database: SQLite connection 'db_connection_140064131987136' is already active.
time="   190.420" type="debug" -> feed-downloader: Downloading new messages for feed ID '58' URL: 'https://distrowatch.com/news/news-headlines.xml' title: 'DistroWatch' in thread  '140063774074560'.
time="   190.421" type="debug" -> feed-downloader: Downloading new messages for feed ID '139' URL: 'https://github.com/superseriousbusiness/gotosocial/releases.atom' title: 'GoToSocial Release Notes' in thread  '140063765681856'.
time="   190.420" type="debug" -> database: SQLite connection 'db_connection_140063757289152' is already active.
time="   190.420" type="debug" -> feed-downloader: Downloading new messages for feed ID '65' URL: 'https://wordpress.org/news/feed/' title: 'WordPress News' in thread  '140065476941504'.
time="   190.421" type="debug" -> feed-downloader: Downloading new messages for feed ID '86' URL: 'https://onethingwell.org/rss' title: 'One Thing Well' in thread  '140065502119616'.
time="   190.421" type="debug" -> feed-downloader: Downloading new messages for feed ID '102' URL: 'https://blogs.gnome.org/jangernert/feed/' title: 'News about Newsflash' in thread  '140063782467264'.
time="   190.421" type="debug" -> database: SQLite connection 'db_connection_140063774074560' is already active.
time="   190.421" type="debug" -> database: SQLite database connection 'db_connection_140065493726912' to file '/home/kelson/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="   190.420" type="debug" -> feed-downloader: Downloading new messages for feed ID '74' URL: 'https://opensourcemusings.com/feed/' title: 'Open Source Musings' in thread  '140063740503744'.
time="   190.421" type="debug" -> feed-downloader: Downloading new messages for feed ID '64' URL: 'https://github.blog/feed/' title: 'GitHub Blog' in thread  '140065653122752'.
time="   190.421" type="debug" -> database: SQLite database connection 'db_connection_140064140379840' to file '/home/kelson/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="   190.421" type="debug" -> database: SQLite database connection 'db_connection_140063774074560' to file '/home/kelson/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="   190.420" type="debug" -> database: SQLite database connection 'db_connection_140063748896448' to file '/home/kelson/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="   190.421" type="debug" -> database: SQLite connection 'db_connection_140065476941504' is already active.
time="   190.421" type="debug" -> database: SQLite connection 'db_connection_140065653122752' is already active.
time="   190.421" type="debug" -> feed-downloader: Downloading new messages for feed ID '70' URL: 'https://developer.wordpress.org/news/feed/' title: 'WordPress Developer Blog' in thread  '140063732111040'.
time="   190.421" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="   190.421" type="debug" -> database: SQLite database connection 'db_connection_140065476941504' to file '/home/kelson/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="   190.421" type="debug" -> database: SQLite connection 'db_connection_140063782467264' is already active.
time="   190.421" type="debug" -> database: SQLite database connection 'db_connection_140063757289152' to file '/home/kelson/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="   190.421" type="debug" -> database: SQLite database connection 'db_connection_140063782467264' to file '/home/kelson/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="   190.421" type="debug" -> database: SQLite database connection 'db_connection_140065653122752' to file '/home/kelson/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="   190.421" type="debug" -> feed-downloader: Downloading new messages for feed ID '56' URL: 'https://wptavern.com/feed' title: 'WP Tavern' in thread  '140065485334208'.
time="   190.422" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="   190.422" type="debug" -> database: SQLite connection 'db_connection_140065485334208' is already active.
time="   190.422" type="debug" -> database: SQLite database connection 'db_connection_140065485334208' to file '/home/kelson/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="   190.421" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="   190.421" type="debug" -> database: SQLite connection 'db_connection_140063732111040' is already active.
time="   190.422" type="debug" -> database: SQLite database connection 'db_connection_140063732111040' to file '/home/kelson/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="   190.421" type="debug" -> database: SQLite connection 'db_connection_140063740503744' is already active.
time="   190.422" type="debug" -> database: SQLite database connection 'db_connection_140063740503744' to file '/home/kelson/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="   190.421" type="debug" -> database: SQLite database connection 'db_connection_140064131987136' to file '/home/kelson/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="   190.421" type="debug" -> database: SQLite connection 'db_connection_140063765681856' is already active.
time="   190.422" type="debug" -> database: SQLite database connection 'db_connection_140063765681856' to file '/home/kelson/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="   190.423" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="   190.421" type="debug" -> database: SQLite connection 'db_connection_140065502119616' is already active.
time="   190.423" type="debug" -> database: SQLite database connection 'db_connection_140065502119616' to file '/home/kelson/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="   190.423" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="   190.423" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="   190.420" type="debug" -> feed-downloader: Downloading new messages for feed ID '14' URL: 'http://hacks.mozilla.org/feed/' title: 'Mozilla Hacks' in thread  '140066009638592'.
time="   190.423" type="debug" -> database: SQLite connection 'db_connection_140066009638592' is already active.
time="   190.423" type="debug" -> database: SQLite database connection 'db_connection_140066009638592' to file '/home/kelson/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="   190.424" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="   190.424" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="   190.424" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="   190.424" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="   190.424" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="   190.424" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="   190.424" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="   190.424" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="   190.424" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="   190.424" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="   199.940" type="debug" -> core: Delaying scheduled feed auto-downloads and message state synchronization for some time due to another running update.
time="   209.940" type="debug" -> core: Delaying scheduled feed auto-downloads and message state synchronization for some time due to another running update.
time="   219.936" type="warning" -> QIODevice::read (QNetworkReplyHttpImpl): device not open
time="   219.936" type="warning" -> QIODevice::read (QNetworkReplyHttpImpl): device not open
time="   219.936" type="warning" -> QIODevice::read (QNetworkReplyHttpImpl): device not open
time="   219.936" type="debug" -> network: Destroying Downloader instance.
time="   219.936" type="debug" -> network: Destroying Downloader instance.
time="   219.936" type="debug" -> network: Destroying Downloader instance.
time="   219.936" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="   219.936" type="warning" -> QIODevice::read (QNetworkReplyHttpImpl): device not open
time="   219.936" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="   219.937" type="debug" -> network: Destroying Downloader instance.
time="   219.937" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="   219.936" type="warning" -> QIODevice::read (QNetworkReplyHttpImpl): device not open
time="   219.936" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="   219.937" type="debug" -> network: Destroying Downloader instance.
time="   219.937" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="   219.937" type="critical" -> nextcloud: Obtaining messages failed with error 'QNetworkReply::OperationCanceledError'.
time="   219.937" type="critical" -> network: Error when fetching feed: 'Feed::Status::NetworkError' message: ''.
time="   219.937" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 1/22 (id of feed is 53).
time="   219.937" type="debug" -> feed-downloader: Downloading new messages for feed ID '140' URL: 'https://github.com/thunderbird/thunderbird-android/releases.atom' title: 'Thunderbird Android Release Notes' in thread  '140065493726912'.
time="   219.937" type="debug" -> database: SQLite connection 'db_connection_140065493726912' is already active.
time="   219.937" type="critical" -> nextcloud: Obtaining messages failed with error 'QNetworkReply::OperationCanceledError'.
time="   219.937" type="debug" -> database: SQLite database connection 'db_connection_140065493726912' to file '/home/kelson/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="   219.937" type="critical" -> network: Error when fetching feed: 'Feed::Status::NetworkError' message: ''.
time="   219.937" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 2/22 (id of feed is 60).
time="   219.937" type="critical" -> nextcloud: Obtaining messages failed with error 'QNetworkReply::OperationCanceledError'.
time="   219.937" type="debug" -> feed-downloader: Downloading new messages for feed ID '141' URL: 'https://github.com/streetcomplete/StreetComplete/releases.atom' title: 'StreetComplete Release Notes' in thread  '140065644730048'.
time="   219.937" type="debug" -> database: SQLite connection 'db_connection_140065644730048' is already active.
time="   219.937" type="critical" -> nextcloud: Obtaining messages failed with error 'QNetworkReply::OperationCanceledError'.
time="   219.937" type="debug" -> database: SQLite database connection 'db_connection_140065644730048' to file '/home/kelson/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="   219.937" type="critical" -> network: Error when fetching feed: 'Feed::Status::NetworkError' message: ''.
time="   219.938" type="critical" -> nextcloud: Obtaining messages failed with error 'QNetworkReply::OperationCanceledError'.
time="   219.938" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="   219.938" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 3/22 (id of feed is 52).
time="   219.938" type="critical" -> network: Error when fetching feed: 'Feed::Status::NetworkError' message: ''.
time="   219.938" type="critical" -> network: Error when fetching feed: 'Feed::Status::NetworkError' message: ''.
time="   219.938" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="   219.938" type="debug" -> feed-downloader: Downloading new messages for feed ID '142' URL: 'https://github.com/bookwyrm-social/bookwyrm/releases.atom' title: 'Bookwyrm Release Notes' in thread  '140063732111040'.
time="   219.938" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 4/22 (id of feed is 51).
time="   219.938" type="debug" -> database: SQLite connection 'db_connection_140063732111040' is already active.
time="   219.938" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 4/22 (id of feed is 58).
time="   219.938" type="debug" -> feed-downloader: Downloading new messages for feed ID '143' URL: 'https://github.com/lxqt/lxqt/releases.atom' title: 'LXQt Release Notes' in thread  '140066009638592'.
time="   219.938" type="debug" -> database: SQLite database connection 'db_connection_140063732111040' to file '/home/kelson/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="   219.938" type="debug" -> feed-downloader: Downloading new messages for feed ID '144' URL: 'https://www.classicpress.net/feed/' title: 'ClassicPress' in thread  '140063757289152'.
time="   219.938" type="debug" -> database: SQLite connection 'db_connection_140066009638592' is already active.
time="   219.938" type="debug" -> database: SQLite connection 'db_connection_140063757289152' is already active.
time="   219.938" type="debug" -> database: SQLite database connection 'db_connection_140063757289152' to file '/home/kelson/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="   219.938" type="debug" -> database: SQLite database connection 'db_connection_140066009638592' to file '/home/kelson/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="   219.938" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="   219.938" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="   219.939" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="   219.945" type="warning" -> QIODevice::read (QNetworkReplyHttpImpl): device not open
time="   219.945" type="warning" -> QIODevice::read (QNetworkReplyHttpImpl): device not open
time="   219.945" type="debug" -> network: Destroying Downloader instance.
time="   219.945" type="warning" -> QIODevice::read (QNetworkReplyHttpImpl): device not open
time="   219.945" type="warning" -> QIODevice::read (QNetworkReplyHttpImpl): device not open
time="   219.945" type="warning" -> QIODevice::read (QNetworkReplyHttpImpl): device not open
time="   219.945" type="warning" -> QIODevice::read (QNetworkReplyHttpImpl): device not open
time="   219.945" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="   219.946" type="debug" -> network: Destroying Downloader instance.
time="   219.946" type="debug" -> network: Destroying Downloader instance.
time="   219.946" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="   219.946" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="   219.945" type="warning" -> QIODevice::read (QNetworkReplyHttpImpl): device not open
time="   219.946" type="debug" -> network: Destroying Downloader instance.
time="   219.946" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="   219.946" type="debug" -> network: Destroying Downloader instance.
time="   219.945" type="debug" -> network: Destroying Downloader instance.
time="   219.946" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="   219.946" type="warning" -> QIODevice::read (QNetworkReplyHttpImpl): device not open
time="   219.946" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="   219.946" type="debug" -> network: Destroying Downloader instance.
time="   219.946" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="   219.945" type="debug" -> network: Destroying Downloader instance.
time="   219.946" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="   219.946" type="warning" -> QIODevice::read (QNetworkReplyHttpImpl): device not open
time="   219.946" type="warning" -> QIODevice::read (QNetworkReplyHttpImpl): device not open
time="   219.945" type="warning" -> QIODevice::read (QNetworkReplyHttpImpl): device not open
time="   219.946" type="debug" -> network: Destroying Downloader instance.
time="   219.946" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="   219.946" type="debug" -> network: Destroying Downloader instance.
time="   219.946" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="   219.947" type="critical" -> nextcloud: Obtaining messages failed with error 'QNetworkReply::OperationCanceledError'.
time="   219.946" type="debug" -> network: Destroying Downloader instance.
time="   219.947" type="critical" -> network: Error when fetching feed: 'Feed::Status::NetworkError' message: ''.
time="   219.947" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="   219.947" type="critical" -> nextcloud: Obtaining messages failed with error 'QNetworkReply::OperationCanceledError'.
time="   219.947" type="critical" -> network: Error when fetching feed: 'Feed::Status::NetworkError' message: ''.
time="   219.947" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 6/22 (id of feed is 61).
time="   219.947" type="debug" -> feed-downloader: Downloading new messages for feed ID '71' URL: 'https://www.alpinelinux.org/atom.xml' title: 'Alpine Linux News' in thread  '140064140379840'.
time="   219.947" type="debug" -> database: SQLite connection 'db_connection_140064140379840' is already active.
time="   219.947" type="critical" -> nextcloud: Obtaining messages failed with error 'QNetworkReply::OperationCanceledError'.
time="   219.947" type="critical" -> nextcloud: Obtaining messages failed with error 'QNetworkReply::OperationCanceledError'.
time="   219.947" type="critical" -> network: Error when fetching feed: 'Feed::Status::NetworkError' message: ''.
time="   219.947" type="critical" -> nextcloud: Obtaining messages failed with error 'QNetworkReply::OperationCanceledError'.
time="   219.947" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 7/22 (id of feed is 47).
time="   219.947" type="debug" -> database: SQLite database connection 'db_connection_140064140379840' to file '/home/kelson/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="   219.947" type="critical" -> nextcloud: Obtaining messages failed with error 'QNetworkReply::OperationCanceledError'.
time="   219.947" type="critical" -> network: Error when fetching feed: 'Feed::Status::NetworkError' message: ''.
time="   219.947" type="critical" -> network: Error when fetching feed: 'Feed::Status::NetworkError' message: ''.
time="   219.947" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 8/22 (id of feed is 46).
time="   219.947" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 8/22 (id of feed is 49).
time="   219.947" type="critical" -> nextcloud: Obtaining messages failed with error 'QNetworkReply::OperationCanceledError'.
time="   219.947" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="   219.947" type="critical" -> network: Error when fetching feed: 'Feed::Status::NetworkError' message: ''.
time="   219.947" type="critical" -> network: Error when fetching feed: 'Feed::Status::NetworkError' message: ''.
time="   219.947" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 10/22 (id of feed is 59).
time="   219.947" type="critical" -> nextcloud: Obtaining messages failed with error 'QNetworkReply::OperationCanceledError'.
time="   219.947" type="critical" -> nextcloud: Obtaining messages failed with error 'QNetworkReply::OperationCanceledError'.
time="   219.947" type="critical" -> network: Error when fetching feed: 'Feed::Status::NetworkError' message: ''.
time="   219.947" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 11/22 (id of feed is 57).
time="   219.947" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 10/22 (id of feed is 56).
time="   219.947" type="critical" -> network: Error when fetching feed: 'Feed::Status::NetworkError' message: ''.
time="   219.947" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 6/22 (id of feed is 48).
time="   219.947" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 13/22 (id of feed is 54).
time="   219.948" type="critical" -> nextcloud: Obtaining messages failed with error 'QNetworkReply::OperationCanceledError'.
time="   219.948" type="critical" -> network: Error when fetching feed: 'Feed::Status::NetworkError' message: ''.
time="   219.948" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 15/22 (id of feed is 50).
time="   219.948" type="critical" -> nextcloud: Obtaining messages failed with error 'QNetworkReply::OperationCanceledError'.
time="   219.948" type="critical" -> network: Error when fetching feed: 'Feed::Status::NetworkError' message: ''.
time="   219.948" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 16/22 (id of feed is 55).
time="   219.960" type="debug" -> core: Delaying scheduled feed auto-downloads and message state synchronization for some time due to another running update.
time="   229.940" type="debug" -> core: Delaying scheduled feed auto-downloads and message state synchronization for some time due to another running update.
time="   239.936" type="debug" -> core: Delaying scheduled feed auto-downloads and message state synchronization for some time due to another running update.
time="   248.936" type="warning" -> Wayland does not support QWindow::requestActivate()
time="   249.936" type="debug" -> core: Delaying scheduled feed auto-downloads and message state synchronization for some time due to another running update.
time="   249.936" type="warning" -> QIODevice::read (QNetworkReplyHttpImpl): device not open
time="   249.936" type="debug" -> network: Destroying Downloader instance.
time="   249.936" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="   249.937" type="critical" -> nextcloud: Obtaining messages failed with error 'QNetworkReply::OperationCanceledError'.
time="   249.937" type="critical" -> network: Error when fetching feed: 'Feed::Status::NetworkError' message: ''.
time="   249.937" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 17/22 (id of feed is 42).
time="   249.941" type="warning" -> QIODevice::read (QNetworkReplyHttpImpl): device not open
time="   249.941" type="debug" -> network: Destroying Downloader instance.
time="   249.942" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="   249.942" type="critical" -> nextcloud: Obtaining messages failed with error 'QNetworkReply::OperationCanceledError'.
time="   249.942" type="warning" -> QIODevice::read (QNetworkReplyHttpImpl): device not open
time="   249.942" type="warning" -> QIODevice::read (QNetworkReplyHttpImpl): device not open
time="   249.942" type="warning" -> QIODevice::read (QNetworkReplyHttpImpl): device not open
time="   249.943" type="critical" -> network: Error when fetching feed: 'Feed::Status::NetworkError' message: ''.
time="   249.943" type="warning" -> QIODevice::read (QNetworkReplyHttpImpl): device not open
time="   249.943" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 18/22 (id of feed is 40).
time="   249.943" type="debug" -> network: Destroying Downloader instance.
time="   249.943" type="debug" -> network: Destroying Downloader instance.
time="   249.943" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="   249.943" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="   249.943" type="debug" -> network: Destroying Downloader instance.
time="   249.943" type="debug" -> network: Destroying Downloader instance.
time="   249.943" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="   249.943" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="   249.943" type="critical" -> nextcloud: Obtaining messages failed with error 'QNetworkReply::OperationCanceledError'.
time="   249.943" type="critical" -> nextcloud: Obtaining messages failed with error 'QNetworkReply::OperationCanceledError'.
time="   249.943" type="critical" -> network: Error when fetching feed: 'Feed::Status::NetworkError' message: ''.
time="   249.943" type="critical" -> nextcloud: Obtaining messages failed with error 'QNetworkReply::OperationCanceledError'.
time="   249.943" type="critical" -> network: Error when fetching feed: 'Feed::Status::NetworkError' message: ''.
time="   249.943" type="critical" -> network: Error when fetching feed: 'Feed::Status::NetworkError' message: ''.
time="   249.944" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 19/22 (id of feed is 45).
time="   249.943" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 19/22 (id of feed is 43).
time="   249.944" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 19/22 (id of feed is 41).
time="   249.943" type="critical" -> nextcloud: Obtaining messages failed with error 'QNetworkReply::OperationCanceledError'.
time="   249.944" type="critical" -> network: Error when fetching feed: 'Feed::Status::NetworkError' message: ''.
time="   249.944" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 22/22 (id of feed is 44).
time="   249.955" type="debug" -> feed-downloader: Finished feed updates in thread '0x7f638affd6c0'.
time="   249.967" type="debug" -> CTRL is NOT pressed while sorting articles - sorting with standard mode.
time="   249.968" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, Feeds.is_rtl, CASE WHEN LENGTH(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Messages.labels LIKE "%." || Labels.custom_id || ".%") as msg_labels, Messages.labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE Feeds.custom_id IN ('71', '144', '143', '142', '141', '140', '139', '102', '86', '82', '74', '14', '70', '69', '65', '64', '58', '56', '31', '24', '22', '16') AND Messages.is_deleted = 0 AND Messages.is_pdeleted = 0 AND Messages.account_id = 1 ORDER BY Messages.date_created DESC;'.
time="   249.968" type="debug" -> gui: Reloading of msg selections took 1 miliseconds.

### Operating system and version

* OS: Linux (Fedora 39 running GNOME on Wayland), also seen on Windows 10 and macOS Ventura
* RSS Guard version: 4.6.3. (Windows/Mac tested a week or two ago with either 4.6.1 or 4.6.2)

**Comment by martinrotter** [comment]
This is very weird, apparently, your News server is choked when many parallel network requests are made to it.

What you can try is to limit this amount of parallel network requests.

Run rssguard from command line like this (navigate to proper folder first):

```
rssguard.exe --threads 1
```

Then report back how it went, thank you.

**Comment by kvibber** [comment]
This is utterly bizarre, but the problem seems to have been that I was just using my regular login and password instead of an app-specific token!

Apparently Nextcloud checks whether a login is app-specific and actually throws and catches an InvalidTokenException if it isn't. This added enough delay in every single connection (since they seem to all be using separate sessions as near as I can tell from the Nextcloud debug log) that it was taking upwards of 30 seconds to fetch all my feeds (I'm following a lot of feeds) and presumably causing the multiple-connection problems.

adding `--threads 1` with the general login info fixes the error, but it's still slow.

Setting up an app-specific password for RSS Guard and using that: No errors, and Fetch All only takes about 3 seconds!

Thank you for looking at this and suggesting that I check out the logs!
