### ISSUE TITLE
macOS: Close button on tabs does not work

### ISSUE THREAD

**Issue by phedlund** [martinrotter/rssguard#126]
#### Brief description of the issue.

Close button on tabs does not work

#### How to reproduce the bug?

1. Open an article in its own tab
2. Attempt to close the tab by clicking the close button
3. 

#### What is the expected result?

The tab should close

#### What actually happened?

Nothing

#### Other information (logs, see Wiki)

![screen shot 2017-07-07 at 10 28 02 am](https://user-images.githubusercontent.com/884639/27969428-aa9bd7fa-62ff-11e7-8bfc-80cd58b57d25.png)

**Comment by martinrotter** [comment]
OK. This is related to #128.

**Comment by martinrotter** [comment]
Probably fixed, please check.

**Comment by phedlund** [comment]
Verified fixed.
