### ISSUE TITLE
[FR]: Sort YouTube feeds by "published" date instead of "updated" date

### ISSUE THREAD

**Issue by MateusAuri** [martinrotter/rssguard#1261]
### Brief description of the feature request

I use [Feeder](https://github.com/spacecowboy/Feeder) to be notified whenever some YouTube channels upload a new video, and I've been trying a few different ones on Windows since Feeder is Android-only.

Unfortunately, the default behaviour of RSS Guard seems to make YouTube feeds come completely out of order, or at least the Date on the articles don't correspond to their respective video's upload date.

Apparently, [according to this reddit comment](https://www.reddit.com/r/youtube/comments/339idg/comment/cqisglq/?utm_source=reddit&utm_medium=web2x&context=3), there are two different date tags, one for when the video was uploaded and another for when the video gets updated.

Here's an example feed: `https://www.youtube.com/feeds/videos.xml?channel_id=UCWN49rf6HI1Zb5T-Mism74g`
They've got a 4-part series that illustrates the problem. Right now, Part 1 appears as newer than Part 4 even though it was uploaded earlier.

I looked around but couldn't find a way to sort the articles by "published" instead of "updated". Is there any way to do that currently?
If not, I'd suggest that to be added as a feature.

**Comment by MateusAuri** [comment]
Ah wait, only now I found your [post processing script](https://github.com/martinrotter/rssguard/issues/416#issuecomment-849339090), I'm gonna try that and see if it solves my issue

**Comment by RetroAbstract** [comment]
> Ah wait, only now I found your [article filtering script](https://github.com/martinrotter/rssguard/issues/416#issuecomment-849339090), I'm gonna try that and see if it solves my issue EDIT: both versions of the script make the feed status become "error (script threw an error)" but I can't see what the error is EDIT2: nevermind I was being dumb and putting it in the wrong place, will check back in a moment EDIT3: it throws an error `(EXISTING articles filtering error: 'TypeError: Cannot read property '__text' of undefined'.)` but it works! Now the feeds seem to be in the correct order, thanks!
> 
> Pardon my dumbness... closing the issue now. If someone else has the same issue and runs into this post, just go to Articles > Article filters > New filter, then check your feeds and use martinrotter's [updated filtering script](https://github.com/martinrotter/rssguard/issues/416#issuecomment-849365155).

Thanks for this. Would like to mention that feeds that have this filtering script seem to bypass the "Avoid adding articles before this date to the database" feature both globally and on a per-feed basis.

Applying this filter (that Martin also shared) to the same feeds that have the updated filtering script applied that you mentioned, fixes this problem:

```
function filterMessage() {
  const THE_DATE = new Date("yyyy-mm-dd");

  if (msg.created >= THE_DATE) {
    return MessageObject.Accept;
  }
  else {
    return MessageObject.Ignore;
  }
}
```

Simply replace the "yyyy-mm-dd" with the date you want.

**Comment by martinrotter** [comment]
> Thanks for this. Would like to mention that feeds that have this filtering script seem to bypass the "Avoid adding articles before this date to the database" feature both globally and on a per-feed basis.

Hi, no, they should not bypass anything.

Filters are run before "avoid adding article before date" feature. If filter "ignores" the message, then it does not even reach the "avoid" feature. If filter accepts message, it still can be "avoided" by the feature if article's date is too old.

**Comment by InfiniteIllusion** [comment]
I made a slight update to the filter to allow the use of relative dates rather than absolutes, thought it might be handy for others:

```
var date_cutoff = new Date();
var days_back = 12;
date_cutoff.setDate(date_cutoff.getDate() - days_back);

function filterMessage() {
  if (msg.created >= date_cutoff) {
    return MessageObject.Accept;
  }
  else {
    return MessageObject.Ignore;
  }
}
```

I also tried combining it with the original date modification code into a single filter, with handling for ATOM vs RSS feeds. Seems to be working fine:

```
var date_cutoff = new Date();
var days_back = 12;
date_cutoff.setDate(date_cutoff.getDate() - days_back);

function filterMessage() {
  // Read raw contents of message and
  // convert to JSON.
  json = utils.fromXmlToJson(msg.rawContents);
  jsonObj = JSON.parse(json)

  // Read published date and parse it.
  // If/else for ATOM vs RSS
  if (typeof jsonObj.entry.published !== 'undefined') {
    publishedDate = jsonObj.entry.published.__text;
  }
  else {
    publishedDate = jsonObj.entry.pubDate.__text;
  }
  parsedDate = utils.parseDateTime(publishedDate);

  // Set new date/time for message and
  // proceed.
  msg.created = parsedDate;
  
  if (msg.created >= date_cutoff) {
    return MessageObject.Accept;
  }
  else {
    return MessageObject.Ignore;
  }
}
```

(Sorry for any inefficiencies, my JS isn't the strongest)
