### ISSUE TITLE
[BUG]: Expanded folder gets collapsed after fetching new articles

### ISSUE THREAD

**Issue by CsatiZoltan** [martinrotter/rssguard#1262]
### Brief description of the issue

An initially expanded folder is collapsed after fetching articles.

### How to reproduce the bug?

1. Activate the *Show unread items only* option for the feeds.
2. Have a folder (in my case, the *Journals* or *arxiv* for instance) with unread feeds in it.
3. Expand the folder.
4. Delete the articles from the folder (may work too if you set them read, although I haven't tried it). Then the folder disappears from the left panel (expected due to point 1).
5. Next time you fetch the articles from the feeds of the folder, the folder is shown collapsed.

### What was the expected result?

I expect the folders be shown in the same state. I.e. if it was expanded, then it should stay expanded later on.

### What actually happened?

The previously expanded folder is set to collapsed mode after fetching the new articles.

### Debug log

[rssguard.zip](https://github.com/martinrotter/rssguard/files/13804342/rssguard.zip)

### Operating system and version

* OS: Pop!_OS, based on Ubuntu 22.04
* RSS Guard version: precompiled binary, 4.6.3 (built on Linux/x86_64), revision 43d164dc4

**Comment by meelten** [comment]
Same thing happens when marking articles as read. It didn't use to be like that, so it must be a relatively new bug. Unfortunately I can't pinpoint when exactly it started because I rarely used RSS Guard in recent months.

**Comment by martinrotter** [comment]
I restored the previous feature responsible for this and enhanced it. Please test latest devbuild after it compiles or wait for new version.

**Comment by CsatiZoltan** [comment]
I confirm that it works on the devbuild of hash 527987b0d: expanded folders stay extended.

**Comment by martinrotter** [comment]
Yes, the fix was even enhanced to actually remember the expand AND collapse states explicitly.
