### ISSUE TITLE
The combination of a blue highlighted color with white text strains my eyes.

### ISSUE THREAD

**Issue by nahid6970** [martinrotter/rssguard#1266]
### Brief description of the feature request

![Screenshot 2024-01-09 124724](https://github.com/martinrotter/rssguard/assets/93816648/bf0c6562-ee42-45ad-adf2-3fbfa04ef734)
here for some reason i cant properly read when the text is white with blue background . i tried  the custom skin color  in different 
 ways but cant change the highlighted color for some reason??

**Comment by RetroAbstract** [comment]
You can change the color of the highlighting aswell as other elements by going into the metadata.xml file of your applied RSS Guard skin.

The 2 default skins do not appear to have a folder in the RSS Guard data folder, so I first downloaded one-by-one the [files in the "nudus-dark" folder from the source code](https://github.com/martinrotter/rssguard/tree/master/resources/skins/nudus-dark), placed them in a folder called for example "mycustomskin", then placed the folder in my RSS Guard data folder (which contains the data and config folders).

Restart RSS Guard if it's open, you should then see "mycustomskin" listed in the skins list in RSS Guard.

In this case for the highlighting color, in the metadata.xml file of "mycustomskin" (or however you name it), simply change the Hex value in the line: `<color role="Highlight">#308CC6</color>` to the color you want (for example `<color role="Highlight">#FF0000</color>` for bright red).

You can see the changes you make by first having the skin applied, then changing the Hex values of the different skin elements in metadata.xml, saving the changes, then restarting RSS Guard.

**Comment by nahid6970** [comment]
> You can change the color of the highlighting aswell as other elements by going into the metadata.xml file of your applied RSS Guard skin.
> 
> The 2 default skins do not appear to have a folder in the RSS Guard data folder, so I first downloaded one-by-one the [files in the "nudus-dark" folder from the source code](https://github.com/martinrotter/rssguard/tree/master/resources/skins/nudus-dark), placed them in a folder called for example "mycustomskin", then placed the folder in my RSS Guard data folder (which contains the data and config folders).
> 
> Restart RSS Guard if it's open, you should then see "mycustomskin" listed in the skins list in RSS Guard.
> 
> In this case for the highlighting color, in the metadata.xml file of "mycustomskin" (or however you name it), simply change the Hex value in the line: `<color role="Highlight">#308CC6</color>` to the color you want (for example `<color role="Highlight">#FF0000</color>` for bright red).
> 
> You can see the changes you make by first having the skin applied, then changing the Hex values of the different skin elements in metadata.xml, saving the changes, then restarting RSS Guard.

![Screenshot 2024-01-09 232554](https://github.com/martinrotter/rssguard/assets/93816648/9ed2b258-28ad-49d4-b87c-832ced68ab09)
i did it  and restarted rssguard but its not showing in the skin tab

**Comment by martinrotter** [comment]
Your skin folder must be placed in "skins" subfolder.

**Comment by RetroAbstract** [comment]
Martin's right, I forgot to mention that. Added it to my comment above.

**Comment by nahid6970** [comment]
thanks a lot guys its working. Also is there a way to make the highlighted text a little bigger than the others. if its not possible its fine😊.

**Comment by martinrotter** [comment]
As for font, this can be tweaked in settings -> feeds/articles -> article list -> article list font. This changes font for all rows. There is now way to change font of only selected row. It is technically possible, but not implemented.
