### ISSUE TITLE
[FR]: Add option "Ignore articles which are N or more days old"

### ISSUE THREAD

**Issue by Ac314** [martinrotter/rssguard#1267]
### Brief description of the feature request

Some feeds are updated very rarely by their owners (like 15 articles for 1 years) and all these articles are permanently included in the feed. So after database cleaning they can be downloaded again despite they were read long time ago and no more needed.
The option "Ignore articles which are N or more days old" can help here - when feed is updated the program checks articles published dates, and if they are older than N days these articles are ignored. In this case we will not have these obsoleted articles in the database and they are not displayed to a user.
Ideally this option should be global (disabled by default) and also can be set for specific feeds (in this case it supersedes the global settings).

**Comment by RetroAbstract** [comment]
You can manually do this:

- Globally by setting a date in "Settings > Feeds & articles > Feed fetching > Avoid adding articles before this date to the database"
- On a per-feed basis by right-clicking a feed > "Edit selected item > Articles > Avoid adding articles before this date to the database" and setting a date.

This method requires manually updating as time goes on if you want to avoid articles that are only a couple days old from now. A "Ignore articles which are X or more days old" feature would automate this and be very nice.

**Comment by Ac314** [comment]
> @RetroAbstract Yes, but I suspect that OP meant to be able to specify "relative" date/time frame, not absolute date/time. 

Yes, you are right. I know about "Avoid adding articles before this date to the database" setting but changing the date every day is not so convenient, to say the least... 

> Already working on this.

Thank you, looking forward for the changes.

**Comment by martinrotter** [comment]
![image](https://github.com/martinrotter/rssguard/assets/1255302/ea996234-946e-4b3b-aab8-e088346f3f3b)

Like this?

**Comment by Ac314** [comment]
> Like this?

Yes, that is always perfect. Just allow to set days here, not only minutes and seconds (maybe seconds are not needed here really).

**Comment by martinrotter** [comment]
By the way, same behavior, can be of course achieved with article filters.

```js
function filterMessage() {
  const OLDER_THAN_DAYS = 5;
  const THE_BARRIER = new Date();

  THE_BARRIER.setDate(THE_BARRIER .getDate() - OLDER_THAN_DAYS);

  if (msg.created >= THE_BARRIER) {
    return MessageObject.Accept;
  }
  else {
    return MessageObject.Ignore;
  }
}
```

**Comment by martinrotter** [comment]
Compilling, pls test rigorously. I also added this to app-wide settings.

**Comment by Ac314** [comment]
Thank you! I can use development build for testing?

**Comment by martinrotter** [comment]
Yes.

**Comment by Ac314** [comment]
It is doing OK with RSS and ATOM, everything works as expected.

The only problem I see there is no correspondence between global option and feed option, precisely I cannot disable it for specific feeds. For example, I have a global option "Do not fetch articles older than 10 days" but I want to disable it for the specific feed (to keep all its articles). Now I cannot do it. In article properties this option is disabled in GUI by default but actually it is not disabled, it is enabled and respects global settings. So I can only set it to something but not disable. 

To resolve it I guess the best way is to change how this option can be set in article properties. The option "Avoid fetching old articles" should be not an option but just an "option title", with the following choices:
- Use global setting (_set by default_)
- Disable
- Published before date/time
- Published days/hours ago

And I also guess it would be better to rename it to "Avoid fetching old articles" to make it clearer.

**Comment by martinrotter** [comment]
![image](https://github.com/martinrotter/rssguard/assets/1255302/b95db5b6-2f71-4a4a-9972-b209a85e1ef1)

The option is already there. When checked, even global setting is ignored for the feed. When not checked, then local feed setting takes precedence before global setting.

**Comment by Ac314** [comment]
:) Did not notice what was right before my eyes.

**Comment by Ac314** [comment]
It seems the custom feed settings will not be saved after the application restart. When application starts the option "Avoid adding articles before this date/time" is always disabled in feed settings despite I have it enabled in previous session.

**Comment by martinrotter** [comment]
test with latest devbuild and clean profile, if issue is there, provide exact set of steps to reproduce pls

**Comment by Ac314** [comment]
Checked it with the devbuild-9439d775e-win10 and clean profile:
1. Start the application
2. Add new account RSS/ATOM/JSON as prompted
3. Add default channels as prompted
4. Enter "Lifehacker" feed settings and enable the option "Avoid adding articles before this date/time into the database"
5. Press OK, restart the application
6. Enter "Lifehacker" feed settings - the option "Avoid adding articles before this date/time into the database" is disabled

**Comment by martinrotter** [comment]
d8180eb68

**Comment by Ac314** [comment]
Works OK in d8180eb68, settings are saved after restart.
Some little flaw: if option is disabled and you enable it then neither radio buttons are selected. If you press OK and restart the application you will see that "Relative time" radio button is selected (despite we did not select it by ourselves before). I guess if you enable the option "Avoid adding articles before this date/time into the database" in GUI then one of the radio buttons must be selected automatically immediately after that.
