### ISSUE TITLE
[FR]: Option to use Legacy simple text-based article viewer for No Web-Engine/Lite version

### ISSUE THREAD

**Issue by RetroAbstract** [martinrotter/rssguard#1268]
### Brief description of the feature request

This feature would allow the user to use the former simple text-based article viewer for the No Web-Engine/Lite builds.

I'm finding myself prefering it far more than the HTML article viewer, and having all image URLs displayed is actually useful with article filters.

This could be implemented with a tickbox in "Settings > Feeds & Articles > Articles > Use Legacy No Web-Engine artice viewer" like this:

![1](https://github.com/martinrotter/rssguard/assets/103272301/41b3b016-10ed-4fe8-bf34-a00741823482)

This feature would only appear in Lite versions of RSS Guard.

Strongly hoping this is possible as I do not wish to miss out on future RSS Guard updates by being bound to 4.5.5.

Thanks!

**Comment by martinrotter** [comment]
![image](https://github.com/martinrotter/rssguard/assets/1255302/39f7404e-2edd-46e8-8e27-0fdf696d1b65)

**Comment by RetroAbstract** [comment]
Thank you so much man.
