### ISSUE TITLE
macOS: Database and settings are deleted when updating the app

### ISSUE THREAD

**Issue by phedlund** [martinrotter/rssguard#127]
#### Brief description of the issue.

Database and settings are deleted when updating the app

#### How to reproduce the bug?

1. Replace an existing app bundle with a new one
2. 
3. 

#### What is the expected result?

Database and settings should remain when updating the app

#### What actually happened?

All feeds and preferences are gone.

RSS Guard is storing the database and its preferences in the app bundle instead of the ~/Library/Application Support and ~/Library/Preferences folders.

This is also a violation of Apple sandbox rules.

**Comment by martinrotter** [comment]
OK, I will force to store settings in the `QStandardPaths::ConfigLocation`. I am not sure what location this is on Mac OS, but it is decided by Qt. So, wait for commit and then test the built bundle in clean environment. Then check in `About` dialog, where the settings files are.

**Comment by martinrotter** [comment]
https://github.com/martinrotter/rssguard/commit/6db681386dc9242d249f3dc826f7930786405019

**Comment by phedlund** [comment]
Thanks. OK, although not perfect. Preferences should be in QStandardPaths::ConfigLocation which is ~/Library/Preferences on macOS. The database should preferably be in 
QStandardPaths::AppDataLocation which is ~/Library/Application Support on macOS.

**Comment by martinrotter** [comment]
Well, it is technically better for RSS Guard that both config and DB are placed under one directory. It makes some other things bit easier for me. It is just better to have all user data under one folder and even better if that is true in a cross-platform way. Perhaps you can make a PR to make that happen?

In that case, you would probably have to edit:

https://github.com/martinrotter/rssguard/blob/master/src/miscellaneous/databasefactory.cpp#L189

You should introduce new method called maybe `qApp->getUserDbDataPath()` and use that in the code above.
