### ISSUE TITLE
[BUG]: Position of the horizontal splitter will not be saved if app is started minimized

### ISSUE THREAD

**Issue by Ac314** [martinrotter/rssguard#1271]
### Brief description of the issue

Position of the horizontal splitter (between the articles list and the article preview) is reset if application is started minimized and we click on the tray icon.

### How to reproduce the bug?

1. Enable the option "Start application hidden"
2. Restart the application
3. Move splitter up or down 
4. The option "splitter_messages_vertical" will be set in config.ini
5. Restart the application (it will start minimized in tray)
6. Click on tray icon - application window is visible now, horizontal splitter is in correct position, but "splitter_messages_vertical" in config.ini will reset to its default value (30, 0)
7. Restart the application - splitter will be (of course) in the default position because config.ini parameter value was reset during the previous session

### What was the expected result?

Keeping the option "splitter_messages_vertical" in config.ini.

### What actually happened?

"splitter_messages_vertical" is reset after clicking on the tray icon.

### Debug log

time="     0.102" type="debug" -> core: Initializing settings in 'D:\Apps\RSS Guard\data4\config\config.ini' (portable way).
time="     0.103" type="debug" -> core: Starting to load active localization. Desired localization is 'en_US'.
time="     0.104" type="debug" -> core: Application localization 'en_US' loaded successfully, specifically sublocalization 'en_US' was loaded.
time="     0.104" type="warning" -> core: Qt localization 'en_US' WAS NOT loaded successfully.
time="     0.398" type="warning" -> database: SQLite database is not initialized. Initializing now.
time="     0.399" type="debug" -> database: SQLite database backend should be ready now.
time="     0.400" type="debug" -> database: File-based SQLite database connection '' to file 'D:\Apps\RSS Guard\data4\database\database.db' seems to be established.
time="     0.400" type="debug" -> database: File-based SQLite database has version '8'.
time="     0.401" type="debug" -> database: Copying data from file-based database into working in-memory database.
time="     0.401" type="warning" -> QSqlDatabasePrivate::removeDatabase: connection '' is still in use, all queries will cease to work.
time="     0.403" type="debug" -> gui: Available icon theme paths: QList(:/icons, :/graphics, D:\Apps\RSS Guard\data4\icons, D:/Apps/RSS Guard\icons)
time="     0.403" type="debug" -> gui: Installed icon themes are: '', 'Breeze', 'Breeze Dark', 'Faenza', 'Numix'
time="     0.403" type="debug" -> gui: Loading icon theme 'Numix'.
time="     0.404" type="debug" -> gui: Found path of base skin: ':\skins\nudus-base'.
time="     0.404" type="debug" -> gui: Base file ':\skins\nudus-base\html_wrapper.html' exists, using it for the skin.
time="     0.404" type="debug" -> gui: Local file ':\skins\nudus-light\html_style.css' exists, using it for the skin.
time="     0.404" type="debug" -> gui: Base file ':\skins\nudus-base\html_enclosure_image.html' exists, using it for the skin.
time="     0.404" type="debug" -> gui: Base file ':\skins\nudus-base\html_single_message.html' exists, using it for the skin.
time="     0.404" type="debug" -> gui: Base file ':\skins\nudus-base\html_enclosure_every.html' exists, using it for the skin.
time="     0.404" type="debug" -> gui: Local file ':\skins\nudus-light\qt_style.qss' exists, using it for the skin.
time="     0.404" type="debug" -> gui: Base file ':\skins\nudus-base\html_adblocked.html' exists, using it for the skin.
time="     0.405" type="debug" -> gui: OS defines color scheme: 'Qt::ColorScheme::Light'.
time="     0.405" type="debug" -> gui: Setting style: 'Fusion'.
time="     0.405" type="debug" -> gui: Skin 'nudus-light' loaded. Lite: 'false'.
time="     0.406" type="warning" -> core: User CSS style was not provided in file 'D:\Apps\RSS Guard\data4\web\user-styles.css'.
time="     0.406" type="debug" -> network: Persistent web data storage path: 'D:\Apps\RSS Guard\data4\web\storage'.
time="     0.406" type="debug" -> network: Disabling application-wide proxy completely.
time="     0.406" type="debug" -> core: SQLite version: '3.42.0'.
time="     0.411" type="debug" -> core: OpenSSL version: 'OpenSSL 3.0.12 24 Oct 2023'.
time="     0.411" type="debug" -> core: OpenSSL supported: 'true'.
time="     0.411" type="debug" -> core: Global thread pool has 12 threads.
time="     0.411" type="debug" -> core: Setting locale for LC_NUMERIC to C as libmpv requires it.
time="     0.411" type="debug" -> core: Instantiated class  'Application'.
time="     0.415" type="debug" -> database: SQLite database connection 'MessagesModel' to file 'file::memory:' seems to be established.
time="     0.418" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, Feeds.is_rtl, CASE WHEN LENGTH(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Messages.labels LIKE "%." || Labels.custom_id || ".%") as msg_labels, Messages.labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1;'.
time="     0.419" type="debug" -> core: Auto-download timer started with interval 10000 ms.
time="     0.419" type="debug" -> core: Creating FeedDownloader singleton.
time="     0.420" type="debug" -> gui: Creating main application form in thread: '0x2ca0'.
time="     0.428" type="debug" -> gui: Current row changed - proxy 'QModelIndex(-1,-1,0x0,QObject(0x0))', source 'QModelIndex(-1,-1,0x0,QObject(0x0))'.
time="     0.436" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     0.455" type="debug" -> gui: Creating tray icon menu.
time="     0.473" type="debug" -> CTRL is NOT pressed while sorting articles - sorting with standard mode.
time="     0.473" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, Feeds.is_rtl, CASE WHEN LENGTH(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Messages.labels LIKE "%." || Labels.custom_id || ".%") as msg_labels, Messages.labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1 ORDER BY Messages.date_created DESC;'.
time="     0.476" type="debug" -> core: Hiding the main window when the application is starting.
time="     0.477" type="debug" -> database: SQLite database connection 'FeedReader' to file 'file::memory:' seems to be established.
time="     0.477" type="debug" -> database: SQLite database connection 'FeedlyEntryPoint' to file 'file::memory:' seems to be established.
time="     0.477" type="debug" -> database: SQLite database connection 'GmailEntryPoint' to file 'file::memory:' seems to be established.
time="     0.477" type="debug" -> database: SQLite database connection 'GreaderEntryPoint' to file 'file::memory:' seems to be established.
time="     0.478" type="debug" -> database: SQLite database connection 'OwnCloudServiceEntryPoint' to file 'file::memory:' seems to be established.
time="     0.478" type="debug" -> database: SQLite database connection 'StandardServiceEntryPoint' to file 'file::memory:' seems to be established.
time="     0.479" type="debug" -> database: SQLite database connection 'StandardServiceRoot' to file 'file::memory:' seems to be established.
time="     0.480" type="debug" -> core: Custom ID of feed when loading from DB is '1'.
time="     0.480" type="debug" -> core: Custom ID of feed when loading from DB is '2'.
time="     0.480" type="debug" -> core: Custom ID of feed when loading from DB is '3'.
time="     0.480" type="debug" -> core: Custom ID of feed when loading from DB is '4'.
time="     0.480" type="debug" -> core: Custom ID of feed when loading from DB is '5'.
time="     0.480" type="debug" -> core: Custom ID of feed when loading from DB is '6'.
time="     0.481" type="debug" -> core: Custom ID of feed when loading from DB is '7'.
time="     0.481" type="debug" -> core: Custom ID of feed when loading from DB is '8'.
time="     0.481" type="debug" -> core: Custom ID of feed when loading from DB is '9'.
time="     0.481" type="debug" -> core: Custom ID of feed when loading from DB is '10'.
time="     0.481" type="debug" -> core: Custom ID of feed when loading from DB is '11'.
time="     0.482" type="debug" -> core: Custom ID of feed when loading from DB is '12'.
time="     0.482" type="debug" -> core: Custom ID of feed when loading from DB is '13'.
time="     0.482" type="debug" -> core: Custom ID of feed when loading from DB is '14'.
time="     0.482" type="debug" -> core: Custom ID of feed when loading from DB is '15'.
time="     0.483" type="debug" -> core: Custom ID of feed when loading from DB is '16'.
time="     0.483" type="debug" -> core: Custom ID of feed when loading from DB is '17'.
time="     0.483" type="debug" -> core: Custom ID of feed when loading from DB is '18'.
time="     0.483" type="debug" -> core: Custom ID of feed when loading from DB is '19'.
time="     0.484" type="debug" -> core: Custom ID of feed when loading from DB is '20'.
time="     0.484" type="debug" -> core: Custom ID of feed when loading from DB is '21'.
time="     0.484" type="debug" -> core: Custom ID of feed when loading from DB is '22'.
time="     0.484" type="debug" -> core: Custom ID of feed when loading from DB is '23'.
time="     0.485" type="debug" -> core: Custom ID of feed when loading from DB is '25'.
time="     0.485" type="debug" -> core: Custom ID of feed when loading from DB is '26'.
time="     0.485" type="debug" -> core: Custom ID of feed when loading from DB is '27'.
time="     0.485" type="debug" -> core: Custom ID of feed when loading from DB is '28'.
time="     0.485" type="debug" -> core: Custom ID of feed when loading from DB is '29'.
time="     0.486" type="debug" -> database: SQLite database connection 'RecycleBin' to file 'file::memory:' seems to be established.
time="     0.486" type="debug" -> database: SQLite database connection 'ImportantNode' to file 'file::memory:' seems to be established.
time="     0.486" type="debug" -> database: SQLite database connection 'UnreadNode' to file 'file::memory:' seems to be established.
time="     0.487" type="debug" -> database: SQLite database connection 'LabelsNode' to file 'file::memory:' seems to be established.
time="     0.487" type="debug" -> database: SQLite connection 'StandardServiceRoot' is already active.
time="     0.487" type="debug" -> database: SQLite database connection 'StandardServiceRoot' to file 'file::memory:' seems to be established.
time="     0.487" type="debug" -> database: SQLite database connection 'TtRssServiceEntryPoint' to file 'file::memory:' seems to be established.
time="     0.487" type="debug" -> gui: User wants to have tray icon.
time="     0.488" type="warning" -> gui: Showing tray icon with little delay.
time="     0.488" type="debug" -> gui: Feed list item expanded - Administrator (RSS/ATOM/JSON)
time="     0.488" type="debug" -> gui: Feed list item expanded - Games
time="     0.488" type="debug" -> gui: Feed list item expanded - Giveaway
time="     0.488" type="debug" -> gui: Feed list item expanded - Дота
time="     0.491" type="debug" -> core: No execution message received from other app instances.
time="     0.539" type="debug" -> gui: Hovered link: 'QUrl()'.
time="     0.539" type="debug" -> core: Silencing GUI message: ''.
time="     0.987" type="warning" -> gui: Tray icon is available, showing now.
time="     0.989" type="debug" -> gui: Creating SystemTrayIcon instance.
time="     0.998" type="debug" -> gui: Showing tray icon immediately.
time="     1.067" type="debug" -> gui: Tray icon displayed.
time="     1.405" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     2.423" type="debug" -> network: Destroying Downloader instance.
time="     2.423" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="     6.699" type="debug" -> gui: Message splitter moved.
time="    25.280" type="debug" -> gui: Main window hide event
time="    25.281" type="debug" -> gui: Main window close event
time="    25.282" type="debug" -> core: Cleaning up resources and saving application state.
time="    25.282" type="debug" -> core: Close lock was obtained safely.
time="    25.283" type="debug" -> core: Stopping StandardServiceRoot instance.
time="    25.283" type="debug" -> feed-downloader: Destroying FeedDownloader instance.
time="    25.283" type="debug" -> database: Saving in-memory working database back to persistent file-based storage.
time="    25.283" type="debug" -> database: SQLite database connection 'SaveFromMemory' to file 'file::memory:' seems to be established.
time="    25.297" type="debug" -> gui: Destroying FormMain instance.
time="    25.297" type="debug" -> gui: Destroying TabWidget instance.
time="    25.298" type="debug" -> gui: Destroying FeedMessageViewer instance.
time="    25.298" type="debug" -> gui: Destroying BaseToolBar instance.
time="    25.299" type="debug" -> network: Destroying Downloader instance.
time="    25.299" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="    25.301" type="debug" -> gui: Destroying MessagesView instance.
time="    25.301" type="debug" -> gui: Destroying BaseToolBar instance.
time="    25.302" type="debug" -> gui: Destroying FeedsView instance.
time="    25.302" type="debug" -> gui: Destroying TabBar instance.
time="    25.302" type="debug" -> gui: Destroying StatusBar instance.
time="    25.303" type="debug" -> gui: Destroying SystemTrayIcon instance.
time="    25.319" type="debug" -> core: Destroying Application instance.
time="    25.319" type="debug" -> core: Destroying Mutex instance.
time="    25.335" type="debug" -> gui: Destroying IconFactory instance.
time="    25.335" type="debug" -> core: Destroying FeedReader instance.
time="    25.335" type="debug" -> feed-model: Destroying FeedsModel instance.
time="    25.335" type="debug" -> feed-model: Destroying FeedsProxyModel instance
time="    25.336" type="debug" -> message-model: Destroying MessagesModel instance.
time="    25.336" type="debug" -> message-model: Destroying MessagesProxyModel instance.

### Operating system and version

* OS: Windows 10 
* RSS Guard version: rssguard-devbuild-607439e49-win10

**Comment by martinrotter** [comment]
Managed to reproduce

**Comment by martinrotter** [comment]
1ab372a0a

Can you test when devbuild compiles?

**Comment by Ac314** [comment]
> [1ab372a](https://github.com/martinrotter/rssguard/commit/1ab372a0afebbcf214f8521b83e0996f30adeae1)
> 
> Can you test when devbuild compiles?

Thanks, of course I will check.

**Comment by Ac314** [comment]
Tested with devbuild-9439d775e-win10 - bug fixed.

**Comment by Ac314** [comment]
Stopped working in rssguard-devbuild-c152df758.

**Comment by Ac314** [comment]
I just wanted to bump it to inform that is still does not work in the current dev build (07eb444d9-win10). It stopped working in some of the dev builds earlier and does not work ever since.
