### ISSUE TITLE
[BUG] \ [FR?]: feed icon culumns disappeared

### ISSUE THREAD

**Issue by Owyn** [martinrotter/rssguard#1276]
### Brief description of the issue

In 4.2.2 I had feed icon columns and it was very handy to see right away which feed an article belonged to but... in 4.6.3 they are **gone**, replaced by "unread green dots"

Before: 
![image](https://github.com/martinrotter/rssguard/assets/1309656/59d979c8-ed7d-4915-be0f-d3bbed05e8a6)

Now:
![image](https://github.com/martinrotter/rssguard/assets/1309656/c1ac6c5e-34ef-489d-b62c-61198f16e9c7)

### How to reproduce the bug?

1. Upgrade to a version with unread green dots new feature

### What was the expected result?

Keeping old features

### What actually happened?

Old features got deleted

### Debug log

[rssguard.log](https://github.com/martinrotter/rssguard/files/14001874/rssguard.log)

### Operating system and version

* OS: Win 10
* RSS Guard version: 4.6.3 Lite Portable

**Comment by Owyn** [comment]
Interesting choice of settings, I understand it is so that all users get new dots after updating?

I wanted to have both dots and icons tho...

**Comment by martinrotter** [comment]
It is configurable in settings, either icons or dots.
