### ISSUE TITLE
clicking left side empty space will make the main page empty

### ISSUE THREAD

**Issue by nahid6970** [martinrotter/rssguard#1277]
### Brief description of the feature request

i used to use rssowl so where if i click left side empty side  it wont affect the articles butt in rssguard if i click left side empty space , the main page shows nothing
![image](https://github.com/martinrotter/rssguard/assets/93816648/8de66767-fb6d-4b67-8a06-158993786191)

and when i click the left empty page it looks like this
![image](https://github.com/martinrotter/rssguard/assets/93816648/6fa7b058-54f2-49bd-9200-20f11b582e98)

**Comment by nahid6970** [comment]
sorry the next image is like this
![image](https://github.com/martinrotter/rssguard/assets/93816648/49e6a5a3-0c99-4b25-9089-fab52dee43bd)

**Comment by martinrotter** [comment]
Yes, this is a feature, not a bug.
