### ISSUE TITLE
[BUG]: fails to fetch odysee feeds

### ISSUE THREAD

**Issue by atomGit** [martinrotter/rssguard#1278]
### Brief description of the issue

fails to fetch odysee feeds, no error

### How to reproduce the bug?

example: `https://odysee.com/$/rss/@EarthNewspaper:e`

### What was the expected result?

fetch feed

### What actually happened?

fail, no error

### Debug log

where is it?

### Operating system and version

* OS: linux
* RSS Guard version: 4.6.3

**Comment by martinrotter** [comment]
Fixed, thanks for reporting.
