### ISSUE TITLE
[BUG]: crash when adding discovered feeds in dev build

### ISSUE THREAD

**Issue by Owyn** [martinrotter/rssguard#1280]
### Brief description of the issue

I clicked discover on "https://drakescans.com/" then selected all and clicked "import" - it did nothing, so I clicked few more times - and it crashed

### How to reproduce the bug?

1 add feed 
2 https://drakescans.com/
3 click "discover"
4 click select all
5 click "import" - but not once but few times ( I did it cuz I felt that nothing happened after I clicked it 1st time )
- crash

### What was the expected result?

no crash

### What actually happened?

crash

### Debug log

[rssguard.log](https://github.com/martinrotter/rssguard/files/14012468/rssguard.log)

### Operating system and version

* OS: Win 10
* RSS Guard version: devbuild-cda0f79e1-lite-win10.7z

Additional info: - apparently clicking multiple times is not necessary for it to crash, it crashes anyway even if clicked ones

**Comment by martinrotter** [comment]
Fixed. The problem was that JSON document was mistakenly identified to be JSON feed while in fact it was not.
