### ISSUE TITLE
[BUG]: out of bounds window positions

### ISSUE THREAD

**Issue by Owyn** [martinrotter/rssguard#1281]
### Brief description of the issue

My newly launched clean Lite Portable version out of borders like this
![image](https://github.com/martinrotter/rssguard/assets/1309656/8acf9a7f-b371-4651-b714-ab006fc22508)

same for when I click "advanced mode" after "add a feed"
![image](https://github.com/martinrotter/rssguard/assets/1309656/a4cb71a6-6dd4-43ee-98a5-802001c82bd2)

even thought there's enough space on the screen to fully fit the window

### How to reproduce the bug?

1 have windows default zoom set to 125%
2 have QT_SCALE_FACTOR env var set to 1.5
3 have 1920x1200 screen resolution

### What was the expected result?

fully visible windows

### What actually happened?

out of bounds windows

### Debug log

[rssguard.log](https://github.com/martinrotter/rssguard/files/14012779/rssguard.log)

### Operating system and version

* OS: Win 10
* RSS Guard version: devbuild-cda0f79e1-lite-win10.7z

**Comment by martinrotter** [comment]
e48677b66

OK, I added automatic logic for **all** modal dialogs and added the same logic when loading main window.

So now, SIZE of windows should not exceed screen size. POSITION of dialogs is not solved yet.

First, please wait until the fix compiles and test the sizes. If they will be okay, I will fix the positions.

**Comment by Owyn** [comment]
> e48677b

Seems to be working 
![image](https://github.com/martinrotter/rssguard/assets/1309656/c8d71de2-7371-4b38-bfe1-7da57e77ebdf)
(not sure if the left size is few px out of bounds or not tho 😁 )

advanced mode shows up fine as well:
![image](https://github.com/martinrotter/rssguard/assets/1309656/f1a2a28e-bb64-446b-afed-ede49fc19af6)

**Comment by martinrotter** [comment]
OK. Added position guarding too.

8e2de8c3c

Check when compiled and let know.

**Comment by Owyn** [comment]
![image](https://github.com/martinrotter/rssguard/assets/1309656/7dbd8714-582e-49d6-962e-c4d76b44d9e1)
![image](https://github.com/martinrotter/rssguard/assets/1309656/fa203e59-67a2-4479-aa27-58a8a126c18d)
👍

**Comment by martinrotter** [comment]
ok, closing, there are some cases where tweaks would have to be made in the future (like keeping aspect ration of down-sized dialogs etc)
