### ISSUE TITLE
macOS: The Resources tab in the About dialog has poor layout

### ISSUE THREAD

**Issue by phedlund** [martinrotter/rssguard#129]
#### Brief description of the issue.

The Resources tab in the About dialog has poor layout.

#### How to reproduce the bug?

1. Open the About dialog
2. Select the Resources tab
3. 

#### What is the expected result?

Fields should resize with the dialog

#### What actually happened?

Fields do not resize with the dialog

#### Other information (logs, see Wiki)

<img width="1040" alt="screen shot 2017-07-09 at 2 50 22 pm" src="https://user-images.githubusercontent.com/884639/27997877-fa91b36c-64b5-11e7-91cd-31c5d9eee423.png">

**Comment by martinrotter** [comment]
Does this issue occur in other dialogs, etc. in "add feed" dialog?

**Comment by martinrotter** [comment]
Thanks to @phedlund.
