### ISSUE TITLE
[BUG]: twitter scrapper.py script dead?

### ISSUE THREAD

**Issue by Owyn** [martinrotter/rssguard#1298]
### Brief description of the issue

https://github.com/martinrotter/rssguard/blob/master/resources/scripts/scrapers/twitter.py no longer works

now when the Nitter alt frontend is dead cuz twitter closed its API or smth I was looking for ways to keep my twitter RSS, but the script here didn't help
![image](https://github.com/martinrotter/rssguard/assets/1309656/19390b6c-76f4-41b0-bfee-7a6984642a91)

### How to reproduce the bug?

![image](https://github.com/martinrotter/rssguard/assets/1309656/8e27d408-e22d-4a3d-81dc-abbf5f5ec960)

### What was the expected result?

a feed

### What actually happened?

error

### Debug log

[rssguard.log](https://github.com/martinrotter/rssguard/files/14297112/rssguard.log)

### Operating system and version

* OS: Win 10
* RSS Guard version: 4.3.3

**Comment by martinrotter** [comment]
Those sample scrapers are all basically "meant" to be dead. They are really "sample" scrapers, nothing more. I do not regularly check if they work or not. Only sometimes I fix some of them.

**Comment by aubreyz** [comment]
> Those sample scrapers are all basically "meant" to be dead. They are really "sample" scrapers, nothing more. I do not regularly check if they work or not. Only sometimes I fix some of them.

Yup understand that. But some of them are fairly fundamental (like Twitter/X). Would really enhance the use of rss guard if someone who knows what they are doing would update them, perhaps in response to issues raised here.

**Comment by martinrotter** [comment]
Yes I agree with you. But I do not really have time for that.
