### ISSUE TITLE
Have you fix my TinyTiny RSS problem

### ISSUE THREAD

**Issue by pixadex** [martinrotter/rssguard#13]
That we were trying to fix?

**Comment by martinrotter** [comment]
Hello, as you noticed, rssguard now fully migrated to github.

I tried to detect the problem. But I was not successfull. You need to provide application log. Without log, I cannot help you.

**Comment by pixadex** [comment]
Ok where can I find application log.

**Comment by martinrotter** [comment]
https://github.com/martinrotter/rssguard/wiki#generating-debug-log-file

**Comment by pixadex** [comment]
ok good but I think I need to download it again, you just have .rar download version and how do you install that, because I was using .exe.

**Comment by martinrotter** [comment]
@pixadex Yea, all downloads are temporarily gone. I will release 3.3.0 today. Note that exe installers will not come back, because I totally adopted archives. Therefore new versions, starting with 3.3.0 will be released in zip archive for Windows.

**Comment by pixadex** [comment]
An how do you run that?

**Comment by pixadex** [comment]
Hey I just downloaded 3.3.0 and name of file is CHANGELOG  is that name of the file ?

**Comment by pixadex** [comment]
Ok after downloading rss guard 3.3.0 way better than all other version, but tiny tiny rss version before my problem was better but now works 1/2 % but what ever, I think that's it. AN I'll also donate in future. THANK YOU.

**Comment by martinrotter** [comment]
Well, it's good to see that there is improvement, but it would be best to actually find the issue. Nevertheless, I mark this as solved. In the future, if you find a bug, please, follow the wiki and obtain log output file. It is really important.

:)
