### ISSUE TITLE
[BUG]: Feed items (youtube videos) recieved anew when they get updated

### ISSUE THREAD

**Issue by turbodude** [martinrotter/rssguard#1307]
### Brief description of the issue

Feed items (youtube videos) recieved anew when they get updated. If the item was deleted, it is received again. If it wasn't deleted, only marked read, the old one gets replaced by a new one, with new time stamp.
I noticed this only with a youtube channel, but it's probably the case for any other feed.

### How to reproduce the bug?

1. Subscribe to https://www.youtube.com/feeds/videos.xml?channel_id=UCERUmrDh9hmqEXBsnYFNTIA 
2. Wait for a new article
3. Wait for that article to get updated

### What was the expected result?

QuiteRSS handled this by receiving a duplicate. IMO that is a better scenario than what's happening now. Because that way you retain the original item with its true time stamp.
The other option would be not to receive updated items at all. Or update the content, without updating the time stamp and read status.

### What actually happened?

Old feed item either gets deleted, or has its time stamp and read status updated.

### Debug log

Can't do that since the described event occurs sporadically 

### Operating system and version

* OS: Windows 11 22H2 22621.3155
* RSS Guard version: 4.6.3

**Comment by turbodude** [comment]
Yes, looks like it's fixed in the 27/02/2024 build. Thank you! 
So what happens now if, say, video description gets updated? Will QuiteRSS ignore the update altogether?

**Comment by martinrotter** [comment]
Update is not ignored, but existing read state is respected.

**Comment by turbodude** [comment]
Hey, the issue is back, as described initially... 
Could it make a difference if it's RSS instead of ATOM?
