### ISSUE TITLE
[BUG]: article list filter only apply to feed list

### ISSUE THREAD

**Issue by nsklaus** [martinrotter/rssguard#1308]
### Brief description of the issue

i added toolbar icon "show only unread item" on  the article list toolbar.
when i click it, the filtering is applied on feed list and not on article list.

### How to reproduce the bug?

1) go to `settings > user interface > toolbars`
2) select "article list toolbar" from the drop down menu
3) add "show only unread items"
4) apply and exit settings
5) on rssguard main window, click the newly added button on the toolbar
6) confirm feeds list is being filtered instead of articles list.

### What was the expected result?

i expected the articles list filter to apply to articles list and not on feeds list.

### What actually happened?

the feeds list was being filtered to show only unread items instead of articles list.

### Debug log

[rssguard.log](https://github.com/martinrotter/rssguard/files/14465930/rssguard.log)

### Operating system and version

* OS: windows 11 
* RSS Guard version: 4.6.3

**Comment by martinrotter** [comment]
You are mistaken.

Menu item "Show unread items only" really is placed by default in "Feeds" menu and you can really add it to article toolbar too, but it controls feeds list items!

For filtering article list items, you use "article list filter" menu button group which is by default placed in article toolbar. See screenshots below.

![rssguard_wQECnIK4qx](https://github.com/martinrotter/rssguard/assets/1255302/01488576-63dc-4058-ba56-72a3cf0991df)
![rssguard_IwZZG0uutn](https://github.com/martinrotter/rssguard/assets/1255302/6733b331-9165-4fa7-88ad-f99c0b1a6490)
![rssguard_9GMHMYfPoC](https://github.com/martinrotter/rssguard/assets/1255302/31e29a3f-1a35-41c5-a261-e7ea3f134ef6)
