### ISSUE TITLE
[BUG]: Youtube channel subscriptions keep showing old/seen videos for weeks!

### ISSUE THREAD

**Issue by tuqueque** [martinrotter/rssguard#1309]
### Brief description of the issue

Hello, first of all, RSS Guard is currently my favorite RSS reader, I'm pretty happy with it, but there's an ubelievably annoying "bug" that almost makes it a deal breaker for me.

I have a bunch of Youtube channels that I follow via RSS and in general, works, but every time feeds are updated in RSS Guard, some of the already seen channels, keep showing old/seen videos. It doesn't matter if I click on "Feeds > Mark all read", the next time RSS Guard update all feeds, some channels keep showing some of the same old videos.

This doesn't happen in other RSS readers I've used, like Liferea!

Also, I noticed that some pages/blogs that work fine in Liferea, don't work in RSS Guard, like:
https://simplex.chat/blog

In Liferea, every new post in the blog gets updated fine in Liferea, but I cannot import this blog in RSS Guard... Could this be possible to do in RSS Guard?

Thank you in advance!

### How to reproduce the bug?

1.- Add a Youtube video feed... e.g.: https://www.youtube.com/feeds/videos.xml?channel_id=UCHnyfMqiRRG1u-2MsSQLbXA

2.- Sometimes feed updates show already seen videos.

### What was the expected result?

Not show already seen videos in later feed updates.

### What actually happened?

Old Youtube videos keep showing!

### Debug log

It doesn't show any log when I click "Help > Display application log"

### Operating system and version

* OS: Manjaro (Linux).
* RSS Guard version: 4.6.3

P.S.: This bug report form is a bit patronizing!

**Comment by martinrotter** [comment]
This was already solved many times and there are many duplicates, make sure you do your searches first.

Anyway. The issue with YT feeds was long-standing and should be fixed in latest development builds. Test it and report back but it should be fixed. Or wait for new release.

**Comment by martinrotter** [comment]
As for other issues you mention in this bug report -> create separate reports for them.
