### ISSUE TITLE
[BUG]: Changing the notification sound causes the app to crash or close

### ISSUE THREAD

**Issue by Chipsum** [martinrotter/rssguard#1317]
### Brief description of the issue

Changing the notification sound causes the app to crash or close.

### How to reproduce the bug?

1. Tools>Settings>Notifications>New (unread) articles fetched.
2. Sound>Browse>Choose wav file (C:/Windows/Media/Windows Proximity Notification.wav).
3. Play>plays normally.
4. Apply>rssguard closes.

### What was the expected result?

To apply the notification Sound.

### What actually happened?

The app closes (crashes ?)

### Debug log

time="     0.092" type="debug" -> core: Initializing settings in 'C:\RSS Guard\data4\config\config.ini' (portable way).
time="     0.092" type="debug" -> core: Starting to load active localization. Desired localization is 'en_US'.
time="     0.093" type="debug" -> core: Application localization 'en_US' loaded successfully, specifically sublocalization 'en_US' was loaded.
time="     0.093" type="warning" -> core: Qt localization 'en_US' WAS NOT loaded successfully.
time="     0.479" type="debug" -> database: File-based SQLite database connection 'DatabaseFactory' to file 'C:\RSS Guard\data4\database\database.db' seems to be established.
time="     0.479" type="debug" -> database: File-based SQLite database has version '8'.
time="     0.480" type="debug" -> gui: Available icon theme paths: QList(:/icons, :/graphics, C:\RSS Guard\data4\icons, C:/RSS Guard\icons)
time="     0.481" type="debug" -> gui: Installed icon themes are: '', 'Breeze', 'Breeze Dark', 'Faenza', 'Numix'
time="     0.481" type="debug" -> gui: Loading icon theme 'Breeze'.
time="     0.481" type="debug" -> gui: Found path of base skin: ':\skins\nudus-base'.
time="     0.481" type="debug" -> gui: Base file ':\skins\nudus-base\html_wrapper.html' exists, using it for the skin.
time="     0.481" type="debug" -> gui: Local file ':\skins\nudus-light\html_style.css' exists, using it for the skin.
time="     0.482" type="debug" -> gui: Base file ':\skins\nudus-base\html_enclosure_image.html' exists, using it for the skin.
time="     0.482" type="debug" -> gui: Base file ':\skins\nudus-base\html_single_message.html' exists, using it for the skin.
time="     0.482" type="debug" -> gui: Base file ':\skins\nudus-base\html_enclosure_every.html' exists, using it for the skin.
time="     0.482" type="debug" -> gui: Local file ':\skins\nudus-light\qt_style.qss' exists, using it for the skin.
time="     0.482" type="debug" -> gui: Base file ':\skins\nudus-base\html_adblocked.html' exists, using it for the skin.
time="     0.482" type="debug" -> gui: OS defines color scheme: 'Qt::ColorScheme::Light'.
time="     0.482" type="debug" -> gui: Setting style: 'Fusion'.
time="     0.483" type="debug" -> gui: Skin 'nudus-light' loaded. Lite: 'false'.
time="     0.483" type="warning" -> core: User CSS style was not provided in file 'C:\RSS Guard\data4\web\user-styles.css'.
time="     0.484" type="debug" -> network: Persistent web data storage path: 'C:\RSS Guard\data4\web\storage'.
time="     0.484" type="debug" -> network: Disabling application-wide proxy completely.
time="     0.484" type="debug" -> core: SQLite version: '3.42.0'.
time="     0.489" type="debug" -> core: OpenSSL version: 'OpenSSL 3.0.12 24 Oct 2023'.
time="     0.489" type="debug" -> core: OpenSSL supported: 'true'.
time="     0.489" type="debug" -> core: Global thread pool has 8 threads.
time="     0.489" type="debug" -> core: Setting locale for LC_NUMERIC to C as libmpv requires it.
time="     0.489" type="debug" -> core: Instantiated class  'Application'.
time="     0.493" type="debug" -> database: SQLite database connection 'MessagesModel' to file 'C:/RSS Guard/data4/database/database.db' seems to be established.
time="     0.498" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, Feeds.is_rtl, CASE WHEN LENGTH(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Messages.labels LIKE "%." || Labels.custom_id || ".%") as msg_labels, Messages.labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1;'.
time="     0.498" type="debug" -> core: Enabling support for very small auto-fetching intervals. This might have performance consequences.
time="     0.499" type="debug" -> core: Auto-download timer started with interval 1000 ms.
time="     0.499" type="debug" -> core: Creating FeedDownloader singleton.
time="     0.500" type="debug" -> gui: Creating main application form in thread: '0x5404'.
time="     0.506" type="debug" -> gui: Current row changed - proxy 'QModelIndex(-1,-1,0x0,QObject(0x0))', source 'QModelIndex(-1,-1,0x0,QObject(0x0))'.
time="     0.512" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     0.535" type="debug" -> gui: Creating tray icon menu.
time="     0.545" type="warning" -> gui: Dialog 'FormMain' was moved from 'QPoint(0,-8)' to 'QPoint(312,177)'.
time="     0.604" type="debug" -> CTRL is NOT pressed while sorting articles - sorting with standard mode.
time="     0.604" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, Feeds.is_rtl, CASE WHEN LENGTH(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Messages.labels LIKE "%." || Labels.custom_id || ".%") as msg_labels, Messages.labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1 ORDER BY Messages.date_created DESC;'.
time="     0.609" type="debug" -> core: Showing the main window when the application is starting.
time="     0.632" type="debug" -> database: SQLite database connection 'FeedReader' to file 'C:/RSS Guard/data4/database/database.db' seems to be established.
time="     0.633" type="debug" -> database: SQLite database connection 'FeedlyEntryPoint' to file 'C:/RSS Guard/data4/database/database.db' seems to be established.
time="     0.633" type="debug" -> database: SQLite database connection 'GmailEntryPoint' to file 'C:/RSS Guard/data4/database/database.db' seems to be established.
time="     0.633" type="debug" -> database: SQLite database connection 'GreaderEntryPoint' to file 'C:/RSS Guard/data4/database/database.db' seems to be established.
time="     0.634" type="debug" -> database: SQLite database connection 'OwnCloudServiceEntryPoint' to file 'C:/RSS Guard/data4/database/database.db' seems to be established.
time="     0.634" type="debug" -> database: SQLite database connection 'StandardServiceEntryPoint' to file 'C:/RSS Guard/data4/database/database.db' seems to be established.
time="     0.635" type="debug" -> database: SQLite database connection 'StandardServiceRoot' to file 'C:/RSS Guard/data4/database/database.db' seems to be established.
time="     0.637" type="debug" -> core: Custom ID of feed when loading from DB is '1'.
time="     0.637" type="debug" -> core: Custom ID of feed when loading from DB is '2'.
time="     0.638" type="debug" -> core: Custom ID of feed when loading from DB is '3'.
time="     0.638" type="debug" -> database: SQLite database connection 'RecycleBin' to file 'C:/RSS Guard/data4/database/database.db' seems to be established.
time="     0.638" type="debug" -> database: SQLite database connection 'ImportantNode' to file 'C:/RSS Guard/data4/database/database.db' seems to be established.
time="     0.639" type="debug" -> database: SQLite database connection 'UnreadNode' to file 'C:/RSS Guard/data4/database/database.db' seems to be established.
time="     0.639" type="debug" -> database: SQLite database connection 'LabelsNode' to file 'C:/RSS Guard/data4/database/database.db' seems to be established.
time="     0.639" type="debug" -> database: SQLite connection 'StandardServiceRoot' is already active.
time="     0.640" type="debug" -> database: SQLite database connection 'StandardServiceRoot' to file 'C:/RSS Guard/data4/database/database.db' seems to be established.
time="     0.640" type="debug" -> database: SQLite database connection 'TtRssServiceEntryPoint' to file 'C:/RSS Guard/data4/database/database.db' seems to be established.
time="     0.640" type="debug" -> gui: User wants to have tray icon.
time="     0.640" type="warning" -> gui: Showing tray icon with little delay.
time="     0.640" type="debug" -> gui: Feed list item expanded - chipsum (RSS/ATOM/JSON)
time="     0.640" type="debug" -> gui: Feed list item expanded - Emulators
time="     0.641" type="debug" -> core: No execution message received from other app instances.
time="     0.653" type="debug" -> gui: Message splitter moved.
time="     0.794" type="debug" -> gui: Hovered link: 'QUrl()'.
time="     1.142" type="warning" -> gui: Tray icon is available, showing now.
time="     1.144" type="debug" -> gui: Creating SystemTrayIcon instance.
time="     1.155" type="debug" -> gui: Showing tray icon immediately.
time="     1.156" type="debug" -> gui: Tray icon displayed.
time="     4.293" type="warning" -> gui: Dialog 'FormSettings' was moved from 'QPoint(0,0)' to 'QPoint(560,229)'.
time="     9.235" type="debug" -> core: Using QSoundEffect to play notification sound.
time="    10.720" type="debug" -> core: Syncing settings.

### Operating system and version

* OS: Windows 11
* RSS Guard version: Latest Stable 4.6.3 & Latest dev build (rssguard-devbuild-07eb444d9-win10)

**Comment by martinrotter** [comment]
It is now crashing when I test it, sorry I am not just able to reproduce. Either test now with 4.6.6 I am about to release. Also, It would be nice if you would be able to generate crashdump.

Maybe someone other will spot it and we will be able to solve.

**Comment by Chipsum** [comment]
@martinrotter Anything you want, here is the crashdump
https://pastebin.com/6yGxvVFf
[dump file](https://github.com/martinrotter/rssguard/files/14614124/rssguard.exe.15576.zip)

**Comment by martinrotter** [comment]
Can you please do the same with 4.6.6? Would be great. Thank you!

**Comment by Chipsum** [comment]
@martinrotter Sure thing:
https://pastebin.com/QFCR
[dump file](https://github.com/martinrotter/rssguard/files/14614240/rssguard.exe.9444.zip)
BT8A

**Comment by martinrotter** [comment]
which file exactly did you install?

**Comment by Chipsum** [comment]
> which file exactly did you install?

https://github.com/martinrotter/rssguard/releases/download/4.6.6/rssguard-4.6.6-6cf2717ed-win10.exe

**Comment by martinrotter** [comment]
also, does the error also happen if you start the rssguard with completely clean user data folder ("data4")?

**Comment by Chipsum** [comment]
This is WinMerge comparison of the two dumps:
https://i.imgur.com/oPMoFuK.png

**Comment by Chipsum** [comment]
> also, does the error also happen if you start the rssguard with completely clean user data folder ("data4")?

Let me check

**Comment by Chipsum** [comment]
@martinrotter Solved with deleting data4 :D

**Comment by martinrotter** [comment]
> @martinrotter Solved with deleting data4 :D

NOOOO. Do you still have that "faulty" data4? Can you perhaps share?

**Comment by Chipsum** [comment]
@Chipsum I totally removed it😬
Let me stop adding any data to my SSD and try a recovery attempt

**Comment by Chipsum** [comment]
@martinrotter Here is the recovered folder
https://www.mediafire.com/file/g6dl5urwjvjppk5/data4_recovered.zip/file

**Comment by martinrotter** [comment]
FOund it.

**Comment by Chipsum** [comment]
@martinrotter Additionally, it makes popping noises when I select an MP3 file.
