### ISSUE TITLE
[FR]: Add a copy to markdown option for the required OS and RSS Guard version to use on GitHub

### ISSUE THREAD

**Issue by shoulders** [martinrotter/rssguard#1318]
### Brief description of the feature request

In the About RSS Guard page it could be a useful tool to add a button to copy all of the required information into the clipboard as markdown that could then be used to paste information here.

## Webmin/Virtualmin does this and it is very useful:

![image](https://github.com/martinrotter/rssguard/assets/319997/9a4307f2-8c2b-4035-8c7c-0059811bc662)

### -->
```
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.9.0       |
|  Theme version       |     21.09.5      |
|  Package updates     |      30  package updates are available   |
```
### -->
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.9.0       |
|  Theme version       |     21.09.5      |
|  Package updates     |      30  package updates are available   |

### -->
![image](https://github.com/martinrotter/rssguard/assets/319997/b2d2428b-8ae7-4090-b81e-33844e29e979)

## Relevant information
RSS Guard
Version: 4.6.3 (built on Windows/AMD64)
Revision: 43d164dc4
Build date: 15/12/2023 11:52
Qt: 6.5.3 (compiled against 6.5.3)
OS: Windows10 Pro 64-Bit

**Comment by martinrotter** [comment]
This is I believe not really needed, because users just copy the plain text info in top of About dialog like you did and it just works.

**Comment by martinrotter** [comment]
But will add a button to copy that plain text.

**Comment by martinrotter** [comment]
![image](https://github.com/martinrotter/rssguard/assets/1255302/0c492065-d1fe-439b-a2f8-d8e9d2ebda04)

### RSS Guard
**Version:** 4.6.6 (built on Windows/AMD64)
**Revision:** 202da682b
**Build date:** 22.03.24 10:45
**OS:** Windows 10 Version 22H2
**Qt:** 6.6.0 (compiled against 6.6.0)

**Comment by shoulders** [comment]
Brilliant, thanks
