### ISSUE TITLE
[FR]: Add Horizontal scroll instead of dynamically resizing the `Title` column

### ISSUE THREAD

**Issue by shoulders** [martinrotter/rssguard#1319]
### Background
- When you hover over the right-hand side of the `Title` column you do not get the resize cursor and so cannot use this method to directly resize the `Title` column
- You can make the `Title` column smaller by stretching the column to the immediate left. This is causes the `Title` column to be squashed rather than the columns all being pushed to the right and then the presence of a horizontal scroll bar as required.
- when you resize the RSSGuard window it is only the `Title` column that is resized, the rest of the columns stay at their fixed size.

So it looks like the dynamic resizing of the `Title` column is to allow the resizing of the columns and the window.

### The issue
- When compared to almost all other apps with configurable columns the way RSS guard handles columns is a bit odd and can be hard to get your head around.
- Everyone expects to be able to resize columns and if they don't all fit on screen, a horizontal scroll bar will appear.

### Request
- can you make the `Title` column directly resizeable
- Add in the use of a horizontal scroll bar instead of relying on the `Title` column being dynamically resized.

### Related
#1079 shows the issue in the video, although he is trying to show an issue with the date field not being resizable, but it is. 😄 

### Relevant information
RSS Guard
Version: 4.6.3 (built on Windows/AMD64)
Revision: 43d164dc4
Build date: 15/12/2023 11:52
Qt: 6.5.3 (compiled against 6.5.3)
OS Windows 10 Pro 64-Bit

**Comment by martinrotter** [comment]
Yes, I unified the behavior for all columns. Fixed.
