### ISSUE TITLE
[FR]: How to change the feed TYPE for all selected feeds at once?

### ISSUE THREAD

**Issue by Dean-Corso** [martinrotter/rssguard#1321]
### Brief description of the feature request

Hi guys,

normally I'm using the old QuiteRSS tool which is no more continued and I found this rssguard tool a short while ago and gave it try. I was trying to export my feeds from QuiteRSS into rssguard and got some issues with the used TYPE. I imported all my Github feeds which using the ATOM TYPE extension...

`<outline text="Release notes from rssguard" type="rss" htmlUrl="https://github.com/martinrotter/rssguard/releases" xmlUrl="https://github.com/martinrotter/rssguard/releases.atom"/>`

...but the type is declared as "rss". The example feed in outline tags above is from my opml export file of QuiteRSS. So when I import the feeds from the opml file then all getting added but the TYPE is set to RSS 2.0 / 2.1 and this type is not working for the feeds and they keep empty. Only when I change the TYPE to ATOM 1.0 then its working. Problem now is that I got many atom type feeds and I have to change them all manually and I would like to change them all at once you know. Otherwise I tried to edit the file by adding the (version="ATOM") tag but this failed to import anything. So I got tons of feeds and don't wanna change them all manually to set the correctly TYPE / VERSION ATOM to make them work. My feature request in this case whether you could add a TYPE change for multiple selected feeds (more than one) or all feeds of a selected folder etc? At the moment I can just change it when I have selected one single feed and otherwise it does not work. Thanks.

**Comment by martinrotter** [comment]
its really simple, simply select feeds you want to edit with CTRL+mouse combo and select context menu item "edit selected items"

OR select parent category/account item and select "edit child feeds" or "edit child feeds (recursive)"
