### ISSUE TITLE
[FR]: How to get media content playing inside of internal browser?

### ISSUE THREAD

**Issue by Dean-Corso** [martinrotter/rssguard#1324]
### Brief description of the feature request

So I tried to open few articles in the internal browser and got some issues for some media content...
![DR_2024-03-13_004512](https://github.com/martinrotter/rssguard/assets/88513086/dece242d-668b-438c-b099-ec9b7d0c2c2a)
...not playing / handle it. Why? Still using a old IE?

So in case when the internal browser can't handle the media content I can use the media player used in rssguard but somehow I can not use the media player for sites I did open directly in internal browser. In this case the menu entry is ghosted and the question is why?

Example: I have a article in my feed I do select and now I can also use the media player on this selected article. When I now open this article in internal browser and clicking then on the URL tag to open the article URL directly to see the website in this browser then I can't use the media player anymore.

Otherwise just open any website in internal browser and this I want to play / handle with the media player (yt-dlp) and not the selected article. Do you know what I mean? Web URL in browser bar pipe to media player. On the image above I did posted you can see the media content is not playing in browser itself and at the same time the "play in media player" popup menu entry is not select able but it should be enabled to use with the loaded website in browser bar (not selected article). How to make this work? Otherwise can you make it work in next release?

**Comment by martinrotter** [comment]
give exact URL to feed and name of the article, and provide perhaps screencast of what exactly you do

**Comment by martinrotter** [comment]
1. RSS Guard contains full-blown Chromium web rendering core and is able to play **almost** all media which Chromium can. Sadly some webpages do not play, dont know why, maybe the error is in the webpage itself, dont know.
2. Flash player is not supported in RSS Guard.
3. If you right click any hyperlink, then "Play in media player" button is available and is not disabled.
4. Your assumptions about "InternetExplorer" are completely wrong. Your assumptions about yt-dlp are completely wrong.
5. I will add button to open loaded URL in media player.

**Comment by Dean-Corso** [comment]
Hi again,

so nobody needs and wants to use flash anymore. But its already strange that you get that info about even you use some Chromium core. In Chromium the media content is playing as it should. By the way, I have test another media content websites and they are also not playing, getting error message like "HTML5 Video not found" or "Format is supported" or no error info's is shown etc. Even the playlist (m3u8) steams it does not play as the link I did post before already. That's bad of course. In this case you have always to switch / open the external browser to get any media content playing or using that detour "Play in media player" which is also not the best method. Just try to find the problem and make your internal browser working to handle those basic media types to play them as it does in any browser. Just a advice.

About yt-dlp, so at all you need it to get the media URL of the website to use it with your media player. So or so you need it or otherwise nothing is playing. But as I said before, it would be much better to fix those internal browser issues RSS Guard has at the moment to make browsing comfortable without those errors all the time tying to play anything and using then the detour over your player or external browser etc. So that's a point I really don't like you know. [Here another playlist live stream](https://www.welt.de/tv-programm-live-stream/) where RSS Guard browser is showing nothing (not playing / no error info etc). Only source which works is Youtube.

The internal media player detour is just not nice and the player itself pretty lags and should only be used in exception cases but not as all the time solution you know. Maybe you can check this problem and find + fix the issues in best case.

MfG

**Comment by martinrotter** [comment]
Sorry I do not really like wording you chose.
