### ISSUE TITLE
[FR]: How to get better visual style look in RSS Guard?

### ISSUE THREAD

**Issue by Dean-Corso** [martinrotter/rssguard#1326]
### Brief description of the feature request

Hi @martinrotter,

I have another new question. I did noticed that the visual style in RSS Guards listviews is pretty odd / old. So I don't like that and do prefer the modern visual style in the listviews of Explorer. Why don't you just add this VS?

`SetWindowTheme(hwndList, L"Explorer", NULL);`
[SetWindowTheme function](https://learn.microsoft.com/en-us/windows/win32/api/uxtheme/nf-uxtheme-setwindowtheme)
So this explorer look is much better and comfortable to use instead that old VS style of Win95. 😃 So in your case I would change that pretty quick and I think the most users would also prefer that VS look like you also have in normal modern Windows Explorer with auto highlighting when you move over the listview entry's. Just add it or give us the choice to use it (enable it) for user like me who want to have that VS look. Thanks.

**Comment by martinrotter** [comment]
Go to settings -> user interface -> style, change to your liking.

windowsvista style is likely what you looking for as it internally uses the "SetWindowTheme" line your wrote above

![image](https://github.com/martinrotter/rssguard/assets/1255302/3d2fe2c2-f5e1-4641-9f16-1c3e13eff67a)
