### ISSUE TITLE
[BUG]: Windows Defender flags RSS Guard as a Trojan

### ISSUE THREAD

**Issue by Sakooooo** [martinrotter/rssguard#1329]
### Brief description of the issue

  ![image](https://github.com/martinrotter/rssguard/assets/78461130/a8d130ff-55c7-4532-be84-3e442396cebf)

### How to reproduce the bug?

1. Install new update FROM github or built in updater
2. Windows Defender flags said installer

### What was the expected result?

1. Install new update FROM github or built in updater
2. No detections

### What actually happened?

Windows defender flags the executable

### Debug log

None

### Operating system and version

* OS: Windows
* RSS Guard version: 4.6.4

**Comment by martinrotter** [comment]
False positive.

https://www.virustotal.com/gui/file/aa8aaf7ec98cc4eaaa885f1211be8e28265d83caa6b0626aef2d36e9c11cfda7

Look, RSS Guard is opensource app and its compilation happens via Github Actions. Everyone can review the compilation process and/or build the app by himself.

**Comment by Sakooooo** [comment]
alright thanks
