### ISSUE TITLE
3.4.1 doesn't compile

### ISSUE THREAD

**Issue by jluttine** [martinrotter/rssguard#133]
#### Brief description of the issue.

Cannot compile 3.4.1 whereas 3.4.0 did compile. Any ideas what could be wrong?

#### How to reproduce the bug?

1. Checkout 3.4.1.
2. Compile.

#### What is the expected result?

Successful build.

#### What actually happened?

```
src/services/standard/feedparser.cpp: In member function 'virtual QList<Message> FeedParser::messages()':
src/services/standard/feedparser.cpp:52:38: error: format not a string literal and no format arguments [-Werror=format-security]
       qDebug(qPrintable(ex.message()));
                                      ^
cc1plus: some warnings being treated as errors
make[1]: *** [Makefile.Release:35061: release/feedparser.o] Error 1
make[1]: Leaving directory '/tmp/nix-build-rssguard-3.4.1.drv-0/rssguard'
make: *** [Makefile:40: release] Error 2
```

**Comment by jluttine** [comment]
Btw, are the submodules required for the app? I built 3.4.0 without checking out the submodules and it compiled.

**Comment by martinrotter** [comment]
I was unreachable for a few weeks, will fix.

**Comment by martinrotter** [comment]
For submodules - read [wiki](https://github.com/martinrotter/rssguard/wiki/How-to-compile-RSS-Guard).

**Comment by martinrotter** [comment]
Working now?

**Comment by jluttine** [comment]
Yes, seems so! Thanks for the quick response and fix. Are you planning to make a new release with this fix soon?

**Comment by martinrotter** [comment]
OK, will release today.
