### ISSUE TITLE
[BUG]: 4.6.4/4.6.5 ignores size/position-settings in config.ini

### ISSUE THREAD

**Issue by mohafri** [martinrotter/rssguard#1333]
### Brief description of the issue

Since 4.6.4/4.6.5 the settings in config.ini regarding the settings-window and the position of the main-window are no longer respected. With 4.6.3 everything was fine.

My settings in config.ini:
settings_window_size=@Size(1008 474) - the window is too narrow with 4.6.4/4.6.5,
window_position=@Point(0 16) - the main window starts always centered with 4.6.4/4.6.5.
Changes to the settings are ignored.

As a workaround I reverted the commits e48677b and 8e2de8c from #1281. Now everything is fine again.

### How to reproduce the bug?

1. change settings regarding size of settings_window and window_position - or - start rssguard and resize windows
2. start rssguard (again)

### What was the expected result?

The settings in config.ini are always respected.

### What actually happened?

Size-settings in config.ini are ignored - rssguard starts always centered, not left-aligned as I would like it to be.

### Debug log

[.rssguard.log](https://github.com/martinrotter/rssguard/files/14606592/default.rssguard.log)

### Operating system and version

* OS: Arch Linux
* RSS Guard version: 4.6.4/4.6.5

**Comment by martinrotter** [comment]
Yes, I found a bug in the code. Thanks, fixing, releasing new version asap.
