### ISSUE TITLE
[FR]: Add Icon Symbol & is a DB file import possible?

### ISSUE THREAD

**Issue by Dean-Corso** [martinrotter/rssguard#1334]
### Brief description of the feature request

Hi again,

Q1: Could you please add the icon symbol showing in the article list? So I'm missing it and I have a lot things I can enable to show from ID till Label etc but I can not let display the feed icon. That's bad. Lets say you have a feeds folder with many different feeds of different websites and if you select that folder you get all feeds to see in the article list window but without the feed icon to recognize quickly where the feeds belong to. My suggestion, add to show / display the feed icon symbol too.

Q2: Is it possible to import all feed articles I have in QuiteRSS into RSS Guard? So the QuiteRSS tool does store all data into a feeds.db file and RSS Guard has a database.db file (SQLite format 3) so would it be possible to use my old database of QuiteRSS in RSS Guard anyhow? Just would like to have the same full feeds & content I have in QuiteRSS in RSS Guard you know. Maybe you can tell me whether its already possible to do that anyhow. Thanks.

**Comment by martinrotter** [comment]
Q1: Check settings my friend.

Q2: No, it is not possible to import right now, but could be if someone written the conversion script. I am quite busy with implementing other things for RSS Guard, but pull requests are always welcomed.

**Comment by Dean-Corso** [comment]
Hi,

where in settings and why? All other items I can see / choose in right mouse popup menu and there is the icon symbol missing. Look...
![A1_2024-03-15_212315](https://github.com/martinrotter/rssguard/assets/88513086/eda01f8d-ceab-4f66-82de-c4327125896c)
...as you can see there is no icon symbol to enable. Before the title I wanna have that feed icon to see quickly to which feed the article belongs. The same you also have in the feed list (feed icon & feed name) but in the article list I don't have it. Why?

Sounds bad about that its not working yet to import entire DB.

PS: Please stop locking my conversation [issues](https://github.com/martinrotter/rssguard/issues/1324) just because you don't like the way I speak. I'm speaking clear text. So it's OK if you don't like it but locking my started issue just because of THAT is really silly. Stop that! Thanks.

**Comment by Ac314** [comment]
> Q1: Could you please add the icon symbol showing in the article list? So I'm missing it and I have a lot things I can enable to show from ID till Label etc but I can not let display the feed icon. That's bad. Lets say you have a feeds folder with many different feeds of different websites and if you select that folder you get all feeds to see in the article list window but without the feed icon to recognize quickly where the feeds belong to. My suggestion, add to show / display the feed icon symbol too.

Look at Settings -> Feeds & articles -> Articles list -> Unread article icon type and set it to "feed icon". Is that what you need?

**Comment by Dean-Corso** [comment]
Hello @Ac314,

thank you trying to help but this is not what I'm looking for. I want to have the feed icon itself of any RSS feed like Youtube etc as symbol before the article title itself to see quickly to which feed the article belongs. On the image I have posted above you can see no feed icon what you can see in case of using QuiteRSS feed reader so there you can let display it or not but this popup entry is missing in RSS Guard and I don't know why because it's glass clear and logic to display also the feed icon itself in article list also in case you have a folder with mixed feeds inside. A Image is telling more than words. Also on the feed list and the left side every feed has a icon you can see quickly what feed it is but just not in the article list view so there it is missing. Just wonder why you can enable lots of other things (see popup image I did post above) nobody really needs to see there but the most important thing (feed icon) you can not set. Sorry, but somehow this is funny. 😃 Below a image from QuiteRSS to see what I mean...
![Q_2024-03-21_010047](https://github.com/martinrotter/rssguard/assets/88513086/ebc9a656-ee8f-4cca-a505-2013538f31b5)
...so there you can enable the Symbol (feed icon) for every article. Its much more helpfully to recognize the article / feed when I have stored many different in same folder.

**Comment by Ac314** [comment]
> I want to have the feed icon itself of any RSS feed like Youtube etc as symbol before the article title itself to see quickly to which feed the article belongs.

Feed icon will be displayed in "Read" column in articles list. Just make this column visible and set the option from my previous message to "feed icon". That will do the trick.

**Comment by Dean-Corso** [comment]
Ahhh, now I see it. 😃 Just thought the green dot is just displaying the read / no read status. Now I can see the feed icon there as I wanted to have. Thank you.

Maybe you can help with [this question I had](https://github.com/martinrotter/rssguard/issues/1322)? So I don't see / find any setting for the requests. Do you?
