### ISSUE TITLE
[BUG]: Window position and size not respected on app restart [4.6.4, 4.6.5 and 4.6.6; macOS]

### ISSUE THREAD

**Issue by lollyP** [martinrotter/rssguard#1335]
### Brief description of the issue

On subsequent restarts of RSS Guard, the window grows taller, first in the downward direction then pushing the window up to the menu bar, such that the window takes the entire vertical dimension of the screen.

I had hoped this was related to [issue  #1333](https://github.com/martinrotter/rssguard/issues/1333), as it began in v4.6.4. However, the issue remains in 4.6.6.

Thanks for the great app.

### How to reproduce the bug?

1. Start RSS Guard following a clean install of the app
2. Note window position and size
3. Close and restart the app
4. Note window position and size; window will have increased in size in the downward vertical direction, in the first instance

### What was the expected result?

Window size and position remain fixed between app restarts

### What actually happened?

Window size and position did not remain fixed between app restarts

### Debug log

None

### Operating system and version

* OS: macOS 14.4 (Sonoma)
* RSS Guard version: 4.6.6

**Comment by martinrotter** [comment]
I was not able to reproduce, for me the window size stays the same as when app closed.

**Comment by martinrotter** [comment]
test latest development build once it compiles pls

**Comment by lollyP** [comment]
The issue is fixed in the development build - thank you.
