### ISSUE TITLE
[BUG]: or FEATURE?  4.6.6 always starts settings-window with fixed size - resizing is not remembered

### ISSUE THREAD

**Issue by mohafri** [martinrotter/rssguard#1336]
### Brief description of the issue

For me #1333 is only partially solved: size of main-window is ok now, but not the size of the settings-window (I also cannot reproduce the bug described in #1335).

My settings in config.ini:
settings_window_size=@SiZe(1008 474) - the window is too narrow with 4.6.6.
Resizing is ignored with next start of rssguard or close and reopen of the settings-window.
Reverting only the lines with 'SettingsWindowInitialSize' in commit e48677b solved the issue for me:
src/librssguard/gui/dialogs/formsettings.cpp:
  62 +   resize(qApp->settings()->value(GROUP(GUI), GUI::SettingsWindowInitialSize, size()).toSize());
125 +   qApp->settings()->setValue(GROUP(GUI), GUI::SettingsWindowInitialSize, size());
src/librssguard/miscellaneous/settings.cpp:
281 + DKEY GUI::SettingsWindowInitialSize = "settings_window_size";
295 + KEY SettingsWindowInitialSize;

### How to reproduce the bug?

1. change settings regarding size of settings_window
2. or resize settings-window, close the window and reopen
3. restart rssguard 

### What was the expected result?

Manually changed size of settings-window is not reset.

### What actually happened?

rssguard always starts the settings-window with fixed size.

### Debug log

none

### Operating system and version

* OS: Arch Linux 64-bit - xfce4-desktop
* RSS Guard version: 4.6.6

**Comment by martinrotter** [comment]
Hopefully fixed. please test via devbuild.

Now the solution is universal and it remembers size for all dialogs inside RSS Guard! As for dialogs' positions - I much prefer to have all modal dialogs display on the center of its parent main window or on the center of the "screen" if the dialog is just too big. This was fixed too.

Pls test and let me know.

**Comment by mohafri** [comment]
Tested with current development build.

Everything is now working perfectly!

> As for dialogs' positions - I much prefer to have all modal dialogs display on the center of its parent main window or on the center of the "screen" ...> 

That is also fine for me.

Thanks again for the quick fix and your great program!
