### ISSUE TITLE
macOS dev Builds are not updated anymore

### ISSUE THREAD

**Issue by peperjohnny** [martinrotter/rssguard#135]
Unfortunately your macOS dev Builds are not updated anymore. Do you have some pointers how to build the packages myself?

**Comment by martinrotter** [comment]
This is error, they should be updated. Let me check.

**Comment by martinrotter** [comment]
Moreover, you can find instructions in rssguard.pro file and [here](https://github.com/martinrotter/rssguard/blob/master/resources/scripts/.travis-install-osx.sh). But I will investigate why Travis CI is not updating wiki with new dev links.

**Comment by martinrotter** [comment]
I potentially fixed the issue - the build for macos contained an [error](https://travis-ci.org/martinrotter/rssguard/jobs/272758943#L3121) which should be fixed in laster master. I will wait for build to finish and let you know.

Btw, thx for donation.

**Comment by peperjohnny** [comment]
No, thank you for this great software!
I will try to build myself as well, maybe I can help you with some reports afterwards.
Thank you for the info.

**Comment by martinrotter** [comment]
Should work now.
https://transfer.sh/SiU1R/RSS-Guard.dmg

**Comment by martinrotter** [comment]
Okay, glad to hear. :) Any help is always welcomed.
