### ISSUE TITLE
[BUG-Maybe]: How to clean up the download tab window (Clean Button Keeps grayed)?

### ISSUE THREAD

**Issue by Dean-Corso** [martinrotter/rssguard#1350]
### Brief description of the feature request

Just have a problem with the download tab. The clean up / Bereingen button is grayed even when I have selected all listed files in this download tab. Seems to be a bug. The files are no more there on HDD so I can not open them or open the download folder path etc. Maybe that's the reason why the clean up keeps grayed. How to fix it to clear the download list? Thanks.

**Comment by martinrotter** [comment]
Yes, there was bug, should be fixed.

**Comment by Dean-Corso** [comment]
> Yes, there was bug, should be fixed.

Not fixed in latest version 4.6.6 and downloads are still there and I can't remove them from the list. Clean button is still disabled. Why? Even when the files are there I can run them / open folder path (these 2 buttons are working when file is there) but also in this case the clean button is still disabled. I just can't remove / clean the download window. Only thing what works is to remove the entry's of downloads from config.ini file then all is gone from the list after restart. So what does your app check to keep the clean button below disabled all the time? You don't need to disable that button so just keep it enabled and when the user does click on it then just remove the selected files from that list if anything is selected etc. Why making it so laborious at moment?
