### ISSUE TITLE
[FR]: Support using the Qt style as defined by the system

### ISSUE THREAD

**Issue by guihkx** [martinrotter/rssguard#1352]
### Brief description of the feature request

On Linux distributions based on KDE Plasma, a Qt style named Breeze is used by default.

Despite of that, on a fresh RSS Guard installation, the Qt style seems hardcoded to Fusion.

It'd be cool to introduce an option to use the system style instead, similar to what is done with the icon theme:

![image](https://github.com/martinrotter/rssguard/assets/626206/9c2c0199-1c3e-4196-bed1-0dc7d93e05a4)

**Comment by guihkx** [comment]
I played around trying to implement this, but since I have no GUI expertise it'd be tricky for me to implement something actually useful.

I was able to access the name of system style with `qApp->style()->objectName()` (tested only on Qt 5.15 and Linux). On Plasma 6, that method returns `breeze`.

**Comment by martinrotter** [comment]
I will test with some KDE-based VM.

**Comment by martinrotter** [comment]
Building right now. Now default style should default to system style, also added "system style" explicit item to settings. Feel free to test.

**Comment by martinrotter** [comment]
Make sure to remove proper key from settings to test "vanilla" default.

**Comment by martinrotter** [comment]
![image](https://github.com/martinrotter/rssguard/assets/1255302/9c894307-ba73-4202-a863-8f7c1c95ffa6)

**Comment by guihkx** [comment]
Just tested it, works perfectly. Thank you very much once again!
