### ISSUE TITLE
[BUG]: Can't fetch normally, as a non-administrator, using a built-in browser

### ISSUE THREAD

**Issue by DawEdhel** [martinrotter/rssguard#1354]
### Brief description of the issue

As a continuation to [this discussion](https://github.com/martinrotter/rssguard/discussions/1313), I've updated the app to the stable release to utilize the built-in browser feature. Unfortunately, upon fetching a feed it returned "Status: error (Cannot open file 'a.html' for writting.)".

It looked like a permission issue, so I restarted the app as an administrator, and the same fetching went successfully.

### How to reproduce the bug?

1. Use built-in browser as a source.

### What was the expected result?

Successful fetching.

### What actually happened?

Unsuccessful fetching with a "Status: error (Cannot open file 'a.html' for writting.)"

### Debug log

time="    77.484" type="warning" -> javascript: scroll (source: :31)
time="    80.669" type="debug" -> core: Delaying scheduled feed auto-downloads and message state synchronization for some time due to another running update.
time="    82.974" type="warning" -> javascript: iiddllee (source: :34)
time="    82.994" type="warning" -> QObject::~QObject: Timers cannot be stopped from another thread
time="    82.994" type="warning" -> QObject::killTimer: Timers cannot be stopped from another thread
time="    82.999" type="critical" -> network: Unknown error when fetching feed:message: 'Cannot open file 'a.html' for writting.'.
time="    82.999" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 1/1 (id of feed is ...).
time="    83.006" type="debug" -> feed-downloader: Finished feed updates in thread '...'.

### Operating system and version

* OS: Win10
* RSS Guard version: 4.6.6-6cf2717ed

**Comment by martinrotter** [comment]
Yes, sorry, forgot to comment out debugging line. Fixed now.
