### ISSUE TITLE
[BUG]: Every time I start RSS Guard Lite I see this discover feeds pop-up window. 

### ISSUE THREAD

**Issue by omega3** [martinrotter/rssguard#1357]
### Brief description of the issue

Every time I start RSS Guard Lite I see this "discover feeds" pop-up window. 

Maybe it is not a bug. I don't know. But I don't see option to disable it.

The strange thing is that when I run it from terminal it doesn't happen. 

### How to reproduce the bug?

I don't know. I installed and added some RSS feeds. Then I switched to dark mode. That's all I did.

### What was the expected result?

Discover feeds pop-ups every app start.

### What actually happened?

No more pop-up.

### Debug log

firejail --seccomp --private=/home/user/Dane/backup/jail/ rssguard --log
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 31617, child pid 31618
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Child process initialized in 79.49 ms
time="     0.000" type="debug" -> core: Starting RSS Guard 4.6.3.
time="     0.000" type="debug" -> core: Current UTC date/time is 2024-03-25T13:32:17Z.
time="     0.014" type="critical" -> core: Missing value after '--log'.
time="     0.014" type="debug" -> core: Initializing settings in '/home/user/.config/RSS Guard 4/config/config.ini' (non-portable way).
time="     0.014" type="debug" -> core: Starting to load active localization. Desired localization is 'pl_PL'.
time="     0.015" type="debug" -> core: Application localization 'pl_PL' loaded successfully, specifically sublocalization 'pl' was loaded.
time="     0.016" type="debug" -> core: Qt localization 'pl' loaded successfully.
time="     0.027" type="debug" -> database: File-based SQLite database connection 'DatabaseFactory' to file '/home/user/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.027" type="debug" -> database: File-based SQLite database has version '7'.
time="     0.028" type="debug" -> gui: Available icon theme paths: QList(/home/user/.local/share/icons, /usr/local/share/icons, /usr/share/icons, :/icons, :/graphics, /home/user/.config/RSS Guard 4/icons, /usr/bin/icons)
time="     0.028" type="debug" -> gui: Installed icon themes are: '', 'hicolor', 'breeze_cursors', 'Oxygen_Zion', 'Oxygen_Yellow', 'Oxygen_White', 'Oxygen_Blue', 'Oxygen_Black', 'KDE_Classic', 'Breeze_Snow', 'oxygen', 'breeze', 'breeze-dark', 'Adwaita', 'default', 'HighContrast'
time="     0.028" type="debug" -> gui: Loading default system icon theme.
time="     0.028" type="debug" -> gui: Found path of base skin: ':/skins/nudus-base'.
time="     0.028" type="debug" -> gui: Base file ':/skins/nudus-base/html_wrapper.html' exists, using it for the skin.
time="     0.028" type="debug" -> gui: Local file ':/skins/nudus-light/lite_html_style.css' exists, using it for the skin.
time="     0.028" type="debug" -> gui: Base file ':/skins/nudus-base/lite_html_enclosure_image.html' exists, using it for the skin.
time="     0.028" type="debug" -> gui: Base file ':/skins/nudus-base/lite_html_single_message.html' exists, using it for the skin.
time="     0.028" type="debug" -> gui: Base file ':/skins/nudus-base/lite_html_enclosure_every.html' exists, using it for the skin.
time="     0.028" type="debug" -> gui: Local file ':/skins/nudus-light/qt_style.qss' exists, using it for the skin.
time="     0.028" type="debug" -> gui: Base file ':/skins/nudus-base/html_adblocked.html' exists, using it for the skin.
time="     0.028" type="debug" -> gui: OS defines color scheme: 'Qt::ColorScheme::Unknown'.
time="     0.028" type="debug" -> gui: Setting style: 'Fusion'.
time="     0.029" type="debug" -> gui: Skin 'nudus-light' loaded. Lite: 'true'.
time="     0.029" type="debug" -> network: Disabling application-wide proxy completely.
time="     0.029" type="debug" -> core: SQLite version: '3.44.2'.
time="     0.033" type="debug" -> core: OpenSSL version: 'OpenSSL 3.2.1 30 Jan 2024'.
time="     0.033" type="debug" -> core: OpenSSL supported: 'true'.
time="     0.033" type="debug" -> core: Global thread pool has 4 threads.
time="     0.033" type="debug" -> core: Setting locale for LC_NUMERIC to C as libmpv requires it.
time="     0.033" type="debug" -> core: Instantiated class  'Application'.
time="     0.035" type="debug" -> database: SQLite database connection 'MessagesModel' to file '/home/user/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.037" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, Feeds.is_rtl, CASE WHEN LENGTH(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Messages.labels LIKE "%." || Labels.custom_id || ".%") as msg_labels, Messages.labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1;'.
time="     0.037" type="debug" -> core: Auto-download timer started with interval 10000 ms.
time="     0.037" type="debug" -> core: Creating FeedDownloader singleton.
time="     0.054" type="debug" -> gui: Creating main application form in thread: '0x7f1038075000'.
time="     0.081" type="debug" -> gui: Current row changed - proxy 'QModelIndex(-1,-1,0x0,QObject(0x0))', source 'QModelIndex(-1,-1,0x0,QObject(0x0))'.
time="     0.087" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     0.087" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     0.087" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     0.132" type="debug" -> gui: Creating tray icon menu.
time="     0.176" type="debug" -> core: OS asked application to save its state.
time="     0.176" type="debug" -> CTRL is NOT pressed while sorting articles - sorting with standard mode.
time="     0.177" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, Feeds.is_rtl, CASE WHEN LENGTH(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Messages.labels LIKE "%." || Labels.custom_id || ".%") as msg_labels, Messages.labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1 ORDER BY Messages.date_created DESC;'.
time="     0.179" type="debug" -> core: Showing the main window when the application is starting.
time="     0.181" type="debug" -> database: SQLite database connection 'FeedReader' to file '/home/user/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.182" type="debug" -> database: SQLite database connection 'FeedlyEntryPoint' to file '/home/user/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.182" type="debug" -> database: SQLite database connection 'GmailEntryPoint' to file '/home/user/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.182" type="debug" -> database: SQLite database connection 'GreaderEntryPoint' to file '/home/user/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.182" type="debug" -> database: SQLite database connection 'OwnCloudServiceEntryPoint' to file '/home/user/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.182" type="debug" -> database: SQLite database connection 'StandardServiceEntryPoint' to file '/home/user/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.183" type="debug" -> database: SQLite database connection 'StandardServiceRoot' to file '/home/user/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.184" type="debug" -> core: Custom ID of feed when loading from DB is '1'.
time="     0.184" type="debug" -> core: Custom ID of feed when loading from DB is '2'.
time="     0.184" type="debug" -> core: Custom ID of feed when loading from DB is '3'.
time="     0.184" type="debug" -> core: Custom ID of feed when loading from DB is '4'.
time="     0.184" type="debug" -> database: SQLite database connection 'RecycleBin' to file '/home/user/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.185" type="debug" -> database: SQLite database connection 'ImportantNode' to file '/home/user/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.185" type="debug" -> database: SQLite database connection 'UnreadNode' to file '/home/user/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.185" type="debug" -> database: SQLite database connection 'LabelsNode' to file '/home/user/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.185" type="debug" -> database: SQLite connection 'StandardServiceRoot' is already active.
time="     0.185" type="debug" -> database: SQLite database connection 'StandardServiceRoot' to file '/home/user/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.186" type="debug" -> database: SQLite database connection 'TtRssServiceEntryPoint' to file '/home/user/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.186" type="debug" -> gui: Feed list item expanded - user (RSS/ATOM/JSON)
time="     0.186" type="debug" -> core: No execution message received from other app instances.
time="     1.796" type="debug" -> gui: Main window close event
time="     1.796" type="debug" -> gui: Main window hide event
time="     1.798" type="debug" -> core: Cleaning up resources and saving application state.
time="     1.798" type="debug" -> core: Close lock was obtained safely.
time="     1.799" type="debug" -> core: Stopping StandardServiceRoot instance.
time="     1.799" type="debug" -> feed-downloader: Destroying FeedDownloader instance.
time="     1.839" type="debug" -> gui: Destroying FormMain instance.
time="     1.839" type="debug" -> gui: Destroying TabWidget instance.
time="     1.839" type="debug" -> gui: Destroying FeedMessageViewer instance.
time="     1.840" type="debug" -> gui: Destroying BaseToolBar instance.
time="     1.841" type="debug" -> network: Destroying Downloader instance.
time="     1.841" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="     1.841" type="debug" -> network: Destroying Downloader instance.
time="     1.841" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="     1.841" type="debug" -> network: Destroying Downloader instance.
time="     1.841" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="     1.841" type="debug" -> gui: Destroying MessagesView instance.
time="     1.841" type="debug" -> gui: Destroying BaseToolBar instance.
time="     1.842" type="debug" -> gui: Destroying FeedsView instance.
time="     1.842" type="debug" -> gui: Destroying TabBar instance.
time="     1.843" type="debug" -> gui: Destroying StatusBar instance.
time="     1.848" type="debug" -> core: Destroying Application instance.
time="     1.848" type="debug" -> core: Destroying Mutex instance.
time="     1.849" type="debug" -> gui: Destroying IconFactory instance.
time="     1.849" type="debug" -> core: Destroying FeedReader instance.
time="     1.849" type="debug" -> feed-model: Destroying FeedsModel instance.
time="     1.850" type="debug" -> feed-model: Destroying FeedsProxyModel instance
time="     1.850" type="debug" -> message-model: Destroying MessagesModel instance.
time="     1.850" type="debug" -> message-model: Destroying MessagesProxyModel instance.

Parent is shutting down, bye...

### Operating system and version

* RSS Guard version: RSS Guard Lite 4.6.3 

Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.11
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.12
Kernel Version: 6.6.19-1-MANJARO (64-bit)
Graphics Platform: X11

**Comment by martinrotter** [comment]
You are using empty "--log" CLI argument which is wrong. See RSS Guard "--help" to know how to use those parameters correctly.
