### ISSUE TITLE
Feature Request: Ability to launch external program with URL as an argument

### ISSUE THREAD

**Issue by forfund** [martinrotter/rssguard#136]
I think it would be very handy to click on a message and do something with its url (use youtube-dl with it for example) without the need to manually copy url.

Opening URLs in custom external browser works exactly like what I'm talking about, but I think there should be another context menu choice specifically for external tools.

**Comment by martinrotter** [comment]
Do you want to be able to add arbitrary number of external tools? Or just one could be enough?

**Comment by martinrotter** [comment]
Fixed in newest master. Go to wiki and test this feature in newest development build, please.

**Comment by forfund** [comment]
It works! Ability to add executable parameters would be a cherry on top.

**Comment by martinrotter** [comment]
> It works! Ability to add executable parameters would be a cherry on top.

Would you use it?

**Comment by forfund** [comment]
> Would you use it?

You mean the parameters? I would.

**Comment by martinrotter** [comment]
OK, will try to enhance

**Comment by martinrotter** [comment]
Added support for parameters, make sure to remove current tools and add them again, to avoid some bugs.

https://github.com/martinrotter/rssguard/commit/5b97260104a1e3c1b431baa33367db4a7a0740fc

Let me know how it went.

**Comment by forfund** [comment]
The parameters are saved correctly and they do work, but only the first one is shown in the settings menu after opening it again.

**Comment by martinrotter** [comment]
OK, let me check.

**Comment by martinrotter** [comment]
Should be fixed.

**Comment by forfund** [comment]
It is. Thank you.
