### ISSUE TITLE
[BUG]: Procedure entry point SystemParametrsinfoForDpi could not be found

### ISSUE THREAD

**Issue by premolirrob** [martinrotter/rssguard#1364]
### Brief description of the issue

When launching the program (both in the portable version and after installation) the error appears: The entry point SystemParametrsinfoForDpi of the procedure could not be found in the dynamic link library .....\Qt6Gui.dll

### How to reproduce the bug?

launching the program (both in the portable version and after installation)

### What was the expected result?

opening of the program

### What actually happened?

dialog box containing the above error

### Debug log

The entry point SystemParametrsinfoForDpi of the procedure could not be found in the dynamic link library .....\Qt6Gui.dll

### Operating system and version

* OS: Windows 10 
* RSS Guard version:  4.6.6 (both portable and installable version)

**Comment by martinrotter** [comment]
Is your Windows 10 up to date?

**Comment by premolirrob** [comment]
I'm sorry, you're right, due to my particular needs I didn't update to the latest version of Windows 10. I thought it was a problem that could be solved even if I didn't update. I apologize

**Comment by martinrotter** [comment]
No problem, that particular function is known to be present only from Windows 10 1607 version so fully updated system usually solves it.
