### ISSUE TITLE
[BUG]: “Unknown file format” when playing podcast

### ISSUE THREAD

**Issue by Jiang10086** [martinrotter/rssguard#1366]
### Brief description of the issue

I installed the app today and didn't change anything(every setting keeps default), and when I try to play a podcast named “字谈字畅” it shows an error message saying “Unknown file format”, but the same podcast plays fine on Apple Podcast.

### How to reproduce the bug?

1. Add the [podcast feed](https://www.thetype.com/typechat/feed/).
2. Click the title of a episode of the podcast.
3. Click the triangle icon to start playing [the audio file](https://static.thetype.cloud/typechat/typechat226.mp3).

### What was the expected result?

The audio file plays well with the familiar mpv GUI.

### What actually happened?

Can't playing podcast at all.

### Debug log

I follow [the instruction](https://rssguard.readthedocs.io/en/stable/contrib/bugs.html#reporting-bugs-or-feature-requests) to start RSS Guard but it didn't creat an log file, when I check the log in the app, it's empty.

### Operating system and version

* OS: Windows 11 22H2
* RSS Guard version: 4.6.6（ti is the install version not the portable one, it is the full version not the lite one）

**Comment by martinrotter** [comment]
Tested on Windows.

![rssguard_fuZp8XPOmB](https://github.com/martinrotter/rssguard/assets/1255302/05d61957-5d9e-44de-8b49-da41ba65aeda)

The audio file plays fine.

1. Open rssguad.
2. Open Application log dialog (will be empty).
3. Try to play the audio file (log dialog will fill with text)
4. Copy/paste text here.

**Comment by Jiang10086** [comment]
I did what you said, and logs shows that:
```
time="    27.165" type="debug" -> gui: Message list got focus with reason 'Qt::MouseFocusReason'.
time="    27.166" type="debug" -> gui: Current row changed - proxy 'QModelIndex(0,6,0x2c30fe6a030,MessagesProxyModel(0x2c309982fa0, name = MessagesProxyModel))', source 'QModelIndex(0,6,0x0,MessagesModel(0x2c306a3c4e0))'.
time="    27.210" type="debug" -> gui: HTML image resizing took 0 miliseconds.
time="    27.327" type="debug" -> gui: Hovered link: 'QUrl()'.
time="    37.933" type="debug" -> gui: Message list got focus with reason 'Qt::ActiveWindowFocusReason'.
time="    38.306" type="debug" -> gui: Hovered link: 'QUrl(https://mp.weixin.qq.com/s/jL2zVUpV4yBKBkTTFhAUAw)'.
time="    38.332" type="debug" -> gui: Hovered link: 'QUrl(https://chromestatus.com/feature/5170044014690304)'.
time="    38.348" type="debug" -> gui: Hovered link: 'QUrl()'.
time="    40.588" type="debug" -> libmpv: Configuration file 'mpv.conf' already exists.
time="    40.588" type="debug" -> libmpv: Configuration file 'input.conf' already exists.
time="    40.630" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="    47.371" type="debug" -> core: Saved data with auto-saver for 'CookieJar' and method 'saveCookies'.
```
I am not a developer and I didn't know what's wrong.
