### ISSUE TITLE
[Wiki] Distribution information

### ISSUE THREAD

**Issue by vatterspun** [martinrotter/rssguard#137]
#### Brief description of the issue.

Just a request to add something to the Wiki and/or Releases page explaining the difference between between the following files:

rssguard-3.4.2-7bad9d1-nowebengine-win32.7z
rssguard-3.4.2-7bad9d1-win32.7z
rssguard-3.4.2-95ee6be-nowebengine-win32.exe
rssguard-3.4.2-95ee6be-win32.exe 

What is "nowebengine"?  What is 95ee6be vs. 7bad9d1?

Thanks.

**Comment by martinrotter** [comment]
https://github.com/martinrotter/rssguard/wiki/Download-file-naming

**Comment by vatterspun** [comment]
Ah, i missed that in the "Downloads & builds" box on the right.  Nvmnd.

**Comment by vatterspun** [comment]
Could you add something on that page explaining what nowebengine means?
