### ISSUE TITLE
[BUG]: Freezes after QT update (Wayland)

### ISSUE THREAD

**Issue by Co3co** [martinrotter/rssguard#1370]
### Brief description of the issue

Client is frozen after the recent QT updates for Arch Linux.

### How to reproduce the bug?

1. Run `rssguard`

### What was the expected result?

Client is responsive

### What actually happened?

Client is unresponsive and cannot be killed with SIGTERM.

### Debug log

[rssguard.log](https://github.com/martinrotter/rssguard/files/14895538/rssguard.log)

### Operating system and version

OS: Artix Linux
Compositor: Hyprland
RSS Guard version: 4.6.6-1
QT Packages:
```
qt4 4.8.7-35
qt5-base 5.15.13+kde+r142-1
qt5-charts 5.15.13-1
qt5-declarative 5.15.13+kde+r30-1
qt5-doc 5.15.13-1.1
qt5-graphicaleffects 5.15.13-1
qt5-location 5.15.13+kde+r6-1
qt5-multimedia 5.15.13+kde+r2-1
qt5-networkauth 5.15.13-1
qt5-quickcontrols 5.15.13-1
qt5-quickcontrols2 5.15.13+kde+r5-1
qt5-sensors 5.15.13-1
qt5-speech 5.15.13+kde+r1-1
qt5-styleplugins 5.0.0.20170311-41
qt5-svg 5.15.13+kde+r6-1
qt5-tools 5.15.13+kde+r4-1
qt5-translations 5.15.13-1
qt5-wayland 5.15.13+kde+r60-1
qt5-webchannel 5.15.13+kde+r3-1
qt5-webengine 5.15.16-6
qt5-webkit-git 5.212.0.alpha4.r13.gac8ebc6c3-2
qt5-x11extras 5.15.13-1
qt5-xmlpatterns 5.15.13-1
qt5ct 1.8-1
qt5pas 1:1.2.15-1
qt6-5compat 6.6.3-1
qt6-base 6.6.3-1
qt6-declarative 6.6.3-1
qt6-httpserver 6.6.3-1
qt6-imageformats 6.6.3-1
qt6-multimedia 6.6.3-1
qt6-multimedia-ffmpeg 6.6.3-1
qt6-networkauth 6.6.3-1
qt6-positioning 6.6.3-1
qt6-sensors 6.6.3-1
qt6-shadertools 6.6.3-1
qt6-speech 6.6.3-1
qt6-svg 6.6.3-1
qt6-tools 6.6.3-1
qt6-translations 6.6.3-1
qt6-virtualkeyboard 6.6.3-1
qt6-wayland 6.6.3-1
qt6-webchannel 6.6.3-1
qt6-webengine 6.6.3-1
qt6-websockets 6.6.3-1
qtwebkit 2.3.4-9
```

**Comment by martinrotter** [comment]
I will test tonight on my home machine.

**Comment by martinrotter** [comment]
Tested with Arch/KDE via xorg session and I do not see any problems. Cannot test directly with wayland as my setup does not allow for wayland.

**Comment by Co3co** [comment]
The issue is wayland only for me. Just tested on X11 and it works perfectly fine.
Is there anything I can do to help get to the bottom of this issue?

**Comment by martinrotter** [comment]
Possibly related to: https://github.com/flathub/io.github.martinrotter.rssguardlite/issues/41#issuecomment-2051081035 ?

I myself do not use Wayland at all,

**Comment by Co3co** [comment]
The window is fully visible for me, but I suppose it's possible that it's because Hyprland handles the window drawing differently.
Also, I'm not on the flathub version. I use `rssguard` from the Arch repos.

**Comment by Co3co** [comment]
Not sure what happened, but it is fixed now. I'm guessing an update to some dependency fixed it.
