### ISSUE TITLE
[FR]: avoid http 429, when too many feeds from same site.

### ISSUE THREAD

**Issue by bhunji2** [martinrotter/rssguard#1375]
### Brief description of the feature request

situation:
Account(RSS/ATOM/JSON)
I subscribe to a forum's RSS
Currently subscribed Topics exceed 169 different URLs
The forum server will return http 429 Too Many Requests

suggestion:
Please add the option to customize the interval between update for same site
Thanks

**Comment by martinrotter** [comment]
Can you give a list of feed URLs from same host/website for me to test?

**Comment by martinrotter** [comment]
Well, i have to find something myself because blind implementing the feature would be difficult.

**Comment by Ac314** [comment]
This is kind of duplicate of #1322 (see conversation there).
