### ISSUE TITLE
[BUG]: RSS Guard not Fetching Reddit NSFW search query for posts aka link

### ISSUE THREAD

**Issue by l5oukz89** [martinrotter/rssguard#1379]
### Brief description of the issue

doesn't fetch posts related to the search query.

even if i input my credentials in the setting of this feed.

(url of search query work well in feedbro chrome extension, so url is legit and written correctly.)

### How to reproduce the bug?

N/A

### What was the expected result?

fetching posts.

### What actually happened?

not fetching posts.

### Debug log

time="  2842.836" type="debug" -> feed-downloader: Starting feed updates from worker in thread '0x7fb1db8b76c0'.
time="  2842.836" type="debug" -> feed-downloader: All caches synchronized.
time="  2842.836" type="debug" -> database: SQLite connection 'db_connection_140401869289152' is already active.
time="  2842.836" type="debug" -> database: SQLite database connection 'db_connection_140401869289152' to file '/home/karim/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="  2842.836" type="debug" -> feed-downloader: Downloading new messages for feed ID '12464' URL: 'https://www.reddit.com/search/.xml?q=title%3A(apple)+self%3Atrue+nsfw%3Ayes&type=link&cId=c7562f6a-aac0-4f11-97f5-1950c3cee7a2&iId=5fe9374a-0b68-4fe6-aa07-25c5931eac42&sort=new&t=all.rss' title: 'reddit.com: search results - title:(apple) self:true nsfw:yes' in thread  '140400383743680'.
time="  2842.837" type="debug" -> database: SQLite database connection 'db_connection_140400383743680' to file '/home/karim/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="  2842.837" type="debug" -> core: Downloading URL 'https://www.reddit.com/search/.xml?q=title%3A(apple)+self%3Atrue+nsfw%3Ayes&type=link&cId=c7562f6a-aac0-4f11-97f5-1950c3cee7a2&iId=5fe9374a-0b68-4fe6-aa07-25c5931eac42&sort=new&t=all.rss' to obtain feed data.
time="  2842.837" type="warning" -> network: Using application-wide proxy.
time="  2842.837" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="  2843.128" type="debug" -> network: Destroying Downloader instance.
time="  2843.128" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="  2843.128" type="debug" -> feed-downloader: Downloaded 0 messages for feed ID '12464',operation took 291976 microseconds.
time="  2843.128" type="debug" -> database: SQLite connection 'db_connection_140400383743680' is already active.
time="  2843.128" type="debug" -> database: SQLite database connection 'db_connection_140400383743680' to file '/home/karim/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="  2843.129" type="debug" -> No messages to be updated/added in DB for feed '12464'.
time="  2843.129" type="debug" -> feed-downloader: Updating messages in DB took 221 microseconds.
time="  2843.129" type="debug" -> feed-downloader: 0 unread messages and 0 total messages for feed '12464' stored in DB.
time="  2843.129" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 1/1 (id of feed is 12464).
time="  2843.131" type="debug" -> feed-downloader: Finished feed updates in thread '0x7fb1db8b76c0'.
time="  2843.140" type="debug" -> CTRL is NOT pressed while sorting articles - sorting with standard mode.
time="  2843.144" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, Feeds.is_rtl, CASE WHEN LENGTH(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Messages.labels LIKE "%." || Labels.custom_id || ".%") as msg_labels, Messages.labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE Feeds.custom_id IN ('12464') AND Messages.is_deleted = 0 AND Messages.is_pdeleted = 0 AND Messages.account_id = 1 ORDER BY Messages.date_created DESC;'.
time="  2843.144" type="debug" -> gui: Reloading of msg selections took 4 miliseconds.

### Operating system and version

* OS: Linux Mint 21.3 Virginia / Ubuntu 22.04 jammy.
* RSS Guard version:  4.6.6 (flatpak / flathub)

**Comment by martinrotter** [comment]
In RSS Guard if your feed is hidden behind log-in (via cookies) you have to login to the site first.

1. Open new browser tab in RSS Guard -> enter reddit.com and loging with your credentials.
2. Fetch your feed. Articles will be there.
3. RSS Guard automatically remembers cookies saved in its embedded web browser and automatically uses them when fetching feeds.

Proof when logged-in:
![image](https://github.com/martinrotter/rssguard/assets/1255302/4932fa78-1c94-4709-8e8c-76fe18fddab1)

**Comment by l5oukz89** [comment]
Thank you the issue was definitely resolved ! many thanks !

**Comment by l5oukz89** [comment]
(i would also like to request a manual button for marking articles as read, just like feedbro)

**Comment by martinrotter** [comment]
there is button to mark articles read or unread, it can be added to article or feed toolbar, settings-> user interface -> toolbars
