### ISSUE TITLE
Please support Chinese

### ISSUE THREAD

**Issue by Hunlongyu** [martinrotter/rssguard#138]
#### Brief description of the issue.

Please support Chinese

#### How to reproduce the bug?

1. 
2. 
3.

**Comment by martinrotter** [comment]
I do not speak Chinese. 

https://github.com/martinrotter/rssguard/wiki#localizations

**Comment by martinrotter** [comment]
I added Chinese localization section for you, you can create account (free) in transifex and start translating.

https://www.transifex.com/martinrotter/rssguard/language/zh/
