### ISSUE TITLE
[FR]: Set custom notification sound for filter, New icon design, Non-account feed, Tray icon notification option

### ISSUE THREAD

**Issue by himurajutsu** [martinrotter/rssguard#1388]
### Brief description of the feature request

Hello, The app is very nice. It would be great if the following features were added. Of course, this is my opinion. Your opinion is important too. Thanks.

1- Set custom notification sound for feed or article filter.
2- Square icon for app. The default icon scaling does not look nice.
3- Adding categories and feeds without an account.
4- Tray icon notification "number of new news" option. (Waking the program should be enough to clear the notification count)

**Comment by martinrotter** [comment]
Hi @himurajutsu.

You broke one of core bug report rules. Always create SEPARATE reports for each individual feature or bug observed or requested.
