### ISSUE TITLE
Layout changing issue in DEV version 3.4.3 (2464df5)

### ISSUE THREAD

**Issue by groentebroer** [martinrotter/rssguard#139]
#### Brief description of the issue.

Selecting a message opens the part of the interface that shows the contents of the message.
Resulting in the interface duplicating a little.
(See screenshot).
The mouse pointer, also moves about the same amount, resulting in the need to click a little above something to select it.

#### How to reproduce the bug?

1. Select a message with the reading pane in the lower part. (Left the feeds, right the titles of the items right bottom, the item content.)
2. 
3. 

#### What is the expected result?

The interface should not be duplicated

#### What actually happened?

See description

#### Other information (logs, see Wiki)

Windows 64bit installation
Development version 3.4.3 (2464df5)
I had it sometimes in the older version as well, but then I was not able to reproduce it.
Now I can ;-).

See the "double" header bar.

![2017-09-11 15_58_30-rss guard 3 4 3](https://user-images.githubusercontent.com/1811817/30279296-1bb972bc-970d-11e7-854b-aa3f9c9a746e.png)

Note the highlighed refresh icon when hovering above it instead of on it.

![2017-09-11 16_25_04-rss guard 3 4 3](https://user-images.githubusercontent.com/1811817/30279562-df235b50-970d-11e7-94fb-4dae765ca949.png)

**Comment by groentebroer** [comment]
It seems to be related to an external display / zoom level thing in Windows. As I restarted RSS Guard without external display and are not able to reproduce the issue now.

**Comment by martinrotter** [comment]
Yes, these kind of issues are very well described in Qt Bugs page and are reported like gazillion times. They are fighting with it, but it is very complex stuff.

Indeed, Qt libraries have troubles when zoom level/DPI stuff is changed in Windows on-the-fly over the application lifetime. It is actually their recommended solution to restart application/pc.

https://bugreports.qt.io/browse/QTBUG-55654?jql=text%20~%20%22dpi%22

So this is very likely upstream bug. I really do not know how to handle this in RSS Guard explicitly, sorry. :)
