### ISSUE TITLE
[EN]: Button for mark all as read in a feed

### ISSUE THREAD

**Issue by gnumanx** [martinrotter/rssguard#1393]
### Brief description of the feature request

Thank you very much for this fantastic, fully-equipped application!

I am using it for a month now, I enjoyed personalizing the toolbars and other aspects.

But I find it difficult to set a button to mark all the articles in a feed as read. There is one to mark all the feeds in the app as read, but not one for the current feed.

Am I wrong? Would you happen to have any suggestions?

**Comment by martinrotter** [comment]
There already is such a button in feed context menu,  also the same button is in "Feeds" main menu as "Mark selected item as read" and this very same button/action can be added both to feed and article list toolbars via settings -> gui -> toolbars.

**Comment by gnumanx** [comment]
You are right! Sorry, I thought I already tried all the options.
Thank you again for you kind support!
