### ISSUE TITLE
[BUG]: problem with high dpi on 4.6 version, with 4.5 - everything is perfect. 

### ISSUE THREAD

**Issue by anthonyanikos** [martinrotter/rssguard#1395]
### Brief description of the issue

[BUG]: problem with high dpi on 4.6 version, with 4.5 - everything is perfect

### How to reproduce the bug?

Just run 4.6 and 4.5 for comparation.

### What was the expected result?

Same perect interface as it was in 4.5

### What actually happened?

Blurry interface, as it happening without check "high dpi settings by application" in shortcut ;(
Thank u a lot for you greate reader!

### Debug log

can't

### Operating system and version

* OS:
* RSS Guard version:
Windows
4.6

**Comment by anthonyanikos** [comment]
As i think, its QT5->QT6 changing... i have reproduced it even at same version - i have 4.3, but my 4.3 have QT5,  but current 4.3 - have already QT6

**Comment by anthonyanikos** [comment]
i am not specialist, sorry, but may be its look like
https://bugreports.qt.io/browse/QTBUG-103488

**Comment by martinrotter** [comment]
OK, I added a semi-fix for this: 7e50de286

Now, you can set "QT_ENABLE_HIGHDPI_SCALING" env. variable to your liked value "0" in Windows OS settings, then launch RSS Guard. It will respect this system setting and should look better for your use case.

Wait for development build to compile and test and let me know.

**Comment by anthonyanikos** [comment]
Thank u very mouch!!! With QT_ENABLE_HIGHDPI_SCALING=0 works perfect!!

with respect, Anthony.

P.S. Thank u for you reader!
