### ISSUE TITLE
[BUG]: Help Creating a very simple basic yet solid Filter when downloading new articles

### ISSUE THREAD

**Issue by l5oukz89** [martinrotter/rssguard#1398]
### Brief description of the issue

// This filter accepts messages whose (title OR content) is on the whitelist AND rejects those whose (title OR content) is on blacklist.
// This filter counts number of characters of the message content and append the title with the length. 
// this filter prefixes title with the matched word or words(up to 3 words).
// This filter purges duplicates.
// This filter purges messages that were rejected.

{includes method versus whitelist.some(i => msg.title.indexOf(i) != -1) method ?}

var or const ? whitelist = ['X', 'Y', 'Z'];
var or const ? blacklist = ['A', 'B', 'C'];

so title should be something like [Length of message content] (mandatory in all cases) + [matched word 1] (mandatory) + [matched word 2] (optional) + [matched word 3] (optional) + [original title] (mandatory)

### How to reproduce the bug?

N/A

### What was the expected result?

N/A

### What actually happened?

N/A

### Debug log

N/A

### Operating system and version

* OS: Linux Mint Cinnamon 21.3
* RSS Guard version: 4.6.6

**Comment by martinrotter** [comment]
Create a discussion for these types of requests, not a bug report. Thank you.

**Comment by l5oukz89** [comment]
okay, thank you.
