### ISSUE TITLE
[FR]: Allow fetching feeds with Blank line before XML declaration

### ISSUE THREAD

**Issue by DraconicNEO** [martinrotter/rssguard#1403]
### Brief description of the feature request

A common problem in many RSS feeds is a [blank line before XML Declaration](https://validator.w3.org/feed/docs/error/WPBlankLine.html). Many feed readers are able to overcome this error and still display the feed. I think we should add the ability to read feeds that have this error in them as it is very common and doesn't really affect the data.

**Comment by martinrotter** [comment]
Please give URL to such a feed.

**Comment by DraconicNEO** [comment]
> Please give URL to such a feed.

TheHardTimes' feed:
https://thehardtimes.net/feed/

**Comment by ScoobyDone** [comment]
https://blog.synology.com/feed - 1 blank line
https://georgerrmartin.com/notablog/feed - 2 blank lines

**Comment by martinrotter** [comment]
Fixed.
