### ISSUE TITLE
FR: Option to prevent opening the internal browser for selected entries

### ISSUE THREAD

**Issue by danowar2k** [martinrotter/rssguard#141]
#### Brief description of the issue.

Just a feature request. At the moment, when you select a feed article, the internal browser is opened at once to display the article. Could you add an option so that you can disable this function? So that it only opens on a keypress or double-click or whatever.

**Comment by martinrotter** [comment]
Why would you want this feature? I do not get it. Is displaying of messages slow? Why exactly would anyone want this?

**Comment by danowar2k** [comment]
Hm, maybe I'm alone with this. The internal browser seems really fast. It's just that when I don't use a function (the internal browser) I'd like to disable it to prevent unnecessary data download or CPU load.

But I guess I could always minify the internal browser window so that I'll probably forget about that. *shrugs*

**Comment by martinrotter** [comment]
I guess I can add some action to "Messages" menu, something like "Disable internal message preview", which could be binded to keyboard shortct, so that you could easily turn this feature on/off. Once disabled, no internal web viewer would be shown when cycling amongst messages.

What you think?

**Comment by danowar2k** [comment]
That would be an absolutely sufficient implementation for what I'm thinking about. *thumbsUp*

**Comment by martinrotter** [comment]
Test this once commit https://github.com/martinrotter/rssguard/commit/f6ed84b4c3f7a39fe3c8a520a32f8e455cb2cbec or newer commit gets compiled and let me know.
