### ISSUE TITLE
[BUG]: Behavior when reading an article when "show unread articles" is on

### ISSUE THREAD

**Issue by aubreyz** [martinrotter/rssguard#1415]
### Brief description of the issue

A minor bug. If you are reading an article while "show unread articles" is on
- The read flag is turned to "not unread" while you are reading - which is fine
- However if while reading the feed updates, the article is removed from view in the middle of reading (as a list update is forced) and is impossible to find again if the list is large

### How to reproduce the bug?

1. Set "show unread articles"
2. Read one as yet unread article in the split pane
3. Have settings such that the feed is updated while reading the article
4. See what happens 

### What was the expected result?

If the feed updates, the currently selected article should not update (regardless of its filter status) - i.e. as usually happens when the article is read and the feed does not update

### What actually happened?

Article disappears in the middle of reading to be replaced by another

### Debug log

Not relevant here

### Operating system and version

* OS: Win 11
* RSS Guard version: 4.7.0

**Comment by Ac314** [comment]
It is related to #1289.
Current solution for me is to enable the option "Only auto-fetch articles if application is unfocused". In this case feeds are not updated at all if I am reading something so articles will not be deleted or hid.

**Comment by martinrotter** [comment]
Hopefully fixed. New behavior will TEMPORARILY display also article which is selected even if it should be hidden by the article list filter. See video below.

https://i.imgur.com/RXGiQ2s.gif

**Comment by aubreyz** [comment]
That looks good. Thanks for your speed and attention to this whole project. Ideally I think the focussed line should remain on the previously selected (unread) article and not shift to another one (which also becomes read) - if I am interpreting the video correctly.

**Comment by martinrotter** [comment]
No. If you have article selected (becomes read) and "unread only" filter is active, then now the new behavior is that the SAME article will still be selected even if the feed gets fetched in the meantime.

**Comment by aubreyz** [comment]
> No. If you have article selected (becomes read) and "unread only" filter is active, then now the new behavior is that the SAME article will still be selected even if the feed gets fetched in the meantime.

That sounds perfect. It was not obvious from the video which looked different. Thanks as always for all of your good spirited work.

**Comment by aubreyz** [comment]
(as an aside - you don't have a PM address - so messaging here 
your paypal link shows an invalid certificate, and is blocked by my setup. That would be my preferred contribution route for one-off coffee gifts. Not sure if a paypal issue or specific to your created link)

**Comment by martinrotter** [comment]
> (as an aside - you don't have a PM address - so messaging here your paypal link shows an invalid certificate, and is blocked by my setup. That would be my preferred contribution route for one-off coffee gifts. Not sure if a paypal issue or specific to your created link)

Weird, that "paypal.me" link is official paypal way of sharing links to get paid via paypal. Maybe its some temporary problem on their side.
