### ISSUE TITLE
[BUG]: Regressions in version 4.7.0

### ISSUE THREAD

**Issue by danfe** [martinrotter/rssguard#1416]
After updating to the new version, all my feeds are gone and I'm greeted with an empty **Add new account** window.

Also, in the **About** window, version information is now just one long string with no separators.

Before (4.6.6):
![466-ok](https://github.com/martinrotter/rssguard/assets/1132291/57c82f25-1aea-4f42-b80c-3b02a59ea12d)

Now (4.7.0):
![470-bad](https://github.com/martinrotter/rssguard/assets/1132291/7a6e5bf8-faa5-4f0e-92a8-a0b32277f151)

### Operating system and version

* OS: FreeBSD/amd64
* RSS Guard version: 4.7.0

**Comment by martinrotter** [comment]
Hi, this is amazing bug report. Where is the log showing some error? Where is precise set of steps to reproduce?

I personally have tested 4.7.0 from 4.6.6 updated several times, also using 4.7.0 for already many hours without problems.

Feel free to provide some context and relevant logs as at this point this BR is unusable.

**Comment by martinrotter** [comment]
It seems that perhaps library files with plugins are not loaded, provide full log.

**Comment by martinrotter** [comment]
I will tast via ghostbsd

**Comment by martinrotter** [comment]
OK I tested it. While I found some other UNRELATED bugs, I must say that RSS Guard 4.7.0 works for me.

If "Add new account" window is empty, it means that library files with plugins were not loaded. So this is rather packaging problem.

I added semi-fix (not tested) to properly search for plugin library files on BSD.

https://github.com/martinrotter/rssguard/blob/master/src/librssguard/miscellaneous/pluginfactory.cpp#L68

Logic is this, if the main executable path in /xx/yy/rssguard (rssguard is name of binary), then rssguard searches plugin in path /xx/lib/rssguard/

So likely real directories should be like

"/usr/local/bin/rssguard" (executable)
"/urs/local/lib/rssguard/librssguard-standard.so" (plugin path)

Someone more able in BSD should check if latest [master] source code packages well.

**Comment by danfe** [comment]
> So likely real directories should be like
> 
> "/usr/local/bin/rssguard" (executable)
> "/urs/local/lib/rssguard/librssguard-standard.so" (plugin path)

Right, that matches my layout.  There's also helpful message in the log now: `core: Checking for plugins in '/usr/local/bin/..//rssguard'` which suggests that the path was not constructed correctly for some reason (missing the `lib` part).

It turns out that you set `RSSGUARD_LIBDIR="${CMAKE_INSTALL_LIBDIR}"` before doing `include (GNUInstallDirs)`.  Moving that `target_compile_definitions` block after fixes the path and now everything's fine, my profile and feeds are all back and working!

**Comment by martinrotter** [comment]
Yes, the part "lib" seems to be missing, can you please do pull request with the fix you did? It would likely be best.

**Comment by chrisretusn** [comment]
I see the same issue. 

slackware64-current.
### RSS Guard
**Version:** 4.7.0 (built on Linux/x86_64)
**Revision:** 
**Build date:** 5/27/24 1:00 PM
**OS:** Slackware 15.0 x86_64 (post 15.0 -current)
**Qt:** 6.7.1 (compiled against 6.7.1)

On starting rssguard from Konsole an empty "Add new account" window appears. The tray icon is in place, pressing Okay results in a segmentation fault. Pressing Cancel RSS Guard stays up, that's how I was able to copy the RSS Guard information. There are no feeds.

[rssguard-20240527-Cancel.log](https://github.com/martinrotter/rssguard/files/15456575/rssguard-20240527-Cancel.log)
[rssguard-20240527-Okay.log](https://github.com/martinrotter/rssguard/files/15456580/rssguard-20240527-Okay.log)

Reverting  back to 4.6.6 and all is okay.

**Comment by chrisretusn** [comment]
Additional. The shared librariy fles are located as follows:

 ls -l /usr/lib64/librssguard*.so /usr/lib64/rssguard/*
-rwxr-xr-x 1 root root 9319744 May 27 22:22 /usr/lib64/librssguard.so*
-rwxr-xr-x 1 root root  268336 May 27 22:22 /usr/lib64/rssguard/librssguard-feedly.so*
-rwxr-xr-x 1 root root  604976 May 27 22:22 /usr/lib64/rssguard/librssguard-gmail.so*
-rwxr-xr-x 1 root root  438512 May 27 22:22 /usr/lib64/rssguard/librssguard-greader.so*
-rwxr-xr-x 1 root root  239616 May 27 22:22 /usr/lib64/rssguard/librssguard-nextcloud.so*
-rwxr-xr-x 1 root root  909600 May 27 22:22 /usr/lib64/rssguard/librssguard-standard.so*
-rwxr-xr-x 1 root root  409312 May 27 22:22 /usr/lib64/rssguard/librssguard-ttrss.so*

**Comment by martinrotter** [comment]
Yes, these problems now should be basically fixed. Either as a packager wait for new release or try to repackage with latest [master] code.

**Comment by chrisretusn** [comment]
> Yes, these problems now should be basically fixed. Either as a packager wait for new release or try to repackage with latest [master] code.

I went with creating a package from master (523e760f1f). All is well.
