### ISSUE TITLE
FR: Auto-select article when article list gains focus

### ISSUE THREAD

**Issue by danowar2k** [martinrotter/rssguard#142]
#### Brief description of the issue.

Just another feature request for better working with the keyboard.

The TAB order of the elements right now seems a little bit off. When the feed list has focus and you press TAB, it would be nice if the article list gains focus. But right it seems (!) that this isn't the case. What happens is you press TAB, then nothing seems to have focus. Then you move with the arrows and you see that the article list HAS gained focus but nothing was selected.
Ergo it would be nice if you would always auto-select an article...?

**Comment by martinrotter** [comment]
Hello, yes, the tab order is correct. I tried to fix this. Please test latest development build and **let me know your results.**

https://github.com/martinrotter/rssguard/commit/ad36c34298728fd4b432f850d3e6f3d170a8894c

**Comment by danowar2k** [comment]
Hi, I tried the dev build at https://transfer.sh/1yTAc/rssguard-3.5.4-35bb9c9-win64.7z

Didn't work quite right. 
I tabbed to the article list, no article was selected. 
I arrowed down, second article was selected. 
I tabbed back to the feed list, a feed was selected. 
I tabbed back to the article list, the last selected article was selected.

**Comment by martinrotter** [comment]
Try this one https://transfer.sh/13Mmlj/rssguard-3.5.4-598b591-win64.7z .
You were trying bad development build (the one without fix).

**Comment by danowar2k** [comment]
Okay, downloading...
Could you do something about the layout of the page? https://github.com/martinrotter/rssguard/wiki/Windows-development-builds
Somehow there seem to be no newlines. Also, I'd propose to sort the builds below date headers, like:

2017-10-10:
2017-10-10_cj45tjd-3.5.4.7z
2017-10-10_fg452jd-3.5.4.7z

Or something like that. And maybe sort by date decreasing, so you have the latest builds on top?

**Comment by danowar2k** [comment]
That build's much better, though. Tabbing now selects the first article in the list. :-)

**Comment by martinrotter** [comment]
Yea, I will eventually sort out better layout for those wiki pages.

So the issue is solved? Can I mark as fixed?

**Comment by danowar2k** [comment]
Yep, I can confirm this is fixed now.
