### ISSUE TITLE
[BUG]: Non-lite builds for windows 7 are missing

### ISSUE THREAD

**Issue by Shakil-Shahadat** [martinrotter/rssguard#1426]
### Brief description of the issue

There used to be 14 assets, even in the last but one build. But now it's 12 in the last 4.7.1 build.

### How to reproduce the bug?

It is not needed.

### What was the expected result?

None

### What actually happened?

None

### Debug log

None

### Operating system and version

* OS: Windows 8.1
* RSS Guard version: 4.7.1

**Comment by martinrotter** [comment]
There was an error in naming release files. Non-lite windows 7 files are there, just use bigger of those named "lite" and they will be non-lite. It will be fixed for new release, or just use newest devbuild. 

https://github.com/martinrotter/rssguard/releases/tag/devbuild
