### ISSUE TITLE
FR: Allow to select multiple feeds in feed list (using CTRL+Click or SHIFT+Click, for example)

### ISSUE THREAD

**Issue by danowar2k** [martinrotter/rssguard#143]
#### Brief description of the issue.

My last feature request for now: Right now you can only select one feed at a time in the feed list. Sometimes it would be nice if you could select multiple feeds to mark them all as read at once.

For example, like in the Windows explorer, select/deselect entries with CTRL+left click, select a range of entries using SHIFT+left click.

**Comment by martinrotter** [comment]
duplicate to #89
