### ISSUE TITLE
[BUG]: Crashing after update

### ISSUE THREAD

**Issue by Vinayak-kadu** [martinrotter/rssguard#1430]
### Brief description of the issue

tried to update from 4.3.2 to 4.7.2 today and mistakenly did it with full version on lite installed.
since then crashing aand not launching.
tried complete reinstall and still no launch

### How to reproduce the bug?

:(

### What was the expected result?

should have updated to newer version of rss guard

### What actually happened?

installed full version on lite version

### Debug log

time="     0.016" type="debug" -> core: Initializing settings in 'C:\Users\Vinayak\AppData\Local\RSS Guard 4\config\config.ini' (non-portable way).
time="     0.017" type="debug" -> core: Starting to load active localization. Desired localization is 'en_US'.
time="     0.018" type="debug" -> core: Application localization 'en_US' loaded successfully, specifically sublocalization 'en_US' was loaded.
time="     0.018" type="warning" -> core: Qt localization 'en_US' WAS NOT loaded successfully.
time="     0.031" type="warning" -> database: SQLite database is not initialized. Initializing now.
time="     0.032" type="debug" -> database: SQLite database backend should be ready now.
time="     0.099" type="debug" -> database: Creating backup of SQLite DB file.
time="     0.100" type="fatal" -> Error when updating DB schema from 4: duplicate column name: labels Unable to execute statement.

### Operating system and version

* OS: Win 10 pro
* RSS Guard version: 4.7.2

**Comment by Vinayak-kadu** [comment]
![default](https://github.com/martinrotter/rssguard/assets/42799246/86bc5895-93e3-44c6-9a02-10c2e0e0244a)

**Comment by martinrotter** [comment]
Hi, it seems that your database file (database.db) got upgraded badly, this was likely caused by some error in upgrade mechanism which did not work well when upgrading from such an old version of RSS Guard.

Can you share your database.db file with me so I can fix? My e-mail is rotter.martinos(at)gmail.com

**Comment by Vinayak-kadu** [comment]
hi, thank you for reply but i have been trying myself if i can repair it..  
currently only way i can open Rssguard by creating empty database.db file.
also i tried to manually replace some unicode characters, Null in my corrupted db file but Rssguard fails to launch on such attempt.
can you provide default or empty schema of database file?  so i can compare where are the differences with my database file.
