### ISSUE TITLE
FR: Be able to select what type of desktop notifications appear

### ISSUE THREAD

**Issue by danowar2k** [martinrotter/rssguard#144]
#### Brief description of the issue.

Another feature request (sorry for the volume): It would be nice if, when desktop notifications are enabled, you could choose what notifications to get. For example, I would like to be notified about new articles, but I don't need to be notified about the fact that RSS guard is starting to look for new articles (if you know what I mean).

**Comment by martinrotter** [comment]
WIP

![image](https://user-images.githubusercontent.com/1255302/122056994-70984200-cdea-11eb-8f77-373854f27724.png)

**Comment by martinrotter** [comment]
Experimental implementation is done. Test via development build, please.

ab1011b
