### ISSUE TITLE
FR: Ability to change font size

### ISSUE THREAD

**Issue by danowar2k** [martinrotter/rssguard#145]
#### Brief description of the issue.

I would like to be able to change the font size in the list views. Just because I'm getting older and the font is sometimes too small for my eyes.

Thank you in advance :-)

**Comment by martinrotter** [comment]
Will add.

**Comment by martinrotter** [comment]
https://imgur.com/a/Krmkh

**Comment by martinrotter** [comment]
Now, I realised I actually changed width of items, not font, let me tweak.

**Comment by martinrotter** [comment]
OK, screenshots, https://imgur.com/a/Krmkh

**Comment by danowar2k** [comment]
Thank you very much.
Does the setting change font size only in the message list or in the feed list, too?
Also, does the "Height or rows in message list" value mean font size?
Couldn't you just copy/paste the Font Size UI element, labeling every copy with the element you change?

**Comment by martinrotter** [comment]
There are now two independent settings - feed list, message list.
And yes, it basically means font size, but there is some extra space around. Is this fix okay for you?

**Comment by danowar2k** [comment]
Completely ok, I think. Don't know if you can see who gave the thumbs up...
