### ISSUE TITLE
[BUG]: Time.com feeds do not render properly

### ISSUE THREAD

**Issue by mmkthecoolest** [martinrotter/rssguard#1450]
### Brief description of the issue

Feeds from time.com seem to display raw HTML rather than normal text and images

### How to reproduce the bug?

1. Add a feed from time.com. Examples: https://time.com/feed/, https://time.com/tech/feed/, https://time.com/health/feed/
2. Fetch articles from the feed source

### What was the expected result?

The articles should just have mostly normal text and images on them.

Example with RSSPreview addon on Firefox:
![image](https://github.com/martinrotter/rssguard/assets/27556124/ef0b8377-d47b-4f28-bee5-ec5b68c85445)

Example with Feeder for Android:
![Screenshot_20240711_000447_Feeder](https://github.com/martinrotter/rssguard/assets/27556124/6c545c39-f707-4052-b8ed-78a640012596)

### What actually happened?

Raw HTML seems to be displayed instead
![image](https://github.com/martinrotter/rssguard/assets/27556124/741f4847-471c-4c0d-9c09-a6bdc7c8864c)

### Debug log

[rssguard.log](https://github.com/user-attachments/files/16168905/rssguard.log)

### Operating system and version

* OS: Fedora 40 (Flatpak)
* RSS Guard version: 4.7.2

**Comment by ScoobyDone** [comment]
also happens with https://laststandonzombieisland.com/feed/

in the artivle view, previews of the images render above the title/header and the malformed text is displayed inline in the article itself.

screencap snippet: https://imgur.com/a/KXIlkHL

**Comment by martinrotter** [comment]
Hi thanks for reporting, I fixed the problem. Either wait for new release or you can test with latest development build once it compiles.

**Comment by martinrotter** [comment]
> also happens with https://laststandonzombieisland.com/feed/
> 
> in the artivle view, previews of the images render above the title/header and the malformed text is displayed inline in the article itself.
> 
> screencap snippet: https://imgur.com/a/KXIlkHL

I checked this and sadly, the HTML contained in this feed is of very low quality and even built-in Chromium-based HTML renderer is not able to render it correctly. The HTML contains syntax errors which make it unable to display the article correctly. Even Chrome browser itself is not able to display it better.

Contact feed author to fix the feed.
