### ISSUE TITLE
https://mail.google.com/mail/feed/atom shows up empty in reader

### ISSUE THREAD

**Issue by pouar** [martinrotter/rssguard#146]
#### Brief description of the issue.
When updating the rss feed at https://mail.google.com/mail/feed/atom it acts like the feed has no new entries

#### How to reproduce the bug?

1. add a new feed using https://mail.google.com/mail/feed/atom as the URL
2. right-click the new feed and select "update selected items"

#### What is the expected result?

New messages are downloaded and show up in the message list for the feed

#### What actually happened?

nothing shows up in the message list for the feed as if there were no new items

#### Other information (logs, see Wiki)
here's the stdout/stderr output
[log.txt](https://github.com/martinrotter/rssguard/files/1364704/log.txt)
Not sure if this is related, but typing https://mail.google.com/mail/feed/atom in the address bar in a web browser tab redirects to Google as if it was a search term instead of a url.

**Comment by martinrotter** [comment]
Please, try this development build - https://transfer.sh/wzLoJ/rssguard-3.4.3-e6eee64-win64.7z - and check if problem is resolved.

**Comment by martinrotter** [comment]
Moreover, I plan to add extra plugin to work with Gmail JSON API.

**Comment by pouar** [comment]
I'm on Arch Linux. But that's no problem as that build seems to be a Windows binary of the current master branch, so I just compiled that. And yeah, the problem seems to be fixed in master.

**Comment by pouar** [comment]
What was the commit that fixed it? As I want to cherry pick that into the current version, unless it involved significant changes.

**Comment by martinrotter** [comment]
I think it was
https://github.com/martinrotter/rssguard/commit/8a7ca6b2895292d62ba982e42ce229f1be8a5179
