### ISSUE TITLE
[FR]: Ignore <updated>-tag in youtube rss feeds

### ISSUE THREAD

**Issue by cyberpunkbln** [martinrotter/rssguard#1462]
### Brief description of the feature request

Hello.

rssguard reads the items in youtube rss feeds again when the updated tag was updated. Some youtube freagles use this to receive an higher attention, primarly on the youtube website. I like the updated tag when i have some sort of videos, live-feeds or announcments but how i write the most youtubers use it occasionally wrong and it annoys to have every day dozend of allready readed feed-items in my feeds.

How quiterss deal with this? In quiterss live-feeds and announcement-feeds will be updated after deleting when live-feed is over and an normal video or annoucment feeds start normaly. Is it why quiterss use rss1or2.0 for reveiving? When this is the trick an function to mass edit rss-feeds will be nice:).

i have every feed-item tested. Every allready readed feed-item has changed the <-updated>-tag to the present day and it is no content changed. Abusive using of this feature.

thx

edit: rssguard copy so entrys with abusive <updated>-tag from the trashcan to the feed-list.

**Comment by martinrotter** [comment]
This can be fixed per-feed with Article Filtering feature. See documentation on how to use it. If not sure how to use that feature, visit us on our discord server, see readme.
