### ISSUE TITLE
[BUG]: RSS Guard 4.7.3 Lite doesn't recognize dates for CSS2RSS eBay feed items

### ISSUE THREAD

**Issue by RetroAbstract** [martinrotter/rssguard#1465]
### As of 4.7.3 Lite (and 4.7.2 Lite), when using CSS2RSS to create eBay feeds and using the script's item date selector, RSS Guard doesn't recognize the eBay item dates.

When I [asked for help](https://github.com/Owyn/CSS2RSS/issues/4#issuecomment-2266238243) in trying to get the item dates for eBay items with CSS2RSS, the script's creator being on 4.3.3 No Web Engine successfully got RSS Guard to recongize eBay item dates with the following string for CSS2RSS: `python css2rss.py "li.s-item" "span.s-item__listingDate" ~ "a[href*=UserReviews]" ~ "span.s-item__listingDate"`.

### **4.3.3 No Web-Engine:**

![3](https://github.com/user-attachments/assets/6b60175f-82f5-4cbf-bb75-d2150c0d0485)
![4](https://github.com/user-attachments/assets/25e007d5-0fcb-44b3-bebc-c4e87489fadb)

_As shown in the screenshots above, 4.3.3 No W-E finds 64 items and finds dates for 62 of them._

4.7.3 Lite being my daily driver, I copied and pasted the post-process script Owyn shared, but got different results.

### **4.3.7 Lite:** 

![2](https://github.com/user-attachments/assets/b33c1769-9094-49ec-800d-8c0e55dc2794)
![1](https://github.com/user-attachments/assets/9ccad78f-ba2e-4e93-bad9-53364b3c0d45)

_As shown in the screenshots above, 4.3.7 Lite finds 27 items (2 with no links) compared to 64 in 4.3.3 No W-E and doesn't find dates for any of the detected items._

Both 4.7.3 Lite and 4.3.3 No W-E are running the same version of CSS2RSS.

Something is clearly different in the way 4.3.3 No W-E and 4.7.3 Lite parses information from eBay with CSS2RSS.

### How to reproduce the bug?

To compare both versions, have both 4.3.7 Lite and 4.3.3 No Web-Engine on your system alongside the latest version of CSS2RSS on your system, then:

1. Create a new feed with this example eBay URL "[nintendo switch](https://www.ebay.com/sch/i.html?_nkw=nintendo+switch&_sacat=0&_sop=10)"
2. Enter the following string in the post-process script box: `python css2rss.py "li.s-item" "span.s-item__listingDate" ~ "a[href*=UserReviews]" ~ "span.s-item__listingDate"`
3. Fetch the feed metadata, notice the differences in the description box outcome between versions 4.3.7 Lite and 4.3.3 No-Web Engine
4. Fetch articles from the feed in both versions and notice also how in 4.3.7 Lite the fetched articles all have the same time relative to when fetched, and in 4.3.3 No W-E the articles have as date the data from the CSS2RSS item date selector

### What was the expected result?

The expected result was for version 4.3.7 Lite to recognize the eBay item dates.

### What actually happened?

4.3.7 Lite didn't and doesn't recognize the eBay item dates.

### Debug log

N/A

### Operating system and version

* OS: Windows 10 
* RSS Guard version: 4.7.3 Lite

**Comment by martinrotter** [comment]
So this works fine with older RSS Guards?

**Comment by martinrotter** [comment]
Will test.

**Comment by martinrotter** [comment]
Here is what it returns for me with latest development RSS Guard.

![image](https://github.com/user-attachments/assets/d3f2f233-f8db-44b6-b6f5-5a081f6f894a)

**Comment by martinrotter** [comment]
![image](https://github.com/user-attachments/assets/634f1188-5e97-44df-abd9-6e6112677936)
