### ISSUE TITLE
[Mac OS X] Internal webengine-based web browser does not work because libraries are not "linked" correctly

### ISSUE THREAD

**Issue by peperjohnny** [martinrotter/rssguard#147]
#### Brief description of the issue.
I added my account and synced with Nextcloud News. However, when I click one of the Feeds nothing appears.

#### How to reproduce the bug?

1. Use the macOS version.
2. Add an account.
3. Click on one of the feeds.

#### What is the expected result?

Feeds should be shown in the internal Browser.

#### What actually happened?

Window stayed blank. Even after a waiting time of a 5 minutes, nothing appeared in the window.
![screen shot 2017-10-09 at 08 23 48](https://user-images.githubusercontent.com/31721266/31326881-a352ad2a-acba-11e7-9023-f793aa50ac66.png)

#### Other information (logs, see Wiki)
This happens if I start the app via terminal, as soon as I click one of the feeds.
`[rssguard] DEBUG: Loading messages from feeds: '11'. (17/09/10 08:20:46)
dyld: Library not loaded: /usr/local/Cellar/qt/5.9.1/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore
  Referenced from: /Applications/RSS Guard.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
  Reason: image not found
[rssguard] DEBUG: Current row changed - row [0,5] source [0, 5]. (17/09/10 08:20:58)
dyld: Library not loaded: /usr/local/Cellar/qt/5.9.1/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore
  Referenced from: /Applications/RSS Guard.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
  Reason: image not found`

**Comment by martinrotter** [comment]
It seems that some library is missing from APK? I do not have Mac OS X, so I cannot provide some kind of serious support, those APKs were more or less just attempt to provide Mac OS X builds.

Maybe you just could install qt via homebrew and it could help.

Let me know if there is any progress.

**Comment by peperjohnny** [comment]
Did as you told and now it's working.

**Comment by martinrotter** [comment]
Well, the dmg files is generated with these scripts:
https://github.com/martinrotter/rssguard/blob/master/resources/scripts/.travis-before-install.sh
https://github.com/martinrotter/rssguard/blob/master/resources/scripts/.travis-install-osx.sh

Basically:
1. Brew packages are installed (Qt too).
2. Application is compiled. (make)
3. DMG is generated with tool macdeployqt. (make dmg)

Maybe the DMG is generated badly, and problem could be related to this: https://bugreports.qt.io/browse/QTBUG-50155

**Comment by martinrotter** [comment]
Maybe the solution would be to NOT package Qt libraries into DMG and rely on Qt installed in system?

**Comment by martinrotter** [comment]
What about distributing just single binary file without libraries. Would it work? I honestly do not know what format is preferable and good in mac os. RSS Guard resources are now compiled directly into the executable.

**Comment by peperjohnny** [comment]
If you can provide me a DMG I can install it and tell you which one works.

**Comment by martinrotter** [comment]
That's little problem, I can generate DMG blindly. I do not have macos, DMG as compiled by Travis CI - https://travis-ci.org/martinrotter/rssguard/jobs/285407347

So I have to make changes and hope they will work.

**Comment by peperjohnny** [comment]
Thing is I have little to no programming knowledge. I'll try to build the package myself without pulling in qt and see what happens.

**Comment by martinrotter** [comment]
I will fiddle it to, and post any results I get.

**Comment by martinrotter** [comment]
Is there any command which would create DMG file from folder?

**Comment by martinrotter** [comment]
Would this work?: `hdiutil create -volname rssguard -srcfolder /path/to/the/folder/you/want/to/create -ov -format UDZO rssguard.dmg`

**Comment by peperjohnny** [comment]
It builds a DMG so should be working

**Comment by martinrotter** [comment]
Is hdutil present on all macoses?

**Comment by peperjohnny** [comment]
It seems so. However, I have no second mac to test on right now.

**Comment by martinrotter** [comment]
I created modified DMG and bare ZIP for you, test both.

https://transfer.sh/dPJf2/RSS-Guard.dmg
https://transfer.sh/13CTAN/rssguard-3.4.3-cc66e17-mac.zip

**Comment by martinrotter** [comment]
I will try to generate DMG WITHOUT qt libs so that we can try to rely on qt libs installed on system.

**Comment by peperjohnny** [comment]
I removed qt beforehand.
The DMG still shows no content if you click a feed.
The ZIP crashes while starting.

The DMG works again if I brew install qt.

**Comment by martinrotter** [comment]
Yes, that is what I expected, I will try to make DMG wihtout qt libs, I guess it would be the best way to have lightweight rssguard archive + have Qt libs installed system-wide via brew.

**Comment by martinrotter** [comment]
Try these ones:

https://transfer.sh/13Lsww/RSS-Guard.dmg
https://transfer.sh/12kN1E/rssguard-3.4.3-5952f91-mac.zip

**Comment by martinrotter** [comment]
Unzip the zip into clean folder first. I also try to generate slimmer dmg.

**Comment by peperjohnny** [comment]
So the DMG starts without qt installed, but has the same problem as before without qt.
The ZIP needs qt to be installed to run. As you probably know.
Works fine as far as I can tell.

**Comment by martinrotter** [comment]
"The ZIP needs qt to be installed to run. As you probably know" I know, but otherwise the zip works? Would distributing this zip be enought for macosx users? Do you think its okay?

**Comment by martinrotter** [comment]
Try this one please: https://transfer.sh/c8Flw/rssguard.dmg

**Comment by martinrotter** [comment]
it is DMG stripped off from qt libs, so it is just like the ZIP but only DMG + so you need system qt installed

**Please, let me know if this DMG could be used as final solution for distributing Mac OS port of RSS Guard.**

**Comment by peperjohnny** [comment]
The last one works for me. 
Short answer for technical people: **Yes**
Short answer for normal people: **No**

In my opinion you can distribute it, but you have to be aware that you absolutely need to have qt installed. I installed it now with homebrew. Now your app may be right now mostly for technical folk, but if you want to have it available for normal users, e.g. not the ones able to install qt themselves, you will need to link statically and provide needed stuff yourself.

**Comment by martinrotter** [comment]
Cannot link statically, the only thing to do is to bundle all Qt libs into the DMG, but I am not able to effectively do that, as I do not have Mac OS X, sorry. If someone with interest/macos comes in, then we could have rock-solid macos DMG file. Until then, we have to be satisfied with system-wide qt.

**Comment by phedlund** [comment]
What changed? Building a fully functional dmg worked a few months back? Sorry, I have not had time to work on/test RSS Guard lately.

**Comment by martinrotter** [comment]
@phedlund Reporter of this issue reported that QtWebEngine libraries are somehow not working in the bundle. As I have absolutely no way to test if these DMGs actually work, I tried to remove Qt libs from bundle, thus forcing users to use system-wide Qt libs (for example installed via HomeBrew).

So, can you double-check if some DMG bundle with included Qt libs actually really works (NO system-wide Qt installed)? For example this one: https://transfer.sh/hA8q9/RSS-Guard.dmg (this is the DMG with qt libs bundled). Your assistance could be helpful here as I have no way to actually trying to solve the libs problems which OP has.

Also, this is the new DMG without Qt libs (https://transfer.sh/YQHe5/Guard.dmg).

**Comment by martinrotter** [comment]
@phedlund @peperjohnny  I will revert DMG to old bundle and I will create a POLL where users will respond if DMG works or not.

**Comment by peperjohnny** [comment]
I got hold of another Mac and tried your latest bundle there. This Mac has not seen any qt at all. But it still did not work.

**Comment by martinrotter** [comment]
Which DMG does not work, the big one which should have Qt included?

I got report from [poll](https://docs.google.com/forms/d/e/1FAIpQLSfewZe9ld0Qlm7uz3RaDjzir2xn_m3QYgJ-KvmLTN6m_Frrtw/viewform) that there indeed can be error, as someone reported that these big DMGs do not work for them too.

As I said, I cannot fix mysel, do not know anything about macosx platform, @phedlund can maybe step in. If not, then the only change I can make is the one we tried yesterday - generating smaller DMGs without qt bundled and use qt from system.

**Comment by peperjohnny** [comment]
Yes sorry the latest one 3.5.0 which you put up for download. I hope @phedlund can provide some assistance.

**Comment by phedlund** [comment]
3.5.0 runs on a Sierra Mac with no Qt installed, but the internal browser is not working. I'll see if I can figure out what's going on in the next few days.

**Comment by martinrotter** [comment]
@phedlund That's precisely the issue. You may want to see DMG build output log: https://travis-ci.org/martinrotter/rssguard/jobs/286002776

Interesting things I think are on line 3837 (otool output). It (I guess?) correctly shows that all Qt libs should be loaded from correct paths, especially

```
@executable_path/../Frameworks/QtWebEngineWidgets.framework/Versions/5/QtWebEngineWidgets (compatibility version 5.9.0, current version 5.9.1)
```
```
@executable_path/../Frameworks/QtWebEngineCore.framework/Versions/5/QtWebEngineCore (compatibility version 5.9.0, current version 5.9.1)
```

**Comment by phedlund** [comment]
Building release from source and then macdeployqt creates a bundle that works fine. 

Differences that I see is that the downloaded build is missing QtMacExtras.framework and PkgInfo.

I don't know if that's enough to explain the difference. I also don't know how to modify or execute the automatic build script.

**Comment by martinrotter** [comment]
So, should I link against QtMacExtras? How do I add PkgInfo? Any docs in this? Do you have Qt installed via homebrew or you tried with Qt-free system?

**Comment by martinrotter** [comment]
Qt WebEngine contains executable helper QtWebEngineProcess. It is not library, but executable file,
`/usr/local/Cellar/qt/5.9.1/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore Referenced from: /Applications/RSS Guard.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess`

Isn't it weird that there is extra `QtWebEngineProcess.app/Contents/MacOS/` in its path?

**Comment by martinrotter** [comment]
Maybe related to this: https://bugreports.qt.io/browse/QTBUG-50155?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

**Comment by martinrotter** [comment]
Same problem: https://stackoverflow.com/questions/46430930/how-to-make-macdeployqt-change-the-library-names-inside-qtwebengineprocess-app-w

**Comment by phedlund** [comment]
> Isn't it weird that there is extra QtWebEngineProcess.app/Contents/MacOS/ in its path?

Not necessarily. All macOS app bundles have the actual executable in /Contents/MacOS/. App bundles are just folders that receive special treatment by the OS.

> should I link against QtMacExtras?

Yes, it's used by one of the changes I did a few months ago. Don't worry about PkgInfo. It's a historical remnant from ages ago.

> Do you have Qt installed via homebrew or you tried with Qt-free system?

I develop and build on a Mac with Qt installed from qt.io. Testing is done on systems that have never had Qt installed in any way.

**Comment by martinrotter** [comment]
So, I will add link to QtMacExtras, then I will let you know, and please make summary for me with this info:
 - if DMGs work or not,
 - if I need to change anything regarding RSS Guard Mac OS X deployment (so that we can finally have really good DMG).

:)

**Comment by martinrotter** [comment]
QtMacExtras added some commits ago. I will probably close it, because it seem as @phedlund reported that DMG should be OK and working (he checked in clean Qt-free environment).

**Comment by martinrotter** [comment]
So, for those who have errors, the workaround is to install Qt from HomeBrew. Hopefully, some fixed will be incoming from Qt people, it is known that the tool for generating bundles on Mac OS X is sometimes buggy.

**Comment by tomowad** [comment]
I installed rssguard 3.7.1 on macOS 10.15.6. The internal browser didn't work. I found this discussion and tried installing Qt via homebrew. Installing via homebrew did not affect rssguard's behavior. Starting rssguard from the terminal, I saw that it is specifically looking for version 5.13.2, whereas homebrew installed 5.15.0.

**Comment by martinrotter** [comment]
@tomowad Yes, there are still problems with "bundling" Qt with RSS Guard. Also, as you stated, system-wide Qt is somehow broken too. This is just shame, as I do not own Mac to develop/test myself.

It seems that we would really need somebody skilled with Qt/C++/mac to dig into the issue and fix it properly.

**Comment by martinrotter** [comment]
I have now tried this and came to conclusion that current DMG file is broken. Homebrew's macdeployqt utility is simply broken and at this point I am just not able to fix it, because in VirtualBox environment with Mac OS, everything is so slow, it is all painful.

At this point, I highly recommend for all Mac OS users to build RSS Guard themselves with official Qt distribution.

**Comment by martinrotter** [comment]
Closing this, starting from 3.8.3, I will not produce WebEngine-based binaries for Mac OS X, because Homebrew's Qt package is broken.

See bold text in https://github.com/martinrotter/rssguard/blob/master/resources/docs/Downloads.md#official-downloads

**Comment by martinrotter** [comment]
OK, guys I decided to give it one more shot and managed to use custom Qt-installer which ships official and WORKING libraries.

I compiled sample DMG for you and now it should all work!! I tested with vanilla Mac OS in VirtualBox: https://bintray.com/api/ui/download/martinrotter/rssguard/rssguard-3.8.2-ebef0783-mac64.dmg

**Comment by tomowad** [comment]
It's working great on 10.15.6. Thank you so much!

**Comment by martinrotter** [comment]
@tomowad Nice to hear that, this ticket was haunting me like a crazy witch.

If you find any bugs or UX problems on macosx, create ticket please, I do not know what eact GUI guidelines are preferred for macosx but I will adjust it if you report.
