### ISSUE TITLE
[FR]: GUI option to set custom User-Agent in settings

### ISSUE THREAD

**Issue by RetroAbstract** [martinrotter/rssguard#1471]
### Brief description of the feature request

This feature would allow the user to set a custom User-Agent directly in the GUI settings.

Currently you can only set a custom User-Agent with -u, --user-agent followed by the User-Agent string when launching RSS Guard from CMD or a bat file.

On Windows at least, the Target box reaches the maximum amount of characters allowed when you factor in:

- the RSS Guard executable path 
- the --d, --data option + data folder path
- the -u, --user-agent + User-Agent string

The above results in needing the RSS Guard program folder to have a short path in order to fit everything in the target box of the executable shortcut. 

Having a GUI option to set the custom User-Agent would allow the RSS Guard program folder/executable to have a longer path while still being able to use the -d, --data option and have a custom User-Agent.

The feature could be added in the form of a string box in _Settings > General > User-Agent: [User's Custom U-A Here]_.

Thanks!

**Comment by martinrotter** [comment]
Yes, I agree, although you can create simple .bat file to launch rssguard with all the CLI switches you need.

**Comment by martinrotter** [comment]
Fixed.

![image](https://github.com/user-attachments/assets/ef8a9e5a-04b5-4bbd-90d1-08ca40b69608)
