### ISSUE TITLE
[FR]: Option to make loading pictures present larger by default

### ISSUE THREAD

**Issue by rambo919** [martinrotter/rssguard#1476]
### Brief description of the feature request

Especially for feeds that basically are images like cartoons..... the tiny or not at all presentations are counter productive to say the least. Doing this per feed would be best as some feeds have huge images for some reason.

**Comment by martinrotter** [comment]
Sorry but can you clearly state what exactly do you request? What do you mean "present larger by default". Write exactly, specifically what exactly should the feature be.

**Comment by rambo919** [comment]
> Sorry but can you clearly state what exactly do you request? What do you mean "present larger by default". Write exactly, specifically what exactly should the feature be.

Sorry I thought it was obvious.... instead of slightly larger than thumbnail let it be closer to full size.... so you can see what it is instead of guessing.

This for example is just plain too small for many images in articles, the more that goes on in the image the less clear it becomes at that size..... leading to lots of squinting. 
![Screenshot_20240813_093838](https://github.com/user-attachments/assets/ade1c206-e636-4838-81f0-9ba64f912c3e)

**Comment by martinrotter** [comment]
Do you use full or lite rssguard?

**Comment by rambo919** [comment]
> Do you use full or lite rssguard?

From the flatpak so assuming full.

**Comment by rambo919** [comment]
> You can set the size of images in articles by default in _Settings > Feeds & articles > Articles > Limit height of all pictures_.
> 

Ah ok, thanks, now I feel stupid.

**Comment by martinrotter** [comment]
not a problem man, cheers
