### ISSUE TITLE
[BUG]: Some valid date/time strings are not recognized 

### ISSUE THREAD

**Issue by itsCryne** [martinrotter/rssguard#1478]
### Brief description of the issue

RSS Guard fails to recognize a date/time string if (e.g.) the day is only one digit or the timezone is `UT` although both are permitted by RFC822

### How to reproduce the bug?

1. Add feed: https://gist.github.com/itsCryne/65893359e21d5eaa85e140402abc53bf
2. Fetch the feed

### What was the expected result?

The pubDate of all three items should be shown.

### What actually happened?

Only the pubDate of the first item is shown correctly. For the other items, the date/time of the fetch is shown.
![image](https://github.com/user-attachments/assets/c38b2256-10b1-4bba-8726-bcc2f0dab5f5)

### Debug log

https://gist.github.com/itsCryne/2564a2a65d624626bafa46ae36c79fc7
(l. 372 & 373 show the error)

### Operating system and version

<h4>RSS Guard</h4><b>Version:</b> 4.7.3 (built on Linux/x86_64)<br/><b>Revision:</b> a4e20486b-lite<br/><b>Build date:</b> 7/26/24 4:34 AM<br/><b>OS:</b> Arch Linux<br/><b>Qt:</b> 6.7.2 (compiled against 6.7.2)

**Comment by martinrotter** [comment]
Perfect, will check these and add support for them

**Comment by itsCryne** [comment]
I don't have any experience with Qt and also only limited C++ knowledge but after having a look at the code it seems that we just need to add another line [here in textfactory.cpp](https://github.com/martinrotter/rssguard/blob/ab4861a64f7d855be8080e03f45692473732a721/src/librssguard/miscellaneous/textfactory.cpp#L86) with
```cpp
.replace(QSL("UT"), QSL("+0000"))
```
and add the following lines [here](https://github.com/martinrotter/rssguard/blob/ab4861a64f7d855be8080e03f45692473732a721/src/librssguard/miscellaneous/textfactory.cpp#L139)

```cpp
// Commented out patterns are already present

pat << QSL("d MMM yy HH:mm:ss");
pat << QSL("dd MMM yy HH:mm:ss");
pat << QSL("ddd, d MMM yy HH:mm:ss");
//  pat << QSL("ddd, dd MMM yy HH:mm:ss");
pat << QSL("d MMM yy HH:mm");
pat << QSL("dd MMM yy HH:mm");
pat << QSL("ddd, d MMM yy HH:mm");
pat << QSL("ddd, dd MMM yy HH:mm");

// Four digit year
// Not valid per RFC822
// but valid per RFC2822
pat << QSL("d MMM yyyy HH:mm:ss");
pat << QSL("dd MMM yyyy HH:mm:ss");
//  pat << QSL("ddd, d MMM yyyy HH:mm:ss");
//  pat << QSL("ddd, dd MMM yyyy HH:mm:ss");
pat << QSL("d MMM yyyy HH:mm");
pat << QSL("dd MMM yyyy HH:mm");
pat << QSL("ddd, d MMM yyyy HH:mm");
//  pat << QSL("ddd, dd MMM yyyy HH:mm");
```

If that seems correct, I could also submit a PR with those changes - but I guess it'd be faster/more convenient for you if you make them directly‽
