### ISSUE TITLE
[BUG]: Unexpected opening from system tray after powering off second monitor

### ISSUE THREAD

**Issue by quickwick** [martinrotter/rssguard#1479]
### Brief description of the issue

RSS Guard unexpectedly comes out of the system tray, with a blank window, after turning off one of two monitors in a dual-screen setup.

### How to reproduce the bug?

1. Have a computer with two monitors, both powered on
2. Minimize RSS Guard to the system tray
3. Power off one of the monitors

### What was the expected result?

Expected result is that RSS Guard stays hidden in the system tray.

### What actually happened?

RSS Guard opens and comes to the forefront, except the window contents are blank. 

At that point, clicking the Close (X) button does not send the application to the system tray (it does nothing, actually). Clicking the Minimize (_) button sends the application to the system tray instead of minimizing.

After manually sending the application to the system tray and then bringing it back, the application appears fully functional (no more blank white window).

### Debug log

time="174313.301" type="debug" -> gui: Message list got focus with reason 'Qt::ActiveWindowFocusReason'.
time="174316.133" type="debug" -> gui: Main window hide event
time="174316.133" type="debug" -> gui: Article list header geometries changed.
time="174316.135" type="debug" -> gui: Main window close event
time="174330.741" type="debug" -> core: Delaying scheduled feed auto-download for some time since window is focused and updates while focused are disabled by the user and all account caches are empty.

### Operating system and version

* OS: Windows 10 Pro 22H2
* RSS Guard version: 4.7.2

**Comment by quickwick** [comment]
Sorry, I didn't search well enough before posting. I think this is the same issue reported in #1384

**Comment by quickwick** [comment]
Oh, and #1456

**Comment by quickwick** [comment]
Possible good news. I updated from 4.7.2 to 4.7.3 after submitting this bug report, and the issue does not appear to be happening anymore.

**Comment by martinrotter** [comment]
THis seems to be really Qt upsteream bug. I will keep updating underlying Qt libraries steadily, hopefully all these bugs will go away. CLosing for now.
