### ISSUE TITLE
[FR]: bind to network interface

### ISSUE THREAD

**Issue by seventyiris83** [martinrotter/rssguard#1480]
### Brief description of the feature request

hi, it would be great to have a "Bind to network interface" feature, like qbittorrent has. could be added in the network web & tools settings section

purpose of it would be rss guard would only use the network interface it is bound to 

thank you :smile:

**Comment by martinrotter** [comment]
What you request is technically impossible because underlying network API used by RSS Guard does not allow such a feature, sadly.
