### ISSUE TITLE
[BUG]: No tray icon.

### ISSUE THREAD

**Issue by thealexparadox** [martinrotter/rssguard#1492]
### Brief description of the issue

There used to be a tray icon with the count of unread posts. This no longer displays.
In Tools | Settings | User Interface | Task bar, "Display count of unread messages" is checked.

### How to reproduce the bug?

Open RSS Guard and look at the taskbar.

### What was the expected result?

Expected: tray icon with the count of unread messages

### What actually happened?

What actually happened: No tray icon.

### Debug log

[rssguard.log](https://github.com/user-attachments/files/16988263/rssguard.log)

### Operating system and version

* OS: Win11 23H2
* RSS Guard version: 4.7.3

**Comment by martinrotter** [comment]
![image](https://github.com/user-attachments/assets/43793ad0-3c3a-4397-8dee-2ad9e7729dcc)
 "Tray icon" is checked too?

**Comment by martinrotter** [comment]
Log seems okay, no errors. This must be something specific to your environment.

**Comment by martinrotter** [comment]
This must be some feature of Windows 11, sometimes it hides some tray icons, make sure this is not the case.

**Comment by martinrotter** [comment]
In that case, I have really no idea how the tray icon can disappear, logs show no related warnings/errors.

I also am not able to reproduce the issue anyhow.

**Comment by martinrotter** [comment]
Also, read the statement in the settings window!

"Your os does not support tray icons at the moment".

Which RSS Guard installation file did you exactly downloaded/installed?

**Comment by martinrotter** [comment]
Yes, that is correct installation file. This is weird. If there was any widespread problem, many users would be reporting it...

**Comment by martinrotter** [comment]
I am just not able to reproduce, sorry, if you have any new info, feel free to comeback.
