### ISSUE TITLE
Handling of auto start should be improved

### ISSUE THREAD

**Issue by pmattern** [martinrotter/rssguard#15]
The current practice to handle auto start could be improved in several ways.

Directory `~/.config/autostart/` doesn't get created if it's missing. Checking the box at Settings - General - "Launch RSS Guard..." silently fails then.

`~/.config/autostart/rssguard.desktop` should be a file instead of a link pointing to `/usr/share/applications`.
Several desktop environments come with tools which allow for toggling the auto start of items preexisting in `$XDG_CONFIG_HOME/autostart/` by adding key `Hidden`. This basically fails due to permission issues if there's just a symbolic link pointing to `/usr/share/applications`. E. g. "Session and Startup" of Xfce replaces the link with the target file automatically but "LXQt Session Settings" of LXQt silently fails.

It would be better to place a dedicated file in `~/.config/autostart/` instead of using the one from `/usr/share/applications` which is primarily meant to appear in menus.
This would allow for using key `TryExec` which makes a lot of sense in desktop entry files used to auto start applications but which isn't so helpful in files `/usr/share/applications/*.desktop` as a failure makes the topic disappear from the menus at least on LXQt and Xfce.
A dedicated file could look like this
```
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Name=RSS Guard
TryExec=rssguard
Exec=rssguard
Hidden=false
X-GNOME-Autostart-Delay=15
X-LXQt-Need-Tray=true
```

Topic Settings - General - "Launch RSS Guard..." is checking whether or not `~/.config/autostart/rssguard.desktop` exists only but doesn't consider key `Hidden`.
This is obviously interfering with the tools mentioned above and could make for a confusing UX. Not sure what's the best way to deal with this, though. The box should certainly appear unchecked when `Hidden=true` is set. But that aside I guess no further changes are needed. In particular unchecking the box should still trigger the removal of `~/.config/autostart/rssguard.desktop` when it was rightly checked before.

**Comment by martinrotter** [comment]
Just thinking about this.

Is it even possible to specify some kind of timeout in that desktop file which would be placed in autostart folder? That would help me to workaround some bugs which exists e.g. in MATE environment.

**Comment by martinrotter** [comment]
So you basically propose:
* Properly use environment variable `$XDG_CONFIG_HOME`. If not set, use `/home/.config`.
* Create `autostart` folder if it does not exist.
* When customized desktop file has attribute `Hidden` set to `true` or `false`, respect it in the settings UI too.
* Do not create link to existing desktop file but create dedicated and customized desktop file.
* User UNchecks "Launch RSS Guard..." -> desktop file gets removed (same behavior as is now).
* User CHECKS "Launch RSS Guard..."

**Comment by pmattern** [comment]
*ad timeout*

To my knowledge and after having another look at the [relevant section](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s05.html) of the specification a generic key to delay the auto start of applications doesn't exist. I mean, this is the very reason why LXQt introduced the said `X-LXQt-Need-Tray`. And while I don't know GNOME even remotely well I dare say their `X-GNOME-Autostart-Delay=15` is serving the same purpose.
IMO the solution should be to encourage the developers of other desktop environments to introduce similar custom keys when needed or maybe use the ones introduced by GNOME and LXQt. This seems rather desirable in particular as RSS Guard is by far not the only application suffering from such problems.

*ad "basically propose"*

> Properly use environment variable $XDG_CONFIG_HOME. [...]

I do not know to what degree the use of those environment variables like `$XDG_CONFIG_HOME` is still widespread these days. The XDG project is rather dead which e. g. gives us lots of troubles in LXQt.
That aside what you write seems like the right thing to do (except it must be `/home/<user>/.config` which is probably a typo only).
But note that I was not seeing any issues regarding the selection of the path to save the auto start stuff. So I was a bit surprised to see you state this as a proposal I had made.

To sum up my proposals: Check whether the target directory exists and create it if needed instead of failing silently. Don't set a symbolic link but use a regular file (which ever this will be). Don't use the file from `/usr/share/applications/` which is meant to appear in menus but a custom one used for auto start only. Consider key `Hidden` which may have been added and/or modified by tools of desktop environments.

Regarding the latter I wasn't sure what's the best way to deal with it (in fact looking into RSS Guard a bit deeper made me get aware of the problem the first time and realize it's affecting several other applications as well). But meanwhile I think the policy should be something like "consider but overwrite".
When the settings dialogue gets launched it should not check for the mere existence of `~/.config/autostart/rssgaurd.desktop` (or what ever) only but check key `Hidden` as well and set the checkbox accordingly.
If the box is unchecked and gets checked the file should either be created if missing or key `Hidden` as the second possible reason to have it unchecked should be set to `false`. The desktop tools should be able to deal with this.
If the box is checked and gets unchecked the file should be removed as right now. Of course it could be considered to set `Hidden=true` as well but by removing any changes to the file get implemented automatically which doesn't happen when only `Hidden` is toggled.

**Comment by martinrotter** [comment]
OK, I did couple of changes, but those are not yet tested. I will test tonight on my home Linux machine. Here is the pointlist:

* Extra desktop file (one you proposed) was added for packaging, location `<prefix>/share/rssguard/autostart/rssguard.desktop.autostart`.
* `XDG_CONFIG_HOME` variable is respected if not empty.
* On autostart activation, existing file `XDG_CONFIG_HOME/autostart/rssguard.desktop` is deleted and replaced by our original file `<prefix>/share/rssguard/autostart/rssguard.desktop.autostart`.
* On autostart DEactivation, file `XDG_CONFIG_HOME/autostart/rssguard.desktop` is deleted.
* Autostart is active when file `XDG_CONFIG_HOME/autostart/rssguard.desktop` is present and its `Hidden` attribute is either non-existent or equals to value `false`. In other cases, autostart is not active.

**Comment by pmattern** [comment]
Directory `~/.config/autostart` does not get created if missing here, the checkbox at Settings - General is empty again the next time the dialogue is opened. Seen in an LXQt session where all relevant variables are set as expected
```
$ env | sort
[...]
XDG_CACHE_HOME=/home/peter/.cache
XDG_CONFIG_DIRS=/etc/xdg
XDG_CONFIG_HOME=/home/peter/.config
XDG_CURRENT_DESKTOP=LXQt
XDG_DATA_DIRS=/home/peter/.local/share:/usr/local/share:/usr/share
XDG_DATA_HOME=/home/peter/.local/share
XDG_MENU_PREFIX=lxqt-
XDG_RUNTIME_DIR=/run/user/1002
```

Everything else we've discussed in this issue is working as expected once directory `~/.config/autostart/` was created manually.

If you make changes to fix this it would be good if you added a regular line break at the last line of `./resources/desktop/rssguard.desktop.autostart`.

**Comment by pmattern** [comment]
Tag `partially-fixed` could be replaced by `fixed` again.
(Just saying as I happened to stumble upon this and was wondering whether you use the tags for ToDo lists,statistics  or stuff like that.)

**Comment by martinrotter** [comment]
I do not use it for stats much. I just like to know what was my opinion on the issue. So I use it like kind of helper technique. Kind of TO-DO, yes.
