### ISSUE TITLE
[BUG]: duplicate article filter assignment

### ISSUE THREAD

**Issue by seventyiris83** [martinrotter/rssguard#1503]
### in a group of feeds where a filter (let's call it filter 1) is partially applied, rss guard re-applies filter 1 to the feeds that already had the filter applied when ticking the feed group (with the intention of applying filter 1 to all the feeds it wasn't applied to:

**part 1: i tick the "Technology" feed group, resulting in all the feeds in the group to have "Test filter 1" applied **once**, no problem:**

![1](https://github.com/user-attachments/assets/8f518dae-7cd6-4362-8023-364ee1a8586f)
![2](https://github.com/user-attachments/assets/371e1d53-8881-40e7-ac2c-dd06c033db4c)

**part 2: i add a new feed, "It's FOSS 2" to the "Technology" feed group, now "Test filter 1" is partially applied to the "Technology" group as expected:**

![3](https://github.com/user-attachments/assets/7622cff2-b473-417e-b135-932bb8730b02)

**part 3: i tick the "Technology" feed group with the intention of applying "Test filter 1" to "It's FOSS 2", it gets applied as expected:**

![4](https://github.com/user-attachments/assets/4595f5b5-542e-4847-b9b7-7ca589b96256)
![5](https://github.com/user-attachments/assets/a578b1ce-fc4a-49d2-aa70-e66380cdde19)

**part 4, the reason of this ticket: all the other feeds that previously had "Test fillter 1" applied to them now have a duplicate of it applied to them:**

![6](https://github.com/user-attachments/assets/4b3d7c1e-ae89-4408-a8a4-ebe619823936)
![7](https://github.com/user-attachments/assets/782d4d48-27cf-4faa-9d28-74393ce3b745)

**this only happens when ticket a feed group to quickly apply a filter to feeds in the group that don't have it applied. it does not happen when manually ticket a feed**

following this logic, feeds could potentially have an unlimited amount of duplicate of feeds if repeated

### How to reproduce the bug?

1. have a feed group
2. create a filter
3. apply the filter to a feed group
4. add a new feed to the same feed group
5. tick the feed group to apply the filter to the new feed
6. see that all the feeds that were there before the newly added one now have the same filter applied twice

### What was the expected result?

only the new feed would have the article filter applied

### What actually happened?

the new feed has the filter applied to it but all the previously existing feeds in the feed group also have the filter re-applied to them, resulting in duplicates

### Debug log

N/A

### Operating system and version

* OS: Windows 10 Pro
* RSS Guard version: 4.7.2 Lite

**Comment by martinrotter** [comment]
You were right, fixed.
