### ISSUE TITLE
[BUG]: image resolution issue in article viewer on lite version

### ISSUE THREAD

**Issue by seventyiris83** [martinrotter/rssguard#1509]
### Brief description of the issue

images and attachements in articles get downscaled until rss guard reboot after shrinking article viewer:

https://github.com/user-attachments/assets/dd133d3c-b129-47e1-867a-4444b84dfbe4

it is related to image and attachement wrapping

as i said the image quality gets restored when rss guard is restarted so this is not a permanent change

### How to reproduce the bug?

1. have latest lite build installed
2. in "Articles" settings increase the height limit of all pictures to 600px to clearly see the problem
3. widen the article viewer size to have image attachements fully fit it
4. open an article that has image attachements (feed used in the video showing the problem is "It's FOSS")
5. shrink the article viewer and widen it back to its original size
6. see the resolution of the images and attachements has been severly decreased

### What was the expected result?

i was expecting the quality of the images to be unaffected by wrapping when shrinking the article viewer window size

### What actually happened?

the quality of images and attachements severly decreased

### Debug log

N/A

### Operating system and version

* OS: Windows 10 Pro
* RSS Guard version: 4.7.3 Lite

**Comment by martinrotter** [comment]
4e698c983

Wait until devbuild compiles, test and report back.

**Comment by seventyiris83** [comment]
https://github.com/user-attachments/assets/cc7182d0-5463-4c39-b075-f8486a90495f

the quality is no longer decrease-only, as it will re-increase as the article viewer window size is re-increased 😄 

however the quality decreasing on non-wrapping images and attachements (no height limit set) is a [different issue](https://github.com/martinrotter/rssguard/issues/1513), closing this one.
