### ISSUE TITLE
[FR]: Hide/show the display of read articles in the window

### ISSUE THREAD

**Issue by leonsoft-kras** [martinrotter/rssguard#1515]
### Brief description of the feature request

How to hide/show the display of read articles in the window, or move them automatically to the trash?

For example, there is an option "Show unread items only" feeds.

**Comment by martinrotter** [comment]
There is article list filtering button in article toolbar.

**Comment by martinrotter** [comment]
![rssguard_KiZrUVBNve](https://github.com/user-attachments/assets/8ec2a4a2-891e-426a-a325-638ace792822)

**Comment by leonsoft-kras** [comment]
Thank you. It works.
I had a hard time finding it. Before that I looked through all possible menus. Access to the function is certainly not obvious. In theory it should be in the main menu.
