### ISSUE TITLE
Bazqux Support?

### ISSUE THREAD

**Issue by SMylk** [martinrotter/rssguard#152]
Is there any plan for supporting Bazqux?
https://bazqux.com

**Comment by martinrotter** [comment]
Hello @SMylk.
Questions:
1. Is Bazqux free/OSS?
2. Do they have free accounts for developers? (I need account to test/develop the plugin.)
3. How many users does Bazqux have? Is it well-know online feed reader?

**Comment by vshabanov** [comment]
1. No, it's paid app with 30 days free trial. Although I'm planning to open source it
2. You could start a free trial and then mail your user ID from bazqux.com/whoami to hello@bazqux.com and I'll mark your account as forever free
3. It's quite small reader with few thousands paying users.

BazQux has Google Reader API. So if you already support The Old Reader or InoReader adding support to BazQux should be quite easy.

**Comment by martinrotter** [comment]
I will postpone and close this, once you feel that the interest in RSS Guard plugin is HIGH, let me know. :)
