### ISSUE TITLE
[FR]: Toggle Read/Unread by Clicking Green Dot

### ISSUE THREAD

**Issue by Nekkowe** [martinrotter/rssguard#1521]
### Toggling Read/Unread by Clicking the Green Dot Indicator

In other software like Thunderbird or QuiteRSS, the green dot that serves as the unread indicator can be clicked to immediately toggle an entry between "read" and "unread".

It would be wonderful if RSS Guard followed that convention, too - especially since the "Important" column already works that way! (And for both these columns, it'd be incredibly nice to have a little "inactive" placeholder icon, as in the below examples).

It's the first thing I found myself tripping over when trying RSS Guard out earlier today (gotta move on from the long-unmaintained QuiteRSS at *some* point, after all!)

QuiteRSS:
![image](https://github.com/user-attachments/assets/a1481aec-1a29-48ea-8c6a-d24ceb911ef9)

Thunderbird:
![image](https://github.com/user-attachments/assets/0287fd28-01f8-4790-8c0e-f63cdf9c29e7)

(P.S.: Incidentally, the only other thing I tripped over was taking a while to find the "View -> Switch Layout" setting. At first, I was searching for that under "Tools -> Settings -> User Interface", and when I couldn't find it there, I got really worried that there might not be a way to move the preview pane to the side. But that's getting off track!)

**Comment by Nekkowe** [comment]
Oh, it looks like I'm not the only one who's missing this functionality - it also came up in [Travis Cardwell's](https://www.extrema.is/blog/2024/06/28/rss-part-20-rssguard-revisited) experience report with RSS Guard:
>  In other feed readers, marking items read/unread is done by clicking on the read/unread dot, but that is not supported in this application.

**Comment by Ac314** [comment]
You can switch article read/unread from the article itself:
![1](https://github.com/user-attachments/assets/1176068e-8875-40bf-8716-88b6073834e8)
But ability to switch it from the article list could be nice too, no objections.

**Comment by martinrotter** [comment]
Yes, I will implement this to work the same way starred column does.

**Comment by Nekkowe** [comment]
Thank you very much!

**Comment by martinrotter** [comment]
Fixed by 56d814481.

Wait until the change compiles, then test via devbuild and report back.

**Comment by Nekkowe** [comment]
Works wonderfully in the dev build, thank you!
