### ISSUE TITLE
Article list should have alternating background color for lines for better readability

### ISSUE THREAD

**Issue by user1891** [martinrotter/rssguard#1524]
### Brief description of the feature request

Article list should have alternating background color for lines for better readability.

Example from Evernote desktop:
![screenshot_2024-10-18T12_12_57](https://github.com/user-attachments/assets/37ce584b-2b92-446f-b3db-78a3ab24d64d)

**Comment by martinrotter** [comment]
![image](https://github.com/user-attachments/assets/18acff1a-186f-4af9-ac27-d4c8a001eec1)
