### ISSUE TITLE
[FR]: Parse Reddit URLs into RSS feeds

### ISSUE THREAD

**Issue by shoulders** [martinrotter/rssguard#1530]
### Brief description of the feature request

I would like to easily add **Reddit** feeds to RSSGuard by copying a standard Reddit URL and then when RSSGuard detects this Reddit URL it will convert it to a RSS feed URL which will then follow the current import/parse procedure for normal RSS feeds.

Using this example Reddit feed you can see the original link and then the modified one which is an RSS feed.

`https://www.reddit.com/r/HomeNetworking/`

-->

`https://www.reddit.com/r/HomeNetworking.rss`

**Links**
- https://www.howtogeek.com/320264/how-to-get-an-rss-feed-for-any-subreddit/

**My RSSGuard Version**

<h4>RSS Guard</h4><b>Version:</b> 4.7.3 (built on Windows/AMD64)<br/><b>Revision:</b> a4e20486b<br/><b>Build date:</b> 26/07/2024 04:16<br/><b>OS:</b> Windows 10 Version 22H2<br/><b>Qt:</b> 6.7.2 (compiled against 6.7.2)

**Comment by martinrotter** [comment]
![image](https://github.com/user-attachments/assets/f0f18f8c-4048-4b01-86e7-0929e15b1b41)

275a34e01

**Comment by shoulders** [comment]
awesome, this will be a welcomed feature. 😄

**Comment by Twig6943** [comment]
@martinrotter this seems to be broken? (Clicked `Discover` multiple times, no results)
![Image](https://github.com/user-attachments/assets/24bec747-3b6a-4706-8d29-37d7e85cd01f)
