### ISSUE TITLE
[FR]: Parse YouTube URLs into RSS feeds

### ISSUE THREAD

**Issue by shoulders** [martinrotter/rssguard#1532]
### Brief description of the feature request

I would like to easily add YouTube feeds to RSSGuard by copying a standard YouTube URL and then when RSSGuard detects this YouTube URL it will convert it to a RSS feed URL which will then follow the current import/parse procedure for normal RSS feeds.

The way you get a YouTube RSS feed is as follows:

- Navigate to a YouTube page i.e. https://www.youtube.com/@syntaxfm
- View Source and browse for the `browser_id` which will look like `{"key":"browse_id","value":"UCyU5wkjgQYGRB0hIHMwm2Sg"}`
- The place holder url is
    `https://www.youtube.com/feeds/videos.xml?channel_id=CHANNELID`
- Swap `CHANNELID` for the `browser_id` you got earlier giving 
    `https://www.youtube.com/feeds/videos.xml?channel_id=UCyU5wkjgQYGRB0hIHMwm2Sg`
- This URL can then be used as any RSS feed for adding into RSS Guard.

**Links**

https://www.thewindowsclub.com/how-to-get-youtube-channel-rss-feed

**My RSSGuard Version**

<h4>RSS Guard</h4><b>Version:</b> 4.7.3 (built on Windows/AMD64)<br/><b>Revision:</b> a4e20486b<br/><b>Build date:</b> 26/07/2024 04:16<br/><b>OS:</b> Windows 10 Version 22H2<br/><b>Qt:</b> 6.7.2 (compiled against 6.7.2)

**Comment by martinrotter** [comment]
fb5ff84ba

![image](https://github.com/user-attachments/assets/9b7916fe-33e7-4866-aceb-56065d010856)

Youtube detection was already there, but I enhanced it as per your suggestion.

Now "Discover feeds" feature works with youtube well. BUT. Before you do anything, make sure to open https://www.youtube.com in RSS Guard internal new tab browser and accept cookies warning first, then all should work with the above fix.

**Comment by shoulders** [comment]
thanks
