### ISSUE TITLE
[3.5.1] - Bug: PVPonline articles can't be opened in external browser...?

### ISSUE THREAD

**Issue by danowar2k** [martinrotter/rssguard#154]
#### Brief description of the issue.

I use mostly the keyboard for choosing and opening articles in my default external browser (Chrome).
So I browse the feed list, select a feed that has new articles indicated, then look at the new headlines in the article list. If any of them interest me, I tab to the article list and then move to the desired articles using the arrow keys. When I reach an interesting article, I press ENTER to "open the selected article in the external browser".

When it works, the focus is shifted to the external browser and a new tab is created containing the article. Then I alt-tab back to RSSGuard and select other articles to open.

 However, this doesn't seem to work with the following feed: http://pvponline.com/feed . I press ENTER and nothing happens.

Any ideas?

#### How to reproduce the bug?

1. Add the feed http://pvponline.com/feed to your RSSguard instance.
2. Try to open an article from that feed in the external browser.

#### What is the expected result?

It should open the pvponline article in the external browser.

#### What actually happened?

Nothing.

#### Other information (logs, see Wiki)

[log.txt](https://github.com/martinrotter/rssguard/files/1402968/log.txt)

**Comment by martinrotter** [comment]
Fixed, the feed for some reason returns newlines and tabs in its "url" field, fix strips those characters out.

**Comment by danowar2k** [comment]
Wow, thanks for the quick fix.
