### ISSUE TITLE
FR: Detect OS when using the update function

### ISSUE THREAD

**Issue by danowar2k** [martinrotter/rssguard#155]
#### Brief description of the issue.

When I use the update function, RSSGuard seems unable to detect my OS so that it could provide me the appropriate installers and hide unnecessary files from me. I'm using Windows 7 64 Bit and get a list containing MacOS packages, for example.

#### How to reproduce the bug?

1. Check for updates.
2. See the list containing packages.

#### What is the expected result?

I should be presented with files appropriate for my OS.

#### What actually happened?

I see packages for every OS.

**Comment by martinrotter** [comment]
Can I see screenshot?

**Comment by danowar2k** [comment]
Yeah, of course. I am on 3.5.1, though. So as long as there are no new releases, I can't provide the screenshot.

(Although at the moment it says "Available version: 3.5.3-test", but there are no downloads in the list).
