### ISSUE TITLE
[BUG]: Cannot read https://openai.com/news/rss.xml

### ISSUE THREAD

**Issue by pemo11** [martinrotter/rssguard#1555]
### Brief description of the issue

I cannot import https://openai.com/news/rss.xml - the feed content is shown in the browser but I cannot make it appear in RSSGuard.

### How to reproduce the bug?

1. Right click on my account and >Neuen Feed hinzufügen
2. Paste https://openai.com/news/rss.xml
3. Entdecke!

No feed is found

### What was the expected result?

The feed should be available for selection

### What actually happened?

Nothing

### Debug log

time="     0.056" type="debug" -> core: Initializing settings in 'C:\Rss Guard\data4\config\config.ini' (portable way).
time="     0.057" type="debug" -> core: Starting to load active localization. Desired localization is 'de_DE'.
time="     0.060" type="debug" -> core: Application localization 'de_DE' loaded successfully, specifically sublocalization 'de' was loaded.
time="     0.071" type="debug" -> core: Qt localization 'de' loaded successfully.
time="     0.131" type="debug" -> database: File-based SQLite database connection 'DatabaseFactory' to file 'C:\Rss Guard\data4\database\database.db' seems to be established.
time="     0.133" type="debug" -> database: File-based SQLite database has version '8'.
time="     0.138" type="debug" -> gui: Available icon theme paths: QList(:/icons, :/graphics, C:\Rss Guard\data4\icons, C:/Rss Guard\icons)
time="     0.140" type="debug" -> gui: Installed icon themes are: '', 'Breeze', 'Breeze Dark', 'Faenza', 'Numix'
time="     0.140" type="debug" -> gui: Loading icon theme 'Breeze'.
time="     0.141" type="debug" -> gui: Found path of base skin: ':\skins\nudus-base'.
time="     0.142" type="debug" -> gui: Base file ':\skins\nudus-base\html_wrapper.html' exists, using it for the skin.
time="     0.142" type="debug" -> gui: Local file ':\skins\nudus-light\lite_html_style.css' exists, using it for the skin.
time="     0.143" type="debug" -> gui: Base file ':\skins\nudus-base\lite_html_enclosure_image.html' exists, using it for the skin.
time="     0.144" type="debug" -> gui: Base file ':\skins\nudus-base\lite_html_single_message.html' exists, using it for the skin.
time="     0.145" type="debug" -> gui: Base file ':\skins\nudus-base\lite_html_enclosure_every.html' exists, using it for the skin.
time="     0.148" type="debug" -> gui: Local file ':\skins\nudus-light\qt_style.qss' exists, using it for the skin.
time="     0.150" type="debug" -> gui: Base file ':\skins\nudus-base\html_adblocked.html' exists, using it for the skin.
time="     0.150" type="debug" -> gui: OS defines color scheme: 'Qt::ColorScheme::Light'.
time="     0.151" type="debug" -> gui: Setting style: 'windowsvista'.
time="     0.156" type="debug" -> gui: Skin 'nudus-light' loaded. Lite: 'true'.
time="     0.157" type="debug" -> network: Disabling application-wide proxy completely.
time="     0.158" type="debug" -> core: Platform: 'windows'.
time="     0.158" type="debug" -> core: SQLite version: '3.42.0'.
time="     0.179" type="debug" -> core: OpenSSL version: 'OpenSSL 3.0.15 3 Sep 2024'.
time="     0.180" type="debug" -> core: OpenSSL supported: 'true'.
time="     0.180" type="debug" -> core: Global thread pool has 8 threads.
time="     0.181" type="debug" -> core: Instantiated class  'Application'.
time="     0.188" type="warning" -> core: Another instance of the application is already running. Notifying it.
time="     0.188" type="debug" -> core: Destroying Application instance.
time="     0.189" type="debug" -> core: Destroying Mutex instance.
time="     0.206" type="debug" -> gui: Destroying IconFactory instance.
time="     0.059" type="debug" -> core: Initializing settings in 'C:\Rss Guard\data4\config\config.ini' (portable way).
time="     0.060" type="debug" -> core: Starting to load active localization. Desired localization is 'de_DE'.
time="     0.063" type="debug" -> core: Application localization 'de_DE' loaded successfully, specifically sublocalization 'de' was loaded.
time="     0.067" type="debug" -> core: Qt localization 'de' loaded successfully.
time="     0.092" type="debug" -> database: File-based SQLite database connection 'DatabaseFactory' to file 'C:\Rss Guard\data4\database\database.db' seems to be established.
time="     0.093" type="debug" -> database: File-based SQLite database has version '8'.
time="     0.097" type="debug" -> gui: Available icon theme paths: QList(:/icons, :/graphics, C:\Rss Guard\data4\icons, C:/Rss Guard\icons)
time="     0.099" type="debug" -> gui: Installed icon themes are: '', 'Breeze', 'Breeze Dark', 'Faenza', 'Numix'
time="     0.100" type="debug" -> gui: Loading icon theme 'Breeze'.
time="     0.101" type="debug" -> gui: Found path of base skin: ':\skins\nudus-base'.
time="     0.102" type="debug" -> gui: Base file ':\skins\nudus-base\html_wrapper.html' exists, using it for the skin.
time="     0.102" type="debug" -> gui: Local file ':\skins\nudus-light\lite_html_style.css' exists, using it for the skin.
time="     0.103" type="debug" -> gui: Base file ':\skins\nudus-base\lite_html_enclosure_image.html' exists, using it for the skin.
time="     0.107" type="debug" -> gui: Base file ':\skins\nudus-base\lite_html_single_message.html' exists, using it for the skin.
time="     0.108" type="debug" -> gui: Base file ':\skins\nudus-base\lite_html_enclosure_every.html' exists, using it for the skin.
time="     0.110" type="debug" -> gui: Local file ':\skins\nudus-light\qt_style.qss' exists, using it for the skin.
time="     0.111" type="debug" -> gui: Base file ':\skins\nudus-base\html_adblocked.html' exists, using it for the skin.
time="     0.111" type="debug" -> gui: OS defines color scheme: 'Qt::ColorScheme::Light'.
time="     0.112" type="debug" -> gui: Setting style: 'windowsvista'.
time="     0.114" type="debug" -> gui: Skin 'nudus-light' loaded. Lite: 'true'.
time="     0.115" type="debug" -> network: Disabling application-wide proxy completely.
time="     0.116" type="debug" -> core: Platform: 'windows'.
time="     0.116" type="debug" -> core: SQLite version: '3.42.0'.
time="     0.153" type="debug" -> core: OpenSSL version: 'OpenSSL 3.0.15 3 Sep 2024'.
time="     0.154" type="debug" -> core: OpenSSL supported: 'true'.
time="     0.155" type="debug" -> core: Global thread pool has 8 threads.
time="     0.155" type="debug" -> core: Instantiated class  'Application'.
time="     0.157" type="warning" -> core: Another instance of the application is already running. Notifying it.
time="     0.157" type="debug" -> core: Destroying Application instance.
time="     0.158" type="debug" -> core: Destroying Mutex instance.
time="     0.190" type="debug" -> gui: Destroying IconFactory instance.

### Operating system and version

* OS: Windows 11
* RSS Guard version: 4.7.4

**Comment by martinrotter** [comment]
Works fine here.

https://openai.com/news/rss.xml

**Comment by martinrotter** [comment]
Could be, yes.

**Comment by pemo11** [comment]
Setting HTTP/2 was succesfull.

Now I can read too whats going on at openAI.
