### ISSUE TITLE
[BUG]: Javascript filters no longer take affect on feeds

### ISSUE THREAD

**Issue by linlinxza** [martinrotter/rssguard#1559]
### Brief description of the issue

Updated to version 4.8.0 and started the application. Filters no longer take affect on retrieved feeds.

### How to reproduce the bug?

1. Update
2. Set a Javascript filter.
3. Retrieve feeds

### What was the expected result?

Feeds should be filtered.

### What actually happened?

Whitelist and blacklist filters are ignored

### Debug log

?

### Operating system and version

* OS: Ubuntu (KDE Neon)
* RSS Guard version: 4.8.0

**Comment by linlinxza** [comment]
EDIT: It's weird. But after disabling the filters and closing the application, and then enabling the filters again, seemed to fix the issue (I think). I'll report should I experience my feeds not being filtered again.

**Comment by linlinxza** [comment]
Well, had to downgrade to 4.7.4 as the filters I have set don't work right in 4.8.0.

**Comment by martinrotter** [comment]
YES! Sorry I made a mistake and some untested code got into release, will fix soon.
