### ISSUE TITLE
rssguard is broken when compiled with -ffat-lto-objects and -flto=16

### ISSUE THREAD

**Issue by soredake** [martinrotter/rssguard#156]
#### How to reproduce the bug?

1. compile rssguard with `-ffat-lto-objects` and `-flto=16`
2. open rssguard
3. rssguard show's NOTHING
![04-11-2017_16 10 08](https://user-images.githubusercontent.com/5204968/32406116-65c485ea-c16a-11e7-81bd-72d587de748f.png)

#### What is the expected result?

Working rssguard.

#### What actually happened?

Nothing is showed. 

#### Other information (logs, see Wiki)

Gentoo stable amd64
rssguard from git

Compiling without `-flto` fixes rssguard. Also, compiling with lto possible only with `-ffat-lto-objects` due to https://bugreports.qt.io/browse/QTBUG-41301

**Comment by martinrotter** [comment]
Please, provide log with when bug is present.

**Comment by soredake** [comment]
Ok, i'll compile it today.

**Comment by martinrotter** [comment]
It seems that qt resource system has some trouble with `-flto`, I will investigate tomorrow. Why do you need `-flto`?

**Comment by soredake** [comment]
https://github.com/InBetweenNames/gentooLTO

**Comment by martinrotter** [comment]
I see. Well, I kind of reproduced the problem, but it seems that I get SIGSEGV in Qt code (not in RSS Guard code). According to your logs, it seems that on your side it also crashes in Qt code.

**Comment by martinrotter** [comment]
Can you try to pass `CONFIG += ltcg` to `qmake`? It should pass `-flto` to compiler automatically, but it also does some hacks in background for Qt to work.

https://bugreports.qt.io/browse/QTBUG-42448

**Comment by soredake** [comment]
After recompiling with `ltcg` rssguard works, thanks.
