### ISSUE TITLE
Missing Categories in Feed list

### ISSUE THREAD

**Issue by mulgaBrian** [martinrotter/rssguard#1560]
### Brief description of the issue

On a new install on windows 11 there is No Regex queries, Important articles or Unread articles in the feed list

### How to reproduce the bug?

1. Install on Windows 11

### What was the expected result?

My Windows 10 install has these categories.
![Graphic_20_12_2024 12_19_38 PM](https://github.com/user-attachments/assets/80b5b58e-14bb-4ca2-8b1c-50a10a2fea18)
![0001](https://github.com/user-attachments/assets/471f4040-e5c7-4459-b3b8-bd3160f58a54)

### What actually happened?

No Unread articles category.
No Regex queries

### Debug log

No debug log and application log empty

### Operating system and version

* OS: Windows 11
* RSS Guard version: 4.7.0 / 4.7.4 / 4.8.0

**Comment by mulgaBrian** [comment]
I had to uninstall RssGuard and delete all it's data then Install 4.2.2 to get a proper install with the missing parts.
4.2.2 was a random selection by me.

**Comment by martinrotter** [comment]
Also, you can enable those advanced items in account edit dialog.

![image](https://github.com/user-attachments/assets/94cdb071-c9b5-4dff-b0ba-17f6fddbc9b1)
