### ISSUE TITLE
Settings: button "Apply" would be nice to have

### ISSUE THREAD

**Issue by pmattern** [martinrotter/rssguard#16]
It would be very nice if dialogue "Settings" featured the usual button "Apply". That is, a button which applies the current settings without closing the dialogue.
Button "OK" involves closing the dialogue which isn't really convenient, in particular when using RSS Guard for the first time and exploring its various options.

**Comment by martinrotter** [comment]
Problem is, that settings infrastructure currently does not provide any way to tell whether currently selected options are saved and if there is some option changed. Thus, when user would hit "Apply" and then "OK", settings would be actually saved twice. So, basically, it would work, but internally it is not ideal.

**Comment by pmattern** [comment]
Would saving twice yield any manifest problem then? Otherwise I'd assume the advantage in practice outweighs the not so nice technical implementation.

**Comment by martinrotter** [comment]
No, it would not produce any bugs. I will add "Apply" and tweak the underlying implementation logic in the future.

**Comment by xmstspider** [comment]
Hi Martin,

Just to add an idea how this usually works.
An user changes some options:
A. If he/she presses Apply, the settings are saved, the OK then simply closes the dialog
B. If he/she presses OK first, a new dialog appears asking for saving or discarding the changes made (may have Apply/Discard buttons). 
C. If he/she presses Cancel, nothing will change (as usual)

**Comment by martinrotter** [comment]
@xmstspider Thanks for clarification.

**Comment by pmattern** [comment]
> Just to add an idea how this *usually* works.

Hm, are you sure?
Personally, I'm only aware of behaviour like this if it comes to closing modified documents.
But I've never seen any such thing regarding settings dialogues. The only behaviour I'm aware of is buttons "OK" are saving and closing the dialogue in question without further query (and buttons "Apply" as well as "Cancel" of course behaving as you stated). And tbh. I think this makes more sense.

**Comment by xmstspider** [comment]
Yes, at least some settings centers like KDE Settings or similar in IDEs. They ask whenever you try to close the window or change the tab. It is more dummy-proof as you won't lose the changes when accidentally clicks on different tab/item/whatever...

But that's just an idea, it's up to you how do you want it ;-)

**Comment by pmattern** [comment]
It's true that System Settings of KDE are behaving that way. But these are a different kind of beast.
Just had another look: Buttons "OK" in the settings dialogues of LibreOffice, QupZilla, Otter Browser, FatRat, Gimp and SMPlayer as well as in the account settings of Thunderbird all save the current settings and close the dialogue without any querying. On the other hand I couldn't find a single application where hitting "OK" triggers some query. (A lot of applications are implementing some apply-on-change policy which is pretty stupid, IMO, and irrelevant for what we're discussing here anyway.)

So while this is certainly a matter of taste I really don't think the proposed behaviour can be called usual as far as settings dialogues of applications are concerned.

**Comment by martinrotter** [comment]
> Yes, at least some settings centers like KDE Settings or similar in IDEs
Exactly, I remembered KDE when reading your lines. It works like you said.

But on Windows, on the other hand, almost no SW I saw behaves like 
> B. If he/she presses OK first, a new dialog appears asking for saving or discarding the changes made (may have Apply/Discard buttons).

I would go more standard way:
* `OK` -> settings are saved (if changed), dialog is closed.
* `APPLY` -> settings are save (if changed).

**Comment by xmstspider** [comment]
No problem, it was just an idea :-)

**Comment by martinrotter** [comment]
Will keep this as main feature for 3.3.3, which will be just bug fix release otherwise.

**Comment by pmattern** [comment]
Works as expected, thanks for implementing.

Changing the language at Settings - Language doesn't get applied by hitting `Apply` but restarting RSS Guard only.
This is absolutely normal behaviour. But would a little popup informing users possibly make sense?

**Comment by martinrotter** [comment]
> Changing the language at Settings - Language doesn't get applied by hitting Apply but restarting RSS Guard only.

Yes the "restart warning" should popup, but maybe I missed it when transitioning the code to new approach. Will fix.
