### ISSUE TITLE
Bug (only in development build?)

### ISSUE THREAD

**Issue by danowar2k** [martinrotter/rssguard#161]
#### Brief description of the issue.

I downloaded this dev build:
https://transfer.sh/SThn2/rssguard-3.5.5-a93c14d-nowebengine-win64.7z
This produced the following bug after starting the program and adding the default feeds.
![bug_lineheight](https://user-images.githubusercontent.com/10991509/32649245-a1785ed4-c5f9-11e7-820b-de8192b2167a.png)

#### How to reproduce the bug?

1. See above.

#### What is the expected result?

The lines should probably be less high.

#### What actually happened?

Way too high line height.

**Comment by martinrotter** [comment]
This may be because all columns in message list are turn on (this was added some versions ago, you can now have many more columns with data displayed). Problem is that some columns (Contents column for example) could contain multi-line data and this is a problem.

Possible solution:
Right-click on column headers -> context menu will show -> disable unneeded columns -> restart RSS Guard.

Let me know if it worked.

**Comment by martinrotter** [comment]
BTW: You can also reorder visible columns by dragging them with your mouse. RSS Guard should remember columns order/position and last sort order.

**Comment by danowar2k** [comment]
The line height returned to normal after removing the column "Inhalt" ("content" probably), quitting and restarting.

Could you resize line height automatically after adding/removing a column?

**Comment by danowar2k** [comment]
Also the content colum produces the effect, but never contains any text apart from "...".
If that is always the case, why adjust the line height when that column is displayed?

**Comment by martinrotter** [comment]
> You don't need to quit to adjust the line height at the moment, just change the feed in the list and then return to the old feed. Still, automatic line height adjustment would be cool.

Yes, should be enough.

> If that is always the case, why adjust the line height when that column is displayed?

I will try to fix this.

**Comment by martinrotter** [comment]
BTW you see "..." because the column is too narrow. If you make it wider, you will see the actual RAW contents (HTML most of the time).

**Comment by martinrotter** [comment]
Probably fixed those multi-line wide items.

**Comment by martinrotter** [comment]
Let me know if fix works (latest commit).

**Comment by martinrotter** [comment]
Considering fixed.

**Comment by danowar2k** [comment]
Whoops, sorry, yeah, this was fixed with this.
