### ISSUE TITLE
FR: Context Menu item "Add feed here" and "Add folder here"

### ISSUE THREAD

**Issue by danowar2k** [martinrotter/rssguard#162]
#### Brief description of the issue.

Please consider to add context menu items for better feed organization. At the moment I have to add feeds and folder via the menu (Feeds & Categories->Add new item->Add new category/feed)

It would be much nicer if I could add folders via a context menu item.
- Right click on a feed->Add folder ---> new folder is created at the same level as the feed
- Right click on a folder->Add folder ---> new folder is created inside the selected folder

It would be also much nicer if I could add feeds via a context item.
- Right click on a folder->Add feed ---> new feed is created inside this folder
- Right click on a feed ->Add feed ---> new feed is created at the same level as the selected feed

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/91696750-58637900-eb70-11ea-96cf-d814ac41e6ad.png)

**Comment by danowar2k** [comment]
Thank you!
