### ISSUE TITLE
Development Builds page - better build names

### ISSUE THREAD

**Issue by danowar2k** [martinrotter/rssguard#163]
#### Brief description of the issue.

At the moment on this page
https://github.com/martinrotter/rssguard/wiki/Windows-development-builds

every line contains a link containing "transfer.sh". It would help if it would be more like this:
[3.5.5-noweb-win64 (7z)](https://transfer.sh/LMVZS/rssguard-3.5.5-eb777b9-nowebengine-win64.7z)

The program is always the same and the commit is already in another column. And the file service doesn't really matter, does it?

**Comment by martinrotter** [comment]
Closing this, partially will be solved with #164.
