### ISSUE TITLE
Missing linux links

### ISSUE THREAD

**Issue by Bystroushaak** [martinrotter/rssguard#164]
Links at https://github.com/martinrotter/rssguard/wiki/Linux-development-builds return 404. For example:

* https://transfer.sh/Ugq6Y/rssguard-b158cca-linux64.AppImage

**Comment by martinrotter** [comment]
** Note that download links expire after 14 days. **

But I partially agree, sometimes the Travis build fails and build script does not handle the situation well. For example [here](https://travis-ci.org/martinrotter/rssguard/jobs/300087189#L764). Although the build failed, Travis reports it as successfull which leads to invalid dev build download link. I will (hopefully) fix that.

Always go from bottom of the list, where newest builds are located.

**Comment by Bystroushaak** [comment]
I don't want to sound like an asshole and I can see the info there now that you pointed it, but imho it's really counter-intuitive. It would be a good example in the [Design of everyday things](https://en.wikipedia.org/wiki/The_Design_of_Everyday_Things) - people expect newest information in changelogs at the top.

Also last two links at the bottom don't work (they point to the wiki itself).

And also - what is the point of having links which are expired? It looks to me like a great source of confusion.

**Comment by danowar2k** [comment]
I...think I have to agree there (newest links on top, removing expired links)

I've seen the deployment/build scripts are also in the repo, though, so when time lands in my lap...

**Comment by martinrotter** [comment]
It is now being solved -> https://github.com/martinrotter/rssguard/wiki/Development-builds

List is now common for all platforms and contains only newest build for each of them. Mac OS still to be solved.

**Comment by Bystroushaak** [comment]
Nice.
