### ISSUE TITLE
[3.5.5] Bug : Updating a certain Feed crashed RSSguard

### ISSUE THREAD

**Issue by danowar2k** [martinrotter/rssguard#165]
#### Brief description of the issue.

I added this feed to RSSguard: http://gravelgamedesign.blogspot.com/feeds/posts/default?alt=rss

When I update it, RSSguard crashes.

#### How to reproduce the bug?

1. Add the feed to RSSguard.
2. Update it manually.
3. RSSguard crashes.

**Comment by danowar2k** [comment]
Not that I need the feed, but I thought reporting it would smash another bug.

**Comment by martinrotter** [comment]
Fixed, please check if solved (easy one). Thank you for reporting. If you manage to crash rssguard, do not hesitate to report. :)
