### ISSUE TITLE
exported feeds can't be imported properly in ThunderBird

### ISSUE THREAD

**Issue by craftwar** [martinrotter/rssguard#166]
#### Brief description of the issue.
After importing feeds, thunderbird can't get feeds urls. thunderbird can't parse file properly.
I don't know much about rss but thunderbird can import feeds exported from feed daemon properly.

#### How to reproduce the bug?

1.  export feeds from rssgurad
2.  import it in thunderbird

#### What is the expected result?

thunderbird gets messages.

**Comment by martinrotter** [comment]
Can you share exported file?

**Comment by craftwar** [comment]
https://mega.nz/#!BxlixDpB!soVPLcKXbt3V5_1ZCj6CWRSiZIQ5HeGdWWT0zC2_DCI

**Comment by martinrotter** [comment]
I fixed some typo which could be related to your issue.

https://github.com/martinrotter/rssguard/commit/72f5e07a3aed3cf0bfe4cdefbae18f0a7ae41db7#diff-7695f19493e79d24e9bdc7b4d2f22cbf

It is fixed in [master], can you test if it works? Check wiki on how to obtain latest development RSS Guard builds, you need build 72f5e07a3aed3cf0bfe4cdefbae18f0a7ae41db7 or newer.

**Comment by craftwar** [comment]
structure is fixed, but still no feed url.
https://imgur.com/a/vNd2C

BTW, you don't need upload Qt as submodule. upgrade to VS2017 qt too

use windeployqt, http://doc.qt.io/qt-5/windows-deployment.html

**Comment by craftwar** [comment]
Another UI issue:
If I select existence opml file, file dialog prompt me if I wana overwrite it. But in fact, rssguard doesn't overwrite it when I press yes. I need press ok to really overwrite it.

Suggesttion: remove ok button when export

**Comment by martinrotter** [comment]
FIxed, please re-test with latest dev build https://github.com/martinrotter/rssguard/commit/5d5564b4d16ae80256aff6777b75e0351543ed02

**Comment by martinrotter** [comment]
"Suggesttion: remove ok button when export" - create another bug report for this.
