### ISSUE TITLE
My system freezes after reading some articles in RRS_Guard

### ISSUE THREAD

**Issue by victorhck** [martinrotter/rssguard#168]
#### Brief description of the issue.
My system (openSUSE tumbleweed + Plasma) freeze after reading some items.
I can't restart the system normally. The system doesn't answer even to SysReq R+E+I+S+U+B keys. So It's needed to power off the system with the power off buton.

#### How to reproduce the bug?

1. RSS Guard is in the systray. Click on it
2. Read some items, etc...
3. the system freezes

#### What is the expected result?

system freeze

#### What actually happened?

there's no a way to restart the system, or power off.

**Comment by martinrotter** [comment]
Provide any relevant logs (dmesg,journalctl,rssguard log). I cannot do anything without actually seeing logs and detecting the problem. I use RSS Guard in ArchLinux without any problems.

**Comment by victorhck** [comment]
Yes, you are right! sorry for that...
Where can I find rssguard.log? 
Yesterday I was in i3wm, and read my feeds without any issues... Today in Plasma the same issue...
[journal.txt](https://github.com/martinrotter/rssguard/files/1530717/journal.txt)

**Comment by martinrotter** [comment]
This must be somehow related to KDE itself, journal seems clean.

**Comment by martinrotter** [comment]
RSS Guard outputs debug information to its standard/error output. 

https://github.com/martinrotter/rssguard/wiki/Generating-debug-log-file

**Comment by victorhck** [comment]
I reproduced the issue again and here you have the logs... hope that can be helpful
[log.txt](https://github.com/martinrotter/rssguard/files/1530801/log.txt)

**Comment by martinrotter** [comment]
Can you for sure say that the issue happens only on KDE and not hapenning on i3wm? Do you have any scenario to reliably reproduce the issue?

**Comment by victorhck** [comment]
Sorry for late reply...
I'm using now tinytinyRSS
