### ISSUE TITLE
Duplicate feed items on each update from hentai-foundry.com

### ISSUE THREAD

**Issue by quickwick** [martinrotter/rssguard#169]
#### Brief description of the issue.

Duplicate items created when updating hentai-foundry.com feeds

#### How to reproduce the bug?

1. Add a feed from hentai-foundry website (eg: http://www.hentai-foundry.com/feed/userPictures/username/W-H-Art)
2. Update the feed. It downloads the most recent feed items, up to 25
3. Update the feed again. It downloads another copy of the most recent items

#### What is the expected result?

When the feed is updated, it should only download new items, no duplicates of existing items

#### What actually happened?

A new copy of the most recent items (up to 25) is created on each update

#### Other information (logs, see Wiki)

Is not occurring on any other website feeds, just hentai-foundry.com. Using RSS Guard v3.5.5

I don't know if this was an issue in earlier versions of RSS Guard, I just started using it recently.

**Comment by martinrotter** [comment]
Does issue happen with other feeds too?

**Comment by quickwick** [comment]
No. I have several other feeds from other sites, they are not being duplicated on update. Just the feeds from this site.

**Comment by martinrotter** [comment]
Bug was identified, I will fix hopefully today.

**Comment by martinrotter** [comment]
Fixed, please test and let me know if it works.

IMPORTANT: Clean your RSS Guard database first, ideally start with clean user data.
