### ISSUE TITLE
Suggesttion: remove ok button when export

### ISSUE THREAD

**Issue by craftwar** [martinrotter/rssguard#170]
If I select existence opml file, file dialog prompt me if I wana overwrite it. But in fact, rssguard doesn't overwrite it when I press yes. I need press ok to really overwrite it. This change makes program consistent with most file save dialogues behavior. (at least in windows)

**Comment by martinrotter** [comment]
> If I select existence opml file, file dialog prompt me if I wana overwrite it. But in fact, rssguard doesn't overwrite it when I press yes

Of course, in the top of the dialog, you only select the target file. The dialog is more complex, you have to also select which feeds you want to export and so on.

**Comment by martinrotter** [comment]
So, I tweaked a layout of dialog a bit and renamed buttons, the dialog cannot be simplified without losing functionality, overally use-case is:
1. You select source/target file (import/export).
2. You select which feeds you actually want to import export.
3. You confirm your selection by clicking "Export to file" or "Import from file" button.

**Comment by martinrotter** [comment]
https://github.com/martinrotter/rssguard/commit/a5340cce99f11a8d109cf65175cac9c007e0d98e
