### ISSUE TITLE
Suggestion: improve Qt dll deployment

### ISSUE THREAD

**Issue by craftwar** [martinrotter/rssguard#171]
Although Qt VS2015 dll is ABI compatible with VS2017, upgrade to VS2017 will be better.

You don't need upload Qt as submodule, use windeployqt http://doc.qt.io/qt-5/windows-deployment.html

**Comment by martinrotter** [comment]
RSS Guard is using Qt 5.9.X compiled with VS2017, also attached MSVC runtime dlls should be 2017. I like better control, so I avoid windeployqt and use my own submodule. There is AFAIK nothing wrong with it.

**Comment by craftwar** [comment]
windeployqt will provide VS2017 dlls if you execute Qt VS2017 version windeployqt.

**Comment by martinrotter** [comment]
I deploy all dlls manually. I do not use windeployqt and I currently do not see its real advantage. It deploys unnecessary files for QtWebEngine, for example unneeded translation files.

**Comment by craftwar** [comment]
--no-translations         Skip deployment of translations.

**Comment by martinrotter** [comment]
What if I want only specific translations?
