### ISSUE TITLE
Ability to export/import feeds for all plugins

### ISSUE THREAD

**Issue by jluttine** [martinrotter/rssguard#174]
How do I export feeds? I couldn't find out how to do it..

**Comment by martinrotter** [comment]
Main menu -> Accounts -> (Your account) -> Export/Import feeds

Let me know if it helped.

**Comment by jluttine** [comment]
I only have "Sync in" option there..

**Comment by martinrotter** [comment]
Export/Import of feeds is only available for "Standard RSS/ATOM account". TT-RSS and owncloud or inoreader do not offer that feature yet. :)

**Comment by jluttine** [comment]
Oh, thanks for the info. My ownCloud instance is dead so I only have my list of feeds in rssguard. I was hoping to be able to export it somehow and then import into my new RSS server, probably TT-RSS.

**Comment by martinrotter** [comment]
Oh on that case it might be best to open RSS GUard's database file in some SQLITE3 DB file browser and get feed's list there (it is in separate table).

I have good experience with SqliteStudio for example. I also think about adding export/import for other plugins and make the feature more "transparent" and easier to use for plugins. :)

**Comment by jluttine** [comment]
Ok! Where are these feed URLs? I looked at table Feeds and all feeds had URL empty. I also looked at other tables and couldn't find feed URLs anywhere. Only post URLs, but those don't point to the feed but to the post URL.

**Comment by jluttine** [comment]
Or RSS Guard doesn't have feed URLs for feeds it syncs from other aggregator?

**Comment by martinrotter** [comment]
Yes, you are correct, RSS Guard does not usually store feed URLs for "synced" accounts (Nextcloud, TT-RSS, ...), because it does not need them.

**Comment by danrobi11** [comment]
Cant import feedlist. What im doing wrong? Thanks!
![cant import feedlist](https://user-images.githubusercontent.com/48020114/66530774-3a63d480-ead7-11e9-8dbc-1ace8360944c.png)

**Comment by martinrotter** [comment]
> Cant import feedlist. What im doing wrong? Thanks!
> ![cant import feedlist](https://user-images.githubusercontent.com/48020114/66530774-3a63d480-ead7-11e9-8dbc-1ace8360944c.png)

Please, create separate bug report for your issue and post OPML file which triggers the bug. Thank you.

**Comment by martinrotter** [comment]
Import/export of OPML files is not supported by any of supported online services, therefore it cannot be added to RSS Guard anyway. :)
