### ISSUE TITLE
Unwelcome welcome notification

### ISSUE THREAD

**Issue by aesy** [martinrotter/rssguard#176]
#### Brief description of the issue.

A welcome notification is shown every time the application starts. I can see in the source that this is intentional, but is it really desirable? I would personally only expect such notifications the first time the application is run.

Thanks for making the best RSS Feed Reader available!

**Comment by martinrotter** [comment]
I see. Let me fix.

**Comment by martinrotter** [comment]
Done, will appear in 3.5.6. :) Thank you for your contribution, bro. :)
