### ISSUE TITLE
FR: Sort article list by multiple columns (e.g. first sort by read status, then sort by title)

### ISSUE THREAD

**Issue by danowar2k** [martinrotter/rssguard#178]
#### Brief description of the issue.

It would be nice if one could sort by multiple columns, e.g. by holding CTRL when clicking on the column title. The sort order could be indicated by a number in brackets, e.g. "^(1)", where ^ is the arrow.

I removed the other headlines, because none seemed to be applicable.

**Comment by martinrotter** [comment]
This feature is already there. It currently automagically sorts according to up to 3 sort columns which were selected most recently.

So, for example:
1. You click on account root node to see all messages from all feeds (you have all message list columns visible).
2. You click on `Title` column header, then click on `Feed` column header.

At this point your list of messages is sorted primarily by `Feed` column and if values in `Feed column` are equal, then those conflicting messages are sorted by `Title` column. As you can see on screenshot below. Items are sorted primarily according to `Feed` column, then by `Title` column.

![screenshot 2018-04-03 06 54 15](https://user-images.githubusercontent.com/1255302/38229966-d6f867a6-370b-11e8-86be-321fddcfdadc.png)

The only thing currently missing is that multi-sort state is currently not clearly visible (numbers in column headers).

Please test, if the feature actually works for you.
