### ISSUE TITLE
Feature Request: FeedHQ Support

### ISSUE THREAD

**Issue by sirredbeard** [martinrotter/rssguard#179]
[FeedHQ.org](https://feedhq.org/) is an open-source RSS feed aggregator like Inoreader with a well-documented API.

It is less expensive to subscribe to a premium hosted version of FeedHQ, only $12 USD annually, than other services.

To date, however, no Linux GUI RSS aggregator has support for FeedHQ, only Newsboater on the CLI.

I would appreciate if you considering  adding support for FeedHQ.

**Comment by martinrotter** [comment]
This will be implemented only if there is massive need for it by many users, not now sorry, as I do not use FeedHQ myself.
