### ISSUE TITLE
build with lower Qt version: 5.7.1

### ISSUE THREAD

**Issue by TrunovS** [martinrotter/rssguard#180]
#### Brief description of the issue.
Tried to build RSS Guard on Debian stretch with default qt repository version 5.7.1. QMake said "rssguard: At least Qt 5.8.0 needed." In my curiosity tried to comment problematic lines in rssguard.pro and build it as is, with few modifications.

#### What actually happened?

Build was succesfull.

**Comment by martinrotter** [comment]
Just curious. Is there any way to get rssguard to official Debian repositories? Or do you just compilling for yourself?
