### ISSUE TITLE
Build fails on archlinux, qt5-5.10.0

### ISSUE THREAD

**Issue by mmetak** [martinrotter/rssguard#182]
#### Brief description of the issue.
```
[  115s] Project MESSAGE: rssguard: Welcome RSS Guard qmake script.
[  115s] Project ERROR: rssguard: At least Qt "5.7.1" is required!!!
```
#### Other information (logs, see Wiki)
rssguard-git-3.5.5.r21.g3ec60aa5

This appears to be a upstream qt5 change. https://bugreports.qt.io/browse/QTBUG-63325

**Comment by martinrotter** [comment]
Does the problem exist if you use 3.5.5 branch/tag?

https://github.com/martinrotter/rssguard/tree/3.5.5

**Comment by martinrotter** [comment]
OK, test latest master, probably fixed.

**Comment by mmetak** [comment]
Builds fine. Closing this.
