### ISSUE TITLE
make install fails, trying to strip xml file

### ISSUE THREAD

**Issue by Kilill** [martinrotter/rssguard#183]
#### Brief description of the issue.
make install fails on trying to strip xml file:

> strip:/home/work/rssguard/rssguard-build/AppDir/usr/share/metainfo/com.github.rssguard.appdata.xml: File format not recognized
> Makefile:7356: recipe for target 'install_appdata' failed

#### How to reproduce the bug?
follow compile instruction on wiki:

```
qmake ../rssguard.pro -r CONFIG+=release
make
sudo make install
```

#### What is the expected result?
Completed install without errors

#### What actually happened?
Install failed 

#### Other information (logs, see Wiki)
commenting out the following line (735) in the make file works around the problem:

> -strip $(INSTALL_ROOT)/home/work/rssguard/rssguard-build/AppDir/usr/share/metainfo/com.github.rssguard.appdata.xml

**Comment by martinrotter** [comment]
Which distro?

Btw, it is actually quite normal that "make install" step contains -strip on all files, but it should "silently" continue the installation phase. Do you say that "make install" stops at that point?

Can you post full compilation log?

**Comment by martinrotter** [comment]
> [  525s] strip:/usr/src/packages/BUILD/rssguard-git/pkg/rssguard-git/usr/share/metainfo/com.github.rssguard.appdata.xml: File format not recognized

> [  525s] make: [Makefile:7327: install_appdata] Error 1 (ignored)

**Comment by Kilill** [comment]
redid the hole build from scratch, and tried to upload the resultant log files, but github throws an error trying to upload them, anyways, looking a bit more careful this seems to be mostly cosmetics, since the make install says:
make: [install_appdata] Error 1 **(ignored)**

Not being to familiar with how qmake does things , it took me a bit of reading the makefile to figure out that the make install drops of stuff in the AppDir folder, and it _seems_ that everything is there:
```
tree AppDir/
AppDir/
└── usr
    ├── bin
    │   └── rssguard
    └── share
        ├── applications
        │   └── com.github.rssguard.desktop
        ├── metainfo
        │   └── com.github.rssguard.appdata.xml
        └── pixmaps
            └── rssguard.png
```
Anyways:

`lsb_release -a:`

```
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
```

`qmake -V:`

```
QMake version 3.1
Using Qt version 5.9.1 in /usr/lib/x86_64-linux-gnu

```
`strip -V:`

`GNU strip (GNU Binutils for Ubuntu) 2.29.1`

Result of **sudo make install**
```
/usr/lib/x86_64-linux-gnu/qt5/bin/qmake -install qinstall -exe rssguard /home/work/rssguard/rssguard-build/AppDir/usr/bin/rssguard
strip /home/work/rssguard/rssguard-build/AppDir/usr/bin/rssguard
/usr/lib/x86_64-linux-gnu/qt5/bin/qmake -install qinstall /home/work/rssguard/resources/desktop/com.github.rssguard.desktop /home/work/rssguard/rssguard-build/AppDir/usr/share/applications/com.github.rssguard.desktop
/usr/lib/x86_64-linux-gnu/qt5/bin/qmake -install qinstall /home/work/rssguard/resources/graphics/rssguard.png /home/work/rssguard/rssguard-build/AppDir/usr/share/pixmaps/rssguard.png
/usr/lib/x86_64-linux-gnu/qt5/bin/qmake -install qinstall -exe /home/work/rssguard/resources/desktop/com.github.rssguard.appdata.xml /home/work/rssguard/rssguard-build/AppDir/usr/share/metainfo/com.github.rssguard.appdata.xml
strip /home/work/rssguard/rssguard-build/AppDir/usr/share/metainfo/com.github.rssguard.appdata.xml
strip:/home/work/rssguard/rssguard-build/AppDir/usr/share/metainfo/com.github.rssguard.appdata.xml: File format not recognized
Makefile:7356: recipe for target 'install_appdata' failed
make: [install_appdata] Error 1 (ignored)
```

qmake log:```

Info: creating stash file /home/work/rssguard/rssguard-build/.qmake.stash                                                       
Project MESSAGE: rssguard: Welcome RSS Guard qmake script.
Project MESSAGE: rssguard: PREFIX variable is not set. This might indicate error.
Project MESSAGE: rssguard: USE_WEBENGINE variable is not set.
Project MESSAGE: rssguard: WebEngine component is probably NOT installed, disabling it.
Project MESSAGE: rssguard: Shadow copy build directory "/home/work/rssguard/rssguard-build".
Project MESSAGE: rssguard: LRELEASE_EXECUTABLE variable is not set.
Project MESSAGE: rssguard: RSS Guard version is: "3.5.6".
Project MESSAGE: rssguard: Detected Qt version: "5.9.1".
Project MESSAGE: rssguard: Build destination directory: "".
Project MESSAGE: rssguard: Prefix directory: "/home/work/rssguard/rssguard-build/AppDir/usr".
Project MESSAGE: rssguard: Build revision: "50af26fa-nowebengine".
Project MESSAGE: rssguard: lrelease executable name: "lrelease".
Project MESSAGE: rssguard: Application will be compiled without QtWebEngine module. Some features will be disabled.
WARNING: Project ERROR: Unknown module(s) in QT: macextras webenginewidgets
Info: creating stash file /home/work/rssguard/.qmake.stash
Updating '/home/work/rssguard/localization/rssguard_cs.qm'...
    Generated 968 translation(s) (968 finished and 0 unfinished)
    Ignored 43 untranslated source text(s)
Updating '/home/work/rssguard/localization/rssguard_da.qm'...
    Generated 424 translation(s) (424 finished and 0 unfinished)
    Ignored 617 untranslated source text(s)
Updating '/home/work/rssguard/localization/rssguard_de.qm'...
    Generated 963 translation(s) (963 finished and 0 unfinished)
    Ignored 48 untranslated source text(s)
Updating '/home/work/rssguard/localization/rssguard_en_GB.qm'...
    Generated 3 translation(s) (3 finished and 0 unfinished)
    Ignored 1077 untranslated source text(s)
Updating '/home/work/rssguard/localization/rssguard_en.qm'...
    Generated 740 translation(s) (568 finished and 172 unfinished)
    Ignored 266 untranslated source text(s)
Updating '/home/work/rssguard/localization/rssguard_es.qm'...
    Generated 960 translation(s) (960 finished and 0 unfinished)
    Ignored 51 untranslated source text(s)
Updating '/home/work/rssguard/localization/rssguard_fr.qm'...
    Generated 457 translation(s) (457 finished and 0 unfinished)
    Ignored 601 untranslated source text(s)
Updating '/home/work/rssguard/localization/rssguard_he.qm'...
    Generated 75 translation(s) (75 finished and 0 unfinished)
    Ignored 1001 untranslated source text(s)
Updating '/home/work/rssguard/localization/rssguard_id.qm'...
    Generated 843 translation(s) (843 finished and 0 unfinished)
    Ignored 168 untranslated source text(s)
Updating '/home/work/rssguard/localization/rssguard_it.qm'...
    Generated 828 translation(s) (828 finished and 0 unfinished)
    Ignored 183 untranslated source text(s)
Updating '/home/work/rssguard/localization/rssguard_ja.qm'...
    Generated 358 translation(s) (358 finished and 0 unfinished)
    Ignored 691 untranslated source text(s)
Updating '/home/work/rssguard/localization/rssguard_lt.qm'...
   Generated 998 translation(s) (998 finished and 0 unfinished)
    Ignored 13 untranslated source text(s)
Updating '/home/work/rssguard/localization/rssguard_nl.qm'...
    Generated 871 translation(s) (871 finished and 0 unfinished)
    Ignored 140 untranslated source text(s)
Updating '/home/work/rssguard/localization/rssguard_pl.qm'...
Removed plural forms as the target language has less forms.
If this sounds wrong, possibly the target language is not set or recognized.
    Generated 773 translation(s) (773 finished and 0 unfinished)
    Ignored 242 untranslated source text(s)
Updating '/home/work/rssguard/localization/rssguard_pt.qm'...
    Generated 1006 translation(s) (1006 finished and 0 unfinished)
    Ignored 5 untranslated source text(s)
Updating '/home/work/rssguard/localization/rssguard_sv.qm'...
    Generated 1006 translation(s) (1006 finished and 0 unfinished)
    Ignored 5 untranslated source text(s)
Updating '/home/work/rssguard/localization/rssguard_zh.qm'...
    Generated 275 translation(s) (275 finished and 0 unfinished)
    Ignored 756 untranslated source text(s)

```
**BTW**

I see the following in the qmake log:

```
Project MESSAGE: rssguard: PREFIX variable is not set. This might indicate error.
Project MESSAGE: rssguard: USE_WEBENGINE variable is not set.
Project MESSAGE: rssguard: WebEngine component is probably NOT installed, disabling it.
```
and
`WARNING: Project ERROR: Unknown module(s) in QT: macextras webenginewidgets`

im assuming that PREFIX and USE_WEBENGINE need to be added to the qmake command, and missing  webengine dev packages.

**Comment by martinrotter** [comment]
Yes, you should install probably https://packages.ubuntu.com/artful/amd64/qtwebengine5-dev and non-dev package as well.

You can use `PREFIX` qmake variable to specify base folder for "make install" step. If you do not provide one, then script will use `$BUILD_DIR/AppDir/` directory on Linux.

**Comment by martinrotter** [comment]
See [this](https://build.opensuse.org/package/view_file/home:skunkos:rssguard/rssguard-git/PKGBUILD?expand=1) line 27.
