### ISSUE TITLE
Navigation by keyboard expands collapsed group

### ISSUE THREAD

**Issue by mahdi1234** [martinrotter/rssguard#185]
```
RSS Guard
Version: 3.5.6 (built on Linux/x86_64)
Revision: 
Build date: 3/26/18 5:22 PM
Qt: 5.9.4 (compiled against 5.9.4)
```

With collapsed groups and set navigation by keyboard CTRL+DOWN

- go down to collapsed group

it's expanded

- collapse the group with Space key
- CTRL+UP

just collapsed group is expanded again.

This is regression worked ok in 3.4 (one before moving to Qt 5.9) ... reverting back to 3.4 for now.

**Comment by martinrotter** [comment]
So, I changed the behavior a bit, please, test it.

https://github.com/martinrotter/rssguard/commit/6baafd0c66c1599e20e18f5d31051e3dc9cb922d

**Comment by mahdi1234** [comment]
There is still the same problem (or almost same), having several collapsed groups and going down or up it expands group which should be selected. If existing group was collapsed it stays collapsed. Expanding should be done only by user hitting Space key.
```
RSS Guard
Version: 3.5.7 (built on Linux/x86_64)
Revision: 7a368e53
Build date: 4/3/18 4:48 PM
Qt: 5.9.4 (compiled against 5.9.4)

```

**Comment by martinrotter** [comment]
Do you use functions "Select next item" and "Select previous item"? Those functions are meant to expand folders they switch into.

If have all groups collapsed and you trigger action "Select next item", then currently selected group should stay collapsed and next item (if it is group) will be expanded and its first child item selected. Same behavior applies for "Select previous item". Can you confirm? Can you make a video?
