### ISSUE TITLE
FR: Font size

### ISSUE THREAD

**Issue by gerroon** [martinrotter/rssguard#187]
Hi

This is a feature request about being able to choose font size used for the feeds area and the messages area. At the moment the fonts look so small on my HD screen.

I am using 3.5.6 app image on Linux

thanks

**Comment by laadler-satx** [comment]
I have to agree. I lo0e RSSGuard, but after a couple of hours my eyes can't take the small font.

**Comment by martinrotter** [comment]
Will add this soon.

**Comment by martinrotter** [comment]
@SaltedBacon @laadler-satx @gerroon 

Do you want this font setting to be global - to change all fonts across application? Or just strictly change font only in feed/message list?

**Comment by SaltedBacon** [comment]
Fonts size setting for feed/message list is enough for me

**Comment by laadler-satx** [comment]
I agree. Keep it simple.

**Comment by martinrotter** [comment]
Working on it:

![image](https://user-images.githubusercontent.com/1255302/58868869-774d3400-86bd-11e9-87c9-0033f7d16982.png)

**Comment by ngortheone** [comment]
@martinrotter is this implemented? I am using version 3.8.3 and I can't find where I can adjust the font size...

**Comment by martinrotter** [comment]
Yes, this was fixed years ago.
[image: image.png]

**Comment by ngortheone** [comment]
Yes, sorry, the menu was not easy to find, I found it afterwards I posted.
