### ISSUE TITLE
In-memory DB crashes since QT updated to 5.11

### ISSUE THREAD

**Issue by vicencb** [martinrotter/rssguard#188]
Hi!

#### Brief description of the issue.

rssguard crashes

#### How to reproduce the bug?

1. Configure RSS Guard to use in-memory SQLite database
2. Update QT from 5.10 to 5.11
3. Update all items

#### What is the expected result?

Update the feed list and message list with new un-read messages

#### What actually happened?

Application closed itself

#### Other information (logs, see Wiki)

[rssguard] CRITICAL: User wanted to update some feeds but all working threads are occupied. (18/27/05 22:25:17)
...
[rssguard] DEBUG: There are some messages to be updated/added to DB. (18/27/05 22:25:17)
[rssguard] WARNING: QSqlDatabasePrivate::database: requested database does not belong to the calling thread. (18/27/05 22:25:17)
[rssguard] FATAL (terminating application): In-memory SQLite database was NOT opened. Delivered error message: 'Driver not loaded Driver not loaded'. (18/27/05 22:25:17)
Aborted (core dumped)

P.D.: In case it matters, running on ARM64

Regards,
&nbsp;&nbsp;Vicenç.

**Comment by martinrotter** [comment]
Yes, I reproduced the issue, it is related partially to #80 and #114. The whole feed update mechanism is buggy and needs to be rewritten.

That said, RSS Guard is no longer my priority because I changed my workflow and I do not use any RSS reader app anymore. I might fix this in a future, but I cannot guarantee anything. My time is highly limited and RSS Guard would seriously need some code contributors and/or maintainers.

**Comment by martinrotter** [comment]
OK, I think I fixed the issue, can you please test development build compiled from 498e85d?

**Comment by xmstspider** [comment]
> That said, RSS Guard is no longer my priority because I changed my workflow and I do not use any RSS reader app anymore. I might fix this in a future, but I cannot guarantee anything. My time is highly limited and RSS Guard would seriously need some code contributors and/or maintainers.

Could you write a blog on abclinuxu about this? Maybe someone could help you...

**Comment by martinrotter** [comment]
Will do today.

**Comment by vicencb** [comment]
This issue got fixed, but another one got introduced.
The way to reproduce the new one is:
1. Tools
1. Settings
1. Data storage
1. Toggle "Use in-memory database as the working database"
1. OK
1. Do you want to restart now? No
1. File
1. Quit

The result is:
```
[rssguard] DEBUG: Syncing settings. (18/28/05 19:22:11)
[rssguard] DEBUG: Destroying FormSettings distance. (18/28/05 19:22:14)
[rssguard] DEBUG: Destroying ToolBarEditor instance. (18/28/05 19:22:14)
[rssguard] DEBUG: Destroying ToolBarEditor instance. (18/28/05 19:22:14)
[rssguard] DEBUG: Destroying ToolBarEditor instance. (18/28/05 19:22:14)
[rssguard] DEBUG: Cleaning up resources and saving application state. (18/28/05 19:22:15)
Segmentation fault (core dumped)
```
Otherwise, the in-memory DB now works fine and (as long as the setting is not changed) it looks pretty stable.

Thanks,
&nbsp;&nbsp;Vicenç.

**Comment by vicencb** [comment]
Hi,
just tested 879a0caad7e614d2b982410c30a02252e399f89b and it works fine!
Thank you.

**Comment by martinrotter** [comment]
> This issue got fixed, but another one got introduced.
>The way to reproduce the new one is:

@vicencb so this regression issue is fixed for you too? Can I close?

**Comment by vicencb** [comment]
Yes, it can be closed. It works great now!
