### ISSUE TITLE
noticeable feed update delay on application startup

### ISSUE THREAD

**Issue by dnmTX** [martinrotter/rssguard#193]
#### Brief description of the issue.
Not sure that it's a bug or by design but when it's set to update all feeds on application startup it usually takes about 25 sec to start updating. Couldn't find anything in the .ini to change it.Would appreciate if there is a option to adjust the delay.In my case i prefer to start updating as soon as i open it.Thank you.

#### How to reproduce the bug?

1. Start rssguard manually(it's set to update feeds on app startup)
2. noticeable delay of about 25 sec before it start updating the feeds
3. 

#### What is the expected result?

to update the feeds as soon as you open rssguard or at least have option to adjust the delay time

**Comment by xmstspider** [comment]
Did you try to run it with strace to see where/if it wait and for what?

**Comment by dnmTX** [comment]
@xmstspider  thank you for replying.I'm not sure how to run it with the "strace" argument,there is not too much info in the **wiki** about running the program from terminal,nevertheless i did run it to generate log file so i'm attaching it here.Based on it it looks like it's designed that way,to wait 30 sec before it starts updating:
_____________________________________________________________________________________________
[rssguard] DEBUG: Auto-update timer started with interval 60000. (18/02/07 02:55:56)
[rssguard] DEBUG: I will start next check for cached service data in 30 seconds. (18/02/07 02:55:56)
[rssguard] DEBUG: Requesting update for all feeds on application startup. (18/02/07 02:55:56)
______________________________________________________________________________________________

If the log attached is not enough and need me to run "strace" please provide more info on **how to**.
Thank you. 
[rssguard.txt](https://github.com/martinrotter/rssguard/files/2154355/rssguard.txt)

**Comment by xmstspider** [comment]
OK, this line:

>  [rssguard] DEBUG: I will start next check for cached service data in 30 seconds. (18/02/07 02:55:56)

Says it will start checking after 30 seconds.

Regarding the strace: not I see you did not specify if you run Linux or Windows. On Linux, you can use strace to see what happens when the program runs. You start it in terminal by running 'strace rssguard' - any other instance of rssguard may not be active.

**Comment by dnmTX** [comment]
@xmstspider  i'm on Windows so no strace for me i guess. Judging by your answer it's confirmed that it waits 30 sec before updating or i misunderstood you? If it does,can anything be done to adjust it?

**Comment by xmstspider** [comment]
Correct - I will check tonight if it does the same thing on my Linux machine, otherwise @martinrotter can probably answer if this is normal behavior or not.

**Comment by martinrotter** [comment]
#define STARTUP_UPDATE_DELAY 30000


delay is hardcoded, i am on vacations, will fix when i get back a week later

**Comment by dnmTX** [comment]
@xmstspider thank you for your help 👍. @martinrotter  i'll leave the issue open just as reminder or you can close it if you want.Have fun on your vacation 😎 and will wait for a fix.

**Comment by martinrotter** [comment]
So how would you prefer this to be fixed? Changeable delay in the settings?

**Comment by dnmTX** [comment]
@martinrotter  sure,as long as there is option to disable any delays(i'm still wondering why there was one on a first place). Thank you.

**Comment by martinrotter** [comment]
There is a delay because some plugins (mainly gmail) use oauth and sometimes it can take some time for processing oauth stuff, but i plan to enhance this behavior and completely remove delays in the future.

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/83635528-ab935300-a5a4-11ea-9d09-bb7d8d7cfa51.png)

Now, delay is configurable with minimum value of 3 seconds.
