### ISSUE TITLE
chocolatey package for rssguard is deprecated

### ISSUE THREAD

**Issue by chantisnake** [martinrotter/rssguard#196]
I was the maintainer for the [chocolatey](https://chocolatey.org/) package for rssguard.
  I am deprecating the chocolatey package for rssguard because I no longer have time to maintain it.

  I have requested for another package maintainer here: https://github.com/chocolatey/chocolatey-package-requests/issues/421
  The chocolatey package page for rssguard : https://chocolatey.org/packages/rssguard

  Sorry for all the inconvenience I have caused.

  (This issue is created automatically, some of the links may be wrong, please inform me if You want me to change them.)

**Comment by martinrotter** [comment]
Seems that the package is no longer abandoned.
