### ISSUE TITLE
How to compile for 16.04?

### ISSUE THREAD

**Issue by cement-head** [martinrotter/rssguard#197]
I've installed Qt 5.8 (locally).

When I try to compile, it uses the global Qt 5.5 libraries.  How do I specify the path to the Qt 5.8 libraries for compiling?

Thanks.

**Comment by martinrotter** [comment]
See

https://github.com/martinrotter/rssguard/blob/master/resources/scripts/.travis-before-install.sh#L17

and

https://github.com/martinrotter/rssguard/blob/master/resources/scripts/.travis-install-linux.sh#L4
