### ISSUE TITLE
TT-RSS: shareToPublished

### ISSUE THREAD

**Issue by netpipe** [martinrotter/rssguard#198]
I tried building the latest repo, but shareToPublished option for tinyrss is either missing or hard to find.

**Comment by martinrotter** [comment]
shareToPublished is not yet supported, but I might add it in the future as it seems relatively easy to add.

**Comment by martinrotter** [comment]
@netpipe How exactly should this feature work? Should just popup dialog show where you enter URL/title/contents of your new article manually or how?

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/149520962-d6301978-2edb-45fe-8ffe-c7e495ba19d0.png)

![image](https://user-images.githubusercontent.com/1255302/149521029-ea8b889e-cee3-4427-8ed0-ca392369f751.png)

![image](https://user-images.githubusercontent.com/1255302/149521052-370f5157-212b-45bb-bd57-0997aa78dcdd.png)

![image](https://user-images.githubusercontent.com/1255302/149521085-d8063b0d-91be-45e4-8a74-0953370a563a.png)
