### ISSUE TITLE
TT-RSS: Download only new unread messages when updating feed(s)

### ISSUE THREAD

**Issue by netpipe** [martinrotter/rssguard#199]
https://git.tt-rss.org/fox/tt-rss/wiki/ApiReference
updateArticle api call can get only nonread items from tinyrss rather than it trying to download all the articles every time.

update only non nonread items from ttrss option.

**Comment by martinrotter** [comment]
Hello, `updateArticle` API method is used to *change* state of already existing articles - e.g. to mark article as read or unread.

Perhaps you mean `getHeadlines` API method which is used by RSS Guard to *download* new messages and you suggest that RSS Guard should only download *unread* messages to RSS Guard and not all of them?

**Comment by dariottolo** [comment]
I think the Api Reference posted in original post changed.
Could:
`unread_only (bool) - only return feeds which have unread articles`
help to retrieve first feeds with unread articles, then fetch them only from those feeds, instead of querying everything all the time?

**Comment by tecan** [comment]
yes , ide noticed it took too long compared to other rss readers. like it did not stop looking when it found a matching headline

**Comment by tecan** [comment]
it was for the desktop clients that are used to download the messages

**Comment by dariottolo** [comment]
> it was for the desktop clients that are used to download the messages

I agree. But TT-RSS has already downloaded the messages, so it makes no sense to fetch for all the feeds if it is possible to retrieve the list of the feeds that have unread messages and just fetch those

**Comment by martinrotter** [comment]
Current situation in RSS Guard is this:
* it iterates all feeds scheduled for update (either auto-update or user chose to update by button)
* it downloads all messages available for the TT-RSS feed
* it updates message and its state in rssguard database

So everytime all messages are downloaded per feed but are only inserted/updated in database if they do not already are there. My suggestion is to use "getCounters" API method first to determine if given feed has any unread messages in TT-RSS server and only actually download unread messages (via "getHeadlines" method with "view_mode" = "unread") when there are really some unread messages.

This would significantly speed-up downloading of messages in TT-RSS plugin. This behavior would be switchable in TT-RSS service rssguard settings.

What do you think?

**Comment by martinrotter** [comment]
> I think the Api Reference posted in original post changed.
> Could:
> `unread_only (bool) - only return feeds which have unread articles`
> help to retrieve first feeds with unread articles, then fetch them only from those feeds, instead of querying everything all the time?

Yes, this API call could help and it essentially provides the same information as "getCounters" call and I will try to incorporate this into TT-RSS plugin.

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/83622040-c909f200-a58f-11ea-853b-054a6ef3985c.png)

Working on it...

**Comment by martinrotter** [comment]
OK, first tests with cca 100 feeds: unread-only-fetching took 15 seconds, all-msgs-fetching took more than 3 minutes.

**Comment by martinrotter** [comment]
OK, I commited first experimental implementation. Please, wait until dev build compiles and test it and let me know.

Thank you.

**Comment by martinrotter** [comment]
OK so now only unread messages can be downloaded if user wants too. I plan to add same feature to owncloud accounts too.

**Comment by dariottolo** [comment]
I downloaded the latest version and I confirm that RSS Guard works much better and is a lot faster with that change. Thank you

**Comment by martinrotter** [comment]
So this happened:
- RSS Guard downloaded **unread** message X
- You did NOT read the message X in RSS Guard
- In the meantime, you also downloaded message X in some other TT-RSS app and marked it read
- You updated messages in RSS Guard later but already downloaded message X is still unread in RSS Guard but you expect it to be marked as read (fetch its latest state from TT-RSS)

**Comment by martinrotter** [comment]
OK, I double checked what is possible with TT-RSS API.

The point is, that when you check "Download unread" box in RSS Guard, then RSS Guard tells TT-RSS server to give only unread messages. If you wish to also receive messages whose read/starred state changed too, then RSS Guard would have to make extra network request to TT-RSS server.

Unfortunately, there is no TT-RSS api to return only messages "updated state", I do not know why. There use `getHeadlines` function with `view_mode=marked/updated` but that returns not only messages with updated state but also some others (for me) unexpected messages which would really make the purpose of "Download unread only messages" useless.

If TT-RSS guys add some kind of better function to actually get message with changed state, I would call it, but at this point I do not see a way to go.
