### ISSUE TITLE
notification icon leaves the systray.

### ISSUE THREAD

**Issue by 666threesixes666** [martinrotter/rssguard#2]
the notification icon leaves the systray sporadically.  running rssguard again throws messages that it's already open.  =D  ps im back....  it's not hidden when minimized.  i set it to run at boot, starting minimized so if nothings shouting at me the apps not in my face.  i dont think it has to do with xfce4's compositing like nm-applets exit from the dock, ie reloading the compositor its still not in the systray.

**Comment by martinrotter** [comment]
Does it happen after your do any particular actions in RSS Guard?

Does it happen when you run it manually, so not after boot autimatically?

**Comment by 666threesixes666** [comment]
i think it does very few and very far between when run manually, but primarily at boot.  im wrecked tired and going to sleep...  thanks for your efforts =)

**Comment by martinrotter** [comment]
Yes yes. Please, it would be best to start rssguard like this "rssguard >& log-file.txt". Start rssguard with this command. Create script for example:

#!/bin/bash
rssguard >& /home/<user>/log-file.txt

And run this script at boot (desktop evnironment login). This will create log file. Then reproduce the bug, then upload created log file.

**Comment by 666threesixes666** [comment]
sorry you must of fixed something...  its far more reliable now...  did it the other day, so im setting up the log.  removing the "launch rssguard at system startup" setting, launching from xfce4's startup with
rssguard >& $HOME/rssguard.log

**Comment by martinrotter** [comment]
Yes yes. See if bug still exists and give me logs if it does. :) Thank you.

**Comment by 666threesixes666** [comment]
it will probably be in the next two weeks to get back to you on this as i dont restart often.

**Comment by 666threesixes666** [comment]
https://gist.github.com/666threesixes666/065aebd01526bd63575f

**Comment by martinrotter** [comment]
Shit, I see no special stuff there about tray icons. Does RSS Guard actually still running when tray icon disappears? Does it help if you try to switch tray icon off -> on in settings when the bug happens?

**Comment by 666threesixes666** [comment]
shit, the potty language = excellent!  i got it to reproduce it a few times, i think ill change it to append to the log instead, that last one the rssguard was straight up freaking out, no rss* in ps aux

**Comment by martinrotter** [comment]
So it actually seems to crash?

**Comment by 666threesixes666** [comment]
i fumbled the script to load it on accident, mybad...  i have my system setup to where i can relogin 100s of times now with out dropping irc and being annoying so i'll produce the bug for you in a bit.

**Comment by martinrotter** [comment]
No problem. :)

2015-06-16 11:12 GMT+02:00 666threesixes666 <notifications@github.com>:
