### ISSUE TITLE
Lack of two-factor authentication support

### ISSUE THREAD

**Issue by ymjonline** [martinrotter/rssguard#204]
#### Brief description of the issue.

RSS-Guard is featured as the de-facto Windows app for Nextcloud News.
Best practises these days clearly instruct to use Two-Factor authentication for Next-cloud.
RSS-Guard does not support it (or at least could not find any way to log in) which renders the app useless.

#### How to reproduce the bug?

1. Open up app, choose Next-cloud
2. Put in username + password

#### What is the expected result?

You'd expect to me redirected to a two-factor auth window, but nothing happens

#### What actually happened?

Nothing, cannot connect.

**Comment by martinrotter** [comment]
Is there any good documentation on how to exactly use 2FA with Nextcloud News API?

**Comment by martinrotter** [comment]
Btw, why do you think that 

> RSS-Guard is featured as the de-facto Windows app for Nextcloud News.

?

**Comment by ymjonline** [comment]
> Is there any good documentation on how to exactly use 2FA with Nextcloud News API?

Probably I haven't checked out yet.
Since RSS-Guard features Nextcloud as

**Comment by ymjonline** [comment]
> Btw, why do you think that
> 
> > RSS-Guard is featured as the de-facto Windows app for Nextcloud News.
> 
> ?

Because of https://github.com/nextcloud/news
It's the one Windows app that seems to integrate with Nextcloud.

Is there documented API. Probably, I haven't checked. But since RSS-Guard claims to be Nextcloud compliant, I was under the assumption that this would be the kind of things you'd be following up on.

**Comment by ymjonline** [comment]
> Is there any good documentation on how to exactly use 2FA with Nextcloud News API?

here you are:

https://docs.nextcloud.com/server/stable/developer_manual/client_apis/LoginFlow/index.html

**Comment by martinrotter** [comment]
As per Nextcloud News [docs](https://github.com/nextcloud/news/blob/master/docs/externalapi/Legacy.md) it seems that LoginFlow is not supported for News API itself.
