### ISSUE TITLE
Images in "nowebengine" version

### ISSUE THREAD

**Issue by meelten** [martinrotter/rssguard#205]
Hello. I run rssguard-nowebengine on linux (without webengine support) and all images are displayed as big "placeholders". Is it possible to either show images without webengine or, if not, disable them completely or hide somehow?

**Comment by martinrotter** [comment]
Nowebengine version of RSS Guard is lightweight variant. Messages are not displayed in full-blown HTML component, but simpler text component is used. This component supports only smaller HTML subset, and no scripting - better performance, more security.

Yes, it is possible to "show" images: RSS Guard automagically detects all images in the message and displays clickable hyperlink in form `[image] address` for each of them. You can click on hyperlinks and RSS Guard asks if you want to open them in external browser, or you can download them to disk.


![image](https://user-images.githubusercontent.com/1255302/58454709-9416c400-811f-11e9-9067-b3e6add25cc8.png)

![image](https://user-images.githubusercontent.com/1255302/58454718-98db7800-811f-11e9-9192-87301f80dd71.png)

![image](https://user-images.githubusercontent.com/1255302/58454727-a264e000-811f-11e9-8e1c-123ede940684.png)

**Comment by martinrotter** [comment]
Or perhaps should I completely turn placeholders off? It's true that they are just occupying precious space...

**Comment by meelten** [comment]
Yest I think it would be better to get rid of them. Or maybe put link to image instead of placeholder if that's possible.

**Comment by martinrotter** [comment]
Fixed now, switchable in settings section "Feeds & messages => Messages"
