### ISSUE TITLE
Appimage missing in new release

### ISSUE THREAD

**Issue by dCo3lh0** [martinrotter/rssguard#206]
Hi, Martin, i have seen that you released a new version, i have seen too that the build for linux appimage failed, another thing is that i noticed that it did recognize my qt5ct and gtk2 to fit my xfce in the theme options, it has gone nice with my desktop, can you add those options to the new build

**Comment by cement-head** [comment]
Any idea of the ETA for the AppImage build for Linux?

**Comment by martinrotter** [comment]
Yes, I am aware of this, I struggle with Travis/AppVeyor github tokens permissions, it just does not sometimes work, but development versions AppImage just compiled and they are almost the same or better as 3.5.7 release.

https://github.com/martinrotter/rssguard/wiki/Development-builds

**Comment by martinrotter** [comment]
@dCo3lh0 

> it did recognize my qt5ct and gtk2 to fit my xfce in the theme options, it has gone nice with my desktop, can you add those options to the new build

Can you please ellaborate for this or even better, create separate ticket...
