### ISSUE TITLE
WebEngine crashing RSS Guard?

### ISSUE THREAD

**Issue by dCo3lh0** [martinrotter/rssguard#209]
#### Brief description of the issue.

RSS Guard for Linux 3.5.9, crashing instantly when opening a message

#### How to reproduce the bug?

1. Open the program
2. select any message
3. crash

#### What is the expected result?

load the message and read

#### What actually happened?

closes without dialog prompt

**Comment by martinrotter** [comment]
Can you launch rssguard via terminal and paste std/err output in terminal after it crashes?

https://github.com/martinrotter/rssguard/wiki/Generating-debug-log-file

No such thing happens for me, weird.

**Comment by dCo3lh0** [comment]
Here is the log file.

[log.txt](https://github.com/martinrotter/rssguard/files/3264517/log.txt)

**Comment by martinrotter** [comment]
Try to launch rssguard from terminal like this:

`QT_WEBENGINE_DISABLE_GPU=1 rssguard`

Anyway, it seems that the issue is upstream na QtWebEngine library.
