### ISSUE TITLE
ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox!

### ISSUE THREAD

**Issue by alium** [martinrotter/rssguard#21]
I can not run the rssguard, ended with error:
[alois@toshiba rssguard]$ rssguard 
[0624/184704:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
[rssguard] DEBUG: Instantiated Application class.
[rssguard] DEBUG: Available icon theme paths: '/home/alois/.icons', '/usr/share/icons', '/usr/share/icons', ':/icons', '/usr/share/rssguard/icons'.
[rssguard] DEBUG: Initializing settings in '/home/alois/.rssguard/data/config/config.ini' (non-portable way).
[rssguard] DEBUG: Installed icon themes are: ', 'hicolor', 'oxygen', 'breeze', 'breeze-dark', 'Breeze_Snow', 'breeze_cursors', 'default'.
[rssguard] DEBUG: Icon theme 'Faenza' cannot be loaded because it is not installed. No icon theme (or default icon theme) is loaded now.
[rssguard] DEBUG: Skin 'base/vergilius.xml' loaded.
[rssguard] DEBUG: Starting to load active localization. Desired localization is 'cs_CZ'.
[rssguard] DEBUG: Application localization 'cs_CZ' loaded successfully, specifically sublocalization 'cs' was loaded.
[rssguard] DEBUG: Qt localization 'cs' loaded successfully.
[rssguard] DEBUG: Creating main application form in thread: '0x7f3cd6f0c800'.
[rssguard] DEBUG: Creating tray icon menu.
[rssguard] DEBUG: Working database source was determined as SQLite file-based database.
[rssguard] WARNING: Error occurred. File-based SQLite database is not initialized. Initializing now.
[rssguard] DEBUG: File-based SQLite database backend should be ready now.
[rssguard] DEBUG: Current row changed - row [-1,-1] source [-1, -1].
[rssguard] DEBUG: Auto-update timer started with interval 60000.
[rssguard] DEBUG: Adjusting column resize modes for MessagesView.
[rssguard] DEBUG: Showing the main window when the application is starting.
[rssguard] DEBUG: Showing tray icon.
[rssguard] DEBUG: Creating SystemTrayIcon instance.
Neoprávněný přístup do paměti (SIGSEGV)

Archlinux, 64-bit,Qt 5.7.0 
build() {
  cd $pkgname-$pkgver
  qmake-qt5 -r CONFIG+=release PREFIX=/usr INSTALL_ROOT="$pkgdir/" QMAKE_CFLAGS_RELEASE="$CPPFLAGS $CFLAGS" QMAKE_CXXFLAGS_RELEASE="$CPPFLAGS $CXXFLAGS" QMAKE_LFLAGS_RELEASE="$LDFLAGS"
  make
}

package() {
  cd $pkgname-$pkgver
  make INSTALL_ROOT="$pkgdir/" install
}

any idea?

**Comment by martinrotter** [comment]
Will try to build latest version? Can you build as debug and provide crash backtrace? Or directly debug in Qt Creator and see at which line exactly it crashes?

**Comment by martinrotter** [comment]
EDIT: Just built latest [master] code on my Arch system, works. Will try to google those errors.

**Comment by martinrotter** [comment]
EDIT: I got same webenegine error at start, does not seem to influence anything.

**Comment by alium** [comment]
I use 3.3.1

**Comment by alium** [comment]
sorry, for closing, bad button :-)

**Comment by pmattern** [comment]
As I understand it the error message about the missing sandbox isn't really an issue but those crashes of QtWebEngine which happen with other applications compiled against QtWebEngine of Qt 5.7 as well are. 
See [QTBUG-53928](https://bugreports.qt.io/browse/QTBUG-53928).

**Comment by alium** [comment]
sorry, it seems Archlinux bug (some packaked needed rebuild with new Qt 5.7.0, i upgrade too fast)

NO BUG,
yet works again (after some updates from Archlinux - rebuilded kwin and kwayland).

**Comment by martinrotter** [comment]
That KDE. :D
