### ISSUE TITLE
Blue in dark theme does not look good

### ISSUE THREAD

**Issue by gerroon** [martinrotter/rssguard#210]
Hi

I use the dark theme and the blue coloring for the unread subsciption is unreadable at all. Please see the image

![Mca3Jaq](https://user-images.githubusercontent.com/8519469/59383782-2807a300-8d50-11e9-8618-7637e4ae074c.png)

**Comment by martinrotter** [comment]
yes it sucks, i will try to update dark skin

**Comment by gerroon** [comment]
Awesome and thanks

**Comment by martinrotter** [comment]
I fixed this, change to orange color.

RSS Guard would benefit from having super-cute-and-polished alternative skin, but unfortunately I am not that good in graphics/ui stuff. Anyway, internall mechanisms implemented allow to change ui style of rss guard completely.

![image](https://user-images.githubusercontent.com/1255302/60241592-fd6f2b80-98b3-11e9-904b-166bb8a2294b.png)

**Comment by guihkx** [comment]
Hi, sorry to necro-bump this, but I'm experiencing the same thing as OP with RSSGuard 3.7.2 on Arch Linux and I didn't wanted to open a new issue:

![image](https://user-images.githubusercontent.com/626206/97254773-ddc07e00-17ed-11eb-9f13-5b2b8e39b8c7.png)

This is my theme settings:

![image](https://user-images.githubusercontent.com/626206/97254843-0ea0b300-17ee-11eb-9a3e-41156b11ea10.png)

I noticed the "unread" counter is blue only when I open RSSGuard after getting a desktop notification for a new feed update. Do I need to change something else in the settings? Thanks.

**Comment by martinrotter** [comment]
It seeems that somehow my fix for this is not in the repo. I probably fucked this up. Lemme fix for next release. :)

**Comment by martinrotter** [comment]
Oh, yes. Completely fucked, I will even enhance this. You can even define your own skins with completely custom colors, but it is not yet documented.

Anyway, fixing, will look like this for dark skin: 
![image](https://user-images.githubusercontent.com/1255302/97268971-07e56080-182d-11eb-8e4f-831f0deed9c0.png)

As for own skins, you can check "About" dialog and there you will see "skins base path": 
![image](https://user-images.githubusercontent.com/1255302/97269259-86da9900-182d-11eb-98ea-1afecb4e3255.png)

In my case, my user skins base path is `D:\Martin\Projekty\Moje\build-build-Qt-Debug\src\rssguard\data\skins` and then you can go [here](https://github.com/martinrotter/rssguard/tree/master/resources/skins), take one of the folders and place it into the path, so for example you can take dark skin, copy its folder and also rename it `D:\Martin\Projekty\Moje\build-build-Qt-Debug\src\rssguard\data\skins\mydark`.

Also you then need to go through skin files and adjust colors as you like. You could be particularly interested in subfile `https://github.com/martinrotter/rssguard/blob/master/resources/skins/dark/metadata.xml` where in `palette` section you will find some colors defined and assigned to keys "1" (which means "highlighted color") and "2" (which means "error" color).

Once you copy your skin and rename its folder, it will be seen by RSS Guard (restart needed).

**Comment by martinrotter** [comment]
OK, I pushed the fix RN. It will appear in 3.8.0 version which will come out in two/three weeks.

**Comment by guihkx** [comment]
Beautiful! Thanks a lot for fixing it this quickly and also thanks for the instructions on skins.

I'll see if I can give it a try later tonight.

**Comment by martinrotter** [comment]
Yes, make sure to test it on latest development build: https://bintray.com/martinrotter/rssguard/Development/Windows

**Comment by guihkx** [comment]
Just tested it, looks much better now on Linux too 👍
