### ISSUE TITLE
RSS Guard icon is incorrect on KDE Plasma Wayland session

### ISSUE THREAD

**Issue by glaubersm** [martinrotter/rssguard#212]
#### Brief description of the issue.
This issue occurs with RSS Guard 3.5.9 on Arch Linux running KDE Plasma desktop environment.

#### How to reproduce the bug?

1. start KDE Plasma Wayland session
2. open RSS Guard
3. 

#### What is the expected result?

Both the title bar and the task switcher (alt+tab menu) show RSS Guard icon.
#### What actually happened?

We can see a Wayland generic icon in the title bar and when we press alt+tab.
#### Other information (logs, see Wiki)

Maybe this link can help you
https://community.kde.org/Guidelines_and_HOWTOs/Wayland_Porting_Notes#Application_Icon

![rss guard](https://user-images.githubusercontent.com/15967631/61578521-b64d1280-aace-11e9-868a-fa8b1c45c56d.png)

**Comment by martinrotter** [comment]
OK

cb0f2324..bdc32401

Please test when dev gets compiled and let me know.

**Comment by glaubersm** [comment]
your appimages run on Xwayland, not natively on Wayland.

I tried to build rssguard-git from AUR

https://aur.archlinux.org/packages/rssguard-git/

 but building fails with this error message:

`Cannot find file: /var/tmp/pamac-build-stalker/rssguard-git/src/rssguard/rssguard.pro.`

**Comment by martinrotter** [comment]
@glaubersm Yes, because PRO files were renamed. See regular package pkgbuild.

https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/rssguard

**Comment by glaubersm** [comment]
I built master branch, a binary called `rssguard`was created in `/home/myusername/rssguard/src/rssguard/AppDir/usr/bin/` but it does not run. Terninal says "command not found" when I run "rssguard".

**Comment by martinrotter** [comment]
Wtf. You probably must run `./rssguard` and make sure you have that binary executable `chmod +x ./rssguard`. Also make sure you are in that folder `cd /home/myusername/rssguard/src/rssguard/AppDir/usr/bin/`. Try and let me know.

**Comment by martinrotter** [comment]
Also, I believe that if you want to test out this stuff, then you must actually install the package, so that *rssguard*.desktop file is also available in the system.

**Comment by martinrotter** [comment]
OK, I tested myself on latest Ubuntu with KDE installed, I launched KDE via Wayland and latest [master] branch compiled via AUR rssguard-git, installed the packaged and it runs just nice. Correct icon is visible.

**Comment by glaubersm** [comment]
I installed built rssguard with `make install`, but no shortcut was created in my apps launcher.
`./rssguard` says `./rssguard: error while loading shared libraries: librssguard.so: cannot open shared object file: No such file or directory`.
I did something wrong. :(
Thank you for your interest on this issue. :)

**Comment by martinrotter** [comment]
make install installs everything under <build-dir>/AppDir directory, you need to make sure that AppDir/usr/lib directory is LD_LIBRARY_PATH env. variable to make it work, or you can create AppImage or simply install Aur-generated package

this is however bit advanced stuff, anyway I checked in GNOME/KDE and in UBUNTU/MANJARO and icon was there, the patch seemed to work.
