### ISSUE TITLE
Feature-Request: Full Youtube Description and Twitch Category

### ISSUE THREAD

**Issue by cyberpunkbln** [martinrotter/rssguard#213]
Hello,

i love rssGuard why it is the only rss-fetcher that have so an simple feature like many external programs with right click;).

But it cannot read the special youtube rss dtd with the full description and with pics with the web render engine release.

[https://www.youtube.com/feeds/videos.xml?channel_id=UCF_k3-4jHtT6aJkzQ9gnIeQ](https://www.youtube.com/feeds/videos.xml?channel_id=UCF_k3-4jHtT6aJkzQ9gnIeQ)

And the special Category-Tag in the twitch rss feed:

https://twitchrss.appspot.com/vod/hirnsturz

As an Feature it will be cool;).

Thx

**Comment by martinrotter** [comment]
fixing right now:

![image](https://user-images.githubusercontent.com/1255302/64416220-14da4a00-d097-11e9-9230-5f6ed3b7ff5b.png)

**Comment by martinrotter** [comment]
+ i am not sure what to do with <category> tag tho, but youtube tags will be fixed

**Comment by martinrotter** [comment]
14dda062

you can try latest dev version when it is auto-compiled

**Comment by cyberpunkbln** [comment]
Hello,
thx, very cool!

**Comment by martinrotter** [comment]
@cyberpunkbln Does it work? Did you try latest builds at  https://github.com/martinrotter/rssguard/wiki/Development-builds

**Comment by cyberpunkbln** [comment]
yes functioned perfectly with web and without web engine.

The possible to manual sort folders and setting of the windows "allways running" message will be nice for the future.
