### ISSUE TITLE
Add repology badge

### ISSUE THREAD

**Issue by luzpaz** [martinrotter/rssguard#214]
### Summary
A way for users to see what downstream repositories carry rssguard

### Proposed design
The compact badge looks like so:  
[![Packaging status](https://repology.org/badge/tiny-repos/rssguard.svg)](https://repology.org/project/rssguard/versions)

The full badge looks like so (but may be too "bulky"):  
[![Packaging status](https://repology.org/badge/vertical-allrepos/rssguard.svg?header=rssguard)](https://repology.org/project/rssguard/versions)  

---------

**Note:** There is also a possibility to add the full badge in to it's own section, like so:

```
### Packaging Status

<details>
  <summary>Expand to see the packaging status of RSSGuard...</summary>

[![Packaging status](https://repology.org/badge/vertical-allrepos/rssguard.svg?header=rssguard)](https://repology.org/project/rssguard/versions)  

</details>
```

**Which gives us:**  

### Packaging Status

<details>
  <summary>Expand to see the packaging status of RSSGuard...</summary

[![Packaging status](https://repology.org/badge/vertical-allrepos/rssguard.svg?header=rssguard)](https://repology.org/project/rssguard/versions)  

</details>

**Comment by martinrotter** [comment]
thats nice, added to main readme, thank you
