### ISSUE TITLE
Can not connect to NextCloud account

### ISSUE THREAD

**Issue by zoxal** [martinrotter/rssguard#215]
#### Brief description of the issue.

I can not connect to my NextCloud News account. 

#### How to reproduce the bug?

1. Accounts -> Add New Account -> NextCloud News
2. Fill URL, user and password fields
3. Click 'Test Setup'

#### What is the expected result?

Test successfully performed

#### What actually happened?

No response from app. After about 30 sec I get network error: 

![image](https://user-images.githubusercontent.com/15104938/64918022-ad13b580-d7a0-11e9-882e-5b25b8456ee7.png)

#### Other information (logs, see Wiki)

OS info: Manjaro Linux (KDE) 18.1.0
App build info: I got the same results with both app from Majaro repositories and my build from sources (seems like important flag 'prefix' is missing in wiki tutorail -- application was installed at rssguard-build/src/rssguard/AppDir/usr directory, so I just copied it to my '/usr').

Also I tried to run it from konsole and got following output: [console.log](https://github.com/martinrotter/rssguard/files/3613494/console.log)

**Comment by martinrotter** [comment]
hello could you make some publicly available test instance which includes the error for me?

**Comment by zoxal** [comment]
Just configured new NextCloud instance to provide test environment for you aaand.. It worked. Connection to main instance works too. Maybe just messed up with my passwords (:

Sorry for lost time, closing this issue.

**Comment by martinrotter** [comment]
No problem, nice to hear it works. :)
