### ISSUE TITLE
RTL request

### ISSUE THREAD

**Issue by rtlUser** [martinrotter/rssguard#217]
This is a request to support feeds and categories for right-to-left languages.

Some rtl feeds are not automatically identified as such, and are displayed from left.
It is very uncomfortable to read.

If possible, can you add a check mark to manual identify such feeds on the properties of a feed/ category? (or any other implementation you think best).

RTL feeds will then be displayed as such on both the list and the reading pane.

1. 
2. 
3.

**Comment by martinrotter** [comment]
So some RTL feeds work and some do not? Can you post URLs of both situation? Possibly with screenshots?

**Comment by rtlUser** [comment]
Sadly, I don't have a link to a feed that look correct on RSS Guard.
I made 2 screenshots of the same feed. One from RSS Guard and the 2nd from another reader with the requested ability.
The general feed is:
https://internet-israel.com/feed/

The one viewed specifically is 2nd on the list, from Sunday, March 29, 2020, 7:07

When aligned to the left, it is impossible to read properly.

The 1st image is a proper RTL display:
![proper-rtl-example](https://user-images.githubusercontent.com/55591197/79757330-a051d400-8324-11ea-9805-0416f18306d3.jpg)

The 2nd is RSS Guard screenshot:
![RSSGuard-example](https://user-images.githubusercontent.com/55591197/79757489-d55e2680-8324-11ea-9518-2f7d797bbf42.jpg)

**Comment by martinrotter** [comment]
Which parts of user interface are important to be RTL?
Text of messages are even headlines in list of messages?

**Comment by martinrotter** [comment]
Notes
====
https://www.w3.org/International/questions/qa-html-dir - specifically look into `dir=auto` which automagically decides RTL state based on first printable character of the HTML element where it is used

**Comment by martinrotter** [comment]
```html
<html >

<body dir="auto">
עִבְרִ aaa bbb ccc
</body>
</html>
```

**Comment by rtlUser** [comment]
> 
> 
> Which parts of user interface are important to be RTL?
> Text of messages are even headlines in list of messages?

Both parts should be RTL.

In sentences or paragraphs are wrongly aligned, they mix words and numbers, or if there's a word in Latin characters, it is taken to one side making the whole line making it hard to make sense of.

As for the html example above, this is exactly why the feature is requested.

Since the RSS reader cannot decide what is the actual direction, the person using the reader needs the ability to set this manually, per feed.

**Comment by martinrotter** [comment]
@rtlUser Is **message** list now in screenshot in correct RTL mode?

![image](https://user-images.githubusercontent.com/1255302/79839573-fc643900-83b4-11ea-9c3c-ab7f91dd451b.png)

**Comment by rtlUser** [comment]
yes, it looks correct :-)

**Comment by martinrotter** [comment]
Just merged into master, RTL is switchable per feed in "Misc" tab. Needs extensive testing.
