### ISSUE TITLE
Loading images in messages

### ISSUE THREAD

**Issue by BlagoYar** [martinrotter/rssguard#218]
Can you do that?
That is, to be visible, not just links

**Comment by martinrotter** [comment]
What exact behavior do you want? Maybe post some screenshots because at this point webengine-based version of rssguard displays images in message just fine.

**Comment by moonburnt** [comment]
> What exact behavior do you want?

I think OP uses version without webengine and wants to get images in it. I like this idea, but iirc you've mentioned before that it would be way too complicated to implement

**Comment by dawidsowa** [comment]
It appears, that it can't display images in `media:thumbnail` and `media:content`.
[Example feed](https://backend.deviantart.com/rss.xml?q=special:dd)

**Comment by martinrotter** [comment]
Ok, I added M-RSS extension to "rss" parser and RSS Guard now should correctly determine thumbnails in those elements.

https://github.com/martinrotter/rssguard/commit/45e163ecba4ed4a092eeff23fe7a1d00cafce9a0
