### ISSUE TITLE
FR: Add option to have monochrome icons (MacOS)

### ISSUE THREAD

**Issue by asteingass** [martinrotter/rssguard#219]
#### Brief description of the issue.

Right now RSS Guard has a colored Icon in the top right status bar.

#### How to reproduce the bug?

1. Start RSS Guard
2. See top right status bar on MacOS, the icon is colored, most other icons are black & white.
3. 

#### What is the expected result?

1. There is an option to configure rather you want to have colored or black & white icon

**Comment by martinrotter** [comment]
I see. Will think.

**Comment by martinrotter** [comment]
![rssguard_mono](https://user-images.githubusercontent.com/1255302/80597297-ed6e2e00-8a27-11ea-8493-40ed84e2661c.png)
![rssguard_plain_mono](https://user-images.githubusercontent.com/1255302/80597300-ed6e2e00-8a27-11ea-9570-5649ab557bdd.png)

Would these grayish icons work? Or do they need to be somehow brighter? Darker?

**Comment by martinrotter** [comment]
Fixed, switchable in settings, change color to almost black, adjusted color of number of unread messages.
