### ISSUE TITLE
RSSGuard not updating feeds

### ISSUE THREAD

**Issue by An4cl3t0** [martinrotter/rssguard#220]
Hi,
RssGuard is not updating the feed (0). I'm on Arch Linux x64.

After reading the log I saw this line:
`[rssguard] CRITICAL: User wanted to update some feeds but all working threads are occupied. 
`
I'm on 2 core 2 thread Intel CPU. (SMT Disabled)

Thanks for your work.

**Comment by martinrotter** [comment]
Yes, this can happen if your PC is "occupied" by many running programs. Disabling SMT might be the actual cause of the error.

**Comment by Awem** [comment]
@martinrotter I am experiencing the same behavior with the same log files, but SMT is enabled. Also on Arch Linux x64 and RSS Guard 3.6.2.

**Comment by martinrotter** [comment]
See this: https://github.com/martinrotter/rssguard/issues/237
