### ISSUE TITLE
Built-in browser ignore proxy settings

### ISSUE THREAD

**Issue by moonburnt** [martinrotter/rssguard#222]
## Brief description of the issue.

Seems that rssguard follow proxy settings only to fetch feed data. E.g if you get some multimedia content inside (images, videos and such), it will be loaded directly, without using proxy.

#### How to reproduce the bug?

1. Add some feed with multimedia content (say, https://www.factorio.com/blog/rss )
2. Restart rssguard
3. Update said feed and open any message that feature images/videos
4. Check list of current online connections via your favorite tool for that purpose

#### What is the expected result?

All content inside feeds (both text and multimedia) should be loaded via proxy, if set.

#### What actually happened?

At least media (images, videos) seem to ignore proxy settings and load via default internet connection.

**Comment by martinrotter** [comment]
You mean version with webengine embedded browser or "nowebengine" version of RSS Guard?

**Comment by moonburnt** [comment]
I mean version with webengine embedded browser (and embedded browser is the one I meant under "built in browser")

**Comment by martinrotter** [comment]
Yes, proxy settings were so far applied only directly to downloading feed files, not to web browser. Will try to fix.

**Comment by martinrotter** [comment]
OK, so, try latest dev version and let me know, in my tests my new fixes worked.
