### ISSUE TITLE
Compile fails on 18.04

### ISSUE THREAD

**Issue by cement-head** [martinrotter/rssguard#224]
#### Brief description of the issue.

rssguard from git-clone fails to compile with MAKE command

#### How to reproduce the bug?

1. git clone the repo
2. run the qmake command
3. run the make command

#### What is the expected result?

rssguard should compile

#### What actually happened?
MAKE crashed
```
In file included from ../src/rssguard/main.cpp:5:0:
../src/librssguard/gui/dialogs/formabout.h:8:10: fatal error: ui_formabout.h: No such file or directory
 #include "ui_formabout.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
Makefile:455: recipe for target 'main.o' failed
make: *** [main.o] Error 1
```

**Comment by martinrotter** [comment]
testing rn

**Comment by martinrotter** [comment]
Tested on latest 18.04 with gcc/g++ and everything works.

https://pastebin.com/9NgDWm6e

**Comment by martinrotter** [comment]
Anyway, I moved FormAbout-related code to librssguard to make sure your error will go away. Try latest db4d07af.
