### ISSUE TITLE
Remove Duplicates?

### ISSUE THREAD

**Issue by cement-head** [martinrotter/rssguard#225]
Does RSSGuard have a "remove duplicates" feature and/or plug-in?

**Comment by martinrotter** [comment]
Hello, you mean remove "duplicate" messages? AFAIK, no. How should this feature work? How would "duplicity" of messages be recognized? By same title? Same URL? Across all feeds or only in the same feed?

RSS Guard avoids "duplicate" messages within one feed, quote from source code:

```cpp
  // Here we have query which will check for existence of the "same" message in given feed.
  // The two message are the "same" if:
  //   1) they belong to the same feed AND,
  //   2) they have same URL AND,
  //   3) they have same AUTHOR AND,
  //   4) they have same title.
```

**Comment by Eleferen** [comment]
Hello. rssguard is the best rss reader! Thank you for developing it.

This feature would be very useful. You can put this in the settings, for example like this:
![image](https://user-images.githubusercontent.com/15795413/83105694-cc9b0600-a0c3-11ea-963c-4bb8ea15e5ad.png)

Very often I encounter duplicate messages when the author changes the title. Example:
![image](https://user-images.githubusercontent.com/15795413/83106159-aa55b800-a0c4-11ea-9869-07502687dabb.png)

This is the same article!

**Comment by martinrotter** [comment]
Should this feature work automatically when new messages get downloaded or as command for example from "Tools" menu?

**Comment by Eleferen** [comment]
I think it should work automatically when downloading new messages.

**Comment by martinrotter** [comment]
@Eleferen So that when RSS Guard downloads new messages and some message meets certain rules (has same title OR/AND ...) then certain action should be done (skip from downloading, mark as read, ...).

Thus, this functionality could be added as part of more general "filtering messages when downloading" mechanism #31 .

**Comment by martinrotter** [comment]
I will close this, all events regarding this feature will now be in #31.
