### ISSUE TITLE
rssguard installed with flatpak on linux debian testing - Nothing runs.

### ISSUE THREAD

**Issue by gillesMioni** [martinrotter/rssguard#226]
Hi
I configured rssguard with standard online feeds and created a local account.
When I tried to import a opml file, nothing happened when I confirmed to fetch feeds online:  
No operation launched and that's all.
I configured an external  web browser but I can't use it.
In fact, I would like to know what's the problem ?

**Comment by martinrotter** [comment]
I will try to take a look via Debian Testing and Arch Linux in coming days. Standard packages work, must be something flatpak related.

**Comment by martinrotter** [comment]
OK, tested on fresh unstable Debian + stable flatpak `rssguard` package. Everything seems to work, cannot reproduce your problems.

Perhaps launch rssguard from terminal and see its command line output which might signalize the problem.

https://streamable.com/d3naf6
