### ISSUE TITLE
No Highlights in submenu for dark theme

### ISSUE THREAD

**Issue by soo-shan** [martinrotter/rssguard#227]
#### Brief description of the issue.
When on dark skin, sub-menus in file menu does not appear highlighted. 
Although sub menus work.

#### How to reproduce the bug?

1. Select dark skin from Tools > Settings > User Interface > Icons & Skins
2. Select any sub menu from file menu

#### What is the expected result?
Sub-menu should show be highlighted.

#### What actually happened?
Sub-menus are not hightlighted

#### Other information (logs, see Wiki)
Using Flatpak on ClearLinux (64 bit)

Sorry I'm not able to take a screenshot with file menu activated. Let me know in case issue is not clear.

**Comment by martinrotter** [comment]
fixed, test it in latest dev build and let me know if it is ok for you :)

**Comment by soo-shan** [comment]
Sorry I switched to light mode and forgot about this issue. :)
I'm using flatpak with RSS Guard version 3.5.9 and it appears to be fixed. 
Thanks
