### ISSUE TITLE
fail to read an atom rss

### ISSUE THREAD

**Issue by pipiscrew** [martinrotter/rssguard#228]
using **v3.5.9**

and trying 

> https://github.com/martinrotter/rssguard/issues

getting :

> Result : unknown content

the feed starting with 
`<feed xmlns="http://www.w3.org/2005/Atom" `

**Comment by martinrotter** [comment]
can you post URL of not-working atom feed?

**Comment by pipiscrew** [comment]
hmmm, when a feed contain **link tag** as 

> <link>https://www.test.com/partner/jobListing.htm?pos=105&ao=878128&s=58&guid=00000171939678809f23777055fa9489&src=GD_JOB_AD&t=SR&extid=1&exst=OL&ist=&ast=OL&vt=w&slr=true&cs=1_586bc1ee&cb=1587319044559&jobListingId=3535978924</link>

cant fetch metadata due 
**&ao=87**

**Comment by martinrotter** [comment]
> hmmm, when a feed contain **link tag** as
> 
> > https://www.test.com/partner/jobListing.htm?pos=105&ao=878128&s=58&guid=00000171939678809f23777055fa9489&src=GD_JOB_AD&t=SR&extid=1&exst=OL&ist=&ast=OL&vt=w&slr=true&cs=1_586bc1ee&cb=1587319044559&jobListingId=3535978924
> 
> cant fetch metadata due
> **&ao=87**

Your URL shows 404, it is not valid feed URL...

**Comment by pipiscrew** [comment]
hi, 

I sent you an email @**gmail** with subject **228**

**Comment by martinrotter** [comment]
@pipiscrew I checked, the XML file is not valid, it contains unescaped `&` characters which should be escaped to `&amp;`.
