### ISSUE TITLE
Font size in message window seems abnormally small.

### ISSUE THREAD

**Issue by Gooberslot** [martinrotter/rssguard#23]
#### Brief description of the issue.

Font size in message window seems abnormally small

#### How to reproduce the bug?

1.  Open message in RSS Guard
2.  Compare font size to another program using the same font
3.  Nothing else

#### What is the expected result?

Fonts should be same size

#### What actually happened?

Font in RSS Guard is much smaller.

#### Other information (logs, see Wiki)

I'm attaching a picture showing RSS Guard and Mousepad both using the Arial Unicode font set to 10 point size.
![screenshot_2016-06-25_01-18-46](https://cloud.githubusercontent.com/assets/7566965/16355118/439f634c-3a73-11e6-9855-9988b90128c1.png)

**Comment by martinrotter** [comment]
You can persistently tweak font in Tools -> Settings -> Feeds & messages -> Messages. Let me know if that solution is fine for you.

**Comment by Gooberslot** [comment]
Yeah, that works. I just thought this was a bug and should be reported.

**Comment by martinrotter** [comment]
Default font is just taken from the WebEngine library. If it is really that small, it is probably upstream bug. Glad to hear setting works for you.
