### ISSUE TITLE
copy url on feeds listview

### ISSUE THREAD

**Issue by pipiscrew** [martinrotter/rssguard#231]
will be more friendly when user do a right click to a feed item, to have have 'Copy URL' option, because doesnt want to browse and share it somewhere. When multiselection copy all URLs.

**Comment by martinrotter** [comment]
Is accessible in context menu and also in "Feeds/categories" menu. Context menu item is accessible for feeds/categories/account nodes. When category/account is selected and action triggered then all URLs are copied to clipboard, separated with newlines.
