### ISSUE TITLE
RSSGuard's repo on Flathub is still on version 3.5.9

### ISSUE THREAD

**Issue by mbrav** [martinrotter/rssguard#236]
Hi, just today I wanted to try out RSS Guard and am liking it very much given that it is a cross-platform client. However, I also noticed that [its repo on Flathub](https://flathub.org/apps/details/com.github.rssguard) is still on version 3.5.9 and was last updated on June 4, 2019.

**Comment by martinrotter** [comment]
yes, because it is not updated automatically, i believe flathub guys should do that, or have some kind of automation for it, i will try to update it by hand.

**Comment by martinrotter** [comment]
ok i merged it should be ready on flathub in few hours or days, depending on how fast they update repo db

**Comment by mbrav** [comment]
Just updated to 3.6.2 trough Flathub, thanks!
