### ISSUE TITLE
Feed updating problems - metaticket

### ISSUE THREAD

**Issue by martinrotter** [martinrotter/rssguard#237]
I merged tickets related to feed updating to this metaticket to better track our fixing of the situation.

Original tickets were:
https://github.com/martinrotter/rssguard/issues/195
https://github.com/martinrotter/rssguard/issues/148
https://github.com/martinrotter/rssguard/issues/177

So our checklist is:
- [x] feed updates throttle all CPU cores at 100%,
- [x] some feeds do not update when running via auto-update,
- [x] update process sometimes never ends (particularly when using TT-RSS plugin).

**Comment by martinrotter** [comment]
I rewrote feed update mechanism, now some (if not all) problems should be addresed. Could you please test newest development build to see if feed update mechanism behaves better now?

https://github.com/martinrotter/rssguard/commit/2c6afa1bb7c8b1854ccb9520b24a24a4234d9ec1

This is the commit, download newest builds [here](https://bintray.com/martinrotter/rssguard/Development/Windows#files/).

**Comment by martinrotter** [comment]
Also there is now work on related ticket #199 which will speed-up feed updates for TT-RSS plugin.

**Comment by Awem** [comment]
@martinrotter I just checked 5748bf983f2fce8127694eec8677cca4574fee56 and the issue described in https://github.com/martinrotter/rssguard/issues/220#issuecomment-636308664 is still present.

**Comment by martinrotter** [comment]
@Awem Please, double check what version/build you are testing because "User wanted to update some feeds but all working threads are occupied" was literally removed from code base, no such error/debug message is present in latest [master] branch code. Try for example this build:

https://ci.appveyor.com/project/martinrotter/rssguard/builds/33290294/job/3s8nqmpktlgnfoam/artifacts

**Comment by Awem** [comment]
@martinrotter You are right: The "User wanted to update some feeds but all working threads are occupied" message was logged before I updated RSS Guard. I edited my post above so that it reflects the CRITICAL and WARNING log entries I see with the current revision.
This is what the `About RSS Guard` modal shows inside the application:
```
RSS Guard
Version: 3.6.3 (built on Linux/x86_64)
Revision: 5748bf98
Build date: 6/3/20 2:43 PM
Qt: 5.14.2 (compiled against 5.14.2)
```

**Comment by martinrotter** [comment]
@Awem So what exactly happens? Some feeds do no update? Are that always the same feeds? Does it happen only for Nextcloud feeds?

**Comment by Awem** [comment]
@martinrotter All of my feeds fail to update, but also ALL of them are Nextcloud feeds. I just noticed, that even the "sync in" command on the Nextcloud account node does not have any effect. I see the following relevant log entries on "sync in":
```
There is request to reload feed model, reloading the 1 items individually.
Settings of BaseNetworkAccessManager loaded.
ownCloud: Obtaining of categories failed with error 204.
```

I just tried adding a new "Standard online feeds" account with the default set of feeds. It is working and updating fine. So it is clearly related to Nextcloud account. I could try removing that account and adding it again.

**Comment by martinrotter** [comment]
Make sure that it all works when testing connection in "Edit account" dialog. I did testing on nextcloud in virtualbox and it all just seems to work. I mean it is not super-fast or super feature rich but the basic nextcloud features should work out of the box.

HTTP/204 error means "there is nothing here to download" which is basically an error which says that you are in the wrong place.

Make sure that you have correct IP/domain used when connecting to server, your credentials are ok etc.

**Comment by Awem** [comment]
Well, the Nextcloud account used to work in 3.6.0. So, the configuration was correct. I now checked again. The password field was empty so I added it again. Then on "Test setup" it says:
```
Selected ownCloud News server is running unsupported version (). At least version 6.0.5 is required.
```

Seems, that the version could not even be retrieved. The log says:
```
ownCloud: Obtaining status info failed with error 204.
```

If I add `index.php` after the server URL it says:
```
Unspecified error, did you enter correct URL?
```

So, it seems that the original URL was correct. Maybe some API changes? I am running Nextcloud 18.0.4 and News 14.1.11.

**Comment by martinrotter** [comment]
It is just weird. When I was testing it, I simple entered "https://IP-ADDRESS" to appropriate textbox and it just worked. Error 204 is just weird.

Is your nextcloud instance somehow testable for me? Accessible from internet?

**Comment by Awem** [comment]
@martinrotter I send the link to the instance to your Gmail

**Comment by martinrotter** [comment]
Test latest development build / there is MAJOR feed fetching mechanism overhaul.
