### ISSUE TITLE
3.6.3 build

### ISSUE THREAD

**Issue by pavroo** [martinrotter/rssguard#239]
#### Brief description of the issue.
Hi
I build RSSGuard on Debian, the latest 3.6.3 on testing, due it requires Qt newer than 5.7 (5.12 on testing), but the build failed. 
#### How to reproduce the bug?

`from moc/moc_googlesuggest.cpp:9:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h: In instantiation of ‘static void QScopedPointerDeleter<T>::cleanup(T*) [with T = Downloader]’:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h:107:25:   required from ‘QScopedPointer<T, Cleanup>::~QScopedPointer() [with T = Downloader; Cleanup = QScopedPointerDeleter<Downloader>]’
moc/../../../../src/librssguard/network-web/googlesuggest.h:46:7:   required from here
/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h:57:40: error: invalid application of ‘sizeof’ to incomplete type ‘Downloader’
   57 |         typedef char IsIncompleteType[ sizeof(T) ? 1 : -1 ];
      |                                        ^~~~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h: In instantiation of ‘static void QScopedPointerDeleter<T>::cleanup(T*) [with T = QListWidget]’:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h:107:25:   required from ‘QScopedPointer<T, Cleanup>::~QScopedPointer() [with T = QListWidget; Cleanup = QScopedPointerDeleter<QListWidget>]’
moc/../../../../src/librssguard/network-web/googlesuggest.h:46:7:   required from here
/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h:57:40: error: invalid application of ‘sizeof’ to incomplete type ‘QListWidget’
g++ -c -pipe -std=c++17 -O3 -std=gnu++1z -Wall -W -D_REENTRANT -fPIC -DAPP_VERSION="\"3.6.3\"" -DAPP_NAME="\"RSS Guard\"" -DAPP_LOW_NAME="\"rssguard\"" -DAPP_LOW_H_NAME="\".rssguard\"" -DAPP_LONG_NAME="\"RSS Guard 3.6.3\"" -DAPP_AUTHOR="\"Martin Rotter\"" -DAPP_EMAIL="\"rotter.martinos@gmail.com\"" -DAPP_URL="\"https://github.com/martinrotter/rssguard\"" -DAPP_URL_ISSUES="\"https://github.com/martinrotter/rssguard/issues\"" -DAPP_URL_ISSUES_NEW="\"https://github.com/martinrotter/rssguard/issues/new\"" -DAPP_URL_WIKI="\"https://github.com/martinrotter/rssguard/wiki\"" -DAPP_USERAGENT="\"RSS Guard/3.6.3 (github.com/martinrotter/rssguard)\"" -DAPP_DONATE_URL="\"https://martinrotter.github.io/donate\"" -DAPP_SYSTEM_NAME="\"Linux\"" -DAPP_SYSTEM_VERSION="\"x86_64\"" -DAPP_REVISION="\"\"" -DQT_USE_QSTRINGBUILDER -DQT_USE_FAST_CONCATENATION -DQT_USE_FAST_OPERATOR_PLUS -DUNICODE -D_UNICODE -DUSE_WEBENGINE -DRSSGUARD_DLLSPEC=Q_DECL_EXPORT -DQT_NO_DEBUG -DQT_WEBENGINEWIDGETS_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB -I../../../src/librssguard -I. -I../../../src/librssguard -I../../../src/librssguard/gui -I../../../src/librssguard/gui/dialogs -I../../../src/librssguard/dynamic-shortcuts -Iui -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebChannel -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtPositioning -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Imoc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o moc_adblocksubscription.o moc/moc_adblocksubscription.cpp
make[1]: *** [Makefile:6966: moc_googlesuggest.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/media/pavroo/dysk2-2/pakiety/rssguard/bullseye/rssguard-3.6.3~sparky6~0/rssguard-build/src/librssguard'
make: *** [Makefile:48: sub-src-librssguard-make_first-ordered] Error 2`

Any suggestions, please?

**Comment by martinrotter** [comment]
Honestly, I have no idea. Maybe just clone the git repo and try to build in Qt Creator and fix the errors as they appear.

In my opinion, the file `googlesuggest.h` looks OK. All `#include`s are there, it should work. Maybe some old compiler?

**Comment by pavroo** [comment]
As you suggested, I updated gcc from Debian experimental repos to version 10 and the latest 3.7.0 build passed ok, thanks.
It means can't be compiled on Debian stable or testing with the present gcc 8 or 9.
