### ISSUE TITLE
Update all items not working correctly

### ISSUE THREAD

**Issue by Kehom** [martinrotter/rssguard#24]
#### Brief description of the issue.

Feeds are not getting automatically updated at all. So I have to manually click the "Update all items" from the "Feeds & categories" menu. Problem is, since 3.3.x, it still does not update all feeds

#### How to reproduce the bug?

1. Open RSS Guard
2. Menu Feeds & categories -> Update all items

#### What is the expected result?

Update all feeds, including subcategories

#### What actually happened?

Only a few of the feeds got updated

#### Other information (logs, see Wiki)

I suspect that, tied to this problem, RSS Guard is displaying the wrong number of unread messages within each feed entry

**Comment by martinrotter** [comment]
Please, write the exact steps to reproduce the problem.

**Comment by martinrotter** [comment]
Probably related/duplicate to #26, #27. All these three bugs are symptoms of one specific code flow, which I will fix with a few days.

**Comment by Kehom** [comment]
Hey, sorry the format for the report was not in the desired way. Edited the report to be within the requested format.
Also, in my mind I didn't think I reported two issues because I believe (of course I could be completely wrong here) the number of unread messages not being the correct value to be tied to the reported issue.
Anyway, again, sorry I didn't follow the template

**Comment by martinrotter** [comment]
Thanks for editing.

When you try to repeatedly update all items, does it still update the SAME feeds and skips SAME feeds? Or does it eventually update all feeds?

**Comment by Kehom** [comment]
Well, it seems to be completely random. I see bellow, at the status bar, the message which tells "updating XYZ feed", which I believe goes over all of my feeds but most of them actually don't get any update.

I don't know if this info will help, but I upgraded from 2.3.1 (which didn't have this problem) to 3.2.0.
V3.2.0 does update everything when I click the menu option however the automatic updates (periodic thing) does not.

**Comment by martinrotter** [comment]
I see. I will check this stuff. I am unfortunately too busy right now, give me time, pls. :)

**Comment by martinrotter** [comment]
Can you provide debug log? See Wiki for more info.

**Comment by martinrotter** [comment]
Can you test latest available code c0824c3885db36cb2c9071c874090eb9b9fb3075 to check if the bug is solved?

**Comment by martinrotter** [comment]
I believe this is fixed, marking as fixed.
