### ISSUE TITLE
[Improvement] Add "starred articles" folder/item on the feed tree/list (also for TT-RSS))

### ISSUE THREAD

**Issue by dariottolo** [martinrotter/rssguard#240]
#### Brief description of the issue.

It's not an issue, but a request. TT-RSS allows to star articles, which are then available in a separate category.

RSS Guard is sort of compatible because if you change the importance of an article, it is added to the starred articles in TT-RSS.

Unfortunately, it is not possible to consult the category "starred", allowing to manage those previously starred articles

#### How to reproduce the bug?

1. add an account based on TT-RSS
2. have some starred articles

#### What is the expected result?

on the left panel, there should be a category named starred

#### What actually happened?

the category is not there

**Comment by martinrotter** [comment]
Starting to work on this, it will add universal "Important messages" meta node in the feed tree and it **will work for all account types**, not just TT-RSS.

![image](https://user-images.githubusercontent.com/1255302/84119979-74ee8a00-aa35-11ea-8098-5b528d8023c4.png)
