### ISSUE TITLE
Mark message as ready when scrolled out of viewport in message list

### ISSUE THREAD

**Issue by pcause** [martinrotter/rssguard#241]
A common feature of many RSS readers is to have an option to mark messages read as they scroll off the top of the screen while reading.  This would be a very useful option

added:  If I select an item and then use the arrow keys to walk down the list items get marked as read, but not when I scroll.  Scrolling is more convenient and faster.

**Comment by martinrotter** [comment]
Well, this feature is common in web-based feed viewers and I am familiar with it. I just cannot imagine it being useful in regular desktop application and myself I am not a fan of this kind of functionality.

Perhaps if there was many more interested people, there would be some actions from me in this regard. :)

**Comment by pcause** [comment]
RSSOwl has this, for example as did a number of other popular feed reders.  Also several android readers do this, not just web based.

**Comment by martinrotter** [comment]
So, correct me if I am wrong, in other words, the feature would work like this if enabled:
1. Message item becomes visible.
2. Message item becomes invisible because it is scrolled out of viewport.
3. Mark this message as read.

**Comment by pcause** [comment]
yes, but item 2 is scrolled out of the top of the viewport.

**Comment by martinrotter** [comment]
I don't want to personally implement this by myself, maybe someone else can and if somebody does implement this, then I will be happy to merge. :)
