### ISSUE TITLE
syncing status back to tt-rss

### ISSUE THREAD

**Issue by pcause** [martinrotter/rssguard#242]
having status syn'ed back to tt-rss regularly would be a very useful addition.  for example, if unread count for a feed/category goes to zero, sync back the status to the server.  what the tt-rss android client does is sync back after an idel period whatever items have changed.  period is relatively short.  since a user might be using both mobile and desktop having this happen automatically and without too long a lag is important.

**Comment by martinrotter** [comment]
Wait. This feature you describe is already included in RSS Guard for ages and should work OUT OF BOX.

RSS Guard caches all message state changes (read, unread, starred, unstarred) and in regular interval pushes changes to TT-RSS server. This should happen ONCE a MINUTE.

Are you saying that if you for example mark a message as starred then this change is not propagated to TT-RSS server after you wait for one/two minutes?

**Comment by pcause** [comment]
OK, I wasn't waiting long enough.  It did mark as important and sync.

**Comment by martinrotter** [comment]
OK, maybe we could talk about the syncing period being configurable or shorter....
