### ISSUE TITLE
duplicate items in rssguard

### ISSUE THREAD

**Issue by pcause** [martinrotter/rssguard#245]
using a feed, in atom format, created by tt-rss.  you can get a URL for the "labels" category and an atom feed is returned.  the feed is an atom feed (root element is "<feed>" if an item is there it is always there until you have marked as read.  i noticed that if i have not read any items and rssguard is fetching the feed multiple times, an item appears many times.  the items all have identical ids and update times on each fetch.  I tested this.  the spec says that if it has same ID and update time you shouldn't add the item a second time.

here is a sample item in the feed:

```
<entry>
<id>tag:not.myserver.com,2020-06-16:/237743</id>
<link href="https://www.reddit.com/r/chromeos/comments/habee4/factory_reset_my_chromebook_and_diskspace_is/" rel="alternate" type="text/html"/>
<title type="html">
Factory reset my chromebook and diskspace is still being used up
</title>
<summary type="html">
<p>submitted by /u/Icook_Tacos [link] [comments]</p>
</summary>
<content type="html">
<p> submitted by <a href="https://www.reddit.com/user/Icook_Tacos" rel="noopener noreferrer" target="_blank"> /u/Icook_Tacos </a> <br> <span><p><a href="https://i.redd.it/s2jrgm0yub551.png" target="_blank" rel="noopener noreferrer">https://i.redd.it/s2jrgm0yub551.png</a></p><br><a href="https://i.redd.it/s2jrgm0yub551.png" rel="noopener noreferrer" target="_blank">[link]</a></span> <span><a href="https://www.reddit.com/r/chromeos/comments/habee4/factory_reset_my_chromebook_and_diskspace_is/" rel="noopener noreferrer" target="_blank">[comments]</a></span></p>
</content>
<updated>2020-06-16T19:56:02+00:00</updated>
<author>
<name>/u/Icook_Tacos</name>
</author>
<source>
<id>https://www.reddit.com/r/chromeos/</id>
<link rel="self" href="https://www.reddit.com/r/chromeos/"/>
<updated>2020-06-16T19:56:02+00:00</updated>
<title>chromeos</title>
</source>
<category term="chromeos"/>
</entry>
```
each time fetched the feed returns this exact text for the item.  i think this is a bug and you need to not insert if the id and update time, if it exists, are identical.

**Comment by martinrotter** [comment]
Please, post url of such a feed? Do I need any tt-rss plugins or so to get it?

**Comment by pcause** [comment]
I unfortunately can't.  private server.  if you have a tt-rss server available it is a standard feature and you can test with any server.  I can also add the full XML here if that helps.

**Comment by martinrotter** [comment]
I don't know TT-RSS much, I have it running in virtualbox, how to get the URL of such a feed to test?

**Comment by martinrotter** [comment]
OK, I tested and this feed gets generated https://pastebin.com/JQccEyPp

I updated it several times and no duplicates appeared. Pls, post full contents of your feed.

**Comment by martinrotter** [comment]
Pls, post full contents of your feed.

**Comment by pcause** [comment]
i deleted and was doing another way.  just added back on latest test build and will send what I verify results and that i'm seeing duplicates again.

**Comment by pcause** [comment]
figured it out and will close.  two issues:

A) the URL tt-rss generates will always give back articles even if none are unread.  You have to add "&view-mode=unread" to get only unread articles.
B)  I forgot that I have filters in tt-rss that can create more than 1 match for an article.  so it can appear multiple times if you fetch each label feed.

**Comment by martinrotter** [comment]
Glad to hear it's solved. :)
