### ISSUE TITLE
Feed sorting is case sensitive - make it case INsensitive

### ISSUE THREAD

**Issue by pcause** [martinrotter/rssguard#247]
What does the down/up mean in sorting categories.  I click on the feed column of a category to get an up arrow and it is sorted by ascending feed name.  I go to another category and the up is shown but the category is sorted by feed with descending alphabetic order by feed.  If I click for down I get ascending but if I go back to the first category it is now showing down and sorted by desending feed name.

A)  Are category sort orders remembered?
B)  If not, shouldn't I keep the same sort order as I switch categories?

Almost like when I switch the sort, the other feeds are flipped in sort order from what they were and don't keep what they had and so the arrow points incorrectly and the old order is lost

**Comment by martinrotter** [comment]
Can you post screenshots? Are we talking about feed list?

Those headers are simply there to sort the whole list. If arrow is up, everything should be sorted hierarchically alphabetically in ascending order. Except "static" items such as "Important messages" or "Recycle bin" which are always shown at the bottom of the list.

**Comment by martinrotter** [comment]
And

A - yes, global sort order/column is remembered. So if you sort the list in descending order according to column "Title" it is resorted when app starts again.
B - honestly I am not sure if I understand, but there is only one sort order/column. same for everything.

**Comment by pcause** [comment]
OK, just figured it out.  the sort is case sensitive.  so "c" is before "T" when sorting.  Not what I expected/wanted but my error.

**Comment by martinrotter** [comment]
Sorting is done with "locale-aware comparison" [method](https://doc.qt.io/qt-5/qstring.html#localeAwareCompare-1), but it really seems that in some locales/cases the comparison is trully case sensitive.

I fix this now to make comparison locale-aware and case INsensitive in the same time, it will make more sense.
