### ISSUE TITLE
"error":"redirect_uri_mismatch" when trying to setup a new inoreader account

### ISSUE THREAD

**Issue by mpr0st** [martinrotter/rssguard#254]
#### Brief description of the issue.

When trying to setup a new inoreader account, in a clean RSS Guard portable installation, after pressing Login button a browser opens pointing to:
https://www.inoreader.com/oauth2/auth?client_id=1000000604&scope=read%20write&redirect_uri=http://localhost:13377&response_type=code&state=26500&prompt=consent&access_type=offline
, but this URL displays this error (this is the text of the webpage):
{"error":"redirect_uri_mismatch","error_description":"The redirect URI provided is missing or does not match","error_uri":"http:\/\/tools.ietf.org\/html\/rfc6749#section-3.1.2"}

#### How to reproduce the bug?

1. New portable RSS Guard 3.7.0 installation.
2. Try to setup a new inoreader account.
3. Authenticate with inoreader.

#### What was the expected result?

The Oauth2 authentication process continues.

#### What actually happened?

The Oauth2 authentication process stops with the error stated above.

#### Other information (logs, see Wiki)

netstat correctly shows RSS Guard listening on port 13377:
C:\Windows\system32>netstat -a -b

Active Connections
  Proto  Local Address          Foreign Address        State
  TCP    127.0.0.1:13377        127.0.0.1:0                  LISTENING
 [rssguard.exe]

Thank you very much!

**Comment by martinrotter** [comment]
Hello @mpr0st. Yes, I have identified the issue and it seems to be a regression bug I introduced by mistake to latest 3.7.0 version. I am very sorry to cause you trouble. I will try to fix in a few days.

Problem is that OAuth redirect listening address is currently hardcoded in RSS Guard and I mistakenly changed it to "http://localhost:13377" which is NOT set in RSS Guard "application".

You can, however, create your own "developer application". Go to your Inoreader settings and select "Developer". Then choose "New Application" and set redirect URI to "http://localhost:13377" and copy App ID and App key to your account settings in RSS Guard.

**Comment by martinrotter** [comment]
OK, I fixed the issue and now PORT of listening server is not hardcoded anymore. Note that predefined redirect URL of built-in Inoreader App ID is "http://localhost" with port 80, which might need admin privileges on some operating systems, therefore ensure that your OS is configured properly.

Or create your own [Application ID](https://www.inoreader.com/developers/register-app) and do not use predefined one and also you can define your own redirection PORT in the process.

![image](https://user-images.githubusercontent.com/1255302/88368237-ebe5a500-cd8d-11ea-87f3-925b4060bd9e.png)

**Comment by martinrotter** [comment]
@mpr0st Can you please download https://dl.bintray.com/martinrotter/rssguard/rssguard-3.7.1-e1a73c9-nowebengine-win64.7z and test it if the problem is solved?

**Comment by mpr0st** [comment]
Version 3.7.1 worked like a charm, thank you!! It worked without creating my own application, but, as per your recommendation, I ended up creating one.

Thank you!!!

**Comment by martinrotter** [comment]
@mpr0st You're welcomed. Feel free to suggest any enhancements to Inoreader plugin or report any bugs if they happen.

Thnk y.

**Comment by DDzwiedziu** [comment]
On Linux I'm getting constantly this error ("The redirect URI provided is missing or does not match"), no matter what port I use 80 (not available to the regular user without accessing superuser privileges), 8080, 13377, 14555, 18080.
The sync only started when I've made my custom app, and used it's API credentials on port 18080.
