### ISSUE TITLE
Error: operation canceled 

### ISSUE THREAD

**Issue by Qabbout** [martinrotter/rssguard#256]
#### Brief description of the issue.

Sometimes I'm getting this error when I try to download a torrent file from the RSS message, even though I'm able to download it from the website normally.

#### How to reproduce the bug?

1. Open a message that contains a torrent URL.
2. Press the URL button.

#### What was the expected result?

To fully download the torrent file

#### What actually happened?

Error: operation canceled. and the percentage stops at 58%

#### Other information (logs, see Wiki)

[log.txt](https://github.com/martinrotter/rssguard/files/5004190/log.txt)

**Comment by martinrotter** [comment]
Can you post such an URL which does not work here?

**Comment by Qabbout** [comment]
Sure, this one for example: https://nyaa.si/download/1267070.torrent

**Comment by martinrotter** [comment]
I fixed, test dev. build and let me know if it works now.

Sadly, the source code for "Download manager" feature of RSS Guard is very poorly written (it was adapted from another project in ancient RSS Guard times) and if there will be more problems, then it is prime candidate for total reconstruction and simplification.

**Comment by Qabbout** [comment]
Yes it's working now, thank you for that hotfix.
