### ISSUE TITLE
Аpplication crash after selecting a feed in "Message filters" (v3.7.0)

### ISSUE THREAD

**Issue by Eleferen** [martinrotter/rssguard#257]
#### Brief description of the issue.

Аpplication crash after selecting a feed in "Message filters"

#### How to reproduce the bug?

1. Menu Messages-->Message filters
2. Click on any feed.

#### What was the expected result?

No application crash. Feed selected

#### What actually happened?

Аpplication crash

#### Other information

Version: 3.7.0 (built on Windows/x86_64)
Revision: a695a4f
Build date: 7/13/20 9:52 AM
Qt: 5.14.2 (compiled against 5.14.2)

Localisation: Russian (does not affect bug reproduction)
Windows 10 64bit

[log.txt](https://github.com/martinrotter/rssguard/files/5007919/log.txt)

![image](https://user-images.githubusercontent.com/15795413/89053502-f7256b80-d35f-11ea-8ce0-46eb7ad07642.png)

**Comment by martinrotter** [comment]
Oh yes, I see the problem. I will fix soon. Before that, try to click "Add new" button first to actually create new filter and THEN assign it to feeds by clicking on them. Will fix, thx.

**Comment by martinrotter** [comment]
Should be fixed now, can you try latest dev build in one hour from now?

**Comment by Eleferen** [comment]
> Should be fixed now, can you try latest dev build in one hour from now?

All OK, thanks
