### ISSUE TITLE
message filters - access to labels from tt-rss

### ISSUE THREAD

**Issue by pcause** [martinrotter/rssguard#260]
one of the items that tt-rss passes back is a set of labels.  these are assigned by filters on the server side.  can you add these as part of the msg object?  for non-tt-rss sources this is just an empty.  This can be used to signal actions to the client filters.  for example, for certain labels i might want to set important.  Or I might want to add "label:label-value" to the content to make searching for certain content easier as I've already done pre-processing on the server and know what I want.  Or if you add tags to the client we could use this to set tags in the client.

**Comment by martinrotter** [comment]
At this point labels are not fetched/parsed into `MessageObject` at all. Would you want to synchronise message labels BACK to TT-RSS server too? Or just have it "read-only" and do some actions based on their value? Or would you need labels "writable" so that your change in labels would propagate to the server?

Read-only access to labels could be probably added relatively easily but adding full-blow label synchronization would be a major feature, which I plan to add too, but it will take quite some time. Also, note there are some labels-related tickets already.

So let me know.

#38 #102

**Comment by pcause** [comment]
A first step would be to just put them in the message object for filters.  As you say, since the API returns this for all messages, pretty easy.

Sync back would be great, but perhaps an intermediate step would be to add tagging for all feeds.  A user could add a tag to any item, from a filter or the GUI and have a way to search for tags.  Eventually these could be syned back.  But just adding tagging would be a huge win.  The tt-rss labels can then be stored as tags, and we could get the equivalent of the label feed by searching for unread items that match a tag.

**Comment by mpr0st** [comment]
I second the petition for being able to manage labels in the filters (read, but specially, write) and syncing them back to the server (in my case, Inoreader). This will give a new dimension to the already great filtering system.

Thank you!

**Comment by martinrotter** [comment]
It seems that the actual "label/tag" functionality is the last big and really wanted feature to be added to RSS Guard anyway, so I will likely start coding it soon so that RSS Guard will offer full-blown label features, including interfacing via msg. filters.

**Comment by pcause** [comment]
That would be terrific.  Thanks.  Just a reminder, in ttrss  an item can have multiple labels.

**Comment by martinrotter** [comment]
> That would be terrific. Thanks. Just a reminder, in ttrss an item can have multiple labels.

Sure, allowing only one label per an item would be a heresy.

**Comment by pcause** [comment]
couple of other thoughts and forgive me if you've got these on your todo list:

- add a virtual feed called tags or labels or whatever you decide to call these, like you do for important.  that way user can see all labeled items.  put label name in the column where you'd have feed.  question is that to do for items with multiple labels.  could show them on mouse over in the feed column.
- for search on regular feeds some syntax that says look for a label is needed.  perhaps label;value
- a menu item to edit labels.  allows adding, deleting, changing.

**Comment by martinrotter** [comment]
@pcause 
> * for search on regular feeds some syntax that says look for a label is needed.  perhaps label;value

Can you elaborate? I did not fully understand what you try to say, sorry. 👍

Btw, I create sub-feature list in #102, check it out.

**Comment by martinrotter** [comment]
I merged this ticket to #102.
