### ISSUE TITLE
When feed contains entries older than today

### ISSUE THREAD

**Issue by pipiscrew** [martinrotter/rssguard#264]
the application displays **only the today** entries. Couldnt find any configuration, this is sad :(

**Comment by martinrotter** [comment]
Can you please post URL of some feed where this problem is visible? RSS Guard should download **ALL** entries available on a feed.

**Comment by martinrotter** [comment]
No response, closing. Feel free to reopen if you provide detailed steps to reproduce the issue, video, whatever. :)
