### ISSUE TITLE
accented characters not displaying correctly

### ISSUE THREAD

**Issue by mpr0st** [martinrotter/rssguard#268]
#### Brief description of the issue.

Accented characters are showing garbled in message list and are not being seen by the filters (maybe related to #267).

#### How to reproduce the bug?

1. Subscribe to a feed which contains messages with accented characters in the title (such as http://feeds.weblogssl.com/vayatele2).
2. Update 

#### What was the expected result?

The messages show the full title in the message list, for example: Las nueve mejores películas... If there's any filter expecting, for example, "películas" in the title, the message gets correctly filtered.

#### What actually happened?

The messages show an erroneous title: `Las nueve mejores pel&iacute;culas...`

![image](https://user-images.githubusercontent.com/49242687/91015695-dc0aec00-e5eb-11ea-8146-6bf2c80f9370.png)

The messages don't get filtered.

#### Other information (logs, see Wiki)

Thank you.

**Comment by martinrotter** [comment]
Can you please test this development build and check bug is still present?

https://bintray.com/martinrotter/rssguard/download_file?file_path=rssguard-3.7.1-b36e84b-win64.7z

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/91019622-918c6e00-e5f1-11ea-8fb0-d85ce6dd381f.png)

**Comment by mpr0st** [comment]
> Can you please test this development build and check bug is still present?
> 
> https://bintray.com/martinrotter/rssguard/download_file?file_path=rssguard-3.7.1-b36e84b-win64.7z

Hmmmm I've tried with rssguard-3.7.1-b36e84b-nowebengine-win64.7z but the issue is still present:

![image](https://user-images.githubusercontent.com/49242687/91032166-db7d5000-e601-11ea-9d22-aed6759386ed.png)

And I see that rssguard-3.7.1-b36e84b-win64.7z also has a build date of 8/21/20 9:50AM:

![image](https://user-images.githubusercontent.com/49242687/91032671-960d5280-e602-11ea-9498-3a935ec47ed4.png)

Thank you!

**Comment by martinrotter** [comment]
Well, this is weird. I now tried exact same build and the issue just does not happen here. I am unable to reproduce it. :(

**Comment by martinrotter** [comment]
Did you try to start that development version with clean data folder? To make sure that messages are "fresh"? Simply unpack to different folder, make sure that database is empty on start, add the feed again and test.

**Comment by mpr0st** [comment]
Hmmm, this is strange, this is what I see with the empty database:

![image](https://user-images.githubusercontent.com/49242687/91059024-7dfcf980-e629-11ea-81d6-a1700461275a.png)

Which is the same I see in my database:

![image](https://user-images.githubusercontent.com/49242687/91059232-c1576800-e629-11ea-9996-563863e98f8c.png)

As you can see, there's a message that's been correctly received ("El festival de Berlín"), but the other ones haven't ("La maldición de Bly").

The build date (21-aug, 3 days ago), is correct? The modified date for rssguard.exe is also 21-aug-2020...

Thank you!

**Comment by martinrotter** [comment]
@mpr0st Is encoding of your feed set to UTF-8?

**Comment by martinrotter** [comment]
OK, so I just commited this commit: 56c44a23 which should force unescape HTML for TITLE/AUTHOR of the messages. Please, download newest build with 56c44a23 in its version/name when it gets compiled (20 minutes from now) and test with totally clean data and let me know if it helped.

I couldn't still reproduce the issue on my side, but tried to blindly fix it, let me know. :)

**Comment by mpr0st** [comment]
Sorry, I think I know why you can't reproduce the issue, my bad completely, I forgot to tell you about an important detail, I'm accessing the feed via Inoreader.

If I directly add the feed, it works perfectly:

![image](https://user-images.githubusercontent.com/49242687/91135986-7a5f8600-e6ae-11ea-9132-59edc86a83d1.png)

But, via Inoreader the issue persists:

![image](https://user-images.githubusercontent.com/49242687/91136145-85b2b180-e6ae-11ea-9105-ec310781f559.png)

Can't tell you how sorry I am, rookie mistake.

Thank you.

**Comment by martinrotter** [comment]
Holy sh. :D That is in fact important, anyway, I will finalize it and check Inoreader too. :) I thought that these online service APIs sanitizy/decode all strings by themselves but it seems they do not.

**Comment by martinrotter** [comment]
OK, I wrote completely new de-escaping mechanism which supports all [html symbols](https://www.w3schools.com/html/html_symbols.asp).

I also enabled the mechanism for TITLE/AUTHOR fields from Inoreader messages. Please test dev. build f1195f7 when it compiles. Thank you and let me know.

PS: Contents (body) of the message is not "de-escaped", primarily because sometimes de-escaping of comples HTML code can lead to broken HTML display/artifacts, particularly if feed is semi-broken.

If you wish to enable de-escaping in message's contents/body too, let me also know.

**Comment by mpr0st** [comment]
Now it works like a charm.

Regarding the body, I've seen the accented characters correctly at all times, so I guess there's nothing to adjust here.

Thank you very much.

**Comment by martinrotter** [comment]
@mpr0st Yes, I would bet that the Inoreader API sanitizes the content. OK, in that case this ticket is solved. I will probably release bug-fix 3.7.1 version soon. It will not introduce any drasticly new features, but bug fixes are there and quite a lot of them already.
