### ISSUE TITLE
[Wiki]Outdated "How to compile RSS Guard" section

### ISSUE THREAD

**Issue by snakepeeker** [martinrotter/rssguard#269]
#### Brief description of the issue.

How to compile RSS Guard is either too confusing for me or just outdated

### Faced issues

0. Guide doesn't include the "extract archive" or "use git" step

1. With git clone the directory is called rssguard, archive called rssguard-master.zip but the guide states that you should somehow have rssguard-git-master directory

2. There are no rssguard.pro on this path.
/rssguard-git-master/rssguard.pro
It's either in 
rssguard/src/rssguard/rssguard.pro
or
rssguard-master/src/rssguard/rssguard.pro

3. The are DIFFERENT instructions written in build.pro with ANOTHER directory of rssguard.pro and it's not there either

4. Should I use qmake or qmake-qt5 for this?

5.  Is it fine to have strings like this one rinning in console while executing make?
g++ -c -pipe -std=c++17 -O3 -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC -DAPP_VERSION="\"3.7.1\"" -DAPP_NAME="\"RSS Guard\"" -DAPP_LOW_NAME="\"rssguard\"" -DAPP_LOW_H_NAME="\".rssguard\"" -DAPP_LONG_NAME="\"RSS Guard 3.7.1\"" -DAPP_AUTHOR="\"Martin Rotter\"" -DAPP_EMAIL="\"rotter.martinos@gmail.com\"" -DAPP_URL="\"https://github.com/martinrotter/rssguard\"" -DAPP_URL_ISSUES="\"https://github.com/martinrotter/rssguard/issues\"" -DAPP_URL_ISSUES_NEW="\"https://github.com/martinrotter/rssguard/issues/new\"" -DAPP_URL_WIKI="\"https://github.com/martinrotter/rssguard/wiki\"" -DAPP_USERAGENT="\"RSS Guard/3.7.1 (github.com/martinrotter/rssguard)\"" -DAPP_DONATE_URL="\"https://martinrotter.github.io/donate\"" -DAPP_SYSTEM_NAME="\"Linux\"" -DAPP_SYSTEM_VERSION="\"x86_64\"" -DAPP_REVISION="\"2aa62448\"" -DQT_USE_QSTRINGBUILDER -DQT_USE_FAST_CONCATENATION -DQT_USE_FAST_OPERATOR_PLUS -DUNICODE -D_UNICODE -DUSE_WEBENGINE -DRSSGUARD_DLLSPEC=Q_DECL_EXPORT -DQT_NO_DEBUG -DQT_WEBENGINEWIDGETS_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_QMLMODELS_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB -I../../../rssguard/src/librssguard -I. -I../../../rssguard/src/librssguard -I../../../rssguard/src/librssguard/gui -I../../../rssguard/src/librssguard/gui/dialogs -I../../../rssguard/src/librssguard/dynamic-shortcuts -Iui -isystem /usr/include/qt -isystem /usr/include/qt/QtWebEngineWidgets -isystem /usr/include/qt/QtPrintSupport -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtWebEngineCore -isystem /usr/include/qt/QtQuick -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtSql -isystem /usr/include/qt/QtQmlModels -isystem /usr/include/qt/QtWebChannel -isystem /usr/include/qt/QtQml -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtXml -isystem /usr/include/qt/QtPositioning -isystem /usr/include/qt/QtCore -Imoc -I/usr/lib/qt/mkspecs/linux-g++ -o databasefactory.o ../../../rssguard/src/librssguard/miscellaneous/databasefactory.cpp
6. How long should it run?

> _i just want the filters feature..._

**Comment by martinrotter** [comment]
Hello.

0) Will fix.
1) Will fix.
2) Will fix.
3) Follow instructions in `build.pro`.
4) `qmake-qt5` of course.
5) Perfectly fine.
6) Compilation takes between 2 - 15 minutes, depending in your hardware.

What distro do you use? There are AppImages prepared for all versions. You just set `chmod +x *.AppImage` and you execute it and that's it.

**Comment by martinrotter** [comment]
OK, cleaned Wiki entry and moved additional info into build.pro, which is now the only source of compilation directions.

**Comment by snakepeeker** [comment]
Thank you for answer! I use archlinux distro and sadly it seemes that arch download is not quite up-to-date. I read a little bit into AppImage and fond it the most simple solution for this.

Still can't say the instructions are clear enough for newcomer to build rssguard. Like, what to build: build.pro or /src/rssguardrssguard.pro? How to execute the app you built?

`You just set chmod +x *.AppImage and you execute it and that's it.`
Maybe add it to readme/how to build guide, that you have option not to build? =)

**Comment by martinrotter** [comment]
If you use ArchLinux, then I am honestly surprised why you did not use official Arch repo's package. Just tweak `pkgver` field, regenerate sha256 checksum and run `makepkg`. You also don't need ` 0001-Fix-238-build.patch`.

I use Arch myself, this is literally the easiest way.
