### ISSUE TITLE
old feed as new feed

### ISSUE THREAD

**Issue by danrobi11** [martinrotter/rssguard#272]
Hello
I often have old seen feed as new feed
rss guard was doing that with older version as well. Im now testing new appimage 3.7.2 and same result. 
Theres nothing new in these feed, they shouldnt popup as new feed. 
The most obvious example here would be my personal reddit feed (comment, message) I keep getting older feed in these all the time

**Comment by martinrotter** [comment]
@danrobi11 I am not sure I completely understand what you try to say.

You say that some old (and possibly already read) messages gets by feed update marked as new/unread again? Can you post feed URL which contains this behavior + some screenshots perhaps?

**Comment by danrobi11** [comment]
To reproduce
Add your personnal Reddit comments, messages and the inbox. Im not posting my personnal feed in here

**Comment by martinrotter** [comment]
@danrobi11 How did you manage to add your personal inbox? Doesn't it require some kind of authentication?

**Comment by martinrotter** [comment]
BTW, see error, investigating...

**Comment by martinrotter** [comment]
BTW, does error happen for all reddit feeds? If not, pls help me to setup my "personal inbox" or whatever.

**Comment by martinrotter** [comment]
BTW, it seems that those messages are NOT duplicates, because they have different titles. Therefore RSS Guard cannot "merge" them. So far it seems as no bug in RSS Guard, this is normal RSS/ATOM behavior. You would net to write Reddit-specific RSS Guard plugin to support advanced nuances of Reddit infrastructure.

**Comment by guihkx** [comment]
Perhaps an option could be added to ignore entries that have the exact same URL? That would be a good way to improve entry deduplication, I think. For example, this entry was published earlier today in a blog I follow:

![image](https://user-images.githubusercontent.com/626206/99004632-339b6280-251e-11eb-9881-2dfb79ed0355.png)

Then, a few hours later, they've updated the title of the article to add new information (while keeping the exact same URL):

![image](https://user-images.githubusercontent.com/626206/99004977-b8867c00-251e-11eb-9a74-1b8f6ba7d926.png)

But RSS Guard created a new entry for this update.

**Comment by martinrotter** [comment]
Hello

**Comment by martinrotter** [comment]
@guihkx Edited.

**Comment by guihkx** [comment]
Wow, you made such an amazing program! :)

I'm going to bed soon but I'll definitely give it a go tomorrow. Thanks!
