### ISSUE TITLE
No Status icon in column  

### ISSUE THREAD

**Issue by danrobi11** [martinrotter/rssguard#273]
No status icon in the column. light/dark theme= same 

- dark theme: https://imgur.com/zz3lRV0.gif

- light theme: https://imgur.com/oynkvb9.gif

Appimage v3.7.2
OS: MX 19.2 (patito feo) x86_64
SysV init version: 2.93
Debian GNU/Linux 10 (buster)
Kernel: 4.19.0-9-amd64
WM: Fluxbox
Theme: Arc-Darker [GTK2/3] 
Icons: Moka [GTK2/3]

**Comment by martinrotter** [comment]
Yes, I see. It seems that icon theme was not for some reason loaded correctly and all icons are in fact missing. Can you navigate to Settings -> GUI and check what ICON THEME is active? Also, can you share full debug log here? See Wiki for info on how to generate one.

**Comment by danrobi11** [comment]
Hello icon theme was set to hicolor. I changed to papirus-dark and now status icon are there in the column. Thanks for the tips :+1:
