### ISSUE TITLE
youtube feed url 

### ISSUE THREAD

**Issue by danrobi11** [martinrotter/rssguard#274]
Hello
This is a normal yotube feed url: https://www.youtube.com/feeds/videos.xml?channel_id=UC5aeU5hk31cLzq_sAExLVWg
That does not work with rssguard. 
Need to modify the url in order to have youtube feed in rssguard to this: https://youtube.com/feeds/videos.xml?channel_id=UC5aeU5hk31cLzq_sAExLVWg 
Its very annoying to have to change all youtube feed url from a saved opml file. 
v3.7.2

**Comment by martinrotter** [comment]
I managed to reproduce the issue, will check out.

**Comment by martinrotter** [comment]
Checked now, and only thing that was somehow broken was "Fetch it now" (metadata) feature. Feed/messages downloading itself worked. Anyway I fixed the metadata downloading.

![image](https://user-images.githubusercontent.com/1255302/92110923-c798d180-edeb-11ea-9c45-aa67588c74f0.png)

**Comment by martinrotter** [comment]
Now it should all work.
