### ISSUE TITLE
Important messages section shows as 0 feed

### ISSUE THREAD

**Issue by danrobi11** [martinrotter/rssguard#275]
Hello
In the important messages section it shows as 0 feed is in there, when theres clearly feeds in there.
![important-messages-issue](https://user-images.githubusercontent.com/48020114/91894860-4e22a700-ec64-11ea-9489-cfc343cd6e40.png)

**Comment by martinrotter** [comment]
Node "Important messages" does not contain any subitems. If you mark some message as important, and then click "Important messages" then ALL your messages from across ALL your feeds will be displayed.
