### ISSUE TITLE
Text is not available for translation

### ISSUE THREAD

**Issue by Eleferen** [martinrotter/rssguard#276]
### Brief description of the issue.
Text in the menu "Update items with custom timers" is not available for translation on the site https://www.transifex.com/martinrotter/rssguard

![image](https://user-images.githubusercontent.com/15795413/92397220-1ff30a80-f12f-11ea-90e4-359134f0b4bf.png)

---

![image](https://user-images.githubusercontent.com/15795413/92397667-e1aa1b00-f12f-11ea-922d-18a8a1ecb1eb.png)

#### Other information (logs, see Wiki)
Version: 3.7.2 (built on Windows/x86_64)
Revision: 4effd1a
Build date: 01.09.2020 06:29
Qt: 5.14.2 (compiled against 5.14.2)

Localisation: Russian
Windows 10 64bit

**Comment by martinrotter** [comment]
I will update translation sources in a few days, i am in hospital...
