### ISSUE TITLE
[Feature request] 'Filter messages like this' functionality

### ISSUE THREAD

**Issue by mpr0st** [martinrotter/rssguard#278]
#### Brief description of the issue.

Would love to be able to right click in a message and then select an option like 'Filter messages like this...' to make the _Filters_ dialog open with the _Sample message_ pane preloaded with the selected message Title, URL, etc. This would make way easier to test a filter.

If it's not possible (for performance, size or other reasons) to load the Contents, maybe you could consider loading only part of it or leaving this field blank.

Thank you.

**Comment by martinrotter** [comment]
I plan to add message "tester" into Message filters dialog as well as this feature.

**Comment by mpr0st** [comment]
OK, thank you very much!

**Comment by martinrotter** [comment]
Done: preview https://imgur.com/a/wA7wUlB
