### ISSUE TITLE
UPDATE FROM 3.3.0 to 3.3.1 Problem 

### ISSUE THREAD

**Issue by pixadex** [martinrotter/rssguard#28]
#### Brief description of the issue.
I used a winrar download to install not full .exe installer.
*Write your description here...*
Updating to 3.3.1 from winrar pack wouldn't saved the data from last section I used on, when updating from that section from HELP>UPDATE  just makes it a new program installed not not just updating it and not losing ever I did on that pack of installation.
#### How to reproduce the bug?

1. 
2. 
3. 

#### What is the expected result?
not losing my data?
*Write expected result here...*

#### What actually happened?
losing data
*Write what in fact happened...*

#### Other information (logs, see Wiki)

*Write any other supplementary information here...*

**Comment by martinrotter** [comment]
Version 3.3.0 was distributed via fully portable `.zip` archive. You have to copy archive to the same folder where your previous RSS Guard installation was.

Version 3.3.1 was distributed via fully portable `.exe` NSIS installation package. This functionality was revived. You must install this installer into the same folder where you had existing RSS Guard installation too.

All user data in `data` subfolder are automatically preserved and NOT removed by the installer.
