### ISSUE TITLE
[Feature Request] Article Thumbnail

### ISSUE THREAD

**Issue by zero77** [martinrotter/rssguard#280]
It can be hard to sort through the on screen text when there is a large number of articles.
Can you please add the option to show the article thumbnail next to the title, thanks.

Something like this as an example, but more the middle column not either end:

![](https://cdn.pocket-lint.com/r/s/1200x630/assets/images/121966-apps-news-rss-reader-netnewswire-4-for-mac-enters-open-beta-image1-aWXcmhT18C.png)

**Comment by martinrotter** [comment]
Hello, you mean show article's thumbnail directly in list of articles?

**Comment by zero77** [comment]
Yes, ideally that's what i am after.

**Comment by martinrotter** [comment]
I see, well this approach would probably not work well with current multi-column list of messages. The GUI layer of list of messages would have to be completely rewritten to accommodate this completely different approach.

At this point, it is unlikely that I will implement this, unless a big portion of users requests this change.

**Comment by zero77** [comment]
Thanks, anyway.

**Comment by martinrotter** [comment]
I must admit that I like the layout in the screenshot you posted. I really like it, but I am afraid that many users are really used to traditional multi-column list, where they can hide some columns etc.

Maybe I will do some kind of survey...

**Comment by o-jasper** [comment]
Could have multiple options? And there is newspaper mode? Not sure how people use that, but maybe sometimes a 'thumbnail mode' with an array of thumbnails and maybe titles(cut off if lone) can make sense. That would be nicely visual, at least.

**Comment by martinrotter** [comment]
Closing, I moved all these similar tickets to single metaticket, follow there pls.

https://github.com/martinrotter/rssguard/issues/585
