### ISSUE TITLE
space between rows

### ISSUE THREAD

**Issue by pcause** [martinrotter/rssguard#282]
I can specify row height but when i have a lot of items scanning is heard.  being able to change space between rows and/or having alternating rows have a grey background or some or mechanism like that can help

**Comment by martinrotter** [comment]
I could add alternating background colors white/gray. Would it help? Would this feature also make sense for feed's list as well?

![image](https://user-images.githubusercontent.com/1255302/97017270-ff9bd580-154d-11eb-9b8e-1b85c8cbd057.png)

**Comment by martinrotter** [comment]
Added the setting and it is persistent of course: 
![image](https://user-images.githubusercontent.com/1255302/98081710-e3fecc00-1e77-11eb-9f5d-c66de885e56b.png)
