### ISSUE TITLE
Create nice and complete wiki/guide/documentation

### ISSUE THREAD

**Issue by martinrotter** [martinrotter/rssguard#288]
Currently, some info is in "Wiki" section, but I would like to create single Wiki page to include all documentation-like information, guides, hints, tips for RSS Guard:
* [x] - Merge all "Information" wiki pages to "[Documentation](https://github.com/martinrotter/rssguard/wiki/Documentation)":
    * [x] - Basic information,
    * [x] - Features,
    * [x] - Message filtering,
    * [x] - Generating debug log file,
* [ ] - Write [documentation](https://github.com/martinrotter/rssguard/wiki/Documentation) for all RSS Guard features:
    * [x] - Introductory chapter with some basic feature overview and info on contributing, donations, generating log files, compilation,
    * [x] - two variants of app, one webengine, one non-web,
    * [x] - online services supported and related info,
    * [x] - feed formats explanation/differences + podcasts,
    * [x] - import/export OPML,
    * [x] - gmail,
    * [x] - msg filtering,
    * [x] - labels,
    * [x] - downloading files,
    * [x] - data backends,
    * [x] - database cleanups,
    * [x] - minor GUI setups - hiding of toolbars, menus etc.

**Comment by nullrend** [comment]
So documentation is not going to be a single file any longer, then?

**Comment by martinrotter** [comment]
@nullrend No, as I wrote in that close PR, I changed my mind and followed your advice to allow bigger chapters to be separated into separate files, and as you can see in master branch, I advanced considerably.
