### ISSUE TITLE
Running separate instances (or profiles) at the same time

### ISSUE THREAD

**Issue by nullrend** [martinrotter/rssguard#289]
#### Brief description of the issue.

When there is a running instance of RSS Guard, attempting to run a second instance will refer you to the already-running instance. It does not matter whether the application was installed or running directly from the a directory (portable mode).

#### How to reproduce the bug?

Windows 10:

To make sure my current system installation was not interfering I uninstalled it entirely and double-checked there was nothing in `%APPDATA%/Local/RSS Guard`, then downloaded the latest portable build (3.7.2) and extracted to two separate directories. 

1. Run `rssguard.exe` from a directory.
2. Run `rssguard.exe` from a second, different, directory.

Linux (Xubuntu 19.10):

RSS Guard creates configuration data in `~/.config/RSS Guard/` when the AppImage is run.

1. Set `rssguard-*.AppImage` as executable.
2. Copy `rssguard-*.AppImage` to different directory.
3. Run first AppImage.
4. Run second (copied) AppImage.

#### What was the expected result?

Instances ran from their own directories should execute independently of each other, each with their own configuration and database.

#### What actually happened?

First instance will run and load its configuration and DB from its `data` directory. Second instance will not run but bring the already existing instance window to the forefront.

#### Other information (logs, see Wiki)

Resolving this could be handled a few different ways

- Make use of user profiles like Firefox does: [Multiple Firefox Profiles](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Multiple_profiles). This would be specially useful to people who do install RSS Guard on their systems as only one executable (and ancillary configuration) would need to be updated instead of multiple ones.
- Change application logic so it detects **where** the executable is located.
  - If you install the application to `%PROGRAMFILES%` it will load configuration from `%APPDATA/Local/RSS Guard`.
  - Running from elsewhere will make application load configuration from `./data`. This would be useful for Linux users.
- Enable a GUI or config.ini setting to explicitly state where the application should look for configuration data.

#### Workaround

Right now you can run the application as a different user on the same system:

Windows 10:
1. Right-click executable file.
2. Select Run as different user.

Linux:
- You can use `su` or `sudo` to execute the AppImage.

**Comment by martinrotter** [comment]
Wow, OK.

Some clarifications to your **Resolving this could be handled a few different ways** pasasge (other things you wrote are practically correct):
1. First check [this](https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#portable-user-data).
2. So if your system is clean and you just start RSS Guard (which is placed in **writable** location) then RSS Guard will automatically run in **portable** mode and write all user data in its application folder.

I agree that I could add some switches to command line interface, for example

```
-d <data-folder, --data <data-folder>
```
Which will start RSS Guard with explicitly specified folder to be used for storing all user's data (DB/CONFIG). Specifying this option will automatically enable multiple instances of RSS Guard to be started.

**Comment by martinrotter** [comment]
`Enable a GUI or config.ini setting to explicitly state where the application should look for configuration data.`

Will prefer CLI approach, it is cleaner.

**Comment by nullrend** [comment]
Still happening on latest development builds. I'm trying to run two separate executables (each with its own `data\config\config.ini` at the same time. Windows will notify the application is already running.

**Comment by martinrotter** [comment]
OK, I implemented this feature few minutes ago: 31f01029

Can you please test latest development build and test the feature? You must launch rssguard with command line parameters like this:

```
rssguard.exe --data "D:\rssguard-data"
```

**Comment by nullrend** [comment]
On Windows 10, downloaded and extracted rssguard-3.8.0-421de5de three times, one to each folder (Foo, Bar, Baz)

1. Ran Foo by double-clicking on executable and loaded default set of feeds.
2. Tried running Bar, application notified an instance of rssguard.exe was already running:

```
time="     0.844" type="debug" -> core: Starting RSS Guard 3.8.0.
time="     0.844" type="debug" -> core: Instantiated class  'Application'.
time="     0.845" type="warning" -> core: Another instance of the application is already running. Notifying it.
time="     0.845" type="debug" -> core: Destroying Application instance.
time="     0.845" type="debug" -> core: Destroying Mutex instance.
time="     1.025" type="debug" -> gui: Destroying IconFactory instance.
```

Closed all instances of rssguard and double-checked Task Manager to ensure of this fact.

----

1. Opened command prompt in Foo directory, executed `rssguard.exe --data ".\data"`. Instance Foo started.
2. Opened command prompt in Bar directory, executed `rssguard.exe --data ".\data"`. Instance Bar started.
3. Opened command prompt in Baz directory, executed `rssguard.exe --data ".\data"`. Instance Baz started.

All three instances are running concurrently without issues.

At this point started closing them and random and executing them from Run dialog, Windows Subsystem for Linux, PowerShell, and git bash shell. Ran without issues.

---

On Desktop, created shortcuts to each instance. Running one notifies there is an instance already running. Edited shortcuts to pass the `--data` argument:

```
"C:\Users\null\Downloads\rssguard-3.8.0-421de5e-win64 Foo\rssguard.exe" --data ".\data"
```

Adjusting the target directory for each instance, of course. Running them in this manner works without issues as well.

**Comment by martinrotter** [comment]
So basically everything is working fine?

**Comment by nullrend** [comment]
By the looks of it, yes. I'll test this out on Linux later tonight.

**Comment by martinrotter** [comment]
Perfectos.
