### ISSUE TITLE
Breaking change in News 15.1.0

### ISSUE THREAD

**Issue by Grotax** [martinrotter/rssguard#293]
#### Brief description of the issue.

With news 15.1.0 we have a change in the feed attribute "folderId", if the feed is in the root folder the id will be "null" instead of 0.

See https://github.com/nextcloud/news/issues/939

#### How to reproduce the bug?

1. Install 15.1.0-rc2
2. sync
3. ...

#### What was the expected result?

Accept both 0 and null as a value at least for a while to allow for a smooth transition.

**Comment by anoymouserver** [comment]
Probably not an issue since `QJsonValue::toInt` falls back to 0 if the value is not a number.

https://github.com/martinrotter/rssguard/blob/f7607dc640937d3b4d5763beacc5a94d185bdd33/src/librssguard/services/owncloud/network/owncloudnetworkfactory.cpp#L621
