### ISSUE TITLE
Date/time of feeds do not follow locale

### ISSUE THREAD

**Issue by guihkx** [martinrotter/rssguard#297]
#### Brief description of the issue.

I'm not sure if I messed something up, but currently, RSS Guard is not displaying dates and times based on my locale:

```
$ cat /etc/locale.conf
LANG=en_US.UTF-8
LC_NUMERIC=pt_BR.UTF-8
LC_TIME=pt_BR.UTF-8
LC_MONETARY=pt_BR.UTF-8
LC_PAPER=pt_BR.UTF-8
LC_MEASUREMENT=pt_BR.UTF-8
```

#### How to reproduce the bug?

Run RSS Guard with `LC_TIME` set with anything other than `C` or `en_US.UTF-8`, e.g.:

```
$ export LC_TIME=pt_BR.UTF-8
$ rssguard
```

#### What was the expected result?

Dates to be displayed as `dd/mm/YY`. And time to be displayed as a 24-hour clock, e.g.: `22:00`.

#### What actually happened?

Dates are displayed the "american way": `mm/dd/YY`. Plus time is displayed as a 12-hour clock, e.g.: `10:00 PM/AM`.

![image](https://user-images.githubusercontent.com/626206/98978435-b9a4b280-24f8-11eb-9e23-e611211edf50.png)

#### Other information (logs, see Wiki)

I'm running latest master on Arch Linux, without QtWebEngine. And I have *not* enabled the **Use custom date/time format** option under **Feeds & messages**, so I believe it should follow my locale, correct?

Thanks.

**Comment by martinrotter** [comment]
That formatting of date/times in message list should by default follow "locale" of the application. I tried for test to change active localization to "Portuguese" in RSS Guard application settings and then the output looks like this:
![image](https://user-images.githubusercontent.com/1255302/98986074-b2939980-2524-11eb-9651-0e8899be3120.png)

You can also change formatting by yourself directly:
![image](https://user-images.githubusercontent.com/1255302/98986118-c3440f80-2524-11eb-9fd0-51e110ade06a.png)

**Comment by guihkx** [comment]
Oh, I thought RSS Guard would follow the system's locale, unless the user manually changed the language inside the program.

But the second option works just fine for me too.

Thanks!
