### ISSUE TITLE
qt5.5 patch

### ISSUE THREAD

**Issue by timcowchip** [martinrotter/rssguard#3]
--- a/src/qtsingleapplication/qtlocalpeer.cpp	2015-07-07 12:47:14.000000000 -0700
+++ b/src/qtsingleapplication/qtlocalpeer.cpp	2015-05-11 06:31:59.000000000 -0700
@@ -42,6 +42,7 @@
 #include "qtlocalpeer.h"
 #include QCoreApplication
 #include QTime
+#include QDataStream
 
 #if defined(Q_OS_WIN)
 #include QLibrary

**Comment by martinrotter** [comment]
Hi.

Okay. Adjusted code, will push tonight.
