### ISSUE TITLE
action order for status bar not being honored

### ISSUE THREAD

**Issue by mpr0st** [martinrotter/rssguard#300]
#### Brief description of the issue.

The order of the actions for the status bar is being ignored.

#### How to reproduce the bug?

1. Update the feeds (Inoreader in my case).

#### What was the expected result?

The specified order for the actions in the status bar is applied.

#### What actually happened?

The order is not applied, _Feed update label_ and _Feed update progress bar_ are located at the end, despite being the first in the list:

![image](https://user-images.githubusercontent.com/49242687/99145851-59d21700-2672-11eb-926b-8b53cc6be5ea.png)

#### Other information (logs, see Wiki)

Clean RSS Guard 3.8.0 final portable installation (rssguard-3.8.0-13c8ecf-nowebengine-win64.7z).

Thank you!

**Comment by martinrotter** [comment]
Does the order fix itself when you restart RSS Guard after making the changes?

**Comment by mpr0st** [comment]
YES!

**Comment by mpr0st** [comment]
BTW, I didn't touch the order, it was the default one...

**Comment by martinrotter** [comment]
Yes, I see the error now, reproduced, will try to fix.

**Comment by martinrotter** [comment]
Well, this proved to be a real pickle with some real technical difficulties. I am RN doing some tweaks and RSS Guard will ask you to restart if you do changes to toolbar settings because it is just really not worth of trying to "properly" re-implement this.

**Comment by mpr0st** [comment]
OK, thank you.
