### ISSUE TITLE
manually sort feed list

### ISSUE THREAD

**Issue by 88mm** [martinrotter/rssguard#302]
I can not manually sort the feed list.  It is either alphabetically listed or  the inverse. Dragging a feed up or down does not work.

Work around:  Edit each feed title and prepend a number  to the title of the feed.  (ex: 01-Title1, 02-Feed2) Then click on "update all items".

I am using rssguard-3.5.9.

**Comment by martinrotter** [comment]
Yes, at this point RSS Guard automatically sorts items in feeds list according to some column, either name or unread/total count. Adding manual sort ability would not be that hard but I personally do not need it. Maybe someone can contribute PR.

BTW: You really should use latest RSS Guard version.

**Comment by martinrotter** [comment]
NOTE: This was requested by high percentage of users in 3.8.3 survey.

**Comment by Owyn** [comment]
Usually when you click a column to sort by it- it goes through these steps
1) sort up by it
2) sort down by it
3) turn off sorting by it

I thought it was simply a bug that dragged items dont go to where you drag em and I doubt others accept it with "oh so it's the sorting, ok",

at least there should be a highlighting to where you can drag items (e.g. - other (sub)folders) and where you won't achieve anything by dragging there so it won't look broken

**Comment by martinrotter** [comment]
I move to this.

So, manual sorting should be supported for **categories**, **feeds** and **account** nodes?

**Comment by guihkx** [comment]
I honestly hadn't thought about organizing by categories and account, but now that you mention it, it'd be something nice to have...

**Comment by martinrotter** [comment]
Working on this.

![image](https://user-images.githubusercontent.com/1255302/156177344-c5ed186b-9d6e-4ec4-bc6e-2ccf0de4bcf6.png)

**Comment by guihkx** [comment]
Awesome! Drag 'n drop will work as well, I assume?

**Comment by martinrotter** [comment]
Working on this.

![image](https://user-images.githubusercontent.com/1255302/156177829-79c158a8-a2b9-4969-b9df-1c4a516916fd.png)


> Awesome! Drag 'n drop will work as well, I assume?

Not there yet, I will decided how exactly this feature will interface with drag/drop, but yes, I expect it to work together.

![Uploading image.png…]()

**Comment by martinrotter** [comment]
One more thing: Manual sorting will work for: feeds, categories and accounts nodes. Not for labels/tags, which will be still sorted alphabetically.

**Comment by martinrotter** [comment]
Guys, I bumped into some serious compatibility issues on SQL/DB layer, which would require HUGE amount of SQL code to be completely rewritten in a backwards-INCOMPATIBLE way.

I could implement this into `4.x` branch of RSS Guard but the implementation would be ugly and possibly slow. Therefore, this feature must wait for RSS Guard `5.0.0` release where I can introduce backwards-incompatible changes.

** I am very sorry for this. ** I just cannot introduce half-baked features into the program. Sorry.

**Comment by martinrotter** [comment]
UPDATE: I had a good sleep today, so I continue with the implementation even for 4.2.0 release.

As of now, the implementation supports manual sorting for FEEDS and actions MOVE UP, MOVE DOWN.

**Comment by martinrotter** [comment]
UPDATE: Experimental implementation is now done.
![rssguard_ETROR5jcxJ](https://user-images.githubusercontent.com/1255302/158538034-70ce98d2-8030-4a84-b86d-cd3ba092f069.png)
![rssguard_7fjL4R9tSu](https://user-images.githubusercontent.com/1255302/158538045-236279f2-6f5f-4486-b8fa-7f6e328d6e6c.png)
![rssguard_ZD8N4oTdhg](https://user-images.githubusercontent.com/1255302/158538052-ce037fa8-8e47-4125-a6c0-bf6723c79bee.png)
![rssguard_wHaky4d9Xi](https://user-images.githubusercontent.com/1255302/158538060-4a55dfeb-e294-4440-9437-d1d18def2a01.png)
