### ISSUE TITLE
Import & Export   .opml 

### ISSUE THREAD

**Issue by blackcrack** [martinrotter/rssguard#307]
#### Brief description of the issue.

Try to import an opml file from an other rss-reader and not possible
so nothing found.. 
like i see works this engine with sqlite and make this also as a mysqlite db, but
i have not found a possible for export and import the clean newstree with urls

#### How to reproduce the bug?

start programm, search a possibility to import opml files

#### What was the expected result?

have a possibility to in/export opml-files

#### What actually happened?

\*beep* wrong search ..

#### Other information (logs, see Wiki)

no info about opml - format and ex/imports

best regards
Blacky

**Comment by martinrotter** [comment]
Hello @blackcrack.
RSS Guard supports OPML export/import for its "standard" plugin's feeds and categories. The functionality is available in account's menu, see below pictures.

![image](https://user-images.githubusercontent.com/1255302/100710138-8c3c7d80-33af-11eb-834e-dde5a3cc025a.png)
![image](https://user-images.githubusercontent.com/1255302/100710122-85156f80-33af-11eb-80d3-ada37b4d3e84.png)

**Comment by blackcrack** [comment]
ahh okey, thank you :)))
