### ISSUE TITLE
RSS Guard overrides DE's icon theme and sets its own icon

### ISSUE THREAD

**Issue by guihkx** [martinrotter/rssguard#308]
#### Brief description of the issue.

First of all, don't get me wrong: I love the new RSS Guard icon and logo (especially the one in system tray :). I simply choose to use a custom icon theme because it feels like they "integrate better" with the whole desktop.

Anyway, apparently, RSS Guard is forcing its own icon instead of letting GNOME (or whatever desktop environment) pick its icon).

#### How to reproduce the bug?

1. Be on GNOME (I guess)
2. Have a custom icon theme installed (I'm using [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme))
3. Run RSS Guard (I'm building from git, commit 59e546a8cd7289b876223894321a8d74d2360490)
4. Open GNOME's "Activities" overview, and notice RSS Guard's icon:

![image](https://user-images.githubusercontent.com/626206/100775840-9035c300-33e2-11eb-8be5-2fd9511b9ddf.png)

#### What was the expected result?

RSS Guard's icon should be the one installed by Papirus, i.e.: `/usr/share/icons/Papirus-Dark/128x128/apps/rssguard.svg`

#### What actually happened?

I _think_ RSS Guard is setting its own icon instead. Additionally, sometimes the icon has some artifacts (?) at the bottom of it (you can even see it in the screenshot above).

#### Other information (logs, see Wiki)

**OS:** Arch Linux
**RSS Guard Version:** 3.8.3 (built on Linux/x86_64)
**Revision:** 59e546a8-nowebengine
**Build date:** 12/1/20 5:08 PM
**Qt:** 5.15.2 (compiled against 5.15.2)

**Comment by martinrotter** [comment]
Yes, RSS Guard at this point uses hardcoded icon in tray area, let me investigate.

Is "Activity area" in Gnome equivavelnt of "tray icon area"? If RSS Guard has some unread messages does the icon stay the same or do you see the number displayed inside the icon?

![image](https://user-images.githubusercontent.com/1255302/100794961-9184e100-341e-11eb-8f20-3dc6239aee1b.png)

I am not sure how "Activity area" in Gnome works, I use MATE on my ArchLinux station.

If activity area is "tray" area, then there is one big problem. When you have some unread messages, RSS Guard displays number of unread messages overlayed over the tray icon and uses special "plain" background icon to make the number easier to read - https://github.com/martinrotter/rssguard/blob/master/resources/graphics/rssguard_plain.png

I guess I will have to test directly.

So the icon is not static but is rather changing dynamically according to number of unread messages.

**Comment by guihkx** [comment]
>If RSS Guard has some unread messages does the icon stay the same or do you see the number displayed inside the icon?

Tray icon remains working like always, as far as I could tell. The only difference is that, previously, the tray icon was a little square with the counter in the middle, now it's a shield-shaped one:

![image](https://user-images.githubusercontent.com/626206/100799540-00a10c00-3404-11eb-8fb5-4ce140a5bc82.png)

However, I must note that the GNOME desktop itself does not have the concept of a "system tray" anymore. [It's been removed a long time ago](https://blogs.gnome.org/aday/2017/08/31/status-icons-and-gnome/).

What GNOME users are doing now, is installing a [GNOME Shell Extension](https://extensions.gnome.org/extension/615/appindicator-support/) that adds a systray area (for example, Ubuntu comes with this extension pre-installed). So, to answer your first question, I really think the Activity Overview icon is disconnected from the tray one.

**Comment by guihkx** [comment]
(Not 100% related to this issue, but just posting in case you're interested to investigate as well):

Question: After RSS Guard finishes checking for feed updates, does it set a new icon in the system tray? Because the GNOME Shell extension I mentioned is unable to update the tray icon, and instead displays this one:

![image](https://user-images.githubusercontent.com/626206/100800490-6fcb3000-3405-11eb-9ca5-9a424d02cab0.png)

Additionally, the system journal shows me this:

```
$ journalctl -f
[...]
dec 01 18:40:47 arch appindicatorsupport@rgcjonas.gmail.com[766]: unable to update icon for RSS Guard
```

The extension is not perfect, by the way. With a few other programs, the tray icon doesn't work at all, so feel free to disregard this as a RSS Guard bug.

**Comment by martinrotter** [comment]
- [ ] Check and fix dynamic tray icon with unread message count on Gnome/w tray extension.
- [ ] Check and fix app icon loading from activated DE's icon theme for activity list.

@guihkx Btw, is your session X11 or wayland?

**Comment by martinrotter** [comment]
OK, I checked it with Manjaro/Gnome. Icon in tray area works fine and gets eventually "regenerated" after some seconds, it just seems that gnome tray area extension is not of great quality, sadly.

I added logic which tries to load application icon from active icon theme and use it if available.

![image](https://user-images.githubusercontent.com/1255302/100843042-0f2a0a80-347a-11eb-9e4d-7d9acf7115f0.png)

Please test with latest revision and let me know: https://github.com/martinrotter/rssguard/commit/a3e648573923e9880787de28df102ba9cc864de0

**Comment by guihkx** [comment]
Just tested it. Now it's properly picking up the icon from my current theme.

Thanks for fixing it this quickly! And I the systray issue probably has to be solved on the extension side: https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/176
