### ISSUE TITLE
Vimeo feed stopped working

### ISSUE THREAD

**Issue by takaduhkha** [martinrotter/rssguard#309]
#### Brief description of the issue.

RSS from Vimeo channels doesn't work anymore

#### How to reproduce the bug?

1. Add new feed https://vimeo.com/(channel name here)/videos
2. Fetch it now gives „All metadata fetched succesfuly) but clicking ok gives „cannot edit feed do to error”
3. Update selected items doesn't load feed

#### What was the expected result?

It used to work as any other feed and inform about new videos.

#### What actually happened?

Described in „How to reproduce the bug”

#### Other information

* OS: Ubuntu 18
* Desktop Environment: Unity
* RSS Guard version: 3.8.3

Stopped to work few months ago.

**Comment by martinrotter** [comment]
Testing with: https://vimeo.com/nobumichiasai/videos/rss

Their RSS feeds are **heavily BROKEN**. Feed itself has NO title, message entries also have NO title and NO description texts.

Anyway, I pushed a dirty fix, but you should notify Vimeo that their RSS feeds are total shit and I take absolutely not responsibility on how they work in RSS Guard, anyway, it should be now fixed: 80eb8679

**Comment by takaduhkha** [comment]
Hi

I'm sorry to bother, I'm nontechy so I could misuderstand. I should just add the URL as title and description? I did but it still loads no feed.
Also yes I completely don't blame RSSGuard ofc, I'm just looking for solution :)
Thx for taking look at it!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by martinrotter** [comment]
No, you need to have newest development/testing RSS Guard version which have the bug fixed, you can download it now here: https://ci.appveyor.com/api/buildjobs/487nfftel10hmvbo/artifacts/rssguard-build%2Fsrc%2Frssguard%2Frssguard-3.8.3-80eb867-win64.exe

Just install and test your feed and let me know if it works now. No other changes needed.

**Comment by takaduhkha** [comment]
Is there appimage also? I can probably use .exe under Wine but would be better.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by martinrotter** [comment]
https://bintray.com/martinrotter/rssguard/download_file?file_path=rssguard-3.8.3-80eb8679-linux64.AppImage

**Comment by takaduhkha** [comment]
Thx a lot. It does work now. I also wrote to Vimeo.
I also wanted to tell you I love RSS Guard. It's the feeder of my choice and it works fantastic.
Cheers!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by martinrotter** [comment]
Cheers.
