### ISSUE TITLE
Filtering messages (when downloading + manual in later versions)

### ISSUE THREAD

**Issue by logos88** [martinrotter/rssguard#31]
Is there any way in rssguard to add filters to each channel or folder like in quiterss or something similar?
If not, I think its something very useful, and would be nice to have in the future.

martinrotter: Create generic set of rules which can be attached to feeds and run automatically when downloading messages and decide what to do with message. Also, perhaps be able to run on specific feed manually.

Possibly actions:
* mark as read/unread/starred,
* do not download.

Question is in which way to define rules which will decide if message is "filtered". QuiteRSS uses combo-box based dialog:
![image](https://user-images.githubusercontent.com/1255302/85019114-94409200-b16e-11ea-8755-332ac2db70fd.png)
which I do not like. Perhaps some kind of scripting could be better. Also note that this feature should be able to tell if message is "duplicate" as stated in #225. Perhaps QJSValue and QJSEngine classes could work well. They allow running JS script which can access data of C++ class (Message class) and run custom C++ functions (isMessageDuplicate()..)...

**Comment by martinrotter** [comment]
Not yet. I will add new major features later, right now we have big problems with bugs in new functionality.

**Comment by martinrotter** [comment]
What exact filters do you mean. You mean filters for operations with messages of feeds? For example when new messages are downloaded, assigned filters are executed and each message is processed with the filters?

**Comment by martinrotter** [comment]
If so then that is actually one of main features I am thinking about for next feature release (3.4.0).

**Comment by logos88** [comment]
Yes, something like that I mean. In quiterss you have the option to choose if one new in the feed contains a particular word in its title, description, content ... to automatiqually be erased, marked as read, ...

Another approach could be implementing something like a blacklist and whitelist of words for each feed channel. This way, when a feed had a word in the blacklist, it wouldn't download the new updates which would have the word listed in the title.

For example, if I have a recipes feed but I don't like fish, I could go to the feed properties and in a new "filter" tag or something like that put the next commands: -fish, -tuna. And then, in my recipes feeds will never appear recipes which contains the words fish and tuna in the title.

Another example. If I have a sports feed but I don't like football and basket, but I want to now the news about my national team I culd put the next commands: -football, -basket, +"Spanish team", +national. This way, I won't have new news with football and basket, but despite it would say football or basket at the title, if it speaks about Spanish team or national they will appear.

I really think this would be a great tool to personalize our feeds and to save time not to reading news that we aren't intersted in. It could be a step ahead in our rss feeds way of reading.I write for a feature request. 

Its great to know you are thinking about something like this for next versions :D

**Comment by martinrotter** [comment]
Yes, that is the exactly thing I plan to add!

Each feed will be able to have assigned X filters. Each newly downloaded message will be checked with all activated filters for given feed and if some feed contains the message, then associated action will be executed.

Possible actions would be something like:
* mark message as read,
* mark message as important,
* ignore message (do not save it into DB).

Those filters will work even across RSS Guard accounts. So user will be able to define ONE filter and attach it to several feeds across accounts (TT-RSS, whatever).

User would be able to use message title, author or message contents to be checked. Regular expressions and wildcard matching will be allowed.

**Comment by logos88** [comment]
Nice. I'll be attentive to new releases then :D

**Comment by martinrotter** [comment]
I expect at least two release before the actual next feature release.

3.3.2 -> 3.3.3 -> 3.4.0

**Comment by meelten** [comment]
Hi. Did you implemented filtering or not? I have 3.5.7 version and can't find anything.

**Comment by martinrotter** [comment]
@meelten Not yet.

**Comment by martinrotter** [comment]
So I did some more testing, and this feature will have these properties:
* while filtering mechanism will be scriptable with JavaScript,
* all properties of every single message will be accessible and even CHANGEABLE via scripting,
* user can decide in script if he wants to accept or reject message and change its properties before it is stored in DB.

Example of such a script:
```js
(function() {
// Change title of the message with condition and make sure it is starred.
if (msg.title.includes("windows")) {
  msg.title = "linux";
  msg.isImportant = true;
}

if (msg.contents.includes("shit")) {
  return 2; // Reject messages with ugly contents.
}
else {
  return 1;
}
})
```

As you can see, your filtering logic can be very complex. You can tweak your message properties in any way and subsequently save it to DB or reject it.

There will be list of filters which will be persistently stored in DB and each filter will be assignable to any feed, so that multiple filters could run when message are downloading.

Also, it will be possible to maybe run filters manually on already existing messages.

**Comment by martinrotter** [comment]
Work continues, now I added a change that will allow user to specify arbitrary "helper" JS functions or other code. The contents of filter scripts will be completely arbitrary except main "filtering" function. Whole script will be evaluated by JS engine and `filterMessage()` will be then repeatedly called by RSS Guard with individual messages.

Example script might look like this:

```
function helper() {
  if (msg.title.includes("A")) {
    msg.isImportant = true;
  }

  if (msg.isDuplicateWithAttribute(1)) {
    // Same message with same title already exists in DB for this feed.
    // Ignore it now.
    return 2;
  }

  return 1;
}

function filterMessage() {
  return helper();
}
```

**Comment by martinrotter** [comment]
Core functionality is done, RN I start working on the GUI for managing/editing filters.

**Comment by martinrotter** [comment]
WIP GUI manager for filters so far:

![image](https://user-images.githubusercontent.com/1255302/86356488-9de8f000-bc6c-11ea-94af-4b368d2a7e80.png)

**Comment by martinrotter** [comment]
I am finishing the GUI rn.

![image](https://user-images.githubusercontent.com/1255302/87005152-dcc3fc00-c1be-11ea-82af-eb628a9d661a.png)

**Comment by martinrotter** [comment]
OK, guys. @logos88 @meelten @vinzv @orschiro, I pushed the feature to [master] branch. It is very experimental, but should work for testing.

Can you please wait when 9695bb23 compiles and then download/test development build?
