### ISSUE TITLE
Not reading icon/favicon data from RSS-Bridge Atom feeds (but JSON works)

### ISSUE THREAD

**Issue by quickwick** [martinrotter/rssguard#310]
#### Brief description of the issue.

RSS Guard does not load an icon when fetching metadata for ATOM format feed generated by [RSS-Bridge](https://github.com/RSS-Bridge/rss-bridge). However, it does successfully load an icon when fetching metadata for JSON format feed, also generated by RSS-Bridge.

#### How to reproduce the bug?

1. Add an RSS-Bridge feed, in ATOM format, to RSS Guard
2. Click the 'Fetch it now' button to fetch metadata
3. Title is correctly fetched, but Icon stays as the default blue globe
4. Add an RSS-Bridge feed, in JSON format, to RSS Guard
5. Click the 'Fetch it now' button to fetch metadata
3. Title and Icon are both correctly fetched

#### What was the expected result?

Icon fetched from ATOM feed metadata

#### What actually happened?

Icon not fetched from ATOM feed metadata

#### Other information

* OS: Windows 10 (2004)
* RSS Guard version: 3.8.3

Here are samples of the RSS-Bridge feed, just the first few lines, in case it is an error with how they are generating their feeds.

ATOM:
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/">

	<title type="text">Twitter @startrek</title>
	<id>http://192.168.1.34/rss-bridge/?action=display&amp;bridge=Twitter&amp;context=By+username&amp;u=startrek&amp;format=Atom</id>
	<icon>https://twitter.com//favicon.ico</icon>
	<logo>https://twitter.com//favicon.ico</logo>
	<updated>2020-12-02T19:26:30+00:00</updated>
	<author>
		<name>RSS-Bridge</name>
	</author>
	<link rel="alternate" type="text/html" href="https://twitter.com/startrek" />
	<link rel="self" type="application/atom+xml" href="http://192.168.1.34/rss-bridge/?action=display&amp;bridge=Twitter&amp;context=By+username&amp;u=startrek&amp;format=Atom" />

Here is the same feed, but in JSON format:

`{
    "version": "https:\/\/jsonfeed.org\/version\/1",
    "title": "Twitter @startrek",
    "home_page_url": "https:\/\/twitter.com\/startrek",
    "feed_url": "http:\/\/192.168.1.34\/rss-bridge\/?action=display&bridge=Twitter&context=By+username&u=startrek&format=Json",
    "icon": "https:\/\/twitter.com\/\/favicon.ico",
    "favicon": "https:\/\/twitter.com\/\/favicon.ico",
`

**Comment by martinrotter** [comment]
Sorry, provide full ATOM feed, not just sample.

@quickwick

**Comment by martinrotter** [comment]
Anyway, I commited f11824ea, pls test development build with "f11824ea" in its name when it gets compiled (30 minutes). Should work now.

**Comment by quickwick** [comment]
Sounds like you didn't need it after all, but here's the entire example ATOM feed anyway.

[ATOM_feed_example.txt](https://github.com/martinrotter/rssguard/files/5637314/ATOM_feed_example.txt)

**Comment by martinrotter** [comment]
Yes, pls test if it works and let me know. :)

**Comment by quickwick** [comment]
Took me a while to figure out where to get development builds. I can confirm that build f11824ea successfully loads favicon from RSS-Bridge ATOM feed. Thank you!
