### ISSUE TITLE
Date sorting sorts by lexicographic order instead of numeric order

### ISSUE THREAD

**Issue by Groctel** [martinrotter/rssguard#312]
#### Brief description of the issue.

When sorting by date, feed items are sorted lexicographically.
For example, when the date format is set to `dd/mm/yyyy`, dates are sorted in ascending order like this:

```
19/07/2019
20/05/2018
25/10/2020
26/05/2020
```

So, the only way to correctly sort the dates is with a format similar to `yyyy-mm-dd`.

#### How to reproduce the bug?

1. Set the date format to something similar to `dd/mm/yyyy`
2. Sort by date
3. Profit

#### What was the expected result?

The feeds should be sorted by date.

#### What actually happened?

They're actually sorted by the date's characters in lexicographic order.

#### Other information

* OS: `Linux grocpc 5.9.12-arch1-1 #1 SMP PREEMPT Wed, 02 Dec 2020 16:14:56 +0000 x86_64 GNU/Linux`
* Desktop Environment: KDE Plasma
* RSS Guard version: rssguard 3.7.2-2

**Comment by martinrotter** [comment]
@Groctel Please, double-check that you REALLY have your list sorted (you see little arrow in your date/time column header). I double checked the code and it is completely separated from the formatting and sorting works nicely.

![image](https://user-images.githubusercontent.com/1255302/101317404-bfbf5200-385e-11eb-9727-22a7d5c56502.png)

**Comment by Groctel** [comment]
I feel like a fucking idiot, but I swear that I had this problem yesterday and I triple checked it was happening with more than one feed list. It's now sorting in numeric order so I don't know what could have happened there...
I'm sorry for making you waste your time on this.

**Comment by martinrotter** [comment]
Its allright, no problem. :)
