### ISSUE TITLE
Synchronize across machines

### ISSUE THREAD

**Issue by CsatiZoltan** [martinrotter/rssguard#314]
Is it possible to synchronize feeds on multiple machines? I searched for it in the issues and in the GUI menus but didn't find it. What I am looking for is the following: when I add new RSS feeds or when I delete entries on one machine (Ubuntu 18.04), the changes are automatically reflected on another machine (Windows 7).

**Comment by martinrotter** [comment]
It depends.

Do you need to synchronize in "real-time". I mean are those two instances of RSS Guard on those two machines running in the same time?

**Comment by CsatiZoltan** [comment]
Ideally, yes. But if I need to exit one of them so that the other instance fetches the changes, it is OK as well.

**Comment by martinrotter** [comment]
Well, you have some options:

### Almost realtime
For almost realtime approach, I would recommend to use "Inoreader" plugin (or other synchronized plugin like TT-RSS or Nextcloud which use self-hosted service, Inoreader is easier to setup). Inoreader is free to use with almost no limitations. Simply add the plugin, fill your username, and hit "Login" button. Then do the same thing on the other PC. All changes made to **messages** (marked read, unread, important, assigned label) are synchronized back to service regularly and if user on the other PC updates some of the feeds, he will receive the changes too.

If you do some change to **feeds** via web interface (add feed, rename, delete, etc.) then you must hit "Sync in" button in RSS Guard to receive changed feeds. Some screenshots:

![rssguard_Y7klnlCsht](https://user-images.githubusercontent.com/1255302/101588215-2b7ff700-39e6-11eb-8aab-b7d79e0aaf6d.png)
![rssguard_Fc8s9h79oa](https://user-images.githubusercontent.com/1255302/101588220-2e7ae780-39e6-11eb-8d3e-1d3d8500bffc.png)
![rssguard_eWPFubxgw2](https://user-images.githubusercontent.com/1255302/101588223-3044ab00-39e6-11eb-99ce-370778afda88.png)

### No realtime
Well, all you need to know is that RSS Guard stores all its data within single folder:
![rssguard_CctbIt5npj](https://user-images.githubusercontent.com/1255302/101588291-55d1b480-39e6-11eb-9905-4625eaabfea8.png)

So, all you need to do is that you have to somehow synchronize the folder to the other PC perhaps via Dropbox or Syncthing. I use this personally with Syncthing but when I am on PC A, then I am not on PC B. When I exit RSS Guard on PC A, my application data get synced to my Syncthing server and when I turn on the other PC B, my data will get re-synchronized with the server and then I start RSS Guard there and have all the latest stuff.

Perhaps I made it all clear.

**Comment by martinrotter** [comment]
Btw, next time for these kind of questions, it might be better to use "discussion" instead of creating ticket: https://github.com/martinrotter/rssguard/discussions

**Comment by CsatiZoltan** [comment]
Yes, the instructions are super clear. Everything works fine, thank you. I chose the almost-real-time solution (the directories being synchronized by MEGA) as I don't read feeds at the same time on two different machines. This solution has the advantage that information in `database.db` is transferred through my trusted MEGA account, while I don't know whether I can trust *Inoreader*.



> Btw, next time for these kind of questions, it might be better to use "discussion" instead of creating ticket: https://github.com/martinrotter/rssguard/discussions

OK, I didn't know about it.
