### ISSUE TITLE
open in external browser page viewed in internal browser

### ISSUE THREAD

**Issue by pcause** [martinrotter/rssguard#320]
I use the internal browser for quick viewing.  some pages i want to read/save/bookmark in my external browser.  How about an icon in the internal browser to open in the external browser the currently viewed page.

**Comment by martinrotter** [comment]
DOne: 
![image](https://user-images.githubusercontent.com/1255302/103688104-9b57b200-4f91-11eb-8cea-2730b56dac39.png)

**Comment by pcause** [comment]
3.8.4 release notes show an amazing effort and a HUGE amount of work.  Thanks so much!

**Comment by martinrotter** [comment]
@pcause Thank you my brother.
