### ISSUE TITLE
3.8.4 - issues with adblock

### ISSUE THREAD

**Issue by pcause** [martinrotter/rssguard#322]
I was in internal browser and selected adblock from the menu and rssgaurd crashed.  I restarted and selected and it takes a log time to show filter lists and crashes occasionally or gives a message about closing.

**Comment by martinrotter** [comment]
Do you have rssguard process standard/error output? Log to a file and post a log perhaps.

**Comment by pcause** [comment]
is there a setting on windows to capture a log?  I don't see.  Sorry if I'm missing something.  Portable installation.

**Comment by martinrotter** [comment]
https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#cli

**Comment by martinrotter** [comment]
I have a hard time reproducing this, for me it does not crash, log could help.

**Comment by martinrotter** [comment]
I made some significant testing and was not able to reproduce :( closing. Feel free to re-open if any new symptoms or something comes up.
