### ISSUE TITLE
Quickly deleting many items causes segfault

### ISSUE THREAD

**Issue by CsatiZoltan** [martinrotter/rssguard#324]
#### Brief description of the issue

I noticed several times (so it is not a one-time event) that when I hold down the `delete` key to delete several items, RSS Guard exits with a segmentation fault.
See the video and the log attached.
[exception.zip](https://github.com/martinrotter/rssguard/files/5694381/exception.zip)

#### How to reproduce the bug?

Try deleting many entries, as described above.

#### What actually happened?

RSS Guard exited.

#### Other information

* OS: Ubuntu 18.04 LTS
* Desktop Environment: Gnome 3.28.4
* RSS Guard version: [3.8.3, Linux Appimage](https://github.com/martinrotter/rssguard/releases/download/3.8.3/rssguard-3.8.3-03684f5d-linux64.AppImage)

**Comment by martinrotter** [comment]
Managed to reproduce, will test.

**Comment by martinrotter** [comment]
Should be fixed, pls wait for devbuild to compile & test and let me know, thanks. :)

**Comment by CsatiZoltan** [comment]
OK, let me know when the devbuild is ready.

**Comment by CsatiZoltan** [comment]
Ahh, sorry. I checked it, but I was deceived by the commit hash `c440b7d`.
![Screenshot from 2020-12-15 13-11-05](https://user-images.githubusercontent.com/12742890/102213542-2b489580-3ed7-11eb-8484-83643bc11ff4.png)
I will try it tomorrow when I will have enough feeds to test the delete on...

**Comment by CsatiZoltan** [comment]
@martinrotter I confirm that no such segmentation fault was experienced with the developer build when deleting many elements.
