### ISSUE TITLE
[BUG] Local changes to messages are sometimes not synced back to server and are forgotten

### ISSUE THREAD

**Issue by pcause** [martinrotter/rssguard#325]
I had been using the 3.8.4 exclusively since yesterday for tt-rss.  I don't enable auto update.  I have a filter that marks all items in one category as read if they don't have a label.  I sync and read things and repeat an hour or 2 later.  I just did a sync and while the web interface shows:

tt-rss shows 570 items as unread and rssguard shows 70.

I am only sync'ing unread and the web view is also unread.  Did another sync while writing this article and the difference is still there with a small delta (5) that are likely new articles.

Sorry don't have any debug.  I deleted the database and am trying a fresh sync to see if things match.  Will update after.

**Comment by pcause** [comment]
after deleted database and syncing in the tt-rss the numbers match.

**Comment by martinrotter** [comment]
I will check it out too.

**Comment by martinrotter** [comment]
@pcause Just thinking, could the difference between unread messages in RSS Guard and unread messages in TT-RSS server be caused by improper synchronization of unread->read message state change back to server from RSS Guard?

In this case, the FULL log from whole time you run RSS Guard would help.

**Comment by martinrotter** [comment]
My internal list of TODO:
- [ ] Make sure that `CacheForServiceRoot::saveCacheToFile` is run automatically each time the cache is changed (something added or removed from cache)
- [ ] Make sure that if client -> server message state change synchronization in `ServiceRoot::saveAllCachedData` fails, then those failed states are pushed back to cache, so that re-synchronization is attempted later again and states are not dropped without synchronization.

**Comment by pcause** [comment]
definitely could and most likely is something with sync BUT I know that tt-rss has made a few changes and some caused duplicate items to appear.  You might handle this differently in terms of the logic you use to detect a dup versus tt-rss.  But I did examine and there are definitely new items in tt-rss that are unread, new not duplicated that aren't getting sycned.

BTW, thanks for the alternating backgrounds in the message list.  makes scanning much easier.

**Comment by martinrotter** [comment]
@pcause Checkout dev. build for bf0c1439 when it gets compiled, it should be more reliable.

**Comment by martinrotter** [comment]
OK, now unsynchronized changes should not be forgotten for TT-RSS and should be re-synchronized again once per minute if previous attempt fails. Also, synchronizing mechanism is gracefully interupted if rssguard is about to quit.

**Comment by pcause** [comment]
if I start a sync will that forcce any changes that are stored locally and haven't been pushed to be pushed?

**Comment by martinrotter** [comment]
No, at this point, synchronization of message states happens:
- in 1 minute intervals automatically
- if you "update" (download messages) some feeds either manually or via auto-update policy

That said, I could certainly add "Synchronize message changes" button to account context menus. Create separate feature request for that. :)

**Comment by martinrotter** [comment]
This feature is not yet done, I must rewrite some code for other plugins as well and polish it all, but from practical POV it should basically work now much better for TT-RSS.

**Comment by martinrotter** [comment]
@pcause I implemented the button: 
![image](https://user-images.githubusercontent.com/1255302/102495731-c035c500-4076-11eb-9e93-e3ec70487bf0.png)

**Comment by martinrotter** [comment]
OK last not done point "Make sure that cache is pushed to server just before user edits account in RSS Guard and clear the cache subsequently, even if previous re-synchronization fails." will be implemented as part of #336.
