### ISSUE TITLE
[FR] Remember open tabs on close/reopen on restart

### ISSUE THREAD

**Issue by pcause** [martinrotter/rssguard#326]
I open items in the internal browser and i happened to close the app and download a new test version and when I restarted my open tabs are lost!  Unexpected behavior.  One would expect open tabs to be remembered on close and reopened on restart.  A plus would be remembering the last N opened in the internal browser.  Not a full history but perhaps last 20 or whatever items (might also be a max for open tabs in browser) and then display/select to open.  Could just put a copy in a new global folder akin to the recycle bin.  right click there an empty which would be good, or restore all, and clearly the items can be opened from a message list

**Comment by pcause** [comment]
another way to do this is to assign a special label to the items when opened.  that will sync back to tt-rss as well.  let user pick the label.  that means it is easy to remember all the pages you've visited and can remove labels from one or several and see what is open on other devices.  issue:

- if syncing unread you have to sync this label in full
- if reading unread need to show this labels items/count
-

**Comment by martinrotter** [comment]
I believe this feature would be best to be added by someone else, every is welcomed to contribute. I would not use such a feature myself but I might eventually fix myself, we will see. :)

**Comment by martinrotter** [comment]
not going to happen
