### ISSUE TITLE
[FR]: Play videos with MPV

### ISSUE THREAD

**Issue by Logarithmus** [martinrotter/rssguard#332]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%243%20Funded-%2300A156.svg" />](https://issuehunt.io/r/martinrotter/rssguard/issues/332)

I guess `newsboat` has such feature. It would be even better to create a setting so each user could choose their favorite player (e. g. VLC). Links to YouTube and other video sharing services should be auto-detected. IMHO having ability to configure custom players for custom video sharing services would be even greater.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $3.00)

- [<img src='https://avatars2.githubusercontent.com/u/29541480?v=4' alt='logarithmus' width=24 height=24> logarithmus](https://issuehunt.io/u/logarithmus) ($3.00)

### Submitted pull Requests
- [#480 dummy PR for fix-mpv](https://issuehunt.io/r/martinrotter/rssguard/pull/480)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/martinrotter/rssguard/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by martinrotter** [comment]
OK, could you please expand a bit?

Where exactly in GUI should be the feature present? When you right click some link within internal web browser -> display "Play in media player" in link's context menu?

**Comment by Logarithmus** [comment]
> OK, could you please expand a bit?
> 
> Where exactly in GUI should be the feature present? When you right click some link within internal web browser -> display "Play in media player" in link's context menu?

As of now, one can setup external web browser & external mail client in `Settings -> Web browser & e-mail & proxy`.
I'd like to have the third option -- setup external video player. User should add list of URL patterns (domains, glob or regex) which RSSGuard must treat as video URLs.

After that when user clicks on some post & simplified text browser appears at the bottom of window. Now, when user clicks on some link here and if this link matches one of the "video websites" URL pattern, instead of opening a web browser, RSSGuard should open this link via video player specified in settings, such as MPV, VLC, or even youtube-dl directly.

**Comment by martinrotter** [comment]
@Logarithmus Thinking about this, it would maybe be good to just expand already implemented concept of "external tools", right?

Each ext. tool currently is basically some executable + parameters and URL is passed as `%1`. Maybe I could add one more attribute for each external tool called "trigger regular expression" and this would be used automagically by RSS Guard each time any link is triggered and appripriate ext. tool would then get automatically called if that happens.

Also, all ext. tools would be available in any link context menu to make them callable manually.

What you think?

**Comment by martinrotter** [comment]
OK. At this point RSS Guard contains some fixes which allow to play ALL hyperlinks and article URL with any media player:

1. You must add `mpv` to list of external tools in app settings.
2. You can right-click article and select `Open with external tool`.
3. Or you can right-click any hyperlink in article preview and select `Open with external tool` there.

Little demonstration with `mpv.exe` and Youtube below. Therefore I consider this fixed.

![LQ4beRMbip](https://user-images.githubusercontent.com/1255302/131455821-5624d80c-d212-4fae-a2af-185d2412d26e.gif)

**Comment by martinrotter** [comment]
posted dummy PR for bountysource - https://github.com/martinrotter/rssguard/pull/480

**Comment by martinrotter** [comment]
@Logarithmus Btw, please, if you feel like you want to donate, do that over Github Sponsors or Perhaps patreon. I will probably cancel IssueHunt because they have some weird withdraw money limitations.

**Comment by fislysandi** [comment]
well thank you so much mate now i can CONSOOM yt in peace.

**Comment by fislysandi** [comment]
also cancelling donation is was kinda scummy move.
