### ISSUE TITLE
[FR]: Hide buttons in message pane

### ISSUE THREAD

**Issue by morgannunan** [martinrotter/rssguard#333]
#### Brief description of the feature request.
I'm glad I can hide the toolbar buttons in the feed and message lists, but I'd like to also hide the buttons in the message pane — especially the vertical toolbar. I"m using RssGuard with my PinePhone and I could use that horizontal space.

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/103425661-257bd100-4bb4-11eb-925d-43ccb8685d85.png)

**Comment by martinrotter** [comment]
@morgannunan Btw, could you please please post some screenshots with RSS Guard running on PinePhone, perhaps even with phone /w screen displayed on the photo?

**Comment by morgannunan** [comment]
![IMG_20201231_215545](https://user-images.githubusercontent.com/8991137/103433251-e0579f00-4bb3-11eb-9b25-a33f91dd3906.jpg)
![IMG_20201231_215651](https://user-images.githubusercontent.com/8991137/103433252-e0f03580-4bb3-11eb-8288-dbc3eca28646.jpg)

Mobian doesn't yet have a screenshot option, as far as I know. But this is what it looks like. Also — and I don't know if I should create a new issue for this — but everything in the main menu has stopped working. I can't click on any of the items, or the home button. I can even hook up a bluetooth mouse to my phone and clicking with that doesn't do anything.

**Comment by martinrotter** [comment]
@morgannunan I forgot to write that the feature is switchable from "View" menu:

![image](https://user-images.githubusercontent.com/1255302/103438678-88fa1300-4c35-11eb-89ae-30c0aa48bebc.png)

As for the main menu - this is very weird. I click on main menu items hundred times a day and it just works. Create separate issue.

**Comment by morgannunan** [comment]
I see. For now, if I wanted this feature, I would have to build from source, until the next release. Is that correct?

**Comment by martinrotter** [comment]
Well, yes. I hoped to add automagically built binaries for Arm too but Github Actions does not seem to support Arm64 yet.

Therefore you might need to wait until 3.8.4 gets out and Debian includes it or build for yourself, which is really not a problem if your phone has full blown distro.

https://github.com/martinrotter/rssguard/blob/master/build.pro

Also, you might see what the actual build dependencies for Debian are: https://github.com/norbusan/rssguard-debian/blob/master/debian/control#L5

**Comment by martinrotter** [comment]
@morgannunan Almost forgot, RSS GUard is also available as FLATPAK on Flathub which I believe also provides ARM builds.
