### ISSUE TITLE
[FR]: Proxy Support Per Account

### ISSUE THREAD

**Issue by zero77** [martinrotter/rssguard#334]
Unless i am mistaken, at the moment proxies can either be turned on for every account, or turned off for every account.

Can you give the option to enable or disable proxy separately for each account, thanks.

**Comment by martinrotter** [comment]
Working on this.

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/105333947-96704080-5bd6-11eb-81a7-6ba0fdc81719.png)

**Comment by martinrotter** [comment]
Just added experimental support for standard RSS/RDF/ATOM/JSON account plugin. You can new "Edit" account and the above dialog will show, where you can safely enter your proxy data. Pls test and let me know.

The proxy setup directly in account has higher priority than application-wide proxy. Also, if you keep your acc proxy at "Default proxy" type, then application-wide proxy is used if set.

https://github.com/martinrotter/rssguard/commit/8e95f8a5ec1481d7b9a50b5eeabd42b47e0961d0

**Comment by zero77** [comment]
Where can i find the latest AppImage to test with.

**Comment by martinrotter** [comment]
@zero77 https://github.com/martinrotter/rssguard/releases/tag/devbuild

**Comment by zero77** [comment]
After testing both socks5 and http proxys work fine.

**Comment by martinrotter** [comment]
@zero77 OK, will add support for remaining plugins.

**Comment by martinrotter** [comment]
Fixed, should now work with all accounts, including oauth accounts.

**Comment by zero77** [comment]
Thanks
