### ISSUE TITLE
Please add API/Function to allow periodically back rssguard DB (as under File -> Back database/settings)

### ISSUE THREAD

**Issue by xmstspider** [martinrotter/rssguard#34]
#### Brief description of the issue.

I would like to backup rssguard settings and DB periodically (like a cron . hourly/daily/monthly/yearly) using some built-in function och API.
#### How to reproduce the bug?
1. Under File -> Backup database/settings
2. Not possible scheduling this task
#### What is the expected result?

Able to schedule a backup of database and settings
#### What actually happened?

Currently only a manual backup is supported

**Comment by martinrotter** [comment]
Thinking closely about this. I imagine scenario, where user has **big** SQLite database file. Let's say 500 MB, which is quite ordinary size. Problem is that during copying this file to backup location, it cannot be accessed by RSS Guard to perform feed/message operations. Thus, automatically scheduled backup operation would have to be performed when program starts or quits.

It would delay RSS Guard startup/shutdown times either way. What do you prefer? Doing backup on launch or when app quits? I probably prefer doing it on application launch, it seems to be that it would be less painful solution.

**Comment by xmstspider** [comment]
I would recommend to do a (cheap) copy at the same location a move the file to the backup location afterwards. This would save the time when the application starts or quits and doesn't affect the current file.

Triggering this function manually using an API would wait for an opportunity like e.g. yum/dnf is working when starting new thread, so:

1. rssguard is running and e.g. updating the DB
2. user requests an backup/restore using an API
3. rssguard returns/prints a message like Waiting for lock, please wait.
4. rssguard is done updating the DB, API call takes over and block the file to prevent rssguard using it
5. API releases the lock

**Comment by JKingweb** [comment]
Doesn't it make more sense to use operating system functionality for this?  If you're running Linux you can use LVM snapshots or file system snapshot capabilities (with ZFS or btrfs) to safely read the files and back them up to wherever you wish, either using a tool like Duplicity or simply tar. If the database (assuming SQLite, here) is in the middle of a write operation, the journal will simply be played back when you open the backup file, and will thereafter be in a consistent state.

If running Windows there are many backup tools that make use of Volume Shadow Copy to achieve the same result.

**Comment by martinrotter** [comment]
> Doesn't it make more sense to use operating system functionality for this?

This came to my mind today. Definitely!

Even something like `backup-current-rssguard-setup.sh && rssguard` can do enough. In windows, there is cmd, so you just write very simple .bat file to copy your current user data to Dropbox maybe?

Closing for now, postponing, will implement if more votes comes in.
