### ISSUE TITLE
[BUG]: by 3.5.9 to 3.8.2

### ISSUE THREAD

**Issue by pipiscrew** [martinrotter/rssguard#341]
last tested v3.5.9,  **v3.8.2** I just replaced by old feed reader. Few things, expecting to be there :

1)
on **feeds treeview**, cant reposition the items :( the reposition line is just identicator to drop the feed to **another folder** :(

2)
on listview, on **mouse context menu**, should be an option "Copy to clipboard", should also handle multiselected.

3)
when double click an article, goes to default browser-fine, after **1sec pop the main app window**, should an option on/off?

as I see v3.8.3 is responsible for this :
```
*added 
When you run "open source article externally" action, then RSS Guard window
regains focus again.
```

?

4)
Will be more cute, on listview to display the **RSS icon** (as is on treeview), for 'if is red' indicator we have the **bold text**... Now all are unique, dont know which feed Im reading... :( have to check the treeview selected node.

4)bug
I can get the RSS of 
https://jlelse.blog/index.xml

by the browser, the app writes :
![image](https://user-images.githubusercontent.com/3852762/105630901-47374380-5e54-11eb-9f7d-008dc9e50982.png)

getting host not found

--

great updates, thanks for your time!

**Comment by martinrotter** [comment]
1. Already reported - https://github.com/martinrotter/rssguard/issues/302
2. Report in separate ticket, please. Describe desired behavior carefully.
3. This is new default behavior and it is configurable:
![image](https://user-images.githubusercontent.com/1255302/105640786-297fd380-5e80-11eb-8807-8b13d107a2eb.png)
4. Report in separate ticket, please. Describe desired behavior carefully. At this point I totally do not understand what you meant with the point. :)
5. Bug with that feed is now fixed: https://github.com/martinrotter/rssguard/commit/193748f8367a416409562e6bc2d620901165b1f5

**Comment by pipiscrew** [comment]
tried 
```
rssguard-3.8.4-7ab95a75-nowebengine-win64.7z
rssguard-3.8.4-7ab95a75-win64.7z
```

![image](https://user-images.githubusercontent.com/3852762/105641379-3c000a00-5e8c-11eb-9d20-23cca6e93e72.png)


the is **no such option** as the screenshot you posted. please advise.

also the repositioning is not working...

what is the difference between **nowebengine** and **plain** version ?

**Comment by martinrotter** [comment]
Yes, because the option was added in the version 3.8.5 which is not yet published, but you can at your own risk download latest development build which already contains the feature: https://github.com/martinrotter/rssguard/releases/tag/devbuild

Repositioning is the requested feature which was reported but was not implemented yet: https://github.com/martinrotter/rssguard/issues

As for nonwebengine vs normal versions, read [documentation](https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#web-based-and-lite-app-variants) carefully.

**Comment by martinrotter** [comment]
EDIT: Wait 10-15 minutes, new development build binaries will appear in https://github.com/martinrotter/rssguard/releases/tag/devbuild shortly.
