### ISSUE TITLE
[BUG]: feed stop working on v3.8.5

### ISSUE THREAD

**Issue by pipiscrew** [martinrotter/rssguard#342]
Previously used v3.8.3, the below feed can be parsed.

https://www.hiveandhoneyapiary.com/honey-bee.xml

now, showing this error 
![image](https://user-images.githubusercontent.com/3852762/105642980-c7ca6400-5e95-11eb-9638-794654b34814.png)

--

FYI - Another feed couldnt be parsed on v3.8.3 - working fine with v3.8.5

--

#### How to reproduce the bug?

1. add the feed to RSSGuard

#### Other information

* OS: win7x64
* RSS Guard version: v3.8.5

**Comment by martinrotter** [comment]
Working fine here, the feed is being redirected to via http/301 redirect. Please, test with latest development build, I fixed these redirection errors yesterday.

![image](https://user-images.githubusercontent.com/1255302/105674165-659a4f00-5ee7-11eb-882b-2c3179ab057c.png)
