### ISSUE TITLE
[FR]: Treeview main node - Context menu option - Collapse/Expand nodes

### ISSUE THREAD

**Issue by pipiscrew** [martinrotter/rssguard#344]
On the treeview main node, when user right click then node, on the mouse context menu, should be added 2 more options

-Collapse
-Expand

which doing the needed on **children folder** nodes.

![image](https://user-images.githubusercontent.com/3852762/105643170-f8f76400-5e96-11eb-9c52-eb8ecafd3538.png)

**Comment by martinrotter** [comment]
You can expand/collapse by mousel double-click or with keyboard arrows. I believe it is enough for now. If more people request this, I will implement.

**Comment by pipiscrew** [comment]
imagine that I have expanded **20 folders** under the main node, **there is no option** to collapse with a click.

**Comment by martinrotter** [comment]
OK, fixed. Feel free to test via development build and let me know.
