### ISSUE TITLE
[FR]: New option for listview selected items

### ISSUE THREAD

**Issue by pipiscrew** [martinrotter/rssguard#345]
When user right click the listview there is a context menu, there should be added an option "**Copy link**"

![image](https://user-images.githubusercontent.com/3852762/105643253-5f7c8200-5e97-11eb-8e75-2a2f8758dfd9.png)

when multiple lines are selected, should be take care of it.

sample of output to **clipboard**

```
https://test1.com
https://test2.com
https://test3.com
```

**Comment by Anomnomnomous** [comment]
There are xclip scripts that work for now as workarounds if setup under External tools. Unfortunately, I don't think that would work very well with the flatpak version.
