### ISSUE TITLE
[FR]: Listview item icon must 'carry' feed main icon

### ISSUE THREAD

**Issue by pipiscrew** [martinrotter/rssguard#346]
when the **state** of the **listview item** is on : 
-read
-unread

must shown the **feed icon** as is on **treeview**. this make **user** more quick understandable which **feed URL** is reading.

![image](https://user-images.githubusercontent.com/3852762/105643408-5f30b680-5e98-11eb-95f4-f4b6acb55872.png)

**Comment by martinrotter** [comment]
The icons on the right are read, unread icons, not "feed" icons.

**Comment by pipiscrew** [comment]
for read/unread, there is the **title** plain/bold text. Personally this what I check is more obvious for the eye because the width area is bigger than an icon.

**Comment by martinrotter** [comment]
@pipiscrew Would feed's icon in existing "Feed" column be enough? Or do you need to add one more column which contains ONLY icon? Is solution from picture below enough?

![image](https://user-images.githubusercontent.com/1255302/105671680-6630e680-5ee3-11eb-9796-65c04742a8f1.png)

**Comment by martinrotter** [comment]
@pipiscrew your last comment actually makes sense, let me test.

**Comment by martinrotter** [comment]
@pipiscrew OK, or this solution, of course switchable. Which on do you prefer? Me myself prefer the first variant with icon being in "Feed" column along with feed title, but both options are doable.

![image](https://user-images.githubusercontent.com/1255302/105672085-1bfc3500-5ee4-11eb-9d89-1cd925460dbc.png)

**Comment by pipiscrew** [comment]
ofc the last one^ minimal, otherwise you know is too 'heavy', too many icons.

**Comment by martinrotter** [comment]
OK, fixed, feature is switchable in settings -> feeds/messages -> messages.

![image](https://user-images.githubusercontent.com/1255302/105673704-b8273b80-5ee6-11eb-8749-3f154c1d7c32.png)
