### ISSUE TITLE
[BUG]: Sort by `Id` is broken in 3.8.4 

### ISSUE THREAD

**Issue by juneidysoo** [martinrotter/rssguard#348]
#### Sort by `Id` is sorting by string representation instead of numeric.

Up until `rssguard-3.8.3`, sorting by `Id` works as expected where it sorts by numeric order.

![sort-working](https://user-images.githubusercontent.com/13762553/105649718-3f55be80-5ea9-11eb-9c25-1c12440e906b.png)

Starting `rssguard-3.8.4`, the sort is based on the string representation, which is arguably not right.

![sort-broken](https://user-images.githubusercontent.com/13762553/105649757-55fc1580-5ea9-11eb-81a8-9223518874dc.png)

#### How to reproduce the bug?

1. Show Id column
2. Sort feed by Id

#### What was the expected result?

Sort should be based on the numeric order.

#### What actually happened?

Sort is based on the string representation.

#### Other information

* OS: Linux 5.9.12-arch1-1
* Desktop Environment: awesome
* RSS Guard version: 3.8.4

**Comment by martinrotter** [comment]
Fixed, thanks for reporting, test with latest dev. build.
