### ISSUE TITLE
I just can't create new categories and change the language of the app.

### ISSUE THREAD

**Issue by hugofeijo** [martinrotter/rssguard#35]
#### Brief description of the issue.

I just can't create new categories and change the language of the app.

#### How to reproduce the bug?

1. 
2. 
3.

**Comment by hugofeijo** [comment]
Thanks for your close attention to the matter.
Best wishes,
Hugo

**Comment by martinrotter** [comment]
Hello. Please, provide debug logs. Follow [this](https://github.com/martinrotter/rssguard/wiki#generating-debug-log-file).

**Comment by hugofeijo** [comment]
As soon as I find the next latest version of RSSguard I'll download and install it to check the new improvements. Thanks.

**Comment by martinrotter** [comment]
Bug is solved?

**Comment by hugofeijo** [comment]
No, not yet. I'm a layman, sorry.  I'm gonna wait for a new version of your app.
Thanks a lot for your kind attention to this matter.
Keep up the good work!
Best wishes,Hugo 

    On Friday, July 1, 2016 1:17 AM, martinrotter <notifications@github.com> wrote:
 
 

 Bug is solved?—
