### ISSUE TITLE
[FR]: Notification sound on new feeds

### ISSUE THREAD

**Issue by guixxx** [martinrotter/rssguard#356]
#### Brief description of the feature request.

Hi, sorry for spamming the issue tracker, but coming from different RSS readers, most of them had this feature to play a bell sound once new feeds arrived. I think that on Windows this is already possible because their desktop notifications play a bell or something (can't remember), and on KDE this can be configured on a per-program basis, IIRC.

Since I use XFCE, I don't think there's a "native" option for this, unfortunately. If you choose to implement this, it could be an opt-in setting, instead of opt-out, so it doesn't annoy Windows or KDE users with two notification sounds... 😄 

And this would also be just perfect if we could enable these sounds on a per-feed basis, instead of globally.

Thank you again!

**Comment by martinrotter** [comment]
Yes, this is entirely possible. I will add this somewhere along the way.

At this point RSS Guard has one more huge feature incoming - official support for Feedly - and then it will be time to do this too.

**Comment by guixxx** [comment]
Awesome! I just have one more question (and kind of a suggestion too): from my own observation, it seems that RSS Guard groups all feed updates in a single [desktop notification without an icon](https://github.com/martinrotter/rssguard/blob/0f4c9ecd6417ec8fb992113c50d1a91e8626544f/src/librssguard/miscellaneous/application.cpp#L534), so if you do consider adding my second suggestion, I think it would also make sense to:

* Make notifications configurable per feed, therefore not grouping all of them anymore
* Add the pretty RSS Guard icon to notifications :D

Thank you for this amazing program!

**Comment by martinrotter** [comment]
This was kind of reported: https://github.com/martinrotter/rssguard/issues/144

**Comment by fabianski7** [comment]
This will be very useful to replace youtube push notifications
Looking forward to it

**Comment by martinrotter** [comment]
WIP

![image](https://user-images.githubusercontent.com/1255302/122057015-77bf5000-cdea-11eb-874f-7065a452ad39.png)

**Comment by martinrotter** [comment]
Experimental implementation is done. Test via development build, please.

ab1011be

**Comment by guihkx** [comment]
Tested on GNOME 40, works for me! Thx :)
