### ISSUE TITLE
[BUG]: All console output sent to stdout

### ISSUE THREAD

**Issue by norbusan** [martinrotter/rssguard#359]
#### Brief description of the issue.

Always logs debug statements to stdout.

#### How to reproduce the bug?

1.  Build and run
2. See messages like
```
time="     0.658" type="debug" -> core: Showing tray icon.
time="     0.659" type="debug" -> gui: Creating SystemTrayIcon instance.
time="     0.659" type="debug" -> gui: Showing tray icon with 1000 ms delay.
```

#### What was the expected result?

Only issue debug messages on request, or only when saving logs to a file.

#### What actually happened?

Flooding of .xsession-errors

#### Other information

* OS: Linux
* Desktop Environment: KDE/Plasma
* RSS Guard version: 3.8.4

**Comment by martinrotter** [comment]
OK, I tweaked the behavior, now all console messages are printed to `stderr`. POSIX standard and related guidelines are quite unclear where "informational" console outputs belong to.

Some people prefer to print informational messages to `stdout` and critical messages to `stderr`. Now everything goes to `stderr` to keep default output channels clear.

**Comment by norbusan** [comment]
Thanks Marin for looking into this, but I don't think it is about stdout versus stderr. I think that rssguard shouldn't send out debug messages *at all* when not asked to. I guess when I start it from the menu or automaticaly on login, both stdout and stderr will be captured and end up again in the .xsession-errors file which grows and grows (last time I deleted it it was 3G).

**Comment by martinrotter** [comment]
@norbusan I respectfully disagree. Primary purpose of built-in output streams is to capture expected/primary application output to `stdout` and diagnostic/debug/warning/error data at `stderr`. It is completely normal, that even GUI application outputs diagnostic data to `stderr`.

That said, I added a CLI switch "-n" which allows you to completely disable all console outputs, if you really wish to.

795e1b2f

**Comment by martinrotter** [comment]
```
RSS Guard

Options:
  -l, --log <log-file>           Write application debug log to file. Note that
                                 logging to file may slow application down.
  -d, --data <user-data-folder>  Use custom folder for user data and disable
                                 single instance application mode.
  -s, --no-single-instance       Allow running of multiple application
                                 instances.
  -n, --no-debug-output          Completely disable stdout/stderr outputs.
  -?, -h, --help                 Displays help on commandline options.
  --help-all                     Displays help including Qt specific options.
  -v, --version                  Displays version information.
```

**Comment by guihkx** [comment]
FWIW, this is especially annoying on GNOME, which logs the entire output of graphical programs to the system journal.

This new option is much appreciated, but alternatively you can also disable these debug messages using the [QT_LOGGING_RULES environment variable](https://wiki.archlinux.org/index.php/qt#Disable/Change_Qt_journal_logging_behaviour).

**Comment by norbusan** [comment]
Cool, thanks, didn't know about this env var. I guess one has to set it in `/etc/environment` otherwise it will be never picked up by Plasma desktop.
