### ISSUE TITLE
[FR]: Nextcloud 2FA

### ISSUE THREAD

**Issue by renatobellotti** [martinrotter/rssguard#360]
Are there plans to add support for 2FA for Nextcloud?

**Comment by martinrotter** [comment]
See https://github.com/nextcloud/news/blob/master/docs/externalapi/Legacy.md

Quote:
> Because REST is stateless you have to send user and password each time you access the API. Therefore running Nextcloud with SSL is highly recommended otherwise everyone in your network can log your credentials.

Therefore it seems that 2FA for Nextcloud News is not even supported upstream. You must file your feature request [there](https://github.com/nextcloud/news/issues).

**Comment by renatobellotti** [comment]
The Nextloud News Android app can login, but I think they use the Android account framework. Not sure how they handle things, but perhaps it might be useful to look at their code if somebody has the time, but I understand that it's not a priority for you.

**Comment by CyberTailor** [comment]
You can generate application passwords and use them in RSS Guard
