### ISSUE TITLE
[BUG]: Crash when running "Synchronize folders" and "Download messages" at same time

### ISSUE THREAD

**Issue by nyanpasu64** [martinrotter/rssguard#362]
#### Brief description of the issue.

If I have a Google Reader account, and run "Synchronize folders & other items" and "Download messages for selected items" at the same time, RSS Guard crashes (probably due to a data race).

#### How to reproduce the bug?

1. If you don't have one already, add a Google Reader API account (in my case, The Old Reader).
    - It should automatically download the list of folders; if not, run "Synchronize folders & other items".
2. In the left feed list, right-click the account and run "Synchronize folders & other items".
3. Before the synchronization completes, right-click the account again and run "Download messages for selected items" (these steps can occur in either order).

#### What was the expected result?

The program does not crash.

#### What actually happened?

The program crashes.

#### Other information

* OS: Arch Linux
* Desktop Environment: KDE
* RSS Guard version: AUR `rssguard-git`, master 6faeba1185480e87635669d2e73d8e66ad5af794

**Comment by martinrotter** [comment]
Hello @nyanpasu64.

Yes, you actually discovered one of the main weak points of RSS Guard - synchronization of critical operations. I am thinking for some time about improving it and I will certainly do in weeks/months to come.

For the time being, please stay away from using those two features at the same time. :)

**Comment by martinrotter** [comment]
Closing this, if issue persists, please re-open with new information. I was not able to easily reproduce the issue lately.
