### ISSUE TITLE
[FR]: Fallback to "favicon.ico" when an icon is not found

### ISSUE THREAD

**Issue by guihkx** [martinrotter/rssguard#363]
#### Brief description of the feature request.

I'm not familiar with how RSS Guard fetches icons of feeds, but it seems to work great in general, i.e. all of my feeds have the proper icon for them. The only site I'm having an issue at the moment is Github.

For instance, when you add the following ATOM feed to RSS Guard:

`https://github.com/martinrotter/rssguard/commits/master.atom`

RSS Guard won't get an icon for that feed:

![image](https://user-images.githubusercontent.com/626206/108896885-38c77d80-75f4-11eb-8343-ada0f82746b4.png)

So I thought about this fallback solution:

1. RSS Guard extracts the domain from that URL: `github.com`
2. RSS Guard adds `/favicon.icon` at the end of that URL
3. RSS Guard will then make a request to: `github.com/favicon.ico`
4. If the request successfully returns an image, then RSS Guard uses that. Otherwise, it sets an empty icon.

Thoughts?

---

**Version:** 3.8.4 (built on Linux/x86_64)
**Revision:** -nowebengine
**Build date:** 1/22/21 8:19 PM
**Qt:** 5.15.2 (compiled against 5.15.2)

**Comment by martinrotter** [comment]
I see. RSS Guard uses quite ellaborate way of detecting icons 

https://github.com/martinrotter/rssguard/blob/master/src/librssguard/network-web/networkfactory.cpp#L140

it tries to download icon directly if specified in the feed, otherwise fallbacks to `http://www.google.com/s2/favicons` service

i will test with the feed and try to improve

**Comment by guihkx** [comment]
Thanks for linking the code, the method seems very robust. One can wonder why Google is returning an empty icon for the GitHub domain, though...

**Comment by guihkx** [comment]
Small observation: Any reason to use `http` instead of `https` for that Google request?

**Comment by guihkx** [comment]
DuckDuckGo's favicon service seems to work just fine for GitHub:

https://external-content.duckduckgo.com/ip3/github.com.ico

Perhaps it could also be added as an option in RSS Guard.

**Comment by martinrotter** [comment]
> Small observation: Any reason to use `http` instead of `https` for that Google request?

No specific reason, probably just overlooked it. I will replace it with duckduckgo as pretty much hate google for their policies.

**Comment by martinrotter** [comment]
Fixed, please test with newest dev. build when they become available.

**Comment by martinrotter** [comment]
> Thanks for linking the code, the method seems very robust. One can wonder why Google is returning an empty icon for the GitHub domain, though...

Maybe because Github is owned by Microsoft? Who knows.

**Comment by guihkx** [comment]
> Fixed, please test with newest dev. build when they become available.

It works! Thanks :)

![image](https://user-images.githubusercontent.com/626206/109020790-0b80db00-7699-11eb-8454-5363855a28d0.png)

**Comment by guihkx** [comment]
Sorry to bump this again.

3.9.0 just got available in Arch repos, so I decided to delete RSS Guard's database and start from scratch.

After manually adding feeds (instead of importing the OPML file), I noticed that a couple of them had the "incorrect" icon. For example, this is how a Reddit feed icon looks on 3.9.0:

![image](https://user-images.githubusercontent.com/626206/109547536-3d83aa00-7aaa-11eb-90c1-f2ac682b0afc.png)

So, I deleted my database again and downloaded the AppImage of version 3.8.4, but this "bug" was still there too:

![image](https://user-images.githubusercontent.com/626206/109547733-80de1880-7aaa-11eb-8d64-5a5b2386c805.png)

Then, I went back a single version (3.8.3), and now the icon was chosen correctly:

![image](https://user-images.githubusercontent.com/626206/109547874-b125b700-7aaa-11eb-97f5-516095ad2f5d.png)

Here's a list of feeds that have different icons between 3.8.3 and 3.8.4, so you can try to reproduce:

* https://old.reddit.com/r/linux/new/.rss
* http://feeds.feedburner.com/tecnoblog
* https://www.zdnet.com/topic/linux/rss.xml

**Comment by guihkx** [comment]
I'm almost sure this was the commit that introduced the issue: https://github.com/martinrotter/rssguard/commit/f11824ea2b319f17eefdeba1b6c09ddbffb7e58b

All 3 websites I linked above have either `image` or `logo` set. Additionally, Reddit has `icon` set to a broken URL (because of a slash added at the end🤦‍♂️):

![image](https://user-images.githubusercontent.com/626206/109549300-8f2d3400-7aac-11eb-897e-419b8098b18b.png)

I'm not even sure what to suggest here. I'd imagine that commit fixed has also fixed a lot of feeds with wrong icons as well, so reverting it might not be feasible...

Perhaps try checking for the width and height of the the icon, if they match, use that. Otherwise fallback to DuckDuckGo's provider? I don't know...

**Comment by martinrotter** [comment]
Will check.

**Comment by martinrotter** [comment]
> 

> Perhaps try checking for the width and height of the the icon, if they match, use that. Otherwise fallback to DuckDuckGo's provider? I don't know...

I wish all bug reporters would be that smart. I will investigate and it seems very likely that "icons" provided by those feed XML tags are indeed not that suitable. I know that some feeds provide HUGE pictures as icons. Your suggestion might work and I will investigate myself.

**Comment by martinrotter** [comment]
@guihkx OK, I did check the situation. There are several problems:
* some feeds report icons via their feed XML tags (`logo`, `icon`, `favicon`, etc.) and those are sometimes invalid as you also noticed with that Reddit feed,
* some icons provided by feed XML files are not in fact icons, they are large, non-square pictures,
* some icons provided by feed XML files are large, but are square and are correctly rescaled by RSS Guard and are OK, while other large square pictures have too many details thus are unsuitable to be displayed in RSS Guard feeds list in "favicon" size,
* some feeds are provided via 3rd-party services or generated offline and those need to include "link" to the original website so that DuckDuckGo can fetch.

Quite a mess. There are only three ways:
* Remove fetching of icons from the feed again.
* Prioritize icons obtained from DuckDuckGo.
* Prioritize icons obtained from feed XML file.

I will try to rewrite the logic and prioritize files provided by DuckDuckGo while trying to obtain correct source doman from the feed.

I will let you know when dev. build is ready.

**Comment by martinrotter** [comment]
OK, done, I wrote small comment about prioritization of individual ICON sources: https://github.com/martinrotter/rssguard/blob/master/src/librssguard/services/standard/standardfeed.cpp#L261

I tested with your example feeds and now all fetched icons seem to be much better.

TL:DR -> I decided to prioritize raw "homepage" links included in feed files.

Dev. build is compilling, test.

**Comment by guihkx** [comment]
Thank you so much for fixing this so quickly! Just gave the dev build a spin and I really like the new approach.

Thanks!

**Comment by martinrotter** [comment]
@guihkx Yes, keep in mind that at this point, development builds are auto-build for next-gen 4.x version which is in highly experimental state and IS broken at this point.

Some changes (as this one) are backported to 3.9.1, which will be released when needed and will only fix bugs like the one we had here.
