### ISSUE TITLE
No option to add a Feedly account option (using Flatpak and AppImage)

### ISSUE THREAD

**Issue by logix2** [martinrotter/rssguard#364]
I understand that "some builds of RSS Guard do not have embedded production Feedly API keys". However, I don't even see the Feedly account option using RSS Guard 3.9.0, so how can I add my own developer access token?

I've tried RSS Guard installed from Flathub as well as the AppImage on Ubuntu 20.10, and it's the same:

![image](https://user-images.githubusercontent.com/38005360/108990367-6b7a8000-769f-11eb-9157-c45564683640.png)

**Comment by martinrotter** [comment]
@logix2 You are correct, I made a mistake, pushed a fix and will overwrite all 3.9.0 packages.

https://github.com/martinrotter/rssguard/commit/a939e237bd02be60492514b023efcfd1943a842d

So wait until they get compiled and re-published. Sorry for inconvenience, I fucked up.

**Comment by logix2** [comment]
Thank you!

**Comment by martinrotter** [comment]
I trigerred re-build on Flathub too, but preferably use AppImage.
