### ISSUE TITLE
[BUG]:  Build fails with Qt 5.12.7

### ISSUE THREAD

**Issue by lgbaldoni** [martinrotter/rssguard#365]
#### Brief description of the issue.

Build fails with Qt 5.12.7

#### How to reproduce the bug?

1.  Have Qt 5.12.7 installed 
2.  Run qmake
3.  Run make

#### What was the expected result?

A successful build.

#### What actually happened?

See [log snippet](https://github.com/martinrotter/rssguard/files/6036147/rssguard_390_Leap152.txt).

#### Other information

* OS: openSUSE Leap 15.2
* Desktop Environment: Plasma 5
* RSS Guard version: 3.9.0

**Comment by martinrotter** [comment]
@lgbaldoni I pushed new commit 56e72357. Can you please somehow do quick test if it is now fixed?

**Comment by lgbaldoni** [comment]
Works for me, thanks.

**Comment by martinrotter** [comment]
@lgbaldoni OK, I will update 3.9.0 tag to point to that commit.

**Comment by martinrotter** [comment]
@lgbaldoni Done.
