### ISSUE TITLE
[FR]: Linux compilation instructions.

### ISSUE THREAD

**Issue by Achaean** [martinrotter/rssguard#366]
I couldn't find any.
(Only for OS2).

If there already are there, but I just couldn't locate them, just ignore this report, or change it to something like an easier way to read them.
(Maybe a web page, or a readme file or something).

.
**Bye!!!**  :-)

**Comment by martinrotter** [comment]
Hello.

In fact, compilation steps consist of "holy trinity". In case of Qt programs, it usually looks like

```
qmake ....../projectfile.pro .... SOME_ARGUMENTS
make
make install
```
More specific build instructions are placed directly in project file - https://github.com/martinrotter/rssguard/blob/master/build.pro#L1

**Comment by Achaean** [comment]
**THANKS!!!**  ;-)

Let me insist though, it maybe easier to have the build instructions, in an INSTALL text file, or as an alternative, at some reference at home page (maybe a link to a wiki page).
