### ISSUE TITLE
[BUG]: Browser Bypassing Proxy

### ISSUE THREAD

**Issue by zero77** [martinrotter/rssguard#367]
#### Brief description of the issue.
The new proxy per account option seems to be working well. 
But, when you view a post from a feed in rssguards browser it bypasses the proxy.

#### How to reproduce the bug?

1. Add proxy to an account 
2. update feed
3. View one of the feeds in the browser, which is not using the proxy that was set.

#### What was the expected result?
The browser should be using the proxy that was set for that account.

#### What actually happened?
The browser does not use the proxy that was set for that account.

#### Other information

* OS: Debian
* Desktop Environment:i3
* RSS Guard version:3.9.0

**Comment by martinrotter** [comment]
@zero77 This is because internal web browser uses application-wide proxy settings which you can set in Settings dialog.

Do you say that internal web browser should take account-specific proxy settings into account and perhaps prioritize it?

**Comment by zero77** [comment]
> Do you say that internal web browser should take account-specific proxy settings into account and perhaps prioritize it?

I think this would make more sense as other people are also lightly to presume that when viewing feeds for an account with a proxy enabled the browser will also be using a proxy. Also, if you are using a proxy to bypass blocks you will not be able to read the feed with out it.

**Comment by martinrotter** [comment]
While I personally agree with your POV I have bad news. Upstream libraries (Qt) sadly do not allow to set per-webengine-view proxies. They only allows to set application-wide proxies, so this features simply cannot be implemented even if I wanted. :(

**Comment by zero77** [comment]
Thank you for having a look.

Would it be possible to have a warning message before any content is fetched when proxies have been enabled. 
So people cant decide if they want to view feeds in internal browser with out a proxy or external browser with their own settings.
