### ISSUE TITLE
Broken 2byte characters

### ISSUE THREAD

**Issue by mahdi1234** [martinrotter/rssguard#37]
#### Brief description of the issue.

Seems like 2byte characters are not displayed correctly.

#### How to reproduce the bug?

Subcribe to attached Chawangshop.xml

[Chawangshop.zip](https://github.com/martinrotter/rssguard/files/355549/Chawangshop.zip)

- displayed in wenbrowser chs_seamonkey.png

![chs_seamonkey](https://cloud.githubusercontent.com/assets/1097047/16707898/cafe2e50-45df-11e6-9f30-def44577f631.png)

- displayed in tt-rss chs_tt-rss.png

![chs_tt-rss](https://cloud.githubusercontent.com/assets/1097047/16707899/cb0a0022-45df-11e6-8333-8e696ed24a43.png)

- displayed in rssguard chs_rssguard.png

![chs_rssguard](https://cloud.githubusercontent.com/assets/1097047/16707897/caf73186-45df-11e6-9369-3a08d7cd0d54.png)

RSS Guard
Version: 3.3.2 (built on Linux/i686)
Revision: 34e4c1c
Build date: 7/7/16 6:43 PM
Qt: 5.7.0 (compiled against 5.7.0)

**Comment by martinrotter** [comment]
Cannot subscribe to given URL. TT-RSS says there is no feed on the site.

**Comment by mahdi1234** [comment]
There is no feed on that page I'm parsing it myself ... please use the feed in attached zip, place it locally and subscribe to it - https://github.com/martinrotter/rssguard/files/355549/Chawangshop.zip it's zipped because github doesn't allow xml

**Comment by martinrotter** [comment]
Okay. Will test.

**Comment by martinrotter** [comment]
![screenshot at 2016-07-19 19 19 17](https://cloud.githubusercontent.com/assets/1255302/16959539/e4486b9c-4de5-11e6-9a27-eb1298ac9489.png)

**Comment by martinrotter** [comment]
It seems, here it works.

**Comment by mahdi1234** [comment]
I see ... I've forced to use some Simplified Chinese font and it's still the same ... maybe platform specific? If I figure out something more I'd let you know, but feel free to dismiss this report.

**Comment by martinrotter** [comment]
Try to play with encoding of the feed, there is really no magic in this in RSS Guard. So far, closing, feel free to reopen.
