### ISSUE TITLE
[BUG]: Problems with minimizing /w tray icon

### ISSUE THREAD

**Issue by kyrawertho** [martinrotter/rssguard#371]
#### Brief description of the issue.

Application opens and immediately closes when opened from systray, but stays active on opening for the second time.

#### How to reproduce the bug?

1. Using options Hide main window when minimized & Tray icon
2. Minimize application to tray
2. Click on systray icon to open – application comes up and disappears again
3. Click icon again for window to stay active

I've finally noticed this doesn't happen when I close with [ X ], only when using minimize [ _ ].

#### What was the expected result?

Minimize to tray should work the same as close to tray.

#### Other information

Operating System: KDE neon 5.21
KDE Plasma Version: 5.21.1
KDE Frameworks Version: 5.79.0
Qt Version: 5.15.2
Kernel Version: 5.4.0-66-generic

RSS Guard version: 3.9.0*
(another note: "rssguard --version" simply shows "rssguard", no version number)

**Comment by martinrotter** [comment]
Managed to reproduce the problem. It seems to happen only on KDE, Windows works fine.

**Comment by martinrotter** [comment]
OK, I fixed it.
