### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by kittykat125** [martinrotter/rssguard#372]
- allow users to re-order categories via a sorting method or drag-and-drop
- visually distinguish between category headings and individual feeds. the counts (#) column look like they're on the same level
- allow users to get rid of recycle bin, labels and important messages
- limit the number of messages that are downloaded by the application globally via number of messages, size or other means 
- the "toolbars' column only spans the feed list pane. Space becomes scarce and icons disappear, while the messages pane has an over-abundance of space
- when you click on a message, the default URL displayed in the view below is "https://rssguard.message/". It should be the URL of the message

**Comment by martinrotter** [comment]
Hello @kittykat125.
It first, read [this](https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#reporting-bugs) and think about how to report high quality ticket. It is not good thing to mix many issues into single ticket.

To your questions:
>allow users to re-order categories via a sorting method or drag-and-drop
Already reported #302.

> visually distinguish between category headings and individual feeds. the counts (#) column look like they're on the same level
There is visual difference between category and feed. Category has "folder" icon, feeds have individual icons, feeds are indented related to category, you have tree arrows next to categories (if not empty). I believe there is a plenty of UI hints to distinguish feed from category.

![image](https://user-images.githubusercontent.com/1255302/109914842-1519cc80-7cb1-11eb-8ffa-9efa2575862e.png)

> allow users to get rid of recycle bin, labels and important messages
Please report as separate ticket.

> limit the number of messages that are downloaded by the application globally via number of messages, size or other means
Please report as separate ticket.

> the "toolbars' column only spans the feed list pane. Space becomes scarce and icons disappear, while the messages pane has an over-abundance of space
RSS Guard actually has three toolbars: feed list toolbar, message list toolbar and status bar and each of this toolbar is configured separately.
![image](https://user-images.githubusercontent.com/1255302/109915057-7477dc80-7cb1-11eb-8ef9-5b3e822a70ea.png)
![image](https://user-images.githubusercontent.com/1255302/109915082-80639e80-7cb1-11eb-8880-7cbd0d7e2934.png)

> when you click on a message, the default URL displayed in the view below is "https://rssguard.message/". It should be the URL of the message
When you click on a message, RSS Guard displays message content fetched from the feed file, not the source article available on website. If you want to go to source article, then click "URL" button.
![image](https://user-images.githubusercontent.com/1255302/109915234-c02a8600-7cb1-11eb-9524-2d576e70c708.png)

I will close this, report individual feature requests as separate tickets as stated above.

Thanks.
