### ISSUE TITLE
rssguard-3.9.0-56e72357 vs rssguard-3.9.0-a939e237

### ISSUE THREAD

**Issue by fredddii** [martinrotter/rssguard#374]
These two 3.9.0 versions are available on the release page, but which one should I pick?

**Comment by martinrotter** [comment]
Hello @fredddii. Those two versions are the same except one thing. I forget to enable Feedly plugin in "release" builds of RSS Guard so I additionally fixed the issue and re-release version 3.9.0 with the fix. Therefore version a939e237 is slightly newer.

I will remove those older builds to avoid confusion.
