### ISSUE TITLE
[FR]: RSS Guard can not be uninstalled in Windows because it does not appear in the software list

### ISSUE THREAD

**Issue by fredddii** [martinrotter/rssguard#376]
RSS Guard does not get added to the Windows software list, and thus can not be removed unless one looks up the uninstaller file manually.

**Comment by martinrotter** [comment]
Yes, RSS Guard follows [KISS](https://en.wikipedia.org/wiki/KISS_principle) so does NOT pollute OS too much. It can be easily completely uninstalled with `Uninstall.exe` file from RSS Guard's directory. No traces are left behind.

**Comment by fredddii** [comment]
@martinrotter

Would it be possible to introduce two releases in that situation? A portable edition and an installer edition?

I very much want installed software to "polute" my operating system by adding itself to the installed software list. Right now there is no way for me to know I installed the software, except for "remembering", which I will not in a couple of months or a few years if I might stop using it.

**Comment by martinrotter** [comment]
There are postable and installer editions:
* `7z` packages are "portable"
* `exe` file are installers.
Ok, I re-open this issue and will add RSS Guard to uninstall section as well, your arguments make sense. :)

**Comment by fredddii** [comment]
Thank you very much! I appreciate it.

**Comment by martinrotter** [comment]
Fixed.
