### ISSUE TITLE
[BUG]: Hard to read text with "alternate row color" in dark skin

### ISSUE THREAD

**Issue by maturz** [martinrotter/rssguard#378]
#### Brief description of the issue.

When using the dark skin and the "alternate row color" feature in under view menu the rows get difficult to read.

#### How to reproduce the bug?

1. Tools > Settings > User Interface > Skin > Dark
2. View > Alternate row colors in lists
3. Look at message list

#### What was the expected result?

Two different dark background colors alternating for each row.

#### What actually happened?

The alternating color is to similar to the text color, making it difficult to read.
[https://imgur.com/a/Cvcgeoc](https://imgur.com/a/Cvcgeoc)

#### Other information

* OS: Windows 10
* RSS Guard version: 3.9.0 (built on Windows/x86_64)

#### Comments

I tried looking for ways to customize or create your own skin but I was not able to figure out how. I think there is a possibility to add custom skins under data\skins but I was not able to find any examples. I think maybe the default skins has been moved into some kind of embedded resource? Maybe an example skin could be added to the skins folder or the documentation.

**Edit;** There also appears to be a similar problem if you create a filter and click test, you then get white text with a bright green background.

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/110582318-5b1cd780-816c-11eb-8f92-063f739440e9.png)

Fixed.
