### ISSUE TITLE
TT-RSS: Add labels

### ISSUE THREAD

**Issue by cwmke** [martinrotter/rssguard#38]
First of all, thanks for this wonderful software.  It would be great if the tt-rss plugin allowed users to see and use the 'Special' folder with starred items, all articles, fresh articles etc.  Also, the ability to use the filters/labels that already exist within tt-rss would be wonderful.   Unlike #31, this would present the server's filters.  Not create new filters in rssguard.  Thanks for any considerations.

**Comment by martinrotter** [comment]
Right now I do not have any option to test any TT-RSS functionality because I do not have any web hosting service bought right now. Thus, if anyone wants some TT-RSS enhancements, I would be glad to be provided with some testing TT-RSS instance. Otherwise I will test in virtualbox.

**Comment by martinrotter** [comment]
I setup TT-RSS in VirtualBox and check this out.

**Comment by martinrotter** [comment]
So you want labels but just in read-only mode? So that you can see messages from particular label, but not change labels at all?

I am thinking about supporting labels in general in RSS Guard....

**Comment by cwmke** [comment]
Correct. I already have filters setup on the web client that automatically send articles to labels. So for tt-rss users, the labels support would be redundant. ownCloud News doesn't have labels so I understand why rssguard support for creating your own labels is a great thing as well.

tt-rss allows for fairly complex filtering which I like but if you want to just implement client side, that works too. :smile:

**Comment by martinrotter** [comment]
Yes, I am thinking about labels very serously as it is partially precondition feature for #31.

**Comment by martinrotter** [comment]
I am not sure what TT-RSS "filters" are, but they are not supported by TT-RSS API, only "labels" are.

**Comment by cwmke** [comment]
Sorry for the confusion. I didn't mean to imply the filters functionality should be implemented in rssguard. The tt-rss filters are just the rules that fill the labels with articles. The labels are the desired function for rssguard. 😃

**Comment by martinrotter** [comment]
"Important messages" (starred) will be added as part of https://github.com/martinrotter/rssguard/issues/240

**Comment by martinrotter** [comment]
"Important messages" are now available in RSS Guard. Also, labels are implemented as part of #102. I will delete this, pls head into #102 to track progress.
