### ISSUE TITLE
[FR]: Search in feeds

### ISSUE THREAD

**Issue by CsatiZoltan** [martinrotter/rssguard#380]
#### Brief description of the feature request.

For dozens or hundreds of feeds, it becomes difficult to find a feed. I think, it would be useful to be able to search not only messages (top right corner), but also feeds (in the left pane). The search could be activated by any of the following methods:
- search box (as for message search)
- <kbd>Ctrl</kbd> + <kbd>f</kbd>
- when the user starts typing, and the pane is active (e.g. a feed is selected)

**Comment by martinrotter** [comment]
Hello @CsatiZoltan.

Option 3 is already natively supported by both feed list and message list, but is kind of "blocked" by single-key default keyboard shortcuts. So you must de-assign all single-stroke keyboard shortcuts first:
![image](https://user-images.githubusercontent.com/1255302/111203424-481f6280-85c5-11eb-85c4-4db7f00eace6.png)

Then simply give focus to feeds list and start typing and your selection should be automatically adjusted to fit your invisible search string.

Is that solution enough? If not let me know and I will implement option 1 (search box) in the same manner as for message list.

**Comment by CsatiZoltan** [comment]
@martinrotter 
I checked it. If it's not a lot of work, I would suggest that you implement option 1. Reasons (with this order of importance -- in my opinion):
1. Only filters by the first letter. E.g. if you remember only a phrase somewhere in the name of the feed, you won't find the that feed with this method.
2. That would not require redefining the keys (not a big issue for me because I use the mouse, but long-time keyboard users would not like this solution).
3. The current search method is invisible (typo not detected).
4. The UI would be more intuitive: messages and feeds would be filtered in the same way.

**Comment by martinrotter** [comment]
OK. I added the ticket to 4.0.0 milestone. It will be huge release to come in maybe like two months. Many changes and enhancements.

**Comment by martinrotter** [comment]
@CsatiZoltan Additional question: So far message filter textbox is only available for message toolbar. Do you want the message filter textbox to be available in feed toolbar?

**Comment by CsatiZoltan** [comment]
@martinrotter I thought of having one message filter textbox for filtering the messages (already exists in RSS Guard) and one for filtering the feed names. This latter filter textbox would be placed on the feed toolbar, like this
![filter](https://user-images.githubusercontent.com/12742890/112062377-28a5ae00-8b60-11eb-815f-2ed5a57bff74.png)
What do you think?

**Comment by martinrotter** [comment]
@CsatiZoltan Yes, that confirms my intentions. OK.

**Comment by martinrotter** [comment]
OK, I fixed. Can you please test with latest development build?

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/114522136-594ea400-9c43-11eb-8282-23936c4ea222.png)

**Comment by CsatiZoltan** [comment]
@martinrotter I cannot try it. After downloading the release with hash that begins with `dc988bf4` for Linux Appimage, I saw the new search box for the feeds. However, all my feeds were lost, getting an empty database. I realized that the new path is not `~/.config/RSS\ Guard`, but `~/.config/RSS\ Guard\ 4`. So I copied the *adblock*, *config* and *database* directories to the new path. Now I got back my feeds, but I cannot update them and the new search bar disappeared as well. To see what is going on, I launched RSS Guard from the terminal and issued an update on my feeds. Here is the log:
[log.txt](https://github.com/martinrotter/rssguard/files/6303268/log.txt)

**Comment by martinrotter** [comment]
Development builds now contain new generation of RSS Guard, version 4 which is NOT backwards compatible with previous RSS Guard versions.

Therefore you must begin with empty user data folder. Please test with empty data folder and let me know. :)

Development builds are meant for testing, I hope you have a backup of your data.

**Comment by CsatiZoltan** [comment]
I started with an empty database and filled it up with some predefined feeds (as shown in your screenshot). I confirm that the search among feeds works in the same way as the search in the individual feed entries. On the other hand, I have some ideas about how the search could be improved. Since the two search boxes share the same behaviour, I think it would make sense to open a new issue, which would not concern the GUI (search box) itself. Or should I start a [discussion](https://github.com/martinrotter/rssguard/discussions/categories/ideas) instead?
Thank you for implementing the current feature, it will make my life much easier (and hopefully that of others)!

---

> Development builds now contain new generation of RSS Guard, version 4 which is NOT backwards compatible with previous RSS Guard versions.

Will you create a migration tool once version 4 is released? For me, migration to version 4 would probably be a no-no if I had to type all my feeds manually (I have so many of them...)

> I hope you have a backup of your data.

Yes, no problem. I *copied* directories from `/RSS\ Guard` to `/RSS\ Guard\ 4`, and it was a relief that everything works on version 3.9.2 as before. :)

**Comment by martinrotter** [comment]
> Will you create a migration tool once version 4 is released? For me, migration to version 4 would probably be a no-no if I had to type all my feeds manually (I have so many of them...)

I am really not sure at this point as some things will be very hard to migrate. That said here are some advanced facts:
* configuration file `config.ini` from RSS Guard 3.x will 99% work for you in RSS Guard 4.x too, same with `key.private` file,
* database file `database.db` will NOT.

So basically, your configuration could be migrated just by copying the file. As for feeds -> you can export to OPML on one side and import on the other. As for messages, no go here, sadly.

One more thing, there will be some upcoming bug-fix releases 3.9.3 and probably 3.9.4 too.

Feel free to open any number of discussions for everything you have to say.
