### ISSUE TITLE
Regular vs. nowebengine?

### ISSUE THREAD

**Issue by fredddd1** [martinrotter/rssguard#381]
Would it be possible to add a description of what the differences are on the homepage of the github repository?

I looked up "nowebengine" on a search engine and the only results I get are RSS Guard.

I have no idea which version to pick.

**Comment by martinrotter** [comment]
Hello, just read documentation linked from readme.

https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#web-based-and-lite-app-variants
