### ISSUE TITLE
[FR]: Problem with synchronizing unread mesages on Reedah  

### ISSUE THREAD

**Issue by cocowash** [martinrotter/rssguard#382]
**#### Brief description of the issue.**
Rss Guard syncs already read messages but can't reach to unread messages. 

**#### How to reproduce the bug?**
1.  add a Google Reader API account (Reedah) and select download all messages. Have 400 or more feeds on the account. Set only download newest X messages per feed on 50. 

**#### What was the expected result?**
The Program syncs fully with Reedah in seconds.  

**#### What actually happened?**
It took me 2 days to have an unread message

**#### Other information**
* OS: win 10
* RSS Guard version: 3.9.0

I contacted Reedah support and they kindly wrote me back: 

> I took a quick look at what RSS Guard is doing and made these observations.
> 
> 1. Fetching data is a bit slow compared to our web interface.  We can
> probably improve this some on our end.
> 
> 2. RSS Guard is logging in and getting a security "token" for every feed
> it checks.  With Reedah this is unnecessary and may add around 4 seconds
> *per feed*.  It is valid and will work, just slower.
> 
> Our servers are running below capacity at the moment (like 10% utilized)
> so there is not an issue with things being overloaded.
> 
> Obviously the first time RSS Guard (or any other software) syncs will be
> the slowest because it is loading X days worth of articles.
> 
> We are happy to work on making things faster for RSS Guard users in the
> future.  But for immediate actions, most things are outside your
> control. The best advice I can give you right now is (a) confirm whether
> sync works for you at all or is it just slow - you are welcome to create
> a temporary account in Reedah with fewer feeds to test it; (b) try to
> mark all articles as read in the web browser before sync; (c) limit RSS
> Guard to the most recent X articles for the first sync, e.g. X=25; and
> (d) be patient - simply the token requesting for 400 feeds could take
> 400x4 = 1600 seconds so I would not be surprised if a complete sync is 1
> hr+ at the moment.

> According to the Google Reader API (which Reedah copies), the
> ClientLogin token expires after two weeks.  What RSS Guard *should* be
> doing is logging in when the app starts and getting the token, then
> storing it and re-using the same token for each request until it expires
> (or at least for a few hours).
> 
> Instead it appears to login and get a token before *every* request (e.g.
> sync of each individual feed).  This creates a new "session" for the
> user in Reedah.  So instead of having a few (1-2) sessions per user, we
> quickly end up with 1,000 per user.
> 
> It is not a particularly big problem for us, but the unnecessary steps
> do slow things down for the user.

**Comment by martinrotter** [comment]
Wow, this seems like some major clusterfuck from my side. Will investigate.

**Comment by martinrotter** [comment]
5a7c06b7

OK, I fixed a couple of Reedah-related bugs. Will continue fixing the rest of it tomorrow.

**Comment by martinrotter** [comment]
@cocowash OK, I fixed the part with repeated unnecessary obtaining of token which is now obtained correctly only once.

Updates should be now much much much faster, please check with latest development build, please.

https://github.com/martinrotter/rssguard/releases/tag/devbuild

**Comment by martinrotter** [comment]
I tested with devbuild, added 100 feeds and initial sync of messages took 25 seconds.

**Comment by cocowash** [comment]
With the newest Development build all syncs a lot faster. Nonetheless, for me now its evident that none of the YouTube feeds are working. (no read or unread messages) [As an example this is the regular structure I use for YouTube feeds on Reedah https://www.youtube.com/feeds/videos.xml?channel_id=UCJHA_jMfCvEnv-3kRjTCQXw] any of the YouTube feed is visible in Reedah but empty on RSS Guard. Could you make a test with a YouTube feed in your account pls?

**Comment by martinrotter** [comment]
Thank you, I will test them. :)

**Comment by martinrotter** [comment]
Fixed with fd7e43ad.

The error was that "id" of the feed was not properly encoded in request URL so the query failed for all feed "id"s which contained "?". Should now work.
