### ISSUE TITLE
[EN]: feedbin account

### ISSUE THREAD

**Issue by ahmetcadirci25** [martinrotter/rssguard#383]
How can I add a feedbin account?

**Comment by martinrotter** [comment]
@ahmetcadirci25, hello.

You can see list of supported online services [here](https://github.com/martinrotter/rssguard/blob/master/resources/docs/Feed-formats.md). Feedbin is not supported, yet, but its support could be added via service plugin. The C++ API is relatively simple and anyone who can program in C++ can contribute it and I would be very happy to accept it.

Therefore you have some options:
1. Implement feedbin RSS Guard plugin yourself and contribute it to RSS Guard.
2. Support me via donations and I will implement the plugin if you really want it. :)

:) I will close the ticket for now, feel free to comment and I will re-open if the situation will demand it.

Have a nice day.
