### ISSUE TITLE
[FR]: Setting to show nothing instead of the chosen 'Message count format in feed list' setting when it is zero

### ISSUE THREAD

**Issue by RandomNerd1** [martinrotter/rssguard#385]
In other words, as an example, if you have "Message count format in feed list" set to "[%unread]" and you have a bunch of feeds with no unread items, an option that would display nothing instead of all those "[0]"s would be nice, especially because when a feed DOES have something unread, it's much easier to distinguish the [1] etc. from the empty space, than from a pillar of [0]s.

Know what I mean? :)

**Comment by martinrotter** [comment]
Do you want this simply for easthetic/look purposes? Also, note that the "counts" are actually separate column which "cannot" be hidden or removed so even if I implemented this and "0" would be hidden, then the previous text (feed's title) will still be cut if too long.

**Comment by martinrotter** [comment]
Alternative here could be to simply remove "counts" column and append the "counts" to the title (if non zero), but that would remove ability to sort feeds according to counts.

**Comment by RandomNerd1** [comment]
No, I'd prefer the first 'option', where the counts column is there, it just displays nothing instead of "[0]" based on your decision (I would have this be an option instead of default behavior, not everyone wants this).

Although now that you mention it, I'm looking and I can't figure out how to sort feeds by counts, I thought it was just always alphabetical. A sort that would go with most to least unread, and alphabetical among feeds with the same number of unread, would be great. Can RSS Guard already do this? If not, maybe time for a new feature request, lol

**Comment by martinrotter** [comment]
@RandomNerd1 You can just click the headers of the list to get it sorted by either column + RSS Guard remembers the column persistently.

<a href="https://i.imgur.com/2Td1yQ9.gif"><img src="https://i.imgur.com/2Td1yQ9m.jpg"></a>

**Comment by RandomNerd1** [comment]
I see, thank you. :)

**Comment by martinrotter** [comment]
OK, I fixed this, feel free to test via development build and let me know if anything does not work.

![image](https://user-images.githubusercontent.com/1255302/114989589-dbcfa180-9e97-11eb-92bc-75273cc7dbd3.png)
