### ISSUE TITLE
[FR]: Bypass internal browser completely for web pages

### ISSUE THREAD

**Issue by RandomNerd1** [martinrotter/rssguard#386]
I don't want RSS Guard to open URLs internally at all. I've noticed I can double-click on the message in the list of messages to open it in my external browser, but I'd like to have a setting that tells RSS Guard to default to using the external browser whenever the application is to open a web page (clicking the "URL" button, etc.).

**Comment by martinrotter** [comment]
#588 is now implemented, allow to do this on a per-feed basis, not globally tho

**Comment by martinrotter** [comment]
fixed, switchable in settings -> external web browser
