### ISSUE TITLE
[FR]: Setting to auto-sort feed list alphabetically etc.

### ISSUE THREAD

**Issue by RandomNerd1** [martinrotter/rssguard#387]
When I imported a list of feeds, they were sorted alphabetically, which is fine. But I noticed that if I rename a feed manually, it does not move to its new correct alphabetic position (although it does if you 'fetch metadata' and that changes the title of the feed).

I'd like there to be a setting that will automatically keep the feed list sorted alphabetically, even if you manually change the title of a feed. It should be optional, because I'm sure some people want to manually sort their feeds.

**Comment by martinrotter** [comment]
> I'm sure some people want to manually sort their feeds

#302

**Comment by martinrotter** [comment]
Checked this. In fact, you discovered a bug.

Feed list should be always sorted by active column: either title, or counts. There was a bug that if you renamed the feed or category, feed list forgot to re-sort itself. I fixed it, thanks.

There is no settings, but after I fixed it, it should now work the way you expect.
