### ISSUE TITLE
[FR]: Ability to fetch only certain types of metadata

### ISSUE THREAD

**Issue by RandomNerd1** [martinrotter/rssguard#388]
When importing a list of feeds from elsewhere, I wanted to keep the custom titles I had given many of them. However, this left me unable to update the feed icons for the entire list without also having my title overwritten with the feed's default titles.

I understand I can go into a feed and download its icon separately, but I have over 100 feeds, so a way to, for example, download all the icons and nothing else, would be much more convenient, and friendly to users coming from other RSS readers.

**Comment by martinrotter** [comment]
Added option to NOT fetch titles when fetching metadata during OPML import.
