### ISSUE TITLE
Show MRSS images directly next to or inline the article; Help or feature request?

### ISSUE THREAD

**Issue by groentebroer** [martinrotter/rssguard#39]
#### Brief description of the issue.

I can't seem to find out how to show an "attached" image via MRSS to directly be shown next to the item. Is this possible? Or would that be a new feature request?

#### How to reproduce the bug?
Not applicable

#### What is the expected result?

Image or images shown next to the article.

#### What actually happened?

Per item downloading the attachment works.

#### Other information (logs, see Wiki)
None.

**Comment by martinrotter** [comment]
You mean, if RSS/ATOM message contains (let's say) PNG or JPG image, show it directly somewhere in the message preview? For example under the title?

**Comment by groentebroer** [comment]
Yes, if the message contains an attachment which is of type "image" Indeed in the preview. Under the title could be nice.

It would be to support these tags in the preview:

`<enclosure type="image/*" />`
or 
`<media:content type="image/*" >`

Some (non-official) reference: https://help.campaignmonitor.com/topic.aspx?t=277

**Comment by martinrotter** [comment]
Yes, now it makes sense, thank you.

This issue itself is really easy to implement. I will have to think a bit about skins. Now, each skins specifies its own markup/stylesheet for displaying individual messages, I will have to tweak the skinning methods a bit to allow this.

**Comment by martinrotter** [comment]
![rssg](https://cloud.githubusercontent.com/assets/1255302/17169296/1555a32e-53e7-11e6-85ba-9ee15864bea4.png)

See the picture and let me know if this is good enought. I highlighted the interesting area with red rectangle. If message contained more images, they would be shown next to each other. Shown image is thumbnail, user can click it and see full-size original image.

Is this enough?

**Comment by groentebroer** [comment]
Looks great already!
Thanks for the fast fix. I will give it a try when 3.3.3 is available for download! Any ETA?

**Comment by martinrotter** [comment]
Okay. Last question: Would it be better that images are placed below the actual message? Or current look is enough?

**Comment by groentebroer** [comment]
In my personal opinion it is best this way. An image says more then 1000 words ;-). I think the image would/should trigger you to read the item. Scanning items will be easier based on the image.
So this preferrable then below, if you ask me.

**Comment by martinrotter** [comment]
Okay, then this is complete.
