### ISSUE TITLE
[FR]: Have RSS Guard able to 'process' a feed being sent to it from a browser

### ISSUE THREAD

**Issue by RandomNerd1** [martinrotter/rssguard#390]
#### Brief description of the feature request.

I use Firefox 86.0.1 (latest version to date, I believe), and while I can tell the browser to send rss data to RSS Guard, the application doesn't seem to do anything with it (its window becomes active, but nothing else happens), whereas my old feed reader would take the info and automatically open the prompt for adding a new feed.

**Comment by martinrotter** [comment]
>while I can tell the browser to send rss data to RSS Guard

How do you do this?

**Comment by RandomNerd1** [comment]
> 
> 
> > while I can tell the browser to send rss data to RSS Guard
> 
> How do you do this?

With Firefox, in its options, you can go under "Applications" and change "application/rss+xml" from "Always ask" (the default) and instead point it to RSS Guard's .exe. That's what I used to do for quiteRSS, my old feed reader.

**Comment by martinrotter** [comment]
Thanks, will test and implement.

**Comment by martinrotter** [comment]
> 
> 
> > > while I can tell the browser to send rss data to RSS Guard
> > 
> > 
> > How do you do this?
> 
> With Firefox, in its options, you can go under "Applications" and change "application/rss+xml" from "Always ask" (the default) and instead point it to RSS Guard's .exe. That's what I used to do for quiteRSS, my old feed reader.

I am not sure how that could/should work because when you do that, what browser (Firefox) does is that it downloads the file to %TEMP% and then feeds local path to the rssguard.exe. RSS Guard would need to get the original URL, not path to downloaded file.

**Comment by RandomNerd1** [comment]
No, it's not 100% reliable. QuiteRSS did nothing with the link you provided. I add feeds manually more often than not (because there's no direct link to them (e.g. YouTube)), so I don't have a good example on hand that quiteRSS did for me straight away.

Is there no way for RSS Guard to get the URL info from Firefox's behavior? If not, it's not a big deal.

**Comment by martinrotter** [comment]
@RandomNerd1 Thing is that every browser downloads the file first and then feeds the local file path to the application. So the only thing RSS Guard obtains is the local path to downloaded feed file.

Problem is that there are several feed formats and the only formats which usually embed the actual feed URL into the feed file are ATOM and JsonFeed, so if user "opens" those, then they can be processed with RSS Guard.

RSS 1.0/2.0 feeds do not have feed URLs embedded in them, so they cannot be processed. If ATOM/JSON feeds would be enough for this feature, then I would implement it. QuiteRSS does not have the feature at all (I checked their source code).

**Comment by martinrotter** [comment]
@RandomNerd1 OK, if you post here at least one or two links to feeds which worked for you in QuiteRSS to open them directly from firefox or other browser, I will implement the feature.

**Comment by martinrotter** [comment]
FOR ME: https://en.wikipedia.org/wiki/Feed_URI_scheme

**Comment by martinrotter** [comment]
OK, I investigated deeply. Quiterss does not seem to offer such a function, or at least I did not find it when investigating their sources.

I added support for feed URLs being passed as an argument to RSS Guard. Read this "CLI" [section](https://github.com/martinrotter/rssguard/blob/version-4/resources/docs/Documentation.md#cli), especially its lower part.

Now with this feature, RSS Guard is easily usable with web browser and feeds can be added without the need of manual copying of feed URLs.

**Comment by martinrotter** [comment]
Will do some related fixes and post screenshots.

**Comment by martinrotter** [comment]
OK, latest devbuild supports the feature nicely. Tested with this [extension](https://addons.mozilla.org/en-US/firefox/addon/open-with/).

![TmPtEtQbPr](https://user-images.githubusercontent.com/1255302/112958698-07862400-9143-11eb-9312-091077a432ec.gif)
