### ISSUE TITLE
[FR]: Support cookies

### ISSUE THREAD

**Issue by RandomNerd1** [martinrotter/rssguard#391]
#### Brief description of the issue.

No matter what I do, I can't get RSS Guard to pull feed data from the RSS feed URL created by a private torrent tracker site.

I don't think I can provide you the URL used and have it work for you, but I was able to save the .xml file I see when I plugged it into Firefox just now. The .xml is zipped and attached, hopefully that's useful to you.

[rss.php.zip](https://github.com/martinrotter/rssguard/files/6186100/rss.php.zip)

I noticed "<rss version="0.91">" near the top, so I tried changing the feed information "Type" to "RSS 0.91/0.92/0.93", but that didn't help, either.

#### How to reproduce the bug?

1. Add said feed to RSS Guard
2. Try to update feed
3. See nothing happen and get sad (lol)

#### What was the expected result?

Seeing the feed info in RSS Guard

#### What actually happened?

Seeing nothing in RSS Guard

#### Other information

* OS: Win10 x64
* Desktop Environment: ?
* RSS Guard version: 3.9.0

**Comment by martinrotter** [comment]
Works here

![image](https://user-images.githubusercontent.com/1255302/112101069-5b729500-8ba6-11eb-8ef8-bd2e024ab8bc.png)

Is feed hidden behind any authentication? How is it "private", do you need to somehow login to see the feed? Also, it would probably make sense to provide debug log from rssguard session when you produced the issue.

https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#generating-debug-log-file

**Comment by RandomNerd1** [comment]
No HTTP authentication. Here's a URL, see if you can add it that way. I am able to add the feed, but updating it yields no 'entries' in the message list:

https://xtremewrestlingtorrents.net/rss.php?feed=dl&cat=75,50,56,51,53:COOKIE:uid=979653;pass=31cf83cbc3619b35b56e53de5dff7685

**Comment by martinrotter** [comment]
Returns "Not logged in!".

How do you authenticate to website? You must login. Your web browser subsequently stores auth cookies which the feed checks I believe. Loading the feed without the actual cookies will not work and that is what I see.

RSS Guard does not support cookies. Do you use "nowebengine" version of RSS Guard?

**Comment by RandomNerd1** [comment]
I log in to the site in Firefox, but after generating the RSS feed URL on the site, I've been able to plug it into quiteRSS, for example, and have it work just fine. I don't log into the site within quiteRSS at any point.

**Comment by martinrotter** [comment]
I see, at that case provide debug log.

https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#generating-debug-log-file

**Comment by martinrotter** [comment]
Just checked QuiteRSS and they do support cookies embedded inside URLs.

https://github.com/QuiteRSS/quiterss/blob/550a8b81094568ee5333685f8df4dbaa186ad09a/src/addfeedwizard.cpp#L391

RSS Guard does not. Therefore I change title of this ticket.

**Comment by martinrotter** [comment]
https://github.com/martinrotter/rssguard/issues/391#issuecomment-804644958

**Comment by martinrotter** [comment]
Starting to work on this.

**Comment by martinrotter** [comment]
OK, I added initial non-persistent support for cookies. Can you test latest dev. build?

Now it works here.

![image](https://user-images.githubusercontent.com/1255302/112121558-ab118a80-8bbf-11eb-8f3a-8382bcc6217f.png)

**Comment by martinrotter** [comment]
OK, I commited even persistent saving of cookies.

Now, it should completely work for you. You can even remove ":COOKIE" part of the URL after feed is guessed with "Fetch it now" feature.

**Comment by RandomNerd1** [comment]
> 
> 
> OK, I added initial non-persistent support for cookies. Can you test latest dev. build?
> 
> Now it works here.
> 
> ![image](https://user-images.githubusercontent.com/1255302/112121558-ab118a80-8bbf-11eb-8f3a-8382bcc6217f.png)

I see no builds on the Development Builds page, as of now.

**Comment by martinrotter** [comment]
they are there now

**Comment by RandomNerd1** [comment]
Seems to be working just fine, thanks! :)

By the way, I don't know if I'm going crazy or what, but I can't find that issue about the YouTube feeds, and I wanted to add that I figured out what changed that made it start working again, so I'll just leave the info here for your reference.

Unless I fetch metadata at least once for a YouTube feed, it will not start pulling data, for whatever reason. I was reluctant to do that except when I was testing and it was the only feed (because fetching metadata will alter my given title for the feed (already submitted a feature request to be able to fetch metadata without changing the title)), that's why I didn't notice at first.

**Comment by martinrotter** [comment]
@RandomNerd1 Can you post some youtube feeds URLs just for me to test again?

**Comment by RandomNerd1** [comment]
https://www.youtube.com/feeds/videos.xml?user=BlameTheController
https://www.youtube.com/feeds/videos.xml?channel_id=UCjcPJbFDwVZZELGG38q2cLQ
