### ISSUE TITLE
[FR]: Ability to turn an individual feed 'off' with visual indication

### ISSUE THREAD

**Issue by RandomNerd1** [martinrotter/rssguard#393]
#### Brief description of the feature request.

Just the ability to right-click on a feed or in its 'edit' window, and get an option to disable/deactivate a feed, keeping it in your list, but no longer getting checked for updates until reactivated. I'd want to be able to see at a glance which feeds are set this way, by maybe striking through the title, showing it grayed out, something like that.

**Comment by martinrotter** [comment]
@RandomNerd1 If you hit "update all feeds" you need those "off" feeds to be skipped?

**Comment by RandomNerd1** [comment]
I think that would be the expected behavior, yes.

**Comment by sakkamade** [comment]
As a workaround can be used a simple message filter (`Alt+i` and `f`):
```js
function filterMessage() {
  return MessageObject.Ignore;
}
```

This will not let any new article in even upon fetching.

**Comment by martinrotter** [comment]
@sakkamade While this if course works it will not avoid the actual downloading of the feed (XML) file, but nice touch anyway.

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/149906116-80afab2b-2ebc-4bc0-9a9e-d4ccfa3436df.png)
![image](https://user-images.githubusercontent.com/1255302/149906146-2a92794e-6b69-427e-8cc1-7ad1fe827091.png)
