### ISSUE TITLE
[BUG]: rssguard 3.9.1 announces itself as 3.9.0

### ISSUE THREAD

**Issue by norbusan** [martinrotter/rssguard#394]
`pri/vars.pri` still contain 3.9.0

**Comment by martinrotter** [comment]
well, shit :D

will fix and re-update the git tag

**Comment by martinrotter** [comment]
fixed, sorry man, i have totally bad day today

**Comment by norbusan** [comment]
No prob, don't worry!!! Thanks for the fix.

**Comment by norbusan** [comment]
Do you upgrade the tag to a release, too? I don't care, just ask...

**Comment by martinrotter** [comment]
Yes, I did just now, assets should compile soon.
