### ISSUE TITLE
[BUG]: 3.9.1 Window is not maximized after double clicking an article

### ISSUE THREAD

**Issue by peperjohnny** [martinrotter/rssguard#395]
#### Brief description of the issue.
With version 3.9,1 the following bug happens. I get my feeds via Nextcloud if this makes any difference. A double clicked article is opened in the external browser but RSS Guard isn't maximized anymore

#### How to reproduce the bug?

1. Install version 3.9.1.
2. Maximize RSS Guard window.
3. Open an article in external browser.

#### What was the expected result?
RSS Guard should keep the same geometry as before.

#### What actually happened?
RSS Guard isn't maximized anymore.

#### Other information

* OS: Windows 10H2 or Arch Linux
* Desktop Environment: Windows or KDE Plasma 5.21.4 Qt 5.15.2
* RSS Guard version: 3.9.1 with webengine

**Comment by martinrotter** [comment]
This probably happens only if feature "Bring application window to front once message is opened in ext. web browser" is ACTIVATED, right?

**Comment by peperjohnny** [comment]
You're right, once I deactivated it, it doesn't happen anymore.

**Comment by martinrotter** [comment]
OK, it is fixed with latest dev build.
