### ISSUE TITLE
How do I download unread only when syncing with a Bazqux account?

### ISSUE THREAD

**Issue by umbellipher** [martinrotter/rssguard#396]
Here's my issue:

1) I connected rssguard with my Bazqux account. I downloaded all feeds and messages.
2) I mark messages as read. In the end, all are so marked.
3) I initiate fresh download, or auto-download starts.
4)  BUT all feeds download afresh, as if I hadn't marked them read.

Questions:
A) Does my marking of messages as 'read' sync back to the Bazqux server?
B) How do I set rssguard up, please, so that I download only new, unread, messages?

Thanks!

**Comment by martinrotter** [comment]
Hello @umbellipher.

Yes, RSS Guard supports Bazqux via Google Reader API plugin. Plugin fully supports rssguard's synchronization mechanism. To your questions:

A. Yes, definitely (unless there is a bug)! RSS Guard synchronizes message's read/unread state, important/normal state, it also synchronizes tags/labels and their de/assignment to individual messages. I will test Bazqux and report back, it should all just work. RSS Guard synchronizes all the data ONCE A MINUTE automatically.
B. Google Reader API plugin (Bazqux, ...) does not have "download unread messages only" feature in RSS Guard. It downloads all messages, but you can filter out unwanted read message with message filters. That said, brand new version of RSS Guard 4.0.0 which is under development ADDS ability to fetch only unread messages for this plugin! I just added this feature some days ago.

EDIT: I just found the bug you describe!

>BUT all feeds download afresh, as if I hadn't marked them read

Fix is [here](https://github.com/martinrotter/rssguard/commit/fd65580071d655d12279e2429ccbd9b9b5420a47). Also, some related features and bug-fixes are already in 4.x branch of RSS Guard. Please, wait 15 minutes and then test with [dev. build](https://github.com/martinrotter/rssguard/releases/tag/devbuild).
