### ISSUE TITLE
Duplicate URLs are reported with invalid error

### ISSUE THREAD

**Issue by ZyX-I** [martinrotter/rssguard#40]
#### How to reproduce the bug?

1. Use “New feed” context menu.
2. Fill feed title and description.
3. Type `file:///home/zyx/.zlrchecker/rss.xml` in the URL field.
4. Click “OK”.
5. Repeat.

#### What is the expected result?

RSS feed is added. Alternative: it is reported that there is a feed with the given URL.

#### What actually happened?

Fails with error (popup) “Cannot edit feed / Feed was not edited due to error.”. The only error actually seen is exclamation mark with  “The url does not meet standard pattern. Does your url start with "http://" or "https://" prefix.”

#### Other information (logs, see Wiki)

Version 2.4.0, installed system-wide from main portage tree (Gentoo).

**Comment by ZyX-I** [comment]
(As you see I actually was thinking that file:/// URLs no longer work. Report body was only changed because I failed to find rssguard version which I installed before (i.e. *different* version) and which allowed me to add feed in question: emerge logs have shown me that rssguard was installed only once and never updated.)

**Comment by ZyX-I** [comment]
Version appears to be too outdated.

**Comment by martinrotter** [comment]
Wait. So if you try latest version, it works?

**Comment by ZyX-I** [comment]
Dunno. Main portage tree does not have the required Qt version, so I can’t install latest version. In 3.1.0 (used ebuild can be found in https://bugs.gentoo.org/show_bug.cgi?id=571028, did not use 3.2.4 because it probably also requires updating Qt)  I can, at least, modify an existing RSS feed to use the same URL as another existing RSS feed (modifying to make URLs match did not work in 2.4.0 as well).

**Comment by martinrotter** [comment]
OK, so if you have any issue with 3.1.0, report it, please, as a new bug, I will check it. It still can there.
