### ISSUE TITLE
[BUG]: 3.9.0 does not find 3.9.2 update (Error: 'Unknown error'.) - due to missing VC redist 2010 for openssl

### ISSUE THREAD

**Issue by fredddd1** [martinrotter/rssguard#400]
#### Brief description of the issue.

Updater can not find updates due to an unknown error.

#### How to reproduce the bug?

1. Try to update via Help -> Check for updates

#### What was the expected result?

For me to be able to update to 3.9.2 from 3.9.0 via the software.

#### What actually happened?

Updater reports:
Error: 'Unknown error'

#### Other information

* OS: Windows Pro 20H2 64-bit
* Desktop Environment: Yes
* RSS Guard version: 3.9.0

![rss-guard-updater-unknown-error](https://user-images.githubusercontent.com/80743272/115108985-a39d9100-9f73-11eb-8e0e-fbf3d1d02e07.png)

**Comment by martinrotter** [comment]
@fredddd1 Just checked with clean Windows 10 install and 3.9.0.

![image](https://user-images.githubusercontent.com/1255302/115113652-a0160400-9f8b-11eb-83c2-7431e09cd04f.png)

Everything works. It seems that there is some other issue with OpenSSL since you report "unknown error" also in the other ticket.

**Comment by fredddd1** [comment]
@martinrotter

Just setup a clean Windows Pro 20H2 64-bit environment and it outputs the same result.

![Untitled](https://user-images.githubusercontent.com/80743272/115121641-1b8bab80-9fb4-11eb-9c51-df0ce56a1a79.png)

**Comment by martinrotter** [comment]
Will do exactly this on Monday and test myself, thanks. Perhaps it is in 20H2, we will see. Thanks.

**Comment by martinrotter** [comment]
I managed to reproduce the problem. VC redist 2010 libraries are now needed by openssl libraries and they are missing. Let me fix.

**Comment by martinrotter** [comment]
@fredddd1 OK, it is fixed and I tested it and now it works. Can you please download development build (it contains latest fixes)

https://github.com/martinrotter/rssguard/releases/tag/devbuild

and test all you issues you are having? Report back with your conclusions, please.

**Comment by fredddd1** [comment]
Seems all good now. Thanks for the effort!

![image](https://user-images.githubusercontent.com/80743272/115251250-a7274880-a12a-11eb-815c-46f5afba827a.png)

**Comment by martinrotter** [comment]
@fredddd1 Can you also comment on your other issues if those are too fixed?

**Comment by fredddd1** [comment]
@martinrotter

Account works fine now. But there still is no visual indication of anything happening when you do Synchronise folders & other items.

No progress bar, no success, no failure indication.

**Comment by martinrotter** [comment]
Provide full debug log, otherwise I cannot do anything.

**Comment by fredddd1** [comment]
> Provide full debug log, otherwise I cannot do anything.

Everything works and messages are pulled in.

But this issue still exists:
https://github.com/martinrotter/rssguard/issues/402

When you click on this, visually, nothing shows you that something is happening.

If I pull in new messages, a progress bar will appear at the bottom right showing the message progress. This does not occur for "Synchronise folders & other items".

**Comment by fredddd1** [comment]
@martinrotter When will this be pushed to a stable release? The software is not really useable on Windows at this point.

**Comment by martinrotter** [comment]
> 
> 
> @martinrotter When will this be pushed to a stable release? The software is not really useable on Windows at this point.

@fredddd1 No ETA at this point. I don't know, in a few weeks maybe.

You can use development build which contains latest code in the meantime.
