### ISSUE TITLE
[FR]: Option to disable yellow pop-up box?

### ISSUE THREAD

**Issue by umbellipher** [martinrotter/rssguard#404]
#### Brief description of the feature request.

When I rest the cursor on a feed, having selected it, a yellow info box

![Screenshot - 25_04_2021 , 00_20_00](https://user-images.githubusercontent.com/59395777/115974459-c40db280-a554-11eb-92a9-04922f091661.png)

 pops up. It stays there until I move the cursor away. I don't really need it, and I'm finding it gets in the way if I forget to move the cursor once I've selected the feed. Could there be an option to disable it, and/or for the box to vanish after a second or so?

By the way, dev version rssguard-3.9.2-c74e73bc is a joy! Linked to my Bazqux account, and set at the (default, when installed) 100 posts per feed, it syncs 450 or so feeds rapidly. That addresses my #398 effectively, and @martinrotter has been most responsive. So: thanks!

**Comment by martinrotter** [comment]
@umbellipher OK, this seems like a seasonable FR.

As for #398 OK, good news. I will probably implement #339 some opt-in better syncing algorithm anyway. We will see.

**Comment by umbellipher** [comment]
Tooltips for message list: yes, I reckon it should switch them off too.

Thanks!

**Comment by martinrotter** [comment]
Fixed, switchable in "Settings" dialog in section "Feeds/messages".
