### ISSUE TITLE
[BUG]: "Mark selected items as read" is slow when feeds syncing

### ISSUE THREAD

**Issue by umbellipher** [martinrotter/rssguard#405]
#### Brief description of the issue.

When feeds are syncing, 'mark selected items as read' is slow to work, sometimes needing several hotkey hits. Once sync has finished, the process is immediate.

#### Other information

* OS: Windows 10, 1909
* Desktop Environment: BazQux account sync process
* RSS Guard version: 40.0.0, dev version c74e73bc

**Comment by martinrotter** [comment]
@umbellipher Can you post a short GIF/video visualising the bug?

**Comment by umbellipher** [comment]
I'd have trouble blurring out personal info on a video or GIF - sorry. Let me try to explain it better. 1) rssguard is mid-sync. 2) Select category or feed title in left pane. 3) Press key to 'mark selected items as read'. 4) Wait to see if it happens, which it only sometimes does. Press key again. 5) Wait until sync is finished, when the intermittency issue goes away.

Btw, I am on W10 1909, and have 16Gb of RAM, so RAM is not an issue. Seems to me that rssguard is slow to catch up when it's mid-sync, and I was wondering whether that lag can be improved.

**Comment by martinrotter** [comment]
> 1) rssguard is mid-sync.
In mid-sync of messages (for example when you hit `Download messages...`)?

**Comment by umbellipher** [comment]
Thanks. I've worked out that it may be my use of [Keyscrambler](https://www.qfxsoftware.com/download.htm) which is causing the lag.

I'll ask the developer of that to add rssguard to his list of program exceptions, and close this issue.
