### ISSUE TITLE
[BUG]: When there's a long feed list of (unread) posts, list and messages pane do not match

### ISSUE THREAD

**Issue by umbellipher** [martinrotter/rssguard#406]
#### Brief description of the issue.

When (with 'unread only' selected) the LHS feed list exceeds the depth of the screen, the top of the list gets hidden under the top bar, but the RHS message list keeps the topmost post at the top.

Since a picture is better than 1000 words:

![Screenshot - 26_04_2021 , 14_29_01](https://user-images.githubusercontent.com/59395777/116083069-19041280-a694-11eb-9a76-7bc38d5c5e2f.png)

#### Other information

* OS: Windows 10 1909
* Desktop Environment: rssguard linked to a BazQux account
* RSS Guard version: latest dev version, 3.9.2-c74e73bc

**Comment by martinrotter** [comment]
@umbellipher Not clear what the bug is. So you have selected some "category" or "account" from feed list and shown messages obviously do not match? Can you post a GIF/video showing the bug?

You can record GIF for example with program called ShareX.

**Comment by umbellipher** [comment]
I'd have trouble blurring out personal info on a video or GIF - sorry. Let me try to explain.

1) Left pane list of unread feeds, longer than the screen estate. 2) Expected behaviour on selecting a category or feed in LH pane: that category or feed sits at the top of the list, just under the top bar. 3) Right hand pane: the posts in that category or feed should, equally, sit at the top of the RH pane. 4) Actual behaviour: category  or feed in LH pane hides under the task bar and is not visible; in RH pane, topmost feed is indeed at the top of the pane.

I could decrease font sizes, but would prefer not to have to.

I hope that helps?

**Comment by martinrotter** [comment]
@umbellipher 

Please, backup your `data` folder and start RSS Guard with clean data folder and try to make video for me. I am not sure if I understood the problem correctly. :)
