### ISSUE TITLE
[FR]: Prevent external browser stealing focus?

### ISSUE THREAD

**Issue by umbellipher** [martinrotter/rssguard#407]
I use a Chromium-fork browser, and there is no way within it to stop it stealing focus when I open a Rssguard feed in it. (The issue is well-discussed, there are no extensions to overcome it, and devs are not going to address this any time soon.)

I notice that [QuiteRSS](https://quiterss.org/en/) has an (experimental) option to prevent the default browser from stealing focus. It's my previous preferred RSS reader, and I can say that the option works well.

Might something similar be possible for Rssguard?

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/116285003-ffdf8c80-a78d-11eb-851c-bd5fd39afa5f.png)

**Comment by umbellipher** [comment]
Thanks. I have that set. I set each of my three Chromium-fork browsers in turn (Slimjet, Ungoogled Chromium, Brave) as default browser in the relevant setting, with the parameter "%1", and each of them still stubbornly stayed at the front, coming from minimized, when I opened a post as an external link.

**Comment by martinrotter** [comment]
Where exactly do you click on link? Somewhere in the contents of message?


Dne st 28. 4. 2021 0:18 uživatel umbellipher ***@***.***>
napsal:

**Comment by umbellipher** [comment]
No, I use a hotkey (the down arrow, in my case) with the post highlighted, to open in external browser. Chromium either opens (if closed) or comes to the front (if minimized). The post loads in the browser, and the browser remains to the front.

**Comment by martinrotter** [comment]
The above checkbox should just work. do you have it checked?

**Comment by martinrotter** [comment]
https://imgur.com/a/fIbItnV

**Comment by umbellipher** [comment]
Yes indeed, and thanks for the video clip. My Chromium browser still sits stubbornly at the front. Since I'm not willing to use Chrome, or Chromium, because both 'phone home' to G**gle, I think I'll put up with the issue, with my thanks, and close this now.
