### ISSUE TITLE
[FR]: Keyboard shortcuts to navigate up/down inside message

### ISSUE THREAD

**Issue by linuxissuper** [martinrotter/rssguard#408]
Keyboard shortcuts to scroll/navigate up/down inside message

I'm using the keyboard to select the next and previous message and I also want to scroll up/down inside the message with the keyboard

This is possible in quiterss, if that is any help 
![image](https://user-images.githubusercontent.com/74221543/116795098-c0d57200-aad2-11eb-87a4-35718f00fdb3.png)

**Comment by martinrotter** [comment]
Fixed, now there are items in main menu "Web browser" + these actions can be binded to keyboard shortcuts.
