### ISSUE TITLE
[FR]: Show/hide reading pane

### ISSUE THREAD

**Issue by kyrawertho** [martinrotter/rssguard#409]
#### Brief description of the feature request.

1. The reading pane disappears when feeds are updated.
2. The reading pane cannot be closed when I want to go back to scrolling through my feed list.

Could an option to show/hide the reading pane be added (just like how we can show/hide the feedlist)?

**Comment by martinrotter** [comment]
Hello @kyrawertho. What is "reading pane", you mean list of messages?

**Comment by kyrawertho** [comment]
I mean the frame that the internal browser opens the messages in (message viewer).
