### ISSUE TITLE
stop working when access messages while updating feeds

### ISSUE THREAD

**Issue by blackarcher21** [martinrotter/rssguard#41]
#### Brief description of the issue.

RSS Guard stop working when I access or read messages while updating feeds of a category. I use MySQL as DB storage. 
RSS Guard 3.3.2
MySQL 5.6.17 (WAMP 2.5.18 x64)
Windows 8.1 x64

#### How to reproduce the bug?

1. Run update on a category
2. Access a message while it updating feeds
3. RSS Guard stop working

#### What is the expected result?

no problem

#### What actually happened?

It stop working

#### Other information (logs, see Wiki)

[log1.txt](https://github.com/martinrotter/rssguard/files/383064/log1.txt)
[log2.txt](https://github.com/martinrotter/rssguard/files/383065/log2.txt)

I decided to attach 2 log from 2 attemps. Thanks

**Comment by martinrotter** [comment]
Is this 100% reproducible every time you try?

**Comment by blackarcher21** [comment]
It's not but it happens most of time.

**Comment by martinrotter** [comment]
OK, it seems that there is clearly problem with mainly MySQL, I will have to use producer-consumer pattern and send all SQL queries to one single class to consume it all in one single thread to avoid these SQL transaction horrors.

**Comment by martinrotter** [comment]
I try to reproduce, but cannot. So you update a lot of feeds and madly clicking on messages and it crashes?

**Comment by martinrotter** [comment]
Okay, I managed it to reproduce once, will try to fix and find bug.

**Comment by martinrotter** [comment]
Does this bug happen with SQLite storage?

**Comment by blackarcher21** [comment]
So far, it's not reproducible with SQLite. Anyway, with MySQL, it seems can be easily make it crash by mark selected messages as read/unread while updating feeds.

**Comment by martinrotter** [comment]
Yes yes, I managed to make it crash too. I know where the core of the problem might be. I will try to think about fix. The goal is to allow multi-thread access to DB so that user can view messages when updating feeds.

**Comment by martinrotter** [comment]
I will fix this this way:

1. All SQL operations when downloading new messages will be done in one single batch transaction. This will have two impacts:
    * When you update for example 10 feeds, all new messages from those feeds will get downloaded first and then all of them will be inserted into SQL at once. So if you update 10 feeds, you will see new messages after all feeds are updated.
    * This approach might bring another noticeable speed improvement, particularly when number of new messages will be high.
    * This approach will also lower SQL/HDD throttling.
2. All SQL operations in separate thread (feed updating) will have unique separated database connections.

**Comment by martinrotter** [comment]
This should be fixed, please test it.

**Comment by blackarcher21** [comment]
could you upload please? resumable link if possible. thanks.

**Comment by martinrotter** [comment]
Will upload test release for you tomorrow maybe.

**Comment by martinrotter** [comment]
Yea, problem is that I moved some DB updating code to main UI thread, which results in app UI thread freezing. I will move the code to feed downloader thread in 3.3.5.

**Comment by martinrotter** [comment]
I made some tweak to make sure that RSS Guard main windows is more responsive during updates. You can get latest automatically compiled development release [here](https://github.com/martinrotter/rssguard/wiki/Windows-development-builds) (It will compile for 15 minutes, so wait 15 minutes from time I post this.).

Let me know if it is better.

**Comment by martinrotter** [comment]
https://transfer.sh/HB4gh/rssguard-win32.7z

**Comment by blackarcher21** [comment]
Hi, thanks for kindly fix the issue. I'm sorry can't test and give feedback, my network connection doesn't look good so got three times timeout already, will try again later.

**Comment by blackarcher21** [comment]
could you upload with resumable link? I have problems when donwloading from these link. It always stop in the middle of process and I need to start again from beginning which is waste lot of my data. Sorry for asking much.

**Comment by martinrotter** [comment]
Don't you have working internet connection? No, I can't I already setup this automatic build machinery, partly for you brother, since you always ask for installers.

**Comment by blackarcher21** [comment]
Yes, I do but not good enough stability for download. Okay, fine. Thank you. :)

**Comment by blackarcher21** [comment]
I can tell that this problem is fixed with newer version. Thanks.

**Comment by martinrotter** [comment]
Okay, perfectos
