### ISSUE TITLE
[FR]: Replace AdBlock with uBlock Origin.

### ISSUE THREAD

**Issue by WhyIsEvery4thYearAlwaysBad** [martinrotter/rssguard#410]
#### Brief description of the feature request.

AdBlock is slower and inefficient compared to uBO (or even AdBlock Plus) and can cause some issues (such as triggering BlockAdBlock) when trying to get RSS updates, due to injecting all filters by default.<sup>[\[1\]](https://github.com/gorhill/uBlock/wiki/About-%22uBlock-is-inferior-in-capabilities-as-a-result-of-being-lighter-on-the-browser%22)[\[2\]](https://github.com/gorhill/uBlock/wiki/Memory-footprint:-what-happens-inside-uBlock-after-installation)[\[3\]](https://github.com/gorhill/uBlock/wiki/Contributed-memory-usage:-benchmarks-over-time)[\[4\]](https://github.com/gorhill/uBlock/wiki/Counterarguments)[\[5\]](https://github.com/gorhill/uBlock/wiki/Debunking-%22uBlock-Origin-is-less-efficient-than-Adguard%22-claims)[\[6\]](https://github.com/gorhill/uBlock/wiki/Firefox-version:-benchmarking-memory-footprint)</sup> I have verified that there are no copyright issues with incorporating uBO's source code into other programs.<sup>[\[1\]](https://old.reddit.com/r/uBlockOrigin/comments/n3ckfy/can_ubo_be_used_in_programs_outside_of_browsers/gwpx4oh/?context=3)[\[2\]](https://github.com/gorhill/uBlock/blob/master/LICENSE.txt)

**Comment by martinrotter** [comment]
@WhyIsEvery4thYearAlwaysBad 

uBlock origin (and pretty much every other adblock implementation) uses JavaScript as its primary runtime (V8) and is pretty much impossible to integrate withing RSS Guard. RSS Guard uses pretty much the same implementation as for example [Falkon](https://www.falkon.org/).

>can cause some issues (such as triggering BlockAdBlock) when trying to get RSS updates

Does this happen to you? It should not, because adblocking in RSS Guard is NEVER used when downloading feeds/messages. It is literally used only when browsing web pages with internal web browser.

>there are no copyright issues with incorporating uBO's source code into other programs

Legally, it is okay. Technically, pretty hardcore. You are welcomed to create nicely structured PR.

**Comment by martinrotter** [comment]
What about allowing user to embed 3rd-party user JavaScript code into web browser part of RSS Guard? If allowed, you could probably use [this](https://github.com/cliqz-oss/adblocker/blob/master/packages/adblocker/README.md).

**Comment by martinrotter** [comment]
For me:
- [ ] Replace C++ implementation of Adblock with modern nodejs-based [implementation](https://github.com/cliqz-oss/adblocker).
- [ ] Remove redundant C++ adblocking classes.
- [ ] Check if/how element hiding rules works.
- [ ] Tweak adblocking GUI dialog and add "Test" button to check if needed node modules are installed. Also add button with link to separate wiki article with adblock.

**Comment by martinrotter** [comment]
@WhyIsEvery4thYearAlwaysBad The solution proposed in my above replies is good, I started implementing it for RSS Guard 4.0.0. Change will be very nice and quite a lot of code could be now removed from RSS Guard as well, while keeping basically almost all previous features and gaining robust, stable and faster implementation.

**Comment by martinrotter** [comment]
Update docs, will start implementing soon.

https://github.com/martinrotter/rssguard/blob/version-4/resources/docs/Documentation.md#adblock

**Comment by WhyIsEvery4thYearAlwaysBad** [comment]
The node.js implementation should work fine. What should be included in adblock/uBO though?

**Comment by martinrotter** [comment]
What do you mean with:

> What should be included in adblock/uBO though

?

**Comment by WhyIsEvery4thYearAlwaysBad** [comment]
> 
> 
> What do you mean with:
> 
> > What should be included in adblock/uBO though

I was just saying what features should be included.

**Comment by martinrotter** [comment]
@WhyIsEvery4thYearAlwaysBad Could you please do some testing of latest development build (compiled in 10 minutes)? The feature should be there and is working pretty nicely.

I will implement adblock query caching to speed it up even more and then close the ticket as done.

**Comment by barolo** [comment]
The amount of setup that needs to be done by end-user for it to work is insane, I have no idea how it ended being acceptable solution.  
Possible example of tech bubble blindness.

**Comment by martinrotter** [comment]
Hello @barolo.

> I have no idea how it ended being acceptable solution.

Sure you don't, everyone can submit PRs by the way.

> Possible example of tech bubble blindness.

Everyone can submit PRs.

At this point, these are the literal steps to have adblock working:
1. Download Nodejs installer, install (it installs NPM too).
2. COPY-PASTE four command line commands into command line.
3. That's it.

> The amount of setup that needs to be done by end-user for it to work is insane, 

Are you kidding me?

> There's rust-adblock which got recently integrated into qutebrowser 

OK so with your suggestion, proposed steps to install your suggested adblock solution would be:
1. Download Python installer, install it.
2. COPY-PASTE some command line commands into command line `(pip3 install python-adblock`).
3. That's it.

WHAT A GREAT improvement over current situation!

**Comment by barolo** [comment]
Not everyone is using Windows, it's worse than tech-bubble blindness it's a Windows-bubble blindness. Python is already a part of the system on non-Windows platforms.

**Comment by remusao** [comment]
> Not everyone is using Windows, it's worse than tech-bubble blindness it's a Windows-bubble blindness. Python is already a part of the system on non-Windows platforms.

Is [Rust](https://github.com/ArniDagur/python-adblock#build-dependencies) also part of the system on non-Windows platforms?

**Comment by barolo** [comment]
> > Not everyone is using Windows, it's worse than tech-bubble blindness it's a Windows-bubble blindness. Python is already a part of the system on non-Windows platforms.
> 
> Is [Rust](https://github.com/ArniDagur/python-adblock#build-dependencies) also part of the system on non-Windows platforms?

Depends on the distro.
Why are we talking about rust dependency anyway python-adblock wheel already contains adblock-rust.

**Comment by martinrotter** [comment]
> Not everyone is using Windows, it's worse than tech-bubble blindness it's a Windows-bubble blindness. Python is already a part of the system on non-Windows platforms

No, generally it is not. It is not a part of OS/2, it is not a part of all Linux distros, for example Arch (which I use).

**Comment by sakkamade** [comment]
> Python is already a part of the system on non-Windows platforms, while node is not [ and for a good reason ]
> 
> The only step needed would be the second one as rust-adblock is already part of the wheel

You are forgetting that the `pip` is also must be installed, or are you saying that it is also a part of the non-Windows systems?

**Comment by martinrotter** [comment]
> 
> 
> > Python is already a part of the system on non-Windows platforms, while node is not [ and for a good reason ]
> > The only step needed would be the second one as rust-adblock is already part of the wheel
> 
> You are forgetting that the `pip` is also must be installed, or are you saying that it is also a part of the non-Windows systems?

It is not - on Arch it is separate package.

All people, take my above [comment](https://github.com/martinrotter/rssguard/issues/410#issuecomment-913992530) into account.

**Comment by sakkamade** [comment]
> It is not - on Arch it is separate package.

Yes, I know, it was a retorical question. (On ubuntu, too.)
