### ISSUE TITLE
[BUG]: protocol error with TheOldReader

### ISSUE THREAD

**Issue by extrowerk** [martinrotter/rssguard#415]
#### Brief description of the issue.
Adding TheOldReader account was added, i left the Server URL field empty, RSSGuard reports protocol_error while trying to connect.

#### How to reproduce the bug?
1. Add an TOR account
2. leave server URL field empty
3. try to synchronize

#### What was the expected result?
Working oob.

#### What actually happened?
Login failed with error: 'protocol error'.

#### Other information
rssguard built by me from unmodified sources.
Debug log: https://gist.github.com/extrowerk/a9cccc790b4fdb0e78451b9a0582acd4

* OS:  64 bit Haiku hrev55087
* RSS Guard version:3.9.2

**Comment by extrowerk** [comment]
Current recipe: https://github.com/haikuports/haikuports/pull/5945

**Comment by extrowerk** [comment]
It looks pretty nice on Haiku:
![42017003-125D-4DB0-A7C0-5DE851E7D304](https://user-images.githubusercontent.com/5569059/119405042-f4c24280-bce0-11eb-89d2-d7826599ab87.png)

**Comment by martinrotter** [comment]
Hello @extrowerk.

You cannot leave "URL" field in greader API plugin settings dialog empty. Even if you choose some service which is not self-hosted, you still have to input target URL.

In [master] branch, there is a change which automatically fills in URL for you if you select non-self-hosted service, like TOR. This change along with other related changes greatly improves stability and usability of Greader API plugin in RSS Guard and will be released with RSS Guard 4.0.0 which will come out maybe in a month.

I highly recommend you to try latest development version, Haiku is not based on Linux, so you have to compile yourself. Simply compile [latest](https://github.com/martinrotter/rssguard/archive/refs/heads/master.zip) code.

https://github.com/martinrotter/rssguard/commit/234d0b13c6c3c6ba32cfabb1e487356bda4b0a01#diff-bd699ace5a42ad1dc3d3772f2034dd23d0c4c687dc43b15ec189d2fad9aa0d1c

Also, there is an indicator icon next to "URL" textbox.

![image](https://user-images.githubusercontent.com/1255302/119442022-658c4d80-bd27-11eb-9a56-be1db24cc40b.png)
![image](https://user-images.githubusercontent.com/1255302/119442034-69b86b00-bd27-11eb-9852-877e71ece6d7.png)

Let me know if I can close this.

**Comment by extrowerk** [comment]
Will try the master branch, thanks for the hint.

I did tested the 3.9.2 version with https://theoldreader.com URL, but it doesnt change anything.
Do i need premium account at TOR for that? Or do i have to enable something at TOR (application password or anything)?

Haiku don't have yet QtWebEngine port, can that be the reason why it doesn't work?

**Comment by extrowerk** [comment]
Oh, i just tested again, with the TOR URL added to the field i get "Network error: access to content was denied"

**Comment by martinrotter** [comment]
> I did tested the 3.9.2 version with https://theoldreader.com URL, but it doesnt change anything.

This is weird.

> Do i need premium account at TOR for that

Certainly not.

> Or do i have to enable something at TOR

Likely not, atleast I did not do anything when testing it.

> Haiku don't have yet QtWebEngine port, can that be the reason why it doesn't work?

No. The difference is only in displaying messages, nothing else.

I tested right now with 3.9.2 and it works here.

![image](https://user-images.githubusercontent.com/1255302/119445627-658f4c00-bd2d-11eb-89c1-01d8c07bbf8a.png)

However, If I deliberately enter wrong password, I get the same "Network error: access to content was denied" as you do. So I believe your entered password is somehow not correct.

Are you sure your PW is correct? Does your password contain non-ASCII characters?

**Comment by extrowerk** [comment]
>So I believe your entered password is somehow not correct.
It is correct.

>Are you sure your PW is correct? Does your password contain non-ASCII characters?
No.

In the meantime i built the master branch and it works correctly. I even copy pasted the account settings from master to 3.9.2 but it still not working in the last release. IDK why. But at least master works. :)

**Comment by martinrotter** [comment]
OK, I consider the thing fixed, I remember there were some little changes in username/password encoding that I changed to be more "correct" and that could be the thing that made it working.

https://github.com/martinrotter/rssguard/commit/9beb4dda8af667388d6ffd2535de639d2f532e63#diff-3ee6921c44f1cd534fce6c5b746530da33c241a4bae7d95a5f079d767f1582e5

**Comment by extrowerk** [comment]
Thank you.
