### ISSUE TITLE
wiki: localization link still pointing to BitBucket

### ISSUE THREAD

**Issue by pmattern** [martinrotter/rssguard#42]
In the wiki's start page link https://bitbucket.org/skunkos/rssguard/raw/master/localization?at=master should be replaced with its counterpart on GitHub.

(Total nonsense to open an issue to report this. But PRs regarding issues still don't seem to be implemented?)

**Comment by martinrotter** [comment]
Fixed.

**Comment by martinrotter** [comment]
You mean PRs regarding wiki I guess.

**Comment by pmattern** [comment]
> You mean PRs regarding wiki I guess.

Ups. Of course.

**Comment by blackarcher21** [comment]
Honestly it's not just the link, some parts of wiki need to be updated.

**Comment by martinrotter** [comment]
@blackarcher21 Tweaked the wiki.

**Comment by blackarcher21** [comment]
looks better to me :+1:
