### ISSUE TITLE
[BUG]: Crash upon clicking "Process checked feeds" in Message filters

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#420]
#### Brief description of the issue.

The crash.

#### How to reproduce the bug?
1. Paste filter (look in Other information) into the "JavaScript code" section of Massage filter
2. Check some either Atom or RSS feed and click "Process checked feeds"
3. The crash

#### What was the expected result?

Not to crash.

#### What actually happened?

Has crashed.

#### Other information

1. The "Script output" if click "Test" on such script is 
```
EXISTING messages filtering error: 'ReferenceError: utils is not defined'.
SAMPLE message filtering error: 'ReferenceError: utils is not defined'.
```
2. The same happens with dev build of latter commit https://github.com/martinrotter/rssguard/commit/719071a9e8c108f76fddd7850a9f86269281cf6e. However I am unable to restart the dev version until after reboot of PC.
(Tried removing the config files, cache files, and cache of QtWebEngine to no avail.)

<details><summary>The script in question (click here)</summary>

```js
function filterMessage() {
  // Read raw contents of message and
  // convert to JSON.
  json = utils.fromXmlToJson(msg.rawContents);
  jsonObj = JSON.parse(json)

  // Read published date and parse it.
  publishedDate = jsonObj.entry.published.__text;
  parsedDate = new Date(publishedDate);

  // Set new date/time for message and
  // proceed.
  msg.created = parsedDate;
  return MessageObject.Accept;
}
```
</details>

* OS: Arch Linux, KDE
* RSS Guard:
Version: 3.9.2 (built on Linux/x86_64)
Revision: 
Build date: 4/17/21 8:31 AM
Qt: 5.15.2 (compiled against 5.15.2)

**Comment by martinrotter** [comment]
thanks, will check!

**Comment by sakkamade** [comment]
> with all feeds or only some feeds?

Every single.

**Comment by martinrotter** [comment]
@sakkamade Feel free to re-test the fix when latest dev. build compiles (15 minutes). AppImages should be there now too as build failure is fixed too.

**Comment by sakkamade** [comment]
> Feel free to re-test the fix

Fixed.
