### ISSUE TITLE
[BUG]: The size of the font of "Internal message browser" cannot be changed

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#421]
#### Brief description of the issue.

While I can set the font itself, I cannot change its size and style unlike the "Feed list font" and "Message list font," where I can customise it all and well.

#### How to reproduce the bug?
1. Settings -> Feeds & Messages -> Internal message browser font
2. Change the style (_Italic_, **Bold**) or the <small>s</small>i<big>ze</big>
3. No variation have befallen the browser 

#### What was the expected result?

Being able to change the size and style of the font in internal browser.

#### What actually happened?

Unable to change aforementioned positions.

#### Other information

The issue present in both `3.9.2` and development build of latter commit https://github.com/martinrotter/rssguard/commit/bc739ca9fa5a733fdb226b18420a51348bb455d3.

* OS: Arch Linux, KDE
* RSS Guard:
Version: 4.0.0 (built on Linux/x86_64)
Revision: bc739ca9
Build date: 5/28/21 8:44 PM
Qt: 5.15.2 (compiled against 5.15.2)

**Comment by martinrotter** [comment]
@sakkamade To summarize:

1. You can change font family, for example to "Arial".
2. You cannot change for variant, for example from "Regular" to "Bold".
3. You cannot change font size.

There are technical limitations in WebEngine component (Chromium-like displayer of HTML/CSS/JS websites) which do not allow to implement 2, sadly. You can indeed change the font itself, but not its variants and there is nothing I can do.

As for problem 3 - shortly, you can use `CTRL + LMBT` (left mouse button) to zoom in/out, just like in regular web browsers and RSS Guard remembers the setting persistently. Long story - problem is that some feeds provide entries which themselves include CSS to style the overall look of the entry/article/message which often hardcodes font style and sizes etc. This CSS discrupts default font size/type/family settings.

I will try to force font size set in app setting more aggresivelly, but it will never be perfect. Just try the above zooming keyboard shortcut, it may work well enough for you and let me know.

**Comment by sakkamade** [comment]
> shortly, you can use `CTRL + LMBT`

It is not so reliable, is it. Too arbitrary...
Would be better to have <kbd>Ctrl</kbd>+<kbd>+</kbd>, <kbd>Ctrl</kbd>+<kbd>-</kbd>, and <kbd>Ctrl</kbd>+<kbd>0</kbd> instead.

**Comment by martinrotter** [comment]
@sakkamade I right now pushed new code, possibly fixing problem 2.

8849d47c

Wait for development build and let me know if the fix works. Here it works beautifully.

**Comment by sakkamade** [comment]
The <kbd>Ctrl</kbd>+<kbd>0</kbd> (or similar) to restore the zoom will be still great to see.

**Comment by martinrotter** [comment]
![D7o1QUJ3LJ](https://user-images.githubusercontent.com/1255302/120148228-2e66e200-c1e8-11eb-9226-c3b0deb21c70.gif)

**Comment by sakkamade** [comment]
> possibly fixing problem 2.

I could not care less about changing the style, actually.

**Comment by martinrotter** [comment]
@sakkamade Here you go: 26f073d8

**Comment by sakkamade** [comment]
Tested: fixed.
