### ISSUE TITLE
[BUG]: Images are not duly displayed with some feeds in the Message viewer

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#422]
#### Brief description of the issue.

The images (the whole reason of my using version with web-engine) are not displayed in Message viewer until the "URL" of the particular message has been opened in internal browser.

#### How to reproduce the bug?
1. Choose some feed which messages contain images, and select some message
2. Click "URL" on this message
3. After the page was loaded, click "Back"
4. The image is displayed correctly now

#### What was the expected result?

The image to load right when message was updated/created.

#### What actually happened?

Image is not loaded properly.

#### Other information

1. I am apologise, I kept utterly forgetting of the log files (save for my first issue here, where I reckoned that the log would be irrelevant), here is one: ~~[rssguard-log.txt]()~~ <ins>removed</ins>
2. The issue exists in both `3.9.2` and development build.

* OS: Arch Linux, KDE
* RSS Guard:
Version: 4.0.0 (built on Linux/x86_64)
Revision: bc739ca9
Build date: 5/28/21 8:44 PM
Qt: 5.15.2 (compiled against 5.15.2)

**Comment by martinrotter** [comment]
@sakkamade Please post screenshot of how message looks BAD and how it looks GOOD so that I can see/compare. Also, does the issue happen with all feeds?

**Comment by sakkamade** [comment]
They are not displayed at all, until the whole page was opened in browser. 
The problem is most likely with that incredible feed, you may find it in log file.

**Comment by martinrotter** [comment]
OK, will check. I check with some random feeds and it works: 

![image](https://user-images.githubusercontent.com/1255302/120150440-599f0080-c1eb-11eb-94db-7838959da52a.png)

Also, there are other settings which influence displaying of images, particularly AdBlock and this:

![image](https://user-images.githubusercontent.com/1255302/120150515-70455780-c1eb-11eb-952c-980dd87eb763.png)

**Comment by martinrotter** [comment]
@sakkamade Reproduced the bug with your feed, let me check.

**Comment by martinrotter** [comment]
Fixed: ad265dfb please check and let me know.

**Comment by sakkamade** [comment]
@martinrotter Yes, everything is fixed.

**Comment by sakkamade** [comment]
@martinrotter, Lately, being hooked up on this RSS-thing as I am, I was trying out quite a bit of different feeds, and found another one, images of which are also not shown. Here's an example:

<details><summary>Example</summary>

```xml
<feed xmlns="http://www.w3.org/2005/Atom">
    <title>the main title</title>
    <link rel="alternate" type="text/html" href="https://the_link"/>
    <link rel="self" href="https://the_link.xml"/>
    <id>https://the_id</id>
    <updated>2001-01-28T01:17:29+00:00</updated>
    <author>
        <name>the author</name>
    </author>
<entry xmlns="http://www.w3.org/2005/Atom">
    <title>the title</title>
    <link xmlns="http://www.w3.org/2005/Atom" rel="alternate" type="text/html" href="https://link"/>
    <id>https://the_id</id>
    <published>2011-05-20T11:19:19+00:00</published>
    <updated>2001-01-28T01:17:29+00:00</updated>
    <author>
        <name>the author</name>
    </author>
    <summary type="text"/>
    <content type="xhtml">
        <div xmlns="http://www.w3.org/1999/xhtml">
            <p>the paragraph</p>                                    <!-- this paragraph is shown --->
            <img src="https://paste_some_image_link_here.png" />    <!-- this image is not shown --->
        </div>
    </content>
</entry>
</feed>
```
(tried it in Akregator as well, works fine)
</details>

**Comment by sakkamade** [comment]
And another one (though image of this feed is not displayed in Akregator likewise):

<details><summary>Example</summary>

```xml
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
    <title>title</title>
    <link href="https://test.atom" rel="self" />
    <subtitle>test syb</subtitle>
    <updated>2020-12-25T10:12:12+00:00</updated>
    <author>
        <name>name test</name>
    </author>
    <id>https://test.com/</id>
    <entry>
        <title>title entry test</title>
        <id>https://test.com/test-12-21</id>
                <updated>2020-12-21T10:08:15+00:00</updated>
                <published>2020-12-21T10:08:15+00:00</published>
        <link href="https://test.com/test-12-21"/>
        <content type="html">
            <![CDATA[
                        <img alt="" src="/image12-21.png" />    <!-- this image is not shown --->
                        <p>paragraph</p>                        <!-- this paragraph is shown --->
                        <p>some more</p>                        <!-- this shown too --->

            ]]>
        </content>
    </entry>
</feed>
```
</details>

**Comment by martinrotter** [comment]
@sakkamade Could you give specific examples with real-worls image source URLs? `https://image12-21.png` is not really valid URL anyway.

**Comment by martinrotter** [comment]
Tested:

![image](https://user-images.githubusercontent.com/1255302/125273439-364c9280-e30d-11eb-90ca-228bd31617d2.png)

```xml
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>title</title>
  <link href="https://test.atom" rel="self" />
  <subtitle>test sub</subtitle>
  <updated>2020-12-25T10:12:12+00:00</updated>
  <author>
    <name>name test</name>
  </author>
  <id>https://test.com/</id>
  <entry>
    <title>title entry test</title>
    <id>https://test.com/test-12-21</id>
    <updated>2020-12-21T10:08:15+00:00</updated>
    <published>2020-12-21T10:08:15+00:00</published>
    <link href="https://test.com/test-12-21" />
    <content type="html">
      <![CDATA[
                        <img alt="" src="https://stavba.tzb-info.cz/docu/tabulky/0001/000172o1.svg" />    <!-- this image is not shown --->
                        <p>paragraph</p>                        <!-- this paragraph is shown --->
                        <p>some more</p>                        <!-- this shown too --->

            ]]>
    </content>
  </entry>
</feed>
```

**Comment by martinrotter** [comment]
I managed to partially reproduce, gimme some time to fix.

**Comment by sakkamade** [comment]
Here it is, if I am not mistaken: https://bakkin.moe/home.atom

**Comment by martinrotter** [comment]
Yes, well it is a mess.

Some feeds do HTML [entity](https://www.w3schools.com/html/html_entities.asp) encoding, some even place their article contents into [CDATA](https://en.wikipedia.org/wiki/CDATA) and some crazy feed authors use website [relative](https://www.w3.org/TR/WD-html40-970917/htmlweb.html) URLs! That is in particular evil behavior for RSS feeds because RSS reader cannot just take HTML/XML fragment and display it. It must somehow decide what the actualy BASE website URL is. Well, that sucks!

Your last example is "perfect" combination of evil practises:


```xml
            <![CDATA[
                        <img alt="" src="/user/pages/01.home/release-oomuro-ke-chapter-59/001.png" />
                        <pre><code>&gt; A wild Hanako appeared
&gt; Misaki used cheat
&gt; Misaki rolled a ⚀
&gt; Hanako rolled a ⚅</code></pre>

            ]]>

Everything is in CDATA, some characters are escaped (others relevant are not) and URLs (to images) are relative. Relative to what? Hell.
```

**Comment by martinrotter** [comment]
So, I believe I am on right track to fix almost all encoding-related issues but those relative paths are big problem.

**Comment by sakkamade** [comment]
> ...  feed authors use website relative URLs! **That is in particular evil behavior for RSS feeds** ...

Ah... I have given an incorrect example...

> ... those relative paths are big problem.

I don't really care much whether that feed will work as it should have. 
As long as RSS Guard is not at fault, it's totally fine.

**Comment by martinrotter** [comment]
I will try to "fix" it but I suspect that we might even get some undesired side effects.

**Comment by sakkamade** [comment]
> some characters are escaped (others relevant are not)

God, I completely forget it... and copied the code by browser's dev tools... 
My examples are perfectly sucks ＼(^o^)／

**Comment by martinrotter** [comment]
Yes, you got caught into that hell too.

**Comment by martinrotter** [comment]
OK, please, test this shit. It could be the miraculous code we are waiting for.

299415f5

**Comment by martinrotter** [comment]
86ae0c58

So test it and if it works I will enable functionality for RDF and JSON feeds too.

**Comment by sakkamade** [comment]
> So test it ...

At the very least, I can see that it works fine with those feeds, now; and these few feeds which I have which enclose the pictures displaying them still.

> big number of standard XML (RSS/ATOM) feeds to find out potential problems ...

The problems of what sort? Not displayed pictures? Or problem might emerge with any URL?

**Comment by martinrotter** [comment]
Just general message layout/formatting problems.

**Comment by sakkamade** [comment]
@martinrotter,
Regression was introduced with one of recent commits, for feeds with such layout:

> ```
>             <![CDATA[
>                         <img alt="" src="/user/pages/01.home/release-oomuro-ke-chapter-59/001.png" />
>                         <pre><code>&gt; A wild Hanako appeared
> &gt; Misaki used cheat
> &gt; Misaki rolled a ⚀
> &gt; Hanako rolled a ⚅</code></pre>
> 
>             ]]>
> ```

Fetching the article for the first time results in a broken image. 
Fetching it second time fixes the image.

**Comment by martinrotter** [comment]
Jeez. URL of a feed?

**Comment by sakkamade** [comment]
> Here it is, ~if I am not mistaken~ certainly: https://bakkin.moe/home.atom

**Comment by sakkamade** [comment]
> done

It is! Thank you!

**Comment by sakkamade** [comment]
@martinrotter, 
Sorry for off-topic, but I have a question.
Am I allowed to fiddle with [RSS Guard's icon](https://github.com/martinrotter/rssguard/tree/master/resources/graphics)?

I want to increase the contrast of monochrome icon, but quite hesitant 
> Application icon was kindly contributed by Siddharth Yadav

I guess it would be better to make an issue with example, rather than PR, right?

**Comment by martinrotter** [comment]
Icon is GNU GPLv3. You can tweak it. Make an issue and potentially PR.
