### ISSUE TITLE
[FR]: Option to display information of selected item from the feed list (persistent Message viewer)

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#424]
#### Brief description of the feature request.

When I select a certain feed from the list, I would like to see its information (Name, Description, 
Homepage, perhaps Type, etc.) in the Message viewer;
When I select Account: the Name, and Information/Description about the service it's using;
When labels, etc., etc.

If there's a willing for this feature to be implemented, I shall elaborate my view, otherwise just close it.

The main argument is that it feels lonely when the Message viewer gets hidden.
In my opinion, even an empty Message viewer would have had a better look (in standard layout).

**Comment by martinrotter** [comment]
Perhaps post some screenshot/mockup? Perhaps from how other apps display this?

**Comment by sakkamade** [comment]
> EDIT: ...
Yes, correct.

**Comment by sakkamade** [comment]
<details><summary>Examples from Akregator:</summary>

Information of item from feeds' list:
![all](https://user-images.githubusercontent.com/62730422/120160910-50f7fb80-c1e6-11eb-8086-93903d5d1083.png)

---
Information of message from feed:
![all2](https://user-images.githubusercontent.com/62730422/120160915-52292880-c1e6-11eb-9871-dcf9a633b618.png)

</details>

**Comment by sakkamade** [comment]
> When I select a certain feed from the list, I would like to see its information (Name, Description,
Homepage, perhaps Type, etc.) in the Message viewer [...]

I believe that all information which is currently shown in tooltip should look great there. (Either account's tooltip, feed's, etc.)

**Comment by martinrotter** [comment]
FOR ME: Also, some people complained that when article previewer hides (in horizontal layout) then article list jumps. As indicated in #495 - different symptoms same cause -> show article "previewer" constantly with some information about rssguard/feed/category/article.

**Comment by martinrotter** [comment]
![rssguard_DXbOvCcn8n](https://user-images.githubusercontent.com/1255302/231679795-a0cc6151-bb5d-4c4e-a8cc-621d637ee71a.gif)

**Comment by martinrotter** [comment]
![rssguard_adMdECB0HL](https://user-images.githubusercontent.com/1255302/231706169-bf313b76-02e1-4b47-b2c2-d9c1f2071b14.gif)
enhanced formatting, some finishing touches and will push today

**Comment by martinrotter** [comment]
fixed, switchable in settings, by default enabled
