### ISSUE TITLE
[BUG]: [KDE] Interface. Missing icons in Toolbars settings.

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#425]
#### Brief description of the issue.

Some icons are missing as shown in screenshot below:

![rss icons](https://user-images.githubusercontent.com/62730422/120054878-24938200-c022-11eb-8112-19145e2b3244.png)

#### How to reproduce the bug?
1. Open the Settings -> User Interface -> Toolbars

#### What was the expected result?
Visible icons.

#### What actually happened?
Icons are invisible (thank you for tooltips).

#### Other information

The icons are missing, and missing constantly. 
It is irrelevant which Icon theme or Style is chosen, some icons are missing nevertheless (unless I am too careless, and accidentally missed one).

<details><summary><code>Default</code> Style (click here)</summary>

![rss guard missing icons](https://user-images.githubusercontent.com/62730422/120118496-5885b900-c182-11eb-9e23-d91415c76373.png)
</details>

* OS: Arch Linux, KDE
* RSS Guard
Version: 4.0.0 (built on Linux/x86_64)
Revision: bc739ca9
Build date: 5/28/21 8:44 PM
Qt: 5.15.2 (compiled against 5.15.2)

**Comment by martinrotter** [comment]
Yes, this is because of how icon themes on Linux work. Some icon themes are more "complete" than other icon themes.

**Comment by sakkamade** [comment]
But there is none which is "completely complete"

**Comment by martinrotter** [comment]
No, but there are themes which are **more** complete. For example Numix or Faenza. These two themes are bundled into RSS Guard on other platforms, on Linux I do not bundle them to keep binary "rssguard" smaller, therefore I recommend you to install one of those and experiment.

**Comment by martinrotter** [comment]
At this actualy place (toolbar editor) the problem is particularly visible because those buttons have texts disabled.

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/120158520-83a8f080-c1f4-11eb-9abf-0d04d1a83506.png)

This is Linux with installed Numix icon theme.

**Comment by sakkamade** [comment]
> Faenza ...

This one is a solution.
The problem is that the package in Arch repository is not listen Faenza as dependency, nor it even an optional dependency.

If someone would be so good to report it there: Good. Otherwise perhaps I will do so—__perhaps__. 

Thank you. Closing it.

**Comment by martinrotter** [comment]
Also, I now add change which displays texts in those button as well.

![image](https://user-images.githubusercontent.com/1255302/120159043-0fbb1800-c1f5-11eb-8c1b-8b373731249d.png)

**Comment by martinrotter** [comment]
> The problem is that the package in Arch repository is not listen Faenza as dependency, nor it even an optional dependency.

https://bugs.archlinux.org/task/71069
