### ISSUE TITLE
[BUG]: Cosmetic. Fusion style. Incorrect background colour and poor appearance of certain items in Settings.

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#426]
#### Brief description of the issue.

Please accept my apology that I have reported two problems in a single issue.
This is only because both of them (at least visually) are related to particular style: Fusion (default).

<details><summary>Three screenshots (click here)</summary>

#### `#1` Issue with padding, margin, or just height of Feed list font:
![rss interface](https://user-images.githubusercontent.com/62730422/120054928-72a88580-c022-11eb-8caa-5961be219f80.png)

#### `#2` Issue of incorrect (grey) background colour in User interface -> Icons & skins
![rss grey background](https://user-images.githubusercontent.com/62730422/120055550-6d4d3a00-c026-11eb-8448-c79d07c488a2.png)

As shown in the following screenshot, the issue is not present in this section of Settings with similar content
![rss proper background](https://user-images.githubusercontent.com/62730422/120055566-86ee8180-c026-11eb-81d4-7132f27d997b.png)
 
</details>

#### How to reproduce the bug?
1. (Please look the screenshots)

#### What was the expected result?

Flawless interface.

#### What actually happened?

Not-so-flawless interface.

#### Other information

I will add the list, so it should be simpler to keep an eye on progress or to see that it is "all done" afterwards.
- [ ] The Feed list font issue
- [ ] The background colour issue

If it is not good still, I shall separate the "Background issue."

* OS: Arch Linux, KDE
* RSS Guard
Version: 4.0.0 (built on Linux/x86_64)
Revision: bc739ca9
Build date: 5/28/21 8:44 PM
Qt: 5.15.2 (compiled against 5.15.2)

**Comment by sakkamade** [comment]
Forgot to mention, the appearance of "Feed list font" is normal in version `3.9.2`.

**Comment by martinrotter** [comment]
> Issue with padding, margin, or just height of Feed list font:

Could be already fixed in latest [master], try latest development build when it appears.

**Comment by martinrotter** [comment]
> Issue of incorrect (grey) background colour in User interface -> Icons & skins

Should be now fixed with: c124d1a1

**Comment by sakkamade** [comment]
@martinrotter, Yes, it is fixed.

/off-topic
Please give me some answer on my request in Transifex.

**Comment by martinrotter** [comment]
Will check, it was you who wanted Eng-GB language? Is it really needed when we have Eng-US?

**Comment by sakkamade** [comment]
Well, I like it much better, furthermore upon setting GB local will be automatically set proper (no offence U.S. dwellers) date/time format, according to: 
![local](https://user-images.githubusercontent.com/62730422/120164602-463f6580-c1ea-11eb-839d-e6e4d2b4b77b.png)

**Comment by sakkamade** [comment]
However if you questioned of its actual need, the answer is nothing but esthetical: from changes there are mostly "se" "sa" in place for "za" "ze".

**Comment by martinrotter** [comment]
@sakkamade OK, peace, brother. I love Brittish people (except "prince" Harry, perhaps).

Your heart is pure, I approve.

**Comment by sakkamade** [comment]
Hahahaha.
