### ISSUE TITLE
[BUG]: "Keep message selection in the middle" is excessively constant

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#427]
#### Brief description of the issue.

"Keep message selection in the middle of the message list viewport" function being triggered on mouse click.

#### How to reproduce the bug?
1. Enable aforementioned option in Settings
2. Click some messages in list

#### What was the expected result?

"Keep message selection in the middle of the message list viewport" should not be utilised by mouse click, but only by arrow keys.

#### What actually happened?

Please spare me...

#### Other information

<details><summary>The details (click here)</summary>

Some nice, little bug which have arisen out of it:

https://user-images.githubusercontent.com/62730422/120121478-3ba5b180-c193-11eb-8be4-4a5137af43d8.mp4

---
To show what I expect it to be, here is the test video of "Kate" which has similar feature:

https://user-images.githubusercontent.com/62730422/120121773-e4084580-c194-11eb-89fd-f0ea25835ad9.mp4
</details>

* OS: Arch Linux, KDE
* RSS Guard
Version: 4.0.0 (built on Linux/x86_64)
Revision: bc739ca9
Build date: 5/28/21 8:44 PM
Qt: 5.15.2 (compiled against 5.15.2)

**Comment by martinrotter** [comment]
Fixed, feature is now not used on message list operations involving mouse clicks.

**Comment by sakkamade** [comment]
Thank you!
