### ISSUE TITLE
[BUG]: Latest dev version b168b6d crashes Visual Studio C++

### ISSUE THREAD

**Issue by umbellipher** [martinrotter/rssguard#428]
b168b6d crashes (Windows 10 Pro 64 build 19041.vb_release.191206-1406) various .dlls for all apps which depend on them, necessitating a roll-back to a previous restore point.

I tried to download twice, and run, with the same effect.

I had kept bc739ca on the PC, in case of issues, but dependencies were corrupted on running that too.

**Comment by sakkamade** [comment]
The issue appears to affect `nowebengine` version.

My steps were such:
1. Install version __with__ webengine
2. Start it
3. Everything is fine
4. Now re-install `nowebengine` version into the same path
5. Attempt to start it
6. Receive a bunch of "VCRUNTIME140.dll errors"
7. Re-install webengine-version
8. Upon start now it shows the same errors
9. Tried to uninstall RSS Guard and Visual Studio application, and then install them again, but result is the same

Did not try to dig deeper than this.

---

Here <https://support.mozilla.org/en-US/questions/1290656> is something relevant, @umbellipher, you may want to try it.

**Comment by sakkamade** [comment]
@umbellipher, Never mind that link.

The temporary solution:
Download Visual Studio 2015, 2017 and 2019 (you may find it [here](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0)), then execute it and click "Repair".

**Comment by martinrotter** [comment]
I really doubt it has something to do with RSS Guard itself. VC runtime did not change some versions back. It has to have something to do with runtime conflicts within the OS.

Also, Microsoft is known to fuck up their runtime compatibility or introduce crashes in new versions.

What I highly recommend is to install ALL runtime with a single installer, you can find here: https://github.com/abbodi1406/vcredist/releases

This is "repack" and author is quite reliable so now viruses etc. It works 1000% better than Microsoft's runtime installers. I will test latest dev. build in latest plain Windows 10 in VirtualBox.

**Comment by martinrotter** [comment]
@umbellipher Also, paster here list of all files you see in RSS Guard folder after installation, pls.

Also note that installer automatically installs VC runtime 2010 and 2015-2019.

**Comment by sakkamade** [comment]
I tested in on Windows version 10.0.19042.928 on virtualbox.


Here the errors I got on 6th and 8th steps.

<details><summary>Screenshots of errors (click here)</summary>


![1](https://user-images.githubusercontent.com/62730422/120270956-eef8ce00-c299-11eb-88a4-1b885ec9d8a0.png)
![2](https://user-images.githubusercontent.com/62730422/120270957-f029fb00-c299-11eb-914d-b98bc4ec062a.png)
![3](https://user-images.githubusercontent.com/62730422/120270959-f029fb00-c299-11eb-85b0-5c76a5793574.png)
![4](https://user-images.githubusercontent.com/62730422/120270962-f0c29180-c299-11eb-97c4-ef7433106e97.png)


</details>


---
But sorry, I did not screenshot folder's content, and I cannot test it again right now.

**Comment by martinrotter** [comment]
OK, I have clean Windows 10 x64 in VB. Images below. RSS Guard correctly installed itself and VC++ runtimes, then it launched OK.

![explorer_MAmzWizkN4](https://user-images.githubusercontent.com/1255302/120272367-45bbd300-c2ad-11eb-9aea-a08bb5b9b6e2.png)
![explorer_p1B0I6nYKE](https://user-images.githubusercontent.com/1255302/120272372-46ed0000-c2ad-11eb-9b10-2b110e29fe41.png)
![explorer_tBhokeiJaq](https://user-images.githubusercontent.com/1255302/120272374-46ed0000-c2ad-11eb-9180-2f9d0c7de1ae.png)

**Comment by umbellipher** [comment]
Thanks, @sakkamade. Those are precisely the errors I get. It's definitely build b168b6d: I downloaded, installed and ran twice, and it happened both times. Not a complaint, of course: this is development stuff! And the effect was to bork runtime system-wide: other programs dependent on it threw the same errors.

**Comment by martinrotter** [comment]
@umbellipher So the error is probably in the runtime installer used by rss guard?

**Comment by martinrotter** [comment]
@umbellipher @sakkamade  Does latest dev build

https://github.com/martinrotter/rssguard/releases/download/devbuild/rssguard-3.9.2-24fb0a2e-win64.exe

gives same problematic results?

**Comment by sakkamade** [comment]
Sorry, I will test it only tomorrow.

**Comment by umbellipher** [comment]
Trying it now...

**Comment by martinrotter** [comment]
@sakkamade @umbellipher BTW, you are correct as for VC runtimes.

Newer versions of RSS Guard seem to include VC runtime installer version 14.29.30037 (which is probably buggy), older versions 14.28.XXX work fine.

Also, those new 14.29.XXX versions of runtime installer are DOUBLE in size when compared with those older ones (24 vs 14 MB).

**Comment by umbellipher** [comment]
Yes, same issue still obtains with 24fb0a2e, sadly.

**Comment by martinrotter** [comment]
@umbellipher Can you confirm that other application are crashing because of fautly runtime too? Or just RSS Guard?

**Comment by martinrotter** [comment]
@umbellipher One more test please, if you just use "7z" archive of rssguard and install those included VC runtime by hand, does it help?

**Comment by umbellipher** [comment]
Yes, I use a digital clock which, when restarted, throws the same error. I am installing https://github.com/abbodi1406/vcredist/releases, but it does not play well with other versions of runtime already installed.

**Comment by umbellipher** [comment]
It's asking me to remove previous runtime versions, and either I'll do that or roll back to a previous restore point.

**Comment by martinrotter** [comment]
> 
> 
> It's asking me to remove previous runtime versions, and either I'll do that or roll back to a previous restore point.

First please try 👍 
One more test please, if you just use "7z" archive of rssguard and install those included VC runtime by hand, does it help?

**Comment by umbellipher** [comment]
Still trying to install runtime  from your link above. Not sure which part of the unpacked 7z to try to install.

**Comment by martinrotter** [comment]
vc_redist.x64.exe (without 2010)

**Comment by umbellipher** [comment]
So far: installing https://github.com/abbodi1406/vcredist/releases corrects the error in 24fb0a2, though I need to reboot before I can be sure. I am not inclined at the moment to do the 7z thing. And, of course, one would not want to re-install runtime every time one tried out a new dev build!

I suspect it has been a clash with runtime versions already installed on W10, but of course I cannot be sure.

**Comment by sakkamade** [comment]
Not from link above!

> just use "7z" archive of rssguard

[This](https://github.com/martinrotter/rssguard/releases/download/3.9.2/rssguard-3.9.2-407646a8-nowebengine-win64.7z)

**Comment by umbellipher** [comment]
@martinrotter So here's where I've got to, fwiw. Installed runtime from https://github.com/abbodi1406/vcredist/releases. Reboot. Other apps with runtime dependencies seem to open without error. But build 24fb0a2e now hangs when I try to open it. Didn't try installing runtime from 7z. Uninstalling 24fb0a2e and reverting to 719071a9 for the moment.

In case I did not make it clear, this was throughout the versions with web engine.

**Comment by martinrotter** [comment]
@umbellipher @sakkamade It seems that official Qt library DLLS bundled with RSS Guard are somehow not quite compatible with newer versions of VC++ runtime.

4.0.0 of RSS Guard is still month(s) away so let's wait until situation settles and then I will come with some solution.

**Comment by umbellipher** [comment]
Okay. The last dev build which did not bork stuff was bc739ca. I'd like to sit with that until this is resolved. How do I download a copy of the Win64 web engine build of that, please? Or, once superseded, is it gone?

**Comment by martinrotter** [comment]
@umbellipher Just to be clear, there is nothing wrong with RSS Guard code, either commit will work. The only difference is that when https://github.com/martinrotter/rssguard/commit/bc739ca9fa5a733fdb226b18420a51348bb455d3 was compiled, the "github actions" environment Windows image contained older VC runtime. Sadly, day ago github updated their Windows images and they now contain newer VC runtime which contains the buggy behavior.

Sadly older builds installers/archives are not kept somewhere. They are overwritten/removed with every build.

**Comment by umbellipher** [comment]
@martinrotter Okay, thanks. I will stick with what I have until the underlying issue - which I now recognize is not easily within your control - is resolved. Thank you for all of this. Appreciated.

**Comment by sakkamade** [comment]
Sorry, but I must confirm that the issue is in the installer.

I have tried to re-install the Microsoft Visual C++ 2015-2019 14.29.30037 from `.7z` archive of the RSS Guard (vc_redist.x64.exe), and it works flawlessly.

**Comment by sakkamade** [comment]
It happens upon second installation either nowebengine or normal version of application.

**Comment by sakkamade** [comment]
Nice and small test-video:

https://user-images.githubusercontent.com/62730422/120432106-f5a24680-c368-11eb-8662-a99d3918f922.mp4

**Comment by martinrotter** [comment]
@sakkamade Holy shit! What the hell. My dear god.

**Comment by martinrotter** [comment]
@sakkamade I will probably disable silent installation of VC runtimes and will displays those installers to the users, so that he can decide what to do.

**Comment by sakkamade** [comment]
Sorry, I am no developer, but why only "vc_redist.x64.exe" has additional "/install" flag?
 I'm wondering, but it's not causing this problem, right?

**Comment by martinrotter** [comment]
@sakkamade Just checked. Older installer for MSVC 2010 does not support `/install` flag. Funny thing is that if I follow your video to a letter I do not reproduce the bug.

**Comment by martinrotter** [comment]
Microsoft Windows [Version 10.0.19042.985]

**Comment by martinrotter** [comment]
I pushed new code and installer now does not install the shit silently and displays window. Let's test it.

**Comment by martinrotter** [comment]
@sakkamade Can you test https://github.com/martinrotter/rssguard/releases/download/devbuild/rssguard-3.9.2-fc474f8e-win64.exe ?

**Comment by sakkamade** [comment]
Why, of course it's work fine now.
However now user needs to go through six additional dialogue windows in case if they already have needed versions.

There must be some verification: No pop-up dialogues, if the versions of VC are up to date.

**Comment by martinrotter** [comment]
@sakkamade This is pain in the a*s. It seems that their "unattended" switches are somehow buggy. There are really no other options.

Some years ago I was shipping needed libraries like `vcruntime_x.dll` directly with the app, but it is problematic regarding  licensing from Microsoft.

There is article about it: https://docs.microsoft.com/en-us/cpp/windows/redistributing-visual-cpp-files?view=msvc-160

You can check some registry entries, but only for runtime 2015+. RSS Guard also needs runtime 2010 (for openssl) which is hard to determine if installed.

**Comment by martinrotter** [comment]
I will try to investigate full DLL dependency tree and maybe I will include all those libs within RSS Guard....each approach really has its advantages and downsides.

**Comment by sakkamade** [comment]
Well, to be honest, I myself see no issue in some six additional dialogues once in a while; however I already see the issues which would be pointing straight to this fact.

**Comment by martinrotter** [comment]
@sakkamade OK, pls test latest dev. build installer, it should work. I tested RN on clean VBox win10.

**Comment by umbellipher** [comment]
That works really well now. Good to exclude runtime installers. I imagine that will set the approach for next dev builds. Thank you!

**Comment by martinrotter** [comment]
Yes, some time ago I thought that I just install official runtime installer silently and that's it - zero hassle operation for me and user, but I was once again proven wrong.

At this point list of needed DLL libs is quite small and manageable. It is here: https://github.com/martinrotter/rssguard/tree/master/resources/scripts/redist

Also, now I have total control over the exact versions of those libs. Future will show if it is good or bad thing.
