### ISSUE TITLE
[BUG]: The zoom reset by Ctrl+0 is not restored after restart

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#429]
#### Brief description of the issue.

100% zoom of the Message viewer which was set by <kbd>Ctrl</kbd>+<kbd>0</kbd> is not kept.

#### How to reproduce the bug?
1. Change zoom with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>=</kbd> or <kbd>Ctrl</kbd>+<kbd>-</kbd>
1. Reset the zoom by <kbd>Ctrl</kbd>+<kbd>0</kbd>
2. Restart application
3. Zoom which was set before <kbd>Ctrl</kbd>+<kbd>0</kbd> is restored

#### What was the expected result?

The zoom to be saved after restart.

#### What actually happened?

It is not.

#### Other information

This has obviously been introduced with 26f073d.

* OS: Arch Linux, KDE
* RSS Guard
Version: 4.0.0 (built on Linux/x86_64)
Revision: b168b6d2
Build date: 31/05/2021 09:14
Qt: 5.15.2 (compiled against 5.15.2)

**Comment by martinrotter** [comment]
:D
