### ISSUE TITLE
[FR]: Shorten the names of Toolbars' actions

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#430]
#### Brief description of the feature request.

I would like to see shorter names (at least by omitting words like "Show", "Select", "Messages", etc.) in toolbar list, or/and make them shorter by overflow at certain width with `...`.

To understand why, you only need to look——
<details><summary> Screenshots (click here) </summary>

### Icons and text
![1](https://user-images.githubusercontent.com/62730422/120400408-5b70dd00-c32d-11eb-935b-3491461dd601.png)

### Text only
![2](https://user-images.githubusercontent.com/62730422/120400420-5e6bcd80-c32d-11eb-9f6b-f8fd56a756fd.png)

### Icons only
![4](https://user-images.githubusercontent.com/62730422/120400426-60ce2780-c32d-11eb-8df1-ea00db8676f6.png)

---
## Nice and tidy look in Akregator

![6 akreg](https://user-images.githubusercontent.com/62730422/120400704-f073d600-c32d-11eb-8b21-c0c94610b303.png)

</details>

**Comment by martinrotter** [comment]
Yes, I plan to completely go through all phrases used in program and unify, shorten them.

**Comment by martinrotter** [comment]
@sakkamade Also, there is a problem for some items whose titles cannot be shortened without losing information on how the item actual does. How would you shorten "Mark selected messages as unread"?

**Comment by sakkamade** [comment]
"Mark as unread", and the tooltip which will display more minute explanation.

**Comment by sakkamade** [comment]
Perhaps change the "Items" to "Feeds"?
And so it will be:
- "Mark as unread"
- "Mark feed as unread"
- "Mark all feeds as unread"
 (I am strongly opposite leaving the "Item" as is; the actual meaning of the word is not followed in my opinion)

Then edit "Select next unread message" to "Next unread", etc.
Well, if you want it to be more plain, may as well append something like "entry", "article" or—here it may be as well—"item".

All in all,
1. "message" to "entry", "item" or simply omit it;
2. "item" to "feed", perhaps "subject", "topic", "object",  otherwise simply omit this one instead;
3. "select", "show" just leave it out.

There is also "Switch importance of selected messages" and "Switch message list layout orientation", they may be changed to "Switch importance" and "Switch layout" respectively.

Honestly, I don't understand the plural of "items": there is no way to select more than one feed, is there? 
Unless they are within the same folder, but even so, it seem to me rather confusing than not.

**Comment by sakkamade** [comment]
I believe I furnished you with too many options...

If you want me to express nothing but my bare opinion, just ask me.

**Comment by martinrotter** [comment]
>     * "Mark all feeds as unread"
>       (I am strongly opposite leaving the "Item" as is; the actual meaning of the word is not followed in my opinion)

Well, thing is that user can select for example "label" or "recycle bin" and mark those read unread - in that case "mark (selected) feeds unread" is not entirely precise

**Comment by martinrotter** [comment]
OK, I must stabilize the vocabulary:
message -> article,
feed,
category (folder of feeds),
fetch feeds

etc

**Comment by martinrotter** [comment]
OK.

c598d6af

Please test latest dev. build when it compiles and let me know if it is better and if it is, i will go through rest of GUI and rewrite texts accordingly.

**Comment by sakkamade** [comment]
Why "categories" and not a "folders"?

**Comment by sakkamade** [comment]
And this was not addressed:

> Honestly, I don't understand the plural of "items" 

Why not "item"?

**Comment by martinrotter** [comment]
fair enough, will use folder, it is better than categories, also i made a conclusion that for the FILESYSTEM folders, I will use "directory"

therefore folders of feeds -> FOLDERS, folders of files -> DIRECTORIES

**Comment by sakkamade** [comment]
Or you did not change every Toolbar action, only some, right?

**Comment by martinrotter** [comment]
yes, only some, but most of them got shortened, for example "as read" -> "read" etc

**Comment by sakkamade** [comment]
Yes, yes, okay.

Let me think.

**Comment by sakkamade** [comment]
So you hold for "items", right?

**Comment by martinrotter** [comment]
just launch the dev. build, it is compiled now.

as for items, some actions are not actually done over "feeds", they are done over "items" (in feed list) for example

"Show unread items only" (it show only rows in feed list which contain some unread articles, for example "folder" item will be shown and also "label" item if it contains unread articles etc)

**Comment by sakkamade** [comment]
I already compiled, and viewing. Worry not ♥

**Comment by sakkamade** [comment]
"Next unread article" should have arrow icon, I think.

And I decide...
I think "as" should ne left.

For example "Mark article as read"

**Comment by sakkamade** [comment]
"Clean all items" -> "Clean all"
"Clean selected items" -> "Clean selected"
"Delete selected article" -> "Delete article"
"Delete selected item" -> "Delete item"
etc.

**Comment by sakkamade** [comment]
I guess  "Expand/Collapse selected item" and  "Expand/Collapse selected item recursively" are mixed up.

**Comment by sakkamade** [comment]
"Fetch selected feeds"—plural again.

**Comment by sakkamade** [comment]
I wonder if this Issue should be transformed into Discussion?

**Comment by sakkamade** [comment]
Or you may write some Pull request and we continue there?

**Comment by martinrotter** [comment]
its okay i am making changes as we discuss

**Comment by sakkamade** [comment]
Alright then.

**Comment by sakkamade** [comment]
"Switch layout orientation": I really think that "Switch layout" will be sufficient.

"Show tree branches" -> "... expanders"

I wonder if "Delete" should be "Remove", since it does not actually deletes.

**Comment by sakkamade** [comment]
"Switch main window visibility" -> "Switch window visibility" 

"Delete selected account" -> "Delete account" (since it is inactive unless account is selected)

"Delete selected articles" -> "Remove selected articles"

**Comment by sakkamade** [comment]
"View fullscreen" to "Fullscreen" or "Fullscreen view"

"New web browser tab" -> "New browser tab" or "New tab"

I think this is all.

**Comment by sakkamade** [comment]
As for this one https://github.com/martinrotter/rssguard/issues/430#issuecomment-853598505 .

I trust the one with collapse only selected tree should be left, and named as "Expand/collapse selected" or just "Expand selected".

**Comment by sakkamade** [comment]
Maybe "Categories" to "Groups"?

**Comment by martinrotter** [comment]
no, alraedy changed to folders

**Comment by martinrotter** [comment]
wait for next commit

**Comment by sakkamade** [comment]
Will test that tomorrow.

**Comment by martinrotter** [comment]
@sakkamade f948152f

Feel free to test and report any problems right here.

One more thing: I am looking for someone to write wikipedia article about RSS Guard. Sadly, I cannot write it myself as it would be self-promotion. Would you be willing to contribute that way? Would have huge effect as RSS Guard could be subsequently added to wikipedia's comparison of feed readers.

You could use

https://en.wikipedia.org/wiki/Liferea
https://en.wikipedia.org/wiki/QuiteRSS

as inspiration. Only basic article with highlights of killer features would be nice. :)

**Comment by sakkamade** [comment]
> I cannot write it myself as it would be self-promotion

I understand that. ([relevant  article](https://en.wikipedia.org/wiki/Wikipedia:Wikipedia_is_not_about_YOU) if someone curious.)
> Would you be willing to contribute that way?

May as well, but it will be at the bottom in my to-do list.

> You could use ... as inspiration.

This is not the question of mere inspiration, there are whole lot of matters by which it can be rejected.
And the point that I have never even tried to do anything of the sort myself is not contributing the question.

**Comment by sakkamade** [comment]
> Feel free to test and report any problems right here.

Only the ones which I already have:


1. "New web browser tab" -> "New browser tab" or "New tab"
2. "Show tree branches" -> "... expanders"
3. I think "as" should be left.
For example "Mark article as read"
4. I guess "Expand/Collapse selected item" and "Expand/Collapse selected item recursively" are mixed up.
But I trust the one which collapses __only__ selected item (without its child folders) should be left, and named as "Expand/collapse selected item".
5. And superfluous plural of "items"  sometimes

However if you have decided that this way is better, I won't insist. Now it is much better either way.

**Comment by martinrotter** [comment]
>  For example "Mark article as read

Yes, well. I went through some e-mail clients and similar apps. Most of them does not use "as". Actually I did not find any other app which uses "as".

English language is not my mother tongue, not sure how correctly it should be but thinking about it now, removing "as" feels more natural for me.

4. They are not mixed up, i double checked. Also, I do not want to remove existing feature.

**Comment by martinrotter** [comment]
OK, I will close this and fix any remnant strings along the way, feel free to report.

**Comment by sakkamade** [comment]
> They are not mixed up

My bad, the word "recursion" has more decent definition for my understanding.
> English language is not my mother tongue

Neither am I a native English-speaker.

**Comment by sakkamade** [comment]
@martinrotter You have totally ignored (perhaps missed?) the plural...
I shall point it out again:
1. Mark selected **items** read
2. Mark selected **items** unread
3. View selected **items** in newspaper mode
4. Copy URLs of selected **items**


In every of these cases the "items" must be "item" because there is no way to select more than one item, wether it is folder, Labels, some feed, etc.

**Comment by martinrotter** [comment]
let me check

**Comment by sakkamade** [comment]
Please in case if so prolonged issue will appear again, such things should be discussed in PRs, or leastwise in Discussions, 
for it would be much easier not to miss something.

**Comment by martinrotter** [comment]
done btw

**Comment by sakkamade** [comment]
> should be discussed in PRs

Of course the PRs in this case should be most neat ones.

> done btw

Thank you ❤

**Comment by sakkamade** [comment]
Apropos this one:

> OK, I must stabilize the vocabulary: (...)

@martinrotter, 
You have missed the word "messages" in search field,
The word "messages" in the toolbar items such as "Message highlighter", "Message search box", "Message filter" and "Message viewer toolbars."

As well as in "Edit selected item":
![edit article](https://user-images.githubusercontent.com/62730422/122831944-262b2f80-d2da-11eb-96b2-1cb3b53ce226.png)

"Download messages using global "interval",
"Download messages every" and 
"Do not download messages at all".

**Comment by martinrotter** [comment]
fa311893
647789d3
ef0f98cb

If you find anything weird or improperly named, let me know.

**Comment by sakkamade** [comment]
Aw, so you decided on Download->Fetch transition everywhere. I thought it was left as "Download" deliberately.

> fa31189

https://github.com/martinrotter/rssguard/blob/fa311893572924dd536084f7fcf5b2e2b381ee5a/src/librssguard/services/abstract/gui/formfeeddetails.cpp#L119

Perhaps "Disable auto-fetching"

https://github.com/martinrotter/rssguard/blob/fa311893572924dd536084f7fcf5b2e2b381ee5a/src/librssguard/services/feedly/gui/feedlyaccountdetails.cpp#L44-L46

... when ... automagically, **permanently** (?) caches ALL articles of a feed ... end **up** with thousands of  articles **which** (this one is not so important) you will never ...

Or "Download many articles with caution ..." or "Beware of downloading ..."

https://github.com/martinrotter/rssguard/blob/fa311893572924dd536084f7fcf5b2e2b381ee5a/src/librssguard/services/greader/gui/greaderaccountdetails.cpp#L32-L35

Limiting **the** number ... **more** articles than ... (remove "then") some older ... **fetched** (?) at all.

**Comment by martinrotter** [comment]
d99ae404

**Comment by sakkamade** [comment]
https://github.com/martinrotter/rssguard/blob/d99ae40447373f797f25638ca06c2431ae245eac/src/librssguard/services/feedly/gui/feedlyaccountdetails.cpp#L45-L46

... caches ALL articles of the feed, (comma) so you might ...

"Forever" is need not, since there is already "permanently."

**Comment by sakkamade** [comment]
@martinrotter ping 

https://github.com/martinrotter/rssguard/issues/430#issuecomment-865695813 ^

and this:

> the "**Message** filter" as well.

**Comment by sakkamade** [comment]
And also in this tab of Settings is still left the whole bunch of "messages":

![mess mess](https://user-images.githubusercontent.com/62730422/123561943-00e76700-d79b-11eb-892c-96809fcb4710.png)

**Comment by martinrotter** [comment]
done

**Comment by sakkamade** [comment]
@martinrotter, There are still plenty of "messages" in the "Cleanup database" modal window.

**Comment by martinrotter** [comment]
done
