### ISSUE TITLE
[FR]: Display images of feed messages in nowebengine version

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#434]
#### Brief description of the feature request.

I would really like to use version without webengine but images.

Is it even possible?

**Comment by martinrotter** [comment]
Yea, this is like 3rd ticket asking for this.

At first you mean images of "message" not feed. Another question, do you mean literally *ALL** images found in message or just "enclosured" (attached) images?

**Comment by sakkamade** [comment]
> Yea, this is like 3rd ticket asking for this.

Well, I have seen only this https://github.com/martinrotter/rssguard/issues/205, and I have also seen that it came to certain conclusion.

> first you mean images of "message" not feed. 

I trust the title says "Display images of feed __messages__..."

> do you mean literally ALL* images found in message or just "enclosured" (attached) images?

No, not attachments.
Yes: all.

**Comment by martinrotter** [comment]
@sakkamade RSS/ATOM/JSON feed formats have several properties for each message:

- "content" - this is often piece of HTML code, formatted text etc. this content can display text or pictures (via HTML `img` tags)
- "attachments" - special list of hyperlinks leading to various external files, often video files - "podcasts"

https://www.w3schools.com/xml/rss_tag_enclosure.asp

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/121135329-af4f5a80-c834-11eb-881d-928ad26c60ae.png)

**Comment by sakkamade** [comment]
I cannot really answer as I have never seen the feed which would had `<enclosure  />` block.
So I guess only from the content.

**Comment by martinrotter** [comment]
> 
> 
> I cannot really answer as I have never seen the feed which would have `<enclosure />` block.
> So I guess only from the content.

Yes. Well. Thing is that in no-webengine version, "text" GUI component is used to display messages. While it can display pictures, thing is that RSS Guard would have to download all those pictures first in order to display them (webengine version's browser does that of course automatically).

**Comment by sakkamade** [comment]
Here is how that very article is shown in normal version and I see no images still.

![rss](https://user-images.githubusercontent.com/62730422/121136765-870c2f80-c825-11eb-97a6-a896e249575c.png)

But I understand that those are the "Attachments", and I could not care less about seeing them loaded.

---
> would have to download all those pictures first in order to display them (webengine version's browser does that of course automatically).

There is an option to turn it off in normal version, and something similar may be added in nowebengine version, no?

**Comment by sakkamade** [comment]
I mean, you care that someone will be bothered by seeing the space to be used excessively?
Or is is that it is not possible for them to be loaded automatically in nowebengine version?

**Comment by martinrotter** [comment]
"Auto-load images" is a feature from bundled web browser and feature is semi-automatic, no manual "downloading" etc is done in that version.

As for the "invisible" images in that specific "Kate Winslett" message - that is faulty feed which includes `<img>..` tags in its contents which lead to non-existing or actually invisible pictures. No idea why they do that.

To explain things how it actually works in RSS Guard:

* WEBENGINE version:
    1. RSS Guard downloads HTML code of message when feed is updated.
    2. HTML code is loaded into display component.
    3. Display component automatically downloads/shows all embedded messages, unless "auto-load images" is disabled.

* NO-WEBENGINE version:
    1. RSS Guard downloads HTML code of message when feed is updated.
    2. User selects message and RSS Guard now pre-processes HTML code (extracts hyperlinks to images from `<img>...` tags, prepends links to enclosures, etc.).
    3. NOT IMPLEMENTED: RSS Guard downloads all pictures. 
    4. Processed HTML code with pictures is loaded into text display component.

Text component itself is capable of displaying pictures but downlading them painlessly when messages are changed it not easy to do. I will thing about this.

**Comment by sakkamade** [comment]
I have as well checked that feed by the link from RSS Guard <<http://rss.cnn.com/rss/edition_world.rss>>, and strangely enough the whole its content made almost as regular web-page... Although I don't know RSS enough to blame them for it.

Regardless, thank you very much the for explanation.

**Comment by martinrotter** [comment]
RSS is just XML file. Feedburner just adds some stylesheets to make sure that if you open XML file in browser, it looks better. That's all.

Feedburner is known to provide very low quality XML code. For example:

```xml
    <item>
      <title><![CDATA[When the pandemic brought her business to a halt, this chef tackled food insecurity with farm-to-table meals]]></title>
      <description>Before the Covid-19 pandemic broke out, Chef Q. Ibraheem ran an upscale catering business and underground supper club in Evanston, Illinois. She was able to charge $250 per person for ambitious, farm-to-table, multicourse meals served in an intimate setting. After years of working to launch her business, it was finally taking off.&lt;img src="http://feeds.feedburner.com/~r/rss/edition_world/~4/BrMgKPWnfsA" height="1" width="1" alt=""/&gt;</description>
      <link>http://rss.cnn.com/~r/rss/edition_world/~3/BrMgKPWnfsA/index.html</link>
      <guid isPermaLink="false">https://www.cnn.com/2021/06/03/us/chicago-covid-food-healthy-meals-cnnheroes/index.html</guid>
      <pubDate>Thu, 03 Jun 2021 21:22:57 GMT</pubDate>
      <media:group>
        <media:content medium="image" url="https://cdn.cnn.com/cnnnext/dam/assets/210603150215-chicago-covid-food-healthy-meal-cnnheroes-00001611-super-169.png" height="619" width="1100" />
        <media:content medium="image" url="https://cdn.cnn.com/cnnnext/dam/assets/210603150215-chicago-covid-food-healthy-meal-cnnheroes-00001611-large-11.png" height="300" width="300" />
        <media:content medium="image" url="https://cdn.cnn.com/cnnnext/dam/assets/210603150215-chicago-covid-food-healthy-meal-cnnheroes-00001611-vertical-large-gallery.png" height="552" width="414" />
        <media:content medium="image" url="https://cdn.cnn.com/cnnnext/dam/assets/210603150215-chicago-covid-food-healthy-meal-cnnheroes-00001611-video-synd-2.png" height="480" width="640" />
        <media:content medium="image" url="https://cdn.cnn.com/cnnnext/dam/assets/210603150215-chicago-covid-food-healthy-meal-cnnheroes-00001611-live-video.png" height="324" width="576" />
        <media:content medium="image" url="https://cdn.cnn.com/cnnnext/dam/assets/210603150215-chicago-covid-food-healthy-meal-cnnheroes-00001611-t1-main.png" height="250" width="250" />
        <media:content medium="image" url="https://cdn.cnn.com/cnnnext/dam/assets/210603150215-chicago-covid-food-healthy-meal-cnnheroes-00001611-vertical-gallery.png" height="360" width="270" />
        <media:content medium="image" url="https://cdn.cnn.com/cnnnext/dam/assets/210603150215-chicago-covid-food-healthy-meal-cnnheroes-00001611-story-body.png" height="169" width="300" />
        <media:content medium="image" url="https://cdn.cnn.com/cnnnext/dam/assets/210603150215-chicago-covid-food-healthy-meal-cnnheroes-00001611-t1-main.png" height="250" width="250" />
        <media:content medium="image" url="https://cdn.cnn.com/cnnnext/dam/assets/210603150215-chicago-covid-food-healthy-meal-cnnheroes-00001611-assign.png" height="186" width="248" />
        <media:content medium="image" url="https://cdn.cnn.com/cnnnext/dam/assets/210603150215-chicago-covid-food-healthy-meal-cnnheroes-00001611-hp-video.png" height="144" width="256" />
      </media:group>
      <feedburner:origLink>https://www.cnn.com/2021/06/03/us/chicago-covid-food-healthy-meals-cnnheroes/index.html</feedburner:origLink>
    </item>
```

Content of the message above contains: `.&lt;img src="http://feeds.feedburner.com/~r/rss/edition_world/~4/BrMgKPWnfsA" height="1" width="1" alt=""/&gt;`.

IT CONTAINS 1x1 pixel big IMAGE. WHAT THE HELL. That is the "invisible" image we talked about earlier.

**Comment by sakkamade** [comment]
> Feedburner just adds some stylesheets to make sure that if you open XML file in browser,

Ah, so that was on purpose. Never seen such before.

> 1x1 pixel big IMAGE. WHAT THE HELL. That is the "invisible" image we talked about earlier.

Indeed...

**Comment by sakkamade** [comment]
Still, going back to the topic, 
> do you mean literally ALL* images found in message or just "enclosured" (attached) images?

 I fail to understand why have you asked that in the first place.
Since the attachments are never actually displayed, why would I want them to be displayed only in the nowebengine version? 

Sorry, but I cannot quite seem to discover explanation to that.

**Comment by martinrotter** [comment]
nevermind

**Comment by sakkamade** [comment]
> EDIT: It looks fine on my latest firefox, just like in chromium.

Huff... Seems I still did not resolve all the problems with old profile from Windows...

**Comment by sakkamade** [comment]
Just asking whether you made any progress so far?

It is of no benefit to me now, as I presently have a simplistic theme for webengine-version.

(At the time of opening it I did not even know there is themeing.)

**Comment by martinrotter** [comment]
No progress and for majority of non-webengine users it is probably redundant as they can already download and/or display those pictures by clicking on links.

Close it?
