### ISSUE TITLE
[BUG]: "Next unread article" + "Keep message selection in the middle"

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#435]
#### Brief description of the issue.

When the option "Keep message selection in the middle of the article list viewport" is enabled, choosing "Next unread article" producing eccentric and buggy behaviour.

#### How to reproduce the bug?
1. Enable "Keep message selection in the middle of the article list viewport"
2. Either click the action in toolbar or assigned key of "Next unread article"
    - Some bizarre flickering already reveal itself
3. Press Arrow Down
    - Observe how the highlight of the entry stay on top of the list while selected article is actually in the middle

#### What was the expected result?

As the action "Next unread article" is executed, and the "Keep message selection in the middle of the article list viewport" is enabled, selected article must adhere to the middle (or to the top as happy medium) of the list, and closer to top or bottom  upon demand, if entry in the list is at respective position. 

After "Next unread article" is executed, the highlight must duly move by Arrow keys. 

All in all, behaviour of aforementioned options should be concordant.

#### What actually happened?

https://user-images.githubusercontent.com/62730422/121789382-f9ce2f80-cbc4-11eb-8fbf-6bc3154b38ad.mp4

#### Other information

* OS: Arch Linux, KDE
* RSS Guard
Version: 4.0.0 (built on Linux/x86_64)
Revision: 21577df3
Build date: 10/06/2021 03:28
Qt: 5.15.2 (compiled against 5.15.2)

**Comment by martinrotter** [comment]
I commited hopeful fix, can you test after build compiles?

**Comment by sakkamade** [comment]
https://github.com/martinrotter/rssguard/issues/439#issuecomment-869579622

Hahaha. Sorry about that...

**Comment by martinrotter** [comment]
So are you saying it is wrong still? Is this with "Keep ... center..." enabled?

**Comment by martinrotter** [comment]
Here is my video: 
![iSftWQ4pQl](https://user-images.githubusercontent.com/1255302/123628415-59f2e180-d813-11eb-80d8-d2ff5379ff39.gif)

Looks pretty much OK. If I have centering enabled, selection tries to be at center, if not, then it sticks to the TOP (when using next/previous/unread message feature) to keep old behavior.

**Comment by sakkamade** [comment]
Here's another screencast, which hopefully will be more plain:

https://user-images.githubusercontent.com/62730422/123913744-1496f700-d96e-11eb-98bd-b11725efd4ae.mp4

And while I was at it, I noted another certain something: 

https://user-images.githubusercontent.com/62730422/123913826-32fcf280-d96e-11eb-9459-a35792f1b027.mp4

As you can observe, as I click "Next unread" the feed list has the same behaviour as articles list used to have. 
However, in this case, I should prefer that it befall no change whatsoever.

**Comment by martinrotter** [comment]
This must somehow be visible on Linux/KDE only. On windows behavior from videos does not happen.

I will test on Linux at home tonight probably.

**Comment by martinrotter** [comment]
does same behavior happen when you use "Select next article" instead of "Select next unread article"

**Comment by sakkamade** [comment]
> does same behavior happen when you use "Select next article" instead of "Select next unread article"

No.

**Comment by martinrotter** [comment]
So the only feature affected is NEXT UNREAD ARTICLE? Other similar features work fine?

**Comment by sakkamade** [comment]
> So the only feature affected is NEXT UNREAD ARTICLE? Other similar features work fine?

Yes, as far as I see it.

**Comment by martinrotter** [comment]
Just pushed 441070f4, test when it compiles and let me know pls.

BTW: I was unable to reproduce the issue on Linux/Arch/KDE.

**Comment by sakkamade** [comment]
> BTW: I was unable to reproduce the issue on Linux/Arch/KDE.

Oh, my god.

As I removed all the data from `config` and `local`, I am also unable to reproduce it...

Sorry... :cry:

**Comment by sakkamade** [comment]
@martinrotter 

This is where the problem was:
```
config.ini
---

...

[gui]

...

msg_view_state=AAAA/wAAAAAAAAABAAAAAQAAAAkBAAAAAAAAAAAAAAASu/0DAAAADwAAAAsAAABkAAAACgAAAGQAAAAFAAAAZAAAAAQAAABkAAAABwAAAGQAAAABAAAAIgAAAAAAAABkAAAAEQAAAGQAAAAQAAAAZAAAAAMAAABkAAAADQAAAGQAAAAMAAAAZAAAAA8AAABkAAAADgAAAGQAAAAIAAAAZAAAA5UAAAASAQEAAAAAAAABAAAABAAAAGQAAAAQAAAAgQAAAAAAAAASAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAJwAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAC4QAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAjQAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAD6AEAAABk

...

```

**Comment by sakkamade** [comment]
> Just pushed 441070f, test when it compiles and let me know pls.

No, even with this commit with that line `config.ini` it stays the same.
