### ISSUE TITLE
[FR]: Set a default filename when exporting feeds to OPML

### ISSUE THREAD

**Issue by guihkx** [martinrotter/rssguard#436]
#### Brief description of the feature request.

Hi! This is a small feature request: When exporting the feeds (**Accounts** > **name (RSS/ATOM/JSON)** > **Export feeds**), RSS Guard could set a default file name, e.g. `rssguard_feeds_YYYY_MM_DD.opml`. What do you think?

Thanks!

**Comment by martinrotter** [comment]
https://github.com/martinrotter/rssguard/commit/e100ffd5306a2563aae62ffb24f63a16121a8e83

**Comment by guihkx** [comment]
Thank you for the quick implementation!

**Comment by guihkx** [comment]
Unrelated: Could you always point the `devbuild` tag to the latest commit? That way the Development build stays at the top when you go to the Releases page. Thx!

**Comment by martinrotter** [comment]
> 
> 
> Unrelated: Could you always point the `devbuild` tag to the latest commit? That way the Development build stays at the top when you go to the Releases page. Thx!

That is actualy harder task than it looks.

**Comment by martinrotter** [comment]
But I will try.

**Comment by guihkx** [comment]
Yeah nevermind, I think you'd have to delete the Github release and re-add it everytime. Merely pointing the tag to the latest commit wouldn't work.

**Comment by martinrotter** [comment]
> 
> 
> Yeah nevermind, I think you'd have to delete the Github release and re-add it everytime. Merely pointing the tag to the latest commit wouldn't work, IIRC.

It's done, should now point to latest commit.

**Comment by guihkx** [comment]
Thanks! It actually worked :D

**Comment by guihkx** [comment]
Though I noticed that artifacts get removed even if the CI fails, is there a way to avoid that? 🤔

**Comment by martinrotter** [comment]
done

**Comment by guihkx** [comment]
Thank you again!
