### ISSUE TITLE
[FR]: Unread messages counter in taskbar (not tray icon)

### ISSUE THREAD

**Issue by pfactum** [martinrotter/rssguard#437]
Ahoj.

In KDE (_dunno about other DEs, probably they support this feature as well_) it is possible for an application to put some badge over the application icon in the task bar (_not systray, but task manager area_). For instance, this is what it looks like with KMail:

![image](https://user-images.githubusercontent.com/122887/122740039-e0437c80-d283-11eb-8fe6-c0d09f4bf636.png)

Here, "2" is an amount of unread messages.

To my knowledge, this is a Qt feature, actually.

Could it be implemented for RSS Guard as well so that the application entry in the task bar shows the amount of unread messages? Having this implemented would be pretty handy, and this would allow disabling systray icon so that there would be less duplicated icons on the panel and hence less visual noise.

Or, if this is already implemented, please let me know where to look for this option.

Díky.

P.S. RSS Guard is awesome.

**Comment by martinrotter** [comment]
Not sure what you want, but RSS Guard already displays number of total unread messages in **tray** icon.

![image](https://user-images.githubusercontent.com/1255302/122743732-8d6bc400-d287-11eb-8386-886621242165.png)
![image](https://user-images.githubusercontent.com/1255302/122743790-9eb4d080-d287-11eb-982f-0a5cff6aef8a.png)

**Comment by martinrotter** [comment]
Oh, you mean TASK bar, not TRAY area. In other words you want this feature to be available even if tray icon is disabled. Let me investigate.

**Comment by pfactum** [comment]
Yes :). Thanks!

**Comment by pfactum** [comment]
I think this is how it is implemented in KMail:

https://invent.kde.org/pim/kmail/-/blob/master/src/unityservicemanager.cpp#L138

**Comment by pfactum** [comment]
I don't know, unfortunately, as I'm no waylandized (_yet­_).

But if needed I can try to boot KDE Neon ISO (_if it supports Wayland, of course_) and issue the following command:

```
$ gdbus emit --session --object-path /org/kmail2/UnityLauncher --signal com.canonical.Unity.LauncherEntry.Update "application://com.github.rssguard.desktop" "{'count-visible': <true>, 'count': <42>}"
```

With this command and X11 I can get the app icon with "42" badge on it in the task bar.

**Comment by martinrotter** [comment]
@pfactum I was literally trying to figure out correct `gdbus` command and just couldn't. Thanks

**Comment by martinrotter** [comment]
@pfactum This is maybe dumb question, but "/org/kmail2/UnityLauncher" does not actually really have anything to do with "Kmail" (email client)? Because I do not even have it installed.

Also, will this dbus call work on Gnome?

**Comment by martinrotter** [comment]
It seem that object path is completely redundant in this case.

**Comment by martinrotter** [comment]
OK, it crashes, I will test at home on my linux machine and implement.

**Comment by pfactum** [comment]
> It seem that object path is completely redundant in this case.

Yes, seems so, but the `gdbus` command requires it, and I had no idea what to put there.

> Also, will this dbus call work on Gnome?

It probably should, but TBH I have never used Gnome.

> OK, it crashes, I will test at home on my linux machine and implement.

Thanks for looking into this!

**Comment by martinrotter** [comment]
OK, you can test in latest development build via AppImage.

https://github.com/martinrotter/rssguard/releases/download/devbuild/rssguard-devbuild-61030b7c-nowebengine-linux64.AppImage

I will polish the feature and make it work better and switchable evening.

![image](https://user-images.githubusercontent.com/1255302/122758836-8e0d5600-d299-11eb-992c-f7f14bb9c116.png)

**Comment by pfactum** [comment]
![image](https://user-images.githubusercontent.com/122887/122761158-37ede200-d29c-11eb-93aa-a725b74f5a32.png)

Seems to work. Thank you!

**Comment by martinrotter** [comment]
OK, the implementation is deliberately simpler than the one of Kmail, hopefully it will work. Inform me if anything fails.

**Comment by sakkamade** [comment]
@martinrotter, 
The only minor issue which I have noticed is that if unread articles are already present on __first__ application startup then the badge won't show up, until  some feed(s) are fetched, either manually or by auto-fetch (both on-startup auto-fetch, and auto-fetch at intervals).

**Comment by martinrotter** [comment]
@sakkamade will check

**Comment by martinrotter** [comment]
> @martinrotter,
> The only minor issue which I have noticed is that if unread articles are already present on **first** application startup then the badge won't show up, until some feed(s) are fetched, either manually or by auto-fetch (both on-startup auto-fetch, and auto-fetch at intervals).

Also does this problem happen only if app is set to launch on distro startup?

**Comment by sakkamade** [comment]
> Also does this problem happen only if app is set to launch on distro startup?

If you mean `.desktop` file in `~/.config/autostart/` directory, then yes.

**Comment by sakkamade** [comment]
> does this problem happen only if app is set to launch on distro startup

No, even if it is not set on autostart. 
Every startup of application, until some feed was fetched.

**Comment by sakkamade** [comment]
I can reproduce it with almost default settings, except the icon in tray area was disabled.

**Comment by martinrotter** [comment]
yes, hopefully fixed, test latest devbuild

**Comment by sakkamade** [comment]
Works perfect!
