### ISSUE TITLE
[BUG]: inoreader login failed when used with VPN v2ray

### ISSUE THREAD

**Issue by Franklittleboy** [martinrotter/rssguard#441]
**Brief description of the issue.**
When I try to log in inoreader（and feedly）, I always fail to log in.

**How to reproduce the bug?**
Try to use Inoreader and test the login.
Network: I am in China, but I have used v2rayN to hook up the proxy, and I can log in to the inoreader webpage.

Login process: I have applied for app id and app key and re（picture1）, and when I click login in rssguard, the webpage jumps to the inoreader authorization page (picture 2), after clicking the authorization, it will jump to the prompt to close the window page (picture 3). But the software crystal surface prompts an unknown error(pic4).

**What was the expected result?**
For the login to report success.

**What actually happened?**
The login fails with the following message:
There is error. unknown error

Hope to reply，thanks a lot!

* OS:  win10 20H2 and macos big sur
* RSS Guard version:3.92 and 4.0
<img width="122" alt="pic1" src="https://user-images.githubusercontent.com/54013763/123372407-12234e80-d5b6-11eb-8ad8-7684bba09a3e.png">
<img width="699" alt="pic2" src="https://user-images.githubusercontent.com/54013763/123372766-c1602580-d5b6-11eb-81a6-c831c8807d91.png">

<img width="518" alt="pic3" src="https://user-images.githubusercontent.com/54013763/123372430-1d767a00-d5b6-11eb-8470-8069e50549cd.png">
<img width="122" alt="pic4" src="https://user-images.githubusercontent.com/54013763/123372435-1f403d80-d5b6-11eb-8dfb-75785fe7e5d4.png">

**Comment by martinrotter** [comment]
can you post here application debug log?

https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#generating-debug-log-file

**Comment by Franklittleboy** [comment]
['log.txt'](https://github.com/martinrotter/rssguard/files/6713947/log.txt)

thanks a lot

**Comment by martinrotter** [comment]
@Franklittleboy So you are behind some proxy? Do you have proxy configured somewhere in RSS Guard?

**Comment by Franklittleboy** [comment]
yes, I have not configured somewhere in RSS Guard, because I use the v2ray/VLESS, rss guard seems does not support it.
but I use the system proxy in rss guard.  is this ok?
<img width="503" alt="proxy" src="https://user-images.githubusercontent.com/54013763/123893761-90556b80-d98f-11eb-9923-85d9e119ef41.png">

**Comment by martinrotter** [comment]
1. I don't speak a word of Chinese so screenshots with Chinese characters does not really help.
2. I have no idea how V2ray works but I am sure that it somehow influences behavior of RSS Guard.

Please, wait 20 minutes and then try with latest development build and provide log again.
