### ISSUE TITLE
[my setup BUG]: TLS initialization failed

### ISSUE THREAD

**Issue by pipiscrew** [martinrotter/rssguard#442]
#### Brief description of the issue.
After new Windows installation,  RSSGuard cant parse the most of the feeds :( 

* **OS**: Win10
* **RSS Guard version**: 3.9.2 (tried with no.webengine and with)

![snap003](https://user-images.githubusercontent.com/3852762/123506876-17909f80-d66f-11eb-99cc-758def012c6e.png)

PFA error log, talking for 

`QSslSocket::connectToHostEncrypted: TLS initialization failed`

**Comment by pipiscrew** [comment]
installing VStudio2012, the problem solved. Possible needs also **older VC++ runtimes** than 2017 (?)

**Comment by martinrotter** [comment]
This problem is I believe already fixed in latest development build.
