### ISSUE TITLE
[BUG]: Feed with disabled auto-fetching updates at startup still, if "Download messages on startup" is enabled

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#444]
#### Brief description of the issue.

Feed which has "Disable auto-fetching of articles" enabled is fetched on startup if respective option is enabled.

#### How to reproduce the bug?
1. Enable "Download messages on application startup" option
2. Disable auto-fetching for certain feed
3. Restart application

#### What was the expected result?

I would expect that every sort of automatic fetching will be disabled for the feed in question.

#### What actually happened?

Feed is fetched automatically.

#### Other information

* OS: Arch Linux, KDE
* RSS Guard
Version: 4.0.0 (built on Linux/x86_64)
Revision: 505af2c9
Build date: 23/06/2021 20:32
Qt: 5.15.2 (compiled against 5.15.2)

**Comment by martinrotter** [comment]
Yes, at this point **all** feeds are processed on startup if checked. It makes sense to exclude feeds with auto-fetching disabled because fetching on startup is auto-fetching too. OK.

**Comment by pipiscrew** [comment]
in the past confused also with this ;) 

should be added also a **separate switch** enable/disable update

because as is now the user doesn't has the option :
auto update on startup, and have some disabled feeds.

**Comment by martinrotter** [comment]
there is similar ticket https://github.com/martinrotter/rssguard/issues/393

**Comment by sakkamade** [comment]
> should be added also a **separate switch** enable/disable update

I wonder. I think it does not make sense to let feed update at startup but not on certain time intervals.

**Comment by sakkamade** [comment]
Thank you! :heart:
