### ISSUE TITLE
[FR]: add auto-download setting to categories

### ISSUE THREAD

**Issue by pipiscrew** [martinrotter/rssguard#445]
Hi all,

when editing a category, should be an option to **batch** set the **auto-download** for the feeds included in this category.

![snap012](https://user-images.githubusercontent.com/3852762/123589076-5e0e0780-d7f1-11eb-93ed-f70c380b0df6.png)

so possible needed this **feed tab** to the **categories** as well.

![snap013](https://user-images.githubusercontent.com/3852762/123589098-65351580-d7f1-11eb-9bab-89a838fddb0e.png)

**Comment by martinrotter** [comment]
This is essentially a duplicate to #143 and https://github.com/martinrotter/rssguard/issues/89.
