### ISSUE TITLE
[FR]: Raw JSON (not JSON Feed) Parsing

### ISSUE THREAD

**Issue by ImportTaste** [martinrotter/rssguard#446]
RSS is sadly becoming more rare while JSON-based API is becoming more common. I've looked around, and I haven't yet come across a feed reader that can just read raw JSON. While this is already possible through the use of post-process scripts, being able to do it within the app would be a big improvement.

[**jq**](https://github.com/stedolan/jq) might be a good inclusion (Creative Commons license) for parsing the retrieved JSON data. It also has a lot of documentation on creating filters to extract specific parts of JSON data that could be used to define individual articles and their contents. While this would be another form of post-process scripting, it wouldn't have to rely on an external script file.

**Comment by martinrotter** [comment]
Hello @ImportTaste.

![image](https://user-images.githubusercontent.com/1255302/123741009-a25cde80-d8a9-11eb-90bc-69dbce000d65.png)

1. This defines how the data for the feed are obtained.
2. This defines how the obtained data are transformed.

You can completely avoid 2 and have the script download data and parse it in the same time.

For example from the example scrapers, you can test with one which uses NVidia JSON API to get information about latest driver releases.

![image](https://user-images.githubusercontent.com/1255302/123741316-1eefbd00-d8aa-11eb-8711-13f1959d0931.png)

1. It downloads very raw specific JSON data from the [API](https://www.nvidia.com/bin/nvidiaGDC/servlet/article.json?locale=en_US&region=us&type=both&tag=drivers&offset=0).
2. RSS Guard then automatically feeds the data via `stdin` to the "post-process" [script](https://github.com/martinrotter/rssguard/blob/version-4/resources/scripts/scrapers/nvidia-driver-articles.py).

This particular script is written in Python and it reads API JSON data with line `json_data = json.loads(sys.stdin.read())` and then processes it and outputs transformed JSON FEED data which can subsequently be read by RSS Guard.

Thing is you don't have to use Python to write your scripts. You can use any scripting or compiled language but Python is just quite suitable for these tasks. So basically.

1. You enter URL of your JSON API service to the "URL" field in RSS Guard.
2. RSS Guard downloads the data.
3. You write some script in your preferred scripting language (python, bash, powershell, ...) which parses the specific data and outpus either JSON feed or ATOM/RSS feed.
4. RSS Guard then automatically grabs this output and processes it just like any other feed.

If you are really not sure how to start, maybe provide me URL of your JSON API you want to scrape.

**Comment by martinrotter** [comment]
Also, I am converting this issue to discussion as it is really a discussion.
