### ISSUE TITLE
[BUG]: Double click on article fails to properly focus the external browser

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#447]
#### Brief description of the issue.

If I double click the article in the list, focus moves to external browser, yes, however immediately thereafter it returns back to RSS Guard.

#### How to reproduce the bug?
1. Double click article's entry
2. See strange things to happen

#### What was the expected result?

RSS Guard should properly move the focus.

#### What actually happened?

After double clicking the article, focus promptly returns to the RSS Guard.

#### Other information

I wonder if it has something to do with KDE, again.

The behaviour is present with Firefox as well as with Chromium. 
However, if I set custom external browser to some executable `.AppImage` file (neither `/usr/lib/firefox/firefox` worked, too), focus shifts just fine. 

* OS: Arch Linux, KDE
* RSS Guard
Version: 4.0.0 (built on Linux/x86_64)
Revision: 22c24fe9
Build date: 28/06/2021 10:37
Qt: 5.15.2 (compiled against 5.15.2)

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/123740782-45f9bf00-d8a9-11eb-8e54-108631c88f97.png)

**Comment by sakkamade** [comment]
Still, to me it totally looks like a bug.
Perhaps it's better to remove it from the default settings?

**Comment by martinrotter** [comment]
Bug?

The behavior is switchable. If you uncheck the checkbox then it works the way you want, yes?

**Comment by sakkamade** [comment]
Yes, it is. I say that it _looks_ like a bug, and wouldn't it be better to have it disabled by default?

As I would have never guessed that it was an intended behaviour 😃

**Comment by martinrotter** [comment]
done ddf12ddf

**Comment by sakkamade** [comment]
@martinrotter,
 I wonder if _this_ is the way it should be worded in changelog, 

https://github.com/martinrotter/rssguard/blob/3ff01ff4cd4a5bbd13ab301b573e2f2db0a6d6b4/resources/text/CHANGELOG#L59

there was no issue with this, in the end. 

It should rather say:

```
* "Bring application window to front once article is opened in external web browser" is now disabled by default. (#447) 
```

**Comment by martinrotter** [comment]
@sakkamade Yes, I am known to be idiot when writing documentation, changelogs, release statements etc.

**Comment by sakkamade** [comment]
Don't be so hard on yourself... :heart:
