### ISSUE TITLE
[BUG]: Fail to fetch feed if URL field contains a paragraph break

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#450]
#### Brief description of the issue.

If the URL field in "Add new feed" modal window contains paragraph break the feed fails to fetch.

With preceding paragraph break: `Network error: protocol error`.
With subsequent paragraph break: `Network error: content not found`.

#### How to reproduce the bug?
1. Add the link of the feed into URL field of "Add new feed" window
2. Tap <kbd>Enter</kbd> there
3. Click "Fetch it now"
4. Observe error

#### What was the expected result?

The paragraph breaks to be automatically stripped.

#### What actually happened?

The error :heart:

#### Other information

* OS: Arch Linux, KDE
* RSS Guard
Version: 4.0.0 (built on Linux/x86_64)
Revision: ddf12ddf
Build date: 30/06/2021 07:02
Qt: 5.15.2 (compiled against 5.15.2)

**Comment by martinrotter** [comment]
I will sanitize every URLs passed to RSS Guard's network subsystem.

**Comment by martinrotter** [comment]
done - b0a11288
