### ISSUE TITLE
[FR]: Remember last used options in "Cleanup database"

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#452]
#### Brief description of the feature request.

I would like to see last used options in "Cleanup database" being remembered. 
It should be very convenient.

For example, I always use only two options: "Remove all messages from Recycle bin" and "Shrink database file". Thence, I should uncheck "Remove all messages older than" every time. Others may have their preference, to which this feature might also be useful.

**Comment by rfkat** [comment]
Similar "forgetfulness" also in "Backup database/settings". A generic solution for remembering previous settings everywhere would be most welcome.

**Comment by martinrotter** [comment]
88c75da5

Added generic solution - so far activated for "cleanup DB" and "backup" dialogs.

**Comment by sakkamade** [comment]
Works perfect! Thank you.
