### ISSUE TITLE
[BUG]: Bouncing sorting of articles when feed is fetched by shortcut

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#453]
#### Brief description of the issue.

If the feed is being fetched by shortcut (seemingly only if shortcut comprise <kbd>Ctrl</kbd>) the order of articles in list is changing.

#### How to reproduce the bug?
   1. Fetch the feed couple of times **by shortcut** (default is `Ctrl+U`)
   3. See articles jumping about

#### What was the expected result?

The sorting to stay unchanged.

#### What actually happened?

It just skipping...

#### Other information

* OS: Arch Linux, KDE
* RSS Guard
Version: 4.0.0 (built on Linux/x86_64)
Revision: 68be51b9
Build date: 27/07/2021 03:02
Qt: 5.15.2 (compiled against 5.15.2)

**Comment by martinrotter** [comment]
i was able to reproduce, no i am not, wtf :D

**Comment by sakkamade** [comment]
> i was able to reproduce, no i am not, wtf :D

Well, I am not sure myself; mostly it happens, but occasionally it is not.

**Comment by martinrotter** [comment]
"30+ times" - that's no load. I am quite sure that they have the feed file cached server-side. Every sane webserver does.

**Comment by sakkamade** [comment]
From what I see, the list's order must be changed before the fetch. 
Upon pressing `Ctrl+U` the order seem to return to the previous set. Although I am not so sure.

> "30+ times" - that's no load. I am quite sure that they have the feed file cached server-side. Every sane webserver does.

Yeah, I am joking :heart:

**Comment by martinrotter** [comment]
@sakkamade Did more testing. Interestingly, if you hit your `CTRL+` combo fast (quickly release the keys) the bug does not happen. If you, however, keep `CTRL` pressed for longer time (still pressed for a while after feed is updated) then the bug will trigger.

**Comment by martinrotter** [comment]
@sakkamade OK, found the issue. Holding down `CTRL` while "sorting" articles triggers multi-column sorting feature. In this case this is obviously unwanted. I will fix.

**Comment by martinrotter** [comment]
OK, it should now be fixed. Test and let me know.

**Comment by sakkamade** [comment]
Appeared to be fixed.
