### ISSUE TITLE
[BUG]: Function "Next unread article" is also moving the feed selection

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#459]
#### Brief description of the issue.

Upon calling "Next unread article" function, the feed in the feeds list is scrolling to the top, just as atricle in articles list.

#### How to reproduce the bug?
1. Feed list should be long enough (or widow small enough) for the feed list to have a scroll bar
2. Evoke function "Next unread article" by either shortcut or toolbar button
3. Observe entry of the feeds list adhere to (or moving closer to) the top

#### What was the expected result?

Feed in feeds list would remain motionless.

#### What actually happened?

Feed in feeds list is moving to top exactly as article in the list of articles.

#### Other information

https://user-images.githubusercontent.com/62730422/123913826-32fcf280-d96e-11eb-9459-a35792f1b027.mp4

(I explain because it may be confusing: I have "Keep article selection in the middle" enabled, so in video article selection is not moving to top, what is expected.)

* OS: Arch Linux, KDE, Xfce
* RSS Guard
Version: 4.0.0 (built on Linux/x86_64)
Revision: 53f78fb3
Build date: 04/08/2021 22:22
Qt: 5.15.2 (compiled against 5.15.2)

**Comment by martinrotter** [comment]
"Next unread article" works **across** all feeds. If you trigger the action and there is no "next" unread article in current feed, then next feed with unread articles is selected and then the article is selected inside that feed.

**Comment by martinrotter** [comment]
EDIT: Oh you mean just the aesthetics of feed list scrolling when running the action.

**Comment by sakkamade** [comment]
> feed list scrolling when running the action

Yes, sorry, I hoped the screencast would speak for me. 
I'll fix it.

**Comment by martinrotter** [comment]
should be fixed

**Comment by sakkamade** [comment]
> should be fixed

It is! Thank you :heart:
