### ISSUE TITLE
[FR]: Emphasise the articles which were fetched automatically

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#460]
#### Brief description of the feature request.

I would love to suggest a feature which is very interesting and used to be helpful to me in Akregator.
I will elaborate on some points slightly: 
1. If articles are fetched automatically, they should be emphasised in some way. 
   I propose them to be in _**bold italics**_, however Akgerator uses red font colour.
2. When the article which has already been fetched automatically is fetched  manually by user (not feed but _article_), it should regain its mere **bold** (or green, in Akregator) state.

EDIT: Forgot the most important...

3. ~~Upon application restart all _**bold italics**_ should become just **bold**, too.~~ <ins>I guess it is included in `#4`</ins>
4. If application has been \*focused\* (not just minimised) with _**bold italics**_ articles present (not a separate feed with such articles, the application itself should be enough), next auto-fetching should likewise turn these articles **bold**. 
  (This one seem to me to be most difficult to implement.)

As for the reason behind, in my opinion, importance of this feature, it will help to distinguish newly added articles, when unread articles are already present in list. 
I.e. I don't have a time to read these articles through now, although would like to run over them later, and just keep focusing the application from time to time to see new updates.

**Comment by martinrotter** [comment]
> When the article which has already been fetched automatically is fetched manually by user (not feed but article), it should regain its mere bold

In RSS Guard, once article is already fetched in RSS Guard's DB, it is not ever overwritten, unles it is really updated (contents/title change etc.).

I understand the goal you would like to achieve but the way it should work is not that easily implementable. I will think about this.

**Comment by sakkamade** [comment]
> In RSS Guard, once article is already fetched in RSS Guard's DB, it is not ever overwritten, ...

How then the "read" and the "unread" states are being saved?

> the way it should work is not that easily implementable

Well, naturally.
>  I will think about this.

Thank you ❤️

**Comment by martinrotter** [comment]
Local state changes are of course saved into DB, also remotely done state changes in article are propagated to DB. There is very complex set of conditions to be met so that article is overwritten in DB.

https://github.com/martinrotter/rssguard/blob/master/src/librssguard/database/databasequeries.cpp#L1255

**Comment by sakkamade** [comment]
> Local state changes are of course saved into DB, also remotely done state changes in article are propagated to DB

Then why another state cannot be added?

**Comment by sakkamade** [comment]
As a fair alternative, I may also suggest highlighting the feeds instead—the feeds which were fetched both automatically and manually, however emphasise them with italic until user enters them (or their folder/category, or the account with them).

**Comment by sakkamade** [comment]
> Something like blue highlight now

Aw, that is not "something like", that is "just like" blue highlight now. I have forgotten how it works.

Anyway, I am closing it, as it seems to be too much effort for too little gain.
