### ISSUE TITLE
[BUG]: Your 9 August dev version is stuck...

### ISSUE THREAD

**Issue by umbellipher** [martinrotter/rssguard#464]
... and needs attention! 
![Screenshot - 09_08_2021 , 17_03_25](https://user-images.githubusercontent.com/59395777/128728410-a5fa9522-704d-49a7-be6d-a40879cb8a98.png)

**Comment by sakkamade** [comment]
Although it builds just fine for me.

**Comment by martinrotter** [comment]
yes, there are some problems in github upstream

https://github.com/softprops/action-gh-release/issues/142

probably fixed
