### ISSUE TITLE
[FR]: Filtering (not just sorting) for "read" and "important" - make those filters NOT exclusive but rather inclusive - checkbox style

### ISSUE THREAD

**Issue by rfkat** [martinrotter/rssguard#468]
### Brief description of the feature request

I'd like to see, e.g., all unread, important messages only, in the message pane.

I can achieve a similar effect by sorting columns in a fixed order, but that order is destroyed as soon as I re-order by a different column (e.g., switching between creation date, and author).

Even when new messages are highlighted, it is very tedious to scroll around after each re-sort, only to find the unread and important that are now "sprinkled" all over the list.

When I've read messages, there is no point for me in having them clutter the view, by default. Hence optional filtering - I wish to be able to filter by un/read, un/important.

**Comment by martinrotter** [comment]
@rfkat At this point there is not feature which offers just "filtering" e.g. via column context menu, BUT you can achieve almost same behavior with some other features:
1. There is main menu item "Articles -> Show unread articles only", which will apply the filter (persistently until switched off) for article list.
2. You can create label and use article filtering mechanism to assign all unread/starred messages to that label and then use the label to view the articles.

**Comment by martinrotter** [comment]
3. Also there are FEED LIST items "Important messages" and "Unread messages".
![image](https://user-images.githubusercontent.com/1255302/129512467-48153308-80bf-4a51-b4db-f901291a9165.png)

**Comment by rfkat** [comment]
Thx!

I'm already using 1. & 2. as workarounds. However, 3. does not seem to be available in 3.9.2, and your wording of the warning for downloaders of 4.0.0 is clear and unambiguous ;-) I'd switch to a reasonably stable 4.0.0 dev version, however the existing 3.9.2 database isn't migrated properly (accounts, filters, labels lost; no messages from existing database displayed) - so that's not an option, at the moment.

Still, RSS Guard is by far the best fit for my needs, I'll just wait for the 4.0.0 final to be released.

**Comment by martinrotter** [comment]
> 
> 
> Thx!
> 
> I'm already using 1. & 2. as workarounds. However, 3. does not seem to be available in 3.9.2, and your wording of the warning for downloaders of 4.0.0 is clear and unambiguous ;-) I'd switch to a reasonably stable 4.0.0 dev version, however the existing 3.9.2 database isn't migrated properly (accounts, filters, labels lost; no messages from existing database displayed) - so that's not an option, at the moment.
> 
> Still, RSS Guard is by far the best fit for my needs, I'll just wait for the 4.0.0 final to be released.

Yes, trust me, I had quite a time of deliberation regarding of DB migration. It is just very difficult. Some tables are completely replaced while some columns got removed/added during the transition etc.

It is just best to start from scratch for new major version. That's how I see it.

Dev. build now available will probably 100% stable as for compatibility. You can probably switch to it without any problems. I do not expect any non-backwards breakings anymore, just cosmetic changes, some bug-fixing.

**Comment by rfkat** [comment]
I don't mind starting over with respect to existing messages, as they come and go anyway...

If you ask people to manually re-create their existing labels and filters, your popularity might suffer a bit, though. ;-) Anyway, thanks for your responsiveness!

**Comment by martinrotter** [comment]
i believe this is now fixed

![image](https://user-images.githubusercontent.com/1255302/186897639-72ac987c-a881-4d51-af71-6b675ddcb9a8.png)

**Comment by rfkat** [comment]
I don't think so. The filter criteria are still mutually exclusive, it is impossible to select both "unread" and "important", so if I e.g. select "Show important artciles", I get to see all important articles that I've already read, too. The only workaround, as described above, is still sorting order changes via column headers.

**Comment by martinrotter** [comment]
so basically, if you were able to pick multiple filtering criteria out of that dropdown menu that would be desirable for you? for example to show "today" + "unread" articles? Therefore show only unread articles from today?

**Comment by rfkat** [comment]
Yes. The most common use case for me is: Important and unread articles only. In general, I'd welcome if the filters could be combined, checkbox-style.

**Comment by martinrotter** [comment]
i see

**Comment by rfkat** [comment]
Thanks!

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/216336816-c11a3153-617c-405d-9456-cb201ee9597e.png)

**Comment by martinrotter** [comment]
This is now fixed, I will do some minor polishing of feature but it is now inclusive, also persistent as per picture.
