### ISSUE TITLE
[BUG]: Column resizing is broken in dev builds

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#469]
### Brief description of the issue

Originally posted here https://github.com/martinrotter/rssguard/issues/465#issuecomment-899673560 by @rfkat

> What I mean is that I'm used to columns remembering their order and respective relative widths; the behavior right now is a bit unusual: I keep the internal browser window at the right border (not at the bottom), and when no message is shown, the columns of the message list just stay where they are, leaving a huge blank space where the internal browser view was.
>
> I'd expected the columns to fill that space, while preserving their relative widths. Same thing happens when I switch the layout so the browser view is at the bottom: the message list doesn't expand to fill the gap. I just checked v3.9.2, and in both cases, the message list exapnds to fill the gap.

First noticed here https://github.com/martinrotter/rssguard/issues/435#issuecomment-872071189

### How to reproduce the bug?

1. Change the width of columns in RSS Guard 3.9.2
2. Update to recent development build of upcoming 4.0.0

### What was the expected result?

Columns to resize together with massage list.

### What actually happened?

Columns in the message list are having a constant width.

### Operating system and version

* OS: Kubuntu 20.04, Arch Linux KDE
* RSS Guard version: Somewhere about here 22c24fe98888686a30ceddc295320699b8c6ec3b

**Comment by sakkamade** [comment]
Expected to be fixed with b81ac69.

**Comment by sakkamade** [comment]
Right, to return auto-reaizing back, user may try to remove this line in the config file:
https://github.com/martinrotter/rssguard/issues/435#issuecomment-872071189

**Comment by martinrotter** [comment]
> Right, to return auto-resizing back, user may try to remove this line in the config file:

Yes, but latest code should already work even without removing this line, but double restart of RSS Guard might be needed.

**Comment by rfkat** [comment]
@sakkamade Re your question [here](https://github.com/martinrotter/rssguard/issues/435#issuecomment-872071189),  I had this in my config.ini (_with_ quotation marks, as shown). `
msg_view_state="AAAA/wAAAAAAAAABAAAAAQAAAAkBAAAAEgAAAAAAAAABAAAAAgAAAAMAAAAEAAAABQAAAAcAAAAIAAAACQAAAAoAAAALAAAADAAAAA0AAAAOAAAADwAAABAAAAAGAAAAEQAAABIAAAAAAAAAAQAAAAIAAAADAAAABAAAAAUAAAAQAAAABgAAAAcAAAAIAAAACQAAAAoAAAALAAAADAAAAA0AAAAOAAAADwAAABEAAAASOdkBAAAACgAAAAMAAABkAAAADQAAAGQAAAAOAAAAZAAAAA8AAABkAAAACgAAAGQAAAALAAAAZAAAAAQAAABkAAAABQAAAGQAAAAHAAAAZAAAAAAAAABkAAAEpgAAABIBAQAAAAAAAAEAAAADAAAAZAAAABAAAACBAAAAAAAAABIAAAAAAAAAAQAAAAAAAAAlAAAAAQAAAAAAAAAeAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAACFAAAAAQAAAAAAAAKZAAAAAQAAAAAAAAAAAAAAAQAAAAAAAABtAAAAAQAAAAAAAACdAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAjAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAYAAAAAQAAAAAAAAPoAQAAAGQ="`

Deleting the line fixed the issue, i.e. the columns auto-resize again, correctly. I remember having re-arranged the columns a couple of times, within a few minutes, enabling & disabling a few of them in the process.

**Comment by martinrotter** [comment]
@rfkat Yes, but in newest development build, everything works OK, even if you keep the above line in your config (in which case you might have to double-restart RSS GUard)?

**Comment by rfkat** [comment]
@martinrotter Sorry, no executable in development builds right now, just source code.
