### ISSUE TITLE
Check for updates doesn't show correct info

### ISSUE THREAD

**Issue by blackarcher21** [martinrotter/rssguard#47]
#### Brief description of the issue.

Check for updates feature doesn't show correct info as now.

![rssguard_2016-08-03_22-26-49](https://cloud.githubusercontent.com/assets/15969210/17369220/0619fa16-59ca-11e6-9379-807fbb566414.png)

**Comment by martinrotter** [comment]
Note that the changelog contains changes from latest (not yet released) version, this is by design.

**Comment by blackarcher21** [comment]
still wrong info. seems you need to fix this before release new build :)

**Comment by martinrotter** [comment]
I always update the file with little delay.
