### ISSUE TITLE
[FR]: Remove rooster from being a default notification sound

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#471]
### Brief description of the feature request

You cannot imagine how confused I was when I heard it for the first time...  （。ˇ ⊖ˇ） 
(That was a few months ago, I remembered only now.)

P.s. Not to a "boing."
P.p.s. There is only a "sheep" left. Should I rename this issue, then? No. 
"Sheep" is fine, though.

**Comment by martinrotter** [comment]
WHY? I love that sound! You can use your custom sound and even have it placed in a portable user data folder.

**Comment by sakkamade** [comment]
> WHY? I love that sound!

Hahaha, so I thought.

>  You can use your custom sound (...)

The problem is not here, but that it is a *default* sound.

As an alternative, perhaps the notifications can be turned off by default?

**Comment by sakkamade** [comment]
> The problem is not here, but that it is a default sound.

I will elaborate: I had no idea that RSS Guard has its own notification sound, first hearing it I thought "Where the hell that came from?" 
And several times this sound was blocked by my music player, so there was the rooster was silent.

Only after a third or fourth time have I noticed that it was coming together with a notification...

I never use notifications, myself.

**Comment by martinrotter** [comment]
> Where the hell that came from?
I have laugh attack, sorry. 🤣 

Yes, I introduced notifications some weeks/months before for 4.0.0, by default notification for "new unread messages fetched" is on and some others are off.

The sound is a good thing as atleast it will force user to actually check where the configuration is and tweak it.

If you find nice free WAV sample to be used by default I have no trouble adding it.

https://freesound.org/browse/

**Comment by sakkamade** [comment]
> I have laugh attack, sorry.

I couldn't help it. I was utterly bewildered.

**Comment by sakkamade** [comment]
> If you find nice free WAV sample to be used by default I have no trouble adding it.

I didn't write it for nothing:

> P.p.s. There is only a "sheep" left. **Should I rename this issue, then? No.**

The problem is that it is The "rooster." 
I listened the "sheep" and it sounded much better.

**Comment by martinrotter** [comment]
OK, here you go. 111ecfe4

**Comment by sakkamade** [comment]
```diff
-                  QSL("%1/rooster.wav").arg(SOUNDS_BUILTIN_DIRECTORY)),
+                  QSL("%1/notify.wav").arg(SOUNDS_BUILTIN_DIRECTORY)),
```

I see you hate the "sheep".

**Comment by sakkamade** [comment]
Hmm, I would recommend something longer than "notify.wav"—it is too short and may be left unnoticed.

> If you find nice free WAV sample to be used by default I have no trouble adding it.
> https://freesound.org/browse/

I guess I'll look into it when I have a time.

**Comment by sakkamade** [comment]
You like it being exotic, I understand, so I decided to follow it.
I considerd quite a variety, from UFO to fire alarms, which seemed to me especially bad idea, then hallelujah, chime, etc. 

It took me a while, it's not the best, but I don't think there may be anything better than [this](https://freesound.org/people/unadamlar/sounds/341985/), [this](https://freesound.org/people/FunWithSound/sounds/456966/) or [this](https://freesound.org/people/tobyk/sounds/26198/).

**Comment by sakkamade** [comment]
By the way, if you didn't understand what was this:
> （。ˇ ⊖ˇ）

Well, it is an downcast, apologetic rooster, or so it appears to me. 
Like, （。ˇ ⊖ˇ）<sup>I'm sorry~</sup>, or something.

**Comment by martinrotter** [comment]
> （。ˇ ⊖ˇ）
Honestly I know it must be something very modern and cool. :D

I will add your samples you chose and will enhance related UI a bit with combobox instead of textbox, which will also auto-complete built-in sounds.

**Comment by sakkamade** [comment]
> Honestly I know it must be something very modern and cool. :D

Hum, never had I considered it such, indeed... I guess?

It just seemed to me quite obvious at first, but then I took a look at it again and found that it is not too much so.

> I will add your samples you chose and will enhance related UI

Not every of them! If you asking me, the first one is the best one: 
> [this](https://freesound.org/people/unadamlar/sounds/341985/)

> which will also auto-complete built-in sounds

Quite an unexpected conclusion you have reached here...

**Comment by martinrotter** [comment]
![rHUtdAfQTV](https://user-images.githubusercontent.com/1255302/130179178-cbbb502e-0f9a-4ecc-bc12-dd38dcc7e71b.gif)
