### ISSUE TITLE
Youtube thumbnail not showing up on article review (4.0.0) [BUG]: 

### ISSUE THREAD

**Issue by cocowash** [martinrotter/rssguard#473]
### Brief description of the issue

So far my experience of 4.0.0 is solid, but by some reason the images on youtube feeds are not displayed automatically (also the video description is missing), if the user press manually the button image/jpeg then it shows the thumbnail of the video.
Currently im using Reedah to handle my feeds, not sure if this feature is broken or not on other account types. 

### How to reproduce the bug?

1. load a youtube feed 
2. try to visualize the content

### What was the expected result?

On previous versions RSS guard displayed  the thumbnail and the video description

### What actually happened?

message appears blank

### Operating system and version

* OS: win 10
* RSS Guard version: 4.0.0 "rev-620aa208" build date 8/20/21 10:16 AM

**Comment by martinrotter** [comment]
lemme check

**Comment by martinrotter** [comment]
@cocowash please, share some URL of RSS feed which has the bug

**Comment by martinrotter** [comment]
Yes, I reproduced the regression and now I made the feature switchable as some users do not want to see attachments, but you want.

![image](https://user-images.githubusercontent.com/1255302/130396337-d2577485-75b9-4c5c-a47f-145d95cbf961.png)
![image](https://user-images.githubusercontent.com/1255302/130396354-3e252402-358a-4857-851d-3f87f799316b.png)

**Comment by cocowash** [comment]
hmmm, that option wasn't present on the build that I tried, anyway ty  very much for developing  Rss Guard, it works like a charm
