### ISSUE TITLE
Some files have bogus executable bit which breaks stripping

### ISSUE THREAD

**Issue by danfe** [martinrotter/rssguard#474]
Several files in the repository, like headers and icons, carry executable bit.  This causes `qmake` to try to strip them upon installation, which naturally fails.  At least the following files must be `chmod -x`:
 - src/librssguard/services/abstract/gui/authenticationdetails.h
 - src/librssguard/services/abstract/importantnode.h
 - src/librssguard/services/abstract/label.h
 - src/librssguard/services/abstract/labelsnode.h
 - resources/graphics/rssguard.png

There are more, but these actually affect the build.  Depending on the settings, it could be just warnings or fatal errors (see #183).  Ideally, _all_ source files, headers, resources, etc. should be stored as plain files without executable bit set.

**Comment by martinrotter** [comment]
@danfe Well, it does not "naturally" fail, as you can see [here](https://github.com/martinrotter/rssguard/actions). So, practically speaking, file permissions are not really a problem. I had never had `make` or `qmake` failures because of file permissions and I did compile `rssguard` for thousands times

I have specific opinion about storing file permissions (executable bits) in source code repositories. It's just nonsense as it is very very very fragile and is known to be very problematic in x-platform repositories. Therefore I am not willing to address the issue unless it really affects practically some builds for some Linux distribution packaging infrastructure etc. Even "Github actions" compile the repository just fine (Ubuntu, Mac OS X, Windows).

**Comment by danfe** [comment]
> I have specific opinion about storing file permissions (executable bits) in source code repositories. It's just nonsense

I very much agree, it is nonsense. :-)  I think you misunderstood me.  I'm not advocating for permission management in the repos, I'm pointing out that right now, in this very repo, executable bits are _already wrongly applied_ to files which are inherently non-executable, e.g.:
```shell
$ git ls-tree HEAD resources/graphics/rssguard.png 
100755 blob ac35cca0ed6c03e61a735efd70f26e474f5fd614    resources/graphics/rssguard.png
```
Maybe the `find(1)` command would be more elaborate, invoked in the freshly cloned repo:
```shell
$ find src/librssguard/services/abstract -type f -perm -1
src/librssguard/services/abstract/feed.cpp
src/librssguard/services/abstract/gui/authenticationdetails.cpp
src/librssguard/services/abstract/gui/authenticationdetails.h
src/librssguard/services/abstract/gui/authenticationdetails.ui
src/librssguard/services/abstract/importantnode.cpp
src/librssguard/services/abstract/importantnode.h
src/librssguard/services/abstract/label.cpp
src/librssguard/services/abstract/label.h
src/librssguard/services/abstract/labelsnode.cpp
src/librssguard/services/abstract/labelsnode.h
src/librssguard/services/abstract/unreadnode.cpp
src/librssguard/services/abstract/unreadnode.h
```
See this [SO question](https://stackoverflow.com/questions/10516201/updating-and-committing-only-a-files-permissions-using-git-version-control) for more information.

> So, practically speaking, file permissions are not really a problem.

I guess it depends on one's definition of a problem, and as I've said, it does not necessarily lead to a build error.  Note, however, that `qmake` will try to strip the file upon installation if it has executable bit set, per this code in the `qmake/generators/makefile.cpp` file:
```c++
    if (is_target || (!fi.isDir() && fi.isExecutable()))
        cmd = QLatin1String("$(QINSTALL_PROGRAM)");
    else
        cmd = QLatin1String("$(QINSTALL)");
```
I guess you already know what `$(QINSTALL_PROGRAM)` expands to.  Even if GitHub actions/etc. are not getting upset by this in your particular case, attempting to strip icons and header files is wrong and, at the very least, looks bad in the build logs:
```
[...]
/usr/local/lib/qt5/bin/qmake -install qinstall -exe .../resources/graphics/rssguard.png ...
strip: file format not recognized
*** Error code 1 (ignored)
```

**Comment by martinrotter** [comment]
OK, fair enough. I tried to fix executable bits for all files and now only trully "executable" files should have them.

**Comment by danfe** [comment]
Thank you, much appreciated!

**Comment by martinrotter** [comment]
https://www.freshports.org/net/rssguard

Nice, you even have WebEngine in BSD, nice.

**Comment by danfe** [comment]
Well, if course we do, why wouldn't we.  But what's even nicer (and kudos to you for that) is that I can build the program without it!  I've been looking on and off for a standalone, desktop RSS reader, and all those typically recommended ones all have a hard dependency on WebKit or WebEngine.  Your program does not, and this makes it awesome. :-)
