### ISSUE TITLE
Is #include <QtConcurrent/QtConcurrentRun> really needed?

### ISSUE THREAD

**Issue by danfe** [martinrotter/rssguard#475]
Several files do `#include <QtConcurrent/QtConcurrentRun>` while I see no `QT *= concurrent` in the `pri/*.pri` files, so looks like it's unused, yet the build is broken without it (due to `#include`).  Could you clarify?

**Comment by martinrotter** [comment]
> while I see no `QT *= concurrent`

"concurrent" is not a Qt module, but is simply a `C++` namespace and is part of QtBase library, therefore `QT *= concurrent` is not even valid "qmake" code.

I removed those includes and it builds as those methods are not really used anywhere. I expect there is many redundant includes as I have not found any tool to manage them efficiently.

**Comment by danfe** [comment]
Fixed in af2b433.
> "concurrent" is not a Qt module, but is simply a C++ namespace and is part of QtBase library

What I was meant to say is that the program does not link against `libQt5Concurrent.so.5`.
