### ISSUE TITLE
[FR]: Already read articles are shown as new after fetch (4.0.0)

### ISSUE THREAD

**Issue by cocowash** [martinrotter/rssguard#478]
### Brief description of the issue

On standard online accounts I'm experiencing that already read articles pop-up after I sync my feeds. 
[take for example https://tecnologeria.com/3alcubo] keeps showing me like 33 old articles as if they were new.
[on the past I had this issue also with my Reedah account, but it wasn't as consistent as now]
 

### How to reproduce the bug?

1. find a faulty feed 
2. sync and mark all the articles as read 
3. sync again

### What was the expected result?

already read articles should not be marked as new

### What actually happened?

some old articles are marked as new

### Operating system and version

* OS: win 10
* RSS Guard version: 4.0.0 ( build "45ee6909")

**Comment by sakkamade** [comment]
Duly verify if the content of the feed is being changed. 
Probably related https://github.com/martinrotter/rssguard/issues/451#issuecomment-887233279.

**Comment by cocowash** [comment]
At the moment I don't see any clue that let me think that the articles that I'm getting as new had a recent update by their creator. Maybe the source of the problem could be related to issue #451, as you said.

**Comment by sakkamade** [comment]
> Maybe the source of the problem could be related to issue #451, as you said.

No, not to that whole issue; read from [this very comment](https://github.com/martinrotter/rssguard/issues/451#issuecomment-887233279) on. May also from this https://github.com/martinrotter/rssguard/issues/451#issuecomment-887192609 (the `#1`).

**Comment by martinrotter** [comment]
Wow, what a nice rendez-vous you have here.

**Comment by martinrotter** [comment]
@cocowash OK, I did some testing and indeed, the feed is faulty and its creators are guilty of one of the most horrific felonies on the planet - HTML entity formatting.

What's more their formatting is inconsistent as they format the same string `mailto:` differently EACH TIME feed file is served to RSS aggregator.

![image](https://user-images.githubusercontent.com/1255302/131293968-454557f9-c176-43ee-a2bb-67c2dab2b38a.png)

Therefore, RSS Guard is not at fault here - feed file is. Ask its creator to fix their shit.

OR - I could add a setting to ignore changes in message contents, feed-specific or application-wide.

**Comment by cocowash** [comment]
Ty for the reply, @martinrotter I will mail them so they fix its feed. then I will change status from bug to feature request.
In the past I used to have a filter to reject already read articles, but if you implement it as a setting then I would use that instead.
