### ISSUE TITLE
[BUG]: Build fails with Qt 5.12

### ISSUE THREAD

**Issue by lgbaldoni** [martinrotter/rssguard#482]
### Brief description of the issue

QPainterPath::clear() was introduced in Qt 5.13

### How to reproduce the bug?

Try building a rpm for openSUSE_Leap_15.3, that uses Qt 5.12.7, see attached [log snippet](https://github.com/martinrotter/rssguard/files/7105256/rssguard-400.txt) for details.

### What was the expected result?

A successful build.

### What actually happened?

`error: 'class QPainterPath' has no member named 'clear'`

### Operating system and version

* OS: openSUSE Leap 15.3
* RSS Guard version: 4.0.0

**Comment by martinrotter** [comment]
@lgbaldoni Pushed fix, can you test the fix?

a54efa225

**Comment by lgbaldoni** [comment]
> Pushed fix, can you test the fix?

Works, but there's [more](https://github.com/martinrotter/rssguard/files/7105424/rssguard-400_2.txt) now. :disappointed:

**Comment by martinrotter** [comment]
@lgbaldoni No problem, fixed?

bc910d509

**Comment by lgbaldoni** [comment]
WFM, thanks.

**Comment by martinrotter** [comment]
ok, releasing 4.0.1
