### ISSUE TITLE
[BUG]: Account setup does not add scroll bar on high resolutions

### ISSUE THREAD

**Issue by fredddd1** [martinrotter/rssguard#483]
### Brief description of the issue

On high resolutions (3200x1800 in the example) the account setup window will not generate a scroll bar when the content goes off screen, disallowing for the setup to be finished.

![rssguard-high-resolution-account-setup](https://user-images.githubusercontent.com/80743272/132069029-d91c4fb7-894b-41f4-b435-a702d342e2a5.png)

### How to reproduce the bug?

1. Have a high resolution such as 3200x1800
2. Try to setup an Inoreader account

### What was the expected result?

For me to be able to scroll all the content.

### What actually happened?

There is no scroll bar, and content extends beyond the screen space.

### Operating system and version

* OS: Windows 21H1
* RSS Guard version: 4.0.1

**Comment by martinrotter** [comment]
I see, although it's weird isn't it? Usually when someone has high resolution, then dialogs tend to me visually smaller on screen. Am I wrong?

**Comment by martinrotter** [comment]
FOR ME: Use `LabelWithStatus` for these informative labels, for example use the long text "There are some preconfigured OAuth tokens...." as tooltip for "Redirect URL" label, which will now be `LabelWithStatus`. Also add "question" icon to label with status.

This will make some dialogs, particularly "Edit account" dialogs much smaller.

**Comment by fredddd1** [comment]
> I see, although it's weird isn't it? Usually when someone has high resolution, then dialogs tend to me visually smaller on screen. Am I wrong?

The operating system will compensate by increasing the DPI.

**Comment by martinrotter** [comment]
@fredddd1 I added a fix. All "help" texts are now hidden by default under "spoilers", thus, the dialog now can be much smaller. Can you test with latest development build in 20 minutes?

**Comment by fredddd1** [comment]
The issue still persists.

![windows-settings](https://user-images.githubusercontent.com/80743272/132248128-3ea82818-ca75-425a-96fb-86c149ddb635.png)

![rssguard](https://user-images.githubusercontent.com/80743272/132248096-dd8f4e81-3190-4d45-85fb-812947cf9956.png)

**Comment by martinrotter** [comment]
I see, I will have to really add scrollbar support, those dialogs are still too long.

**Comment by martinrotter** [comment]
@fredddd1 

OK, I made contents of those "edit" dialogs scrollable if needed.

8b7b57a2f

Wait until dev. build compiles and please test and report back, thanks.

**Comment by fredddd1** [comment]
Thanks for the fix.
