### ISSUE TITLE
[FR]: Add option to, or disable selecting messages by typing letters; Conflict with keyboard shortcuts

### ISSUE THREAD

**Issue by tonebacas** [martinrotter/rssguard#484]
### Brief description of the feature request

Having the ability to perform certain actions using keyboard shortcuts does not mesh well with the ability to select messages by typing in letters/words present in the title of an article -- there's already a search feature that lets the user filter messages based on the presence of certain letters/words.

When I press a key, I don't wish to accidentally scroll and select a different message from the one I was reading at the time. Instead, I wish the perform the action that key might have assigned to it.

**Comment by martinrotter** [comment]
@tonebacas 
I see. That seems like a valid request. Accepting. Will add this perhaps as option.

**Comment by martinrotter** [comment]
@tonebacas Now, can you write exactly which keyboard shortcuts/gestures are problematic?

**Comment by tonebacas** [comment]
When you click on any message and then press any alpha-numeric key that is not associated with a keyboard shortcut command, the view will scroll to and select the first message that starts with the character you typed. For example, if you press G, and it isn't used for any command, the first message which title starts with G will be selected. And this happens without using the search box.


In my particular case, I have the keys Q, W, E, R, A, and S associated to some commands, so as I use those keys, no unintentional scrolling/selecting with happen. However, I'd like to prevent any unintentional action from taking place by disabling the behavior I've described previously.

**Comment by martinrotter** [comment]
@tonebacas OK, what keys should be only allowed in "restricted" mode - only arrow keys + modifiers (CTRL/ALT/META)? Or some extra additional keys like PGDN/PGUP/DELETE/HOME?

**Comment by martinrotter** [comment]
fixed in latest dev. build, please test in 20 minutes

![image](https://user-images.githubusercontent.com/1255302/133228453-ccf512ad-34b2-46fa-9265-84261a8db20f.png)

**Comment by martinrotter** [comment]
if feature is enabled, only basic shortcuts will work like arrows, DELETE, etc. test and let me know

**Comment by tonebacas** [comment]
I'm sorry, but I could no test the change. I will wait for the next release build.

**Comment by martinrotter** [comment]
@tonebacas why, you can just download it the same way as release build
