### ISSUE TITLE
[FR]: Add delay between entering search terms and performing search

### ISSUE THREAD

**Issue by tonebacas** [martinrotter/rssguard#485]
### Brief description of the feature request

Currently, whenever the user types their search terms in the search box, a new search operation is performed for each keystroke. This slows down the search process, because more than likely the user is going to type in words with more than a single character.

For example, if the user were to search for the word "Suddenly", the search function would trigger 8 times, and would block the UI thread every time a new letter is typed in, and not respond to user input until the search is finished for the current term.

Ideally, the search operation should only be performed after a certain amount of time after the user stops typing, and furthermore, not block the UI thread while the search is being performed.

**Comment by martinrotter** [comment]
@tonebacas 

> would trigger 8 times, and would block the UI thread

It there a noticeably GUI freeze when performing search function?

**Comment by tonebacas** [comment]
When the database has many articles, yes, it's very noticeable.

**Comment by martinrotter** [comment]
@tonebacas How many articles?

**Comment by martinrotter** [comment]
Fixed - delay is set to 700 ms.

91356bcae

**Comment by sakkamade** [comment]
> Fixed - delay is set to 700 ms.

I really hate this delay. 
Not only does it slow down the display of search results greatly, it also does the same when the filter is begin cleared.

Perhaps 200ms will be enough?

> For example, if the user were to search for the word "Suddenly", the search function would trigger 8 times, and would block the UI thread every time a new letter is typed in, and not respond to user input until the search is finished for the current term.

Do you really have a performance drop using search? How many articles in list? 
And even if you do, it is usually only some 10-seconds task, I don't think it is worth the candle.

**Comment by martinrotter** [comment]
@sakkamade 

> it also does the same when the filter is begin cleared.

Fixing, RN.

> Perhaps 200ms will be enough?

Lowering the value to 300ms. Re-test after dev. build is done and report back, perhaps.

> Do you really have a performance drop using search? 

I just tested with 15 000 messages and yes, filtering can take even like 3 seconds to complete. Unftortunately, the filtering right now is done on main GUI thread thus temporary "freezing" could be seen. Rewriting it in a more efficient way will not be trivial but is doable.

15b00e5e2

**Comment by sakkamade** [comment]
> I just tested with 15 000 messages and yes, filtering can take even like 3 seconds to complete.

Well, I have also now tried with 16000+ articles on one of previous dev. build versions, and search is almost instant (although with some tiny UI-stutters indeed).

> Lowering the value to 300ms.

I am still thinking of some lower value :heart:

**Comment by martinrotter** [comment]
@sakkamade Perhaps I will make the delay configurable. On my Linux machine, the search i instant too. On my Windows machine, it is not that instant, but very usable.

**Comment by sakkamade** [comment]
> On my Windows machine, it is not that instant

God, I knew it! 

> Perhaps I will make the delay configurable.

No, it's will be weird. If 300ms looks best to you (on WIndows), so be it. 
It is much better than 700ms, anyhow.

Thank you.

**Comment by sakkamade** [comment]
@martinrotter, I am not sure what is the cause, but the Settings modal is broken for me now (Xfce), can you confirm if you are seeing the same?

![image](https://user-images.githubusercontent.com/62730422/133964044-3375c7dc-91b4-4053-8a2d-9d429577bf71.png)

**Comment by sakkamade** [comment]
This commit has no such issue 3bdcdc0c.

**Comment by martinrotter** [comment]
@sakkamade re-post your comment to https://github.com/martinrotter/rssguard/issues/493
