### ISSUE TITLE
Linking fails when version 3.9.2 is installed

### ISSUE THREAD

**Issue by danfe** [martinrotter/rssguard#486]
When building version 4.0.1 while version 3.9.2 is installed, linking fails, being unable to resolve `parseCmdArgumentsFromOtherInstance(const QString& message)` symbol.  Removing or renaming `/usr/local/lib/librssguard.so` helps, but the following small change to `src/rssguard/rssguard.pro` would make the build more robust:
```patch
-unix: LIBS += -L$$OUT_PWD/../librssguard/ -lrssguard
+unix: LIBS += $$OUT_PWD/../librssguard/librssguard.so
```

**Comment by martinrotter** [comment]
@danfe could you provide pull request with the change?

**Comment by martinrotter** [comment]
@danfe I checked the issue once more.

My usage of `LIBS` is correct. Problem is that you problem do not compile application in "fakeroot" clean environment and/ord you compile directly with `OUT_PWD` pointing to some "used" system location like `/usr/` or something like that.

`-L$$OUT_PWD/../librssguard/ -lrssguard` should expand exactly to `$$OUT_PWD/../librssguard/librssguard.so`.

**Comment by danfe** [comment]
> Problem is that you problem do not compile application in "fakeroot" clean environment

Well, that's right, the problem does not occur in the pristine environment, it occurs when version 3.9.2 is installed, system-wide, on the same machine one is trying to build version 4.0.1.

> -L$$OUT_PWD/../librssguard/ -lrssguard should expand exactly to $$OUT_PWD/../librssguard/librssguard.so.

Right.  The thing is that `-L/usr/local/lib` precedes `-L$$OUT_PWD` on the command line, so previously installed system-wide library would be picked up first.

**Comment by martinrotter** [comment]
> `-L/usr/local/lib` precedes `-L$$OUT_PWD` on the command line, so previously installed system-wide library would be picked up first.

How exactly do your "configure/make/make install" holy trinity commands look like?

**Comment by danfe** [comment]
Our (FreeBSD's) build framework does this for me, particularly, `qmake` logic lives [here](https://cgit.freebsd.org/ports/tree/Mk/Uses/qmake.mk).  Full build log (I'm sorry, it's IPv6 only), with all variables' values expanded, can be found [here](http://beefy6.nyi.freebsd.org/data/122amd64-default/a985fc1b4ec1/logs/rssguard-3.9.2.log) (it's for version 3.9.2 but the linking command is the same, search for "-o rssguard main.o" and you'll see the full command line).

**Comment by martinrotter** [comment]
https://github.com/martinrotter/rssguard/commit/5b6e01538411b8a25b9d7376a26001dd67ada857
