### ISSUE TITLE
[BUG]: Fetching messages; marking read messages as unread

### ISSUE THREAD

**Issue by tonebacas** [martinrotter/rssguard#487]
### Brief description of the issue

When fetching new messages for the following feed, messages which were marked as read are now marked as unread.

feed: https://www.gamingonlinux.com/article_rss.php

### How to reproduce the bug?

1. Launch RSS Guard.
2. Fetch messages for feed (https://www.gamingonlinux.com/article_rss.php)
3. Mark messages as read.
4. Fetch messages for same feed again.

### What was the expected result?

On step 4, I expected any new message to show as unread on the feed.

### What actually happened?

On step 4, messages which were previously marked as read are now marked as unread, along with any actual new message.

### Other information

I've experimented with database options `use DB transactions` and `use in-memory database`, restarting the application when needed. The result is the same regardless.

### Operating system and version

* OS: Windows 10
* RSS Guard version: 4.0.1

**Comment by martinrotter** [comment]
Will check. These kinds of errors are usually caused by problematic feed but I will check tomorrow and report back.

**Comment by tonebacas** [comment]
I checked the contents from the feed in two distinct instants, not 10 seconds apart, and there's a difference between an article's old and new 'fetch'. Some HTML content has unique ids that seem to be generated on the fly. This happens for a lot of articles, and presumably this could be the issue if you're determining the uniqueness of an article based on its contents.

![image](https://user-images.githubusercontent.com/26316700/132248146-b5314bc6-cb9c-4184-858e-41ca347f67fd.png)

**Comment by martinrotter** [comment]
@tonebacas You did investigation for me.

Indeed this is the culprit and source of problem. I can add switchable global option which would ingore changes made to "content" of article (not to date of postage, author, etc.) so that these "bad" messages would not be treated as "updated". What you think.

Other option is to write clever article filter in RSS Guard which will use some regexp magic and will replace those problematic parts of message.

You pick.

**Comment by tonebacas** [comment]
Curiously enough, this wasn't happening back in 3.9.2. I would assume now you're using a different strategy to determine if a message is considered new.

As much as I understand the logic behind comparing messages down to their content, I would say this could become problematic in the future if done to such extent. I can't gauge how many feeds use automatic HTML code generation like the one I provided, but webdev is unpredictable like that, and I would not be surprised if new variations of this problem arise.

Performing the comparison in terms of the other attributes besides content should suffice.

**Comment by martinrotter** [comment]
@tonebacas I agree. I will therefore add new global option "Do not take changes of article contents into account when updating the article" and will enable it by default - current behavior will not be affected and these problems will be solved.

**Comment by martinrotter** [comment]
@tonebacas OK, introduced the option in "Feeds/messages" settings dialog.

ceb88b3c2

![image](https://user-images.githubusercontent.com/1255302/132470750-53f4c6c9-0c5c-4b84-b8d1-3a9d4f699153.png)


By default the option is ON - ignore contents. It should provide more stable results and not overwrite message needlessly.
