### ISSUE TITLE
[request] right-click behavior without fetch the messages

### ISSUE THREAD

**Issue by blackarcher21** [martinrotter/rssguard#49]
Right-click on certain account, category or feed, RSS Guard will immediately show all messages. I'm not sure if it sounds good to you, but that could avoid unneeded process. Thanks and regards :)

**Comment by martinrotter** [comment]
You mean, that when you right-click some feed/category/account, new messages should be downloaded?

**Comment by martinrotter** [comment]
And what cat it exactly avoid? I do not entirely understand the point. :) Please, elaborate.

**Comment by blackarcher21** [comment]
sorry :)
I mean whenever right-click on feed/category/account, RSS Guard will fetch messages from DB. 
For example if users want to export/import feeds via right-click on account, RSS fetch the messages from DB which I think its not necessary, though they also can do the job via menu from menu bar. What do you think? :)

**Comment by martinrotter** [comment]
Oh, so when you right-click an item, you do not want that item to become automatically selected?

**Comment by blackarcher21** [comment]
yes, that's what I mean

**Comment by martinrotter** [comment]
Well, pre-selecting item when right-clicking on it is standard Qt library behavior. I even thing it is natural. How natural is to view properties of item and not having it already selected?

**Comment by blackarcher21** [comment]
Yes, I guess you're right. So means it can't/won't be changed? Okay, fine. Thank you. :)
