### ISSUE TITLE
[BUG]: Inoreader - Failed to start OAth redirection listener.

### ISSUE THREAD

**Issue by fredddd1** [martinrotter/rssguard#490]
### Brief description of the issue

Attempting to setup an Inoreader account.

### How to reproduce the bug?

Setup Inoreader account and fill in the required details.

### What was the expected result?

For the test to succeed.

### What actually happened?

The test failed with an error:

![image](https://user-images.githubusercontent.com/80743272/132372910-e807d855-b2b4-4006-8821-c714ce90e9cd.png)

### Operating system and version

* OS: Windows Pro 21H1 64-bit
* RSS Guard version: 4.0.1

**Comment by martinrotter** [comment]
@fredddd1 Please, provide full application debug log. See documentation on how to generate it.

**Comment by fredddd1** [comment]
> @fredddd1 Please, provide full application debug log. See documentation on how to generate it.

I am unable to find an entry on how to generate a debug log. Could you point me to it please?

**Comment by martinrotter** [comment]
It is bit buried: https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#cli

**Comment by fredddd1** [comment]
Please remove the debug log as soon as it is not needed any more.

[debug.log](https://github.com/martinrotter/rssguard/files/7149482/debug.log)

**Comment by martinrotter** [comment]
@fredddd1 So the issue is now solved? What was the culprit?

**Comment by fredddd1** [comment]
The issue is not solved.

**Comment by martinrotter** [comment]
@fredddd1 I see, I misunderstood your previous comment.

Can you please send your debug log to my e-mail: rotter.martinos(at)gmail.com ?

**Comment by martinrotter** [comment]
@fredddd1 OK, I checked your debug log carefully.
1. Do you have your Inoreader "developer" settings correctly set? Have you entered your own App ID/Key and **proper** redirection localhost url with correct port?
2. How did you install RSS Guard?

**Comment by fredddd1** [comment]
I ended up switching to Reedah to save myself the trouble.

For Inoreader I pretty much just made the app and copied the information over to RSS Guard.

I really have no idea what I could have done wrong just copying the information over.
