### ISSUE TITLE
[FR]: Dark Mode Webview

### ISSUE THREAD

**Issue by barolo** [martinrotter/rssguard#491]
### Brief description of the feature request

Not really sure if FR, just a hint that might be useful.
It's possible to get a nice 'dark mode' in qtwebview  via chromium's env flags

works with current 5* Qt [overlay scrollbars as a bonus]
`
QTWEBENGINE_CHROMIUM_FLAGS="-blink-settings=forceDarkModeEnabled=true -enable-features=OverlayScrollbar" rssguard`

I know that some chromium based browser have internal toggle for this.

**Comment by martinrotter** [comment]
@barolo In 4.0.2 I update both built-in skins to use same CSS library Pico.css, dark variant looks like this:
![image](https://user-images.githubusercontent.com/1255302/132626216-b09ce13e-514e-4486-a4d0-495798c23ef2.png)

With your env. variable: 
![image](https://user-images.githubusercontent.com/1255302/132626368-d5a56257-9bcc-4dd1-9966-473aa678e615.png)

I don't see scrollbar at all.

With default "light" skin:
![image](https://user-images.githubusercontent.com/1255302/132626464-b789b947-8041-4a30-963c-9fe15daf7f1d.png)

So for me, it does not produce any enhancements at all, but might work better for others.

**Comment by barolo** [comment]
Oh, I'm yet to try the update. The scrollbar should be only visible during scrolling.

**Comment by martinrotter** [comment]
I see, it is not visible even when scrolling in my case. :D
