### ISSUE TITLE
[FR]: Regard the article "new" taking into account only its date

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#492]
### Brief description of the feature request

Consider article as "updated"—or "new"—if its date (which is determined by `<id>`) was changed.

### Long description

The new feature of "Ignore changes in article content" is truly nice. 
Lately, I found myself nearly submerged in feeds which keep changing their content, however eccentric those changes are. 

And although it _is_ a nice and useful feature, it leaves no leeway at all, which is crucial to me sometimes.

What if article actually was updated? It will also be ignored, right? 
Since the only way to show that the article was updated  is its date, I would like to see RSS Guard paying special attention to it.

Certainly, there can be some one or two bizarre feeds, which changing the dates back and forth (e.g. https://github.com/martinrotter/rssguard/issues/451#issuecomment-887233279, albeit here the changes were in `content` element too), but chances are almost nil.

So, if RSS Guard would take into account the dates of articles, the appearance of these new-but-not-really-updated articles will be minimised, and the feature of "Ignore changes in article content" can certainly be replaced by this one instead. 
Or perhaps it should be a default behaviour?

With that said, I still do want to see the content of article being updated, even if the article itself was not. 
Therefore, for such cases, I think the article should not be considered "new" if its content undergone changes, but date is not.

Would really like to hear your thoughts on this.

**Comment by martinrotter** [comment]
@sakkamade
> which is determined by <id>

No, `id` is just an ID, that's it. Date/time of the article is held in various XML elements depending on type RSS/ATOM/RDF/JSON and RSS Guard properly loads those elements.

The merging algorithm is non-trivial and will not ever work for 100% for everyone, that has to be said.

Also, it there is a message in XML feed source, and its date/time (`pubDate` or `date` elements for RSS) is DIFFERENT than date/time of the very same already saved article, then article is overwritten, BUT NOT MARKED AS UNREAD, stored read state is retained.

If contents (HTML/TEXT) are changed then it depends on the setting I recently added.

I think that the feature you want is actually already there.

Also remember this, there are TWO very important things happening in the process of merging algorithm:
1. Find out if the older (possibly) version message we are about to update (or not) is even stored in our local database. This is usually done via special ID element (`guid` for RSS).
2. If we found stored version of the message, then perform the actual comparisons to determine if newly incoming message is "updated".

Now, what specifically happens for both of above points (for non-synchronized accounts, like standard RSS/ATOM) in RSS Guard is:
1. If message has unique ID fetched from feed (`guid`) then find stored message directly with the ID. If there is no ID (bad, bad, bad feed!) use triplet `(author, title, url)` to find existing local article.
2. If local article is not found, then message is new and is added. If article is found, then perform the comparisons (at least one must be true):
    a. If message has ID, then check if title **or** contents are changed (if feature disabled) and if they are, update message.
    b. If message has date/time **or** contents changed (if feature disabled), then update message.

Your case is covered by 2/b.

**Comment by martinrotter** [comment]
> And although it is a nice and useful feature, it leaves no leeway at all

What about expanding the feature to also be optionally switchable per-feed?

**Comment by sakkamade** [comment]
I thought by explaining my reasoning it should be easier to understand.
Sorry about that.
> > which is determined by
> 
> No, `id` is just an ID, that's it. 

Oops, some typo.

This is how it must be: 
> Consider article as "updated"—or "new"—if date of the article (the particular article which is determined by its unique `<id>`) was changed.


---

> Also, it there is a message in XML feed source, and its date/time (pubDate or date elements for RSS) is DIFFERENT than date/time of the very same already saved article, then article is overwritten, BUT NOT MARKED AS UNREAD, stored read state is retained.

Huh? So if the date of article was changed, the article is not being marked as unread? Why?

---

I will go straight to the point then:
1. I'd like for the old article to be marked as new if its date is changed
2. I'd like to see the content of article to be changed, if it was updated upstream, however it should not be marked unread, unless the date was changed too

> What about expanding the feature to also be optionally switchable per-feed?

I guess it could solve the problem, however it would be overcomplicated, wouldn't it?

I rather not have that feature at all. I wonder if it will give any advantage if the two above conditions are fulfilled?

**Comment by sakkamade** [comment]
Thank you for quick response, btw!

**Comment by martinrotter** [comment]
> Huh? So if the date of article was changed, the article is not being marked as unread? Why?
That's how it always was. Nobody really asked about it.

1.
> I'd like for the old article to be marked as new if its date is changed
You mean mark it unread if its date is changed upstream?

2. Content is already updated if the "ignore" option is not enabled.

So basically, everything you ask for as to mark messages as unread of their upstream date/time is changed? That's it?

**Comment by sakkamade** [comment]
> You mean mark it unread if its date is changed upstream?

Yes. Only.
> That's it? I am still maybe missing something between the lines as I feel that all features we talked about are already there (except for marking as unread in this case).

Hmmm... Yes?

But you see, the importaint point is that it should not be marked as unread if only content was changed.

**Comment by sakkamade** [comment]
By the way, if you planning on leaving that feature, reword it slightly so that to change the word "new" to "unread."
And I think it can be disabled by default.

**Comment by martinrotter** [comment]
So you think that date/time change is actually more important than (real) content change? I mean, of course we want to avoid those shitty content "changes" but when the actual and useful content change happens, isn't it equally important?

I suggest new feature "Mark article unread when it is updated upstream" which will work with respect to "Ignore changes in contents...". If "mark-unread" is checked and "ignore" checked then only change in date will mark it as unread. If "ignore" is unchecked, then change **either** in date/time **or** in contents will mark as unread.

**Comment by sakkamade** [comment]
> So you think that date/time change is actually more important than (real) content change?

I believe that if author deliberately changed the content, the date will also be deliberately updated. That is how I do it.

The changes in content are mostly not intentional.
What I have seen as semi-intentional were just fixes of severe and very noticable to naked eye issues. But such things are always updated within an hour of published time.

/
Sorry, that's about it from me for now.

**Comment by martinrotter** [comment]
FOR ME: Add feature "Mark article unread if its date/time is changed".

**Comment by sakkamade** [comment]
I am talking about feeds that serves as nothing but notification.
Of course, if there are feeds which have full content of the article being placed within, it's another question, However I have never seen such thing so far.

**Comment by sakkamade** [comment]
> only for non-synchronized accounts

Yes, as I have mentioned some time ago, I don't use any services, and I am not sure how they work.

**Comment by sakkamade** [comment]
> I suggest new feature "Mark article unread when it is updated upstream" which will work with respect to "Ignore changes in contents...".

I guess it will be for the best indeed.
> If "mark-unread" is checked and "ignore" checked then only change in date will mark it as unread. 

I think, more intuitive would be:
1. No changes are ignored (neither date nor content), which will be a default behaviour
1. Option to ignore changes in content only
2. Option to ignore any changes (either date or content)
> If "ignore" is unchecked, then change either in date/time or in contents will mark as unread.

Why not make it take date changes into account by default, just like changes in content now?

**Comment by sakkamade** [comment]
I guess I need some clarification as well.
The current option of "Ignore changes in article contents when determining [...]" What is it doing exactly? 
Prevents any changes to already fetched articles? Or is it only prevents updated articles from being marked as unread?

**Comment by martinrotter** [comment]
@sakkamade OK we are now obviously buried in our conversation too much.

Copying excerpt of my previous answer, expanded:

*********

Now, what specifically happens when message is about to be updated or inserted (for non-synchronized accounts, like standard RSS/ATOM) in RSS Guard is:
1. If new message has unique ID fetched from feed (`guid`) then find stored message directly with the ID. If there is no ID (bad, bad, bad feed!) use triplet (author, title, url) to find existing local article.
2. If local article is not found, then message is new and is added. **If article is found, then perform the comparisons (at least one must be true):**
    a. If message has ID, then check if title or contents are changed (if feature "Ignore changes in article contents when determining [...]" is disabled) and if they are, update message.
    b. If message has date/time **or** contents changed (if feature "Ignore changes in article contents when determining [...]" is disabled), then update message.

Feature "Ignore changes in article contents when determining [...]"  does exactly what it says. It takes **contents** (and contents only) out of the equation when determining if message is "updated". All other factors (like date/time) are still there.

**Comment by sakkamade** [comment]
> > Or is it only prevents updated articles from being marked as unread?
>
> There is currently literally no functionality which is marking "updated" messages as unread

Right, I only wanted to reconfirm.

**Comment by martinrotter** [comment]
So we need some kind of consensus. All features are there except for marking as unread when updated?

**Comment by sakkamade** [comment]
> There is currently literally no functionality which is marking "updated" messages as unread, this is not there, no automagic marking as unread happens, never.

>  there is a message in XML feed source, and its date/time (pubDate or date elements for RSS) is DIFFERENT than date/time of the very same already saved article, then article is overwritten, BUT NOT MARKED AS UNREAD

I find it quite contradictory. Which is true?

**Comment by sakkamade** [comment]
> All features are there except for marking as unread when updated?

By updated, do you mean edited upstream? Or just fetched?

**Comment by sakkamade** [comment]
> So we need some kind of consensus. 

It is here:
> I think, more intuitive would be:
> 
>  1. No changes are ignored (neither date nor content), which will be a behaviour with neither option enabled
>  2. Option to ignore changes in content only
>  3. Option to ignore any changes (either date or content)

I am waiting for you to comment on this.

**Comment by martinrotter** [comment]
> 
> 
> > All features are there except for marking as unread when updated?
> 
> By updated, do you mean edited upstream? Or just fetched?
> I meant the former.

By "updated" I mean when it gets overwritten in local DB with "newer" version of article downloaded from upstream feed file.

**Comment by martinrotter** [comment]
> 
> 
> > So we need some kind of consensus.
> 
> It is here:
> 
> > I think, more intuitive would be:
> > 
> > 1. No changes are ignored (neither date nor content), which will be a behaviour with neither option enabled
> > 2. Option to ignore changes in content only (so only if the date was changed message will be updated) **<-- this should be added**
> > 3. Option to ignore any changes (either date or content)
> 
> I am waiting for you to comment on this.

1. This is already there when "Ignore changes in article contents when determining [...]" **is NOT** enabled/checked.
2. This is already there when "Ignore changes in article contents when determining [...]" **is** enabled/checked.
3. This is not implemented. Could be added as "Do not overwrite local articles with newer versions fetched from upstream EVER".

**Comment by sakkamade** [comment]
> 2. This is already there when "Ignore changes in article contents when determining [...]" **is** enabled/checked.

Ha?
So presently with that option enabled only the date of article is taken into account marking article as "new", or "unread" (updating it)?

**Comment by martinrotter** [comment]
> 
> 
> > 1. This is already there when "Ignore changes in article contents when determining [...]" **is** enabled/checked.
> 
> Ha?
> So presently with that option enabled only the date of article is taken into account to mark article as "new", or "unread" (updating it)?

This is not what I said. The option enabled does exactly what you stated in 2. - **Option to ignore changes in content only **. So changes in contents and IN CONTENTS ONLY are ignore. All other factors are respected.

**Comment by martinrotter** [comment]
Here is code comment from algorithm from RSS Guard source code:
```
//   2) FOR NON-SYNCHRONIZED SERVICES (RSS/ATOM/JSON): Message has custom ID/GUID and its title or contents are changed.
//
//   3) FOR ALL SERVICES: Message has its date fetched from feed AND its date is different
//      from date in DB or content is changed.
```

**Comment by sakkamade** [comment]
> All other factors are respected.

Ah, yes, of course, since there is also the author, enclosures, etc. I just don't consider them.

**Comment by sakkamade** [comment]
Yes, it's all clear now.

I just did not expect for that "contents" to be the same "content" which I was talking of.
Whew...

Thank you. There is nothing to be done here, closing it.

**Comment by martinrotter** [comment]
Oh, that's nice conclusion after 27 comments, anyway feel free to post ticket to mark updated messages as unread, could be added.

**Comment by sakkamade** [comment]
I suggest to rename "contents" to something like the "article", to avoid misunderstandings.

**Comment by martinrotter** [comment]
Maybe "contents" -> "text of article"?

**Comment by sakkamade** [comment]
> Oh, that's nice conclusion after 27 comments,

Far from it, actually. But now I am more versed to open another issue, properly knowing present situation :heart: 

Although may ask here as well, this condition left unfulfilled:
I still do want to see the content of article being updated, but for article _not_ to be marked as unread unless the date was changed too.
What are chances for it to be implemented?

> Maybe "contents" -> "text of article"?

"Article contents" -> "contents of article", perhaps even "body of article."

**Comment by martinrotter** [comment]
Open small, well-strucured individual tickets. I like to avoid confusion as much as possible.

In other words, you want to mark article as unread if it was updated based on the fact that date/time was changed upstream. - Yes that can be added - post individual tickets for all requests.

**Comment by sakkamade** [comment]
> In other words ...

Not quite, I'll explain there.

**Comment by sakkamade** [comment]
> Maybe "contents" -> "text of article"?

Never mind it. The "article contents" is fine. I better learn how to read in English.

**Comment by martinrotter** [comment]
English is not my native language either. I may fucked up my wording as well and I am sure there are many phrases inside RSS Guard which should be changed.

**Comment by sakkamade** [comment]
Well, to make myself as plain as possible, I thought that the "article contents" define the whole entry, i.e. date, author, category, summary, etc.

**Comment by martinrotter** [comment]
Yes, that was the core of confusion. I hate the word "contents". I will replace it with "body"

**Comment by sakkamade** [comment]
> I will replace it with "body"

It could certainly be changed to "body", if we were talking about `html`, but here it is not so clear.

Here what I found about it https://www.toppr.com/guides/english/writing/article/
Although it can avoid misunderstandings for one, it can cause them for another.

Perhaps it should be left it as is, but some explanatory tooltip can be added?

**Comment by martinrotter** [comment]
No need to take HTML technicality into account. For 95% of users, body of article is the text is is saying, HTML is just another form how the text is represented on a technical level. Similar phrases are used for emails which also have body and it is not important if it is plain text or HTML on each individual email.

**Comment by sakkamade** [comment]
https://github.com/martinrotter/rssguard/blob/99afe5433ed36ac63bfd1e32d95397317080f758/src/librssguard/gui/settings/settingsfeedsmessages.ui#L475

I was thinking about it a bit, and you know, for ordinary users the "upstream", "downstream" has no meaning whatsoever.

The "text" in parenthesis is also disturbs me.

Perhaps: `Ignore changes in article body when articles are fetched` ?

**Comment by martinrotter** [comment]
done
