### ISSUE TITLE
[FR]: Mark read edited article as unread only if its date was changed

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#494]
### Brief description of the feature request

Although now there is a feature which allows to ignore changes in article contents, I would like to see read articles being updated upon fetching if they have been edited upstream, but to still be left as "read".

And to be marked as unread when its date has been changed too/only.

**Comment by martinrotter** [comment]
If you have "ignore contents changes" checked and date of message is changed, it is overwritten in DB and marked UNREAD.

If you dont have "ignore contents changes" checked, then if either contents OR date is changed, msg is overwritten in DB and marked UNREAD.

So to me it sounds like "And to be marked as unread when its date has been changed too/only." request is already working, should be.
