### ISSUE TITLE
[BUG]: BazQux: drop in sync speed

### ISSUE THREAD

**Issue by umbellipher** [martinrotter/rssguard#496]
### Brief description of the issue

Just to say that, using 99afe453 over a 429 Mbps connection, it took 11 minutes 7 seconds to sync 498 unread BazQux items on 701 feeds.

### How to reproduce the bug?

-

### What was the expected result?

-

### What actually happened?

-

### Other information

-

### Operating system and version

* OS: Windows 10
* RSS Guard version: see above.

**Comment by martinrotter** [comment]
will check, is speed noticeably bigger with other/older version or?

**Comment by martinrotter** [comment]
also, how exactly did you triggered the sync, was it started automatically? did you update all feeds or selected specific category?

**Comment by martinrotter** [comment]
OK, checked (80 feeds):
* First pass - 13000 articles - 1:55
* Second pass - 0 new articles - 0:07

So here it works, please answer all above questions and possibly provide debug log.

![image](https://user-images.githubusercontent.com/1255302/133552963-6e779b82-0c9f-4b5b-be82-b9e86823792d.png)

**Comment by umbellipher** [comment]
@martinrotter

Thanks. Can't tell re older version, since this is the only one installed.

Triggered sync manually. All feeds. Intelligent sync enabled. 'Since' set to one year ago (was back in Aug 20 until I adjusted it just now.).

Happy to send log, if you tell me how!

Rechecked just now. First pass on opening: 7'20'' this time. 602 unread. Second pass: 3'45''. 642 unread. Download speed: 364 Mbps.

**Comment by martinrotter** [comment]
Link on how to get logs is there visible when creating bug ticket.

https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#reprt

**Comment by umbellipher** [comment]
@martinrotter 

Tried everything as suggested to get a log file, but no success so far.

Insane: I know. Wish i knew what was causing it.

I tried a (second) sync without my always-on VPN, and it clocked at 3'47''. 1128 unread. No real improvement.

Account and settings: 
![Screenshot - 16_09_2021 , 11_33_27](https://user-images.githubusercontent.com/59395777/133590750-d6a2d973-c65d-4d27-aaf7-89c668255a6e.png)
![Screenshot - 16_09_2021 , 11_34_22](https://user-images.githubusercontent.com/59395777/133590760-0c67601b-e8a5-4b34-bdde-820eace41baf.png)
![Screenshot - 16_09_2021 , 11_34_04](https://user-images.githubusercontent.com/59395777/133590763-6ebf341c-0055-41a8-b97f-d6d84b011fea.png)

**Comment by umbellipher** [comment]
For other reasons (I did not want them) I reduced the number of feeds to 648.

I then reverted to 4.0.2 0178a046 and ran two syncs, over fast fibre connection.

Sync 1: 3'40'': 138 unread.

Sync 2, directly afterwards: 2'46.

Rather faster, then. Not your speeds, though.

I wonder what has happened between 0178a046 and 99afe54 (also applies to latest, f42c372), to slow it down so much, for me at least.

(Tried and tried to do a log, but no success so far.)

**Comment by martinrotter** [comment]
> (Tried and tried to do a log, but no success so far.)

I really cannot do anything without debug log, it would be just guessing.

1. start cmd.exe
2. navigate to folder of rssguard.
3. run: rssguard.exe --log '.\rssguard.log'
4. reproduce problem and exit rss guard
5. find "rssguard.log" file in rssguard folder and upload here.

Really cannot help much more than that at this point, there were no real changes which could affect sync speed.

**Comment by umbellipher** [comment]
Tried everything to get a log. Cmd admin, Powershell. Search computer with Everything: no rssguard.log generated.

DB settings:
![Screenshot - 17_09_2021 , 09_59_06](https://user-images.githubusercontent.com/59395777/133746748-4309efc4-d8a2-4bda-948b-dc576e6b1de7.png)

**Comment by umbellipher** [comment]
I've now solved this to my satisfaction. Turns out that I needed (under Accounts) 'download unread only' enabled, as well as 'intelligent algorithm'.

Speeds back up to very fast again.
