### ISSUE TITLE
[BUG]: Enter key doesn't work when assigned to used open in External browser

### ISSUE THREAD

**Issue by mahdi1234** [martinrotter/rssguard#498]
### Brief description of the issue

Enter key doesn't work when assigned to used open in External browser

### How to reproduce the bug?

1. Tools - Setting - Keyboard shortcuts
2. Assign "Enter" for "Open in external browser"
3. Navigate via keyboard to any article and fire Enter

### What was the expected result?

Article opens in external browser

### What actually happened?

Nothing

### Other information

Other keys works fine, probably Enter is problem not particular action.

### Operating system and version

* OS: Gentoo
* RSS Guard version: 4.0.1

**Comment by martinrotter** [comment]
I see, will look into it.

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/133879380-72dab1c2-7995-44be-be26-a9f33b44bb35.png)

It works fine here (on Windows), either with `Return` key or `Enter` key. Cannot thus reproduce your behavior. I will test on my Linux machine.

**Comment by sakkamade** [comment]
Works fine on Arch Linux, Xfce.

**Comment by mahdi1234** [comment]
Thanks, that's really strange I had to fiddle with the control, it originally took string "Enter" and that didn't work, but once it recognized key as "Return" it works :) thanks for hint.

**Comment by martinrotter** [comment]
Well, note that "Return" and "Enter" are not the same key. One is located in right/bottom corner of keyboard, other is the big L-shaped button. So everything works? OK, closing.
