### ISSUE TITLE
Global menu hide on Unity

### ISSUE THREAD

**Issue by varlesh** [martinrotter/rssguard#5]
If use "Switch visibility of main window" and restore window - global menu not visibly on Unity.
OS: Ubuntu 15.04 amd64
RSSGuard: 2.5.1

**Comment by martinrotter** [comment]
So workflow is this:

1. Main window visible and FOCUSED -> global menu visible.
2. You hide main window -> global menu of course invisible.
3. You restore window (via clicking on tray icon?) -> global menu still invisible? Does window has input focus after step 3? Does the same behavior exist when you simply close the window via clicking on [X] button?

**Comment by varlesh** [comment]
First start - menu working.
Close program (to tray) and restore window - menu not visible.
Also "Switch visibility of main window" - menu not visible.

**Comment by martinrotter** [comment]
Are you entirely sure this is not Unity/Ubuntu/Qt bug?

RSS Guard does not control "global" menu in any way. It does not show/hide menu when main window is hidden/shown.

**Comment by varlesh** [comment]
No, please see video demonstration:
https://youtu.be/I9dqt_uZh3g

**Comment by martinrotter** [comment]
Did this bug got somehow solved with latest versions? I have absolutely no way to test this.

**Comment by varlesh** [comment]
On 3.1.0 Qt4 menu working fine. Thx :+1:
