### ISSUE TITLE
[BUG]: Translation script needed sys.stdout.reconfigure(encoding = src_enc) for Windows with various localizations

### ISSUE THREAD

**Issue by nnolex** [martinrotter/rssguard#500]
### Brief description of the feature request

Hi. I was very interested in the automatic translation script, I tried to use it, but it didn't work for me, giving various errors. I am far from programming, I had to get my hands on a search engine and spend a couple of days to figure it out. My operating system is Windows and it is localized to Russian, when I used the script I kept getting an error about the unknown characters encoding pointing to cp1251. It only worked after I added `sys.stdout.reconfigure(encoding = src_enc)` to the script. And at the moment googletrans doesn't work for me, seems to be some kind of module incompatibility on my Windows 7, had to use a different package.

**Comment by martinrotter** [comment]
Can you perhaps create pull request with your changes?

Btw: Example scripts contained in the repository are there rather as inspiration for users to create their own scripts and I completely expect that they won't work for everyone. I will close this ticket, please create PR for the particular problem you had and I will merge. :)
