### ISSUE TITLE
[FR]: Mark "Standard online feeds" in "Add new account" as something distinct

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#503]
### Brief description of the feature request

(I should apologise beforehand, as I won't be brief. You may skip the middle section.)

I hope to see "Standard online feeds" in "Add new account" window to be treated/marked as something distinct (since it is not an account of any online service).

---
The reasoning behind this is that I remember looking for the RSS program some time ago, and I have tried out the RSS Guard too.
Why I didn't start using it back then was for I could not even actually start it.

Being a casual RSS user as I am, I had/have still no account of any online RSS service, and when I launched the RSS Guard I was asked to choose the online service which I supposed to use (It is Tiny Tiny RSS which is chosen by default).

That did not scare me as I didn't really know what it was, and I clicked OK without much thinking, then Bang! I was introduced with some strange options such as type in the url, username, password, etc. 

"Huh?" thought I, "this is not for me."

And the next moment I remember myself typing in the command of `sudo pacman -Rs rssguard`.

Only after some months could I succeed to read somewhere that it also supports plain feeds and actually test it out.

---

One suggestion could have been to have "Standard online feeds" to be simply highlighted by default, but I don't think it will be of much help, so rather than that I guess would be best to separate it from the rest of online services in list (leaving it in the same window, but somewhat detached).

**Comment by martinrotter** [comment]
@sakkamade

Well:
1. I completely understand that you overlooked it. This situation certainly could be somehow improved. Part of the problem was the description of RSS Guard in `README.md` which I updated some weeks ago to: `RSS Guard is simple feed reader which supports RSS/ATOM/JSON and many web-based feed services` which is better. Documentation was also updated to mention explicitly that both local/classic RSS/ATOM/... are supported as well as remote synchronizable solutions.
2. While RSS/ATOM/.. may be "default" and something "distinct" for you, believe me that there is another group of users which have exactly opposite mindset. For them, `RSS` is the web interface of their favorite online feed reader. Yea, I agree, it's fucked up. Perhaps I could distinguish both types of "accounts" with background color?

**Comment by sakkamade** [comment]
> 1. Part of the problem was the description of RSS Guard in `README.md`

I simply searched through `pacman -Ss`.

> and something "distinct" for you, believe me that there is another group of users

But it certainly is a smaller group.
What I say is that this may be one of the reasons RSS Guard is not as popular.

> Perhaps I could distinguish both types of "accounts" with background color?

Well, if so, first I would have at least removed the icon from there, which has clearly misled me back then.
Perhaps also adhered to the bottom border?

**Comment by martinrotter** [comment]
OK, now "RSS" account is preselected in the dialog, its title was little changed to be less misleading and also icon is now classic RSS.

**Comment by sakkamade** [comment]
@martinrotter, Excuse me, but do you really think that something has improved? 

![image](https://user-images.githubusercontent.com/62730422/134126128-28354a23-f5e1-4f76-8271-ec37960fc26f.png)
(Save for it being selected first.)

The icon may be as well be the one used by the online service.
 I can easily imagine that the "Classic feeds" is another name of some other online service.

---

Okay. Here I go.

1. It should not be amidst other services. Move it either to top or to bottom.
2. Name: Just leave those "RSS/ATOM/JSON."
3. As for the icon, I see it is hard-coded with the icon shown by the "Account's" side in list, so it will be unreasonable to remove it;
    1. Then perhaps leave it with the folder icon? Since, in the end, it can be considered a mere folder, in this case.
    2. Otherwise, placing there simplistic "feed" icon of the icon theme that is currently used can be the way?
        The one which is used for "Add new feed" action presently.

**Comment by martinrotter** [comment]
2. done
3. II - done

1416e1818

**Comment by sakkamade** [comment]
What argument for turning down the `#1`?

**Comment by martinrotter** [comment]
> 
> 
> What is the argument for turning down the `#1`?

Too much coding and when you combine that with the fact I am lazy programmer, then you have pretty strong argument. Other argument is that i do not actually thing that having it on top/bottom is that much better. It is now preselected. I think it's okay.
