### ISSUE TITLE
[BUG]: The Crash

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#504]
### Brief description of the issue

Crashes when I click on the article (the message viewer is not showing).

### How to reproduce the bug?

1. Start RSS Guard
2. Click any article

### What was the expected result?

Not crashed :stuck_out_tongue_closed_eyes: 

### What actually happened?

Crashed.

### Other information

Some log: [rss-log.txt](https://github.com/martinrotter/rssguard/files/7202564/rss-log.txt)

### Operating system and version

* OS: Arch Linux
* RSS Guard
Version: 4.0.3 (built on Linux/x86_64)
Revision: e9add2fd
Build date: 21/09/2021 07:49
Qt: 5.15.2 (compiled against 5.15.2)

**Comment by martinrotter** [comment]
Try to reboot your system. These kinds of errors happen if kernel modules (or kernel) get updated and machine was not restarted.

**Comment by sakkamade** [comment]
> These kinds of errors happen if kernel modules (or kernel) get updated and machine was not restarted.

Thank you. Indeed.  I forgot about it...

**Comment by martinrotter** [comment]
Happened to me like a million times. I just run "pacman -Syu" like a zombie, not even thinking about what I do. That's Arch. It just works.

**Comment by sakkamade** [comment]
>  just run "pacman -Syu" like a zombie, not even thinking about what I do. That's Arch. It just works
 
Hahahaha.
