### ISSUE TITLE
[BUG]: Articles being fetched again after already being marked as read and deleted

### ISSUE THREAD

**Issue by Elionna** [martinrotter/rssguard#505]
### Brief description of the issue

I'm getting duplicate articles from a feed, I delete the articles after marking them as read but they fetch again. It's just with this feed, and I don't have this issue with other feeds. I do not have this issue with this feed in other RSS readers. 

### How to reproduce the bug?

1. Add feed, https://gbatemp.net/forums/gbatemp-scene-news.101/index.rss
2. After initial fetch of articles, mark them as read and delete
3. After a few hours try to refetch, some of the same articles will be fetched again

### What was the expected result?

n/a

### What actually happened?

n/a

### Operating system and version

* OS: Windows 
* RSS Guard version: 4.0.2

**Comment by Elionna** [comment]
I will reopen after trying to troubleshoot a bit more

**Comment by Elionna** [comment]
Still having the issue, just fetched the articles again and duplicates came in

**Comment by martinrotter** [comment]
OK, I will investigate soon.

**Comment by Elionna** [comment]
It's just this feed, settings are default. Ignore changes in article contents when determining if article is "new" is checked.

**Comment by martinrotter** [comment]
i see, provide debug log or i cannot really help

![image](https://user-images.githubusercontent.com/1255302/134462231-45f8a181-4e86-47c1-9263-90c64f9442ab.png)
https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#reprt

**Comment by martinrotter** [comment]
@Elionna OK I checked the situation and your feed is changing date/time of articles. For example there is article `GBAtemp is now in TEMPORARY MODE` which had date/time Thursday, 23 September 2021 08:40:23 GMT+02:00 DST and when feed was fetched few minutes later, it had date/time Thursday, 23 September 2021 09:00:37 GMT+02:00 DST.

The feed is de-facto faulty. You can solve the situation by using proper article filter or if you want, I can create new similar feature: `Ignore changes in article date/time when article is updated upstream` - if you want that, create feature request with it.

**Comment by sakkamade** [comment]
> Ignore changes in __article contents__ when determining if article is "new" is checked.

I guess this have caused a misunderstanding again. @Elionna, Have it?

@martinrotter, Still, I wonder if having the "... (text) ..." in parenthesis is all that good. 
(Related commit https://github.com/martinrotter/rssguard/commit/99afe5433ed36ac63bfd1e32d95397317080f758)


@Elionna, If you use English locale, do you think "article body" would be better/easier to understand than the "article contents"? 

----
> OK I checked the situation and your feed is changing date/time of articles.

Gosh, these feeds are truly yet another hell on earth.

**Comment by martinrotter** [comment]
@sakkamade Problem is not that date/time was changed, problem is that it was changed without any clear reason, probably just a bug in the CMS the source website is using.

**Comment by sakkamade** [comment]
>  Problem is not that date/time was changed, problem is that it was changed without any clear reason,

Yes, that's why I said

> feeds are truly yet another hell on earth.

**Comment by Elionna** [comment]
thanks for looking into this

@martinrotter what would I put into the filter for this feed so I don't get duplicates? 

@sakkamade yes article body would be easier to understand in my opinion

**Comment by martinrotter** [comment]
@Elionna
```js
function filterMessage() {
  if (msg.isDuplicateWithAttribute(MessageObject.SameUrl)) {
    return MessageObject.Ignore;
  }
  else {
    return MessageObject.Accept;
  }
}
```
This would reject new article if article with same URL is already stored in local DB, effectively solving your problems.

**Comment by Elionna** [comment]
excellent, thank you very much
