### ISSUE TITLE
[BUG]: "Automatically expand item when selected" option has no effect when using the key bindings

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#506]
### Brief description of the issue

The behaviour of "Automatically expand item when selected" (feed list) remains when moving through the list with key bindings (`S` and `A`), despite that respective option (in "Alt+e" menu) is unchecked.

### How to reproduce the bug?

1. Observe the behaviour with (by default) unchecked option while using `S` and `A`
2. Check the option, and see the same behaviour
3. Uncheck it again 
4. Nothing changes

### What was the expected result?

Not to expand the items in list.

### What actually happened?

They were expanding.

### Other information

Tested with default configuration.

### Operating system and version

* OS: Arch Linux
* RSS Guard
Version: 4.0.3 (built on Linux/x86_64)
Revision: 4fde9993
Qt: 5.15.2 (compiled against 5.15.2)

**Comment by martinrotter** [comment]
a87e09d49

Hopefully fixed, test pls.

**Comment by sakkamade** [comment]
Fixed. Thank you very much!
