### ISSUE TITLE
[FR]: How to make two computers display the same unread quantity as tiny tiny rss

### ISSUE THREAD

**Issue by Franklittleboy** [martinrotter/rssguard#508]
### Brief description of the feature request

I have two computers. After I synchronize the unread articles on both computers, I turn off the computer after reading some articles on one of the devices(computer 1）. Open the client on another computer（computer 2）, and articles that have been read on computer 1 will not be marked as read on computer 2, continue  to be displayed as unread. How to make two devices consistent with the unread status on tiny tiny rss?

**Comment by martinrotter** [comment]
https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#sfr

Synchronization of TT-RSS in rssguard is two-way. That means that if you change state of any article in rssguard (mark as read, unread, etc.) then the change IS propagated back to TT-RSS server but not immediately. RSS Guard batches all changes made and sends them to server in ONE MINUTE intervals.

Therefore if you mark some message read and immediately switch off PC/rssguard, the change will not have enough time to be synchronized back to server.

Also, how is TT-RSS setup in rssguard?
![image](https://user-images.githubusercontent.com/1255302/135207793-3075f614-d972-429b-b0b9-768965dea5ec.png)
Do you have "Download unread articles only" enabled?

**Comment by Franklittleboy** [comment]
"Download unread articles only" is not enabled.
got it , i'll try it later, thanks very much!

**Comment by Franklittleboy** [comment]
When I synchronize in rssguard, there are 50 unread messages on both the server and the client. Then, I read 5 messages in the server, and 45 unread messages remain in the server. But after rssguard is synchronized with the server at this time, the rssguard client still has 50 unread messages (at the same time, the server has only 45 unread messages).
Can you tell me why and how to do it? thanks
<img width="276" alt="pic" src="https://user-images.githubusercontent.com/54013763/136507711-4df4e954-acbf-44e9-ada5-e14d29de8a5f.png">
.

**Comment by martinrotter** [comment]
@Franklittleboy Sounds like a bug. I've tested right now and it works correctly here:
1. 52 unread on both client/server, marked 2 as ready on server.
2. Made sync again with rssguard.
3. 50 unread on both server and client.

![image](https://user-images.githubusercontent.com/1255302/136510675-4197a4c8-db85-4266-9389-2ae836bbc745.png)

You must really really provide full application debug log recorded during the time when bug appears. I cannot do anything w/o it.

https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#reprt

So provide debug log and I will re-open and investigate. Until then, closing. :)
