### ISSUE TITLE
[FR]: `SameId` for article filters

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#509]
### Brief description of the feature request

At last laying my hands on scraping and filtering features (truly amazing thing, btw), I found that a crucial for me element is likely missing.

It is also not documented [here](https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#duplicationattributecheck-enum), so I suspect that it does not exist yet.

**Comment by sakkamade** [comment]
Well, I guess in my case I can adapt it to the `SameTitle` as well.
But do tell me if it's okay.

**Comment by martinrotter** [comment]
not exist yet, can be safely added



> Well, I guess in my case I can adapt it to the `SameTitle` as well.
> But please do tell me if it's okay.

Sure, you can do that, I will add sameid to. But your probably do not want `SameId`, you want `SameCustomId`.

`id` is rssguard's internal ID of the message while `customid` is ID of the message as was provided by the feed/service.

https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#messageobject-class

?

**Comment by sakkamade** [comment]
> while `customid` is ID of the message as was provided by the feed/service.

Yes, this one.

**Comment by martinrotter** [comment]
b35c97754

**Comment by sakkamade** [comment]
Thank you very much!

**Comment by sakkamade** [comment]
@martinrotter Does not seem to work?

**Comment by sakkamade** [comment]
Although my script does not look as neat, it does work with `SameTitle`, but not with the `SameCustomId`:

```js
const conditions = [
  	'title1',
  	'title2'
	];
function filterMessage() {
  if (msg.isDuplicateWithAttribute(MessageObject.SameCustomId)) {
    return MessageObject.Ignore;
  } 
  else if (conditions.some(el => msg.title.includes(el)) >= 1) {
    return MessageObject.Accept;
  } 
  else {
    return MessageObject.Ignore;
  }
}
```

Thoughts?

**Comment by martinrotter** [comment]
let me test your script, do you have any specific feed i can test with?

**Comment by martinrotter** [comment]
btw your `some` usage is not entirely correct as `some` return Boolean, not number

```js
else if (conditions.some(el => msg.title.includes(el))) {
    return MessageObject.Accept;
  } 
```

**Comment by sakkamade** [comment]
> do you have any specific feed i can test with?

Well, I use it with custom feed (and I certainly know that the ids remain constant), but it would take some hours of me to rewrite it here now. 
Only tomorrow, if you really need it. 



> btw your `some` usage is not entirely correct as `some` return Boolean,

Don't worry, my  JS knowledge is awfully basic, that part was something I adopted from stackoverflow, but thank you.

**Comment by sakkamade** [comment]
> time="  1557.194" type="debug" -> No messages to be updated/added in DB for feed '6'.

Oh, right. I forgot that it is a very specific filter for very specific feed... Later then.

**Comment by martinrotter** [comment]
> No messages to be updated/added in DB for feed '6'.

This means that filter rejected all messages as their duplicate check with custom ID revealed that they already are in the DB.

**Comment by sakkamade** [comment]
I am almost certain, however, that the fault is not there, since with `SameTitle` it works flawlessly, and the id and title of articles in that feed is identical.

**Comment by sakkamade** [comment]
When I say it does not work for me, I mean it does not work for me, please believe me.
You have seen the script and said that there is not any big issue about it, and I am quite confident with my feed. The rest goes tomorrow. 

By the way, the last time I tested it was with this commit https://github.com/martinrotter/rssguard/commit/2f39114e8abd5b3f1aaee196019a74598360e21b.

**Comment by sakkamade** [comment]
You know, it just occurred to me, that feed is RSS 2.0, and since have not really dealt with it I am not sure, but according to the first link I have just found https://validator.w3.org/feed/docs/rss2.html#hrelementsOfLtitemgt, the RSS 2.0 has `guid` instead of `id` element... ... Is that right? ...

**Comment by sakkamade** [comment]
I am apologise for taking your time.

**Comment by martinrotter** [comment]
@sakkamade 
RSS Guard in case of RSS 2.0 extracts "customID" from "guid".

https://github.com/martinrotter/rssguard/blob/master/src/librssguard/services/standard/rssparser.cpp#L37
