### ISSUE TITLE
Support a compile-time or a run-time option (or both) to choose between QTextBrowser and QtWebEngine

### ISSUE THREAD

**Issue by xmstspider** [martinrotter/rssguard#51]
#### Brief description of the issue.

Up to 3.2 (?), rssguard used QTextBrowser to preview RSS entries, without supporting the pictures. Some users want pictures, other can live without them. Therefore, it would be fine to provide an either compile-time or run-time option to use either the QTextBrowser or the QtWebEngine. The compile-time option would be preferred, as some distributions don't containt the qt5-qtwebengine package.

#### How to reproduce the bug?

1. Run version 3.2.x to use the QTextBrowser
2. Update to version 3.3.x if possible
3. The QtWebEngine is used

#### What is the expected result?

Both QTextBrowser and QtWebEngine options are supported through a compile-time or run-time option (or both)

#### What actually happened?

Only QtWebEngine is used in the 3.3.x version. therefore making this version impossible to build on some distributions (Fedora < 24).

**Comment by martinrotter** [comment]
![rssguard](https://cloud.githubusercontent.com/assets/1255302/17803767/a9e1b6b8-65f8-11e6-916d-1e54f1643337.png)
