### ISSUE TITLE
[BUG]: Tooltips in articles list are not displayed

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#511]
### Brief description of the issue

Tooltips are not displayed when I hover the articles in list.

### How to reproduce the bug?

1. Ensure the "Display tooltips for feeds and articles" in settings is checked
2. Hover the list of articles

### What was the expected result?

Tooltips to be shown.

### What actually happened?

They are not.

### Other information

Wanted to open a FR, thankfully found https://github.com/martinrotter/rssguard/issues/404.

Would never have thought to look for a tooltips toggle in settings... (It is checked by default.)

### Operating system and version

* OS: Arch Linux
* RSS Guard
Version: 4.0.3 (built on Linux/x86_64)
Revision: 2888458e
Qt: 5.15.2 (compiled against 5.15.2)

**Comment by martinrotter** [comment]
To my knowledge, list of **articles** does not in fact display any tooltips (not really needed? what should it display anyway?) except for column `Score` whose tooltip displays the exact numberical value of the score, for example `54.9` etc.

**Comment by sakkamade** [comment]
So it really should be a feature request after all....

> not really needed? what should it display anyway?

Feed tooltip the feed's name; title tooltip the article's title. I am only interested in these ones.

Since many feeds that I use have a very long names with informative part located behind, it is truly troublesome for me to understand the article of which feed is currently opened (when I view some category).

I hope this won't cause a performance issues? 
But if it actually will cause them. most important to me seems the feed tooltip.
