### ISSUE TITLE
[FR]: Tooltips for articles list

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#513]
### Brief description of the feature request

(Outcome of https://github.com/martinrotter/rssguard/issues/511.)

Since many feeds that I use have a very long names with informative part located behind, it is truly troublesome for me to understand the article of which feed is currently opened (when I view some category, for example).

---
I hope this won't cause a performance issues?

**Comment by martinrotter** [comment]
> I hope this won't cause a performance issues?

No issues.

**Comment by martinrotter** [comment]
c44d46e15

**Comment by sakkamade** [comment]
There are some truly amazing time tooltips now.

![dateguard](https://user-images.githubusercontent.com/62730422/135537046-66e38fab-0c67-4ef6-b1bc-4f19133cd59c.png)

([Epoch time - Wikipedia](https://en.wikipedia.org/wiki/Unix_time))

But I wonder what format should be placed there.

**Comment by martinrotter** [comment]
I think that epoch times are quite obvious for everyone, no need to change. At least there is no crazy formatting in between and everyone see the exact values.

Kidding of course.

2a172bf3e
