### ISSUE TITLE
[FR]: Allow resizing of "Read" and "Important" columns

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#514]
### Brief description of the feature request

This was bothering me for a while now, I believe after auto-resizing was fixed https://github.com/martinrotter/rssguard/issues/469 (or here https://github.com/martinrotter/rssguard/issues/435#issuecomment-872071189, to be percise), but these columns are just too wide, and they cannot be resized at all:

![image](https://user-images.githubusercontent.com/62730422/135428841-b68c09e2-9798-493c-9fba-6ec52d8f22bc.png)

Perhaps with some other icon themes they look nice, but not with `breeze`.

**Comment by martinrotter** [comment]
These specific column are set to "fit-to-contents" mode and the reason why you think they are wide is that the headers of those columns must be that wide to accomodate for sort order arrow too.

I could probably add allow those columns being resizable but it could introduce some cosmetic problems when sorting with those columns.

**Comment by sakkamade** [comment]
> it could introduce some cosmetic problems when sorting with those columns.

I can bear with them.

> those columns must be that wide to accomodate for sort order arrow too.

I do not remember seeing Qt application which does the same.

**Comment by martinrotter** [comment]
> I do not remember seeing Qt application which does the same.
> They just couldn't care less, and I support that.

I do not havve any special handling of that width in my app too, it just forces that size.

**Comment by martinrotter** [comment]
93ea31107

**Comment by sakkamade** [comment]
> I do not have any special handling of that width in my app too

I meant that "[...] they just couldn't care less _about cosmetic problems_."

**Comment by sakkamade** [comment]
Thank you!

**Comment by sakkamade** [comment]
This actually looks much better than I expected.
![image](https://user-images.githubusercontent.com/62730422/135535890-6ad91484-c70d-4134-9059-2ca0f4ae69df.png)

I expected it to look like this (Date column in example below):
![image](https://user-images.githubusercontent.com/62730422/135535989-c34a365d-582b-4a8d-b971-695b609ce979.png)

---
The `papirus` icon theme would look as following:

![image](https://user-images.githubusercontent.com/62730422/135536280-3a4ca1bc-6a3c-401f-b94f-7f83d6b19c12.png)

However, even in case with this theme, the arrow may take much less space without overlapping the icon:

![image](https://user-images.githubusercontent.com/62730422/135536426-5024a816-4cfa-4d8b-91f5-6f4e878d1132.png)

**Comment by martinrotter** [comment]
create separate ticket on custom arrow drawing @sakkamade

**Comment by sakkamade** [comment]
> create separate ticket on custom arrow drawing

You mean about "Date" column and such?
If so, no, it's fine. I am seeing it all the time, and here (in RSS Guard) it is not bothering at all.
