### ISSUE TITLE
[BUG]: 6a3b0edb: BazQux: on sync, Rssguard does not sync properly with feed items removed in BazQux itself

### ISSUE THREAD

**Issue by umbellipher** [martinrotter/rssguard#518]
### Brief description of the issue

6a3b0edb: BazQux: on sync, Rssguard does not sync properly with feed items removed in BazQux itself.

### How to reproduce the bug?

1. Access BazQux web page.
2. Read, mark read items.
3. Wait a few seconds for BazQux to register the new number of read/unread items.
4. Sync Rssguard.

### What was the expected result?

Items marked read in BazQux web page should disappear, on sync, from Rssguard if R is set to view only unread items, leaving the same number of feeds as in B.

### What actually happened?

Read items remain in place in Rssguard, and have to be marked read manually.

### Operating system and version

* OS: Windows 10 21H1 latest
* RSS Guard version: 6a3b0edb

**Comment by martinrotter** [comment]
If you mark some article as READ on Bazqux web interface, then the change should be noticed by RSS Guard next time you update the feed in RSS Guard and the article should be visible as READ in RSS Guard too.

I will try your steps to see if can reproduce.

**Comment by martinrotter** [comment]
I checked it and did this:
1. Went to web gui.
2. Marked one message as unread -> read.
3. Opened rssguard and updated feed.
4. Message is now READ in RSS Guard too.

Therefore cannot reproduce the issue.
