### ISSUE TITLE
[BUG]: Article List Row Height

### ISSUE THREAD

**Issue by qcybb** [martinrotter/rssguard#528]
### Brief description of the issue

Setting the value to anything but -1, 0 or 1 shrinks the font size down to an unreadable size.

It also does not adjust the row spacing between news entries which I am looking to do.

Maybe I'm understanding the option correctly?

### How to reproduce the bug?

Adjust the "Article List Row Height" setting to anything but 1, 0 or 1.

### What was the expected result?

Adjust the row spacing between news entries

### What actually happened?

Shrink the font size down to an unreadable size and does not adjust the row spacing between news entries.

### Operating system and version

* OS: Windows 10 Home
* RSS Guard version: 4.04

![rssguard](https://user-images.githubusercontent.com/16991734/139711928-f983aec0-e9e5-424e-80e1-a46cc61ac229.png)

**Comment by akinokonomi** [comment]
What values did you try to set it to exactly?

E.g. `30` (on Linux):
![image](https://user-images.githubusercontent.com/91767492/139717152-a56ff32c-b0c3-478b-bc8b-02c209a36836.png)

`40`
![image](https://user-images.githubusercontent.com/91767492/139717403-caf1ef0c-db92-483b-97e4-0a4482b08661.png)

**Comment by qcybb** [comment]
I tried 0-12 and then stopped. I guess I misunderstood the option and what it did.

Is there an option to increase the spacing between rows? They are too close together.

**Comment by martinrotter** [comment]
> 
> 
> I tried 0-12 and then stopped. I guess I misunderstood the option and what it did.
> 
> Is there an option to increase the spacing between rows? They are too close together.

It seems like a bug. There are two options:

**Article list row height** which should set height of each row i pixels.

**Article list font** where you can set font type/size.

Using those two features you should be set the list size exactly, including padding etc.

Let me check.

**Comment by martinrotter** [comment]
Found a bug, fixing.

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/139812230-d1cfd0ee-3e6c-4134-920c-9e212e1a7b2a.png)

Fixed, now, both settings mentioned above do actually work well together. You can set your row height for example to 20 and font size to 15 to create padding. See screenshot with both lists row heights and fonts customized.

**Comment by martinrotter** [comment]
71dd65aef

**Comment by akinokonomi** [comment]
> [71dd65a](https://github.com/martinrotter/rssguard/commit/71dd65aef991b09a6bc6ece62144699432d3d3c4)

Can confirm. "Article List Row Height" works only for _line height_ now.

**Comment by martinrotter** [comment]
@akinokonomi Wait so you say issue is not solved? I do not entirely understand what you try to say.

**Comment by akinokonomi** [comment]
For me (Arch Linux), when I changed the value of "Article list row height" the font size would also change. 
So no, now it works right.
