### ISSUE TITLE
[FR]: Uninstaller should detect if an instance is running

### ISSUE THREAD

**Issue by vlakoff** [martinrotter/rssguard#529]
After uninstallation, I noticed the  `C:\RSS Guard` folder was still present, then that there was a running instance.

The uninstaller should detect if an instance is running, and if so, offer to close it programmatically.

Refs in the NSIS documentation: [Check whether your application is running](https://nsis.sourceforge.io/Check_whether_your_application_is_running)

**Comment by martinrotter** [comment]
Indeed.

**Comment by martinrotter** [comment]
fixed, uninstaller now checks if "rssguard.exe" is running and offers to abort uninstallation
