### ISSUE TITLE
Can't start RSS Guard 3.3.3 under Windows XP

### ISSUE THREAD

**Issue by Gooberslot** [martinrotter/rssguard#53]
#### Brief description of the issue.

Trying to launch RSS Guard under Windows XP results in "rssguard.exe is not a valid Win32 application" message.

---------------------------
OK   
---------------------------

#### How to reproduce the bug?

1.  Try to launch program under Windows XP.
2. 
3. 

#### What is the expected result?

Program should run.

#### What actually happened?

Program doesn't run.

#### Other information (logs, see Wiki)

I'm using the portable (7z) version of RSS Guard.

**Comment by martinrotter** [comment]
Does 3.3.2 work under XP? If no, which last version worked?

**Comment by martinrotter** [comment]
BTW, bug is fixed, but note that internal web browser (QtWebEngine module) will not work under Windows XP. This OS is not supported. You must compile RSS Guard with `USE_WEBENGINE=false` switch for Windows XP.

**Comment by Gooberslot** [comment]
Does this mean you're going to start compiling a special version for XP or are you planning on dropping XP support?

**Comment by martinrotter** [comment]
I will probably not compile special version for XP, I am not entirely decided. RSS Guard now should run on XP without any problems with given WebEngine switch. I do not plan support Windows XP anymore, but I expect that current and future RSS Guard versions will work on XP.

So you will probably have to compile RSS Guard by yourself with `USE_WEBENGINE=false` switch. You need to have Qt 5.6+ and Visual Studio (I recommend 2013) installed. Then you need to read Wiki section, which gives some info on compilling.

I am really not sure If I will compile both versions, but maybe I will.
