### ISSUE TITLE
[FR]: If date = today - show time only

### ISSUE THREAD

**Issue by qcybb** [martinrotter/rssguard#530]
### Brief description of the feature request

Would it be possible to have an option to only show the time under the "Date" column - if the news came in today?

For example : 

8:27 AM
7:24 AM
11/1/21 4:53 PM
11/1/21 3:21 PM
11/1/21 12:05 PM

I've seen this method used in other applications (Thunderbird email), and it help makes today's stuff stand out.

**Comment by martinrotter** [comment]
will implement

**Comment by qcybb** [comment]
Thank you!

**Comment by martinrotter** [comment]
1. Should feature be switchable.
2. Would you prefer to see for example "15 minutes ago" instead of "7:00" for fresh messages?

**Comment by qcybb** [comment]
It should be "7:00" format for fresh messages. That is what everyone else is doing.

**Comment by akinokonomi** [comment]
> Should feature be switchable.

Of course.

> It should be "7:00" format for fresh messages. That is what everyone else is doing.

Don't just say "everyone." I remember no one doing like that. Give some examples.

**Comment by qcybb** [comment]
QuiteRSS, Thunderbird email, etc do "7:00 AM" for todays news/email.

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/140028458-8b42e884-08de-48ee-9f1e-477e357c3c8c.png)
![image](https://user-images.githubusercontent.com/1255302/140028506-76d5ab24-d2bc-46d9-8adb-0e9e2d2192e4.png)

**Comment by martinrotter** [comment]
> 
> 
> QuiteRSS, Thunderbird email, etc do "7:00 AM" for todays news/email.

Issue is fixed, also, Gmail does it same way. See above screenshots.

**Comment by qcybb** [comment]
Is it possible to have it in 12 hour format? and include the AM or PM?

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/140029756-77319c92-8ecb-4868-a80b-c7e341185410.png)

**Comment by qcybb** [comment]
Oh my mistake, the option is already there.

Thank you for all your had work!
