### ISSUE TITLE
[FR]: Option to keep only recent articles on fedd (based on date / quantity)

### ISSUE THREAD

**Issue by Ac314** [martinrotter/rssguard#531]
### Brief description of the feature request

Now there is no option to automatically "clean up" feeds to keep only recent articles (and delete the old ones). Without it there is no way to keep the feeds clean except of doing it by hands (or maybe I cannot find the way to do it).

Two options should be available: 
1) Keep only last XXX articles
2) Keep articles only for XXX days
They can be applied simultaneously or separately. 

Auto clean process could be performed differently depending on the options set.

For "Keep articles only for XXX days": auto clean process is performed while feed is updated. When feed is checked by the application:
1) If there are articles in the feed which are older than XXX days (based on their publishing dates) then they are not downloaded.
2) After feed updating is finished the application deletes the feeds older than XXX days from the database.

For "Keep only last XXX articles": auto cleaning can be performed either the same way (during the feed updating) or application can do it periodically in the background (for example, in idle time).

**Comment by akinokonomi** [comment]
Does "Show unread articles only" not satisfy your needs? In this case you needn't clean up all that often.

**Comment by martinrotter** [comment]
I agree with @akinokonomi. Do you/we really really need "automatic" cleanup of feeds? I do not believe so as RSS Guard should handle tens of thousands of articles just fine and once a month you can cleanup manually via "Cleanup database" feature.

**Comment by Ac314** [comment]
1) > I agree with @akinokonomi. Do you/we really really need "automatic" cleanup of feeds? 

Well for me this is definitely a very useful feature because sooner or later I will just forget to clean-up manually... And I guess I am not alone here. So making it to clean up automatically should be good idea (at least for me) - just tune it with some options and forget about it.

BTW maybe it also can bу implemented by command line - like the application performs cleaning when started (according to the options set) and runs as usual after that (or, as an option, just exit after cleaning).

And regarding the clean-up options: it seems it does not have an option "Keep only last XXX articles". It can clean old articles only based by "days old".

2) Regarding the cleaning during the feed update - maybe it can be achieved by message filtering? I am not sure but maybe it is possible to just purge all messages based on the publishing date or/and message quantity?

**Comment by akinokonomi** [comment]
I guess it should be mentioned that there is an option of "Remove all read articles from all feeds on application exit" (Settings -> Feeds & articles -> Articles).

**Comment by martinrotter** [comment]
> 2\. Regarding the cleaning during the feed update - maybe it can be achieved by message filtering? I am not sure but maybe it is possible to just purge all messages based on the publishing date or/and message quantity?

No, at that point only new/updated articles come through that mechanism.

I will add some of suggested features to cleanup messages automatically.

**Comment by Ac314** [comment]
OK, thank you.

**Comment by martinrotter** [comment]
This was implemented already in previous versions, based on date.

**Comment by Ac314** [comment]
Could you please clarify how this can be achieved in the current version (I did not follow the development process closely in the past months so I definitely do not know all the new features)? Cleanup can be performed automatically? Filters can be applied to old articles too? Or maybe there are some other means for this functionality?
