### ISSUE TITLE
[FR]: Mark all articles read in Toolbar for Articles List

### ISSUE THREAD

**Issue by snakyjake1** [martinrotter/rssguard#533]
### Brief description of the feature request

I would like to see the "Toolbar for articles list" have a button to "Mark all articles as read".

This might be more intuitive than having the button in the "Toolbar for feeds list".

It's also more intuitive to have the buttons represent the action in the Article Pane.  

I also don't want the feature to be confused with marking all articles in all feeds as read.

**Comment by akinokonomi** [comment]
> "Mark all articles as read"

If by that you mean that you want to mark all articles __of selected feed__ as read, there is a button that does just that, 
called "Mark selected item read".

You can change buttons in: Settings -> User interface ->Toolbars.

**Comment by martinrotter** [comment]
Yes, that. There is also a button to make ALL read. Closing.
