### ISSUE TITLE
[FR]: Save article

### ISSUE THREAD

**Issue by snakyjake1** [martinrotter/rssguard#534]
### Brief description of the feature request

I would like a feature to save the article.  Also, the saved article cannot be automatically deleted/cleaned.

**Comment by akinokonomi** [comment]
> I would like a feature to save the article.

You mean saving them locally to review them offline later?

> Also, the saved article cannot be automatically deleted/cleaned.

As far as I know, in RSS Guard, nothing is cleaned/deleted automatically. You mean removed from cache? Could you clarify?

**Comment by martinrotter** [comment]
Once you fetch articles in RSS Guard, they will stay there forever. You can cleanup via `Tools -> Cleanup database` but it should not really be needed.

**Comment by akinokonomi** [comment]
> You mean removed from cache?

Just to clarify, here I meant the cache of Qt Webengine (images, etc.).

**Comment by snakyjake1** [comment]
More info...

![image](https://user-images.githubusercontent.com/8312560/151043519-ec729284-84d3-4f36-b9f7-5deacf9d05a2.png)

**Comment by akinokonomi** [comment]
> More info...

@snakyjake1, Aw, so this is what you meant.

1. I guess "starred" should be _important_. True.
2. Currently there is no such option. Why would you need that?
3. 1. You can mark articles _important_, and uncheck "Remove all starred articles" checkbox. _Important_ articles will remain.
![image](https://user-images.githubusercontent.com/91767492/151067906-d03d4743-0a0a-4572-9f12-a1a93ed086a5.png)
     2. You can mark **all** articles read, then mark some artcles unread and/or important, and then **only** check "Remove all read articles" (and "Optimize database file"). Unread and/or _important_ articles will remain.
