### ISSUE TITLE
[FR]: Indicate image position within text in nowebengine

### ISSUE THREAD

**Issue by senseiski** [martinrotter/rssguard#538]
### Brief description of the feature request

Hi, I would like to suggest adding the option to indicate where within the text an image is actually located instead of just linking it at the end. That feels like a decent compromise b/w not displaying images in nowebengine and how other aggregators are doing it. That's the way for example Newsboat is approaching it (see screenshot for comparison):
![Screenshot from 2021-11-18 09-50-01](https://user-images.githubusercontent.com/6433919/142374748-76f59642-6d6b-484a-be5a-cc5d94895158.png)
For articles, where images are more relevant to the content that seems like a decent approach. In my use case, I've added an image viewer as a custom tool so I could load images - but it doesn't really work if I have no idea where in the article they were located.

**Comment by martinrotter** [comment]
Perhaps I should place links with `[image]` placeholder directly into the place were they belong instead of cummulating them at the end of article?

**Comment by senseiski** [comment]
That works too, although might be ugly if the url is too long.

**Comment by martinrotter** [comment]
#669

**Comment by martinrotter** [comment]
Images are now directly visible even in nonwebengine version. I will add option to display placeholders instead of images and also polish the overall feature-set.

Pls test with dev. build.
