### ISSUE TITLE
[FR]: Yahoo Mail support?

### ISSUE THREAD

**Issue by qcybb** [martinrotter/rssguard#541]
### Brief description of the feature request

Any plans on adding support for Yahoo mail?

https://developer.yahoo.com/oauth2/guide/

**Comment by martinrotter** [comment]
Hello @qcybb.

RSS Guard is primarily feed reader. It does include simplistic Gmail plugin, but it is not used much when compared with other plugins. I really do not believe that adding plugin for another emailing platform is good idea. Or are you interested in some of their other APIs?

Expand...

**Comment by qcybb** [comment]
I understand. I just saw you supported Gmail using Oauth, and thought Yahoo mail could be an easy addition.

I personally use both mail services, and was looking to have a "all in one" solution for checking RSS and mail.

**Comment by martinrotter** [comment]
Yes, while OAuth2 can be easily used, the actual API would take time to implement.

**Comment by qcybb** [comment]
Yeah, I wasn't sure if a lot of the existing code could be reused. It was just an idea.

Feel free to close this.

**Comment by martinrotter** [comment]
Well, a lot of code would be reused, but as I said, I personally do not use Yahoo, perhaps if there will be much greater interest of many users...
