### ISSUE TITLE
[BUG]: Space in RSS link

### ISSUE THREAD

**Issue by Shinkir0** [martinrotter/rssguard#542]
### Brief description of the issue

In the 4th version of the program, if there are spaces in the RSS link, the feed is not updated

### How to reproduce the bug?

if the spaces are replaced by %20, then the feed is updated normally.
The same situation is with the symbol | if replaced by %7C
### What was the expected result?

In the 3rd version of the program, spaces in the link were handled normally

### What actually happened?

RSS links with spaces do not work

### Operating system and version

* OS: Windows 10 Pro 21H1
* RSS Guard version: 4.0.4. and in the last 4.1 too

**Comment by martinrotter** [comment]
Where is the space, in the end of link? in the middle? Post example URL which does not work now.

**Comment by Shinkir0** [comment]
I'm not sure that it's worth posting the real link here,. because it's NSFW
but its structure looks like this, the problem is in the additional parameters at the end, acting as a filter on the site
http://site.net/forum/rss.php?nm=2015|2016 -DVDRip -TVrip -360p -News -Hotel -Yulia -Guide -k2s -Ron -rus&f=60

**Comment by akinokonomi** [comment]
> I'm not sure that it's worth posting the real link here,. 

Among other things, this would ease testing.

I think you could send it to: rotter (dot) martinos at gmail (dot) com (Help -> About application)

@martinrotter, Is your email still active?

**Comment by martinrotter** [comment]
post full URL, we are grown adults, not children

**Comment by Shinkir0** [comment]
well good with such filters, I think it won't show anything hard :)
https://pornolab.net/forum/rss.php?nm=2015|2016 -DVDRip -TVrip -360p -News -Hotel -Yulia -Guide -k2s -Ron -rus&f=60

**Comment by martinrotter** [comment]
I reproduced the issue, problem is that "I" character is not really allowed in URLs, anyway. Thing is that modern browsers do not really sanitize URLs that much and RSS Guard was following RFC very strictly.

I made minor adjustments and now it works.

https://pornolab.net/forum/rss.php?nm=2015|2016 -DVDRip -TVrip -360p -News -Hotel -Yulia -Guide -k2s -Ron -rus&f=60
