### ISSUE TITLE
[FR]: "Next important" action for the toolbar

### ISSUE THREAD

**Issue by akinokonomi** [martinrotter/rssguard#544]
### Brief description of the feature request

Similar to "Next unread article", it would be nice to have "Next important" (article) action.

**Comment by martinrotter** [comment]
do you want that action to work "across" feeds? so if selected item has no important messages, then next one is auto-selected?

**Comment by akinokonomi** [comment]
Yes, that's right.

**Comment by martinrotter** [comment]
Well, this would be actually way more difficult. :) But I might add it, side effect will be that info in "counts" column in feed list would be enhanced with counts of important articles within items.

**Comment by akinokonomi** [comment]
I see. Well, it just seemed to me a nice and simple idea. 
But if from your point of view things would become overcomplicated, I rather close it?

**Comment by martinrotter** [comment]
No, keep that open. Will implement some day in the future.

**Comment by akinokonomi** [comment]
#678 looks like a much better idea to me.

Closing it.
