### ISSUE TITLE
[FR]: Keyboard shortcuts to focus search input boxes 

### ISSUE THREAD

**Issue by akinokonomi** [martinrotter/rssguard#545]
### Brief description of the feature request

Similar to #408, I'd like to have keyboard shortcuts to focus articles (and feeds) search input boxes.

(Likely "Article search" box can be set to `Ctrl+f` by default.)

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/217466693-3382ff0b-15e0-49a8-813f-c37a714324a1.png)
