### ISSUE TITLE
[BUG]: Feed categories collapse when quitting the application with an active search filter

### ISSUE THREAD

**Issue by akinokonomi** [martinrotter/rssguard#546]
### Brief description of the issue

Searching for some feed, and then quitting the RSS Guard without removing the search word will collapse the categories that were filtered out on the next startup.

### How to reproduce the bug?

1. Have some categories in feeds list
2. Place "Feeds search box" somewhere in toolbar
2. Type some "word1" which is present in feed name of one of the categories but not in other
3. Hit `Ctrl+q`
4. Start RSS Guard: all categories except the one with "word1" are collapsed

### What was the expected result?

For categories to remain open, if they were.

### What actually happened?

Categories collapsed.

### Operating system and version

* OS: Arch Linux
* RSS Guard
Version: 4.1.0 (built on Linux/x86_64)
Revision: 8ae02930
Qt: 5.15.2 (compiled against 5.15.2)

**Comment by akinokonomi** [comment]
Also, when I enable/disable "Show unread items only" option, every feed category expand. 
State of previously collapsed categories does not save. 

Is that related, or should be opened as a separate issue?

**Comment by akinokonomi** [comment]
> when I enable+disable "Show unread items only" option, every feed category expand.

Was fixed with bdc00d5, it _was_ related after all.

Thank you.

**Comment by umbellipher** [comment]
So how, with bdc00d5, do I now set things so that, on opening and syncing, and syncing later thereafter, all feeds containing unread items are expanded, but those with no unread items remain unexpanded (the way it worked before the latest dev version)?

**Comment by martinrotter** [comment]
@umbellipher Can you compile list of steps to take to reproduce the situation?

**Comment by umbellipher** [comment]
@martinrotter 

1. Open app with: (a) Feeds -> 'Show unread items only' toggled to show unread items only; Feeds -> 'Automatically expand when selected' ticked; Feeds -> 'Show tree expanders' ticked.
2. Sync, several times.
3. I get what's depicted in Image1.
![Image1](https://user-images.githubusercontent.com/59395777/148557511-3e8a887c-50cf-46e1-95a7-0979dc954e65.png)

Namely, some unread feeds are expanded, some not.

If I uncheck 'Show tree expanders' and sync again, the unexpanded unread feeds remain unexpanded.

Uncheck, 'Automatically expand...' and resync: same outcome.

Leave 'Automatically expand...' unchecked but tick ''Show tree expanders' and resync: same outcome.

In an ideal world, the app would pick up all unread feeds, whether new (blue) or from a previous sync (black) - as it used to - and expand them upon sync ending.

Does that help?

**Comment by akinokonomi** [comment]
`Show unread items only`
In this instance, "items" refer to accounts, categories, and feeds; not just feeds.

> Namely, some unread feeds are expanded, some not.

> In an ideal world, the app would pick up all unread feeds, whether new (blue) or from a previous sync (black) - as it used to - and expand them upon sync ending.

I think current behaviour is the correct one. 

I wouldn't want to see every category that contains unread feeds expand, just because I enabled _Show unread items only_ option.

Just so you know, what  RSS Guard actually used to expand were _all_ categories, not some chosen ones.

> Uncheck, 'Automatically expand...' and resync: same outcome.

Why would you expect otherwise?
In that case, item (category or account) automatically expands when you select it, and it also works correctly.

> Leave 'Automatically expand...' unchecked but tick ''Show tree expanders' and resync: same outcome.

Neither of those options are related to that, so this result is expected.

Ability to have multiple categories goes with idea that only some can be expanded and some collapsed,
But if you always use _Show unread only_, why can't you just leave all categories expanded?

---
Every fix breaks someone's workflow :smile: 

But why you call buggy behaviour "ideal world" is still strange to me.

**Comment by akinokonomi** [comment]
It is interesting, but I can't reproduce what I described here https://github.com/martinrotter/rssguard/issues/546#issuecomment-1003268998, even with this b743c72a commit... 
In other words, with that commit I'm seeing the same as @umbellipher sees now, but the main issue https://github.com/martinrotter/rssguard/issues/546#issue-1064024087 is still reproducible.

It could be that there were some other conditions.

**Comment by umbellipher** [comment]
@martinrotter 

> Every fix breaks someone's workflow 😄
> 
> But why you call buggy behaviour "ideal world" is still strange to me.

I expressed myself badly: I should have said "*my* ideal world". And by that, I guess I meant 'what I have got used to seeing happen'!

If the new workflow is to see unread feeds open as I hotkey through unread feeds, then that's just fine: I am already getting used to it, and it does make a lot of sense.

(I am always saying how much I value this app, and my clumsy wording earlier should not be understood to detract from that :satisfied:.)

**Comment by martinrotter** [comment]
Don't worry I will check your steps tonight and report back

**Comment by martinrotter** [comment]
> It is interesting, but I can't reproduce what I described here [#546 (comment)](https://github.com/martinrotter/rssguard/issues/546#issuecomment-1003268998), even with this [b743c72](https://github.com/martinrotter/rssguard/commit/b743c72a040733a2ea2846af6b92c225d7c93246) commit... In other words, with that commit I'm seeing the same as @umbellipher sees now, but the main issue [#546 (comment)](https://github.com/martinrotter/rssguard/issues/546#issue-1064024087) is still reproducible.
> 
> It could be that there were some other conditions or there were some changes in Qt.

Wait so the big is not fixed?

**Comment by akinokonomi** [comment]
> Wait so the bug is not fixed?

It is. But I can't reproduce it even with older version anymore.

**Comment by akinokonomi** [comment]
Haa.

@martinrotter, 

Well, this is how it used to be (https://github.com/martinrotter/rssguard/issues/546#issuecomment-1003268998):
Press U -> All categories expand

Now (https://github.com/martinrotter/rssguard/issues/546#issuecomment-1007446139), and with older versions, too, also now:
Press U -> categories' state remain as is: Categories which were expanded remain expanded, other not.

**Comment by akinokonomi** [comment]
Oops, I'm sorry, please nevermind those comments, my memory plays tricks on me. This is the bug I've seen:

Press U + U -> All categories expand. That's it.

The behaviour described here https://github.com/martinrotter/rssguard/issues/546#issuecomment-1007446139 I've never seen before, therefore was unable to reproduce it.

Used this commit 0d046d6b

**Comment by akinokonomi** [comment]
> So how, with bdc00d5, do I now set things so that, on opening and syncing, and syncing later thereafter, all feeds containing unread items are expanded, but those with no unread items remain unexpanded (the way it worked before the latest dev version)?

@umbellipher, What version/commit exactly that you've seen it work that way?

**Comment by umbellipher** [comment]
@akinokonomi, all versions before bdc00d5, I think.

Perhaps I am explaining badly. 1) Say I have a folder in the left pane: "News". 2) Within News, I have say 20 feeds. 3) I do a sync with the underlying API, in my case BazQux. 4) There are four News feeds which have unread articles, after sync. 16 have no new unread articles.

The way it worked before was: after sync, with it set to view unread items only, and without doing anything more, the folders with unread articles in their feeds - in this case, News - would expand to show the four feeds, in the left pane, which contained new unread articles. Not the 16 with no unread articles, of course. I could then progress through each folder and feed with hotkeys so as to display each feed in turn in the left pane, with all its unread articles in the right pane. Another press of 'Read next article' would display the next item's contents in the lower pane, for me to open in external browser, or mark read, etc.

Now, the News folder remains unexpanded until I hit the 'Read next article' hotkey, when News expands, but the other folders with unread feeds remain unexpanded, until I work by hotkey to that folder, when it expanded.

All I am saying is: that is new workflow for me.

**Comment by akinokonomi** [comment]
> The way it worked before was: after sync, with it set to view unread items only ... the folders with unread articles in their feeds ... would expand to show the four feeds, ... which contained new unread articles

This is exactly how I understood you, but I've never seen it work like that before, so I guess that was some Windows thing, as I am on Linux.

---

At the same time, I noticed regression (bdc00d5):

@martinrotter, 

**Condition**

1. Have _Next unread article_ action in toolbar, or assigned shortcut

**Steps**

1. Have feed with unread articles
2. Click the latest (bottommost) article, leaving some unread articles above
3. Use _Next unread article_ action
4. See focused the first unread article of **current** feed

**Comment by martinrotter** [comment]
> @martinrotter
> 
>     1. Open app with: (a) Feeds -> 'Show unread items only' toggled to show unread items only; Feeds -> 'Automatically expand when selected' ticked; Feeds -> 'Show tree expanders' ticked.
> 
>     2. Sync, several times.
> 
>     3. I get what's depicted in Image1.
>        ![Image1](https://user-images.githubusercontent.com/59395777/148557511-3e8a887c-50cf-46e1-95a7-0979dc954e65.png)
> 
> 
> Namely, some unread feeds are expanded, some not.
> 
> If I uncheck 'Show tree expanders' and sync again, the unexpanded unread feeds remain unexpanded.
> 
> Uncheck, 'Automatically expand...' and resync: same outcome.
> 
> Leave 'Automatically expand...' unchecked but tick ''Show tree expanders' and resync: same outcome.
> 
> In an ideal world, the app would pick up all unread feeds, whether new (blue) or from a previous sync (black) - as it used to - and expand them upon sync ending.
> 
> Does that help?

If I understand correctly, previous behavior was, that when you had "show unread only" enabled and some feed got new unread articles, then it became visible and was eventually expanded if under some category? Now after change I made those are actually not expanded, right?

**Comment by umbellipher** [comment]
@martinrotter 



> If I understand correctly, previous behavior was, that when you had "show unread only" enabled and some feed got new unread articles, then it became visible and was eventually expanded if under some category? Now after change I made those are actually not expanded, right?

Essentially, yes. After a sync, all the feeds containing unread articles auto-expanded in the tree, under the category folder which contained them - and only them. So that I could then see what feeds with unread articles were present, without further action.

**Comment by martinrotter** [comment]
> The way it worked before was: after sync, with it set to view unread items only, and without doing anything more, the folders with unread articles in their feeds - in this case, News - would expand to show the four feeds, in the left pane, which contained new unread articles

YES. I get it now. The reason this actually worked was that there was a "bug" in the implementation. LET ME fine tune the behavior.

Thing is that there are now two filtering mechanisms which should cooperate: "unread-only" and "regexp" - I basically agree that if some item is hidden (has no unread items and/or not regexped etc.) and at some point becomes suddenly visible (unread articles arrive etc. - filtering conditions change) - then the items should be expanded to really become visible -> this already works when just regexping but not when changind "unread-only" - let me debug.

**Comment by martinrotter** [comment]
OK, there are questions and points to take:

- if user does not have any filtering enabled (no search string and show unread only NOT enabled) - changes made in expand states are saved, this is clear
- if user has regexp filtering enabled and tweaks search string (or has show-unread-only items enabled), then he naturally would expect all matched items to expand themselves and this expand state change should NOT be saved, right?
- if user has ONLY show unread only enabled, then all matching items should also expand themselves and this expand state change should NOT be saved, right?
- if user switches of filtering (clears search string and/or disables show-unread-only option) expand states should be reset to last saved state?

**Comment by umbellipher** [comment]
@martinrotter 

> OK, there are questions and points to take:
> 
> * if user does not have any filtering enabled (no search string and show unread only NOT enabled) - changes made in expand states are saved, this is clear

In this case, the current outcome is that all category folders are displayed, unexpanded, in LH pane, with those with unread feeds in bold.

Old practice used to be: each and every category folder - with or without unread feeds - would auto-expand, after a wait of a few seconds, so as to display each feed in the category folder. This no longer happens.

> * if user has regexp filtering enabled and tweaks search string (or has show-unread-only items enabled), then he naturally would expect all matched items to expand themselves and this expand state change should NOT be saved, right?

Yes. I have checked that I have nothing in the search box.

> * if user has ONLY show unread only enabled, then all matching items should also expand themselves and this expand state change should NOT be saved, right?

In this case, *'Next unread article'* moves me to the first of the unread feeds, expanding that and only that category folder in LH pane.

If I find only one unread item in that feed in RH pane, I hit *'Next unread article'* again. The feed in question disappears from the left pane, and I am moved onto the next feed which contains unread article(s).

If there is more that one unread item in a given feed in RH pane, I hit *'Mark selected item read (Mark all messages (without message filters) from selected items as read.)'*. The previously unread items disappear from the RH pane, the feed name in the LH pane is no longer in bold, I hit *'Next unread article'*, and the now read feed disappears from the tree, and the next unread item in the next unread feed is selected in RH pane, is unbolded, and its contents appear in the text box below.

The only difference between this current flow, and the the flow which occurred before, is that:
a) when *'Show unread items only'* is selected,  **unread feeds are no longer auto-expanded under their (unread) category folder in the tree** in the LH pane, after a sync.
b) when *'Show unread items only'* is UNselected, **all feeds are no longer auto-expanded under their category folder in the tree** in the LH pane.

(It is easier to do than explain!.)

> * if user switches of filtering (clears search string and/or disables show-unread-only option) expand states should be reset to last saved state?

Yes, I think so.

**Comment by martinrotter** [comment]
I see. I will just try to iteratively make some changes and you will review them, it is quite hard to explain all side cases and technical problems associated.

**Comment by martinrotter** [comment]
@umbellipher 

70d915f - test devbuild when compiles and let me know.

**Comment by umbellipher** [comment]
Yes, unread feeds auto-expand now when sync finishes. Thanks. Less than 30 seconds to sync 760 or so feeds also. Thank you so much for your responsiveness.

**Comment by martinrotter** [comment]
So now, from your point of view, issue is fully solved?

**Comment by umbellipher** [comment]
It is, thank you!

**Comment by martinrotter** [comment]
OK, @akinokonomi, check latest devbuild too and report back.

**Comment by akinokonomi** [comment]
> 1. Have feed with unread articles

_Multiple_ feeds, is what I meant.

> 2. Click the latest (bottommost) article, leaving some unread articles above

It is also essential to leave some another feed with unread articles below (or above) selected feed.

---

Basically, instead of moving to next feed that also has unread articles, _Next unread article_ action loops in currently selected feed until it has no unread articles.

---

@martinrotter, No, I still see it with 6cbcef3e, but right now I am also able to see the same so far as 24db7c53 goes, and even with 4.0.4 from Community Arch Repository, with clean config each time. 

I think it has to do with something else, though I am also unsure whether it already worked like that at the time. 

Somehow, there seem to be too many things I can't test properly at the moment.

I can give no more data, so I think this can be closed.

**Comment by martinrotter** [comment]
post your thoughts about "next unread article" as separate ticket....

**Comment by akinokonomi** [comment]
> I think this is actually intented behavior - "next unread article" - why it should move to next feed when there are still unread articles in the current one?

Aw! Just tried a7410954 on Windows 10, and it works the same. I guess I mixed it up with some other application.
