### ISSUE TITLE
[BUG]: Adding RSS request a Proxy ?

### ISSUE THREAD

**Issue by martiniturbide** [martinrotter/rssguard#548]
### Brief description of the issue

Hi

I'm new trying this software. I want to add some RSS feeds, but when I "Add Account" it asks me for a Proxy. I'm not sure if I'm doing it right. 

### How to reproduce the bug?

Add Acount
Select RSS
A Proxy requesting window appear. 

### What was the expected result?

I was expecting a place to put the RSS URL

### What actually happened?

It asks me for a proxy server with userid and password. 

### Operating system and version

* OS: Windows
* RSS Guard version: rssguard-4.0.4-9855b8a5-nowebengine-win64.exe

**Comment by akinokonomi** [comment]
Yeah, it certainly is weird, but you can leave it at _System proxy_ and just click _OK_, so RSS Guard will follow the proxy settings of your system, if any.

You can also choose _No proxy_, which can be selected by clicking the combo box beside the _Type_ for RSS Guard to bypass even the system proxy.
 
As for place to put RSS URL, it can be done afterwards by right-clicking your account name, e.g. _Username (RSS/ATOM/JSON)_, and using _Add new feed_ action in the opened context menu. 
This action can as well be assigned to some keyboard shortcut in settings.

**Comment by martiniturbide** [comment]
Yes, I didn't understood that you needed first to create a "service account" and later register the RSS feed inside it. Now I get it, but it is weird that proxy question there.

**Comment by akinokonomi** [comment]
It only shows up once when user creates a new account, so I think it's fine.

**Comment by martinrotter** [comment]
Once you "Add account" then account's setup dialog shows up. In case of classic RSS/ATOM/JSON acccount there is only optional proxy to set up. Other account types, however, have sometimes way more ellaborate setup dialogs.
