### ISSUE TITLE
Switch from QMediaPlayer to QSoundEffect for notification sound

### ISSUE THREAD

**Issue by danfe** [martinrotter/rssguard#551]
In 5c5a5b0, notification sound had been improved by making its volume configurable (and setting it to 50% by default). Previously, the notification sound was indeed a bit too loud. :-)

However, please consider using [QSoundEffect](https://doc.qt.io/qt-5/qsoundeffect.html) class instead, as QMediaPlayer does not work if Qt5 _multimedia_ package was built without GStreamer support, complaining to the console:

```
defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
```
While QSound and QSoundEffect classes work with just core sound backend like ALSA or OSS.

The [patch](https://cgit.freebsd.org/ports/tree/net/rssguard/files/patch-src_librssguard_miscellaneous_notification.cpp) is ready and tested.

**Comment by martinrotter** [comment]
Fixed RN. :)

94585e5f9

**Comment by danfe** [comment]
I think you've missed one thing upon merging my patch: when using `QSoundEffect` API, its `setVolume()` method takes [real argument, not integer](https://doc.qt.io/qt-5/qsoundeffect.html#setVolume).  My code used `static_cast<qreal>(m_volume) / 100`, your similar code below uses implicit type promotion as `(m_volume * 1.0f) / 100.0f`, but either way, currently `*.wav` notification sounds play at full volume.
