### ISSUE TITLE
[FR]: -no-webengine parameter

### ISSUE THREAD

**Issue by ImportTaste** [martinrotter/rssguard#554]
### Brief description of the feature request

I would like to be able to launch rssguard.exe with the -no-webengine parameter to have it function identically to the nowebengine builds.

To prevent user error, parameter aliases `-nowebengine` & `-no-web-engine` could be included, and it wouldn't be a bad idea to add `-no-singleinstance`, `-nosingleinstance`, `-no-debugoutput`, and `-nodebugoutput` as well.

**Comment by martinrotter** [comment]
First, I completely disagree with "To prevent user error..." part and I do not plan to implement that as literally no other SW with CLI does not offer that feature.

Why don't you use `nowebengine` build directly? What you want to achieve?

**Comment by ImportTaste** [comment]
> First, I completely disagree with "To prevent user error..." part and I do not plan to implement that as literally no other SW with CLI does not offer that feature.

Uhh, okay, the parameter aliases weren't really a big deal in the first place.

> Why don't you use `nowebengine` build directly? What you want to achieve?

Just not having to have two separate builds downloaded each time I update RSS Guard, really. There's also the slight chance I accidentally launch both at once, which is a problem since I have the data4 directory symbolically linked to the other build.

**Comment by akinokonomi** [comment]
> > Why don't you use `nowebengine` build directly? What you want to achieve?
> 
> Just not having to have two separate builds downloaded each time I update RSS Guard, really. There's also the slight chance I accidentally launch both at once, which is a problem since I have the data4 directory symbolically linked to the other build.

Why do you use both builds, then?

**Comment by ImportTaste** [comment]
> > > Why don't you use `nowebengine` build directly? What you want to achieve?
> > 
> > 
> > Just not having to have two separate builds downloaded each time I update RSS Guard, really. There's also the slight chance I accidentally launch both at once, which is a problem since I have the data4 directory symbolically linked to the other build.
> 
> Why do you use both builds, then?

My little tablet computer is very weak, but there are times when it's more convenient to have the web engine on it. So basically, actively using it, I switch to the webengine build, and when it's just running in the background, I do the no web engine build.

**Comment by akinokonomi** [comment]
> but there are times when it's more convenient to have the web engine on it

When exactly? Wouldn't it be more reasonable to improve the no-webengine version instead?

**Comment by ImportTaste** [comment]
> > but there are times when it's more convenient to have the web engine on it
> 
> When exactly? Wouldn't it be more reasonable to improve the no-webengine version instead?

When I want to see the webpages like a normal browser and navigate the website or whatever.

**Comment by martinrotter** [comment]
I see. I will investigate the code and will check if this can be done easily.

**Comment by barolo** [comment]
What about something in-between, like [litehml rendering engine](https://github.com/litehtml/litehtml)?

**Comment by martinrotter** [comment]
> What about something in-between, like [litehml rendering engine](https://github.com/litehtml/litehtml)? It has Qt bindings and is used in Qt-Creator.

I am thinking about something actually similar. Solution might appear in one of future versions.

**Comment by martinrotter** [comment]
#669

**Comment by martinrotter** [comment]
THis was now fixed in #669.

**Comment by martinrotter** [comment]
New flag is "-w" or "--no-web-engine".
