### ISSUE TITLE
[FR]: WebEngine feed retrieval

### ISSUE THREAD

**Issue by ImportTaste** [martinrotter/rssguard#555]
### Brief description of the feature request

**Use Case 1:** A site has no RSS and needs to be parsed with a postprocessing script, but JavaScript needs to run on the retrieved page first.

**Use Case 2:** I've had this issue where a site is getting DDOSed and they put everything - including the feed URL - behind Cloudflare protection.

This could take the form of a non-default boolean within an individual feed (a `[WebEngine build required, feed will be retrieved normally]` required message would appear underneath it if this is enabled on a nowebengine build, but it would still let you toggle the setting), as well as a context menu option that only appears when the last feed retrieval encountered.

Additionally, there could be a global option that, when enabled, will always attempt WebEngine-based retrieval if a 503 error was encountered (displaying the same error message on nowebengine builds that I mentioned prior).

**Comment by martinrotter** [comment]
This is actually very interesting idea! Wow. Will think about that.

Do you have any specific use-cases or some services which I could try to test/debug the feature?

**Comment by ImportTaste** [comment]
> This is actually very interesting idea! Wow. Will think about that.
> 
> Do you have any specific use-cases or some services which I could try to test/debug the feature?

Just open someone's Twitter timeline since Twitter does a lot of lazyloading. I forgot to mention, but since browser height affects lazyload, the headless retrieval should have its browser height set at a large value. (With puppeteer I use the --window-size parameter since it uses Chromium, haven't really looked to see how RSS Guard's backend works.) I'd recommend either 4320 or 8640.

**Comment by martinrotter** [comment]
> > This is actually very interesting idea! Wow. Will think about that.
> > Do you have any specific use-cases or some services which I could try to test/debug the feature?
> 
> Just open someone's Twitter timeline since Twitter does a lot of lazyloading. I forgot to mention, but since browser height affects lazyload, the headless retrieval should have its browser height set at a large value. (With puppeteer I use the --window-size parameter since it uses Chromium, haven't really looked to see how RSS Guard's backend works.) I'd recommend either 4320 or 8640.

OK, did some testing. Twitter returns basically error, that JS is not enabled etc.

Do you have any puppeteer or similar working script to fetch Twitter data/tweets/posts?

I am starting to get impression that simply using puppeteer with RSS Guard (which is already possible, se my above post) is just better option, but I agree that getting already compiled component to work and avoiding the need of installing other headless solution is not bad idea.

**Comment by ImportTaste** [comment]
> Are you aware of that?

Yes.

> I am starting to get impression that simply using puppeteer with RSS Guard (which is already possible, se my above post) is just better option, but I agree that getting already compiled component to work and avoiding the need of installing other headless solution is not bad idea.

That was my thinking as well.

**Comment by martinrotter** [comment]
I tested many options with built-in WebEngine and nothing reliably works, it seems that WebEngine is just really not suitable for these headless mode. Use selenium or pupeteer with "website scraping" feature to achieve same goal. :)

Sorry.
