### ISSUE TITLE
[FR]: Make feed retrieval use same cookies and useragent as the internal browser

### ISSUE THREAD

**Issue by ImportTaste** [martinrotter/rssguard#556]
### Brief description of the feature request

For similar reasons to #555, I'd like feed retrieval to use the same cookies and useragent as the internal browser. This would make it so that, even if Cloudflare becomes an obstacle, a page could be opened in the internal browser and then the user could just fetch the feed again.

**Comment by martinrotter** [comment]
Makes sense, but of course only cookies for the "URL" should get applied, not all cookies, right? So for example if your cache will have cookies for "www.abc.com/*" then only those cookies will be used if you load feed "www.abc.com/feed.xml" right?

**Comment by martinrotter** [comment]
* [ ] same cookies
* [ ] same UA

**Comment by martinrotter** [comment]
Do you perhaps have any "feed" which could be tested which only works with "cookies" etc.?

**Comment by ImportTaste** [comment]
> Do you perhaps have any "feed" which could be tested which only works with "cookies" etc.?

Not to any site that is currently accepting new registrations, but why not do something simple like setting a repo to private and then trying to get it to not return the 404 page that you see when you're not logged in?

**Comment by martinrotter** [comment]
That could be viable solution!

**Comment by martinrotter** [comment]
Well, not: https://stackoverflow.com/a/17419321

Private repos do not seem to provide "accessible with cookies" feeds.

**Comment by martinrotter** [comment]
But I guess I will find another way.

**Comment by ImportTaste** [comment]
> But I guess I will find another way.

Does it have to be a feed? If you'd like, I can just make a postprocessor script that'll spit out a page source as the first JSONFeed entry.

**Comment by martinrotter** [comment]
Wow, what a cute script, thanks, will use it to debug the ticket.

**Comment by martinrotter** [comment]
OK, I implemented it.

If cookie is added/deleted in webengine, the change is propagated to internal cookie store of rss guard and vice versa.

Just tested with your script on website where I logged in and then tried to fetch and it really showed correct "logged-in" message. I guess this is done then.
