### ISSUE TITLE
Mis-interpretation of Language in newsfeed

### ISSUE THREAD

**Issue by Nithin-Reddy** [martinrotter/rssguard#56]
#### Brief description of the issue.

Just now I installed rssguard, from arch aur pkg builds using yaourt tool.
When ever I open any news feed, I get it in some other language other than English.

#### How to reproduce the bug?

1. Normal Installation from pkgbuild
2. Did add an account of standard rss feed.
3. open any news feed, I get it in different type of language.

#### What is the expected result?

Feed in English

#### What actually happened?

Feed in some other language

#### Other information (logs, see Wiki)

I did cross-check my language was English in tools option.
Here is the log file and some screenshots.
[log.txt](https://github.com/martinrotter/rssguard/files/453178/log.txt)
![screenshot_20160903_085021](https://cloud.githubusercontent.com/assets/19215729/18222445/94ad8d58-71b5-11e6-85ec-0e7b2b151deb.png)
![screenshot_20160903_084929](https://cloud.githubusercontent.com/assets/19215729/18222446/97593fc0-71b5-11e6-8bf0-4d2517f8ee9e.png)
![screenshot_20160903_084958](https://cloud.githubusercontent.com/assets/19215729/18222448/9aa6ed9e-71b5-11e6-9cdd-53c4f1000c0c.png)
![screenshot_20160809_053103](https://cloud.githubusercontent.com/assets/19215729/18222449/a893a69a-71b5-11e6-8d05-ddc51077f52b.png)

**Comment by martinrotter** [comment]
What font do you have setup in `Tools > Settings > Feeds & messages > Messages > Internal messages browser fonts`?

Try to set there some other classic font like Arial or something like that.

**Comment by Nithin-Reddy** [comment]
Yes, When I changed Font everything was alright!
Previous Font:Noto Sans
Changed to: sans serif
Thank you.

**Comment by martinrotter** [comment]
OK, solved, closing.
