### ISSUE TITLE
[FR]: Auto-fetch resets to set value after quiting program.

### ISSUE THREAD

**Issue by chrisretusn** [martinrotter/rssguard#561]
### Brief description of the issue

Auto-fetch time resets to set time scale on starting RSS Guard. 

### How to reproduce the bug?

1. Set Auto-fetch to 24 hours (1440 minutes), wait 5 minutes (next auto-fetch 1435 minutes left).
2. Check time left. (hover over feed)
2. Exit RSS Guard
3. Start RSS Guard check the minutes until next auto-fetch, it's back at 1440 minutes.

Occurs with Feed settings and global setting. 

### What was the expected result?

Expected result was there would be 1435 (or close to that) minutes left until next auto-fetch.

### What actually happened?

Reset to 1440 miutes

### Other information

I currently have my Auto-fetch, globally  set to 24 hours (1440 minutes). I noticed the articles were not always being fetched as expected. What discovered was if I exit RSS Guard and later start it again, the Auto-fetch is set to 1440 minutes again regardless of what the setting was at on exit. For example "30 minute(s) to next auto-fetch of articles", set back to 1440 minutes on restart of program. This also happens with Auto-fetch set in individual feeds. I checked by setting a feed to 15 minuets, wait until 10 minutes were left, exited RSS Guard, check next auto-fetch for the feed was 15 minutes. 

### Operating system and version

* OS: Slackware64-current
* RSS Guard version: 4.0.4 (built on Linux/x86_64)
Build date: 12/1/21 12:18 AM
Qt: 5.15.3 (compiled against 5.15.3)

**Comment by akinokonomi** [comment]
> Exit RSS Guard
Start RSS Guard check the minutes until next auto-fetch, it's back at 1440 minutes.

Isn't that expected behaviour?

> Expected result was there would be 1435 (or close to that) minutes left until next auto-fetch.

Let's make one point clear first: You want timer to remain on `1435`, even if RSS Guard was not active for >1 hour? 
Or you want it that with each lapsed hour the timer will also change, e.g. RSS Guard was not active for 4 hours, so time to the next fetch should be `1195`?

**Comment by martinrotter** [comment]
@chrisretusn 
This is actually (so far) a feature! It is true that RSS Guard does not "subtract" "exit" duration from the interval. In other words, it indeed does start from full interval when you start the application.

Answer to comment from @akinokonomi first, then we can start some more specific discussion.

**Comment by chrisretusn** [comment]
> > Exit RSS Guard
> > Start RSS Guard check the minutes until next auto-fetch, it's back at 1440 minutes.
> 
> Isn't that expected behaviour?
> 
> > Expected result was there would be 1435 (or close to that) minutes left until next auto-fetch.
> 
> Let's make one point clear first: You want timer to remain on `1435`, even if RSS Guard was not active for >1 hour? Or you want it that with each lapsed hour the timer will also change, e.g. RSS Guard was not active for 4 hours, so time to the next fetch should be `1195`?
I like your "Or", part better than how I stated it. The expected behavior is to fetch every 24 hours, not 24 hours from the start of RSS Guard. So, yes, if I exit RSS Guard and it was not active for 4 hours, the next fetch should be 1195. 

I keep this computer up 24/7 but there are times when I need to reboot or exit KDE Plasma to do some package upgrades that affect KDE, thus having to quit RSS Guard. Once before quitting RSS Guard I checked the time remaining, it was 94 minutes, about 30 minutes later, started RSS Guard (autostarts with Plamsa) a found the time remaining was 1440 minutes.

**Comment by chrisretusn** [comment]
As an aside, while searching for the issue I found one about the notification sound and learned about the rooster. Love it! :)

**Comment by martinrotter** [comment]
From "practical" POV, your request makes very much sense. From technical POV, it would require RSS Guard to remember time each feed was last updated, and also global last update time.

I will probably implement this.

If you find any other bugs, feel free to report, yes those sounds are hilarious, feel free to suggest even more free sounds, I will embed them.

**Comment by zer0-x** [comment]
> Let's make one point clear first: You want timer to remain on `1435`, even if RSS Guard was not active for >1 hour? Or you > want it that with each lapsed hour the timer will also change, e.g. RSS Guard was not active for 4 hours, so time to the next fetch should be `1195`?


I don't think that the **second behavior** is a good idea from my point of view. I'm with the **first behavior**, where the timer will just change while `rssguard` is active. If 1435 minutes were remaining when I closed `rssguard`, I want it to stay 1435 even if I opened `rssguard` even after a whole day.

The problem with the **second behavior** is that if all the timers reached 0 while `rssguard` is not active, as soon as I open it, it will fetch every thing at the same time. This will lead to some privacy issues for me.

It would be a great thing to have an option in the settings to select the timer behavior.

**Comment by chrisretusn** [comment]
I'm good with this. Thanks for the time and effort. I understand the difficulty of making this work as I was hoping it would. I have changed the way I use RSS Guard. Instead of relying on auto-fetch I just do things manually with "Fetch All".
