### ISSUE TITLE
[FR]: "Are you sure?" dialogue when removing selected article filter

### ISSUE THREAD

**Issue by akinokonomi** [martinrotter/rssguard#562]
### Brief description of the feature request

It would be nice to see some confirmation dialogue, when user clicks "Remove selected" in Article filters window.

**Comment by martinrotter** [comment]
Did you learn this the hard way btw?

**Comment by akinokonomi** [comment]
Hahaha, caught me! Though it was around month ago, yeah...

**Comment by martinrotter** [comment]
done
