### ISSUE TITLE
[FR] / [BUG] http agent identifiert

### ISSUE THREAD

**Issue by maxdevaine** [martinrotter/rssguard#564]
### Brief description of the feature request

Hello,
RSS Guard (version: 4.0.4) does't send agent identification or have wrong agent identifiert.<br /><br />

For example, this feed need regular http agent identifiert, so this does't work (in rss guard does't work too):<br />
```
curl https://www.vmware.com/security/advisories.xml
You don't have permission to access
```

and this working ok:<br />
`curl -s -A "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0)" https://www.vmware.com/security/advisories.xml`

So, it is possible to add regular agent info to RSS Guard? Or option to specify agent indentifiert?<br /><br />

**Operating system and version**
RSS Guard 4.0.4 (Linux/x86_64)
Build date: 17.10.21 9:01
Qt: 5.15.2 (compiled 5.15.2)

Thanks<br />
Max<br />
PS: for solve this problem I used workaround - load feed via script

**Comment by martinrotter** [comment]
Check with latest dev build. Could be fixed. RSS Guard uses valid and well-formed ua string.

https://github.com/martinrotter/rssguard/commit/d001ca63781072f9ec9d975da02588752f81b673

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/148017785-36bd1e6f-60ca-4618-a030-7aa463190ff6.png)
