### ISSUE TITLE
[FR]: Card view

### ISSUE THREAD

**Issue by onmyouji** [martinrotter/rssguard#568]
### Brief description of the feature request

Hi, is it possible to have a card view? Something that looks like this:

![1](https://user-images.githubusercontent.com/8424198/148098846-ba0e33db-0c4a-486d-a1b3-885f7b428cde.png)

**Comment by martinrotter** [comment]
Technically, entirely possible.

Sadly, implementing the ticket would be quite a challenging, time consuming challenge, at this point, there seem to be more important things to implement.

Anyway, thanks for reporting. :)

**Comment by martinrotter** [comment]
But do not get me wrong, I have ideas on how to implement actually nice/modern/useful newspaper/card/tile mode on my mind and will address the issue sooner or later.

**Comment by martinrotter** [comment]
Closing, I moved all these similar tickets to single metaticket, follow there pls.

https://github.com/martinrotter/rssguard/issues/585
