### ISSUE TITLE
Make JS and PLUGINS switchable, enable changing of message background color

### ISSUE THREAD

**Issue by Mvtante** [martinrotter/rssguard#57]
#### Brief description of the issue.

RSSguard is a good program but it needs a few implementations to become a more privacy and security friendly option. 
#### How to reproduce the bug?
1. 
2. 
3. 
#### What is the expected result?

An option to deactivate javascript (for privacy and security reasons).

An option to deactivate plugins (like facebook and twitter).

An option to change the feed background color (from white to black).

**Comment by martinrotter** [comment]
> An option to change the feed background color (from white to black).

That option is already there. You just need to write custom skin for that, which is easy.

**Comment by martinrotter** [comment]
Now fixed, the ability is added in web viewer context menu + main menu. User can switch off/on many web engine viewer options, including plugins/JS etc.
