### ISSUE TITLE
[FR]: Add a Row that indicates days

### ISSUE THREAD

**Issue by AmmarSaleemG** [martinrotter/rssguard#571]
### Brief description of the feature request

Hello,
To make the application look more clean & sleek, there should be a row that indicates days segregated between the rows of feeds. So, one can get the idea clearly via looking at the days, such as: Yesterday, Today, 5th Jan 2022, etc.

Example:
![image](https://user-images.githubusercontent.com/15247707/148507813-85c825b8-e590-425f-800c-9c179b1fa9b1.png)

**Comment by akinokonomi** [comment]
Hi,
Do you know about this option https://github.com/martinrotter/rssguard/issues/530#issuecomment-958737024 ?

It seems to have the same purpose.

**Comment by qcybb** [comment]
If this feature is added, I hope it'll be an option. I don't want my feed to be split up sections like that.

**Comment by martinrotter** [comment]
Dont worry, the way current list of articles works it is basically impossible to implement. It would require total rewrite of article list.

**Comment by martinrotter** [comment]
Closing, I moved all these similar tickets to single metaticket, follow there pls.

https://github.com/martinrotter/rssguard/issues/585
