### ISSUE TITLE
[FR]: If date <> today - show date only

### ISSUE THREAD

**Issue by qcybb** [martinrotter/rssguard#572]
### Brief description of the feature request

This is similar to my previous feature request.

https://github.com/martinrotter/rssguard/issues/530

Would it be possible to have an option to only show the date under the "Date" column - if the news is older than today?

This would make it even more compact + cleaner to look at.

For example :

8:27 AM
7:24 AM
01/07/22
01/06/22
01/06/22

**Comment by martinrotter** [comment]
oh, okay :)

**Comment by qcybb** [comment]
Thank you!

**Comment by qcybb** [comment]
Any chance this can make it in to 4.2.0?

**Comment by martinrotter** [comment]
yes, this will appear in 4.2.0, it is already implemented and you can test it in dev. build

**Comment by martinrotter** [comment]
this ticket should've been closed, because it is in fact already there

![image](https://user-images.githubusercontent.com/1255302/155895548-b2f72ef7-c3e4-46d3-b4ff-6f4fff547cd1.png)

**Comment by qcybb** [comment]
Thanks!
