### ISSUE TITLE
[BUG]: Application Doesn't run after converting Database Driver to MariaDB

### ISSUE THREAD

**Issue by AmmarSaleemG** [martinrotter/rssguard#573]
### Brief description of the issue

After converting the database driver to MariaDB. Application prompts restart.  After that, It doesn't run at all.

### How to reproduce the bug?

Goto Data Storage
Select MariaDB as a database driver (input everything required)
Apply and restart it, It will never start again.

You must have fresh database in your MariaDB server.

### What was the expected result?

Data Storage feature is truly appealing, it makes you try it. 
I tried it but got hit with the bug.

### What actually happened?

I switched the database driver to MariaDB > It prompted a restart > on confirming, The application closed and never started.

Then, to revive it back, I had to delete the config.ini file from the config folder. 
It started and settings reverted to default (as expected).

All in all, It failed to convert the database to MariaDB.

### Other information

`Potential Reason`
---
I went through my localhost to PhpMyAdmin. There, I found that it failed to create few of the tables.
Then i used SQL DB browser to browse the Tables schema, I copied the "Create Statement" of Tables. Pasted into sql query in phpmyadmin
Through SQL query, I found a potential problem that could be causing it to fail to create the table. 

There is a wrong "`value`" in column named "`icon`" in every table that hinder it to create tables. 
---
Below is the picture that depicts it:
![image](https://user-images.githubusercontent.com/15247707/148648437-2d4aa2b1-4206-417e-84e6-0150bd26f4e5.png)

### Operating system and version

* OS: Windows 11
* RSS Guard version: 4.0.4

**Comment by martinrotter** [comment]
will check, those special strings are just placeholders which are meant to get replaced before the sql statement is sent to server

**Comment by AmmarSaleemG** [comment]
> posting the actual debug log of app would help
Where is it located?

**Comment by martinrotter** [comment]
https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#reprt

**Comment by martinrotter** [comment]
OK, should be fixed, i found the issue.

daa889e
