### ISSUE TITLE
[BUG]: Issue with changing skins?

### ISSUE THREAD

**Issue by qcybb** [martinrotter/rssguard#574]
### Brief description of the issue

When I switch to the skin verigilius, nudus-light or nudus-dark and restart RSS Guard, nothing changes.

The only skin that works is "dark". 

### How to reproduce the bug?

Change the skin to anything but "dark" and nothing changes.

### What was the expected result?

The skin should change.

### What actually happened?

The skin does not change.

### Operating system and version

* OS: Window 10 Home
* RSS Guard version: 4.1.1

**Comment by martinrotter** [comment]
I see, let me test.

**Comment by qcybb** [comment]
The verigilius skin is active - but it looks exactly the same as nudus-light and nudus-dark.

**Comment by martinrotter** [comment]
OK, this.

1. Run rssguard with vergilius, fetch some feed, click some article -> make screenshot.
2. Run rssguard with nudus-light, fetch some feed, click some article -> make screenshot.
3. Run rssguard with nudus-dark, make sure your "style" is set to "Fusion" and make sure that checkbox "Force dark look (Fusion only)" is checked, fetch some feed, click some article -> make screenshot.

Posts screenshots pls.

**Comment by qcybb** [comment]
RSS Guard
Version: 4.1.1 (built on Windows/x86_64)
Revision: 35264af6-nowebengine
Build date: 1/7/22 2:12 PM
Qt: 5.15.2 (compiled against 5.15.2)

vergilius :
![vergilius](https://user-images.githubusercontent.com/16991734/148658406-7ba0b4f4-b06f-4843-b373-a6cfa9656b1a.png)

nudus-light :
![nudus-light](https://user-images.githubusercontent.com/16991734/148658417-614f5d9e-2d42-4269-b4e5-0c1c982618a2.png)

nudus-dark :
![nudus-dark](https://user-images.githubusercontent.com/16991734/148658453-549e2ccc-4897-4b22-a439-fad29699a590.png)

**Comment by martinrotter** [comment]
YOu have installed version "nowebengine" which is variant of rssguard which does not use "skins" to style articles -> you need to use classic "full" variant.

https://github.com/martinrotter/rssguard/releases/download/4.1.1/rssguard-4.1.1-35264af6-win64.7z

Note that "skins" included in RSS GUard are rather minimal, they only change the look of articles and to some minimal styling of rss guard GUI

**Comment by qcybb** [comment]
Ok, thank you. I see the differences now.
