### ISSUE TITLE
[BUG]: Parse HTML in Title (to support RTL titles)

### ISSUE THREAD

**Issue by rabin-io** [martinrotter/rssguard#576]
### Brief description of the feature request

Hi, 

Some feed will use an html `div` tag to align the title and set it direction for readability. 

e.g a Hebrew feed which use the div tag and direction attribute 
![image](https://user-images.githubusercontent.com/5116363/148754755-0f916763-8ab3-46fd-98c4-9ca8d71eb4dc.png)

while in Feedly it display the titles correctly, with the current aliment and direction (RTL)
![image](https://user-images.githubusercontent.com/5116363/148755060-0bd79258-b3bd-49e1-b5a6-ea537813b70a.png)

**Comment by martinrotter** [comment]
RTL is not really supported at all.

What is URL of feed?

#217

**Comment by rabin-io** [comment]
It's weird, I think those tags come through Feedly and not through the source, 
the original feed was https://hwzone.co.il/feed/ but I don't see this tag in it. and when adding this feed directly to RSS Guard, I don't see this tags.

**Comment by martinrotter** [comment]
so you actually use feedly plugin in rss guard?

**Comment by rabin-io** [comment]
yes. as you can see, same feed, one via Feedly and the other directly, where in Feedly we get the extra HTML tags

![image](https://user-images.githubusercontent.com/5116363/148777311-8ac93186-1014-4238-aecb-9ce1b623e366.png)

![image](https://user-images.githubusercontent.com/5116363/148777485-ceeffbaf-cb9b-4f53-afb5-eb70233e0028.png)

**Comment by martinrotter** [comment]
as for RTL support, head to #217, i will close this ticket when i fix that HTML issue

**Comment by martinrotter** [comment]
issue is fixed, HTML code should be properly handled in feedly plugin now, for overall RTL support, head to #217 and post your opinion there

**Comment by rabin-io** [comment]
OK, thanks, waiting for flatpak to be updated, to test it.

**Comment by martinrotter** [comment]
i will update when new version is out, for now you can try appimage built automatically

**Comment by rabin-io** [comment]
I'll wait, for some reason the AppImage is not pulling the feeds form Feedly.

**Comment by martinrotter** [comment]
Feedly should work in AppImage without any problems.
