### ISSUE TITLE
[BUG], [MariaDB]: Failing to escape (quote, commas, Arabic/Urdu font, etc.) strings

### ISSUE THREAD

**Issue by AmmarSaleemG** [martinrotter/rssguard#579]
### Brief description of the issue

A question mark is shown instead of Inverted commas and Arabic/Urdu font. Most probably these strings are not escaping properly.

### How to reproduce the bug?

Self-explanatory:
- It is shown in the article list

### What was the expected result?

The expected result was to see the proper strings.

### What actually happened?

The following Image is self-explanatory:
![image](https://user-images.githubusercontent.com/15247707/148934456-795c4a49-20df-445c-9844-c57fffc4f5ca.png)

**EDIT: MORE DATA**
URDU LANGUAGE: (**Before** clicking on URL Button in Browser )
![image](https://user-images.githubusercontent.com/15247707/148981485-51baf61a-2f1c-4ddf-805e-f1db23f0acf1.png)

URDU LANGUAGE: (**After** clicking on URL Button in Browser)
![image](https://user-images.githubusercontent.com/15247707/148981834-514162f8-b210-43c1-9571-4c79c04d8609.png)

### Other information

Keep in mind that the **_website viewer_** also **cannot** escape the string **unless** you click on the "**URL**" then whole webpage is opened (which is the best feature in it).

### Operating system and version

* OS: Windows 11
* RSS Guard version: 4.1.2

**Comment by martinrotter** [comment]
Post URL of such a feeds.

**Comment by AmmarSaleemG** [comment]
I am using MariaDB: and this occurs (i guess when parsing the strings from) there

https://www.independent.co.uk/asia/china/china-xinjiang-intel-suppliers-letter-b1990563.html
https://www.independent.co.uk/asia/china/china-daily/ancient-bronzes-china-buddha-bronzes-b1988610.html
https://www.newsobserver.com/sports/spt-columns-blogs/luke-decock/article257187757.html
https://www.fishstripes.com/2022/1/11/22877958/marlins-kyle-keller-npb-hanshin-tigers


I recently encountered a database crash too, But i am not confirm about the reason, so i am waiting for next crash.
I wish i knew how to produce a debug log. I followed the documentation, it didnt help.

**Comment by martinrotter** [comment]
Not URLs of articles, I need URL of a feed, so that I can add it and test myself.

**Comment by AmmarSaleemG** [comment]
Ah, apologies, here it is:
http://feeds.feedburner.com/BBCNews_Urdu

**Comment by martinrotter** [comment]
I cannot reproduce, tested with sqlite and mariadb.

![image](https://user-images.githubusercontent.com/1255302/149137860-793ce41a-8994-4ff6-8c69-ca4c9db2e9ab.png)

**Comment by martinrotter** [comment]
Do you see same problems with SQLite DB backend?

**Comment by AmmarSaleemG** [comment]
This happens while using MariaDB
![image](https://user-images.githubusercontent.com/15247707/149138620-7b6a2076-cc22-4378-a09a-406c0f5954f9.png)


**Close the application after fetching the feed using MariaDB, then re-open it, you may see these.**

**Comment by martinrotter** [comment]
nothing, still same correct output

i would try newest mariadb version, especially if this happens for you only on mariadb backend.

**Comment by AmmarSaleemG** [comment]
Just to let you know: I am using Xampp.

BTW,
This is the result when you switch back to SQlite

![image](https://user-images.githubusercontent.com/15247707/149140084-c8fd8985-9910-4037-bdc7-ebe4b8bdf384.png)

**Comment by martinrotter** [comment]
then this is clearly problem with your version of mariadb server, you could try original mariadb?

https://mirror.nextlayer.at/mariadb/mariadb-10.6.5/winx64-packages/mariadb-10.6.5-winx64.zip

**Comment by martinrotter** [comment]
it is just weird

**Comment by martinrotter** [comment]
cannot reproduce, closing, feel free to comment if any new things come up

**Comment by martinrotter** [comment]
This bug partially revelaed itself for me. Investigating. It seems to only trigger with Qt 5 (!) build of RSS Guard, not with Qt 6 build.

**Comment by martinrotter** [comment]
OK, found the bug upstream.

https://bugreports.qt.io/browse/QTBUG-95071

It is not fixed for Qt 5.15 but is for Qt 6. I will try to backport fix.

**Comment by AmmarSaleemG** [comment]
Great!

**Comment by martinrotter** [comment]
OK my friend. I had to dig through Qt source code to find the problem.

I believe it is now fixed even for Qt 5.15+. Development build is building RN. Feel free to test.

**Comment by martinrotter** [comment]
Tested: 
![image](https://user-images.githubusercontent.com/1255302/159429528-6648d00e-177f-4693-8ab3-4a496732769a.png)

**Comment by AmmarSaleemG** [comment]
> OK my friend. I had to dig through Qt source code to find the problem.
> 
> I believe it is now fixed even for Qt 5.15+. Development build is building RN. Feel free to test.

**Many Thanks Brother!**



> Tested: ![image](https://user-images.githubusercontent.com/1255302/159429528-6648d00e-177f-4693-8ab3-4a496732769a.png)

**Perfect**!
