### ISSUE TITLE
Handle SSL warnings

### ISSUE THREAD

**Issue by divico** [martinrotter/rssguard#58]
#### Brief description of the issue.

rssguard version 3.3.4 will not connect to an owncloud news instance in case of SSL warnings. 
My owncloud server supplies a SSL certificate issued for a different hostname. Therefore hostname verification is not possible. In this case, rssguard will not connect to the owncloud instance.

#### How to reproduce the bug?
Connect to an owncloud news instance that supplies a SSL certificate whose hostname cannot be verified.

#### What is the expected result?
Ask the user if he accepts the security exception and connect to the owncloud instance.

#### What actually happened?
On connection the following error is raised
`WARNING: Ignoring SSL errors for 'https://xxxx/index.php/apps/news/api/v1-2/status': 'Unknown error' (code 0).
WARNING: QIODevice::read (QNetworkReplyHttpImpl): device not open
DEBUG: Destroying SilentNetworkAccessManager instance.
WARNING: ownCloud: Obtaining status info failed with error 5.`

I can provide access to the server if needed.

**Comment by martinrotter** [comment]
Hello. Yes, please provide demo account on your server, I will test it out and fix if possible.

Does this happen on Windows? Linux?

**Comment by martinrotter** [comment]
Follow-up: did it work with previous RSS Guard version?

**Comment by divico** [comment]
Today it works perfectly so it must be an issue from the server. I'm sorry for having opened this issue!
