### ISSUE TITLE
[BUG]: 4.1.2 build fails with Qt 5.12

### ISSUE THREAD

**Issue by lgbaldoni** [martinrotter/rssguard#580]
### Brief description of the issue

`expandRecursively` not available

### How to reproduce the bug?

1. Unpack source tarball
2. Try to build the package

### What was the expected result?

A successful build.

### What actually happened?

See [log snippet](https://github.com/martinrotter/rssguard/files/7846103/rssguard412_Qt5127.txt).

### Operating system and version

* OS: openSUSE Leap 15.3 / Qt 5.12.7
* RSS Guard version: 4.1.2

**Comment by martinrotter** [comment]
I pushed a fix, can you test it?

https://github.com/martinrotter/rssguard/commit/b1d4bd93ec3172fb8886fdcb12af246de65bccf3

**Comment by lgbaldoni** [comment]
The fix works, TYVM.
