### ISSUE TITLE
[BUG], [MariaDB]: Cannot import feed: 'Server has gone away QMYSQL: Unable to execute query'.

### ISSUE THREAD

**Issue by AmmarSaleemG** [martinrotter/rssguard#581]
### Brief description of the issue

I am using MariaDB, here is the debug log:

time="    59.876" type="critical" -> core: Cannot import feed: 'Server has gone away QMYSQL: Unable to execute query'.

More detailed data:
time="  3389.204" type="debug" -> database: MySQL connection 'StandardServiceRoot' is already active.
time="  3389.205" type="debug" -> database: MySQL database connection 'StandardServiceRoot' to file 'rssguard' seems to be established.
time="  3389.205" type="debug" -> database: MySQL connection 'StandardServiceRoot' is already active.
time="  3389.206" type="debug" -> database: MySQL database connection 'StandardServiceRoot' to file 'rssguard' seems to be established.
time="  3389.206" type="debug" -> database: MySQL connection 'StandardServiceRoot' is already active.
time="  3389.206" type="debug" -> database: MySQL database connection 'StandardServiceRoot' to file 'rssguard' seems to be established.
time="  3389.207" type="critical" -> core: Cannot import feed: 'Server has gone away QMYSQL: Unable to execute query'.
time="  3389.207" type="debug" -> database: MySQL connection 'StandardServiceRoot' is already active.
time="  3389.207" type="debug" -> database: MySQL database connection 'StandardServiceRoot' to file 'rssguard' seems to be established.
time="  3389.208" type="critical" -> core: Cannot import feed: 'Server has gone away QMYSQL: Unable to execute query'.
time="  3389.208" type="debug" -> database: MySQL connection 'StandardServiceRoot' is already active.
time="  3389.208" type="debug" -> database: MySQL database connection 'StandardServiceRoot' to file 'rssguard' seems to be established.
time="  3389.208" type="critical" -> core: Cannot import feed: 'Server has gone away QMYSQL: Unable to execute query'.
time="  3389.209" type="debug" -> database: MySQL connection 'StandardServiceRoot' is already active.
time="  3389.209" type="debug" -> database: MySQL database connection 'StandardServiceRoot' to file 'rssguard' seems to be established.
time="  3389.209" type="critical" -> core: Cannot import feed: 'Server has gone away QMYSQL: Unable to execute query'.
time="  3389.209" type="debug" -> database: MySQL connection 'StandardServiceRoot' is already active.
time="  3389.210" type="debug" -> database: MySQL database connection 'StandardServiceRoot' to file 'rssguard' seems to be established.
time="  3389.210" type="critical" -> core: Cannot import feed: 'Server has gone away QMYSQL: Unable to execute query'.
time="  3389.210" type="debug" -> database: MySQL connection 'StandardServiceRoot' is already active.
time="  3389.211" type="debug" -> database: MySQL database connection 'StandardServiceRoot' to file 'rssguard' seems to be established.
time="  3389.211" type="critical" -> core: Cannot import feed: 'Server has gone away QMYSQL: Unable to execute query'.
time="  3389.211" type="debug" -> database: MySQL connection 'StandardServiceRoot' is already active.
time="  3389.211" type="debug" -> database: MySQL database connection 'StandardServiceRoot' to file 'rssguard' seems to be established.
time="  3389.212" type="critical" -> core: Cannot import feed: 'Server has gone away QMYSQL: Unable to execute query'.

### How to reproduce the bug?

Feeds above than 12 (i have 17) in one folder (category) fails to load and produce error.

### What was the expected result?

To load all the feeds smoothly

### What actually happened?

I was importing feeds and got struck with this bug.

### Operating system and version

* OS: Windows 11
* RSS Guard version: 4.1.2
* Database Driver: MariaDB

**Comment by martinrotter** [comment]
I see, can you share opml which causes the big?

**Comment by AmmarSaleemG** [comment]
This file was exported while using SQLite:
[rssguard_feeds_2022-01-11.zip](https://github.com/martinrotter/rssguard/files/7848030/rssguard_feeds_2022-01-11.zip)

Same file failed to import all feeds while using MariaDB.

I will remove this file later soon.

**Comment by martinrotter** [comment]
Would check tomorrow.

**Comment by martinrotter** [comment]
youcan remove, downloaded

**Comment by martinrotter** [comment]
I checked, what version of MariaDB you use? Also, I believe you should investigate your MariaDB logs? Also, does server actually "crash" and you have to restart it?

**Comment by AmmarSaleemG** [comment]
This is the version
![image](https://user-images.githubusercontent.com/15247707/149138159-35b30765-86e2-4c15-9acd-6f179026792b.png)

I am using RssGuard 4.1.2

**Comment by martinrotter** [comment]
try latest mariadb perhaps, also respond other questions i had

**Comment by AmmarSaleemG** [comment]
Also, I believe you should investigate your MariaDB logs?
There is no error in MariaDB log. From now onwards i shall post the MariaDB logs too.

Also, does server actually "crash" and you have to restart it?
It crashed once two days ago. There was another problem which is not connected to it. 
But I reinstalled it, started from a fresh database. Now it has not crashed at all till now.

**Comment by martinrotter** [comment]
still weird, there are now two mariadb issues you see, but i don't

have you tried vanilla mariadb from official website? i have quite bad experience with xampp honestly

**Comment by AmmarSaleemG** [comment]
Seems this is from my end. Let's defer this issue for now.
I will try WAMP server in future, (or suggest any other). Then will let you know.

**Comment by martinrotter** [comment]
OK

**Comment by martinrotter** [comment]
OK, I will close, feel free to comment if any news come up, I just cannot reproduce right now.
