### ISSUE TITLE
[FR]: Disable "Important articles" and "Labels" ?

### ISSUE THREAD

**Issue by Owyn** [martinrotter/rssguard#584]
### Brief description of the feature request

![image](https://user-images.githubusercontent.com/1309656/149140063-5873cb07-6239-40e7-a8e3-81815fbea48d.png)

Implementing deleting those two would be nice, - I'm not using those and it's just taking space I'm short of cuz there are lots of feed sources

**Comment by qcybb** [comment]
Yes, It would be great to be able to hide these!

**Comment by Owyn** [comment]
disabling "unread articles" folder would be nice as well because when I press "go to next unread" hotkey and it takes me to that unread articles folder but I'd like it to go to the feed folder with the unread article itself instead to see context

**Comment by Shakil-Shahadat** [comment]
I need options to hide 'Regex queries' and 'Recycle bin' too. Thanks.

**Comment by martinrotter** [comment]
Do we want this to be configurable application-wide or account-wide? Account-wide is a bit easier to implement actually and would make better functionality.

**Comment by martinrotter** [comment]
![image](https://github.com/martinrotter/rssguard/assets/1255302/bb8daa79-84ec-48b3-ba61-945a482a1c6f)
 Fixing right now, will be switchable in account settings for all account types.

![image](https://github.com/martinrotter/rssguard/assets/1255302/5af8ca90-aac9-448f-82df-6ab61a5dc642)
