### ISSUE TITLE
[BUG] or [FR]: custom User-agent\Cookies for nowebengine

### ISSUE THREAD

**Issue by Owyn** [martinrotter/rssguard#586]
### Brief description of the issue

bug: NoWebEngine uses "RssGuard" as its user-agent so it can't fetch some websites because they filter unknown\robotic useragents 

https://github.com/martinrotter/rssguard/blob/1f5157fd42f18eee994e77d7053170f6a96b9f26/pri/vars.pri#L14 
https://github.com/martinrotter/rssguard/blob/daa889ee951dea1e2827d8f61cc4db626de854e2/src/librssguard/definitions/definitions.h#L149

![image](https://user-images.githubusercontent.com/1309656/149657338-98df7d4c-1fba-44b7-a969-9be09b88e74f.png)

here my post script should return a title either way - when it works and when it doesn't but it simply doesn't get run (or smth) cuz web-request got blocked-half way with 403 error (I know this cuz I tried to request that page in Python earlier) - btw, RSSguard doesn't say anywhere that it got an error getting the page (?) and simply thinks everything is OK but no feeds would be ever delivered 

### How to reproduce the bug?

example url: https://mangahub.io/manga/i-m-an-evil-god/
example script line: python#css2rss.py#ul.list-group > li > a#span > span

( the script: https://github.com/Owyn/CSS2RSS )

### What was the expected result?

it'd work:
- URL page would get requested successfully 
- script would run
- title would get set
- feeds would get generated

### What actually happened?

it didn't

### Other information

writing logs still doesn't work here:

![image](https://user-images.githubusercontent.com/1309656/149657630-0e94ab6d-dcb8-4614-8ef8-ff777fa3c9c0.png)

![image](https://user-images.githubusercontent.com/1309656/149657647-1752c569-8ef1-4fcb-b3fa-2ce56ba16097.png)

so, a [FR]: custom User-agent\Cookies setting for nowebengine (or for both versions actually) would be a nice way to fix it

### Operating system and version

* OS: Win10 x64
* RSS Guard version: 4.1.2

**Comment by martinrotter** [comment]
Yes, I tweaked the UA for non-webengine version, it should now use more standard UA and should work. Can you test with latest dev. build when eb76dd369 compiles?

BTW: you can move your scripts into your "user data" folder!

https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#data-placeholder-

As for cookies, they are automatically stored/used also in non-webengine version, but of course particularly "login" cookies must be somehow obtained, and that's a problem in non-webengine version.

**Comment by martinrotter** [comment]
As with logging, yes, I indeed found a problem and fixed it: d13f87740.

**Comment by Owyn** [comment]
> Yes, I tweaked the UA for non-webengine version, it should now use more standard UA and should work. Can you test with latest dev. build when [eb76dd3](https://github.com/martinrotter/rssguard/commit/eb76dd36948797135e5b5b6ca51de2180f74f9bb) compiles?

yes, when it compiles, but it should work if the user agent is correct

thought, an indication of any sort when an error accessing the URL occurs would be also very welcomed for the poor users who don't know why it suddenly doesn't work 😄

**Comment by martinrotter** [comment]
> thought, an indication of any sort when an error accessing the URL occurs would be also very welcomed for the poor users who don't know why it suddenly doesn't work 😄

will check that as it should clearly fail

**Comment by Owyn** [comment]
![image](https://user-images.githubusercontent.com/1309656/149790098-3ad9a896-11b5-42d3-a4a3-8620d4816e36.png)

Probably same error somehow?

https://github.com/Owyn/CSS2RSS/blob/main/css2rss.py#L11
since I added user-agent to my python script and tested it with it - it worked there, unlike default python user agent

**Comment by martinrotter** [comment]
Just tested WITH LATEST devbuild, works:

![image](https://user-images.githubusercontent.com/1255302/150080109-ddb5f08e-4902-424a-b93e-55a0fbb94f51.png)

**Comment by martinrotter** [comment]
Tested with your css2rss script to. Note that script returns invalid JSON feed - missing (double) quotes around JSON properties.

```json
{
  "title": "You searched for Wo Wei Xie Di - Manhuaus.com",
  "description": "Script found 1 items",
  "items": [
    {
      "title": Chapter 223.2,
      "content_html": <a href="https://manhuaus.com/manga/im-an-evil-god/chapter-223-2/">Chapter 223.2</a>,
      "url": "https://manhuaus.com/manga/im-an-evil-god/chapter-223-2/"
    }
  ]
}
```

**Comment by martinrotter** [comment]
I tested with latest devbuild, USER_AGENT issue is already addressed, it is now changed to more sane value. Closing.

**Comment by Owyn** [comment]
Can confirm it works now for both websites

fixed in https://github.com/Owyn/CSS2RSS/commit/7922bcdd3928069303ebf50ab347a5f9e215e853 

but still... even when an invalid JSON feed was returned RSSguard didn't bat an eye and say anything about it, just "all metadata fetched successfully"

**Comment by martinrotter** [comment]
No. The returned JSON is valid, because JSON parser in RSS Guard is non-strict, it simply ignores invalid parts of JSON.

Invalid part is inside `items` (list of articles) - RSS Guard basically thought it is valid feed but with no articles which is not generally a problem.

**Comment by martinrotter** [comment]
But I will make it stricter ok.

**Comment by martinrotter** [comment]
DOne.
