### ISSUE TITLE
[BUG]: Divider Goes to Middle of Window

### ISSUE THREAD

**Issue by LeRaldo** [martinrotter/rssguard#587]
### Brief description of the issue

The divider in the main RSS Guard window randomly sets itself to the center. I don't recall experiencing this bug in version 3, but have been noticing it since version 4. It seems to happen once every day to 5 days. With the update to 4.1.2 and the suggestion to try a new skin, I thought that might fix it, but it still occurs on both dark and nudus-dark.

![guard 1](https://user-images.githubusercontent.com/3815475/149675515-7d9bece8-f29a-4c10-bb8f-41f393e3e200.png)
This is how I have my RSS Guard configured to look.

![guard 2](https://user-images.githubusercontent.com/3815475/149675522-956ddd03-3033-45b2-b14c-8cea37ba6877.png)
This is what happens when the bug occurs.

### How to reproduce the bug?

I haven't found a way to reproduce. It just happens when RSS Guard has been running for a while minimized to the tray, and upon un-minimizing the divider is now in the center of the window.

### What was the expected result?

n/a

### What actually happened?

n/a

### Other information

I tried to generate a log following the directions provided but it didn't work. No log was created.

### Operating system and version

* OS: Windows 10 x64 21H2 (19044.1466)
* RSS Guard version: 4.1.2 nowebengine

**Comment by martinrotter** [comment]
That's weird, the problem with dividers was addressed some versions back and it just seems to "work".

So it happens not only when you quit RSS Guard but also when you just minimize it?

**Comment by martinrotter** [comment]
As with logging, yes, I indeed found a problem and fixed it: d13f87740.

**Comment by LeRaldo** [comment]
> That's weird, the problem with dividers was addressed some versions back and it just seems to "work".
> 
> So it happens not only when you quit RSS Guard but also when you just minimize it?

It's possible it's happening on application start instead of un-minimize from tray. I'll have to pay closer attention.

**Comment by akinokonomi** [comment]
@LeRaldo, If you'll experience this again, try to remove/rename config file `C:\Users\<user>\AppData\Local\RSS Guard 4\data\config\config.ini`. 
(Note that you'll lose your current configuration, but all articles and feeds should remain.)

**Comment by LeRaldo** [comment]
Will do, thanks. Any idea in which version this bug was fixed? I think I remember doing a clean install of 4.0. But I'll still do as recommended regardless to see if it resolves the issue.

**Comment by martinrotter** [comment]
All versions. The way the code is written should basically avoid resetting it to default value. If it is very hard to reproduce, i cannot really do anything.
