### ISSUE TITLE
[FR]: support touch screen interactions

### ISSUE THREAD

**Issue by Slater91** [martinrotter/rssguard#595]
### Brief description of the feature request

Hello! Thanks for developing RSSGuard.
I've tried to use the application on my tablet, a Dell Venue 11 Pro 7140, using Linux with KDE Plasma. The experience was far from ideal as RSSGuard appears not to support touch screens: scrolling the list of news articles and, more generally, interacting with the application is not ideal as the application treats touch input like it would a mouse.
Would it be possible to introduce support for interacting using a touch screen?
Thank you!

**Comment by martinrotter** [comment]
RSS Guard is developed using GUI framework meant for **desktop** usage. Note that while RSS Guard runs just "ok" on tablet devices and even on Android tablet devices, it is really not optimized for that kind of usage and it is practically impossible to improve this.

The only solution would be implementing fully mobile-friendly GUI which is massive task which would require hundreds of hours to complete.

**Comment by Slater91** [comment]
Thanks for your reply. I understand that it is meant for desktops, but at the moment I find entirely unusable with my tablet as I can't even scroll through the news articles using touch. I am not asking for a touch-centric interface, which of course would require a full reworking of the UI, but simply support for scrolling using touch. That alone would make RSSGuard usable on touch-enabled devices.

**Comment by martinrotter** [comment]
Hard to say. I believe that touch interactions themselves should basically work. I cannot sadly test it in any way. No touchscreen devices near.

**Comment by Slater91** [comment]
I think you could emulate that using your mouse as if it was a finger, because under X11 the finger moves the pointer. I'm not sure about Wayland as I don't/can't use it.

**Comment by martinrotter** [comment]
i see

**Comment by martinrotter** [comment]
can you make perhaps a video of what happens?
