### ISSUE TITLE
[BUG]: dragging problem - it doesn't go where you drag it or just goes nowhere

### ISSUE THREAD

**Issue by Owyn** [martinrotter/rssguard#598]
### Brief description of the issue

https://streamable.com/rai4l4 - recorded a video

### How to reproduce the bug?

drag
maybe also have QT_SCALE_FACTOR global variably set

### What was the expected result?

it'd drag to where you point exactly

### What actually happened?

it drags somewhere else
or
it just doesn't drag anywhere and stays where it was

### Operating system and version

* OS: Win 10 x64
* RSS Guard version: Dev

**Comment by martinrotter** [comment]
This is because in feed list, items are not sorted manually but automatically. This is essentially duplicate.

#302
