### ISSUE TITLE
Suggestions to improve keyboard usability

### ISSUE THREAD

**Issue by efferre79** [martinrotter/rssguard#6]
I would suggest the following changes:
- add actions (menù and shortcuts) for cycling among the open tabs
- the "select next unread message" actions should be able to move across feeds, not just in the current feed (so the user can navigatate across all the feeds with a single key)

**Comment by martinrotter** [comment]
Hello. Thank you for your opinion.

Point one - thanks this could indeed be interesting.
Point two - there is already a feature request for this in main repository bug tracker. :) This could be a little hard to implement but indeed, can be useful much more than current implementation.

**Comment by martinrotter** [comment]
Point one now pointless - see changelog of rssguard 3.2.0 when it comes out.

**Comment by martinrotter** [comment]
Please, go to Wiki and test if this is solved correctly for you by downloading development build from commit https://github.com/martinrotter/rssguard/commit/0a8aea55584a4731e9e3330822940c6614c5d778
