### ISSUE TITLE
Column header and tooltips are not translated

### ISSUE THREAD

**Issue by blackarcher21** [martinrotter/rssguard#60]
#### Brief description of the issue.

I use RSS Guard 3.3.5 no webengine version on Windows 8.1, as title said, they are not translated. Can't confirm with normal version, I don't use it.

#### How to reproduce the bug?

1. Switched to other language, e.g. Indonesian
2. As far as I can tell, menus are translated, but column header and tooltips are still in English, not Indonesian

#### What is the expected result?

Translated, they are included in localization file

#### What actually happened?

Not translated

**Comment by eson57** [comment]
I can confirm this also for Swedish. Column headers and tooltips do not translate.

**Comment by martinrotter** [comment]
Are we talking about column headers in message/feed list?

**Comment by martinrotter** [comment]
Was  this bug present in 3.3.4 or older versions?

**Comment by eson57** [comment]
Yes, to both questions.  :)

**Comment by martinrotter** [comment]
Oh, okay. I will check that out. Looks like some bigger shit happened.

**Comment by martinrotter** [comment]
Should be now fixed.

**Comment by eson57** [comment]
Wow, that was quick!  :+1:

**Comment by martinrotter** [comment]
Thanks, easy fix.
