### ISSUE TITLE
[FR]: Improvements in vertical layout of browser

### ISSUE THREAD

**Issue by martinrotter** [martinrotter/rssguard#601]
### Discussed in https://github.com/martinrotter/rssguard/discussions/600

<div type='discussions-op-text'>

<sup>Originally posted by **AmmarSaleemG** January 20, 2022</sup>
## Please take a look into the following picture:

![image](https://user-images.githubusercontent.com/15247707/150319583-2aeb1558-5d9c-4890-b7db-6c8185d4085e.png)

## This CONCEPT photoshopped pic may help:
![image](https://user-images.githubusercontent.com/15247707/150319999-b834f5c2-bbd5-49ed-a94d-19b3e7cecdae.png)

## The RED arrow Down button may replace URL link at the end of the message title. It may say, Open article here.
Best regards
</div>

**Comment by AmmarSaleemG** [comment]
One more addition:

![image](https://user-images.githubusercontent.com/15247707/150324637-9cc6aa73-8af7-4526-b06b-c052ff97d5b0.png)

The word "Written by" is redundant (in my opinion) only author name  is sufficient (if available), Since this line is dedicated for it.
Moreover, if Author is Unknown, attach **Feed Title**.

**Comment by martinrotter** [comment]
Well.

At this point, note that that the top toolbar is ONLY present in WEBENGINE versions, not in NON-WEBENGINE version, because nonwebengine version does not have internal browser, thus does not need those BACK, FORWARD etc buttons.

Also, left toolbar ALSO displays all labels (if user has created any) which can be assigned etc. to article.

![image](https://user-images.githubusercontent.com/1255302/150344814-b59e9539-1d66-4aa3-a8c9-1b3d280284f3.png)

For these (and some other) reasons, it is very hard to "merge" toolbar into the top one.

Sorry. :)
