### ISSUE TITLE
[BUG]: Hide tab bar menu also makes app menu inaccessible 

### ISSUE THREAD

**Issue by Owyn** [martinrotter/rssguard#604]
### Brief description of the issue

Hide tab bar menu option makes app menu inaccessible 

### How to reproduce the bug?

Here's the app menu I access via a letter icon:

![image](https://user-images.githubusercontent.com/1309656/150525297-a06d44f5-a2be-4750-99e0-6cec79731bbb.png)

But here if you select that option it goes poof and you can't access its functions anyhow anymore?
![image](https://user-images.githubusercontent.com/1309656/150525168-a16cbb3b-ba12-427f-8653-35c495925753.png)

### What was the expected result?

A way to access it after that

### What actually happened?

no way

### Other information

Maybe a way to add that letter icon menu to toolbars?

or just display its menu when you click the app status bar icon (i've seen such thing in other apps) instead of std minimize\close drop-down menu there

### Operating system and version

* OS: Win 10 x64
* RSS Guard version: dev

**Comment by martinrotter** [comment]
Well you can map a keyboard shortcut to display main menu (defaults to `M`). That is not enough?

**Comment by Owyn** [comment]
What if I forget to map it and leave it unmapped? It will be gone forever without some serious hacking...

**Comment by martinrotter** [comment]
OK, I added action which can be added to any toolbar - called "Open main menu".

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/151666888-4f22b85d-ec0b-4e31-b725-37c63cd3d176.png)

**Comment by Owyn** [comment]
> OK, I added action which can be added to any toolbar - called "Open main menu".

but can you make a hotkey for it?

actually in most apps there's already a default hotkey for exactly that action (show main menu) - it's `ALT` - e.g. firefox and notepad+

**Comment by martinrotter** [comment]
yes, you can set a hotkey in settings

**Comment by Owyn** [comment]
> yes, you can set a hotkey in settings

but I can't set it to 'ALT', doesn't seem to recognize it and just leaves hotkey empty waiting for more input
