### ISSUE TITLE
[BUG]: clicking tray notification about new article does nothing

### ISSUE THREAD

**Issue by Owyn** [martinrotter/rssguard#606]
### Brief description of the issue

clicking tray notification about new article does nothing

### How to reproduce the bug?

get a new article fetched when RSSguard is minimized to tray
click the balloon notification

### What was the expected result?

RSSguard window should pop-up focused on that article

### What actually happened?

nothing, notification just got hidden

### Operating system and version

* OS: Win10
* RSS Guard version: dev

**Comment by martinrotter** [comment]
Yes, report this upstream (to microsoft). It's known notification bug. Not my bug.

**Comment by Owyn** [comment]
> Yes, report this upstream (to microsoft). It's known notification bug. Not my bug.

 🤔 
Just checked with utorrent, it is minimized to tray, clicking its notification opened the folder of downloaded torrent just fine

Tried the same with Tixati - clicking the notification successfully maximized the apps window from the tray

TinyRSS has its own notification pop-up (not the windows default one) - so maybe at least making that to make things work would do it?

**Comment by martinrotter** [comment]
i will check but usually

**Comment by Owyn** [comment]
> (especially if notification is "old") when it does not

I know that clicking em in notification centers "archive" does nothing (when they pop-up and then go hide there), 

I meant clicking them right when they appear on the screen

**Comment by martinrotter** [comment]
ok, i will test, what windows exact version

**Comment by Owyn** [comment]
> ok, i will test, what windows exact version

![image](https://user-images.githubusercontent.com/1309656/150557598-c99c2655-a1a4-4dd0-9a88-8924eca1fefc.png)

**Comment by martinrotter** [comment]
Also, which exact notification did you click and you expect it to do something?

**Comment by Owyn** [comment]
a notification about new feed

**Comment by martinrotter** [comment]
That notification does not have any "click" action defined in RSS Guard. It's just a notification.

**Comment by martinrotter** [comment]
That notification does not have any "click" action defined in RSS Guard. It's just a notification.

**Comment by Owyn** [comment]
> That notification does not have any "click" action defined in RSS Guard. It's just a notification.

Well it should? cuz other rss readers, QuiteRSS for example - bring you to the reader app window when you click the notification, 

cuz that's what one would expect from clicking a notification about a new unread item in their feed - to go to its reading when clicking the notification
