### ISSUE TITLE
[FR] or [BUG]: find RSS feed on the provided URL?

### ISSUE THREAD

**Issue by Owyn** [martinrotter/rssguard#607]
### Brief description of the feature request

I try to enter `https://stikvk.ru/archives/category/Стикеры/Бесплатные-стикеры` into feed url and RSSGuard errors saying it's not well formed XML, or content not found (I get % characters when I copy right from the Firefox url bar - for that it says XML error)

![image](https://user-images.githubusercontent.com/1309656/150567680-5248d1e3-8472-459c-abc2-3f03e834e1a9.png)
![image](https://user-images.githubusercontent.com/1309656/150567701-004b76ba-0561-456f-83df-deb3357fb1c3.png)

I enter the same into QuiteRSS - and it works fine

![image](https://user-images.githubusercontent.com/1309656/150567568-b705f39e-bc6a-4a7b-a69b-265dd4427a36.png)

![image](https://user-images.githubusercontent.com/1309656/150567967-644cdda1-ff29-4463-a2f9-eb08f60912ad.png)

**Comment by martinrotter** [comment]
1. At this point this works in webengine version, if you navigate to some webpage, RSS Guard detects feeds and gives button to add them.
2. How would you solve situation when site has several feeds?

**Comment by Owyn** [comment]
Not sure about several cuz now it finds none

from user perspective - you don't want to investigate stuff, you just want to give your rssreader a link and make it look for an rss feed there to follow

but if there are several - more specific one I'd say (longer url?), e.g.
site.com/section/feed
instead of
site.com/feed

OR - just ask the user to add both feeds so he'd see for himself what he wants?

**Comment by martinrotter** [comment]
Btw webengine version already has the feature.

When you enter some URL into internal web browser, when its loaded RSS Guard crawls all RSS feeds from page.

![image](https://user-images.githubusercontent.com/1255302/151121443-c53f8ec0-01b4-45b2-8377-7ba302199a01.png)

**Comment by Owyn** [comment]
Also there are many times the website itself doesn't link any feeds but has it, so the reader should try common urls like `/feed` `/rss` etc, like QuiteRSS does
example
https://www.asurascans.com/
https://www.asurascans.com/feed

**Comment by martinrotter** [comment]
Fixed with new "Discover feeds" dialog. Test via devbuild.
