### ISSUE TITLE
[BUG]: Duplicate Entries from Bing News

### ISSUE THREAD

**Issue by AmmarSaleemG** [martinrotter/rssguard#612]
### This issue happens with Bing News only
On each feed fetching from Bing news, it duplicates them. Picture below:

![image](https://user-images.githubusercontent.com/15247707/150923381-b2d957ce-b4aa-4e01-a514-15fe3d3eda12.png)

### How to reproduce the bug?

1 - Add this link into your feed: `https://www.bing.com/news/search?q=breaking+news&format=rss`
2 - Right click > Fetch Feed
3 - Repeat Step 2 and you will get duplicate entries each time you repeat it.

### What was the expected result?

A clean feed with no duplicate entry.

### What actually happened?

Received duplicate entries which bloated my feed list.

### Other information
Pretty sure, their redirect links are different. For that, I guess we need a Title Duplication checking system.
So, a possible solution can be to add _Title Duplicate Entries Checking System_ when we set up a feed. There, this option should be selectable.

### Operating system and version

* OS: WIN-11
* RSS Guard version: 4.1.3 Dev

**Comment by martinrotter** [comment]
Yes, this is because the feed is of shit quality. They use randomly generated URLs in entries which change each time feed is fetched.

RSS Guard is not to blame here and this situation can be easily resolved by using very simple article filter.

**Comment by martinrotter** [comment]
```js
function filterMessage() {
  if (msg.isDuplicateWithAttribute(MessageObject.SameTitle)) {
    return MessageObject.Ignore;
  }
  else {
    return MessageObject.Accept;
  }
}
```

**Comment by AmmarSaleemG** [comment]
Truly impressive. RSSGuard article Filter with script support is an art!
