### ISSUE TITLE
[BUG]: Copy link locations unavailable

### ISSUE THREAD

**Issue by mattrattus** [martinrotter/rssguard#620]
### Brief description of the issue

From the right-click drop-down menu, when the URL is selected, the "Copy Link Location" item is unavailable.
This applies to all web addresses.

### How to reproduce the bug?

Normal usage of applications.

### What was the expected result?

The option should be available.
It was available in version 3.x without any problems.

### What actually happened?

Option is not available.

### Operating system and version

* OS: ArchLinux
* RSS Guard version: 4.0.4 (built on Linux/x86_64)
* Revision: -nowebengine

**Comment by martinrotter** [comment]
@akinokonomi

**Comment by martinrotter** [comment]
@mattrattus Test with latest stable version, for example with latest `AppImage`. Feel free to re-open issue if bug is there with latest version.
