### ISSUE TITLE
[FR]: iterate current date for articles with no own date

### ISSUE THREAD

**Issue by Owyn** [martinrotter/rssguard#621]
### Brief description of the feature request

https://github.com/martinrotter/rssguard/blob/b0b3acf1c2443caf4a7d3c02e9783fe23a7b8bf4/src/librssguard/services/standard/rssparser.cpp#L112

currently it sets same current time for all articles from a feed without their own published-date specified

FR: - subtract article index (1st arcticle, 2nd article... 99th article) from the date-time so it would become possible to sort by time in the RSSGuard for articles without specified pubDate in their feed (pretty much everything generated via script - cuz on sites ppl don't specify publish-date of grabbed-parsed links),
so articles at the top of the feed would get placed at the top of the rssguard articles list window when sorted by date

e.g.:
Title       |      Date
Most Recent article - 15:05
Yesterdays article - 15:04
Very old article- 15:03

how it is now:
Title       |      Date
Very old article - 15:05
Most Recent article - 15:05
Yesterdays article - 15:05

**Comment by martinrotter** [comment]
URL of some feed to test this?

**Comment by martinrotter** [comment]
Nevermind, fixed. I set the increment to 1 second.

![image](https://user-images.githubusercontent.com/1255302/152653692-af9dd155-7992-4e30-8138-780caf8c99bc.png)

**Comment by Owyn** [comment]
Thx, this'd be a great improvement for when you add a (pubDate-less) feed for the first time, before everything had the same time and couldn't be sorted by date

**Comment by Owyn** [comment]
Is it not there yet? 

I tried dev 
`Version: 4.2.0 (built on Windows/AMD64)
Revision: 5ef90cc6-nowebengine`
with related commits above and the time is still all the same

![image](https://user-images.githubusercontent.com/1309656/152656687-3824ce45-d52d-4413-9b30-addd0b320bae.png)

url: `https://asurascans.com`
script: `python css2rss.py "div.luf" "h4" "li > a" "li > a" "li > a"`

**Comment by martinrotter** [comment]
Yes, I completely forgot about JSON feeds. Will fix.

**Comment by martinrotter** [comment]
fixed for json too

![image](https://user-images.githubusercontent.com/1255302/152696210-742046d5-6ba8-47ed-90cc-f068278a97c6.png)
