### ISSUE TITLE
[FR]: display number of unread articles in title and taskbar icon

### ISSUE THREAD

**Issue by Owyn** [martinrotter/rssguard#622]
### Brief description of the feature request

Here: 
![image](https://user-images.githubusercontent.com/1309656/152679460-d1c81ded-49a2-4ec4-b6e2-671ccf36b837.png)

and here:
![image](https://user-images.githubusercontent.com/1309656/152679485-885f1658-8da6-41f2-9e57-b4af468f3864.png)

I disabled tray icon in the settings and now there is basically no place to see if rssguard has new unread items except in the active rssguard window itself - it would be nice if big taskbar icon could show number of unread items (just like tray icon) and rssguard window title had number of unread too e.g. `RSS Guard 4.2.0 (5)` (5 unread items) so you could notice there are new items when you Alt+Tab

**Comment by martinrotter** [comment]
For me: https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist3-setoverlayicon?redirectedfrom=MSDN

**Comment by martinrotter** [comment]
- [ ] title
- [ ] taskbar

**Comment by martinrotter** [comment]
As for taskbar, something like this?

![image](https://user-images.githubusercontent.com/1255302/155491015-97ff6a7e-8bf6-4d00-8076-f25bf032af8f.png)

**Comment by Owyn** [comment]
Yea, just like discord does 
![image](https://user-images.githubusercontent.com/1309656/155493997-65267561-ce5c-4089-8298-05d305f87650.png)

**Comment by martinrotter** [comment]
Improved: 
![image](https://user-images.githubusercontent.com/1255302/155498224-c449d3e5-42d9-4e47-a843-dbc47b2d764f.png)

**Comment by Owyn** [comment]
white background was more visible than green for me...

**Comment by martinrotter** [comment]
indeed, i will polish it a bit and push for testing

**Comment by Owyn** [comment]
orange: 
![image](https://user-images.githubusercontent.com/1309656/155502128-4bd6df2f-b5d9-43ae-956b-fc8a66ebf058.png)

yellow: 
![image](https://user-images.githubusercontent.com/1309656/155502282-5bb06981-4871-4bc2-9d71-a21d2fe79390.png)

yellow looks rather readable

plus not sure but maybe using `sharp` instead of `smooth` for number text might look more clear (I used sharp for my examples above)

![image](https://user-images.githubusercontent.com/1309656/155503261-16e35560-6fed-4f7c-ba76-78cc04116063.png)

**Comment by martinrotter** [comment]
OK, pushed, pls test and report back. Feature is switchable in settings->gui->taskbar.

**Comment by martinrotter** [comment]
![64dnGTDSZ1](https://user-images.githubusercontent.com/1255302/155512999-575b6bd9-43eb-4016-be41-1da4da87b9df.gif)

added taskbar progressbar too

**Comment by Owyn** [comment]
Everything works nicely now

![image](https://user-images.githubusercontent.com/1309656/155518989-65278ff6-1857-44db-8e75-9931cfdc42e0.png)

background square is a bit too big tho

**Comment by martinrotter** [comment]
> Everything works nicely now
> 
> ![image](https://user-images.githubusercontent.com/1309656/155518989-65278ff6-1857-44db-8e75-9931cfdc42e0.png)
> 
> background square is a bit too big tho

Not big if you have more digits-number of unread, it is now configured to display values up to "999" and in that case, the square is just about right

**Comment by martinrotter** [comment]
I polished the number size a bit.
