### ISSUE TITLE
[BUG]: Width of "Title" column cannot be manually adjusted.

### ISSUE THREAD

**Issue by geverl** [martinrotter/rssguard#623]
### Brief description of the issue

Width of "Title" column cannot be manually adjusted:
![image](https://user-images.githubusercontent.com/3144213/152690794-c68a7818-57aa-42fc-8e32-bdbe39c738f2.png)

### How to reproduce the bug?

Open RSS Guard and try to make "Title" column wider or smaller without changing overall window width.

### What was the expected result?

Width of "Title" column should be adjustable in the same way that the width of other columns is.

### What actually happened?

Width of "Title" column cannot be manually adjusted.

### Other information

![image](https://user-images.githubusercontent.com/3144213/152690871-624d2daf-40c4-41a5-8c14-654e514f1e52.png)
[rssguard.zip](https://github.com/martinrotter/rssguard/files/8010601/rssguard.zip)

### Operating system and version

Version: 4.1.2 (built on Windows/x86_64)
Revision: 1f5157fd
Build date: 1/10/22 7:26 AM

**Comment by martinrotter** [comment]
"title" column is set to be "interactive" - it fills all remaining space. You need to tweak width of other columns+window to achieve desired width.

![rssguard_UQZrOPJXmp](https://user-images.githubusercontent.com/1255302/152696422-e9f716d5-6139-4e32-b5a2-a5ff27497451.gif)
