### ISSUE TITLE
[BUG]: "Check for updates on application startup" is ambiguous

### ISSUE THREAD

**Issue by aleksejrs** [martinrotter/rssguard#626]
### Brief description of the issue

Fetching articles includes checking for updates of feeds.
This setting on the General pane is about checking for updates *of RSS Guard*, but doesn't say so explicitly.
Feeds are more important to the user.

### How to reproduce the bug?

Be a new user, wanting to change the global interval or configure fetching on startup.
Open settings.

### What was the expected result?

See feed and article settings on top, and/or the app launching/updating pane named "RSS Guard", "Application"~~, "Software itself"~~ or something. Or (easier):
See "[ ] Check for new versions of RSS Guard on application startup".

### What actually happened?

See "[ ] Check for updates on application startup" and think it's about fetching articles, and there are no other settings for that.

### Operating system and version

* OS: Debian stable-testing mix.
* RSS Guard version: 4.0.4 from Debian testing.

**Comment by martinrotter** [comment]
I re-phrased the label.
