### ISSUE TITLE
Highlight search keyword in result messages

### ISSUE THREAD

**Issue by blackarcher21** [martinrotter/rssguard#63]
I can't find any way for this, so I would like to make a request. I think it will help to find where a certain words appear in messages, especially messages with lots of content. Whether it will be optional or by default, that would be your decision. :)

**Comment by martinrotter** [comment]
You can filter messages with top/right textbox which should filter via all columns. But I guess that you want to add standard CTRL+F searching/highlighting in single selected message right? Does this concern webengine message display mode or simple text message display mode?

**Comment by blackarcher21** [comment]
> I guess that you want to add standard CTRL+F searching/highlighting in single selected message right?
Yes. When read on filtered message, keywords are highlighted in every messages in preview (if possible).
>Does this concern webengine message display mode or simple text message display mode?
I only use and test with simple text message display which doesn't have it. Which one should/possible to have it, maybe you know more about it. I hope it possible for both though.

**Comment by martinrotter** [comment]
> Yes. When read on filtered message, keywords are highlighted in every messages in preview (if possible).

To understand you. I understand this that you want to highlight searched words with ONE message? Is that correct? You can filter all messages in message list already, that feature is there.

**Comment by blackarcher21** [comment]
I don't see any highlight in message I preview.
What I do:
- Enter keyword in search box
- Select a message from filtered to show it in preview
- Looking for message content, no words are highlighted.
OK, I test with current version I use v3.3.5 nowebengine, and previous version I saved, v3.3.4
Am I wrong? Sorry if there's a misunderstanding here

**Comment by martinrotter** [comment]
Yes yes, you get it right. The search box is meant to show only messages which contain entered keyword, the keyword itself is not highlighted in any way in those messages.

I will add probably CTRL+F shortcut and implement "find dialog" for webengine and maybe for no-webengine too, if possible.

**Comment by martinrotter** [comment]
EDIT: I made research, it is possible to add "find/highlight" for both message frontends.

**Comment by martinrotter** [comment]
BTW: I tweaked my auto-build scripts and no-webengine version of RSS Guard is now automatically compiled from EACH commit.

https://github.com/martinrotter/rssguard/wiki/Windows-development-builds

**Comment by blackarcher21** [comment]
Thanks for the notification :)

**Comment by martinrotter** [comment]
Fixed, see changelog on how to use.
