### ISSUE TITLE
[FR]: Custom UI color themes? edit existing ones?

### ISSUE THREAD

**Issue by Owyn** [martinrotter/rssguard#634]
### Brief description of the feature request

I couldn't find themes in the apps folder anywhere to edit it (without recompiling everything) , it would be nice if we could do that - people would be interested in making custom color themes

**Comment by martinrotter** [comment]
You already can do custom themes! First read "Skins" section [here](https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#skin).

Basically, you create "skins" subfolder in your user data folder and then copy some existing skin for example ["plain"](https://github.com/martinrotter/rssguard/tree/master/resources/skins/plain) into the folder, so you will have "......\data4\skin\my-plain\" path. RSS Guard on restart will detect the skin and you can activate it. Files inside the "plain" are documented, so you can have some idea how to use them.

**Comment by martinrotter** [comment]
Also, turing to discussion.
