### ISSUE TITLE
[BUG]: Alerting Unread on Old Items Marked Read

### ISSUE THREAD

**Issue by donuts-are-good** [martinrotter/rssguard#640]
### Brief description of the issue

I use RSS Guard to subscribe to youtube channel feeds. The issue I am experiencing is that I get notifications intermittently of items that were previously already marked read, and were posted days ago. 

Notes: I have refresh set to pull new items every 2 minutes, and I have double checked that nothing is being edited in the description or titles of these items (initially I assumed that the notification was triggered by items being edited by the creators being rebroadcast to their feeds, this was incorrect). 

Attempts at resolution: None of these attempted solutions have caused a difference-
- reboot
- reinstall
- re-adding the feeds
- changing feed interval to 10 minutes
- mark all items (globally) as 'read'

Please advise. 

### How to reproduce the bug?

1. create a folder for youtube feeds
2. add some youtube channel rss feeds
3. set refresh interval to 1, 2 mins
4. turn on notifications

### What was the expected result?

I expected old items not to re-alert me after opening them, or marking them read.

### What actually happened?

I was notified intermittently (not every sync) throughout the day and night of new episodes of Bonne Appetit, and other shows.

There were in fact no new episodes of Bonne Appetit and other shows. 

### Other information

I'm probably misconfigured somehow, but I just can't find it.

### Operating system and version

* OS: Linux
* RSS Guard version: RSS Guard
Version: 4.0.4 (built on Linux/x86_64)
Revision: 
Build date: 10/17/21 9:01 AM
Qt: 5.15.2 (compiled against 5.15.2)

**Comment by donuts-are-good** [comment]
In what appears to be an effort to protest, it has just re-alerted me again on an item posted yesterday.

**Comment by martinrotter** [comment]
Some feeds (youtube in particular) often "updates" articles. The same article gets updated - it time changes, or its contents changes or its title changes for example. If that happens, RSS Guard detects it and article is updated in RSS Guard too and marked unread again.

It is hard to say without deep observation what exactly in the article got changed. Log file would show more data. This is not a bug, but a feature.

> I have double checked that nothing is being edited in the description or titles of these items

Trust me. We had similar "bug" reports before and always it turned out that it is the case.

**Comment by martinrotter** [comment]
Post URL of some youtube feed with the "problem". I will check but I am almost positive that it is the case as I wrote above.

**Comment by donuts-are-good** [comment]
> is not a bug, but a feature

The amount of consternation on this end of the keyboard has motivated me to walk across the house and get a book on modern C++ from the bookcase. 

I can't be held responsible for what happens if I'm forced to begin chapter 1.

https://www.youtube.com/feeds/videos.xml?channel_id=UC2TXq_t06Hjdr2g_KdKpHQg
https://www.youtube.com/feeds/videos.xml?channel_id=UCptavIZTUzswaKbEEDP9KxQ

**Comment by martinrotter** [comment]
OK, testing.

Do you have this checked?

![image](https://user-images.githubusercontent.com/1255302/154210484-f8de12d1-d77b-4c19-a094-ab3f1c25f38f.png)

**Comment by martinrotter** [comment]
OK. I checked and youtube feeds change date/time of articles frequently. For example:

```
date existing   1644889057000 - Tuesday, 15 February 2022 01:37:37
date new        1644995123000 - Wednesday, 16 February 2022 07:05:23
```

Not sure why Youtube does this.

This behavior can be EASILY solved with RSS Guard feature called "article filtering" which can automatically reject these updated articles. This simple filter will do:

```js
function filterMessage() {
  if (msg.isDuplicateWithAttribute(MessageObject.SameUrl)) {
    return MessageObject.Ignore;
  }
  else {
    return MessageObject.Accept;
  }
}
```

**Comment by donuts-are-good** [comment]
Too late, I've begun chapter 1. We're going to merge this PR-from-hell together when I'm done with it in a few years time. 

> OK, testing.
> 
> Do you have this checked?
> 
> ![image](https://user-images.githubusercontent.com/1255302/154210484-f8de12d1-d77b-4c19-a094-ab3f1c25f38f.png)

Yes it was already checked.

**Comment by donuts-are-good** [comment]
> ```js
> function filterMessage() {
>   if (msg.isDuplicateWithAttribute(MessageObject.SameUrl)) {
>     return MessageObject.Ignore;
>   }
>   else {
>     return MessageObject.Accept;
>   }
> }
> ```

Thanks for the reply. I'm going to assume I should 'just know' where this filtering takes place. I will give it a shot and get back to you in a new separate issue since this one was hastily closed.

**Comment by donuts-are-good** [comment]
For anybody else reading this who is also not-an-rssguard-dev-or-expert, you're looking for 'Article filtering' in Accounts from the top menu, it's the last option.

**Comment by donuts-are-good** [comment]
I'm just winging it, and I apologize if it isn't done correctly. The interface leaves much to be desired as far as instruction.

I guess I'm just supposed to click New Filter, since trying to insert into the text box before that gives zero feedback or output. I clicked new filter, and I've pasted in the code, and I have no clue how I save it, or if it is now active, or any obvious feedback of the sort. I'm just going to close this dialog box after inputting the filter text and do a short prayer in hopes that it worked.

Also, clicking "test" highlighted a big list of red entries, which at first glance looks like my entire feed list, but I can't tell because I don't have them memorized to know if this is the entire set of feeds or a subset of them. This would have been much better represented by a number or something that tells me the amount of feed items vs culled items or culled updates, etc.

---


Everything after this point is unnecessary commentary, it can be skipped if you don't have a thick skin or a historyof exposure to the Linux kernel dev mailing list.


---

Look, I'm not going to tell you directly that you should do a rewrite or a substantial cleanup, but if it were me I'd do a rewrite. I'm uninitiated to your program, and despite being generally experienced with feedreaders, I literally had to crawl the repo code looking for where something called "filter" would exist. Browsing the code of this repo was an eye opener.

 A lot of the way things are arranged is as if they were just added as you went. Example, why am I setting font sizes all over the settings window, why not just put all of those inside the category for UI changes? You have font settings there, and in other pages.

I'm beginning chapter 2 today of C++ for dummies. Shape up your project or I'm coming for you when I'm done with this book. You don't want to review my pull requests, trust me, don't force my hand. It's better for all of us if you just put things where they belong, plan features properly, work on some wizard prompts etc.
