### ISSUE TITLE
[FR]: install with brew

### ISSUE THREAD

**Issue by foolioo** [martinrotter/rssguard#643]
### Brief description of the feature request

Thank you for your fine work!

The community would love to have RSSGuard on [brew](https://github.com/Homebrew/brew). This will ease the installation and upgrades of RSSGuard.

As a reference, here is an [example of brew formula](https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/vienna.rb).

**Comment by martinrotter** [comment]
Hello @foolioo.

1. I do not own Mac OS machine. So creating `brew Cask` is rather not easy.
2. I build `dmg` [files](https://github.com/martinrotter/rssguard/releases) for Mac OS which you can use as a source for brew formula/cask.
3. I am not a packager.

Sorry.
