### ISSUE TITLE
Connecting Owncloud and tinytiny rss readers FAILS

### ISSUE THREAD

**Issue by pixadex** [martinrotter/rssguard#65]
So when I'm trying to connected to server it doesn't connected but on there version it did???

**Comment by martinrotter** [comment]
Please, I do not get one single piece of information from your issue.

So connecting to OwnCloud and/or TT-RSS servers fails? It worked in previous RSS Guard versions? What errors do you get?

**Comment by pixadex** [comment]
One thing how do you restart rssguard because when I connected to sever it says you have to restart manually, is that normal?

**Comment by pixadex** [comment]
Yea you have something thats works for ownclould because it says 9.0.5 will 9.0.2 work?

**Comment by martinrotter** [comment]
Write your bug reports in correct English, closing this as invalid.
