### ISSUE TITLE
[FR]: Resolving relative URLs

### ISSUE THREAD

**Issue by guihkx** [martinrotter/rssguard#652]
### Brief description of the feature request

Just a minor request (I hope 😄), and I'm not sure if this is specific to the NOWEBENGINE build, but take this sample ATOM feed from a GitLab repository:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/">
<title>pipewire:master commits</title>
<link href="https://gitlab.freedesktop.org/pipewire/pipewire/-/commits/master?feed_token=&amp;format=atom" rel="self" type="application/atom+xml"/>
<link href="https://gitlab.freedesktop.org/pipewire/pipewire/-/commits/master" rel="alternate" type="text/html"/>
<id>https://gitlab.freedesktop.org/pipewire/pipewire/-/commits/master</id>
<updated>2022-02-22T12:42:36+01:00</updated>
<entry>
  <id>https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/542b0acd7334b8817d9ac7df419f42b0e1c58093</id>
  <link href="https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/542b0acd7334b8817d9ac7df419f42b0e1c58093"/>
  <title>context: set zero_denormals in data thread.</title>
  <updated>2022-02-22T11:31:06+01:00</updated>
  <media:thumbnail width="40" height="40" url="https://secure.gravatar.com/avatar/658fd1a5efb5b1865941c856f54b9ee8?s=80&amp;d=identicon"/>
  <author>
    <name>Wim Taymans</name>
    <email>wtaymans@redhat.com</email>
  </author>
  <summary type="html">
Use invoke to set the zero-denormals flag from the data thread when
explicitly set. The flag is per thread and should really only be set on
the data thread and only when explicitly enabled.

Fixes &lt;a href="/pipewire/pipewire/-/issues/2160" data-original="#2160" data-link="false" data-link-reference="false" data-project="4753" data-issue="51116" data-reference-type="issue" data-container="body" data-placement="top" title="pw_context_new sets DAZ bits in MXCSR register, crashes LuaJIT" class="gfm gfm-issue has-tooltip"&gt;#2160&lt;/a&gt;</summary>
</entry>
</feed>
```

RSS Guard will render the message like this in the NOWEBENGINE version (which is correct, as far as I can tell):

![image](https://user-images.githubusercontent.com/626206/155148934-b264ea92-0188-4a23-9459-3c2a9248d2c5.png)

However, despite that `#2160` link at the end being clickable, when you try to click on it, the external web browser won't open, because it's not an absolute URL and I think RSS Guard can't handle relative URLs at the moment...?

Thank you!

**Comment by martinrotter** [comment]
There already was/is some logic to deal with realtive URLs within feed entries.

In WebEngine variant of RSS Guard, I set base URL correctly when possible and relative URLs should just work.

In Non-webengine build I agree, it probably is not just there. Let me check.

**Comment by martinrotter** [comment]
I believe this is fixed, tested with feed https://gitlab.freedesktop.org/pipewire/pipewire/-/commits/master?feed_token=&amp;format=atom

**Comment by guihkx** [comment]
On what desktop environment did you test this? I grabbed the latest dev AppImage to test it, but on GNOME it doesn't work when you try to open the link in the external web browser (internal browser works though):

**gio: file:///pipewire/pipewire/-/issues/2328: Error when getting information for file “/pipewire/pipewire/-/issues/2328”: No such file or directory**

https://user-images.githubusercontent.com/626206/166232409-6cafc15a-7295-49a0-a3df-b77348b2c9d4.mp4

**Comment by martinrotter** [comment]
![rssguard_8pUKC51f9C](https://user-images.githubusercontent.com/1255302/166235469-708bee98-c352-4271-bad7-bc9057ffaaa2.gif)

**Comment by guihkx** [comment]
Yes, like I mentioned, it works when I open the link using the "internal browser" of RSS Guard, but it doesn't work if I try to open it with the external web browser. Does it work on Windows, though? 🤔

**Comment by martinrotter** [comment]
OH I see, let me check

**Comment by martinrotter** [comment]
4348a51d6

Pls test with latest master when devbuild compiles.

**Comment by guihkx** [comment]
Works now! Thanks! :D
