### ISSUE TITLE
Umlauts are not displayed correctly in the user account

### ISSUE THREAD

**Issue by Simlock** [martinrotter/rssguard#657]
### Brief description of the feature request

Umlaute werden beim Benutzerkonto nicht richtig dargestellt.

J�rg (RSS/ATOM/JSON)

richtig wäre

Jörg (RSS/ATOM/JSON)

Google Übersetzer
Google Translator

Umlauts are not displayed correctly in the user account.

J�rg (RSS/ATOM/JSON)

would be right

Jörg (RSS/ATOM/JSON)

![Screenshot 2022-03-07 181119](https://user-images.githubusercontent.com/4655434/157085643-0922c7a2-51bf-4d52-9978-41fd0e2e950e.jpg)

**Comment by martinrotter** [comment]
reproduced and fixed the bug, thanks.
