### ISSUE TITLE
[BUG]: nodejs settings option gone on 4.0.4

### ISSUE THREAD

**Issue by sbe-arg** [martinrotter/rssguard#658]
### Brief description of the issue

Can't configure nodejs options for adblock to work on 4.0.4

### How to reproduce the bug?

try to enable ad-block it crashes due missing nodejs configs
there is no nodejs settings anymore

### What was the expected result?

enabling ad-block

### What actually happened?

fails as can't find nodejs

### Operating system and version

* OS: fedora 35 
* RSS Guard version: 4.0.4

**Comment by martinrotter** [comment]
Test with latest stable release. If issue persists re-open the ticket.
