### ISSUE TITLE
[FR]: Enhancement for "count of Unread Messages in Tray & Taskbar"

### ISSUE THREAD

**Issue by AmmarSaleemG** [martinrotter/rssguard#662]
### Brief description of the feature request

There is no use of having the ability of count (of Unread Messages in Tray & Taskbar), if it shows you infinity sign after an increase from a certain amount.
![image](https://user-images.githubusercontent.com/15247707/159435740-c1c102e5-eb45-4258-aed6-5d4ffc24f15f.png) ![image](https://user-images.githubusercontent.com/15247707/159435807-4d12bfb0-a21c-450c-99d2-808c18a5d6bc.png)

### Possible workaround for this

1. Either add an ability which allows us to select the specific set of Feeds separately and show their count exclusively.
OR
2. Simplify it if it increases from 1000 unread items to:

   - 1k  for 1000 feeds
   - 1.2k for 1200 feeds
   - 10k for 10000 feeds

**Comment by martinrotter** [comment]
fixed

![image](https://user-images.githubusercontent.com/1255302/159439816-9eb16dd4-fb4b-465c-804a-501ad34b51fb.png)

**Comment by AmmarSaleemG** [comment]
> fixed, now it shos "15k" for 15000 (circa) messages etc, works up to 99999 messages, higher numbers shown as infinity

Now that's perfect.

**Comment by martinrotter** [comment]
fixed for tray icon too
