### ISSUE TITLE
[BUG]: Can't Import FEEDS

### ISSUE THREAD

**Issue by cement-head** [martinrotter/rssguard#664]
### Brief description of the issue

Switching laptops.  Exported FEEDS from RSSGuard into a file.  Copied the OPML file to new laptop. Started RSS Guard and attempted to Import FEEDS.  File is recognised, but no feeds are listed in the preview and therefore cannot import feeds.

### How to reproduce the bug?

Switching laptops.  Exported FEEDS from RSSGuard into a file.  Copied the OPML file to new laptop. Started RSS Guard and attempted to Import FEEDS.  File is recognised, but no feeds are listed in the preview and therefore cannot import feeds.

### What was the expected result?

Switching laptops.  Exported FEEDS from RSSGuard into a file.  Copied the OPML file to new laptop. Started RSS Guard and attempted to Import FEEDS.  File is recognised, but no feeds are listed in the preview and therefore cannot import feeds.

### What actually happened?

Switching laptops.  Exported FEEDS from RSSGuard into a file.  Copied the OPML file to new laptop. Started RSS Guard and attempted to Import FEEDS.  File is recognised, but no feeds are listed in the preview and therefore cannot import feeds.

### Operating system and version

* OS: Linux (Ubuntu/Pop_OS)
* RSS Guard version: 4.1.2

**Comment by martinrotter** [comment]
provide the file here pls

**Comment by cement-head** [comment]
[rss-guard-feeds.opml.txt](https://github.com/martinrotter/rssguard/files/8333969/rss-guard-feeds.opml.txt)

Appended <.txt> to the end of the file for upload.  TIA.

**Comment by martinrotter** [comment]
I was able to import with 4.2.1 version just fine.

![image](https://user-images.githubusercontent.com/1255302/159856875-c0f1286a-5afe-489a-98c1-2b79b0351050.png)

Provide debug log which you should have provided in the first place. Then I can re-open.

**Comment by cement-head** [comment]
How do I generate a debug log?

**Comment by cement-head** [comment]
4.2.1 from the AppImage won't run on Pop_OS 20.04 (crashes on launch).
