### ISSUE TITLE
[BUG]: 4.2.1 release "Please, fill the survey." No option to refuse.

### ISSUE THREAD

**Issue by jeandestouches** [martinrotter/rssguard#667]
### Brief description of the issue

Hello,
After updating to 4.2.1, this box appeared "Please, fill the survey." without any way to refuse.
Then, it opened my browser with this address : https://forms.gle/9GgSa38Awqr37xLV8 which redirects to a docs.google.com page. :/
Please at least offer a way to refuse that for the next release.
Thanks.

### How to reproduce the bug?

-

### What was the expected result?

-

### What actually happened?

-

### Operating system and version

* OS: Gentoo
* RSS Guard version: 4.2.1

**Comment by martinrotter** [comment]
Hi, that prompt only show on 4.2.1 and shows once, it is already commented out for next releases. Also, when I will do next survey, I will display yes/no message box to allow users to decline.
