### ISSUE TITLE
MYQSL

### ISSUE THREAD

**Issue by pixadex** [martinrotter/rssguard#67]
"That's because your MySQL database was not running when RSS Guard was launched. Also, when you switch data storage options in settings, RSS Guard needs to be restarted."
1. how do I run mysql
   2.switch data storage options 
   3.can you give me directions not information please stop closing thread please need to fix this

THANK YOU.

**Comment by martinrotter** [comment]
Bro, I really cannot tell you how to run MySQL. Just Google it OMG.

**Comment by martinrotter** [comment]
Your "bug" reports are written in totally shit English, you do not provide debug logs. You do not follow default template. What can I do in this situation?

**Comment by pixadex** [comment]
it was working before on your program now its not, I downloaded this https://dev.mysql.com/downloads/windows/ you think it would work because its your the programmer so you should know and what other information do you want to fix this problem. TEAMVIEWER?

**Comment by martinrotter** [comment]
When you create new bug report, there is predefined text in it which you should complete. You also did not provide debug log.

**Comment by pixadex** [comment]
ok so how do I make a log again, I forgot the process.

**Comment by martinrotter** [comment]
Check wiki.

**Comment by pixadex** [comment]
2. problem... https://imgur.com/a/SvFql

**Comment by martinrotter** [comment]
I compile RSS Guard for Mac OS X but I have absolutely no way how to test or debug it. I do not have Mac  machine.

Someone else must do it. It seems that Mac OS searching for QtWidgets library in the wrong place, because all Qt libraries should be packed in the bundle.

**Comment by martinrotter** [comment]
@pixadex 

I made some blind fixes, testing version is compilling right now....

It will compile and results are here: https://travis-ci.org/martinrotter/rssguard/jobs/167554240

When it compiles, go to Wiki -> Mac OS dev builds and test the latest build (one at the bottom).
