### ISSUE TITLE
[FR]: Make the use of npm optional

### ISSUE THREAD

**Issue by lgbaldoni** [martinrotter/rssguard#671]
### Brief description of the feature request

I package rssguard for openSUSE and I'm having trouble with the integrated npm package manager. It would be far more acceptable to install what's required by hand.

Which packages are actually required?

**Comment by martinrotter** [comment]
Hello @lgbaldoni.

Usage of NODE/NPM IS optional. The only features which use npm/node are these:
* adblock,
* reader mode.

Both of those features are completely optional, side features which are both opt-in (off by default). RSS Guard executable/library does not "link" against any of node/npm libs and when user wants to use some of those features above, he is warned if node is not found.

So no new deps are required, but if opensuse packaging format allows for "optional deps", then I would recommend to add packages which offer "node" and "npm" executables.
