### ISSUE TITLE
[BUG]: Loop of SilentNetworkAccessManager

### ISSUE THREAD

**Issue by salvadorbs** [martinrotter/rssguard#672]
### Brief description of the issue

It cannot get information from Inoreader on first run

### How to reproduce the bug?

1. Install RSSGuard (from scoop repo)
2. Add inoreader account with some feeds
3. Download feed
4. Infinite loop

### What was the expected result?

Feed downloaded

### What actually happened?

Infinite loop:
time="    94.465" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="    96.794" type="debug" -> network: Destroying Downloader instance.
time="    96.795" type="debug" -> network: Destroying SilentNetworkAccessManager instance.

### Operating system and version

* OS: Windows 10
* RSS Guard version: 4.2.1

**Comment by martinrotter** [comment]
That's not loop, it just takes time (only initial sync), adjust your acc settings and make sure that intelligent sync. algorithm is enabled. Also, limit number of articles by setting reasonable "only download newer articles" date/time.

I see you waited like 90 seconds, that is not enough, particularly if you have many thousands articles + Inoreader API is known to be SLOW, fucking SLOW.

**Comment by salvadorbs** [comment]
Without logging, in another session, I have been waiting for over an hour and have had no results. Anyway thank you.

**Comment by martinrotter** [comment]
Also, what happens if you try to set more recent date here?

Try to set like 1 month in the past date, 1 March 2022. If you try it, does the sync go fast?

![image](https://user-images.githubusercontent.com/1255302/161053124-2d8a5678-e70b-40e6-952d-f90e16a18ab5.png)

**Comment by martinrotter** [comment]
No answer, closing.
