### ISSUE TITLE
[BUG]: cookie can not work

### ISSUE THREAD

**Issue by fulige18** [martinrotter/rssguard#674]
### Brief description of the issue

problem1.the cookie can not save 
problem2.can not login in

### How to reproduce the bug?

1.I successfully logged into this website and it was successfully saved. But after more than ten minutes, the login status disappeared.
2.can not login in

### What was the expected result?

problem1.the cookie can  save 
problem2.can login in

### What actually happened?

problem1.the cookie can not save 
problem2.can not login in

### Other information

the problem 1 site is https://post.smzdm.com
the problem 2 site is https://www.52pojie.cn/

### Operating system and version

* OS:Windows Portable
* RSS Guard version:4.2.1

**Comment by martinrotter** [comment]
I did some testing with some websites I have username/password at. I logged in in one tab of RSS Guard, did some work for some times, then tried to open the site in other RSS Guard tab and I was still logged in.

All cookies are kept in application memory for the whole time when RSS Guard runs. Maybe the website does limit the "alive" time for cookies somehow. Anyway, I cannot reproduce the problem.

Are you having the problem on some websites only or on all websites?

**Comment by fulige18** [comment]
I just need to log in on the two websites I provided. I was logged in that day, but it became not logged in a few days later. However, the same website stays logged in all the time on QuiteRss. So I am wondering if there is some setting option that is not configured. Or the reason for the portable version?

**Comment by martinrotter** [comment]
@fulige18 I just pushed 7cac9d7f5.

Wait 20 minutes and then pls try latest development [build](https://github.com/martinrotter/rssguard/releases/tag/devbuild) and check if issue is resolved.

**Comment by fulige18** [comment]
> > I just need to log in on the two websites I provided. I was logged in that day, but it became not logged in a few days later. However, the same website stays logged in all the time on QuiteRss. So I am wondering if there is some setting option that is not configured. Or the reason for the portable version?
> 
> It should really just work, no matter if portable or not.
> 
> As this is a bug, you really must provide application debug log of whole session(s).
> 
> https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#reprt
> 
> Also, do you restart RSS Guard between those days? If you do, also provide debug log when you re-start RSS Guard the next day (the day when login stops working).
> 
> It could be related to RSS Guard stop-start mechanism. Can you also try to login, quit RSS Guard, start it again and check if it works?

I've definitely rebooted, but if I log back in immediately after logging in, the logged in state is still there. If I log in tomorrow, it becomes logged out again

**Comment by fulige18** [comment]
> @fulige18 I just pushed [7cac9d7](https://github.com/martinrotter/rssguard/commit/7cac9d7f5b7b26529215bb83a4081770247a1be2).
> 
> Wait 20 minutes and then pls try latest development [build](https://github.com/martinrotter/rssguard/releases/tag/devbuild) and check if issue is resolved.

ok，i will try it ,tomorrow  reply to you.thanks

**Comment by fulige18** [comment]
resolved,nice job
