### ISSUE TITLE
[FR]: Can I make filters to be not case sensitive?

### ISSUE THREAD

**Issue by meelten** [martinrotter/rssguard#676]
### Brief description of the feature request

I have no idea about coding. I need simple filters to ignore messages containing certain words in title so I copy-pasted example from documentation. Problem is it works in case sensitive manner, how can I make it insensitive? I want put "some title" into filter and have it remove "Some title", "Some Title" and "sOmE TiTlE" as well.

Also I can't test it at the moment but I wonder if filters work for character sequences that are part of other words? For example if I put 'star' into filter will it remove titles with "popstar", "rockstar", "starring", "stark" etc.? If not can I make it to?

**Comment by martinrotter** [comment]
Make your strings lower case and also make the title lowercase. Can you post your script? Sample:

```js
var blacklist = [
  'other name', 'some other name'
];
function filterMessage() {
  if (blacklist.some(i => msg.title.toLowerCase().indexOf(i) != -1)) {
    return MessageObject.Ignore;
  } else {
    return MessageObject.Accept;
  }
}
```

**Comment by meelten** [comment]
I just used blacklist example from [wiki](https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#examples).

The script you posted works perfect. Thank you. Maybe it's worth adding to examples, at least I find it very useful.

**Comment by martinrotter** [comment]
> Also I can't test it at the moment but I wonder if filters work for character sequences that are part of other words? For example if I put 'star' into filter will it remove titles with "popstar", "rockstar", "starring", "stark" etc.? If not can I make it to?

The filter I posted works exactly that way as it uses JavaScript method [`indexOf`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf).

So "star" in "stark" would match.
