### ISSUE TITLE
[FR]: System tray option to toggle window visibility

### ISSUE THREAD

**Issue by guihkx** [martinrotter/rssguard#679]
### Brief description of the feature request

Hi! Can you please consider adding an option to the system tray context menu that toggles RSS Guard's visibility?

I'm using GNOME, so before upgrading to the more recent v42 release, I'd just double click the tray icon and the window state would toggle between "hidden to tray" and visible,  and that used to work just fine (albeit sometimes buggy).

However, now double clicking the tray icon does absolutely nothing, so probably something broke in this v42 update... Nevertheless I think it'd be a nice addition. In case you need a implementation reference, KeePassXC's is pretty solid.

Thank you in advance!

**Comment by guihkx** [comment]
Wow, that was quick haha

Thank you very much for your hard work on this project <3

**Comment by martinrotter** [comment]
Anyway, Gnome is know to not give a fuck about users.

Everybody loves fixing their upstream bug in our downstream projects.

**Comment by guihkx** [comment]
Yeah, I think it's pretty sad that we have to rely on an third-party extension for having a working system tray icon. :(

But IIRC there are some people working on a new system tray standard (again lol), so we'll see...

**Comment by martinrotter** [comment]
> new system tray standard

WHAT. Ok. That suxx.

**Comment by guihkx** [comment]
Yup, here: https://gitlab.freedesktop.org/xdg/xdg-specs/-/issues/84

By the way I just realized that double clicking stopped working for all programs that I use, not just RSS Guard.

Damn it... I think I should've actually reported this to the guy maintaining the system tray extension.

But thanks for the fix nevertheless!

**Comment by martinrotter** [comment]
It does not bother me, I do not use gnome and I implicitly expected that it broke for all apps.  There is very general code snippet in RSS Guard which enables tray icon "activations" and it is Qt code which should just work for all supported platforms.

This is clearly upstream regression, which should be fixed upstream. Here we just workarounded it kind of.

**Comment by cement-head** [comment]
thanks!
