### ISSUE TITLE
Improvements for Windows Zoom level in the message preview

### ISSUE THREAD

**Issue by groentebroer** [martinrotter/rssguard#68]
#### Brief description of the issue.

In Windows the user has the ability to set a "global" zoom level.
In this way, you can use the high resolution and will still be able to read the text.
For some reason the preview window does not seem to honor this zoom level. But the feed titles and article titles do.
#### How to reproduce the bug?
1. Install RSS Guard on Windows
2. Set the Zoom level. (Right click on the desktop and "display settings")
3. Logout / Login to make it fully active
4. Take a look at the message preview of an article. It is not adjusted to the zoom level.
#### What is the expected result?

The zoom level should be honored.
#### What actually happened?

The zoom level is not honored, so in my case the font is to small to read.
#### Other information (logs, see Wiki)

It is possible to adjust the font size in the settings, which solves the issue. But when using an external display with a different zoom level, the font should be changed back again. This forces me to change it every time when changing between external and internal monitor.

**Comment by martinrotter** [comment]
It seems, that this issue influences only webengine-based message previewer. Simple, text-based previewer scales its text well and makes it bigger if one sets 100%+ zoom.

Actually, I think that this is a bug upstream, not RSS Guard bug. I would have to detect zoom changes by myself in application and change "zoom" level of web-based previewer manually, which, I think, is not correct approach.

But I will investigate it further.

**Comment by groentebroer** [comment]
In addition, when the zoom level changes with RSS Guard opened, (connecting the PC to an external monitor) the new zoom level is also not honored by the feed titles and article titles. (Restarting RSS Guard solves this.)

**Comment by martinrotter** [comment]
Yea yea. Qt-based apps are not able to automatically rescale themselves, restarting RSS Guard must be done for changes to take effect.

**Comment by martinrotter** [comment]
I double-checked, this is definitely Qt upstream bug.
