### ISSUE TITLE
[FR]: General option: "Don't fetch articles older than X days" (for standard RSS/ATOM/JSON "accounts")

### ISSUE THREAD

**Issue by RetroAbstract** [martinrotter/rssguard#683]
### Brief description of the feature request

As the title says, this general option would allow the user to set RSSGuard to not fetch articles older than X amount of days for all feeds for standard RSS/ATOM/JSON "accounts".

Would be located in: Tools > Settings > Feeds & Articles > Feed Fetching > Don't fetch articles older than [X] days.

**Comment by RetroAbstract** [comment]
> You want this for standard RSS/ATOM/JSON "account"? Because some accounts (like TT-RSS or Nextcloud Nexws) have similar option.

Yes

**Comment by martinrotter** [comment]
This was added in https://github.com/martinrotter/rssguard/pull/1019

It can be activated either globally in app settings -> feed&messages -> articles or separately for each feed.

**Comment by RetroAbstract** [comment]
> This was added in #1019
> 
> It can be activated either globally in app settings -> feed&messages -> articles or separately for each feed.

The new feature appears to work fine on a per feed basis, but not globally.

Setting the date to for example 01/08/2023 in the app settings, articles from before the set date are still added to the db.

**Comment by martinrotter** [comment]
> 

I see, if you set global limit, how does the setting page of AFFECTED feed looks like?

**Comment by RetroAbstract** [comment]
> > 
> 
> I see, if you set global limit, how does the setting page of AFFECTED feed looks like?

If I set the global limit, every feed still has "Add articles with any date to the database" enabled in the feeds' settings.

Feeds that have a set date specificially for them through their settings aren't affected in any way by enabling/disabling the feature globally and changing the set date globally.

The global aspect of the feature doesn't appear to affect anything.

**Comment by martinrotter** [comment]
> > > 
> > 
> > 
> > I see, if you set global limit, how does the setting page of AFFECTED feed looks like?
> 
> If I set the global limit, every feed still has "Add articles with any date to the database" enabled in the feeds' settings.
> 
> Feeds that have a set date specificially for them through their settings aren't affected in any way by enabling/disabling the feature globally and changing the set date globally.
> 
> The global aspect of the feature doesn't appear to affect anything.

If you have "Add any..." checked in feed settings then naturally this disables global limit for that feed. Thats the whole goal of that checkbox.

**Comment by RetroAbstract** [comment]
> > > > 
> > > 
> > > 
> > > I see, if you set global limit, how does the setting page of AFFECTED feed looks like?
> > 
> > 
> > If I set the global limit, every feed still has "Add articles with any date to the database" enabled in the feeds' settings.
> > Feeds that have a set date specificially for them through their settings aren't affected in any way by enabling/disabling the feature globally and changing the set date globally.
> > The global aspect of the feature doesn't appear to affect anything.
> 
> If you have "Add any..." checked in feed settings then naturally this disables global limit for that feed. Thats the whole goal of that checkbox.

Yes, but right now "Add any..." is checked for all feeds by default.

Wouldn't it be best if the global aspect of the feature would override individual feeds' settings?

So if all feeds have "Add any.." checked like they have now by default (in `a4818bd32-nowebengine`), if I set a date globally in the app settings that would uncheck "Add any..", check "Avoid adding articles before this date into the database" and apply the newly set date for all feeds?

**Comment by RetroAbstract** [comment]
[Solved](https://github.com/martinrotter/rssguard/issues/1049#issuecomment-1785036361).
