### ISSUE TITLE
[FR]: Specific option: "Auto-fetch all feeds for selected feed categories every: X minute(s) and X second(s)"

### ISSUE THREAD

**Issue by RetroAbstract** [martinrotter/rssguard#684]
### Brief description of the feature request

As the title says, this specific option would allow the user to set RSSGuard to auto-fetch all feeds to selected feed categories every: X minute(s) and X second(s).

This option would have a menu where the user can add & remove feed categories to include in the auto feed fetching of selected categories every: X minute(s) and X second(s).

Would be located in: Tools > Settings > Feeds & Articles > Feed Fetching

**Comment by Rex000** [comment]
+1 from my side

**Comment by RetroAbstract** [comment]
[5d7cb9d](https://github.com/martinrotter/rssguard/commit/5d7cb9dfcdc983b60ea708bacadc1b57676dd244) allows to easily do what's requested in this ticket:

1. Right click the category containing the feeds you want to edit
2. Click "Edit child feeds" or "Edit child feeds (recursive)" depending on the context
3. Enable the "Auto-downloading of articles" setting in the "Articles" tab to edit it
4. Enter the time interval you want the feeds being edited to have for auto-article fetching
5. Click "OK"
6. Done

Every single feed in the category you just edited should now have the auto-article fetching time interval you entered.
