### ISSUE TITLE
[FR]: Toggle to export feeds & categories without custom icons

### ISSUE THREAD

**Issue by RetroAbstract** [martinrotter/rssguard#685]
### Brief description of the feature request

As the title says, this toggle would allow the user to export all or selected feeds & categories without custom icons (icons loaded from file).

Would be located in: Accounts > [Account Name] > Export feeds > "Export feeds & categories without custom icons" (loaded from file) toggle.

**Comment by martinrotter** [comment]
Added as checkbox.

![image](https://user-images.githubusercontent.com/1255302/162583377-8e05b32f-18b9-4a98-94a0-17d43700c584.png)
