### ISSUE TITLE
[BUG]: database gone after updating?

### ISSUE THREAD

**Issue by Owyn** [martinrotter/rssguard#688]
### Brief description of the issue

![image](https://user-images.githubusercontent.com/1309656/162567827-4f6472c4-29f0-4085-a6cd-8e738661acde.png)

### How to reproduce the bug?

Upgrade to a38d3fb9 nowebengine

### What was the expected result?

database stay

### What actually happened?

database gone

### Debug log

[rssguard.zip](https://github.com/martinrotter/rssguard/files/8456710/rssguard.zip)

you changed number of columns huh? and no back-compat?

### Operating system and version

* OS: Win 10
* RSS Guard version: a38d3fb9

**Comment by Owyn** [comment]
same with updating to latest stable build 😢 
[rssguard_stable.zip](https://github.com/martinrotter/rssguard/files/8456723/rssguard_stable.zip)

**Comment by martinrotter** [comment]
devbuild "releases" are not compatible between each other, there is huge warning in devbuild download page

" database: Failed to copy new data to 'main.Categories', error: 'table storage.Categories has 8 columns but 9 values were supplied Unable to execute statement'."

Do not ever use "devbuild" with stable DB data or vice verse and do not ever expect individual devbuild releases to be "upgradable".

Devbuild has one purpose only, test new features/bugfixes etc.

**Comment by Owyn** [comment]
So... what do I do now?

**Comment by martinrotter** [comment]
You read all warnings carefully. That's the first step.

Then go to database.db file, open with Sqlite editor, change "schema_version" value to "1" and try to start Rss guard

**Comment by Owyn** [comment]
nope didn't help

feeds seem to be all there, but all accounts (feed sources) got fast-deleted it seems :-(

**Comment by martinrotter** [comment]
if you share your dtabase.db i could take a look

**Comment by Owyn** [comment]
thank you, I've sent you a gmail

**Comment by martinrotter** [comment]
Checked it, all feeds/categories/acc are gone.

Unrecoverable. Not sure how that happened.

**Comment by Owyn** [comment]
I upgraded from a52d703e -nowebengine to a38d3fb -nowebengine that's all 🤷🏻

**Comment by martinrotter** [comment]
rssguard automatically creates ".bak" file when DB schme is about to be upgraded, do you see .bak file?

**Comment by Owyn** [comment]
it overwrote it shortly after it seems
versioning of bak files would be nice btw
e.g. `data.09_04_2022.bak`
