### ISSUE TITLE
[May not be a BUG]: With a38d3fb9, how do I 'show unread articles only' in article list?

### ISSUE THREAD

**Issue by umbellipher** [martinrotter/rssguard#689]
### Brief description of the issue

The option seems to have vanished from the Articles tab. (Sorry if the solution is an obvious one!)

### How to reproduce the bug?

-

### What was the expected result?

-

### What actually happened?

-

### Debug log

-

### Operating system and version

* OS: Windows 10 pro
* RSS Guard version: a38d3fb9

**Comment by martinrotter** [comment]
See picture from [here](https://github.com/martinrotter/rssguard/pull/678).

You might need to add the button to article toolbar, it is called "Article list filter".
