### ISSUE TITLE
Feature: Size of Preview image from Media RSS feed

### ISSUE THREAD

**Issue by groentebroer** [martinrotter/rssguard#69]
#### Brief description of the issue.

I fully enjoy the added feature that shows the image from Media RSS! (Thanks again for that!)
(See ticket #39)
In my case the images show rather small. I would like them to be (maybe even 4x) bigger.
Would it be wise to have a setting how big this image will display? It would help me a lot!
#### How to reproduce the bug?
1. It is actually not a bug.
#### What is the expected result?

Bigger image from Media RSS.
#### What actually happened?

The image is shown rather small.

**Comment by martinrotter** [comment]
Yes, the size (height, to be more specific) of images is hardcoded to size "36" (pixels). It is not hard to make it configurable.

**Comment by martinrotter** [comment]
Fixed. See latest development builds in Wiki, it will get compiled in 15 minutes. The revision number "653b18f" will be visible in the filename of new dev build.

**Comment by groentebroer** [comment]
Thanks very much!! Will test / use this with the new release!

**Comment by groentebroer** [comment]
Thanks for the confirmation!
I switched to Linux about 8 years ago, so not able to test/confirm anymore ;-).
