### ISSUE TITLE
[FR]: Option to move Articles dropdown to left, leaving search box on extreme right?

### ISSUE THREAD

**Issue by umbellipher** [martinrotter/rssguard#692]
### Brief description of the feature request

% 678901 234 56 789 0123456 789012 34567 890 1234567 89 012 34 5678901 "34567

Graphic explains!
![Screenshot - 10_04_2022 , 14_44_45](https://user-images.githubusercontent.com/59395777/162618794-0f694103-983e-43e7-bc48-bafbfd03f7f8.png)

**Comment by martinrotter** [comment]
I am not sure if I get this, but it seems to be entirely possible. Simply use toolbar editor to re-order your buttons.

![image](https://user-images.githubusercontent.com/1255302/164189354-cf5fab44-1a6a-4c5f-ab15-dec60c0b8f9d.png)

![image](https://user-images.githubusercontent.com/1255302/164189383-847f1533-44b4-4dda-98e7-541938955a05.png)
