### ISSUE TITLE
[FR]: 4 additional options in "Custom skin colours"

### ISSUE THREAD

**Issue by RetroAbstract** [martinrotter/rssguard#694]
### Brief description of the feature request

As title says, these 4 additional options in "Custom skin colours" would allow the user to customize the colour of:

- RSS Guard's background
- Unread articles in article list
- Feeds in feed list
- Feed categories in feed list

Quick visual concept:

![Options](https://user-images.githubusercontent.com/103272301/162989820-b11d7df7-f2c7-432c-97df-88257f00c7d6.jpg)

Would be located in: Tools > Settings > User Interface > Custom skin colours.

**Comment by martinrotter** [comment]
BACKGROUND - what background?
FEEDS - what exactly?
FEED CATEGORIES - what exactly?

**Comment by RetroAbstract** [comment]
> BACKGROUND - what background? FEEDS - what exactly? FEED CATEGORIES - what exactly?

- Background as in the application's background colour (Made up of "Base", "Button" & "Window" elements of an RSS Guard skin metadata file - see screenshots*)
- Feeds as in Feed title colour (Equivalent of "Text" in skin metadata file)
- Feed categories as in Feed category title colour (Also equivalent of "Text" in skin metadata file)

*Skin metadata file elements for "Background" (highlighted in yellow):

1. Base

![Base](https://user-images.githubusercontent.com/103272301/165767378-1f842696-d962-4578-8ef8-b7db73343dd5.jpg)



2. Button

![Button](https://user-images.githubusercontent.com/103272301/165767656-db2475a5-b311-4d6b-bca9-8cff8a7476c0.jpg)



3. Window

![Window](https://user-images.githubusercontent.com/103272301/165767670-3152b9ea-1d56-4f26-9f14-86803a24f4f3.jpg)


### Ultimately the end goal would be, on top of the already customizable files in a skin's folder, to have a "Colors" menu like the one present in QuiteRSS with the same options (excluding those where no visible changes were noticed when tweaking - see list below), allowing the user to fine tune the colours of many elements of RSS Guard directly within the program:

![Colors](https://user-images.githubusercontent.com/103272301/165771007-2e45144d-28e1-4784-974f-4728d861f336.jpg)

Equivalents of QuiteRSS Colors menu elements to RSS Guard:

_Feeds list color_ = **Feed title colour**
_Feeds list background_ = **Feed list base colour**
_News list color_ = **Read articles text colour**
_News list background_ = **Article list base colour**
_Focused news color_ = _No visible changes when tweaking this one_
_Focused news background color_ = _No visible changes when tweaking this one_
_Link color_ = **Link text colour in message viewer/article previewer & internal browser**
_Title color_ = **Article title text colour in article list**
_Date color_ = **Article date text colour in article list**
_Author color_ = **Article author text colour in article list**
_News text color_ = **Message viewer/article previewer & internal browser text colour**
_News title background_ = **Message viewer/article previewer toolbar colour**
_News background_ = **Article previewer & internal browser base colour**
_Feed with new news_ = **Feed title colour with new articles (upon fetching)**
_Count of unread news in feeds tree_ = **Colour of unread news count in feed list**
_Text color of new news_ = **New unread articles text colour (upon fetching)**
_Text color of unread news_ = **Unread articles text colour**
_Focused feed color_ = _No visible changes when tweaking this one_
_Focused feed background color_ = _No visible changes when tweaking this one_
_Disabled feed_ = **Disabled feed text color**
_Alternating row colors_ = **Alternate row colour in article list**
_Notification text color_ = _No equivalent as QuiteRSS uses it's own notification system_
_Notification background color_ = _No equivalent as QuiteRSS uses it's own notification system_

Additionaly, on top of the QuiteRSS "Colors" menu options and the options I originally posted in this FR issue, the following would be great too:

- "Highlight colour" option ("ToolTipText" in skin metadata file)
- "Highlight text colour" option ("HighlightText" in skin metadata file)
- "Button (area) text colour" ("ButtonText" in skin metadata file)
- "Window (area) text colour" ("WindowText" in skin metadata file)
- "Feed with unread articles text colour"
- "Feed category with unread articles text colour"
- "Status bar loading bar colour"

**Comment by RetroAbstract** [comment]
See https://github.com/martinrotter/rssguard/issues/711
