### ISSUE TITLE
[FR]: Option to edit User icon for RSS/ATOM/JSON accounts

### ISSUE THREAD

**Issue by RetroAbstract** [martinrotter/rssguard#695]
### Brief description of the feature request

As title says, this option would allow the user to set a custom icon to their RSS/ATOM/JSON accout by being able to "Load icon from file" like you can already do with feeds & feed categories.

Would be located in: Right Click on [ACCOUNT NAME] (RSS/ATOM/JSON) account in feed list > Edit selected item > Icon > Load icon from file.

**Comment by martinrotter** [comment]
I see.

**Comment by RetroAbstract** [comment]
Thanks :)
