### ISSUE TITLE
[FR]: Network error: unknown error - make it known please

### ISSUE THREAD

**Issue by Owyn** [martinrotter/rssguard#696]
### Brief description of the feature request

Please write exact network error for the reader to see
not just:
![изображение](https://user-images.githubusercontent.com/1309656/163156996-3cedfcb1-567d-43e0-90f5-f8f630cf50fe.png)
but actual error, like:
![изображение](https://user-images.githubusercontent.com/1309656/163157070-dc77121d-7571-445a-9e96-c23b14238296.png)

**Comment by martinrotter** [comment]
Where is this exactly visible

**Comment by Owyn** [comment]
> Where is this exactly visible

in add\edit feed window when fetching, or in main window when a feed turns red and you hover over it with your mouse

**Comment by martinrotter** [comment]
Can you provide the exact URL/script with which to test? That window should report pretty accurate errors.

Thanks.

**Comment by Owyn** [comment]
Well, 503 is a temporary error, site which had it already finished its maintenance so I can't...

**Comment by martinrotter** [comment]
should be fixed
