### ISSUE TITLE
[BUG]: dev nowebengine images white

### ISSUE THREAD

**Issue by Owyn** [martinrotter/rssguard#697]
### Brief description of the issue

![image](https://user-images.githubusercontent.com/1309656/164205541-c8df85c6-6419-4b74-95df-a94acda717ae.png)
![image](https://user-images.githubusercontent.com/1309656/164205558-1e7d264c-2b7e-4499-9e12-0c2e6e77abec.png)

even after reloading image (why do I have to press that btw? can you make it auto-press it?)

### How to reproduce the bug?

example feed: 
url: `https://reaperscans.com/home1/`
scrapper: `python css2rss.py "@div.manga" ".post-title" "img" ".btn-link" ".btn-link"`

same with png and jpg images, 

but I've found one feed where top few jpg images are shown fine: `https://flamescans.org/feed`

### What was the expected result?

images shown (automatically when I open the feed)

### What actually happened?

images not shown even after I press reload

### Debug log

do my feed images show fine for you?

### Operating system and version

* OS: Win10
* RSS Guard version: dev a0

Did i try testing this too early?

also, the limit of image height doesn't seem to work:
![image](https://user-images.githubusercontent.com/1309656/164212077-6bb1b42d-8b84-404e-aef3-391eac2f35dc.png)

**Comment by martinrotter** [comment]
> also, the limit of image height doesn't seem to work:

Some related features are now semi broken, but overally images should show.

I will test.

**Comment by martinrotter** [comment]
Found the problem.

* Please define somewhere in readme of css2rss tool what version of Python is supported.
* Your post-processing logic generates messages with this sample content layout:

`
<img alt="TTITH" class="img-responsive lazyload effect-fade" data-sizes="(max-width: 720px) 100vw, 720px" data-src="https://reaperscans.com/wp-content/uploads/2021/10/TTITH.png" data-srcset="https://reaperscans.com/wp-content/uploads/2021/10/TTITH.png 720w, https://reaperscans.com/wp-content/uploads/2021/10/TTITH-110x150.png 110w" height="972" src="https://reaperscans.com/wp-content/themes/madara/images/dflazy.jpg" style="padding-top:972px;" width="720"/>`

Key here is that the `img` tag has attribute `src="https://reaperscans.com/wp-content/themes/madara/images/dflazy.jpg"` and https://reaperscans.com/wp-content/themes/madara/images/dflazy.jpg is only placeholder "empty" image to be replaced by lazy-loaded image with JavaScript.

NonWebEngine component is not able to recognize this and when you "reload with images" it blindly loads https://reaperscans.com/wp-content/themes/madara/images/dflazy.jpg

You probably noticed that RSS Guard also "parses" the contents and generates list of found images below the message. Generated list of messages is more "functional" because of some luck and bit better regular expression used to find those "*src" links.

Therefore I would recommend that your post-process script should output really static contents of articles -> get rid of "lazy" "src" attribute and perhaps replace it with "data-src" attribute (rename to "src") which points to the actual image.

![image](https://user-images.githubusercontent.com/1255302/164393609-c2034f4c-a42f-41d1-9d9b-a2f45964d958.png)

**Comment by martinrotter** [comment]
Wait, I will try to replace all "img" tags with fixups automagically.

**Comment by martinrotter** [comment]
OK, I made a fix:

* image attachment size is now respected and when set to 0 or -1 it respects original image size
* faulty "img" tags are replaced with more correct ones and also all images are now clickable as hyperlinks

**Comment by Owyn** [comment]
> Therefore I would recommend that your post-process script should output really static contents of articles -> get rid of "lazy" "src" attribute and perhaps replace it with "data-src" attribute (rename to "src") which points to the actual image.

A good place to fix img attributes would be rssguard 😊 
since scrappers only scrap websites and don't really control their contents

`https://flamescans.org/feed` now shows all images fine and image height limit also works but this feed kinda very laggy when scrolling down and eats up all cpu

and this one:
url: `https://reaperscans.com/home1/`
script: `python css2rss.py "@div.manga" ".post-title" "img" ".btn-link" ".btn-link"`

some images show while others don't,
e.g: https://reaperscans.com/wp-content/uploads/2021/07/%C2%B3a%C2%B3e%C2%B8%C2%B6%C2%BDA_%C2%BDA%C2%B8%C2%AEAi_C%C2%A5Ao1000x1500_JPG-175x238.jpg 

![image](https://user-images.githubusercontent.com/1309656/164428667-eb279843-db53-4b44-af2a-4c8911252b71.png)

and: https://reaperscans.com/wp-content/uploads/2022/01/lvl1-175x238.png 
![image](https://user-images.githubusercontent.com/1309656/164428743-1b7ea9a8-b4dc-40d6-a833-771635c25d09.png)

btw, when can we have auto-reload with images when opening the feed item so we don't have to click it manually?

P.s. - the option "limit height of images" isn't the "limit" but also the "minimal height" not just the maximum one

**Comment by martinrotter** [comment]
> since scrappers only scrap websites and don't really control their contents

Scrapers must deliver valid feed data, that is what is written in documentation. I will look into it and possibly "fix" from RSS Guard side, but if you deliver BAD "src" attribute, you cannot possibly expect it to show without problems, can you?

Also, those pictures you linked do not work, show some HTTP errors even in my Firefox.

**Comment by martinrotter** [comment]
Also, the problematic URL of one of those images is

https://reaperscans.com/wp-content/uploads/2021/07/³a³e¸¶½A_½A¸®Ai_C¥Ao1000x1500_JPG-175x238.jpg

Clearly broken somehow.

**Comment by Owyn** [comment]
> Also, those pictures you linked do not work, show some HTTP errors even in my Firefox.

Both show fine in my stable Firefox 99 🤔

**Comment by Owyn** [comment]
> Clearly broken somehow.

Just unicode characters in the url, totally up to http specification, no? 


also, it seems that "reload with images" doesn't always work, so I have to press it twice or more for image to load, I thought image was totally broken but after clicking "reload" multiple times it loaded:
![image](https://user-images.githubusercontent.com/1309656/164448381-e4884741-41c5-4b82-a809-4f2330b8f5e1.png)

would be nice to fix it, or make auto-retry for image-loading maybe

**Comment by martinrotter** [comment]
I will very likely work on the component to not require pushing "Reload...." button, but will make that button checkable "Load remote images" and persistent.

There is some technical trickery behind all this. The  whole feature is more tricky to implement than one might think. :)

**Comment by Owyn** [comment]
> Scrapers must deliver valid feed data, that is what is written in documentation.

RSSGuard version with full webengine supports data-src tho so it's valid there, right? 

Anyway, thx for the fix, I appreciate it. Now it seems to work fine and use `data-src` first

**Comment by Owyn** [comment]
There seems to be a problem with displaying images with relative URLs, even thought clicking them works fine:
![image](https://user-images.githubusercontent.com/1309656/164719902-f0964471-cab4-45e1-9b91-20a9feebbd13.png)
![image](https://user-images.githubusercontent.com/1309656/164720080-070c1c3c-3e1c-4527-bba6-59d4e7b0bdd8.png)


`http://rublacklist.net/feed/`

**Comment by martinrotter** [comment]
Just commited a fix, wait for it to build and plst test.

**Comment by Owyn** [comment]
It works now
![image](https://user-images.githubusercontent.com/1309656/164724347-061d692d-3eb8-46f5-a90f-171a066fd2c6.png)

btw, thought resolve_url function might help with unicode urls, but still no
![image](https://user-images.githubusercontent.com/1309656/164724578-b38ee43b-81ad-4f32-81c5-bccb116ee82f.png)

**Comment by Owyn** [comment]
if you change the feed while images in previous feed are still loading - it will crash, I think

**Comment by martinrotter** [comment]
That is entirely possible at this point.

**Comment by Owyn** [comment]
> Just commited a fix, wait for it to build and plst test.

Suddenly relative image urls don't work again.

Revision: https://github.com/martinrotter/rssguard/commit/871c92c1b6734753812ce317c0f51a09071e0cae-nowebengine

![image](https://user-images.githubusercontent.com/1309656/166714673-5579e8bb-7d37-4386-9fba-2c435fd4900a.png)
![image](https://user-images.githubusercontent.com/1309656/166714811-c4da931d-5780-45d1-8faf-450c6284fe6c.png)

feed url: `http://rublacklist.net/feed/`

**Comment by martinrotter** [comment]
Let me check.

**Comment by martinrotter** [comment]
521eb9293

Pls check if working.

**Comment by martinrotter** [comment]
827190c1d

Pls test. Problem was with URL encoding.

**Comment by Owyn** [comment]
Now it works, thanks :)

maybe while you're at it - you could also make fetching images user feed url as the referrer? cuz some images need it to load, else "access denied" (it seems)

example: 
url: `https://manhuaus.com/?s=Wo+Wei+Xie+Di&post_type=wp-manga&post_type=wp-manga`
script: `python css2rss.py ".c-tabs-item__content" "!I'm an Evil God" ".c-image-hover img" ".latest-chap a"`

![image](https://user-images.githubusercontent.com/1309656/167157641-e0236401-3602-4d45-a39c-85255e2c5db0.png)
