### ISSUE TITLE
[BUG]: Articles images can’t be loaded in RSS Guard.

### ISSUE THREAD

**Issue by guillaumesoucy94** [martinrotter/rssguard#703]
### Brief description of the issue

Hello, 

I’m able to load articles from my FreshRSS server but images in articles can’t be loader inline. 

I look on this GitHub, I’d find post with the same issues. If I understood correctly, I need to get “M RSS”, where to get it?

I’m a bit confuse.

Regards, 

Guillaume

### How to reproduce the bug?

1. Open RSSGuard.
2. Open an article. 
3. The images are not displayed. Only the link to it.
![Screenshot at 2022-04-26 04-28-12](https://user-images.githubusercontent.com/22561876/165256975-36673e08-ae42-4b4a-822b-7460f04226a9.png)

### What was the expected result?

To have the images displayed inline. 

### What actually happened?

The images are not displayed, only the links to them. 
![Screenshot at 2022-04-26 04-28-12](https://user-images.githubusercontent.com/22561876/165257153-54adf975-6093-4074-8e55-c34f81bc0412.png)

### Debug log

The instructions here: https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#reprt seem to be for Windows OS, I'm using Linux. How to obtain the debug logs for Linux?

### Operating system and version

* OS: Linux Mint 20.3 Una
* RSS Guard version: 4.2.1

**Comment by martinrotter** [comment]
Try latest dev. build and see below.

![image](https://user-images.githubusercontent.com/1255302/165621312-c8720749-9422-4234-be74-086711279112.png)
