### ISSUE TITLE
[BUG]: Toggle between tray icon and maximised window Pop_OS 22.04 (GNOME Shell 42)

### ISSUE THREAD

**Issue by cement-head** [martinrotter/rssguard#710]
### Brief description of the issue

Double clicking tray icon should maximise window.  In GNOME Shell 42 this does not happen.  It was working in GNOME Shell 40 (Pop_OS 20.04 LTS).

### How to reproduce the bug?

1) Install Pop_OS 22.04 LTS with GNOME Shell 42
2) Install RSSGuard 4.2.1 via Flatpak
3) Double click minimised to trayicon, icon -> NO maximisation occurs

### What was the expected result?

Maximised window

### What actually happened?

Nothing; this **could** be a Gnome Shell 42 Ubuntu Appindicators bug...

### Debug log

N/A

### Operating system and version

* OS: Pop_OS 22.04 LTS
* RSS Guard version: 4.2.1 NoWebEngine

**Comment by martinrotter** [comment]
Did you test **same** RSS Guard version on both Gnome Shell 40 and 42?

If you did then this is clearly gnome regression and not the first one.

**Comment by martinrotter** [comment]
Also, see this: https://github.com/martinrotter/rssguard/issues/679

**Comment by cement-head** [comment]
CRAP!
