### ISSUE TITLE
[BUG]: Launching with -w still spawns QtWebEngineProcess / node

### ISSUE THREAD

**Issue by guihkx** [martinrotter/rssguard#713]
### Brief description of the issue

I'm not sure if I'm misunderstanding something, but I figured the `-w` launch option would prevent `QtWebEngineProcess` and `node` processes from being launched, but that doesn't seem the case on Linux:

![image](https://user-images.githubusercontent.com/626206/165959886-1d54cfc8-504d-4db4-b551-31e0eb75fa7c.png)

Additionally, if you launch RSS Guard for the first time with `-w`, you can still install the Adblock, which IMO doesn't make sense because the Adblock feature relies on QWebEngine to work.

### How to reproduce the bug?

1. Run `rssguard -w`
2. Open your OS' task manager
3. Find `rssguard` and notice children `QtWebEngineProcess` processes

You'll also get `node` processes if you had enabled the Adblock feature previously.

### What was the expected result?

No node/QtWebEngineProcess processes?

### What actually happened?

Processes for `node` and `QtWebEngineProcess` are spawned, however RSS Guard doesn't appear to use it in the reading panel itself:

![image](https://user-images.githubusercontent.com/626206/165960375-2826aa04-47cf-4bcf-9a3e-06a0b364fd58.png)

### Debug log

[rssguard.log](https://github.com/martinrotter/rssguard/files/8591340/rssguard.log)

### Operating system and version

* OS: Arch Linux
* RSS Guard version: 4.2.2 (AppImage)

**Comment by martinrotter** [comment]
Well, technically AdBlock does not QtWebEngine functionality at all and even NonWebEngine article viewer can load remote resources (pictures, CSS, etc.) so at this point AdBlock really can be used with "-w" (nowebengine) as well!

I plan to finalize that "remote resources" feature which will not load just pictures, but CSS style too. In that case AdBlock might be of use.

Of course, AdBlock is opt-in feature, therefore "node" does not really have to be running at all.

As for "qtwebengine", yes, that is possible "problem" and I will check where it is used (i have some idea and will try to fix).

**Comment by martinrotter** [comment]
Btw, is this related only to AppImage build?

**Comment by guihkx** [comment]
No, I only used AppImage for easier reproduction. I actually found this out while using the Flatpak build.

**Comment by martinrotter** [comment]
I just did testing on Windows and do not see any QtWebEngine binaries forked from "rssguard" binary. Will check on Linux tonight.

**Comment by guihkx** [comment]
No need to be sorry, I completely understand. Thank you for looking into this anyway!
