### ISSUE TITLE
[FR]: Hide image URLs in articles when loading images in message viewer/article previewer (No Web Engine version)

### ISSUE THREAD

**Issue by RetroAbstract** [martinrotter/rssguard#714]
### Brief description of the feature request

Since the release of 4.2.2 adding image loading in articles for No Web Engine versions, this option would allow the user to hide the image URLs of images that are loaded directly in the message viewer/article previewer for the No Web Engine version of RSS Guard.

**Comment by inson1** [comment]
+1
