### ISSUE TITLE
[BUG]: Missing option to hide read items in articles list

### ISSUE THREAD

**Issue by quickwick** [martinrotter/rssguard#715]
### Brief description of the issue

I just updated to v 4.2.2, and the option to control display of already read items in articles list is gone. I tried adding the 'Show unread items only' button back to the 'Toolbar for articles list', but it changes the display of the feed list, not the articles list.

### How to reproduce the bug?

1. Open RSS Guard
2. Select feed
3. The articles list shows both read and unread items
4. Open the 'Articles' menu. There is no option to 'Show unread items only'

### What was the expected result?

There should be an option to 'Show unread items only' for the Articles list

### What actually happened?

There is no option to 'Show unread items only'

### Debug log

I fail to see how a debug log will help with this. I will happily provide if it's actually useful.

### Operating system and version

* OS: Windows 10 21H2 (19044.1682)
* RSS Guard version: 4.2.2

**Comment by martinrotter** [comment]
https://github.com/martinrotter/rssguard/pull/678

Also citing changelog:

> Article list filtering button is now greatly enhanced. Go to "Settings -> User interface -> Toolbars -> Toolbar for article list" and add "Article list filter" button to the toolbar.

In other words, filtering was enhanced, add relevant button to your article list toolbar and profit.

**Comment by quickwick** [comment]
Thank you.

It would have been appreciated if that "Article list filter" button could have been added automatically to the articles list toolbar, in place of the button that was removed.
