### ISSUE TITLE
[BUG]: Some feeds can cause RSS Guard to write to `config.ini` way too many times

### ISSUE THREAD

**Issue by guihkx** [martinrotter/rssguard#716]
### Brief description of the issue

A single Reddit feed can cause RSS Guard to write 50 KB (or more) to disk on each fetch operation. It may not look like much, but this becomes a real issue when you have multiple Reddit feeds with a short update interval.

I started investigating this after noticing that the `rssguard` process on GNOME's System Monitor had written 8 GB of data to disk in less than 24 hours running.

After trying RSS Guard's on-RAM database feature and not seeing any improvements, I investigated this further and discovered all this data was actually being written to just `config.ini`!

### How to reproduce the bug?

Assuming you're running RSS Guard for the first time (and on Linux):

1. Import this Reddit feed: `https://old.reddit.com/r/worldnews/new/.rss`
2. (Optional) Fetch the feed for the first time, just to populate the list
3. Open a terminal window and begin monitoring RSS Guard's `config` directory using `inotifywait`:
    ```
    inotifywait --timefmt '%F %T' --format '%T %w %e %f' -e move -m -r ~/.config/RSS\ Guard\ 4/
    ```
4. Go back to RSS Guard, fetch the Reddit feed once more
5. Go back to the terminal and notice a bunch of write and move operations just on a single fetch:
    ```
    2022-05-01 13:17:53 /home/gui/.config/RSS Guard 4/config/ MOVED_FROM config.ini.stGfSC
    2022-05-01 13:17:53 /home/gui/.config/RSS Guard 4/config/ MOVED_TO config.ini
    2022-05-01 13:17:53 /home/gui/.config/RSS Guard 4/config/ MOVED_FROM config.ini.geqYaH
    2022-05-01 13:17:53 /home/gui/.config/RSS Guard 4/config/ MOVED_TO config.ini
    2022-05-01 13:17:53 /home/gui/.config/RSS Guard 4/config/ MOVED_FROM config.ini.xCrjVH
    2022-05-01 13:17:53 /home/gui/.config/RSS Guard 4/config/ MOVED_TO config.ini
    2022-05-01 13:17:53 /home/gui/.config/RSS Guard 4/config/ MOVED_FROM config.ini.OOvEEW
    2022-05-01 13:17:53 /home/gui/.config/RSS Guard 4/config/ MOVED_TO config.ini
    ```

### What was the expected result?

RSS Guard could greatly reduce write operations `config.ini`.

### What actually happened?

RSS Guard writes many times to `config.ini` unnecessarily:

https://user-images.githubusercontent.com/626206/166155626-a16013a1-b41c-423d-926a-a368a4a2dec0.mp4

### Debug log

- [rssguard.log](https://github.com/martinrotter/rssguard/files/8599331/rssguard.log)

### Operating system and version

* OS: Arch Linux
* RSS Guard version: 4.2.2 (AppImage)

**Comment by martinrotter** [comment]
Weird, that happens only with that specific feed?

**Comment by guihkx** [comment]
I have about 40 feeds in total. I tried fetching every single one of them, but I could only reproduce this issue on my 3 Reddit feeds.

This leads me to believe it's something related to cookies, because Reddit seems to be the only one sending them:

```
$ curl -sc- https://old.reddit.com/r/worldnews/new/.rss -o /dev/null
# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

.reddit.com     TRUE    /       TRUE    1714501196      edgebucket      pSEnhjcUgHrYz6exjS
.reddit.com     TRUE    /       TRUE    1714501197      csv     2
.reddit.com     TRUE    /       TRUE    1651436396      session_tracker MMyIGBtOo5JXNVeLPZ.0.1651429197511.Z0FBQUFBQmliczlOdFUxX1BpYlluUlJXMWwza3Fkd1Y2SV9nd2x3a3REeVNyaWxzZnhoYTZKbmNFYzVqdjBYalpYbmxsQnBwZHdNQXBpOHE1WGxDTkJlRnFlMEZnRV9CU0gwREFYcy1mZ1V3eE9QQzlqZkpFUXlWZTlucVFodUpYSG5RUHVKb3JSYUg
```

My RSS Guard `config.ini` has a `[cookies]` section, which I don't understand why because I'm running the nowebengine build 🤔 

```ini
[categories_expand_states]
1-16--1=true

[cookies]
1-csv="AwVVJYUh1bvARkeN2cgKRxvcCOohoo/9kI+lT9/3mMQaMPg8XnN/I2M2+T0/8ZgiYzZhRQJIROPf8Lz+wY7nRx8yeNjDkOUifVeaOkBwQcSkCib8f9PfYcBsw3p6VFznpmhZBYBWQRs+Db6cA2cmpEJF+A=="
2-edgebucket="AwXHKNdu+fGvKvDHwtk4syrvm3txuxxuAxwO5HRcUGtJG0uUED1Rkoqf7Q9rOFFW9xlu8/SeLdeImFWR897Sjs6bVJCSXDWPzpvM6K/l6U5yXRFTbCNK6rKf1XVuPUiP0Po3l+3b6m8PoY1X1Hh0ymvHaNHR//dMDcPyriv96rCVphU3qMyNA0t1Lg=="
3-session_tracker=AwVis7DzQM3r6XlXphl+DJr8AfBGUon7lojLIbHfXfT3aiCq4GN15oqzognbmTnN5dru5e8tpBskw1KAAEIuRs449Uj7jJpCtG2IX6dixGRauRmfIsZO/8CeZZyThWDxMaP0pVvpfk6FxB9NSNlnlhOWjT7Yr739EoGqEotAK+bCxuK2nDW2m+0I90EOEYU1DwUK9tVn4OOKsxQhpJsaEtsPL0mTINNMyv0ihQ0JXuGxodnQEokEGLAEOlmGbG/77d5952qtGM38LyYhzChRU4y3iuCYr7mT8f2cJKRu3GZxLnBiT58cCfndmSpJENhu1t3ItGy07+JBw10FhAmrQqlG2oyY4KLJIrv+GsYYGjNzUDv+Nz0cszbAKLmHb/DOIJQj3f4gltuhvK5v

[feeds]
show_tree_branches=true

[gui]
default_sort_column_feeds=0
default_sort_order_feeds=0
enable_list_headers=true
enable_status_bar=true
enable_toolbars=true
is_window_maximized_before_fullscreen=true
main_menu_visible=true
msg_view_state=AAAAEgAAAAEAAAAAAAAAAAAAAAABAAAAAQAAAB4AAAAAAgAAABgAAAAAAwAAAAABAAAABAAAAAABAAAABQAAAAABAAAABgAAAUYAAAAABwAAAAABAAAACAAAAGQAAAAACQAAAGQAAAAACgAAAAABAAAACwAAAAABAAAADAAAAAABAAAADQAAAAABAAAADgAAAAABAAAADwAAAAABAAAAEAAAAAABAAAAEQAAAAAB
splitter_feeds=309, 982
splitter_messages_vertical=408, 0
start_in_fullscreen=false
window_is_maximized=true
window_position=@Point(128 88)
window_size=@Size(768 518)

[main]
first_run=false
first_run_4.2.2=false

[messages]
enable_message_preview=true

[notifications]
1=1, , 50
2=1, :/sounds/notify.wav, 50
5=1, , 50
6=1, , 50
7=1, , 50
8=1, , 50
```

**Comment by martinrotter** [comment]
@guihkx Just checked. Yes. RSS Guard processes cookies sent from remote servers with their HTTP responses.

Reddit server uses cookies HEAVILY and sends a lot of them when responding with RSS feed data.

At this point, there is no cookies management in RSS Guard - it just accepts and stores all cookies, no matter if webengine build or not.

This could be expanded, I agree.

Maybe a general on/off switch in settings `Ignore all cookies` would do the job?

**Comment by guihkx** [comment]
Sounds perfect to me.

**Comment by guihkx** [comment]
It could be turned on by default too, I guess?

**Comment by martinrotter** [comment]
> It could be turned on by default too, I guess?

No, I must keep backwards compatibility, including behavior.

**Comment by martinrotter** [comment]
d9a651490

![image](https://user-images.githubusercontent.com/1255302/166224885-5ecccee7-906c-406d-a2bb-205159a80525.png)

**Comment by martinrotter** [comment]
Test and report back pls.

**Comment by guihkx** [comment]
Just tested it. It works, thanks!

**Comment by meelten** [comment]
> [d9a6514](https://github.com/martinrotter/rssguard/commit/d9a651490aea6b8f21e4fe182f92686e29e9cbf7)
> 
> 

Hey, maybe while you are at it, add also switch to disable disk cache? QtWebengine allows for that I think and I don't see any downsides as I run RSS Guard with read-only cache folder for long time now.

**Comment by martinrotter** [comment]
Yes, it is possible. https://doc.qt.io/qt-5/qwebengineprofile.html#setHttpCacheType

**Comment by martinrotter** [comment]
@meelten Pls create separate ticket for that. Thanks.
