### ISSUE TITLE
[FR]: Compile flag to disable update checking altogether

### ISSUE THREAD

**Issue by guihkx** [martinrotter/rssguard#717]
### Brief description of the feature request

Traditionally, Linux apps have a compile flag to disable checking for updates, because that doesn't make sense when your app is installed using your distribution's official repositories.

**Comment by martinrotter** [comment]
Added, use like any other "cmake" switches.

e6536a172

**Comment by guihkx** [comment]
I'm not sure if this is on purpose, but we can still check for updates under **Help** > **Check for updates**:

![image](https://user-images.githubusercontent.com/626206/166253218-fdfcd7b0-11f1-4ca3-8749-fa3238b54462.png)
