### ISSUE TITLE
[FR]: The autostart feature doesn't work on the Flatpak build

### ISSUE THREAD

**Issue by guihkx** [martinrotter/rssguard#718]
### Brief description of the feature request

Due to the sandbox nature of Flatpak apps, the option to "Launch RSS Guard on operating system startup" currently doesn't work for two main reasons:

1. The Flatpak build doesn't have access to `~/.config/autostart` because it lacks this manifest permission: `--filesystem=xdg-config/autostart`.
  <br>So, RSS Guard ends up writing to `~/.var/app/com.github.rssguard/config/autostart` instead, which isn't a valid path recognized by the desktop environment to auto-launch programs.<br><br>
2. But even if we added the Flatpak permission above, RSS Guard would still create an invalid `.desktop` file under `~/.config/autostart`:<br><br>
    ```ini
    [Desktop Entry]
    Version=1.0
    Type=Application
    Terminal=false
    Name=RSS Guard
    TryExec=rssguard
    Exec=rssguard
    Hidden=false
    X-GNOME-Autostart-Delay=15
    X-LXQt-Need-Tray=true
    ```

This is invalid because Flatpak apps don't expose the main binary of a program in the `$PATH` variable, so when the desktop environment tries to search for the `rssguard` binary under the directories of `$PATH`, it doesn't find anything.

I see two approaches to this issue:

1. Disable the autostart option for Flatpak apps completely (not ideal, I think).
2. Add the missing manifest permission and then add Flatpak-specific code to create a valid `.desktop` file by modifying the `TryExec=` and `Exec=` to something like this:<br><br>
    ```ini
    ...
    TryExec=flatpak
    Exec=flatpak run com.github.rssguard
    ...
    ```

Now, to actually detect if we're running RSS Guard under a Flatpak environment, most apps seem to just detect if a file named `.flatpak-info` is present on the root directory (`/`). Here's some pseudo-code:

```cpp
bool is_flatpak = false;

if (file_exists("/.flatpak-info")) {
    is_flatpak = true;
}
if (is_flatpak) {
    change_desktop_file("TryExec=flatpak");
    change_desktop_file("Exec=flatpak run com.github.rssguard");
}
```

This doesn't seem to be document anywhere, but [this GNOME library](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1573) (and many others) seems to make use of it, so it must be reliable.

Please share your thoughts.

Thank you.

**Comment by martinrotter** [comment]
Well. That is one way.

Other way could be yet another cmake build option, something like `FLATPAK_BUILD` and use that in compile time. You would then set `DFLATPAK_BUILD=ON` and that would be it.

**Comment by guihkx** [comment]
Sure! Whatever option you think it's best for you.

**Comment by martinrotter** [comment]
4ddee5d

Option is `IS_FLATPAK_BUILD`

**Comment by guihkx** [comment]
Thanks for the quick implementation, however the `TryExec` key has an invalid value. The spec says:

>TryExec:  Path to an executable file on disk used to determine if the program is actually installed. If the path is not an absolute path, the file is looked up in the $PATH environment variable. If the file is not present or if it is not executable, the entry may be ignored (not be used in menus, for example). 

[Source](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#:~:text=NO-,tryexec,-Path%20to%20an)

So you can either use:

```ini
TryExec=flatpak
Exec=flatpak run com.github.rssguard
```

or

```ini
TryExec=com.github.rssguard
Exec=com.github.rssguard
```

However for the latter option to work,  the display manager must have sourced `/etc/profile.d/flatpak.sh` so that the `com.github.rssguard` script is added to `PATH` variable, i.e. the opposite of your [recent experience](https://github.com/flathub/com.github.rssguard/pull/25#issuecomment-1114305474) with Flatpak. 😄

**Comment by martinrotter** [comment]
@guihkx Yes.

I just got an interesting idea. I have of course access to `argv` which includes "exec" line of running RSS Guard instance. So I can use those live information instead of hardcoded stuff. Also, I could append all currently used CLI parameters to the `.desktop` file too.

Let me implement this tonight when I will have time on my Linux machine.

**Comment by martinrotter** [comment]
@guihkx I tried to blind fix, not tested at all. It should generate `desktop` file not with hard-coded constants but with values taken from `argv`. So if user executed it as `flatpak com..... --arg --arg` then "flatpak" should appear in "TryExec" and whole line in "Exec".

6bde01321

**Comment by guihkx** [comment]
Didn't work unfortunately:

https://user-images.githubusercontent.com/626206/166682712-a7bef97a-c2d6-4e0e-a2fb-5705bb582c18.mp4

**Comment by guihkx** [comment]
>Thing is, what if someone launches with for example --user flag? flatpak --user com...... that is broken too right?

Good question actually, unfortunately I install all my Flatpak apps system-wide so I won't be able to test this

**Comment by martinrotter** [comment]
Is your testing build launched as rotational?

**Comment by guihkx** [comment]
Not sure I understand the question correctly, but yes, in the video I ran RSS Guard by running this in the terminal:

```
flatpak run com.github.rssguard --no-web-engine
```

**Comment by martinrotter** [comment]
I see.

**Comment by martinrotter** [comment]
How flatpak works? What is the name of actualy binary that gets launched when flatpaked app is launched?

**Comment by martinrotter** [comment]
Yes, that is the problem. I see. I will fix tonight.

**Comment by martinrotter** [comment]
blind fix: e153a1fac

make sure to have that `IS_FLATPAK_BUILD` flag set

this should use hardcoded "flatpak com.github..." + add all used CLI flags behind it for "Exec" line

**Comment by martinrotter** [comment]
sure thanks, it is pretty straightforward

https://github.com/martinrotter/rssguard/commit/e153a1facafb284da1fd4851122d280c079a2edb#diff-4835a22bc4a5315dda9e332772945bf55afca3145c68fc6329cef1c89d2d5620R191

**Comment by guihkx** [comment]
RSS created this desktop file:

```ini
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Name=RSS Guard
TryExec=flatpak run com.github.rssguard
Exec=-w
Hidden=false
X-GNOME-Autostart-Delay=15
X-LXQt-Need-Tray=true
```

**Comment by martinrotter** [comment]
Yes, like I said, blind fix. Will fix properly tonight, sorry for wasting our time. I am an idiot.

**Comment by martinrotter** [comment]
OK, now generates:

```
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Name=RSS Guard
TryExec=flatpak run com.github.rssguard
Exec=flatpak run com.github.rssguard -w
Hidden=false
X-GNOME-Autostart-Delay=15
X-LXQt-Need-Tray=true
```
15d529a

Pls test and report back.

**Comment by guihkx** [comment]
I haven't tested yet, bu judging from the generated desktop file, it won't work. The `TryExec` property must contain the name of the binary to be searched, not the full command to launch the program.

When the desktop environment sees `TryExec=flatpak run com.github.rssguard`, it will iterate over the directories set in `$PATH` and search for that whole string inside `TryExec`. Example:

Assuming your `$PATH` variable has this value: `/usr/local/bin:/usr/bin:/usr/local/sbin`

The desktop environment will try to find this *exact* binary:

- `/usr/local/bin/flatpak run com.github.rssguard`
- `/usr/bin/flatpak run com.github.rssguard`
- `/usr/sbin/flatpak run com.github.rssguard`

Because none of those paths exist, the desktop environment will not autostart RSS Guard.

If you *really* want to use the `TryExec` property (you don't have to), you could either set it to just `flatpak` or `com.github.rssguard`, but the latter assumes the user has  the`$XDG_DATA_DIRS` variable properly configured for Flatpak.

**Comment by martinrotter** [comment]
ok will remove TryExec

**Comment by martinrotter** [comment]
d1b904d

I just have a bad day, sorry.

**Comment by guihkx** [comment]
No need to apologize ever! Just tested, it works great now:

```ini
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Name=RSS Guard
Exec=flatpak run com.github.rssguard --no-web-engine
Hidden=false
X-GNOME-Autostart-Delay=15
X-LXQt-Need-Tray=true
```

Thank you very much!
