### ISSUE TITLE
[FR]: Feed management for FreshRSS 

### ISSUE THREAD

**Issue by karmicdude** [martinrotter/rssguard#719]
### Brief description of the feature request

Background: I'm looking for a convenient multidevice RSS sync option with user-friendly clients (MacOS / Linux / Android). After considering different options, I chose FreshRSS as a server. There are a huge number of clients for android that have good two-way synchronization with FreshRSS. On macOS, Reeder5 does it well. 
By two-way synchronization I mean the ability to manage feeds on the client side: adding, deleting, editing, grouping and etc. 
Although the RSS Guard documentation announces the possibility of two-way synchronization for FreshRSS, it doesn't work or I just do not understand what is meant by it then.
When I try to add a feed or category on the RSS Guard side I get the message:  `Not supported by account - Selected account does not support adding of new categories / new feeds`.
The account connected through `Google Reader API` and FreshRSS selected as Service. 
Is it possible to add the ability to manage feeds? Or point out a possible misconfiguration on my side.

**Comment by martinrotter** [comment]
Yes, that would benefit other services with greader api too.

**Comment by martinrotter** [comment]
added opml export/import, will add rest soon

**Comment by martinrotter** [comment]
added feed adding/editing/deleting too
