### ISSUE TITLE
[BUG]: Minimalize Windows - doesn't work, AdBlock - doesn't work

### ISSUE THREAD

**Issue by PrzemekRyk** [martinrotter/rssguard#720]
### Brief description of the issue

What I have done:

1. I've exported my settings and database from version 4.1.2
2. I've upgraded RSS Guard to version 4.2.2
3. I've tried to enable AdBlock (node.js installed)
4. I've tried to minimize program window

Adblock doesn't work - message, that I need to configure this feature. Minimizing program window doesn't work - RSS Guard comes back in full size.

I've installed RSS Guard and node.js on virtual machine, imported my settings and database. Result is the same.
[RSS Guard.zip](https://github.com/martinrotter/rssguard/files/8619363/RSS.Guard.zip)

RSS Guard.zip - settings file and database file

### How to reproduce the bug?

1. Install RSS Guard 4.2.2
2. Install node.js (I've used version 18.0.0)
3. Restore my settings and database file
4. Restart RSS Guard
5. Try to enable AdBlock
6. Try to minimize program window using minimize button

### What was the expected result?

Two results I expect:

1. working Adblock
2. ability to minimalize program window to tray

### What actually happened?

1. AdBlock is disabled
2. program window doesn't minimize - it is restored back to its original size

### Debug log

time="     0.094" type="debug" -> core: Initializing settings in 'C:\RSS Guard\data4\config\config.ini' (portable way).
time="     0.364" type="warning" -> database: SQLite database is not initialized. Initializing now.
time="     0.366" type="debug" -> database: SQLite database backend should be ready now.
time="     0.368" type="debug" -> database: File-based SQLite database connection '' to file 'C:\RSS Guard\data4\database\database.db' seems to be established.
time="     0.369" type="debug" -> database: File-based SQLite database has version '2'.
time="     0.426" type="debug" -> database: Copying data from file-based database into working in-memory database.
time="     0.428" type="debug" -> gui: Available icon theme paths: (:/icons, :/graphics, C:/RSS Guard\data4\icons, C:/RSS Guard\icons)
time="     0.430" type="debug" -> gui: Installed icon themes are: '', 'Breeze', 'Breeze Dark', 'Faenza', 'Numix'
time="     0.430" type="debug" -> gui: Loading icon theme 'Faenza'.
time="     0.431" type="debug" -> gui: Found path of base skin: ':\skins\nudus-base'.
time="     0.431" type="debug" -> gui: Local file ':\skins\nudus-dark\html_wrapper.html' exists, using it for the skin.
time="     0.431" type="debug" -> gui: Local file ':\skins\nudus-dark\html_style.css' exists, using it for the skin.
time="     0.432" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_enclosure_image.html' for the skin.
time="     0.432" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_single_message.html' for the skin.
time="     0.433" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_enclosure_every.html' for the skin.
time="     0.433" type="debug" -> gui: Local file ':\skins\nudus-dark\qt_style.qss' exists, using it for the skin.
time="     0.435" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_adblocked.html' for the skin.
time="     0.436" type="debug" -> gui: Setting style: 'Fusion'.
time="     0.437" type="debug" -> gui: Activating alternative palette.
time="     0.437" type="debug" -> gui: Skin 'nudus-dark' loaded.
time="     0.438" type="debug" -> network: Persistent web data storage path: 'C:/RSS Guard\data4\web\storage'.
time="     0.438" type="debug" -> network: Disabling application-wide proxy completely.
time="     0.445" type="debug" -> core: OpenSSL version: 'OpenSSL 1.1.1j  16 Feb 2021'.
time="     0.446" type="debug" -> core: OpenSSL supported: 'true'.
time="     0.446" type="debug" -> core: Starting RSS Guard 4.2.2.
time="     0.447" type="debug" -> core: Instantiated class  'Application'.
time="     0.447" type="debug" -> core: Starting to load active localization. Desired localization is 'en'.
time="     0.448" type="debug" -> core: Application localization 'en' loaded successfully, specifically sublocalization 'en_US' was loaded.
time="     0.449" type="warning" -> core: Qt localization 'en_US' WAS NOT loaded successfully.
time="     0.451" type="debug" -> database: SQLite database connection 'MessagesModel' to file 'file::memory:' seems to be established.
time="     0.454" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, CASE WHEN length(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1;'.
time="     0.454" type="debug" -> core: Auto-download timer started with interval 60000 ms.
time="     0.455" type="debug" -> core: Creating FeedDownloader singleton.
time="     0.459" type="debug" -> gui: Creating main application form in thread: '0x132c'.
time="     0.465" type="debug" -> gui: Current row changed - proxy 'QModelIndex(-1,-1,0x0,QObject(0x0))', source 'QModelIndex(-1,-1,0x0,QObject(0x0))'.
time="     0.480" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     0.900" type="debug" -> gui: Creating tray icon menu.
time="     1.013" type="debug" -> core: Hiding the main window when the application is starting.
time="     1.013" type="debug" -> database: SQLite database connection 'FeedReader' to file 'file::memory:' seems to be established.
time="     1.014" type="debug" -> database: SQLite database connection 'FeedlyEntryPoint' to file 'file::memory:' seems to be established.
time="     1.044" type="debug" -> database: SQLite database connection 'GmailEntryPoint' to file 'file::memory:' seems to be established.
time="     1.054" type="debug" -> database: SQLite database connection 'GreaderEntryPoint' to file 'file::memory:' seems to be established.
time="     1.076" type="debug" -> database: SQLite database connection 'OwnCloudServiceEntryPoint' to file 'file::memory:' seems to be established.
time="     1.077" type="debug" -> database: SQLite database connection 'StandardServiceEntryPoint' to file 'file::memory:' seems to be established.
time="     1.079" type="debug" -> core: Filter accepts row 'Rico (RSS/ATOM/JSON)' and filter result is: 'true'.
time="     1.079" type="debug" -> database: SQLite database connection 'StandardServiceRoot' to file 'file::memory:' seems to be established.
time="     1.085" type="warning" -> libpng warning: iCCP: known incorrect sRGB profile
time="     1.094" type="debug" -> core: Custom ID of feed when loading from DB is '1'.
time="     1.097" type="debug" -> core: Custom ID of feed when loading from DB is '2'.
time="     1.120" type="debug" -> core: Custom ID of feed when loading from DB is '3'.
time="     1.129" type="debug" -> core: Custom ID of feed when loading from DB is '4'.
time="     1.130" type="debug" -> core: Custom ID of feed when loading from DB is '6'.
time="     1.130" type="debug" -> core: Custom ID of feed when loading from DB is '7'.
time="     1.131" type="debug" -> core: Custom ID of feed when loading from DB is '8'.
time="     1.131" type="debug" -> core: Custom ID of feed when loading from DB is '9'.
time="     1.132" type="debug" -> core: Custom ID of feed when loading from DB is '10'.
time="     1.139" type="debug" -> core: Custom ID of feed when loading from DB is '11'.
time="     1.146" type="debug" -> core: Custom ID of feed when loading from DB is '12'.
time="     1.150" type="debug" -> core: Custom ID of feed when loading from DB is '13'.
time="     1.152" type="debug" -> core: Custom ID of feed when loading from DB is '14'.
time="     1.153" type="debug" -> core: Custom ID of feed when loading from DB is '16'.
time="     1.153" type="debug" -> core: Custom ID of feed when loading from DB is '17'.
time="     1.154" type="debug" -> core: Custom ID of feed when loading from DB is '18'.
time="     1.154" type="debug" -> core: Custom ID of feed when loading from DB is '19'.
time="     1.155" type="debug" -> core: Custom ID of feed when loading from DB is '20'.
time="     1.155" type="debug" -> core: Custom ID of feed when loading from DB is '21'.
time="     1.155" type="debug" -> core: Custom ID of feed when loading from DB is '22'.
time="     1.156" type="debug" -> core: Custom ID of feed when loading from DB is '23'.
time="     1.158" type="debug" -> core: Custom ID of feed when loading from DB is '24'.
time="     1.158" type="debug" -> core: Custom ID of feed when loading from DB is '25'.
time="     1.163" type="debug" -> core: Custom ID of feed when loading from DB is '26'.
time="     1.164" type="debug" -> core: Custom ID of feed when loading from DB is '27'.
time="     1.165" type="debug" -> core: Custom ID of feed when loading from DB is '28'.
time="     1.165" type="debug" -> core: Custom ID of feed when loading from DB is '29'.
time="     1.178" type="debug" -> core: Custom ID of feed when loading from DB is '30'.
time="     1.178" type="debug" -> core: Custom ID of feed when loading from DB is '31'.
time="     1.179" type="debug" -> core: Custom ID of feed when loading from DB is '32'.
time="     1.179" type="debug" -> core: Custom ID of feed when loading from DB is '33'.
time="     1.182" type="debug" -> core: Custom ID of feed when loading from DB is '34'.
time="     1.183" type="debug" -> core: Custom ID of feed when loading from DB is '35'.
time="     1.195" type="debug" -> core: Custom ID of feed when loading from DB is '36'.
time="     1.196" type="debug" -> core: Custom ID of feed when loading from DB is '37'.
time="     1.196" type="debug" -> core: Custom ID of feed when loading from DB is '38'.
time="     1.197" type="debug" -> core: Custom ID of feed when loading from DB is '39'.
time="     1.198" type="debug" -> core: Custom ID of feed when loading from DB is '40'.
time="     1.198" type="debug" -> core: Custom ID of feed when loading from DB is '41'.
time="     1.199" type="debug" -> core: Custom ID of feed when loading from DB is '42'.
time="     1.199" type="debug" -> core: Custom ID of feed when loading from DB is '43'.
time="     1.200" type="debug" -> core: Custom ID of feed when loading from DB is '44'.
time="     1.203" type="warning" -> libpng warning: iCCP: known incorrect sRGB profile
time="     1.205" type="debug" -> core: Custom ID of feed when loading from DB is '45'.
time="     1.205" type="debug" -> core: Custom ID of feed when loading from DB is '46'.
time="     1.205" type="debug" -> core: Custom ID of feed when loading from DB is '47'.
time="     1.206" type="debug" -> core: Custom ID of feed when loading from DB is '48'.
time="     1.206" type="debug" -> core: Custom ID of feed when loading from DB is '49'.
time="     1.206" type="debug" -> core: Custom ID of feed when loading from DB is '50'.
time="     1.206" type="debug" -> core: Custom ID of feed when loading from DB is '51'.
time="     1.207" type="debug" -> core: Custom ID of feed when loading from DB is '52'.
time="     1.207" type="debug" -> core: Custom ID of feed when loading from DB is '53'.
time="     1.208" type="debug" -> core: Custom ID of feed when loading from DB is '54'.
time="     1.208" type="debug" -> core: Custom ID of feed when loading from DB is '55'.
time="     1.208" type="debug" -> core: Custom ID of feed when loading from DB is '56'.
time="     1.208" type="debug" -> core: Custom ID of feed when loading from DB is '57'.
time="     1.209" type="debug" -> core: Custom ID of feed when loading from DB is '58'.
time="     1.209" type="debug" -> core: Custom ID of feed when loading from DB is '59'.
time="     1.209" type="debug" -> core: Custom ID of feed when loading from DB is '60'.
time="     1.209" type="debug" -> core: Custom ID of feed when loading from DB is '61'.
time="     1.209" type="debug" -> core: Custom ID of feed when loading from DB is '62'.
time="     1.209" type="debug" -> core: Custom ID of feed when loading from DB is '63'.
time="     1.209" type="debug" -> core: Custom ID of feed when loading from DB is '64'.
time="     1.211" type="debug" -> core: Custom ID of feed when loading from DB is '65'.
time="     1.211" type="debug" -> core: Custom ID of feed when loading from DB is '66'.
time="     1.212" type="debug" -> core: Custom ID of feed when loading from DB is '67'.
time="     1.212" type="debug" -> core: Custom ID of feed when loading from DB is '68'.
time="     1.212" type="debug" -> core: Custom ID of feed when loading from DB is '69'.
time="     1.213" type="debug" -> core: Custom ID of feed when loading from DB is '70'.
time="     1.213" type="debug" -> core: Custom ID of feed when loading from DB is '71'.
time="     1.213" type="debug" -> core: Custom ID of feed when loading from DB is '72'.
time="     1.214" type="debug" -> core: Custom ID of feed when loading from DB is '73'.
time="     1.214" type="debug" -> core: Custom ID of feed when loading from DB is '74'.
time="     1.214" type="debug" -> core: Custom ID of feed when loading from DB is '75'.
time="     1.214" type="debug" -> core: Custom ID of feed when loading from DB is '76'.
time="     1.214" type="debug" -> core: Custom ID of feed when loading from DB is '77'.
time="     1.215" type="debug" -> core: Custom ID of feed when loading from DB is '78'.
time="     1.215" type="debug" -> core: Custom ID of feed when loading from DB is '79'.
time="     1.215" type="debug" -> core: Custom ID of feed when loading from DB is '80'.
time="     1.215" type="debug" -> core: Custom ID of feed when loading from DB is '81'.
time="     1.216" type="debug" -> core: Custom ID of feed when loading from DB is '82'.
time="     1.216" type="debug" -> core: Custom ID of feed when loading from DB is '83'.
time="     1.216" type="debug" -> core: Custom ID of feed when loading from DB is '84'.
time="     1.216" type="debug" -> core: Custom ID of feed when loading from DB is '85'.
time="     1.217" type="debug" -> core: Custom ID of feed when loading from DB is '86'.
time="     1.218" type="debug" -> database: SQLite database connection 'RecycleBin' to file 'file::memory:' seems to be established.
time="     1.243" type="debug" -> database: SQLite database connection 'ImportantNode' to file 'file::memory:' seems to be established.
time="     1.246" type="debug" -> database: SQLite database connection 'RootItem' to file 'file::memory:' seems to be established.
time="     1.248" type="debug" -> database: SQLite database connection 'Label' to file 'file::memory:' seems to be established.
time="     1.256" type="debug" -> database: SQLite connection 'Label' is already active.
time="     1.256" type="debug" -> database: SQLite database connection 'Label' to file 'file::memory:' seems to be established.
time="     1.264" type="debug" -> database: SQLite connection 'Label' is already active.
time="     1.264" type="debug" -> database: SQLite database connection 'Label' to file 'file::memory:' seems to be established.
time="     1.272" type="debug" -> database: SQLite connection 'Label' is already active.
time="     1.307" type="debug" -> database: SQLite database connection 'Label' to file 'file::memory:' seems to be established.
time="     1.316" type="debug" -> database: SQLite connection 'StandardServiceRoot' is already active.
time="     1.316" type="debug" -> database: SQLite database connection 'StandardServiceRoot' to file 'file::memory:' seems to be established.
time="     1.320" type="debug" -> database: SQLite database connection 'TtRssServiceEntryPoint' to file 'file::memory:' seems to be established.
time="     1.321" type="debug" -> gui: User wants to have tray icon.
time="     1.321" type="debug" -> gui: Tray icon is available, showing now.
time="     1.326" type="debug" -> gui: Creating SystemTrayIcon instance.
time="     1.344" type="debug" -> gui: Showing tray icon immediately.
time="     1.395" type="debug" -> gui: Tray icon displayed.
time="     1.396" type="debug" -> gui: Feed list item expanded - Rico (RSS/ATOM/JSON)
time="     1.396" type="debug" -> core: Filter accepts row 'Recycle bin' and filter result is: 'true'.
time="     1.396" type="debug" -> core: Filter accepts row 'Important articles' and filter result is: 'true'.
time="     1.397" type="debug" -> core: Filter accepts row 'Unread articles' and filter result is: 'true'.
time="     1.397" type="debug" -> core: Filter accepts row 'Labels' and filter result is: 'true'.
time="     1.397" type="debug" -> core: Filter accepts row 'Military' and filter result is: 'true'.
time="     1.398" type="debug" -> core: Filter accepts row '____Fun' and filter result is: 'true'.
time="     1.398" type="debug" -> core: Filter accepts row '____Fun - comics' and filter result is: 'true'.
time="     1.398" type="debug" -> core: Filter accepts row 'Downloads' and filter result is: 'true'.
time="     1.399" type="debug" -> core: Filter accepts row 'Computers' and filter result is: 'true'.
time="     1.399" type="debug" -> core: Filter accepts row '___Blogs' and filter result is: 'true'.
time="     1.399" type="debug" -> core: Filter accepts row '___Kitchen' and filter result is: 'true'.
time="     1.400" type="debug" -> core: Filter accepts row '___Society & Politics' and filter result is: 'true'.
time="     1.400" type="debug" -> core: Filter accepts row '__Design, graphics, DTP' and filter result is: 'true'.
time="     1.401" type="debug" -> gui: Feed list item expanded - Labels
time="     1.401" type="debug" -> gui: Feed list item expanded - Military
time="     1.401" type="debug" -> gui: Feed list item expanded - ____Fun
time="     1.402" type="debug" -> gui: Feed list item expanded - ____Fun - comics
time="     1.402" type="debug" -> gui: Feed list item expanded - Downloads
time="     1.402" type="debug" -> gui: Feed list item expanded - Computers
time="     1.403" type="debug" -> gui: Feed list item expanded - ___Blogs
time="     1.403" type="debug" -> gui: Feed list item expanded - ___Kitchen
time="     1.403" type="debug" -> gui: Feed list item expanded - ___Society & Politics
time="     1.404" type="debug" -> gui: Feed list item expanded - __Design, graphics, DTP
time="     1.404" type="debug" -> core: No execution message received from other app instances.
time="     1.438" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     1.532" type="debug" -> gui: Hovered link: 'QUrl()'.
time="     1.533" type="debug" -> core: Silencing GUI message: ''.
time="     2.151" type="debug" -> network: Destroying Downloader instance.
time="     2.153" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="     7.250" type="debug" -> gui: Message splitter moved.
time="     7.258" type="debug" -> core: Filter accepts row 'Joe Monster' and filter result is: 'true'.
time="     7.259" type="debug" -> core: Filter accepts row 'Mistrzowie.org' and filter result is: 'true'.
time="     7.259" type="debug" -> core: Filter accepts row 'Piekielni.pl' and filter result is: 'true'.
time="     7.259" type="debug" -> core: Filter accepts row 'Cartoonwars.pl' and filter result is: 'true'.
time="     7.259" type="debug" -> core: Filter accepts row 'Chomikiem i rysikiem' and filter result is: 'true'.
time="     7.260" type="debug" -> core: Filter accepts row 'JAGODIBUJA' and filter result is: 'true'.
time="     7.260" type="debug" -> core: Filter accepts row 'KRYZYS WIEKU' and filter result is: 'true'.
time="     7.260" type="debug" -> core: Filter accepts row 'Sponiewierany Ołówek' and filter result is: 'true'.
time="     7.260" type="debug" -> core: Filter accepts row 'Boli Blog' and filter result is: 'true'.
time="     7.260" type="debug" -> core: Filter accepts row 'Radek Teklak' and filter result is: 'true'.
time="     7.261" type="debug" -> core: Filter accepts row 'Malvina Pe.' and filter result is: 'true'.
time="     7.261" type="debug" -> core: Filter accepts row 'notatki na mankietach' and filter result is: 'true'.
time="     7.261" type="debug" -> core: Filter accepts row 'Serialowa' and filter result is: 'true'.
time="     7.261" type="debug" -> core: Filter accepts row 'snafu' and filter result is: 'true'.
time="     7.261" type="debug" -> core: Filter accepts row 'To Tylko Teoria' and filter result is: 'true'.
time="     7.261" type="debug" -> core: Filter accepts row 'użyj wyobraźni' and filter result is: 'true'.
time="     7.262" type="debug" -> core: Filter accepts row 'Volantification.pl' and filter result is: 'true'.
time="     7.262" type="debug" -> core: Filter accepts row '...et si vous veniez manger chez nous?' and filter result is: 'true'.
time="     7.262" type="debug" -> core: Filter accepts row 'Gotuj z Cthulhu' and filter result is: 'true'.
time="     7.262" type="debug" -> core: Filter accepts row 'Klapsa czy konferencja?' and filter result is: 'true'.
time="     7.262" type="debug" -> core: Filter accepts row 'Krytyka Kulinarna' and filter result is: 'true'.
time="     7.263" type="debug" -> core: Filter accepts row 'Kwestia Smaku' and filter result is: 'true'.
time="     7.263" type="debug" -> core: Filter accepts row 'LADY KITCHEN' and filter result is: 'true'.
time="     7.263" type="debug" -> core: Filter accepts row 'Pocztówki z kuchni' and filter result is: 'true'.
time="     7.263" type="debug" -> core: Filter accepts row 'Przepisy kulinarne, poradnik kulinarny:' and filter result is: 'true'.
time="     7.264" type="debug" -> core: Filter accepts row 'Simple Cooking Pleasures' and filter result is: 'true'.
time="     7.264" type="debug" -> core: Filter accepts row 'Twoje&Moje' and filter result is: 'true'.
time="     7.264" type="debug" -> core: Filter accepts row 'White Plate' and filter result is: 'true'.
time="     7.264" type="debug" -> core: Filter accepts row 'Zmysły w kuchni - przepisy kulinarne, podróże, książki' and filter result is: 'true'.
time="     7.264" type="debug" -> core: Filter accepts row 'Ahmed Goldstein' and filter result is: 'true'.
time="     7.265" type="debug" -> core: Filter accepts row 'Crazy Nauka' and filter result is: 'true'.
time="     7.265" type="debug" -> core: Filter accepts row 'Pokolenie Ikea' and filter result is: 'true'.
time="     7.265" type="debug" -> core: Filter accepts row 'Ateistka/Antyteistka' and filter result is: 'true'.
time="     7.265" type="debug" -> core: Filter accepts row 'Crowd Media' and filter result is: 'true'.
time="     7.266" type="debug" -> core: Filter accepts row 'Gra w klasy' and filter result is: 'true'.
time="     7.266" type="debug" -> core: Filter accepts row 'KrytykaPolityczna.pl' and filter result is: 'true'.
time="     7.266" type="debug" -> core: Filter accepts row 'Między Rurytanią a Molwanią' and filter result is: 'true'.
time="     7.266" type="debug" -> core: Filter accepts row 'Obywatele RP' and filter result is: 'true'.
time="     7.266" type="debug" -> core: Filter accepts row 'oko.press' and filter result is: 'true'.
time="     7.267" type="debug" -> core: Filter accepts row 'Piknik na skraju głupoty' and filter result is: 'true'.
time="     7.267" type="debug" -> core: Filter accepts row 'PolskiAteista.pl' and filter result is: 'true'.
time="     7.267" type="debug" -> core: Filter accepts row 'slwstr' and filter result is: 'true'.
time="     7.267" type="debug" -> core: Filter accepts row 'Wiadomo.co' and filter result is: 'true'.
time="     7.267" type="debug" -> core: Filter accepts row 'Globalna Gra – zrozumieć świat | Geopolityka | Stosunki międzynarodowe' and filter result is: 'true'.
time="     7.268" type="debug" -> core: Filter accepts row 'Bittbox' and filter result is: 'true'.
time="     7.268" type="debug" -> core: Filter accepts row 'Comments on: Tips For Creating The Best Brand Design' and filter result is: 'true'.
time="     7.268" type="debug" -> core: Filter accepts row 'Blugraphic' and filter result is: 'true'.
time="     7.268" type="debug" -> core: Filter accepts row 'Design Shack' and filter result is: 'true'.
time="     7.268" type="debug" -> core: Filter accepts row 'Designbeep' and filter result is: 'true'.
time="     7.269" type="debug" -> core: Filter accepts row 'Eleganckie Wizytówki.' and filter result is: 'true'.
time="     7.269" type="debug" -> core: Filter accepts row '✔️ Fotografia ślubna Wrocław Jacek Kawecki' and filter result is: 'true'.
time="     7.269" type="debug" -> core: Filter accepts row 'Media Zine' and filter result is: 'true'.
time="     7.269" type="debug" -> core: Filter accepts row 'Grafmag' and filter result is: 'true'.
time="     7.269" type="debug" -> core: Filter accepts row 'GraphicBurger' and filter result is: 'true'.
time="     7.270" type="debug" -> core: Filter accepts row 'hatalska.com' and filter result is: 'true'.
time="     7.270" type="debug" -> core: Filter accepts row 'Layers Magazine' and filter result is: 'true'.
time="     7.270" type="debug" -> core: Filter accepts row 'Web Design Blog Helping Website and Graphic Designers' and filter result is: 'true'.
time="     7.270" type="debug" -> core: Filter accepts row 'Photoshop Essentials.com Latest Tutorials' and filter result is: 'true'.
time="     7.270" type="debug" -> core: Filter accepts row 'Articles on Smashing Magazine — For Web Designers And Developers' and filter result is: 'true'.
time="     7.271" type="debug" -> core: Filter accepts row 'Speckyboy Design Magazine' and filter result is: 'true'.
time="     7.271" type="debug" -> core: Filter accepts row 'Spoon Graphics' and filter result is: 'true'.
time="     7.271" type="debug" -> core: Filter accepts row 'Envato Tuts+ Design & Illustration' and filter result is: 'true'.
time="     7.271" type="debug" -> core: Filter accepts row 'Webdesigner Depot' and filter result is: 'true'.
time="     7.271" type="debug" -> core: Filter accepts row 'IndiSnip [InDesign® Snippets]' and filter result is: 'true'.
time="     7.272" type="debug" -> core: Filter accepts row 'IndiTip [InDesign® Tips&Tricks]' and filter result is: 'true'.
time="     7.272" type="debug" -> core: Filter accepts row 'The InDesigner' and filter result is: 'true'.
time="     7.272" type="debug" -> core: Filter accepts row 'Planet Photoshop' and filter result is: 'true'.
time="     7.272" type="debug" -> core: Filter accepts row 'PSDGraphics' and filter result is: 'true'.
time="     7.273" type="debug" -> core: Filter accepts row 'PSHERO' and filter result is: 'true'.
time="     7.273" type="debug" -> core: Filter accepts row 'Vectips' and filter result is: 'true'.
time="     7.275" type="debug" -> core: Filter accepts row 'Ciekawostki ze świata gier' and filter result is: 'true'.
time="     7.275" type="debug" -> core: Filter accepts row 'AddictiveTips' and filter result is: 'true'.
time="     7.276" type="debug" -> core: Filter accepts row 'Spece.IT' and filter result is: 'true'.
time="     7.276" type="debug" -> core: Filter accepts row 'TechPowerUp' and filter result is: 'true'.
time="     7.277" type="debug" -> core: Filter accepts row 'TweakTown' and filter result is: 'true'.
time="     7.277" type="debug" -> core: Filter accepts row 'Neowin News Feed for: Software' and filter result is: 'true'.
time="     7.277" type="debug" -> core: Filter accepts row 'Downloadly' and filter result is: 'true'.
time="     7.277" type="debug" -> core: Filter accepts row 'Get Into PC' and filter result is: 'true'.
time="     7.277" type="debug" -> core: Filter accepts row 'Dj Mixes, Live Sets, Radioshow, Charts and Compilations!' and filter result is: 'true'.
time="     7.278" type="debug" -> core: Filter accepts row 'Windows software, drivers & operating system' and filter result is: 'true'.
time="     7.278" type="debug" -> core: Filter accepts row 'Vorek.pl - portal,download,forum,pobierz,filmy,muzyka,programy' and filter result is: 'true'.
time="     7.278" type="debug" -> core: Filter accepts row 'The Drive' and filter result is: 'true'.
time="     7.278" type="debug" -> core: Filter accepts row 'Konflikty.pl' and filter result is: 'true'.
time="     7.278" type="debug" -> core: Filter accepts row 'The Aviation Geek Club' and filter result is: 'true'.
time="     7.279" type="debug" -> core: Filter accepts row 'Important' and filter result is: 'true'.
time="     7.279" type="debug" -> core: Filter accepts row 'Later' and filter result is: 'true'.
time="     7.279" type="debug" -> core: Filter accepts row 'Download' and filter result is: 'true'.
time="     7.279" type="debug" -> core: Filter accepts row 'Saved' and filter result is: 'true'.
time="     7.827" type="debug" -> gui: Main window's hide event
time="    10.945" type="debug" -> gui: Main window's hide event
time="    11.904" type="debug" -> gui: Main window's hide event
time="    12.718" type="debug" -> gui: Main window's hide event
time="    13.502" type="debug" -> gui: Main window's hide event
time="    14.220" type="debug" -> gui: Main window's hide event
time="    19.753" type="warning" -> QIODevice::write (QFile, "C:\Program Files\nodejs\package.json"): device not open
time="    19.754" type="warning" -> QIODevice::write (QFile, "C:\Program Files\nodejs\package.json"): device not open
time="    21.424" type="debug" -> nodejs: Installing packages '@cliqz/adblocker@1.23.5'.
time="    21.424" type="warning" -> QIODevice::write (QFile, "C:\Program Files\nodejs\package.json"): device not open
time="    23.726" type="critical" -> nodejs: Error when installing packages '@cliqz/adblocker@1.23.5'. Exit code: '-4048'. Message: 'npm ERR! code EPERM
npm ERR! syscall mkdir
npm ERR! path C:\Program Files\nodejs\node_modules\.corepack-yRBjKBW1
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, mkdir 'C:\Program Files\nodejs\node_modules\.corepack-yRBjKBW1'
npm ERR!  [Error: EPERM: operation not permitted, mkdir 'C:\Program Files\nodejs\node_modules\.corepack-yRBjKBW1'] {
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: 'C:\\Program Files\\nodejs\\node_modules\\.corepack-yRBjKBW1'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rico\AppData\Local\npm-cache\_logs\2022-05-04T10_24_10_546Z-debug-0.log
'.
time="    23.726" type="critical" -> adblock: Needed Node.js packages were not installed: 'Unknown error'.
time="    23.749" type="critical" -> core: Notification for event '8' not found
time="    28.368" type="debug" -> gui: Main window's hide event
time="    30.988" type="debug" -> gui: Main window's hide event

### Operating system and version

* OS: Windows 10 x64
* RSS Guard version: 4.2.2

**Comment by martinrotter** [comment]
How does this window looks like in your setup?

![image](https://user-images.githubusercontent.com/1255302/166669584-74c61e38-dabd-4c1b-9654-508ac25cfed2.png)

**Comment by martinrotter** [comment]
As for minimizing thing, you really need to write exact steps you take to minimize the window, what exactly happen etc.

**Comment by martinrotter** [comment]
No response, closing.

**Comment by erkston** [comment]
I was having both of these issues and have some hopefully helpful info:

When the "Hide main window when it is minimized" setting is checked, clicking either the Minimize button on the top right of the window OR the Taskbar button, the window briefly minimizes then reappears. Clicking the tray icon minimizes the window and removes the icon from taskbar as expected. OP has hide_when_minimized=true in their config so I am pretty sure this is the issue.

As for the adblock error, OP has their Node.js Package Folder set to a location that requires Admin privileges (package_folderWindows=C:\\Program Files\\nodejs). I did the same thing and assumed that the "Package Folder" should be the nodejs base folder. Since the .exe and .cmd did not show full paths I (wrongly) assumed it needed the base folder.

Somewhat relatedly, all three of the "Browse" buttons on the Node.js settings set the Package Folder field. The top two fields have to be edited manually even though they have a Browse button.
