### ISSUE TITLE
[BUG]: Images in nowebenging in 4.2.2 appear pixelated

### ISSUE THREAD

**Issue by senseiski** [martinrotter/rssguard#724]
### Brief description of the issue

All images appear pixelated and changing the height in settings does not appear to fix this - if opened via right click the images appear okay, but there's no back button to go back to the article ![Screenshot from 2022-05-05 13-53-25](https://user-images.githubusercontent.com/6433919/166909848-9fdc7ec5-1da4-4e89-a139-4ed8580ec4da.png)

### How to reproduce the bug?

1. enable images in settings
2. fetch an article with images from a feed

### What was the expected result?

images to appear not pixelated

### What actually happened?

images appear pixelated as shown in screenshot

### Debug log

I don't know how to see log for an app image, using the AppImage on Linux Mint 20.3. If you can let me know how, I'll add the log.

### Operating system and version

* OS: Linux Mint 20.3
* RSS Guard version: 4.2.2 nowebengine

**Comment by martinrotter** [comment]
I see.

Does it help if you set the "height" setting to "-1" (unchanged size)? If yes, then it seems to be "my" bug. If not, then it is likely upstream bug.

**Comment by martinrotter** [comment]
Also, are images still pixelated if you click on that image and open the image directly?

**Comment by senseiski** [comment]
> I see.
> 
> Does it help if you set the "height" setting to "-1" (unchanged size)? If yes, then it seems to be "my" bug. If not, then it is likely upstream bug.

That seems to fix it, thanks!
