### ISSUE TITLE
[FR]: Add option to disable disk cache

### ISSUE THREAD

**Issue by meelten** [martinrotter/rssguard#725]
### Brief description of the feature request

As mentioned [here](https://github.com/martinrotter/rssguard/issues/716#issuecomment-1118492929) I propose adding another switch, alongside cookies, to disable disk cache. I don't think many people actually benefit from disk cache in rss reader and it can get to considerable size pretty fast also causing unnecessary disk activity.

PS. Although I'm kind of baffled now because after upgrade from 4.1.2 to 4.2.2 RSS Guard doesn't seem to use usual directory anymore (on Linux - /.cache/RSS Guard/QtWebEngine). Was it moved somewhere or cache is not used by default already?

**Comment by martinrotter** [comment]
Webengine cache was moved under RSS Guard main config folder.

**Comment by akinokonomi** [comment]
> on Linux - /.cache/RSS Guard/QtWebEngine

It used to be in `~/.local/share/RSS Guard`, but there might have been some cache in `~/.cache/RSS Guard` as well.

> Webengine cache was moved under RSS Guard main config folder

@martinrotter Why did you do that? For portability?

I've never seen application that does that. The usual path for Qt webengine cache is `~/.local/share/APP_NAME`. 

Now it's just baffling. I think, it'd have been better to be left as is.
 Even though `~/.local/share` is not the best place for it, `~/.config` is worse.

**Comment by martinrotter** [comment]
> > on Linux - /.cache/RSS Guard/QtWebEngine
> 
> It used to be in `~/.local/share/RSS Guard`, but there might have been some cache in `~/.cache/RSS Guard` as well.
> 
> > Webengine cache was moved under RSS Guard main config folder
> 
> @martinrotter Why did you do that? For portability?
> 
> I've never seen application that does that. The usual path for Qt webengine cache is `~/.local/share/APP_NAME`.
> 
> Now it's just baffling. I think, it'd have been better to be left as is. Even though `~/.local/share` is not the best place for it, `~/.config` is worse.

Yes, I moved the cache under RSS Guard user data folder (`web` subfolder). Technically able users who really want to have cache in proper directories can use symlinks easily to achieve that.

Main goal was to have cache also synced for people who sync their user data folder. Also, note that QtWebEngine cache is more or less cross-platform (as well as other RSS Guard user data) so the cache could work even when syncing across multiple platforms.

**Comment by akinokonomi** [comment]
> Main goal was to have cache also synced for people who sync their user data folder.

I don't really believe that cache needs to be synchronized. Why would you want that? 
"web" just stores the default Qtwebengine cache, right?

And while it heavily depends on whether user would browse websites in RSS Guard or just view RSS article's content, caching in modern browsers is not so great anyway, it clears up really fast.
 It's not like it stores months' worth of data from all visited websites.

> Also, note that QtWebEngine cache is more or less cross-platform (as well as other RSS Guard user data) so the cache could work even when syncing across multiple platforms.

It may as well be cross-platform, but even if caching actually worked good, I don't really see why would anyone want to sync it.

And as you've said, people who *really* cares about synching cache for cross-platform use could easily do that with symlinks.
Only technically able users would want a cross-platform synching, so they are likely aware of symlinks.

(IIRC, there was a nice tool for creating symlinks on windows too. I forgot the name.)

**Comment by martinrotter** [comment]
> (IIRC, there was a nice tool for creating symlinks on windows too. I forgot the name.)

I just use "mklink". Works.

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/216343942-346969ac-d8e5-479a-9760-a81ceb3f7dcd.png)
