### ISSUE TITLE
[BUG]: Inoreader - ProtocolInvalidOperationError

### ISSUE THREAD

**Issue by mizzunet** [martinrotter/rssguard#728]
### Brief description of the issue

Inoreader failed to login wth error `ProtocolInvalidOperationError`

### How to reproduce the bug?

1. Create a new application at https://www.inoreader.com/all_articles#preferences-developer, set redirect URL to http://localhost:14488
2. Add a new account in RSSGuard, Accounts > Add account > Google Reader API
3. Choose Inoreader
4. Fill username, API key and API app key
5. Click on `Login`
6. Do login
7. Will say, `You can close this window now. Go back to RSS Guard.`

### What was the expected result?

Successfully log in on RSSGuard

### What actually happened?

Shown an error dialog saying `ProtocolInvalidOperationError`

### Debug log

time="     0.093" type="debug" -> core: Initializing settings in '/home/missu/.config/RSS Guard 4/config/config.ini' (non-portable way).
time="     0.095" type="info" -> 

GL Type: desktop
Surface Type: OpenGL
Surface Profile: NoProfile
Surface Version: 3.0
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: yes

Init Parameters:
  *  application-name rssguard 
  *  browser-subprocess-path /usr/lib/qt6/QtWebEngineProcess 
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-setuid-sandbox  
  *  disable-speech-api  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-threaded-compositing  
  *  in-process-gpu  
  *  log  
  *  use-gl desktop 

time="     0.243" type="debug" -> database: File-based SQLite database connection 'DatabaseFactory' to file '/home/missu/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.243" type="debug" -> database: File-based SQLite database has version '2'.
time="     0.243" type="debug" -> gui: Available icon theme paths: QList(/home/missu/.icons, /home/missu/.local/share/icons, /usr/share/icons, :/icons, :/graphics, /home/missu/.config/RSS Guard 4/icons, /usr/bin/icons)
time="     0.244" type="debug" -> gui: Icon theme 'breeze-dark' already loaded.
time="     0.245" type="debug" -> gui: Found path of base skin: ':/skins/nudus-base'.
time="     0.245" type="debug" -> gui: Local file ':/skins/nudus-dark/html_wrapper.html' exists, using it for the skin.
time="     0.245" type="debug" -> gui: Local file ':/skins/nudus-dark/html_style.css' exists, using it for the skin.
time="     0.245" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_enclosure_image.html' for the skin.
time="     0.246" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_single_message.html' for the skin.
time="     0.246" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_enclosure_every.html' for the skin.
time="     0.246" type="debug" -> gui: Local file ':/skins/nudus-dark/qt_style.qss' exists, using it for the skin.
time="     0.246" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_adblocked.html' for the skin.
time="     0.246" type="debug" -> gui: Setting style: 'kvantum-dark'.
time="     0.275" type="debug" -> gui: Skin 'nudus-dark' loaded.
time="     0.275" type="debug" -> network: Persistent web data storage path: '/home/missu/.config/RSS Guard 4/web/storage'.
time="     0.275" type="debug" -> network: Disabling application-wide proxy completely.
time="     0.283" type="debug" -> core: OpenSSL version: 'OpenSSL 1.1.1o  3 May 2022'.
time="     0.283" type="debug" -> core: OpenSSL supported: 'true'.
time="     0.283" type="debug" -> core: Starting RSS Guard 4.2.2.
time="     0.283" type="debug" -> core: Instantiated class  'Application'.
time="     0.283" type="debug" -> core: Starting to load active localization. Desired localization is 'en_GB'.
time="     0.283" type="debug" -> core: Application localization 'en_GB' loaded successfully, specifically sublocalization 'en_GB' was loaded.
time="     0.283" type="warning" -> core: Qt localization 'en_GB' WAS NOT loaded successfully.
time="     0.287" type="debug" -> database: SQLite database connection 'MessagesModel' to file '/home/missu/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.289" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, CASE WHEN length(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1;'.
time="     0.289" type="debug" -> core: Auto-download timer started with interval 60000 ms.
time="     0.289" type="debug" -> core: Creating FeedDownloader singleton.
time="     0.302" type="debug" -> gui: Creating main application form in thread: '0x7f4abd8ce240'.
time="     0.311" type="debug" -> gui: Current row changed - proxy 'QModelIndex(-1,-1,0x0,QObject(0x0))', source 'QModelIndex(-1,-1,0x0,QObject(0x0))'.
time="     0.315" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     0.409" type="debug" -> CTRL is NOT pressed while sorting articles - sorting with standard mode.
time="     0.410" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, CASE WHEN length(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1 ORDER BY Messages.id DESC;'.
time="     0.410" type="debug" -> gui: Reloading of msg selections took 1 miliseconds.
time="     0.432" type="debug" -> core: Showing the main window when the application is starting.
time="     0.444" type="debug" -> database: SQLite database connection 'FeedReader' to file '/home/missu/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.445" type="debug" -> database: SQLite database connection 'FeedlyEntryPoint' to file '/home/missu/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.446" type="debug" -> database: SQLite database connection 'GmailEntryPoint' to file '/home/missu/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.447" type="debug" -> database: SQLite database connection 'GreaderEntryPoint' to file '/home/missu/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.447" type="debug" -> database: SQLite database connection 'OwnCloudServiceEntryPoint' to file '/home/missu/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.448" type="debug" -> database: SQLite database connection 'StandardServiceEntryPoint' to file '/home/missu/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.449" type="debug" -> database: SQLite database connection 'TtRssServiceEntryPoint' to file '/home/missu/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.450" type="debug" -> gui: User wants to have tray icon.
time="     0.450" type="warning" -> gui: Showing tray icon with 3000 ms delay.
time="     0.450" type="debug" -> core: No execution message received from other app instances.
time="     0.643" type="debug" -> gui: Hovered link: 'QUrl()'.
time="     1.276" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     1.569" type="debug" -> network: Destroying Downloader instance.
time="     1.569" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="     3.184" type="warning" -> failed to create compose table
time="     4.821" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     4.822" type="debug" -> oauth: User does not want handler to be running.
time="    24.034" type="debug" -> oauth: Clearing tokens.
time="    24.035" type="debug" -> oauth: Stopped redirection handler.
time="    24.035" type="debug" -> oauth: OAuth redirect handler IS LISTENING on address '127.0.0.1' and port '14488'.
time="    24.035" type="debug" -> network: We are trying to open URL 'https://www.inoreader.com/oauth2/auth?client_id=1000004455&scope=read write&redirect_uri=http://localhost:14488&response_type=code&state=3580648747&prompt=consent&duration=permanent&access_type=offline'.
time="    26.054" type="debug" -> gui: Message splitter moved.
time="    40.711" type="debug" -> oauth: Posting data for access token retrieval: 'client_id=1000004455&client_secret=tgW2nUH0_TB5udffiRtwUoxqEISwaRf9 &code=67dbaa45e178433d9006b1d6ebbaa910d88c7402&redirect_uri=http://localhost:14488&grant_type=authorization_code'.
time="    41.163" type="critical" -> oauth: Invalid request: 'http://127.0.0.114488/favicon.ico'.
time="    41.164" type="critical" -> oauth: Invalid request: 'http://127.0.0.114488/favicon.ico'.
time="    41.167" type="critical" -> oauth: Invalid request: 'http://127.0.0.114488/favicon.ico'.
time="    41.168" type="critical" -> oauth: Invalid request: 'http://127.0.0.114488/favicon.ico'.
time="    41.168" type="critical" -> oauth: Invalid request: 'http://127.0.0.114488/favicon.ico'.
time="    41.169" type="critical" -> oauth: Invalid request: 'http://127.0.0.114488/favicon.ico'.
time="    41.171" type="critical" -> oauth: Invalid request: 'http://127.0.0.114488/favicon.ico'.
time="    41.172" type="critical" -> oauth: Invalid request: 'http://127.0.0.114488/favicon.ico'.
time="    41.174" type="critical" -> oauth: Invalid request: 'http://127.0.0.114488/favicon.ico'.
time="    41.175" type="critical" -> oauth: Invalid request: 'http://127.0.0.114488/favicon.ico'.
time="    42.425" type="debug" -> oauth: Token response: '{
    "error": "invalid_client",
    "error_description": "The client credentials are invalid"
}
'.
time="    42.426" type="warning" -> oauth: Network error when obtaining token response: 'QNetworkReply::ProtocolInvalidOperationError'.

### Operating system and version

* OS: Arch Linux
* RSS Guard version: 4.2.2

**Comment by martinrotter** [comment]
> "error": "invalid_client",
> "error_description": "The client credentials are invalid"

**Comment by martinrotter** [comment]
It seems your client secret contains "space" in the end

'tgW2nUH0_TB5udffiRtwUoxqEISwaRf9 ' but it should be 'tgW2nUH0_TB5udffiRtwUoxqEISwaRf9'

?

**Comment by martinrotter** [comment]
Thing is that "official" RSS Guard builds already HAVE these tokens built-in. Simply leave both textboxes empty and it should work.
