### ISSUE TITLE
[FR]: "Load image from file" for RSS Guard interface background

### ISSUE THREAD

**Issue by RetroAbstract** [martinrotter/rssguard#729]
### Brief description of the feature request

This feature would allow the user to import an image file and apply it as the interface's background.

For example, if I were to "Load image from file" this image:

![Background](https://user-images.githubusercontent.com/103272301/166063942-9c046c3a-5264-4e37-a621-8456758e7629.jpg)
([Source](https://unsplash.com/photos/zNN6ubHmruI))

RSS Guard would look like this:

![5](https://user-images.githubusercontent.com/103272301/166066291-e7cb15b0-e01c-431a-a54d-a77d6ca29409.jpg)

Image fitting options would include:

- Fill
- Fit
- Stretch
- Tile
- Centre

**Comment by martinrotter** [comment]
Nice feature request. I myself do not really plan to implement this. Maybe someone could provide PR.

**Comment by akinokonomi** [comment]
In my opinion, similar to https://github.com/martinrotter/rssguard/issues/698, this is also should be done via external Qt themes.
