### ISSUE TITLE
[BUG]: Inoreader: Not syncing, fetching anything

### ISSUE THREAD

**Issue by mizzunet** [martinrotter/rssguard#730]
### Brief description of the issue

After login, nothing seem to be occurring.

I tried to manually `Synchronise folders` and `Fetch all`, that didn't do anything.
I tried disabling `Intellingent Sync Algorithm`, didn't help either

### How to reproduce the bug?

1. Login for Inoreader
2. Wait for automatic syncing, and showing articles
3. See that it doesn't happen
4. Do manully Sync and Fetch

### What was the expected result?

Display folders, unread articles and all

### What actually happened?

It just stays like this,
![image](https://user-images.githubusercontent.com/10193999/167408889-9d548eb7-a588-4f54-9b5e-4355429f35c1.png)

Nothing happening.

### Debug log

time="     0.090" type="debug" -> core: Initializing settings in '/home/missu/.config/RSS Guard 4/config/config.ini' (non-portable way).
time="     0.092" type="info" -> 

GL Type: desktop
Surface Type: OpenGL
Surface Profile: NoProfile
Surface Version: 3.0
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: yes

Init Parameters:
  *  application-name rssguard 
  *  browser-subprocess-path /usr/lib/qt6/QtWebEngineProcess 
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-setuid-sandbox  
  *  disable-speech-api  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-threaded-compositing  
  *  in-process-gpu  
  *  log  
  *  use-gl desktop 

time="     0.248" type="debug" -> database: File-based SQLite database connection 'DatabaseFactory' to file '/home/missu/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.248" type="debug" -> database: File-based SQLite database has version '2'.
time="     0.248" type="debug" -> gui: Available icon theme paths: QList(/home/missu/.icons, /home/missu/.local/share/icons, /usr/share/icons, :/icons, :/graphics, /home/missu/.config/RSS Guard 4/icons, /usr/bin/icons)
time="     0.251" type="debug" -> gui: Icon theme 'breeze-dark' already loaded.
time="     0.252" type="debug" -> gui: Found path of base skin: ':/skins/nudus-base'.
time="     0.253" type="debug" -> gui: Local file ':/skins/nudus-dark/html_wrapper.html' exists, using it for the skin.
time="     0.253" type="debug" -> gui: Local file ':/skins/nudus-dark/html_style.css' exists, using it for the skin.
time="     0.253" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_enclosure_image.html' for the skin.
time="     0.253" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_single_message.html' for the skin.
time="     0.253" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_enclosure_every.html' for the skin.
time="     0.253" type="debug" -> gui: Local file ':/skins/nudus-dark/qt_style.qss' exists, using it for the skin.
time="     0.254" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_adblocked.html' for the skin.
time="     0.254" type="debug" -> gui: Setting style: 'kvantum-dark'.
time="     0.314" type="debug" -> gui: Skin 'nudus-dark' loaded.
time="     0.314" type="debug" -> network: Persistent web data storage path: '/home/missu/.config/RSS Guard 4/web/storage'.
time="     0.314" type="debug" -> network: Disabling application-wide proxy completely.
time="     0.331" type="debug" -> core: OpenSSL version: 'OpenSSL 1.1.1o  3 May 2022'.
time="     0.331" type="debug" -> core: OpenSSL supported: 'true'.
time="     0.331" type="debug" -> core: Starting RSS Guard 4.2.2.
time="     0.331" type="debug" -> core: Instantiated class  'Application'.
time="     0.331" type="debug" -> core: Starting to load active localization. Desired localization is 'en_GB'.
time="     0.332" type="debug" -> core: Application localization 'en_GB' loaded successfully, specifically sublocalization 'en_GB' was loaded.
time="     0.332" type="warning" -> core: Qt localization 'en_GB' WAS NOT loaded successfully.
time="     0.340" type="debug" -> database: SQLite database connection 'MessagesModel' to file '/home/missu/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.344" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, CASE WHEN length(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1;'.
time="     0.345" type="debug" -> core: Auto-download timer started with interval 60000 ms.
time="     0.345" type="debug" -> core: Creating FeedDownloader singleton.
time="     0.374" type="debug" -> gui: Creating main application form in thread: '0x7ff1901bf240'.
time="     0.382" type="debug" -> gui: Current row changed - proxy 'QModelIndex(-1,-1,0x0,QObject(0x0))', source 'QModelIndex(-1,-1,0x0,QObject(0x0))'.
time="     0.386" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     0.491" type="debug" -> CTRL is NOT pressed while sorting articles - sorting with standard mode.
time="     0.492" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, CASE WHEN length(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1 ORDER BY Messages.id DESC;'.
time="     0.492" type="debug" -> gui: Reloading of msg selections took 1 miliseconds.
time="     0.513" type="debug" -> core: Showing the main window when the application is starting.
time="     0.524" type="debug" -> database: SQLite database connection 'FeedReader' to file '/home/missu/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.525" type="debug" -> database: SQLite database connection 'FeedlyEntryPoint' to file '/home/missu/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.526" type="debug" -> database: SQLite database connection 'GmailEntryPoint' to file '/home/missu/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.527" type="debug" -> database: SQLite database connection 'GreaderEntryPoint' to file '/home/missu/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.528" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     0.528" type="debug" -> oauth: User does not want handler to be running.
time="     0.529" type="debug" -> oauth: OAuth redirect handler IS LISTENING on address '127.0.0.1' and port '14488'.
time="     0.529" type="debug" -> core: Filter accepts row '' and filter result is: 'true'.
time="     0.529" type="debug" -> database: SQLite database connection 'GreaderServiceRoot' to file '/home/missu/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.530" type="debug" -> database: SQLite database connection 'RecycleBin' to file '/home/missu/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.531" type="debug" -> database: SQLite database connection 'ImportantNode' to file '/home/missu/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.533" type="debug" -> database: SQLite database connection 'RootItem' to file '/home/missu/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.534" type="critical" -> core: Notification for event '4' not found
time="     0.534" type="debug" -> oauth: Posting data for access token refreshing: 'client_id=1000004453&client_secret=Qe2ZNDfWWXX5kDmQlPh7DGf3aW_W_jxH&refresh_token=972e39a9c2982fe9f4bdbb239f14d3c4ad6db002&grant_type=refresh_token'.
time="     0.536" type="debug" -> database: SQLite database connection 'OwnCloudServiceEntryPoint' to file '/home/missu/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.536" type="debug" -> database: SQLite database connection 'StandardServiceEntryPoint' to file '/home/missu/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.537" type="debug" -> database: SQLite database connection 'TtRssServiceEntryPoint' to file '/home/missu/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.537" type="debug" -> gui: User wants to have tray icon.
time="     0.537" type="warning" -> gui: Showing tray icon with 3000 ms delay.
time="     0.537" type="debug" -> gui: Feed list item expanded - mizzunet (Inoreader)
time="     0.537" type="debug" -> core: Filter accepts row 'Recycle bin' and filter result is: 'true'.
time="     0.537" type="debug" -> core: Filter accepts row 'Important articles' and filter result is: 'true'.
time="     0.538" type="debug" -> core: Filter accepts row 'Unread articles' and filter result is: 'true'.
time="     0.538" type="debug" -> core: Filter accepts row 'Labels' and filter result is: 'true'.
time="     0.538" type="debug" -> gui: Feed list item expanded - Labels
time="     0.538" type="debug" -> core: No execution message received from other app instances.
time="     0.555" type="debug" -> core: Filter accepts row 'mizzunet (Inoreader)' and filter result is: 'true'.
time="     0.555" type="debug" -> core: Filter accepts row 'Labels' and filter result is: 'true'.
time="     0.555" type="debug" -> core: Filter accepts row 'Important articles' and filter result is: 'true'.
time="     0.555" type="debug" -> core: Filter accepts row 'Unread articles' and filter result is: 'true'.
time="     0.555" type="debug" -> core: Filter accepts row 'Recycle bin' and filter result is: 'true'.
time="     0.693" type="warning" -> failed to create compose table
time="     0.707" type="debug" -> gui: Hovered link: 'QUrl()'.
time="     0.788" type="debug" -> gui: Message splitter moved.
time="     1.315" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     1.629" type="debug" -> network: Destroying Downloader instance.
time="     1.629" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="     1.891" type="debug" -> oauth: Token response: '{
    "access_token": "b9f3914bda713d12518b0de1865a692cc9387060",
    "expires_in": 86400,
    "refresh_token": "924c2fc7ea28742b02b987428a1e52e29b41247d",
    "scope": "read write",
    "token_type": "Bearer"
}
'.
time="     1.891" type="debug" -> oauth: Obtained refresh token '924c2fc7ea28742b02b987428a1e52e29b41247d' - expires on date/time 'QDateTime(2022-05-10 17:50:08.679 IST Qt::LocalTime)'.
time="     1.891" type="debug" -> feed-model: There is request to reload feed model, reloading the 1 items individually.
time="     1.891" type="debug" -> core: Filter accepts row 'mizzunet (Inoreader)' and filter result is: 'true'.
time="     1.893" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     3.426" type="debug" -> network: Destroying Downloader instance.
time="     3.426" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="     3.427" type="debug" -> feed-model: There is request to reload feed model, reloading the 5 items individually.
time="     3.427" type="debug" -> core: Filter accepts row 'mizzunet (Inoreader)' and filter result is: 'true'.
time="     3.428" type="debug" -> core: Filter accepts row 'Recycle bin' and filter result is: 'true'.
time="     3.429" type="debug" -> core: Filter accepts row 'mizzunet (Inoreader)' and filter result is: 'true'.
time="     3.429" type="debug" -> core: Filter accepts row 'mizzunet (Inoreader)' and filter result is: 'true'.
time="     3.430" type="debug" -> core: Filter accepts row 'Important articles' and filter result is: 'true'.
time="     3.431" type="debug" -> core: Filter accepts row 'mizzunet (Inoreader)' and filter result is: 'true'.
time="     3.431" type="debug" -> core: Filter accepts row 'mizzunet (Inoreader)' and filter result is: 'true'.
time="     3.432" type="debug" -> core: Filter accepts row 'Unread articles' and filter result is: 'true'.
time="     3.433" type="debug" -> core: Filter accepts row 'mizzunet (Inoreader)' and filter result is: 'true'.
time="     3.433" type="debug" -> core: Filter accepts row 'mizzunet (Inoreader)' and filter result is: 'true'.
time="     3.434" type="debug" -> core: Filter accepts row 'Labels' and filter result is: 'true'.
time="     3.435" type="debug" -> core: Filter accepts row 'mizzunet (Inoreader)' and filter result is: 'true'.
time="     3.435" type="debug" -> core: Filter accepts row 'mizzunet (Inoreader)' and filter result is: 'true'.
time="     3.436" type="debug" -> gui: Feed list item expanded - Recycle bin
time="     3.439" type="debug" -> gui: Feed list item expanded - Important articles
time="     3.440" type="debug" -> gui: Feed list item expanded - Unread articles
time="     3.441" type="debug" -> database: SQLite database connection 'GreaderNetwork' to file '/home/missu/.config/RSS Guard 4/database/database.db' seems to be established.
time="    10.100" type="debug" -> feed-model: There is request to reload feed model, reloading the 1 items individually.
time="    10.100" type="debug" -> core: Filter accepts row 'mizzunet (Inoreader)' and filter result is: 'true'.
time="    10.102" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="    11.545" type="debug" -> network: Destroying Downloader instance.
time="    11.545" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="    11.546" type="debug" -> feed-model: There is request to reload feed model, reloading the 5 items individually.
time="    11.546" type="debug" -> core: Filter accepts row 'mizzunet (Inoreader)' and filter result is: 'true'.
time="    11.548" type="debug" -> core: Filter accepts row 'Recycle bin' and filter result is: 'true'.
time="    11.548" type="debug" -> core: Filter accepts row 'mizzunet (Inoreader)' and filter result is: 'true'.
time="    11.549" type="debug" -> core: Filter accepts row 'mizzunet (Inoreader)' and filter result is: 'true'.
time="    11.550" type="debug" -> core: Filter accepts row 'Important articles' and filter result is: 'true'.
time="    11.550" type="debug" -> core: Filter accepts row 'mizzunet (Inoreader)' and filter result is: 'true'.
time="    11.551" type="debug" -> core: Filter accepts row 'mizzunet (Inoreader)' and filter result is: 'true'.
time="    11.551" type="debug" -> core: Filter accepts row 'Unread articles' and filter result is: 'true'.
time="    11.552" type="debug" -> core: Filter accepts row 'mizzunet (Inoreader)' and filter result is: 'true'.
time="    11.553" type="debug" -> core: Filter accepts row 'mizzunet (Inoreader)' and filter result is: 'true'.
time="    11.554" type="debug" -> core: Filter accepts row 'Labels' and filter result is: 'true'.
time="    11.555" type="debug" -> core: Filter accepts row 'mizzunet (Inoreader)' and filter result is: 'true'.
time="    11.555" type="debug" -> core: Filter accepts row 'mizzunet (Inoreader)' and filter result is: 'true'.
time="    16.770" type="debug" -> feed-downloader: No feeds to update in worker thread, aborting update.
time="    16.770" type="debug" -> feed-downloader: Finished feed updates in thread: '0x7ff14affe640'.
time="    16.775" type="debug" -> CTRL is NOT pressed while sorting articles - sorting with standard mode.
time="    16.777" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, CASE WHEN length(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1 ORDER BY Messages.id DESC;'.
time="    16.778" type="debug" -> gui: Reloading of msg selections took 3 miliseconds.
time="    16.852" type="debug" -> gui: Hovered link: 'QUrl()'.

### Operating system and version

* OS: ArchLinux
* RSS Guard version: 4.2.2

**Comment by martinrotter** [comment]
Does "Test setup" button in inoreader edit dialog produce positive result?

![image](https://user-images.githubusercontent.com/1255302/167550419-0d65afd3-6607-4c82-a92b-d5f04d0eab98.png)

**Comment by martinrotter** [comment]
Also, pls wait until 76912b6d8 compiles and then try with latest devbuild.

https://github.com/martinrotter/rssguard/releases/tag/devbuild

**Comment by martinrotter** [comment]
> I had created a folder in Inoreader from web, and surprisingly, that has reflected in Rssgaurd. ![image](https://user-images.githubusercontent.com/10193999/167631224-5a783807-67e1-446d-83d0-78ac39c1802e.png)
> 
> Though, still feeds aren't loading.
> 
> BTW, do you have Inoreader account working at your end?

Yes.

![image](https://user-images.githubusercontent.com/1255302/167632072-141d21d1-9baf-4843-b69f-9afa8c6e9bf7.png)


OK, if you installed latest devbuild, pls generate new debug log and paste here.

**Comment by martinrotter** [comment]
Yes that is likely the problem.

**Comment by martinrotter** [comment]
Try again with latest devbuild release and DO NOT enter your cliend id/secret (remove all values from those textboxes).

I increased max limits in built-in tokens. Inoreader granted my request and now more users should be able to use those default toknes.

Also, I will add proper error handling so that user know what went wrong.

**Comment by martinrotter** [comment]
Few points:
1. Only official prebuilt binaries include default Inoreader tokens, they are added during build process and are "secret".
2. It is almost always better to use own tokens. If their daily usage quota is not exceeded, they should work.
3. Simply have latest dev. build and test with your own tokens (and make sure point 2 is good).

Honestly, it should just work.
