### ISSUE TITLE
[BUG]: Feedly plugin fetches site URL rather than articles URL

### ISSUE THREAD

**Issue by naabtog** [martinrotter/rssguard#732]
### Brief description of the issue

The name says it all. For some sites most articles have the exact same URL.

### How to reproduce the bug?

1. Fetch articles from Feedly
2. Fetch articles of the same site from standalone ATOM/RSS feed
3. Compare URL fields of articles

### What was the expected result?

Each article has its own URL. That makes sense.

### What actually happened?

See the difference.
<details>
  <summary>Feedly</summary>
  
![rssguard_2MOacJtXxg](https://user-images.githubusercontent.com/76522339/167689452-a8b051fa-9868-46a1-833f-69470398e86e.png)
  
</details>

<details>
  <summary>RSS</summary>
  
![rssguard_iyew0guh33](https://user-images.githubusercontent.com/76522339/167689508-aa8e65ac-795a-458c-aac6-a766092106de.png)
  
</details>

Here's another example.

<details>
  <summary>Feedly</summary>
  
![rssguard_Sw1ByydRoH](https://user-images.githubusercontent.com/76522339/167690272-77bf02db-1018-4ba0-8195-c8b63330c7c2.png)
  
</details>

<details>
  <summary>RSS</summary>
  
![rssguard_EVaMxzD6lK](https://user-images.githubusercontent.com/76522339/167690284-5e4fc1e0-63cb-4332-933e-b82cb27bc89f.png)
  
</details>

### Debug log

[rssguard.log](https://github.com/martinrotter/rssguard/files/8664034/rssguard.log)

### Operating system and version

* OS: Windows 10 Pro 21H2
* RSS Guard version: rssguard-4.2.2-4f2f991b-nowebengine-win64

**Comment by martinrotter** [comment]
I managed to reproduce.
