### ISSUE TITLE
[FR]: Missing "Show unread articles only" from v.4.2.2. Removed on purpose or bug?

### ISSUE THREAD

**Issue by lazypete365** [martinrotter/rssguard#733]
### Brief description of the feature request

Hello,

I have noticed that the "Show unread articles only" option has disappeared completely from the interface on version 4.2.2. At a quick glance I could not find mention of this removal in the changelog, so I am not sure if this feature has been moved elsewhere, if it was removed accidentally during development or if it was removed on purpose for some reason. So I have called this a "feature request", but it could possibly be a bug. In either case it was a pretty useful feature, so it would be very nice to have it back (or at least replaced with something equivalent).

These two screencaps were taken using the same configuration file:

V 4.2.1 Win64
![imagen](https://user-images.githubusercontent.com/9962097/167721452-39a00cda-0c43-4b6f-ad8b-3099e3ba08b5.png)

V 4.2.2 Win64 development build a70fcb66, but it was the same on the 4f2f991b release:
![imagen](https://user-images.githubusercontent.com/9962097/167721797-6a48911d-51e0-4ba8-beaa-8350df21b108.png)

The feature has disappeared completely from the interface, including the toolbar customisation and keyboard shortcuts settings screen. "Show unread items only", on the other hand, is still present and works just fine. The debug log did not seem to show anything different (in particular no obvious gui errors), but I can provide it anyway if necessary.

**Comment by martinrotter** [comment]
https://github.com/martinrotter/rssguard/issues/715
