### ISSUE TITLE
[FR]: Drag-and-drop feature request

### ISSUE THREAD

**Issue by xmstspider** [martinrotter/rssguard#735]
### Brief description of the feature request

Hi,

I am not able to drag&drop articles under different feed, i.e. drag some articles from the view and drop them under different feed in the feed list on left side.

Would it be possible to implement this feature (essentially just enable the drag&drop for article window)?

The reason for this feature request is, I need to move some older items under different feed and I would like to avoid messing with the DB.

Thank you

**Comment by martinrotter** [comment]
This is very unorthodox shit. :D

But yes, technically that is possible. Question is "why"? You could solve this in other ways like assigning some label, or using "Article list filter" dropdown button or simply moving those articles into recycle bin?
