### ISSUE TITLE
[BUG]: issue with filters? filter to remove images not working, even thought test window showed it should

### ISSUE THREAD

**Issue by Owyn** [martinrotter/rssguard#737]
### Brief description of the issue

issue with filters? my filter is not working, even thought test window showed it should

I have two filters for one feed, 1st is a usual whitelist, 2nd is to leave only 1st image and get rid of the rest:
```
function filterMessage() {
  msg.contents = msg.contents.replace('<img>', '<lmg>');
  while (msg.contents.indexOf('<img>') != -1) {
    msg.contents = msg.contents.replace('<img>', '<noimage>');
  }
  msg.contents = msg.contents.replace('<lmg>', '<img>');
  return MessageObject.Accept;
}
```

I tested it on sample article and sample output and it worked fine but for actual feed - all images seem to be intact after it? could you check?)

### How to reproduce the bug?

test feed url: `https://www.asurascans.com/rss`
filter source is above

### What was the expected result?

only 1st image left

### What actually happened?

all images are still there

### Debug log

why does replacing <img> with <noimage> to stop images from displaying not work? what should I do to achieve that?

### Operating system and version

* OS: Win10
* RSS Guard version: 827190c1-nowebengine

P.S. - why is there no `replaceAll` method available and only `replace`? 😱

**Comment by martinrotter** [comment]
Several problems:

There is "replaceAll" - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll

The interpreter supports ECMA "standard".

Also your script is rather "naive" because it cripples the resulting HTML of the article, because you do not seem to convert "end" tags - "</img>" as well.

**Comment by martinrotter** [comment]
Will test in detail tomorrow.

**Comment by Owyn** [comment]
> There is "replaceAll" 
Yea, I tried it first, then checked that my spelling is correct, it says there is no such function
![image](https://user-images.githubusercontent.com/1309656/169889206-01bfb4f0-05cf-4ae4-81ab-c48eacf61fa8.png)

**Comment by Owyn** [comment]
> because you do not seem to convert "end" tags - "" as well.

yea, that's the point - to "break" images and stop them from showing, nothing more 😄

**Comment by martinrotter** [comment]
OK, I checked it.

You cannot search for `<img>` because that substring is not there. The sample message from your feed contains this:

```html
.....
<img loading="lazy" src="https://www.asurascans.com/wp-content/uploads/2022/05/00-207.jpg" alt="" width="1200" height="800" class="alignnone size-full wp-image-100481" />
....
```

**Comment by martinrotter** [comment]
Fixed with this:

```js
function filterMessage() {
  msg.contents = msg.contents.replace('<img', '<lmg');
  msg.contents = msg.contents.replace(/<img/g, '<span');
  msg.contents = msg.contents.replace('<lmg', '<img');

  return MessageObject.Accept;
}
```

**Comment by martinrotter** [comment]
> why is there no replaceAll method available and only replace? 😱

Honestly don't know, but see my example above, you can use "replace" to replace all occurrences too, if first parameter passed is not string but regexp, which can act as a string too.

`'whatever'` -> `/whatever/g` (notice no quotes)

**Comment by Owyn** [comment]
Thank you, for some reason I forgot html isn't bb-code 😄
