### ISSUE TITLE
[FR]: "Find in feedlist" option

### ISSUE THREAD

**Issue by RetroAbstract** [martinrotter/rssguard#740]
### Brief description of the feature request

This option would allow the user to find a feed in their feed list by right clicking on the feed name in the article list and clicking "Find in feed list". RSS Guard would then highlight the feed in the feed list.

**Comment by akinokonomi** [comment]
Sorry, not sure if you are aware, but you can add a "Feeds search box" to the toolbar in a settings: User interface -> Toolbars.

Does it not cover your needs?

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/179386147-14dd7cd2-c850-4353-9709-f918d03e4984.png)

![image](https://user-images.githubusercontent.com/1255302/179386166-c325b693-29fc-430a-9a78-9f6aa02a7267.png)
