### ISSUE TITLE
[FR]: When all articles of a feed have been read, automatically jump to the next feed with unread articles

### ISSUE THREAD

**Issue by fulige18** [martinrotter/rssguard#742]
### Brief description of the feature request

When all articles of a feed have been read, automatically jump to the next feed with unread articles，This is very convenient and user-friendly function。hope it will come true

**Comment by martinrotter** [comment]
There is an action for that. You can assign that to keyboard shorcut and when that action is hit, it automatically goes to next (unread) feed and selects next (unread message).

![image](https://user-images.githubusercontent.com/1255302/170645242-5e7da95b-e57e-466b-8adc-6e299eed12c8.png)
