### ISSUE TITLE
[BUG]:  Custom External Browser doesn't work at all

### ISSUE THREAD

**Issue by catthou** [martinrotter/rssguard#748]
There are multiple issues when the `Use custom external web browser` box is checked.

This command works from my terminal prompt or from a .desktop file:
`/usr/bin/chromium-browser --profile-directory="Profile 1" "https://google.com"`

However, from RSS Guard, with the arguments:
````
Web browser executable: /usr/bin/chromium-browser
Parameters: "%1"
````
I get no error, but my browser opens:
`https://%22https://google.com"` (including that final quotation mark)

And beyond that, with the arguments:
````
Web browser executable: /usr/bin/chromium-browser
Parameters: --profile-directory="Profile 1" "%1"
````
I get the error in terminal:
`[5126:5126:0603/190843.696026:ERROR:profile_manager.cc(908)] Cannot create profile at path /home/haruka/.config/chromium/"Profile 1" "https://google.com"`

So it appears possible that the way these input fields are interpreted isn't working at all.

**Comment by martinrotter** [comment]
Yes, I see it now. Will fix soon.

**Comment by martinrotter** [comment]
Fixing...

**Comment by martinrotter** [comment]
I made a fix: ab68236cb

Can you test with latest development build?

**Comment by catthou** [comment]
It seems to work good now! I tested from chrome closed down, from chrome open but the target profile closed down, and from an open session, and in all 3 scenarios it works as I would expect it to. Well done!

**Comment by martinrotter** [comment]
OK, fixed it is. :)
