### ISSUE TITLE
Locale file names

### ISSUE THREAD

**Issue by luigino** [martinrotter/rssguard#75]
Linux packaging would be a tad easier if locale files had an
underscore instead of a hyphen in their names.
E.g. rssguard-en.ts -> rssguard_en.ts, otherwise they might not
be recognised as l10n.

**Comment by martinrotter** [comment]
How exactly would be Linux packaging easier? Can you put some example here, please? :)

> otherwise they might not be recognised as l10n.

Why?

**Comment by luigino** [comment]
I don't know whether this is a general Qt guideline or not, but when building a separate -lang package, some distros like openSUSE, Fedora, Mageia et al. use the %find_lang macro which fails to identify the locale files when a hyphen instead of an underscore is used as separator (see https://github.com/rpm-software-management/rpm/blob/master/scripts/find-lang.sh#L116).

Regards

**Comment by martinrotter** [comment]
So when you tried to you hyphen, it worked? Does replacing underscores with hyphens do the trick? If so, then I guess I could rename those files.

**Comment by luigino** [comment]
The other way around, but yes. I apply [this patch](https://build.opensuse.org/package/view_file/X11:Utilities/rssguard/rssguard-locale.patch?expand=1) to package rssguard on openSUSE (the path is not relevant though).

**Comment by martinrotter** [comment]
Nice patch!

But why is directory `l10n` renamed to directory `lang`? Is that a change I should include in main rssguard repo too?

**Comment by martinrotter** [comment]
Follow-up: You package RSS Guard "officially" for some distro?

**Comment by luigino** [comment]
Oh no, the path is not important, I just changed it because every other app I encountered used the "lang" folder.

Concerning the rest, I submitted rssguard to be included in the main repository, but these things take time.

By the way, I recently updated the Italian translation on transifex if you want to integrate it.

**Comment by martinrotter** [comment]
> Oh no, the path is not important, I just changed it because every other app I encountered used the "lang" folder.

I see, I could change it too, "lang" is more self-descriptive.

> By the way, I recently updated the Italian translation on transifex if you want to integrate it.

Perfect, I will trigger the sync and push it to repo.

**Comment by luigino** [comment]
Sorry, I still see locale filenames using hyphens instead of underscores.

**Comment by martinrotter** [comment]
You need to check [dev] branch, https://github.com/martinrotter/rssguard/tree/dev

**Comment by luigino** [comment]
Ouch, sorry.
