### ISSUE TITLE
[BUG]: website certificate error not counted as an error - gives blank website contents w "no error"

### ISSUE THREAD

**Issue by Owyn** [martinrotter/rssguard#751]
### Brief description of the issue

website certificate error not counted as an error, instead it says "no errors" and uses blank page as a source

### How to reproduce the bug?

1. find a website with expired\bad ssl cert
or use a dns blocker with a block page enabled (cuz of the redirect a same ssl warning will occur) - e.g. nextdns
e.g.  `http://pulselb.relap.info` (next-dns block - you need to use nextdns and that filter and the blockpage setting on to have it)
![изображение](https://user-images.githubusercontent.com/1309656/173060488-bf42d284-f254-4c39-a495-b1e3d5711e61.png)

2. try to add the website and parse it with RSSGuard 
![изображение](https://user-images.githubusercontent.com/1309656/173060563-5de1eb4d-38b7-4324-9abb-ca3df47d5cff.png)
- it says success and no errors, but doesn't give us page contents - only the favicon

![изображение](https://user-images.githubusercontent.com/1309656/173060850-b8202585-2c77-40f0-94c3-64c5f52a929e.png)

### What was the expected result?

website contents OR at least an "Error" status

### What actually happened?

"" - blank website contents instead of actual contents

### Debug log

[rssguard.log](https://github.com/martinrotter/rssguard/files/8878683/rssguard.log)

### Operating system and version

* OS: Win 10
* RSS Guard version:
Version: 4.2.2 (built on Windows/AMD64)
Revision: 827190c1-nowebengine

**Comment by martinrotter** [comment]
Hi. This would have to be tested on my side with particular URLs.

There is "testing" website for expired cert, can you test?

https://expired.badssl.com/

**Comment by martinrotter** [comment]
Just tested with https://expired.badssl.com/

RSS Guard ignores all "certificate" errors and returns HTML code of the website without problems. So it "works" as I intended, question is if those certificate errors should be ignored or not.

**Comment by martinrotter** [comment]
> For some reason I can get the html of that website just fine with rssguard, but for block-pages done via MITM dns - just a blank page, could you perhaps check nextdns blocked domains block page case?
> 
> > question is if those certificate errors should be ignored or not.
> 
> if you insist - maybe just mark the feed "yellow" as a warning?

Can you give me some sample URL to test?

**Comment by Owyn** [comment]
I've given you a sample URL in the 1st post, you just need to use nextdns as your dns with appropriate settings

**Comment by martinrotter** [comment]
Cannot test as nextdns requires sign up from me (registration) which I do not want to do. Sorry.

**Comment by Owyn** [comment]
> nextdns requires sign up from me (registration) 

No it doesn't.
![image](https://user-images.githubusercontent.com/1309656/174841932-5891c60c-37f7-48c0-be19-df1c9f4513ee.png)

**Comment by martinrotter** [comment]
Just enterint nextdns DNS server IP to my network config as DNS server does not work and does not block the webpage. Not sure if I have to enable somewhere something, moreover this displays.

![image](https://user-images.githubusercontent.com/1255302/174947637-7f5b2229-b00a-48c4-b65e-f445754e3d86.png)

**Comment by Owyn** [comment]
> I have to enable somewhere

Yea, you have, on the "DenyList" manually block a website
![image](https://user-images.githubusercontent.com/1309656/175007501-1912eaf5-c387-4e3f-a3d5-a112b9c48d1d.png)


And in Settings panel enable blockpage
![image](https://user-images.githubusercontent.com/1309656/175007632-b81920ed-befe-46ff-ad52-408afa9c2cfc.png)

**Comment by martinrotter** [comment]
Yes, that's nice but like I said. It requires signup from me. Sorry.

**Comment by Owyn** [comment]
Here's what it responds:
![image](https://user-images.githubusercontent.com/1309656/175012516-8c6e5fa2-2532-4bd1-9df4-39a19f755725.png)

and that's what rssguard gets "0 bytes" page - that's the issue, it doesn't even get the blue "blocked" page

If I click "accept the risk", then yea it's 200 OK and html page, but RSSguard doesn't get that far
![image](https://user-images.githubusercontent.com/1309656/175012788-0506ca4e-4e9e-460f-a434-7b49fb843444.png)
