### ISSUE TITLE
[BUG]: feedburner feeds are rarly avalable to open in system browser

### ISSUE THREAD

**Issue by Motocycle347** [martinrotter/rssguard#753]
### Brief description of the issue

[BUG]: feedburner feeds are rarly avalable to open in system browser

### How to reproduce the bug?

pick feed

### What was the expected result?

https://mashable.com/deals/june-14-anti-spy-camera

### What actually happened?

There has been an error of some kind. Ack!
FeedBurner could not deliver this feed to you because of the specific problem listed below:

Feed Address: http://feeds.feedburner.com/

HTTP Error (Code) and Message: (404) Feed not found error: FeedBurner cannot locate this feed URI.

### Debug log

log not needed

### Operating system and version

* OS:
* RSS Guard version:
os 11` rss 2.2.3

**Comment by martinrotter** [comment]
Hi, I do not understand what is the exact problem. Please re-phrase your ticket and add concise set of steps to reproduce the issue.

**Comment by Motocycle347** [comment]
![selector](https://user-images.githubusercontent.com/15929091/174919144-4b95db26-b694-43d6-9125-a475fadd7d41.png)

Here I demonstrate rhe issue in numbered steps
![selector 2](https://user-images.githubusercontent.com/15929091/174919309-511cffa4-905a-4347-86e0-c3b3c8b30a73.png)

**Comment by martinrotter** [comment]
Give URL of the feed itself pls.

**Comment by martinrotter** [comment]
URL of sample feed not given, closing. Feel free to reopen once you provide URL for testing.
