### ISSUE TITLE
[BUG]: Application not responding

### ISSUE THREAD

**Issue by kvkpls** [martinrotter/rssguard#757]
### Brief description of the issue

Dear Sirs,
I've been using RSS Guard for a long time. I was stuck in version 3.92 due to database inconsistencies with version 4. Today I decided to completely remove version 3.92. I tried using the latest version 4.23 from scratch. However, when I complete installation, the program does not start (There is a blank screen and the sign "RSS guard 4.23 (not responding). I uninstalled, reinstalled, rebooted machine several times with no effect. I tried all versions after 4.00 and seems that the issue started after version 4.12 (i.e. with 4.20). If there is something you can suggest, I would appreciate.

### How to reproduce the bug?

1. Install application
2. When trying to load, application not responding.

### What was the expected result?

Application should have started.

### What actually happened?

Application not responding.

### Debug log

time="     0.016" type="debug" -> core: Initializing settings in 'C:\Users\Θεοδόσης 2\AppData\Local\RSS Guard 4\config\config.ini' (non-portable way).
time="     0.032" type="debug" -> database: File-based SQLite database connection 'DatabaseFactory' to file 'C:\Users\Θεοδόσης 2\AppData\Local\RSS Guard 4\database\database.db' seems to be established.
time="     0.034" type="debug" -> database: File-based SQLite database has version '21'.
time="     0.038" type="debug" -> gui: Available icon theme paths: (:/icons, :/graphics, C:/Users/Θεοδόσης 2/AppData/Local\RSS Guard 4\icons, C:/Program Files/RSS Guard\icons)
time="     0.040" type="debug" -> gui: Installed icon themes are: '', 'Breeze', 'Breeze Dark', 'Faenza', 'Numix'
time="     0.042" type="debug" -> gui: Loading icon theme 'Numix'.
time="     0.044" type="debug" -> gui: Found path of base skin: ':\skins\nudus-base'.
time="     0.045" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_wrapper.html' for the skin.
time="     0.047" type="debug" -> gui: Local file ':\skins\nudus-light\html_style.css' exists, using it for the skin.
time="     0.048" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_enclosure_image.html' for the skin.
time="     0.050" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_single_message.html' for the skin.
time="     0.051" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_enclosure_every.html' for the skin.
time="     0.053" type="debug" -> gui: Local file ':\skins\nudus-light\qt_style.qss' exists, using it for the skin.
time="     0.055" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_adblocked.html' for the skin.
time="     0.057" type="debug" -> gui: Setting style: 'Fusion'.
time="     0.059" type="debug" -> gui: Skin 'nudus-light' loaded.
time="     0.060" type="debug" -> network: Disabling application-wide proxy completely.
time="     0.067" type="debug" -> core: OpenSSL version: 'OpenSSL 1.1.1j  16 Feb 2021'.
time="     0.069" type="debug" -> core: OpenSSL supported: 'true'.
time="     0.071" type="debug" -> core: Starting RSS Guard 4.2.3.
time="     0.073" type="debug" -> core: Instantiated class  'Application'.
time="     0.075" type="debug" -> core: Starting to load active localization. Desired localization is 'el_GR'.
time="     0.077" type="warning" -> core: Application localization 'el_GR' was not loaded. Loading 'en_US' instead.
time="     0.079" type="warning" -> core: Qt localization 'en_US' WAS NOT loaded successfully.
time="     0.085" type="debug" -> database: SQLite database connection 'MessagesModel' to file 'C:/Users/Θεοδόσης 2/AppData/Local/RSS Guard 4/database/database.db' seems to be established.
time="     0.091" type="critical" -> message-model: Error when setting new msg view query: 'no such column: Messages.score Unable to execute statement'.
time="     0.093" type="critical" -> message-model: Used SQL select statement: 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, CASE WHEN length(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1;'.
time="     0.095" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, CASE WHEN length(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1;'.
time="     0.097" type="debug" -> core: Auto-download timer started with interval 60000 ms.
time="     0.099" type="debug" -> core: Creating FeedDownloader singleton.
time="     0.104" type="debug" -> gui: Creating main application form in thread: '0x10dc'.
time="     0.119" type="debug" -> gui: Current row changed - proxy 'QModelIndex(-1,-1,0x0,QObject(0x0))', source 'QModelIndex(-1,-1,0x0,QObject(0x0))'.
time="     0.147" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     0.153" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     0.164" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     0.642" type="debug" -> gui: Creating tray icon menu.
time="     0.701" type="debug" -> core: Showing the main window when the application is starting.
time="     0.739" type="debug" -> database: SQLite database connection 'FeedReader' to file 'C:/Users/Θεοδόσης 2/AppData/Local/RSS Guard 4/database/database.db' seems to be established.
time="     0.746" type="debug" -> database: SQLite database connection 'FeedlyEntryPoint' to file 'C:/Users/Θεοδόσης 2/AppData/Local/RSS Guard 4/database/database.db' seems to be established.
time="     0.751" type="debug" -> database: SQLite database connection 'GmailEntryPoint' to file 'C:/Users/Θεοδόσης 2/AppData/Local/RSS Guard 4/database/database.db' seems to be established.
time="     0.757" type="debug" -> database: SQLite database connection 'GreaderEntryPoint' to file 'C:/Users/Θεοδόσης 2/AppData/Local/RSS Guard 4/database/database.db' seems to be established.
time="     0.762" type="debug" -> database: SQLite database connection 'OwnCloudServiceEntryPoint' to file 'C:/Users/Θεοδόσης 2/AppData/Local/RSS Guard 4/database/database.db' seems to be established.
time="     0.766" type="debug" -> database: SQLite database connection 'StandardServiceEntryPoint' to file 'C:/Users/Θεοδόσης 2/AppData/Local/RSS Guard 4/database/database.db' seems to be established.
time="     0.771" type="warning" -> QSqlQuery::value: unknown field name 'ordr'
time="     0.778" type="warning" -> QSqlQuery::value: unknown field name 'custom_data'
time="     0.781" type="debug" -> core: Filter accepts row 'Θεοδόσης 2 (RSS/ATOM/JSON)' and filter result is: 'true'.
time="     0.784" type="debug" -> database: SQLite database connection 'StandardServiceRoot' to file 'C:/Users/Θεοδόσης 2/AppData/Local/RSS Guard 4/database/database.db' seems to be established.

### Operating system and version

* OS: Windows 10 Home 64bit
* RSS Guard version: 4.2.0-4.2.3

**Comment by martinrotter** [comment]
Hi? Why closed? Issue is resolved?

**Comment by kvkpls** [comment]
Yes, the issue is resolved. The old version database file was retained. After deteting it, everything is OK.
