### ISSUE TITLE
[FR]: Apple Silicon arm64 release

### ISSUE THREAD

**Issue by chromer030** [martinrotter/rssguard#758]
### Brief description of the feature request

Thank you very much for this great and lovely software.
Currently the binary for macOS is just for Intel architecture , please provide Universal Binary or separate arm64 binary too , X86 is going to be deprecated in macOS world.
```
$ ../RSS Guard.app/Contents/MacOS % file rssguard
rssguard: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK|PIE>
```

we need this :
```
Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>] [arm64]
```

**Comment by martinrotter** [comment]
Hi, so far RSS Guard is still built using Qt 5.15 on macosx. This issue will be solvable when I decide to switch to Qt 6.

You can build RSS Guard by yourself however, Qt 6 is supported and you can enable universal binaries easily.

https://www.qt.io/blog/qt-on-apple-silicon

**Comment by martinrotter** [comment]
@chromer030 Pls, test with latest dev-build.

**Comment by chromer030** [comment]
@martinrotter 
Something is wrong , it's not running , the dmg file is only 1.19 MB ! an nothing in macOS folder of app.

**Comment by martinrotter** [comment]
yes, will check it

**Comment by martinrotter** [comment]
any better now?

**Comment by chromer030** [comment]
The build is OK , thank you very much for your efforts 

```
rssguard: Mach-O universal binary with 2 architectures:
[x86_64:Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK|PIE>]
[arm64:Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK|PIE>]
```
