### ISSUE TITLE
[BUG]: annoying name

### ISSUE THREAD

**Issue by al-caveman** [martinrotter/rssguard#762]
### Brief description of the issue

rssguard?  GUARD?  really?  what are you guarding?  

what were you thinking when you picked the name "guard"?  it makes no sense.

anyway.  i'll be making a better rss app than yours.  

also not sure why you're doing it in c++.  why not just do it in QtPy and call it a day?

### How to reproduce the bug?

1. look at rssguard.
2. use your brain.

### What was the expected result?

'guard' must not be in the name.

### What actually happened?

'guard' is in the name.

### Debug log

n/a.

### Operating system and version

* OS: any
* RSS ~~Guard~~ version: any

**Comment by martinrotter** [comment]
Thank you for your kind criticism. Feel free to create better app, you have my blessing.
