### ISSUE TITLE
[FR]: Limit the amount of articles fetched from selected feeds

### ISSUE THREAD

**Issue by RetroAbstract** [martinrotter/rssguard#764]
### Brief description of the feature request

This feature would allow the user to adjust how many articles RSS Guard fetches from a feed.

**The problem:**

Currently, by default when fetching articles from a feed for the first time or fetching articles from a feed after cleaning up the database, 15 (or sometimes more) articles will be fetched and stored in the database.

This isn't a problem for feeds whose articles are always timestamped according to when the article/video was published as you can apply an article filter to only fetch articles after a certain date, however from a feed with all articles having the same time & date attributed to them (time & date based on when RSS Guard fetched them and not from when a new video or article was uploaded/published) when initially fetched or fetched after cleaning up the database, this becomes a problem.

![1](https://user-images.githubusercontent.com/103272301/178261683-ce207917-3d08-4838-bde7-218de16e48f4.jpg)

In this case with [Invidious](https://github.com/iv-org/invidious) feeds, this results in every feed having 15 articles by default if one wants to fetch videos from them. This makes the database very bloated.

Note that this only happens when fetching articles from a feed for the first time or fetching articles after cleaning up the database, fetching articles from an Invidious feed or any other feed with the problem mentioned above with those 15 initial articles stored in the DB will result in articles/videos fetched with the time of publication as timestamp, not when being fetched.

A feature to limit how many articles are fetched from selected feeds would allow standard RSS/ATOM/JSON account users to keep their DB light & trimmed.

Would be located in "Feeds & articles > Feed fetching".

**Comment by martinrotter** [comment]
Few things.

* Post URL of the affected feeds here. This can very well be error in feed parsing in RSS Guard and date/times are not parsed correctly.
* Yes, RSS Guard just fetches all entries available online in the feed, which is to be expected.
* Yes, general per-feed (?) option to limit amount of messages somehow, would be good to have - either comfortably via article filters feature or via GUI option in "edit feed" dialog.

**Comment by RetroAbstract** [comment]
> Few things.
> 
>     * Post URL of the affected feeds here. This can very well be error in feed parsing in RSS Guard and date/times are not parsed correctly.
> 
>     * Yes, RSS Guard just fetches all entries available online in the feed, which is to be expected.
> 
>     * Yes, general per-feed (?) option to limit amount of messages somehow, would be good to have - either comfortably via article filters feature or via GUI option in "edit feed" dialog.

- All feeds URLs from Invidious are affected by this, I've tested on multiple instances. (Feed URL template: https://invidious.snopyta.org/feed/channel/[CHANNEL ID] , feed URL used in example: https://invidious.snopyta.org/feed/channel/UCXuqSBlHAE6Xw-yeJA0Tunw)
- Yes.
- Giving options to apply a limit to:

1. All feeds in "Settings > Feeds & Articles > Feed Fetching > Limit amount of articles fetched from all feeds: X"
2. Selected feeds by right clicking a feed > "Edit selected item > Miscellaneous > Limit amount of articles fetched from this feed: X"
3. All feeds within a feed category by right clicking a feed category > "Edit selected item > Miscellaneous > Limit amount of articles fetched from feeds within this category: X"

Would be great. This would cover a broad amount of scenarios in which users would want to limit how many articles RSS Guard fetches from feeds.

**Comment by martinrotter** [comment]
I do not get what you mean by "fetching a video". RSS Guard does not really fetch any "video" during feed downloading. 15 messages cannot really "bloat" your DB.

**Comment by RetroAbstract** [comment]
> I do not get what you mean by "fetching a video". RSS Guard does not really fetch any "video" during feed downloading. 15 messages cannot really "bloat" your DB.

@martinrotter I meant to say fetching an article.

If you would only have 1 channel in your feed list that would always have 15 messages all the time that wouldn't be an issue. However when there's hundreds (500+) of channels in your feed list, each having thumbnails in every article fetched, in my experience RSS Guard feels sluggish.

My suggestion in my previous comment:

>    Giving options to apply a limit to:
>
>1. All feeds in "Settings > Feeds & Articles > Feed Fetching > Limit amount of articles fetched from all feeds: X"
>2. Selected feeds by right clicking a feed > "Edit selected item > Miscellaneous > Limit amount of articles fetched from this feed: X"
>3. All feeds within a feed category by right clicking a feed category > "Edit selected item > Miscellaneous > Limit amount of articles fetched from feeds within this category: X"

Would be great.

**Comment by LiohMoeller** [comment]
This feature would be amazing. I have subscribed to several Podcast Feeds with about 2000 items each and the application gets really slow like that. Having the ability to just fetch the latest 100 items would be great.

**Comment by martinrotter** [comment]
This is now kind of possible with #1270, closing this
