### ISSUE TITLE
[BUG]: Old items keep coming back as new for Youtube Feeds

### ISSUE THREAD

**Issue by ThomasWeber** [martinrotter/rssguard#767]
### Brief description of the issue

When following a youtube RSS feed, old videos, sometimes very old ones already marked as read, can come back and show as new. The date in the app will show as the current day, but if you go to the actual video it still has the old date.

This doesn't happen with other RSS clients I've tried, and only seems to happen for me with youtube feeds. 

Thanks!

### How to reproduce the bug?

1. Add a youtube rss feed, example: https://www.youtube.com/feeds/videos.xml?channel_id=UCXuqSBlHAE6Xw-yeJA0Tunw
2. Mark videos as read
3. Wait and eventually old videos will start showing as new again.

### What was the expected result?

The dead should stay dead

### What actually happened?

Zombies

### Debug log

 time="     0.170" type="debug" -> core: Initializing settings in 'E:\progs\RSS Guard\data4\config\config.ini' (portable way).
time="     0.545" type="debug" -> database: File-based SQLite database connection 'DatabaseFactory' to file 'E:\progs\RSS Guard\data4\database\database.db' seems to be established.
time="     0.545" type="debug" -> database: File-based SQLite database has version '2'.
time="     0.547" type="debug" -> gui: Available icon theme paths: (:/icons, :/graphics, E:/progs/RSS Guard\data4\icons, E:/progs/RSS Guard\icons)
time="     0.547" type="debug" -> gui: Installed icon themes are: '', 'Breeze', 'Breeze Dark', 'Faenza', 'Numix'
time="     0.548" type="debug" -> gui: Loading icon theme 'Numix'.
time="     0.548" type="warning" -> gui: Failed to load skin 'dark'.
time="     0.548" type="debug" -> gui: Found path of base skin: ':\skins\nudus-base'.
time="     0.548" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_wrapper.html' for the skin.
time="     0.548" type="debug" -> gui: Local file ':\skins\nudus-light\html_style.css' exists, using it for the skin.
time="     0.549" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_enclosure_image.html' for the skin.
time="     0.549" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_single_message.html' for the skin.
time="     0.549" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_enclosure_every.html' for the skin.
time="     0.549" type="debug" -> gui: Local file ':\skins\nudus-light\qt_style.qss' exists, using it for the skin.
time="     0.549" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_adblocked.html' for the skin.
time="     0.549" type="debug" -> gui: Setting style: 'Fusion'.
time="     0.550" type="debug" -> gui: Skin 'nudus-light' loaded.
time="     0.550" type="debug" -> network: Persistent web data storage path: 'E:/progs/RSS Guard\data4\web\storage'.
time="     0.550" type="debug" -> network: Disabling application-wide proxy completely.
time="     0.553" type="debug" -> core: OpenSSL version: 'OpenSSL 1.1.1j  16 Feb 2021'.
time="     0.553" type="debug" -> core: OpenSSL supported: 'true'.
time="     0.553" type="debug" -> core: Starting RSS Guard 4.2.3.
time="     0.554" type="debug" -> core: Instantiated class  'Application'.
time="     0.554" type="debug" -> core: Starting to load active localization. Desired localization is 'en_US'.
time="     0.554" type="debug" -> core: Application localization 'en_US' loaded successfully, specifically sublocalization 'en_US' was loaded.
time="     0.554" type="warning" -> core: Qt localization 'en_US' WAS NOT loaded successfully.
time="     0.558" type="debug" -> database: SQLite database connection 'MessagesModel' to file 'E:/progs/RSS Guard/data4/database/database.db' seems to be established.
time="     0.561" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, CASE WHEN length(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1;'.
time="     0.561" type="debug" -> core: Auto-download timer started with interval 60000 ms.
time="     0.561" type="debug" -> core: Creating FeedDownloader singleton.
time="     0.562" type="debug" -> core: Requesting update for all feeds on application startup.
time="     0.564" type="debug" -> gui: Creating main application form in thread: '0x69dc'.
time="     0.571" type="debug" -> gui: Current row changed - proxy 'QModelIndex(-1,-1,0x0,QObject(0x0))', source 'QModelIndex(-1,-1,0x0,QObject(0x0))'.
time="     0.587" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     0.622" type="debug" -> gui: Creating tray icon menu.
time="     0.742" type="debug" -> core: Hiding the main window when the application is starting.
time="     0.742" type="debug" -> database: SQLite database connection 'FeedReader' to file 'E:/progs/RSS Guard/data4/database/database.db' seems to be established.
time="     0.743" type="debug" -> database: SQLite database connection 'FeedlyEntryPoint' to file 'E:/progs/RSS Guard/data4/database/database.db' seems to be established.
time="     0.744" type="debug" -> database: SQLite database connection 'GmailEntryPoint' to file 'E:/progs/RSS Guard/data4/database/database.db' seems to be established.
time="     0.744" type="debug" -> database: SQLite database connection 'GreaderEntryPoint' to file 'E:/progs/RSS Guard/data4/database/database.db' seems to be established.
time="     0.745" type="debug" -> database: SQLite database connection 'OwnCloudServiceEntryPoint' to file 'E:/progs/RSS Guard/data4/database/database.db' seems to be established.
time="     0.745" type="debug" -> database: SQLite database connection 'StandardServiceEntryPoint' to file 'E:/progs/RSS Guard/data4/database/database.db' seems to be established.
time="     0.747" type="debug" -> core: Filter accepts row 'user (RSS/ATOM/JSON)' and filter result is: 'true'.
time="     0.748" type="debug" -> database: SQLite database connection 'StandardServiceRoot' to file 'E:/progs/RSS Guard/data4/database/database.db' seems to be established.
time="     0.749" type="debug" -> core: Custom ID of feed when loading from DB is '1'.
time="     0.749" type="debug" -> database: SQLite database connection 'RecycleBin' to file 'E:/progs/RSS Guard/data4/database/database.db' seems to be established.
time="     0.750" type="debug" -> database: SQLite database connection 'ImportantNode' to file 'E:/progs/RSS Guard/data4/database/database.db' seems to be established.
time="     0.750" type="debug" -> database: SQLite database connection 'RootItem' to file 'E:/progs/RSS Guard/data4/database/database.db' seems to be established.
time="     0.751" type="debug" -> database: SQLite connection 'StandardServiceRoot' is already active.
time="     0.751" type="debug" -> database: SQLite database connection 'StandardServiceRoot' to file 'E:/progs/RSS Guard/data4/database/database.db' seems to be established.
time="     0.751" type="debug" -> database: SQLite database connection 'TtRssServiceEntryPoint' to file 'E:/progs/RSS Guard/data4/database/database.db' seems to be established.
time="     0.752" type="debug" -> gui: User wants to have tray icon.
time="     0.752" type="debug" -> gui: Tray icon is available, showing now.
time="     0.754" type="debug" -> gui: Creating SystemTrayIcon instance.
time="     0.772" type="debug" -> gui: Showing tray icon immediately.
time="     0.829" type="debug" -> gui: Tray icon displayed.
time="     0.829" type="debug" -> gui: Feed list item expanded - user (RSS/ATOM/JSON)
time="     0.829" type="debug" -> core: Filter accepts row 'Recycle bin' and filter result is: 'true'.
time="     0.829" type="debug" -> core: Filter accepts row 'Important articles' and filter result is: 'true'.
time="     0.830" type="debug" -> core: Filter accepts row 'Unread articles' and filter result is: 'true'.
time="     0.830" type="debug" -> core: Filter accepts row 'Labels' and filter result is: 'true'.
time="     0.830" type="debug" -> core: Filter accepts row 'Linus Tech Tips' and filter result is: 'true'.
time="     0.830" type="debug" -> gui: Feed list item expanded - Labels
time="     0.830" type="debug" -> core: No execution message received from other app instances.
time="     0.929" type="debug" -> gui: Hovered link: 'QUrl()'.
time="     0.929" type="debug" -> core: Silencing GUI message: ''.
time="     1.553" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     2.851" type="debug" -> network: Destroying Downloader instance.
time="     2.851" type="debug" -> network: Destroying SilentNetworkAccessManager instance.

### Operating system and version

* OS: Windows 11 and Arch Linux
* RSS Guard version: 4.2.3

**Comment by martinrotter** [comment]
Yes, this is known issue and is only specific to Youtube feeds. Those feeds sometimes weirdly change date/time of their entries, leading RSS Guard to think that the entry changed, thus updating it in internal DB and marking unread.

I do not want to make any program-wide fixes because this is youtube-specific stuff and also can be easily fixed with custom article filter (which is exactly use case article filters are useful for). See below for sample article filter to fix the issue.

![image](https://user-images.githubusercontent.com/1255302/178897889-55fe415b-5bad-4de9-a58d-0781b5b78a94.png)

```js
function filterMessage() {
  if (msg.isAlreadyInDatabase(MessageObject.SameCustomId)) {
    return MessageObject.Ignore;
  }
  else {
    return MessageObject.Accept;
  }
}
```

This filter only accepts new articles for the feed, ignoring all article changes and effectively fixing your problem. See screenshot for related info, simply check feed you want and that's it. Article filters are automatically evaluated each time feed is fetched.
