### ISSUE TITLE
[FR]: Unmark files marked for deletion

### ISSUE THREAD

**Issue by xmstspider** [martinrotter/rssguard#771]
### Brief description of the feature request

Hi,

by mistake, I marked some files as Deleted (Shift-Del) instead of Read. I did not find any way how:

1. Unmark them so they won't be deleted.
2. Re-fetch them again after the articles have been deleted.

Any tips/hints?

Thank you

**Comment by martinrotter** [comment]
If you "delete" articles, they are moved to recycle bin.

You can "restore" articles when you open recycle bin and select and right click them or you can restore whole bin by right clicking bin.
