### ISSUE TITLE
[BUG]: App not opening when clicking on the taskbar's icon

### ISSUE THREAD

**Issue by pokemaster974** [martinrotter/rssguard#773]
### Brief description of the issue

RSS Guard opens on startup
When I click on the RSS Guard's icon on the taskbar, it won't open it.
If I click on the RSS Guard's icon on the tray areo, it will open

### How to reproduce the bug?

1. Open RSS Guard
2. Pin if not already pinned RSS Guard into the taskbar
3. Click on RSS Guard's icon

### What was the expected result?

Opening the window of RSS Guard

### What actually happened?

Nothing

### Debug log

time="    47.085" type="debug" -> gui: Reloading of msg selections took 1 miliseconds.
time="    47.125" type="debug" -> gui: Hovered link: 'QUrl()'.
time="    55.520" type="debug" -> gui: Main window's close event
time="    55.536" type="debug" -> gui: Main window's hide event
time="    58.004" type="debug" -> gui: Main window's close event
time="    58.017" type="debug" -> gui: Main window's hide event
time="    61.494" type="debug" -> core: Starting auto-download event, remaining 59 minutes out of 60 total minutes to next global feed update.
time="    65.319" type="debug" -> core: Cleaning up resources and saving application state.
time="    65.320" type="debug" -> core: Close lock was obtained safely.
time="    65.320" type="debug" -> feed-downloader: Destroying FeedDownloader instance.
time="    65.391" type="debug" -> gui: Destroying FormMain instance.
time="    65.398" type="debug" -> gui: Destroying TabWidget instance.
time="    65.398" type="debug" -> gui: Destroying FeedMessageViewer instance.
time="    65.399" type="debug" -> gui: Destroying BaseToolBar instance.
time="    65.426" type="debug" -> gui: Destroying MessagesView instance.
time="    65.427" type="debug" -> gui: Destroying BaseToolBar instance.
time="    65.427" type="debug" -> gui: Destroying FeedsView instance.
time="    65.428" type="debug" -> gui: Destroying TabBar instance.
time="    65.429" type="debug" -> gui: Destroying StatusBar instance.
time="    65.431" type="debug" -> gui: Destroying SystemTrayIcon instance.
time="    65.481" type="debug" -> core: Destroying Application instance.
time="    65.481" type="debug" -> core: Destroying Mutex instance.
time="    65.640" type="debug" -> gui: Destroying IconFactory instance.
time="    65.640" type="debug" -> core: Destroying FeedReader instance.
time="    65.641" type="debug" -> feed-model: Destroying FeedsModel instance.
time="    65.642" type="debug" -> oauth: Destroying OAuth2Service instance.
time="    65.642" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="    65.642" type="debug" -> feed-model: Destroying FeedsProxyModel instance
time="    65.643" type="debug" -> message-model: Destroying MessagesModel instance.
time="    65.643" type="debug" -> message-model: Destroying MessagesProxyModel instance.

### Operating system and version

* OS: Windows 10
* RSS Guard version: 4.2.3

**Comment by martinrotter** [comment]
can you perhaps post video?

also, can you do screenshot of settings->gui->try section?

**Comment by pokemaster974** [comment]
@martinrotter Hoping that this gif will explain better the issue :
![asEeTgvADq](https://user-images.githubusercontent.com/28442699/186446729-66c37b1c-8400-4ce6-a258-830e4d554461.gif)

**Comment by martinrotter** [comment]
Thing is that when you pin icon to taskbar, the icon is not really part of "alive" application and is mean to "start" next instance of the application.

I disovered related bug there, but will check.

**Comment by pokemaster974** [comment]
> Thing is that when you pin icon to taskbar, the icon is not really part of "alive" application and is mean to "start" next instance of the application.
> 
> I disovered related bug there, but will check.

So there isn't any "fix" possible ? Thing is that this situation (not opening when clicking) only for RSS Guard.

Regards.

**Comment by martinrotter** [comment]
there is a fix possible, likely, will try to come with one

**Comment by martinrotter** [comment]
> > Thing is that when you pin icon to taskbar, the icon is not really part of "alive" application and is mean to "start" next instance of the application.
> > I disovered related bug there, but will check.
> 
> So there isn't any "fix" possible ? Thing is that this situation (not opening when clicking) only for RSS Guard.
> 
> Regards.

Can you please try with LATEST development build?

**Comment by martinrotter** [comment]
I think I now properly fixed this: 89a77315b

**Comment by pokemaster974** [comment]
Confirmed that it works ont 4.2.5.
Thanks !
