### ISSUE TITLE
[BUG]: Empty opml when noty exporting all feeds (local account)

### ISSUE THREAD

**Issue by xfzv** [martinrotter/rssguard#774]
### Brief description of the issue

My feeds from my local account are organized in several categories.

### How to reproduce the bug?

- When I export all the feeds from all the categories, no issue.
- When I export all the feeds from one category (any of them) and a few other feeds from other categories, no issue.
- However, when I export only a few feeds from any category (can be 9 feeds out of 10, the issue occurs as long as they're not all selected), with or without any additional feed from another category, then the exported opml file is empty with the following content:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<opml version="2.0" xmlns:rssguard="https://github.com/martinrotter/rssguard">
  <head>
    <title>RSS Guard</title>
    <dateCreated>Sun, 14 Aug 2022 20:32:17 GMT</dateCreated>
  </head>
  <body/>
</opml>
```

### What was the expected result?

The opml file should contain the feeds I want to export without having to select a whole category.

### What actually happened?

The exported opml file is empty with the following content:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<opml version="2.0" xmlns:rssguard="https://github.com/martinrotter/rssguard">
  <head>
    <title>RSS Guard</title>
    <dateCreated>Sun, 14 Aug 2022 20:32:17 GMT</dateCreated>
  </head>
  <body/>
</opml>
```

### Debug log

Nothing related to the issue appears with:

```bash
% rssguard --log /path/to/log/file.log`
```

### Operating system and version

* OS: Gentoo
* RSS Guard version: 4.2.3

**Comment by akinokonomi** [comment]
Can confirm it with the default feed list.

Checking to export the whole category "Technology" works fine, but when I uncheck a single feed in there, for example NYT, RSS Guard exports an empty OPML file without any feeds.

**Comment by martinrotter** [comment]
Fixed, check if fix works. :)

**Comment by xfzv** [comment]
> Fixed, check if fix works. :)

All good now with `rssguard-devbuild-65e232d2-nowebengine-win64.exe` here.

Thank you!
