### ISSUE TITLE
[BUG]: RSSGuard Crash on Windows 10 21H1

### ISSUE THREAD

**Issue by joseashb** [martinrotter/rssguard#776]
### Brief description of the issue

RSSGuard crashes multiple times.
I tried clean install but issue persist

`Faulting application name: QuiteRSS.exe, version: 0.19.4.3937, time stamp: 0x602ffb0d
Faulting module name: libstdc++-6.dll, version: 0.0.0.0, time stamp: 0x0000b000
Exception code: 0x40000015
Fault offset: 0x0002085d
Faulting process id: 0x2020
Faulting application start time: 0x01d8af3994304a5c
Faulting application path: C:\Program Files (x86)\QuiteRSS\QuiteRSS.exe
Faulting module path: C:\Program Files (x86)\QuiteRSS\libstdc++-6.dll
Report Id: da48eca8-01a0-415e-bf10-ccecbd18510e
Faulting package full name: 
Faulting package-relative application ID: `

### How to reproduce the bug?

1. Open app
2. Use and wait until it crashes by itself
3. Restart app

### What was the expected result?

App not to crash

### What actually happened?

App crashes

### Debug log

Faulting application name: QuiteRSS.exe, version: 0.19.4.3937, time stamp: 0x602ffb0d
Faulting module name: libstdc++-6.dll, version: 0.0.0.0, time stamp: 0x0000b000
Exception code: 0x40000015
Fault offset: 0x0002085d
Faulting process id: 0x2020
Faulting application start time: 0x01d8af3994304a5c
Faulting application path: C:\Program Files (x86)\QuiteRSS\QuiteRSS.exe
Faulting module path: C:\Program Files (x86)\QuiteRSS\libstdc++-6.dll
Report Id: da48eca8-01a0-415e-bf10-ccecbd18510e
Faulting package full name: 
Faulting package-relative application ID: 

### Operating system and version

* OS: Windows 10 21H1 updated
* RSS Guard version: 4.2.3

**Comment by akinokonomi** [comment]
> Faulting application name: **QuiteRSS.exe**, version: 0.19.4.3937, time stamp: 0x602ffb0d
Faulting module name: libstdc++-6.dll, version: 0.0.0.0, time stamp: 0x0000b000
Exception code: 0x40000015
Fault offset: 0x0002085d
Faulting process id: 0x2020
Faulting application start time: 0x01d8af3994304a5c
Faulting application path: C:\Program Files (x86)\QuiteRSS\QuiteRSS.exe
Faulting module path: C:\Program Files (x86)\QuiteRSS\libstdc++-6.dll

> RSSGuard crashes multiple times.


Are you sure that *RSS Guard* is the name of application that crashes?

**Comment by martinrotter** [comment]
Apparently this belongs to some other repo.
