### ISSUE TITLE
Images in post preview are not displayed

### ISSUE THREAD

**Issue by TomaszGasior** [martinrotter/rssguard#78]
#### Brief description of the issue.

In preview of post from RSS images are not displayed. Instead application displays placeholder, small icon with blank piece of paper. 
But if image contains inline css with height or width, it uses it.

#### How to reproduce the bug?

Use this RSS for example: http://feeds.feedburner.com/wpzen
Try to open post with embedded images.

#### What is the expected result?

image placeholder does not use CSS width/height
OR
remove image placeholder
OR
allow to show images in preview

See screenshot: http://i.imgur.com/RlcxY3W.png

**Comment by martinrotter** [comment]
That is because you use RSS Guard light version compiled without QtWebEngine module. This version does not use full HTML/CSS rendering engine. It uses simpler and faster text-based component. You need to compile/install RSS Guard with will QtWebEngine support.

**Comment by TomaszGasior** [comment]
I have installed QtWebEngine in my OS. Should I do more?

**Comment by martinrotter** [comment]
Which distro you have and which package with RSS Guard did you install?

RSS Guard needs to be specifically compiled with QtWebEngine support enabled. If QtWebEngine is installed WHEN RSS GUARD IS COMPILED, it is automatically detected and enabled. So the detection of QtWebEngine is done during COMPILATION, not during applicaiton run-time.

**Comment by martinrotter** [comment]
OK, this seems as not out bug. This is probably packaging/installation issue. closing.
