### ISSUE TITLE
[BUG]: Doesn't download any content when using "Google Reader API" With "Miniflux"

### ISSUE THREAD

**Issue by arran4** [martinrotter/rssguard#780]
### Brief description of the issue

When you setup Miniflux as a "Google Reader API" account type:
![image](https://user-images.githubusercontent.com/111667/185840061-d0ff4e05-67de-494c-b217-e798e62eb22b.png)

![image](https://user-images.githubusercontent.com/111667/185840073-eea76389-bd96-4e75-8332-e93163b8478a.png)

With any settings (default or otherwise)

it fails:

![Uploading image.png…]()

### How to reproduce the bug?

1. Install or use an existing Miniflux deployment
2. Enable Google Reader API in Miniflux
![image](https://user-images.githubusercontent.com/111667/185840157-d0288950-147c-4794-a794-3387f4df2b5e.png)

3. Add API endpoint to RSS Guard
4. Refresh feeds

### What was the expected result?

For it to list the feeds and the content of the feeds

### What actually happened?

It only list the feeds, it doesn't fetch the content.

### Debug log

n/a

### Operating system and version

* OS: Ubuntu
* RSS Guard version:
![image](https://user-images.githubusercontent.com/111667/185840282-d4c86897-92c4-47df-a59d-159e9269ce03.png)

![image](https://user-images.githubusercontent.com/111667/185840316-67999461-dc2d-4e40-892b-7fb2401e71c0.png)

**Comment by martinrotter** [comment]
hi @arran4 i will install miniflux with docker and test thanks

**Comment by arran4** [comment]
Thanks.

**Comment by martinrotter** [comment]
OK, so, RSS Guard supports two modes of function. Luckily for you, faster approach is supported by miniflux and slower is not, which is quite unusual. Slower approach is not implemented yet.

I made changes to RSS Guard to take this into account and fixed some related bugs on my side.

Check screenshot below:
1. Make sure that "Miniflux" is selected as "Service".
2. Make sure that the red rectangled checkbox is checked.

![image](https://user-images.githubusercontent.com/1255302/185867418-590569eb-9f7e-4edf-836c-50e25b773e74.png)

35e9f299a

Once miniflux fixes missing functionality upstream, then the checkbox won't matter.

**Comment by arran4** [comment]
Thanks again for the quick analysis and fix.

**Comment by arran4** [comment]
Are there binaries or do I need to compile myself?

**Comment by martinrotter** [comment]
https://github.com/martinrotter/rssguard/releases/tag/devbuild

**Comment by arran4** [comment]
Cool. It pulls down the content fine now! However it doesn't seem to get the read / unread status.

**Comment by martinrotter** [comment]
I see, will check tomorrow.

**Comment by arran4** [comment]
No worries. Thanks.

**Comment by martinrotter** [comment]
OK, should be fixed.

f0904b21c

**Comment by arran4** [comment]
Thanks testing: [rssguard-devbuild-772aa7da-linux64.AppImage](https://github.com/martinrotter/rssguard/releases/download/devbuild/rssguard-devbuild-772aa7da-linux64.AppImage)

**Comment by arran4** [comment]
![image](https://user-images.githubusercontent.com/111667/187027320-35ced4df-a966-404e-9633-9727e2ee0dfa.png)

Interesting it doesn't detect version differences?

**Comment by arran4** [comment]
![image](https://user-images.githubusercontent.com/111667/187027568-5afc44c5-4bad-4554-b8b2-d5687dc1484b.png)

![image](https://user-images.githubusercontent.com/111667/187027571-4a883efe-3f72-42b1-8029-039d020f4203.png)

I presume that's wrong.. Perhaps I misunderstood / imagined the feature?

Tried on both:
![image](https://user-images.githubusercontent.com/111667/187027598-1d512fd5-86e4-426c-a42b-313c277cec28.png)

**Comment by martinrotter** [comment]
if you change message state in rssguard, the change is propagated to miniflux server with up to 60 seconds delay!

i just tested and both way message state synchronization does work

**Comment by arran4** [comment]
Ah Okay. I see. It seems to not work on blacklog items. Marking as read works both ways the first time. However subsequent times it seems to have trouble with me marking it as unread in miniflux, rssguard doesn't seem to pick that up.

**Comment by arran4** [comment]
Marking everything as read (a couple feeds but a 2 year backlog), then forcing a sync seems to cause sync issues where it pushes invalid read states back to miniflux

**Comment by arran4** [comment]
But.. Eventually corrects....

**Comment by martinrotter** [comment]
> But.. Eventually corrects....

That would somehow need maybe more debugging. Hard to say, also printscreen your acc settings dialog in rss guard and share here.

**Comment by arran4** [comment]
Okay, sorry about the sheer number of pictures... I also cleared out the account and recreated it each time which would trigger this.. (I didn't delete the sqlite db however.) 

Everything is currently "marked as read correctly." I will keep you up to date on that. I suspect this is probably a threading issue so possibly state management for concurrent jobs?

[Pictures.zip](https://github.com/martinrotter/rssguard/files/9437915/Pictures.zip)

The feed I'm testing with it is:
https://www.youtube.com/feeds/videos.xml?channel_id=UCVgO39Bk5sMo66-6o6Spn6Q
However I don't think you can get the amount of data I have. (Happy to export it if you let me know how.)

**Comment by arran4** [comment]
"Marking selected item as read" a whole folder caused them all to be marked unread:
![image](https://user-images.githubusercontent.com/111667/187100642-94484e93-e992-49d7-853f-ea64eb8e94b9.png)

Initially only 2 items were unread.

**Comment by arran4** [comment]
Actually looks like they were actually marked as read:
![image](https://user-images.githubusercontent.com/111667/187100711-2541bf87-e48c-4760-84f7-9e863c64151d.png)

So effectively the whole "folder" of feeds marked as read status was toggled. (I waited 30 mins.)
