### ISSUE TITLE
[FR]: Set custom directory where RSS Guards stores and refers to all user data

### ISSUE THREAD

**Issue by RetroAbstract** [martinrotter/rssguard#781]
### Brief description of the feature request

This feature would allow the user to set a custom directory where RSS Guard stores and refers to all user data.

Currently RSS Guard portable builds will first check and see if an "RSS Guard 4" folder is present in 'AppData/Local/' and load all the user data in there when booted up, which results in having to move the already existing RSS Guard 4 folder made by an installed version of RSS Guard out of there if you wish to try out portable development builds of RSS Guard without mixing your data with them.

Reason for this feature: Ability to conveniently use separatlely an installed stable RSS Guard and RSS Guard Portable Development builds.

**Comment by martinrotter** [comment]
This is already possible, run rssguard with parameter "--help" for more info
