### ISSUE TITLE
[BUG]: Persist 'sort [feed folders] alphabetically' across restarts

### ISSUE THREAD

**Issue by umbellipher** [martinrotter/rssguard#784]
### Brief description of the issue

1) 'Sort [feed folders] alphabetically' doesn't persist across restarts (and perhaps after minimize/maximize).

2) The 'sort' button has to be selected twice for it to take effect.

### How to reproduce the bug?

Open app.
Sync.
Sort alphabetically.
Sort alphabetically again, so that it takes effect.
Restart (or perhaps merely minimize/maximize).
Feed folders in random order.

### What was the expected result?

Expected persistence of alphabetical sorting across retart.

### What actually happened?

No persistence.

### Debug log

[Uploading rssguard.log…]()

### Operating system and version

* OS: Windows 10 Pro
* RSS Guard version: 605c1b0

**Comment by martinrotter** [comment]
yes, there is some catch, will look into it

**Comment by martinrotter** [comment]
it is expected to be persistent of course, but there seems to be some problem

**Comment by martinrotter** [comment]
ok, i found bugs related to this, fixed and tested, works now, pls test

cc014dc1d

**Comment by umbellipher** [comment]
Appears to have resolved, both. Thanks.
