### ISSUE TITLE
[FR]: rssguard web interface

### ISSUE THREAD

**Issue by pipiscrew** [martinrotter/rssguard#786]
### Brief description of the feature request

a 30m project, using the **php.exe** builtin development server to display the feeds from **rssguard** sqlite dbase.

https://github.com/pipiscrew/small_prjs/tree/master/php_rssguard_web

![2022-08-28_225402](https://user-images.githubusercontent.com/3852762/187094094-6c8f0e41-d6cd-4328-b73d-1dbba4a6cb05.png)

**CSS** by hackernews-minimal.herokuapp.com

**Comment by martinrotter** [comment]
@pipiscrew 

Well, what a nice little project we have here. Good job. Do you have any specific requests for me?

**Comment by pipiscrew** [comment]
hi @martinrotter,

I would like to request the same for **rssguard** GUI, by that means a new button 
![2022-08-29_074558](https://user-images.githubusercontent.com/3852762/187131364-5d0a40b4-da90-4cc3-9bf2-a379ac6f7715.png)

now when the user has something selected on treeview and press the /web view/ the **listview** replaced by the a **webview** and display the threads. Here possible you have to limit the records shown to 500... As on my php example, otherwise will take ages to be displayed... In the end will be like

![2022-08-29_074713b](https://user-images.githubusercontent.com/3852762/187132011-001c5a48-9db8-4460-a162-91e834b0be94.png)

for sure more easy to read vs listview.. 

in that way you bring the **rssguard** to 21st century!!

ps : you have to hook the the http/https request from /web view/ and open it to /external browser/ as configured on rssguard settings.

**Comment by martinrotter** [comment]
@pipiscrew 

Let me be completely honest and I am no personal offence.

>for sure more easy to read vs listview..
For some people maybe, but for majority of people using rssguard, this is not what is "more easy". You are actually the first one to request such a feature. Moreover, there is "newspaper" view which is greatly extensible via "skinning" feature and can be tweaked to more or less do what you want.

>in that way you bring the rssguard to 21st century!!
For me, having inconsistent user interface polluted with all sorts of font sizes and colors is NOT 21st century.

This probably was not what you want to hear. Sorry.

**Comment by pipiscrew** [comment]
@martinrotter 

dont know if you tried, but here is first day, with the script posted on #1, my **eyes** still fresh!!

very very big difference!!

**Comment by pipiscrew** [comment]
@martinrotter after use it, was difficult to come insynch which is red or not!

**v0.1** 
https://github.com/pipiscrew/small_prjs/blob/master/php_rssguard_web/feed.php

**Comment by pipiscrew** [comment]
@martinrotter 

also a small update went to v0.2^

--

using v3.9,2 (dont know afraid to update to latest should I do any dbase migration ??)

As you advice I checked the 'newspaper view' with dark theme, look how it is 

![2022-09-17_213808](https://user-images.githubusercontent.com/3852762/190873835-8af1ae43-0d2e-4b29-9745-650190d149cb.png)

is that corrected on latest version ?

can I somehow alter the structure of HTML ?

can be infinite scrolling and not have to click the `show more messages` every 5 articles ?
