### ISSUE TITLE
[BUG]: RSSGUARD Crashes randomly

### ISSUE THREAD

**Issue by Motocycle347** [martinrotter/rssguard#788]
### Brief description of the issue

this started 3 days ago. RSSGuard crashes random ly

### How to reproduce the bug?

Just using the program

### What was the expected result?

it should not crash

### What actually happened?

just crashes. i clean the database a lot for safety

### Debug log

[rssguard.zip](https://github.com/martinrotter/rssguard/files/9474933/rssguard.zip)

### Operating system and version

Windows 11 21H2
4.23

**Comment by martinrotter** [comment]
In this case, you have really not other chance than to provide full crashdump and upload here as log file does not really indicate any problem.

https://www.ibm.com/support/pages/how-create-crash-dump-windows

Closing until crash dump or other hints are provided.
