### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by TomaszGasior** [martinrotter/rssguard#79]
Is it possible to add custom for new preview to RSS Guard?

**Comment by martinrotter** [comment]
If you want to change the layout/CSS of message PREVIEW, then yes, it is possible. Some steps depend on your platform (Linux/Win/...) and if you compile RSS Guard from sources or not. Let's assume you use Windows.

You need solid text editor for this, I recommend Notepad++.

1. Go to application root folder to `skins\base` subfolder.
2. Find file `vergilius.xml` and make a copy and name it e. g. `my-skin.xml`.

The skin file is XML and has this format:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<skin version="SKIN-VERSION">
  <name>SKIN-NAME</name>
  <author>
    <name>Your name</name>
    <email>YOUR-EMAIL@COM.COM</email>
  </author>
  <markup_wrapper>#BASE-64-OUTER-MESSAGE-HTML-CSS</markup_wrapper>
  <enclosure_image>#BASE-64-IMAGE-HTML</enclosure_image>
  <markup>#BASE-64-HTML-OF-ONE-MESSAGE</markup>
  <markup_enclosure>#BASE-64-HTML-OF-ENCLOSURE</markup_enclosure>
  <data>#BASE-64-QT-STYLE</data>
</skin>
```

You probably want to only edit contents of `markup_wrapper` element. You need to decode contents of the element, change what you need, encode contents back to Base64 and that's it.

**Comment by TomaszGasior** [comment]
Thanks. I will try it.

**Comment by martinrotter** [comment]
OK. Let me know if this is solved or not, so that I can close the issue. :)

**Comment by martinrotter** [comment]
Any news for me @TomaszGasior? Do you consider this issue solved?

**Comment by Sybles** [comment]
Pre-configured dark theme interface skin and RSS CSS would be perfect for reading at night, or better yet have the XML items stored in plain text rather than base64 for easy customization. You should make the donate link much more visible by putting it in the README.md. Thanks for all the hard work you've put into this project, and especially the syncing with owncloud!

**Comment by martinrotter** [comment]
Those are actually very reasonable requirements.

The only problem with base64 -> plain text conversion might be that base64 data probably contain non-valid XML characters. Therefore I would have to convert format of skin file from XML to JSON or use the set of files, which is not bad idea either.

I will incorporate your suggestions. Thanks.

**Comment by martinrotter** [comment]
There actually was dark file before, but nobody wanted to maintain it. It is not easy to write great Qt CSS skin file which will fit most desktop environments and look very beautiful. I shall try again. I could base it on http://ethanschoonover.com/solarized what you think.

**Comment by Sybles** [comment]
Seems like a great system, looking forward to the night mode. Thanks

**Comment by martinrotter** [comment]
Okay, skin got converted to set of files which are a lot easier to understand.

**Comment by martinrotter** [comment]
https://github.com/martinrotter/rssguard/commit/dac3a30a0427a748b448255f5c44b5aa129afe77

**Comment by martinrotter** [comment]
What you think about this [color scheme](https://snag.gy/C1xuHp.jpg)?

**Comment by martinrotter** [comment]
First snapshot of new skin.

https://snag.gy/5RHcv3.jpg

**Comment by Sybles** [comment]
Fantastic! Is there an easy way to also color the upper application bar as well? If not don't sweat it, this is basically what I was looking for. Thanks

**Comment by martinrotter** [comment]
"upper application bar" What is it? You mean the bar which contains minimize, maximize and close window buttons?

No, that one is managed purely by OS, it cannot be managed by the application.

**Comment by martinrotter** [comment]
Okay, you can try latest development build. See Wiki for more info. You can work on skin if you want and enhance it. I will merge any changes you make.

**Comment by martinrotter** [comment]
So try it out and let me know if this issue is resolved and I can close it.

**Comment by Sybles** [comment]
Spot on, well done. Case closed
