### ISSUE TITLE
[BUG]: Regression in 4.2.4 causes Reddit HTML feeds to be treated as plain text

### ISSUE THREAD

**Issue by guihkx** [martinrotter/rssguard#792]
### Brief description of the issue

Version 4.2.4 introduces an issue where Reddit feeds are treated as plain text, even though they're clearly HTML.

Bisecting this points to commit cc142367de7b57c1d7ded77962c2f9199e2c202d as the culprit.

### How to reproduce the bug?

1. Add this Reddit feed: `https://old.reddit.com/r/linux_gaming/new/.rss`
2. Update the feed
3. Browse through the entries

### What was the expected result?

4.2.3 (WebEngine):

![image](https://user-images.githubusercontent.com/626206/188781852-a0b2a7d4-85a5-4c96-9105-cdc604de68f9.png)

### What actually happened?

4.2.4 (WebEngine):

![image](https://user-images.githubusercontent.com/626206/188782017-b77ebb52-45b8-494e-aa14-4a2f9dd5665b.png)

### Debug log

N/A

### Operating system and version

* OS: Arch Linux
* RSS Guard version: 4.2.4 (Qt6 , WebEngine ON)

**Comment by martinrotter** [comment]
ok, i actually expected this.

thing is that in like 90+ % HTML (!) feed entries, formatting was substantially improved by https://github.com/martinrotter/rssguard/commit/cc142367de7b57c1d7ded77962c2f9199e2c202d, sadly some cases appeared as faulty, including this particular case

it seems that `<!--SC_OFF-->` string in the beginning (WTF, btw) is the problem)

wil check and fix somehow

**Comment by martinrotter** [comment]
I believe I fixed it.

**Comment by guihkx** [comment]
Works for me™

Thank you!

**Comment by martinrotter** [comment]
> Works for me™
> 
> Thank you!

OK, I would like to this autodetection work good. If it proves problematic, I will have to either roll it back or add override option per-feed.

**Comment by guihkx** [comment]
I'm not familiar at all with the ATOM specification, but at least the whole ATOM file passes okay in only XML validators.

The `<!--SC_OFF-->` is also a valid comment line in HTML/XML, which should just be ignored, I think...

I found on Google [the reason](https://www.reddit.com/r/redditdev/comments/f7zv87/whats_the_meaning_of_sc_offsc_on_on_rss_feeds/) Reddit feeds use it.

**Comment by guihkx** [comment]
Additionally, Reddit seems to set the `type="html"` attribute for all its `<content>`s, so perhaps RSS Guard could take that into account as well, I don't know...

**Comment by guihkx** [comment]
@xfzv What other feeds? Can you share them?

But yeah, I just downloaded the 4.2.5 `NoWebEngine` AppImage and I can also confirm Reddit is still broken. o_o

Weirdly, it's also broken with the `WebEngine` build, but only when you run it with `--no-web-engine`, which is weird, because I could swear I tested the fix with `--no-web-engine` and it did work...

Nevertheless, I didn't notice this because I've been using this [filter](https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#fltr) for Reddit since 4.2.4, which fixes the issue:

```js
function filterMessage() {
  msg.contents = msg.contents.replace("<!-- SC_OFF -->", "");
  return MessageObject.Accept;
}
```

**Comment by martinrotter** [comment]
https://github.com/martinrotter/rssguard/blob/master/CMakeLists.txt#L5

**Comment by martinrotter** [comment]
will test/merge tonight maybe, very busy rn

**Comment by guihkx** [comment]
I'm just using this on Arch:

```
cmake -B build -S . -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_WITH_QT6=ON -DUSE_WEBENGINE=OFF
cmake --build build -j$(nproc)
./build/src/rssguard/rssguard
```
