### ISSUE TITLE
[BUG]: Windows 7 dropped or?

### ISSUE THREAD

**Issue by GeniusBroccoli** [martinrotter/rssguard#797]
### Brief description of the issue

> Windows and Linux official packages now use Qt 6.3.1 or newer. Qt 5.15 is still supported, though.

0xc0000005 error on Windows 7. Is it because of the transition to Qt6? Should Windows 7 users expect a separate build or am I doing something wrong?

### How to reproduce the bug?

1. Launch RSS Guard on Windows 7x64.

### What was the expected result?

RSS Guard starting.

### What actually happened?

RSS Guard not starting.

### Debug log

Em, not starting.

### Operating system and version

* OS: Windows 7x64
* RSS Guard version: 4.2.4

**Comment by martinrotter** [comment]
Yes, from 4.2.4 only Windows variants supported by Microsoft are supported.

https://doc.qt.io/qt-6/supported-platforms.html
