### ISSUE TITLE
Option to open preview-links in external browser

### ISSUE THREAD

**Issue by tutnixzursache** [martinrotter/rssguard#80]
I really miss an option which, when enabled, opens preview-links in the external browser instead of a new tab, i.e. this option would disable tabs completely.
#### How to reproduce the current behavior?

1. Click on any news item with a preview containing links
2. Click on a link within the preview section -> a new tab opens showing the linked web page

#### What is the expected new behavior?
When the option is enabled:
1. Click on any news item with a preview containing links
2. Click on a link within the preview section -> the linked web page is opened in the external browser 

Keep up the good work!

**Comment by martinrotter** [comment]
How do you click on those links? You use `CTRL+CLICK` combination?

**Comment by martinrotter** [comment]
#76 is related here.

**Comment by tutnixzursache** [comment]
Sorry for my late response.

Well, I just use a simple left click.
But using a Ctrl+Left click results in the same behavior.

Btw.
I am using this version:
https://aur.archlinux.org/packages/rssguard-git/

**Comment by martinrotter** [comment]
Simply clicking left on any link should not open the link in new tab but in the same window, it should only load new page according to link.

**Comment by martinrotter** [comment]
Fixed, there is new context menu item when right-clicked on link.
