### ISSUE TITLE
[FR]: Add sync support

### ISSUE THREAD

**Issue by sbstn87** [martinrotter/rssguard#801]
### Brief description of the feature request

Would it be possible to add a sync support? It could be done using DecSync:
https://github.com/39aldo39/DecSync

Or doing what android app Feeder does:
https://gitlab.com/spacecowboy/Feeder

It would be great to sync feeds between RSS Guard on the desktop and Feeder on Android.

**Comment by martinrotter** [comment]
I am not sure - Feeder does have web interface and some kind of API?

As for Decsync - RSS Guard database and settings file is already configured to be easily portable and can be synced with Syncthing without problems. I use it that way for years.

**Comment by sbstn87** [comment]
To be honest, I do not know the specifics of their method. Here's a screenshot of the option:
![Screenshot_20220912-083535_Feeder](https://user-images.githubusercontent.com/37237675/189588632-0a27104c-ab99-443b-9e4a-b42f10139fee.png)

**Comment by sbstn87** [comment]
Option to sync with Syncthing is great, but does not work for Android <-> Desktop case or Private <-> Company environment where tools like Syncthing are blocked from network access.

**Comment by martinrotter** [comment]
> Option to sync with Syncthing is great, but does not work for Android <-> Desktop case or Private <-> Company environment where tools like Syncthing are blocked from network access.

Well. At this point, RSS Guard already supports multiple syncing RSS services which also have Android clients - for example Feedly or Inoreader or TT-RSS.

I do not plan to add yet another RSS syncing implementation into RSS Guard. There is simple `C++` interface to do that.

If anyone provides PR and will be willing to maintain it, I will be happy to merge.
