### ISSUE TITLE
[FR]: Add option the export feeds as a .json file

### ISSUE THREAD

**Issue by sbstn87** [martinrotter/rssguard#802]
### Brief description of the feature request

Would it be possible to add a .json file export option for YouTube feeds? This would make it possible to use them later as an input for NewPipe import.  There is an option to export as a .txt file, but unfortunately it does not work for NewPipe.

**Comment by martinrotter** [comment]
Provide link to JSON format/specs documentation.

**Comment by sbstn87** [comment]
Sample subscription .json file content for NewPipe:

{"app_version":"0.23.3","app_version_int":989,"subscriptions":[{"service_id":0,"url":"https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw","name":"3Blue1Brown"},{"service_id":0,"url":"https://www.youtube.com/channel/UCivA7_KLKWo43tFcCkFvydw","name":"Applied Science"}]}

**Comment by martinrotter** [comment]
Those URLs do not point to valid RSS feeds. In other words, Youtube channel URLs exported from RSS Guard will likely not work in NewPipe anyway because RSS Guard needs URLs pointing to RSS XML but NewPipe needs URLs pointing to CHANNELs.
