### ISSUE TITLE
[FR]: Add a daily delimiter in the articles list

### ISSUE THREAD

**Issue by sbstn87** [martinrotter/rssguard#803]
### Brief description of the feature request

It would be nice to have a daily delimiter, that separates articles from each day. Visually the perfect example would be the one in the Brief RSS reader:
![image](https://user-images.githubusercontent.com/37237675/189543209-2ed8492b-5465-47b8-910d-fb96dce2c640.png)

This makes reading the news much more optically friendly.

**Comment by martinrotter** [comment]
I do not plan to implement this. If anyone will provide PR, I will be more than happy to assist/merge.
