### ISSUE TITLE
[FR]: 

### ISSUE THREAD

**Issue by pipiscrew** [martinrotter/rssguard#806]
### Brief description of the feature request

Confused little bit.. From my understanding by 
https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#websites-scraping-

correct me if Im wrong : 

when the **Source** combo is `Script`
you can either :
a) enter the URL to download the webpage and **serve it** to `Post-process script`
b) provide **empty URL** and let the `Post-process script` do all the job.

now Im sitting on v3.9.2 and for example chose the a)

![2022-09-17_210925](https://user-images.githubusercontent.com/3852762/190873048-8eb57a43-136a-40c6-bc70-b21cefa5a9c6.png)

why the **#** argument needed ????? no idea :(

the documentation only writes
`As of RSS Guard 4.2.0, you cannot separate your arguments with #. If your argument contains spaces, then enclose it with DOUBLE quotes, for example "my argument". DO NOT use SINGLE quotes to do that.`

![2022-09-17_212239](https://user-images.githubusercontent.com/3852762/190873272-3b2049d6-a293-40b4-aa87-d6a8febb51f3.png)

even I add random # and click **fetch now** seems that is not running the `Post-process script` no logs no error.

--

The `Post-process script` output should be equivalent with `Type` combotext setted on `Add new feed` form ?

--

I submitted it as **FR** as if **Bugfix** to many things to write, do you like also add a 3rd type ??

**Comment by martinrotter** [comment]
First of all,  do not use that old RSS Guard version, not supported anymore. Update to latest RSS Guard.

Secondly, read documentation carefully.
