### ISSUE TITLE
[BUG]: feedly initial sync and subsequent folder sync causes rssguard to close/crash

### ISSUE THREAD

**Issue by rpushd** [martinrotter/rssguard#807]
### Brief description of the issue

rssguard either closes or crashes (I think the latter, but nothing shows in the Windows event log) when adding a feedly account, or when running a manual feedly folder sync after the initial crash.

### How to reproduce the bug?

1. Run rssguard
2. Add feedly account
3. Main rssguard window disappears after a few seconds, and is no longer running (no associated process).
4. You are left with a partially synced feed list. In my case, the last few folders showed up, but feeds within those folders did not.

### What was the expected result?

Full sync

### What actually happened?

Partial sync + process closed or crashed

### Debug log

[....]
time="    47.680" type="debug" -> database: SQLite connection 'FeedlyServiceRoot' is already active.
time="    47.681" type="debug" -> database: SQLite database connection 'FeedlyServiceRoot' to file 'C:/Users/user/Downloads/rssguard-4.2.4-1f6d7c0b-win64/data4/database/database.db' seems to be established.
time="    47.907" type="fatal" -> Cannot store account tree: 'CHECK constraint failed: title != '' Unable to fetch row'.

when switching from embedded sqlite db to a mariadb instance:
time="    34.607" type="fatal" -> Cannot store account tree: 'CONSTRAINT `feeds.title` failed for `rssguard`.`feeds` QMYSQL: Unable to execute statement'.

### Operating system and version

* OS: Windows 10 Pro 21H2
* RSS Guard version:

**Comment by martinrotter** [comment]
can you export your feedly feeds into OPML file and share here?

**Comment by rpushd** [comment]
> can you export your feedly feeds into OPML file and share here?

Sorry, but I would rather not. I would have to some entries first, and it is a sizable list to go through and sanitize. Is there anything else I can check?

I might grab a copy of the source and run it locally with a debugger attached, but finding the time is currently tricky.

**Comment by martinrotter** [comment]
> > can you export your feedly feeds into OPML file and share here?
> 
> Sorry, but I would rather not. I would have to some entries first, and it is a sizable list to go through and sanitize. Is there anything else I can check?
> 
> I might grab a copy of the source and run it locally with a debugger attached, but finding the time is currently tricky.

it seems that for some reason, some of your feeds does not have title/caption?

i will try to test with some random opml

**Comment by rpushd** [comment]
I checked, and yes, one feed appears to not have a name. Looks like it wasn't picked up by feedly on import.

**Comment by martinrotter** [comment]
> 

can you perhaps create opml with only that one signle feed for me to test?

**Comment by rpushd** [comment]
The offending feed URL was https://www.france24.com/en/rss
It had a blank name. I renamed it, and this appears to have solved the sync crash.
I'm going to do a fresh start and see if I run into any issues.

**Comment by martinrotter** [comment]
yyes, i managed to reproduce

**Comment by rpushd** [comment]
Tried again with a fresh start, and it synced fine again. So it does seem to be related to blank names.

**Comment by martinrotter** [comment]
OK, I believe it is now fixed. Will be released soon or you can try devbuild.
