### ISSUE TITLE
[BUG]: Can't pull freshly subscribed feeds from Nextcloud News without destroying manual feed ordering

### ISSUE THREAD

**Issue by rfkat** [martinrotter/rssguard#809]
### Brief description of the issue

The only way to pull a new feed one has just subscribed to in Nextcloud News seems to be a "Synchronize folders & other items". This however destroys the manual ordering one may have applied by moving feeds up or down. Having ordered 110+ feeds in the feed list so that they match my workflow this loss is really excruciating for me. Saving and restoring settings unfortunately does not seem to restore the manual feed ordering.

### How to reproduce the bug?

1. Sort some feeds, so the native ordering of feeds is changed.
2. Subscribe to a new feed in Nextcloud News.
3. Do a "Synchronize folders & other items" in RSS Guard, to retrieve the newly added feed.
4. The manual sort order is destroyed / reset to default.

### What was the expected result?

Newly subscribed feeds should blend in at their native (manually unordered) position, wherever that may be. The rest of the manual ordering should be preserved (or at least be recoverable via "Restore settings").

### What actually happened?

 The manual sort order is destroyed by each "Synchronize folders & other items".

### Debug log

n/a

### Operating system and version

* OS: Linux
* RSS Guard version: 4.2.4

**Comment by martinrotter** [comment]
Yes, this is unintented regression which I forgot about when implementing sorting.

I will address this rather soon.

**Comment by martinrotter** [comment]
I just committed

**Comment by rfkat** [comment]
Thank you.
Can confirm sorting is preserved _within_ folders (categories).

**Comment by martinrotter** [comment]
Ok will polish feature and implement for folders too
