### ISSUE TITLE
Custom user skins in user profile folder

### ISSUE THREAD

**Issue by mahdi1234** [martinrotter/rssguard#81]
Did test latest dev version with black skin and yeah I like it in full screen mode!

Though I will be making some changes to the skin. I figured I could simply copy it under /usr/share/rssguard/skins/ to create new skin.

However custom user data should be stored rather under ~/.rssguard/

Would it be possible for application to also check for skins folder under user profile? I.e. built-in skins are under /usr/share and custom skins under /home?

**Comment by martinrotter** [comment]
Fixed, please test the feature in latest development build and read the changelog for more info.

**Comment by martinrotter** [comment]
One more info. All skins must have unique names. Therefore any new custom user skin cannot have the same name as predefined skins.

**Comment by mahdi1234** [comment]
Seems to be fine with 7bc8caa cheers
