### ISSUE TITLE
[BUG]: custom external browser doesn't work

### ISSUE THREAD

**Issue by orzel** [martinrotter/rssguard#811]
### Brief description of the issue

double clicking a feed entry righfully open an external browser using the 'system' browser.

### How to reproduce the bug?

(i translate in English from my localised rssguard, may differ slightly)

1) In settings / "network & web & tools" / "External web browser" tab 
2) click on "use a personalized web browser"
3) choose:
executable: chromium-browser
parameters: --incognito --new-window "%1"

### What was the expected result?

rssguard executes 
chromium-browser --incognito --new-window "https://xxx"

### What actually happened?

double clicking en entry will open a new chromium window, empty(blank), with an empty url bar, and it's no in 'incognito' mode.

### Debug log

In the (console) output, i can still see this, which seems perfectly ok to me: 
time="  1479.201" type="debug" -> network: Arguments for external browser: '--incognito --new-window "https://xxx"'.

### Operating system and version

* OS: linux/gentoo
* RSS Guard version: 4.2.3

**Comment by akinokonomi** [comment]
> executable: chromium-browser

Have you tried full path to executable?

**Comment by martinrotter** [comment]
test with latest release, if still persists, reopen

**Comment by orzel** [comment]
It seems to work in 4.2.5, indeed !
