### ISSUE TITLE
[BUG]: Feeds in Nextcloud News will not show any items without a title tag (but with link and description tag)

### ISSUE THREAD

**Issue by kescherCode** [martinrotter/rssguard#814]
### Brief description of the issue

When having a feed like https://toot.site/tags/Cats.rss in Nextcloud News, you will see no articles in RSS Guard. In Nextcloud News, as well as in its companion Android app, this works fine.

This feed's articles have no `<title>` tag, but they do have a `<description>` tag. Only one of the two is required for an article according to RSS 2.0 spec.

### How to reproduce the bug?

1. Add feed to Nextcloud News
2. Synchronize folders and other items

### What was the expected result?

The feed should show articles, either with an empty title or falling back to some other default, as is done with the **RSS/ATOM/JSON** pseudo-account when feeds are in RSS Guard itself: 
![The RSS feed showing a list of articles, with the `<link>` tag being used as fallback.](https://user-images.githubusercontent.com/23276523/193987710-26e09ce7-0bdd-4eb4-92ee-822fc694e6b8.png)

### What actually happened?

The feed articles don't show up at all.
![Empty RSS feed list](https://user-images.githubusercontent.com/23276523/193987855-4e8240e3-826b-4f04-af10-c45aca90427f.png)
![the same RSS feed not being empty when Nextcloud News renders it](https://user-images.githubusercontent.com/23276523/193987996-a3813fae-fe02-4392-ae73-b917449be7ec.png)

### Debug log

N/A

### Operating system and version

* OS: Arch Linux
* RSS Guard version: 4.2.5, but the issue reaches back a while

**Comment by martinrotter** [comment]
fixed
