### ISSUE TITLE
[BUG]: Kaspersky detected like malware

### ISSUE THREAD

**Issue by norman003** [martinrotter/rssguard#815]
### Brief description of the issue

Kaspersky detected rssguard like malware

### How to reproduce the bug?

![image](https://user-images.githubusercontent.com/33376952/194977375-b593e1b6-3d61-40cb-8c99-73c48123474f.png)

### What was the expected result?

Send to kaspersky to evaluate

### What actually happened?

Kaspersky detected like malware

### Debug log

Image

### Operating system and version

* OS: Windows 11 Version 21H2
* RSS Guard version: 4.2.5

**Comment by martinrotter** [comment]
https://www.virustotal.com/gui/url/995816e3a8063c5e04435700cda6e0c65cd213bc8f697d2189fe49b2d087c77e?nocache=1
