### ISSUE TITLE
[FR]: Web view in dark mode

### ISSUE THREAD

**Issue by norman003** [martinrotter/rssguard#816]
### Brief description of the feature request

Support to web view in dark mode
![image](https://user-images.githubusercontent.com/33376952/194977052-202c3802-edbf-4553-b79f-2bec008570f0.png)

**Comment by martinrotter** [comment]
If you open some "source" website, of course that CSS formatting of that website will be loaded.

"entries" of feeds are loaded with "dark" CSS.

![image](https://user-images.githubusercontent.com/1255302/195016915-83ddbda8-2780-45cc-9d8c-68f7dbbe9f72.png)

**Comment by norman003** [comment]
![image](https://user-images.githubusercontent.com/33376952/195103425-5607c039-a169-4796-89d9-8ebf7339790e.png)
When you click in url
![image](https://user-images.githubusercontent.com/33376952/195103499-72c3fecf-e808-4ddb-8d75-4f93e6f7ea3c.png)
