### ISSUE TITLE
[FR]: Enable selection of adblock port, for usage of multiple instances

### ISSUE THREAD

**Issue by alexjp** [martinrotter/rssguard#819]
### Brief description of the feature request

Hi!

Currently when using adblock, it will use a hardcoded single port. this works on the first instance of rssguard, but when launching a second instance, it will fail with "port already in use".

So it would be great if one could customize the adblock port.

Opinion: seeing that to enable multiple instances (the `-s switch and --data switch` for configuring the data folder on each) are already command line switches, maybe adding a `--adblock-port=xxxxx` would be great.
(this is just my particular usecase, but the reasoning of this is that, when I make setting changes in one instance/data folder of rssguard, i just copy the config.ini to the other data folder. so being a command line switch would keep this "copying of config.ini" and adblock port working)

Thank you very much for rssguard!

**Comment by martinrotter** [comment]
Fixed, see "--help" for more info.

```
RSS Guard

Options:
  -h, --help                     Displays overview of CLI.
  -v, --version                  Displays version of the application.
  -l, --log <log-file>           Write application debug log to file. Note that
                                 logging to file may slow application down.
  -d, --data <user-data-folder>  Use custom folder for user data and disable
                                 single instance application mode.
  -s, --no-single-instance       Allow running of multiple application
                                 instances.
  -g, --no-debug-output          Disable just "debug" output.
  -n, --no-standard-output       Completely disable stdout/stderr outputs.
  -w, --no-web-engine            Force usage of simpler text-based embedded web
                                 browser.
  -t, --style <style-name>       Force some application style.
  -p, --adblock-port <port>      Use custom port for AdBlock server. It is
                                 highly recommended to use values higher than
                                 1024.

Arguments:
  urls                           List of URL addresses pointing to individual
                                 online feeds which should be added.
```
