### ISSUE TITLE
Black theme blinking white backround cycling between messages

### ISSUE THREAD

**Issue by mahdi1234** [martinrotter/rssguard#82]
With latest dev version and stock black theme see attached video it goes between white and black when changing messages by keyboard (simple going down/up)

[rss_blinking.zip](https://github.com/martinrotter/rssguard/files/706660/rss_blinking.zip)

Sorry for zip, but github doesn't allow videos apparently.

Another thing related to black theme - scrollbar for message list is black, but scrollbar in the web preview keeps system settings I guess.

![rssguard_scrollbar](https://cloud.githubusercontent.com/assets/1097047/21963531/ea98ecf8-db3c-11e6-8c7d-a979dcd849c5.png)

**Comment by martinrotter** [comment]
As for scrollbar theming. This is not our bug, but [bug upstream](https://bugreports.qt.io/browse/QTBUG-51186).

**Comment by martinrotter** [comment]
Please, test latest dev build and let me know if this is solved.

**Comment by mahdi1234** [comment]
Fixed with 1db5e61 closing.
