### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by pokemaster974** [martinrotter/rssguard#821]
### Brief description of the issue

Since I've updated RSS Guard from 4.2.3 to 4.2.5 today, the size of the interface is very little compared my interface into 4.2.3.

I've changed nothing, just install the exe of 4.2.5.

### How to reproduce the bug?

1. Open RSS Guard

### What was the expected result?

Having the same font size as before or having the possibilty to set it (I don't find it into actual settings window)

### What actually happened?

I've not old screenshot but it seems that for my case the font' size have decreased.
It's very difficult to see the text.
![image](https://user-images.githubusercontent.com/28442699/196391632-bfab6717-489c-44b9-8044-18a65e5985c8.png)

### Debug log

time="     0.195" type="debug" -> core: Initializing settings in 'C:\Users\xxx\AppData\Local\RSS Guard 4\config\config.ini' (non-portable way).
time="     0.201" type="info" -> 

GL Type: desktop
Surface Type: OpenGL
Surface Profile: CompatibilityProfile
Surface Version: 4.6
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: yes

Init Parameters:
  *  application-name rssguard 
  *  browser-subprocess-path C:\Program Files\RSS Guard\QtWebEngineProcess.exe 
  *  create-default-gl-context  
  *  disable-es3-gl-context  
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-speech-api  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-threaded-compositing  
  *  enable-use-zoom-for-dsf false 
  *  in-process-gpu  
  *  log  
  *  use-gl desktop 

time="     0.636" type="debug" -> database: File-based SQLite database connection 'DatabaseFactory' to file 'C:\Users\xxx\AppData\Local\RSS Guard 4\database\database.db' seems to be established.
time="     0.637" type="debug" -> database: File-based SQLite database has version '3'.
time="     0.639" type="debug" -> gui: Available icon theme paths: QList(:/icons, :/graphics, C:/Users/xxx/AppData/Local\RSS Guard 4\icons, C:/Program Files/RSS Guard\icons)
time="     0.640" type="debug" -> gui: Installed icon themes are: '', 'Breeze', 'Breeze Dark', 'Faenza', 'Numix'
time="     0.640" type="debug" -> gui: Loading icon theme 'Numix'.
time="     0.641" type="debug" -> gui: Found path of base skin: ':\skins\nudus-base'.
time="     0.641" type="debug" -> gui: Local file ':\skins\nudus-dark\html_wrapper.html' exists, using it for the skin.
time="     0.641" type="debug" -> gui: Local file ':\skins\nudus-dark\html_style.css' exists, using it for the skin.
time="     0.642" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_enclosure_image.html' for the skin.
time="     0.642" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_single_message.html' for the skin.
time="     0.642" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_enclosure_every.html' for the skin.
time="     0.642" type="debug" -> gui: Local file ':\skins\nudus-dark\qt_style.qss' exists, using it for the skin.
time="     0.642" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_adblocked.html' for the skin.
time="     0.643" type="debug" -> gui: Setting style: 'Fusion'.
time="     0.643" type="debug" -> gui: Activating alternative palette.
time="     0.643" type="debug" -> gui: Skin 'nudus-dark' loaded.
time="     0.644" type="debug" -> network: Persistent web data storage path: 'C:/Users/xxx/AppData/Local\RSS Guard 4\web\storage'.
time="     0.644" type="debug" -> network: Disabling application-wide proxy completely.
time="     0.651" type="debug" -> core: OpenSSL version: 'OpenSSL 1.1.1j  16 Feb 2021'.
time="     0.652" type="debug" -> core: OpenSSL supported: 'true'.
time="     0.652" type="debug" -> core: Starting RSS Guard 4.2.5.
time="     0.652" type="debug" -> core: Instantiated class  'Application'.
time="     0.653" type="debug" -> core: Starting to load active localization. Desired localization is 'en_US'.
time="     0.653" type="debug" -> core: Application localization 'en_US' loaded successfully, specifically sublocalization 'en_US' was loaded.
time="     0.654" type="warning" -> core: Qt localization 'en_US' WAS NOT loaded successfully.
time="     0.658" type="debug" -> database: SQLite database connection 'MessagesModel' to file 'C:/Users/xxx/AppData/Local/RSS Guard 4/database/database.db' seems to be established.
time="     0.662" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, CASE WHEN length(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1;'.
time="     0.662" type="debug" -> core: Auto-download timer started with interval 10000 ms.
time="     0.662" type="debug" -> core: Creating FeedDownloader singleton.
time="     0.663" type="debug" -> core: Requesting update for all feeds on application startup.
time="     0.666" type="debug" -> gui: Creating main application form in thread: '0x4528'.
time="     0.675" type="debug" -> gui: Current row changed - proxy 'QModelIndex(-1,-1,0x0,QObject(0x0))', source 'QModelIndex(-1,-1,0x0,QObject(0x0))'.
time="     0.681" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     1.092" type="debug" -> gui: Creating tray icon menu.
time="     1.093" type="debug" -> CTRL is NOT pressed while sorting articles - sorting with standard mode.
time="     1.093" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, CASE WHEN length(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1 ORDER BY Messages.id DESC;'.
time="     1.094" type="debug" -> gui: Reloading of msg selections took 1 miliseconds.
time="     1.167" type="debug" -> CTRL is NOT pressed while sorting articles - sorting with standard mode.
time="     1.167" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, CASE WHEN length(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1 ORDER BY Messages.date_created DESC, Messages.id DESC;'.
time="     1.169" type="debug" -> core: Hiding the main window when the application is starting.
time="     1.169" type="debug" -> database: SQLite database connection 'FeedReader' to file 'C:/Users/xxx/AppData/Local/RSS Guard 4/database/database.db' seems to be established.
time="     1.170" type="debug" -> database: SQLite database connection 'FeedlyEntryPoint' to file 'C:/Users/xxx/AppData/Local/RSS Guard 4/database/database.db' seems to be established.
time="     1.171" type="debug" -> database: SQLite database connection 'GmailEntryPoint' to file 'C:/Users/xxx/AppData/Local/RSS Guard 4/database/database.db' seems to be established.
time="     1.172" type="debug" -> database: SQLite database connection 'GreaderEntryPoint' to file 'C:/Users/xxx/AppData/Local/RSS Guard 4/database/database.db' seems to be established.
time="     1.174" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     1.174" type="debug" -> oauth: User does not want handler to be running.
time="     1.175" type="debug" -> core: Filter accepts row '' and filter result is: 'true'.
time="     1.176" type="debug" -> database: SQLite database connection 'GreaderServiceRoot' to file 'C:/Users/xxx/AppData/Local/RSS Guard 4/database/database.db' seems to be established.
time="     1.177" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/2'.
time="     1.177" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/3'.
time="     1.177" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/4'.
time="     1.178" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/5'.
time="     1.178" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/6'.
time="     1.179" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/7'.
time="     1.179" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/8'.
time="     1.180" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/9'.
time="     1.180" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/11'.
time="     1.180" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/10'.
time="     1.181" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/12'.
time="     1.181" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/13'.
time="     1.186" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/14'.
time="     1.186" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/15'.
time="     1.187" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/17'.
time="     1.187" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/18'.
time="     1.187" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/19'.
time="     1.188" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/21'.
time="     1.188" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/22'.
time="     1.188" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/23'.
time="     1.189" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/35'.
time="     1.189" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/34'.
time="     1.189" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/24'.
time="     1.190" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/25'.
time="     1.190" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/26'.
time="     1.191" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/27'.
time="     1.191" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/28'.
time="     1.191" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/29'.
time="     1.192" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/30'.
time="     1.192" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/31'.
time="     1.192" type="debug" -> core: Custom ID of feed when loading from DB is 'feed/32'.
time="     1.193" type="debug" -> database: SQLite database connection 'RecycleBin' to file 'C:/Users/xxx/AppData/Local/RSS Guard 4/database/database.db' seems to be established.
time="     1.217" type="debug" -> database: SQLite database connection 'ImportantNode' to file 'C:/Users/xxx/AppData/Local/RSS Guard 4/database/database.db' seems to be established.
time="     1.245" type="debug" -> database: SQLite database connection 'RootItem' to file 'C:/Users/xxx/AppData/Local/RSS Guard 4/database/database.db' seems to be established.
time="     1.268" type="debug" -> database: SQLite connection 'GreaderServiceRoot' is already active.
time="     1.269" type="debug" -> database: SQLite database connection 'GreaderServiceRoot' to file 'C:/Users/xxx/AppData/Local/RSS Guard 4/database/database.db' seems to be established.
time="     1.336" type="debug" -> database: SQLite database connection 'OwnCloudServiceEntryPoint' to file 'C:/Users/xxx/AppData/Local/RSS Guard 4/database/database.db' seems to be established.
time="     1.338" type="debug" -> database: SQLite database connection 'StandardServiceEntryPoint' to file 'C:/Users/xxx/AppData/Local/RSS Guard 4/database/database.db' seems to be established.
time="     1.339" type="debug" -> database: SQLite database connection 'TtRssServiceEntryPoint' to file 'C:/Users/xxx/AppData/Local/RSS Guard 4/database/database.db' seems to be established.
time="     1.340" type="debug" -> gui: User wants to have tray icon.
time="     1.340" type="debug" -> gui: Tray icon is available, showing now.
time="     1.343" type="debug" -> gui: Creating SystemTrayIcon instance.
time="     1.384" type="debug" -> gui: Showing tray icon immediately.
time="     1.519" type="debug" -> gui: Tray icon displayed.
time="     1.520" type="debug" -> gui: Feed list item expanded - xxx (FreshRSS)
time="     1.520" type="debug" -> core: Filter accepts row 'Recycle bin' and filter result is: 'true'.
time="     1.520" type="debug" -> core: Filter accepts row 'Important articles' and filter result is: 'true'.
time="     1.520" type="debug" -> core: Filter accepts row 'Unread articles' and filter result is: 'true'.
time="     1.520" type="debug" -> core: Filter accepts row 'Labels' and filter result is: 'true'.
time="     1.521" type="debug" -> core: Filter accepts row 'Cinema' and filter result is: 'true'.
time="     1.521" type="debug" -> core: Filter accepts row 'Crypto' and filter result is: 'true'.
time="     1.521" type="debug" -> core: Filter accepts row 'DDL' and filter result is: 'true'.
time="     1.521" type="debug" -> core: Filter accepts row 'Informatique' and filter result is: 'true'.
time="     1.522" type="debug" -> core: Filter accepts row 'Jeux' and filter result is: 'true'.
time="     1.522" type="debug" -> core: Filter accepts row 'Musique' and filter result is: 'true'.
time="     1.522" type="debug" -> core: Filter accepts row 'Médecine' and filter result is: 'true'.
time="     1.522" type="debug" -> gui: Feed list item expanded - Labels
time="     1.523" type="debug" -> gui: Feed list item expanded - Cinema
time="     1.523" type="debug" -> gui: Feed list item expanded - Crypto
time="     1.523" type="debug" -> gui: Feed list item expanded - DDL
time="     1.523" type="debug" -> gui: Feed list item expanded - Informatique
time="     1.523" type="debug" -> gui: Feed list item expanded - Jeux
time="     1.524" type="debug" -> gui: Feed list item expanded - Musique
time="     1.524" type="debug" -> gui: Feed list item expanded - Médecine
time="     1.524" type="debug" -> core: No execution message received from other app instances.
time="     1.636" type="debug" -> gui: Hovered link: 'QUrl()'.
time="     1.636" type="debug" -> core: Silencing GUI message: ''.
time="     1.645" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     2.451" type="debug" -> network: Destroying Downloader instance.
time="     2.451" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="     7.659" type="debug" -> gui: Message splitter moved.
time="     7.663" type="debug" -> core: Filter accepts row 'AlloCine' and filter result is: 'true'.
time="     7.663" type="debug" -> core: Filter accepts row 'CloneWeb' and filter result is: 'true'.
time="     7.663" type="debug" -> core: Filter accepts row 'Faux Raccord' and filter result is: 'true'.
time="     7.663" type="debug" -> core: Filter accepts row 'COIN24.FR' and filter result is: 'true'.
time="     7.663" type="debug" -> core: Filter accepts row 'Coindoo' and filter result is: 'true'.
time="     7.664" type="debug" -> core: Filter accepts row 'Journal du Coin' and filter result is: 'true'.
time="     7.664" type="debug" -> core: Filter accepts row 'Extreme Download' and filter result is: 'true'.
time="     7.664" type="debug" -> core: Filter accepts row 'Bonsplans.tech' and filter result is: 'true'.
time="     7.665" type="debug" -> core: Filter accepts row 'Clubic.com (articles)' and filter result is: 'true'.
time="     7.665" type="debug" -> core: Filter accepts row 'Clubic.com (news)' and filter result is: 'true'.
time="     7.665" type="debug" -> core: Filter accepts row 'Dealabs' and filter result is: 'true'.
time="     7.665" type="debug" -> core: Filter accepts row 'Google Camera Port' and filter result is: 'true'.
time="     7.665" type="debug" -> core: Filter accepts row 'JDG' and filter result is: 'true'.
time="     7.666" type="debug" -> core: Filter accepts row 'Next INpact - Actualités' and filter result is: 'true'.
time="     7.666" type="debug" -> core: Filter accepts row 'Nikon Passion' and filter result is: 'true'.
time="     7.666" type="debug" -> core: Filter accepts row 'Photography Life' and filter result is: 'true'.
time="     7.666" type="debug" -> core: Filter accepts row 'Sciphone' and filter result is: 'true'.
time="     7.667" type="debug" -> core: Filter accepts row 'Tom's Hardware' and filter result is: 'true'.
time="     7.667" type="debug" -> core: Filter accepts row 'Actualités Tric Trac par La rédaction' and filter result is: 'true'.
time="     7.667" type="debug" -> core: Filter accepts row 'Actualités Tric Trac par Les blogueurs' and filter result is: 'true'.
time="     7.667" type="debug" -> core: Filter accepts row 'Brawl Stars ／ @BrawlStars' and filter result is: 'true'.
time="     7.668" type="debug" -> core: Filter accepts row 'Clash Royale ／ @ClashRoyale' and filter result is: 'true'.
time="     7.668" type="debug" -> core: Filter accepts row 'DamonX' and filter result is: 'true'.
time="     7.668" type="debug" -> core: Filter accepts row 'JV.com - PC' and filter result is: 'true'.
time="     7.668" type="debug" -> core: Filter accepts row 'Pokémon Go English' and filter result is: 'true'.
time="     7.669" type="debug" -> core: Filter accepts row 'Pokémon Go France' and filter result is: 'true'.
time="     7.669" type="debug" -> core: Filter accepts row '# PLC Muziks 974 ♫' and filter result is: 'true'.
time="     7.669" type="debug" -> core: Filter accepts row 'Blog Music Officiel de New-Son-974' and filter result is: 'true'.
time="     7.670" type="debug" -> core: Filter accepts row 'Noutmizik-974.skyrock.com' and filter result is: 'true'.
time="     7.670" type="debug" -> core: Filter accepts row 'DREES' and filter result is: 'true'.
time="     7.670" type="debug" -> core: Filter accepts row 'EM-Consulte - AKOS (Traité de Médecine)' and filter result is: 'true'.
time="    10.736" type="debug" -> gui: Main window's close event
time="    10.737" type="debug" -> gui: Main window's hide event
time="    10.741" type="debug" -> core: Cleaning up resources and saving application state.
time="    10.742" type="debug" -> core: Close lock was obtained safely.
time="    10.742" type="debug" -> feed-downloader: Destroying FeedDownloader instance.
time="    10.750" type="debug" -> gui: Destroying FormMain instance.
time="    10.750" type="debug" -> gui: Destroying TabWidget instance.
time="    10.750" type="debug" -> gui: Destroying FeedMessageViewer instance.
time="    10.751" type="debug" -> gui: Destroying BaseToolBar instance.
time="    10.756" type="debug" -> gui: Destroying MessagesView instance.
time="    10.756" type="debug" -> gui: Destroying BaseToolBar instance.
time="    10.757" type="debug" -> gui: Destroying FeedsView instance.
time="    10.757" type="debug" -> gui: Destroying TabBar instance.
time="    10.758" type="debug" -> gui: Destroying StatusBar instance.
time="    10.758" type="debug" -> gui: Destroying SystemTrayIcon instance.
time="    10.798" type="debug" -> core: Destroying Application instance.
time="    10.798" type="debug" -> core: Destroying Mutex instance.
time="    10.828" type="debug" -> gui: Destroying IconFactory instance.
time="    10.829" type="debug" -> core: Destroying FeedReader instance.
time="    10.829" type="debug" -> feed-model: Destroying FeedsModel instance.
time="    10.829" type="debug" -> oauth: Destroying OAuth2Service instance.
time="    10.830" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="    10.830" type="debug" -> feed-model: Destroying FeedsProxyModel instance
time="    10.830" type="debug" -> message-model: Destroying MessagesModel instance.
time="    10.830" type="debug" -> message-model: Destroying MessagesProxyModel instance.

### Operating system and version

* OS: W10
* RSS Guard version: 4.2.5

**Comment by martinrotter** [comment]
You likely now installed Qt6-based variant of RSS Guard which handles fonts bit differently. Perhaps installed the "win7" flavor of RSS Guard to have previous UX.

**Comment by martinrotter** [comment]
Also, you can change size of fonts in settings.

**Comment by pokemaster974** [comment]
Could you just tell me where I can find this option please ?
I found only this in the settings window :
![image](https://user-images.githubusercontent.com/28442699/196396711-2dc879af-215e-45db-91ff-ecb8d1c01d9a.png)
