### ISSUE TITLE
Media icon URL handled strangely, Mashable RSS feed

### ISSUE THREAD

**Issue by groentebroer** [martinrotter/rssguard#83]
#### Brief description of the issue.

The article Thumbnail icon URL is handled strangly in the case of the Mashable RSS feed.
I cannot tell if it is an error in the feed or that it is RSS Guard.
Firefox seems to display it well.

#### How to reproduce the bug?

1. Configure: http://feeds.mashable.com/Mashable
2. Open an article with a thumbnail from this feed

#### What is the expected result?

The thumbnail should be shown.

#### What actually happened?

It displays a broken image with a misfigured url.

**Comment by martinrotter** [comment]
Can we see the screenshot of the situation? Ideally, screenshot from both firefox && rssguard?

**Comment by groentebroer** [comment]
Yes, sure!

RSSGuard:
![image](https://cloud.githubusercontent.com/assets/1811817/22240654/5a3dd6aa-e21c-11e6-8bb1-c9488926384c.png)

Firefox:
![image](https://cloud.githubusercontent.com/assets/1811817/22240699/843a8b6a-e21c-11e6-8214-22aca745111b.png)

**Comment by martinrotter** [comment]
I see, it seems that they have some special characters (which are included in resource http link) [encoded](https://grox.net/utils/encoding.html). It seems that WebEngine cannot handle these automatically. Therefore, I would have to decode it before giving HTML to WebEngine and displaying it.

Funny thing is that the last image of the message is not encoded and characters `://` are written OK.

**Comment by martinrotter** [comment]
Fixed.

Note that Windows development builds are for certain amount of time not working, because there are some new libs missing on compilation platform. I expect them to work again soon, in a week perhaps.

**Comment by groentebroer** [comment]
Oke, will check it later on.
