### ISSUE TITLE
[FR]: macOS Monterey 12.6.1 (M1) & RSS Guard 4.2.5

### ISSUE THREAD

**Issue by MaxNYSE** [martinrotter/rssguard#830]
### Brief description of the feature request

Your program does not work on the macOS Monterey 12.6.1 (M1)!
RSS Guard 4.2.5

**Comment by martinrotter** [comment]
Your bug report is missing any logs etc.

Please provide logs, or some documentation, screenshots, whatever to somehow see what is actually wrong.

"does not work" is very vague.

**Comment by MaxNYSE** [comment]
App crash and unexpectedly quit (during installation and first start).

**Comment by martinrotter** [comment]
This is still NOT enough. Closing.

https://www.chiark.greenend.org.uk/~sgtatham/bugs.html
