### ISSUE TITLE
[FR]: User Agent Spoofing

### ISSUE THREAD

**Issue by RetroAbstract** [martinrotter/rssguard#835]
### Brief description of the feature request

This feature would allow the user to spoof their RSS Guard User Agent by setting RSS Guard to change it's user agent to a newly generated one on launch or periodically.

Periodically would include changing the user agent every: 5, 10, 20, 30, 45, 60 minutes.

RSS Guard could generate User Agents from this index: https://developers.whatismybrowser.com/useragents/explore/

**Comment by martinrotter** [comment]
On launch, could be added.

**Comment by martinrotter** [comment]
I thought about this.

What about including some rather big list of user agents in the app and when user passes THE option when starting, RSS Guard would randomly use one of available UAs for each network request.

I am not sure if changing user agents even works novadays with avoiding bans etc.?

**Comment by RetroAbstract** [comment]
> I thought about this.
> 
> What about including some rather big list of user agents in the app and when user passes THE option when starting, RSS Guard would randomly use one of available UAs for each network request.

That sounds good. So for each feed RSS Guard connects to to fetch articles from, a different UA would be used, randomly picked from the big list if I understand correctly.

This option would be a toggle in settings?

> I am not sure if changing user agents even works novadays with avoiding bans etc.?

I originally made this FR to increase users' privacy. As you say, not sure about the effectiveness this feature would have regarding avoiding bans

**Comment by martinrotter** [comment]
After some deliberating, I decided to implement simple custom UA setting, because for sake of privacy, that is enough. For avoiding web bans etc. multiple rotating UAs are useless anyway.

**Comment by martinrotter** [comment]
```
  -u, --user-agent <user-agent>  User custom User-Agent HTTP header for all
                                 network requests.
```
