### ISSUE TITLE
Account root folder is preselected even when some specific subfolder is selected and "Add feed to selected account" is pressed

### ISSUE THREAD

**Issue by groentebroer** [martinrotter/rssguard#84]
#### Brief description of the issue.

Not really a bug, more a feature request.

#### How to reproduce the bug?

1.  I added the "add new item into selected account" to the toolbar.
2. Select a category (or map) and press the "add new item" button.
3. 

#### What is the expected result?

That the "add new feed" item, automatically uses the selected category (map) to create the new feed "under".

#### What actually happened?

The feed is standard added to the main account group.

**Comment by martinrotter** [comment]
What is "map"?

**Comment by groentebroer** [comment]
Sorry, for my English. I meant "folder".
So when selecting a subfolder and then "add new feed", it does not respect the selected subfolder from the account, but selects the top level (account).

**Comment by martinrotter** [comment]
Oh, now I know what you mean. There is no such feature I believe, it always selects the root folder of the account.

**Comment by groentebroer** [comment]
Yes, I think it would be more a feature request.
