### ISSUE TITLE
[BUG]: libQt6WebEngineWidgets.so.6 not found in majnaro

### ISSUE THREAD

**Issue by generalsmithers** [martinrotter/rssguard#841]
### Brief description of the issue

Rssguard crashes immediately with the following error:
"rssguard: error while loading shared libraries: libQt6WebEngineWidgets.so.6: cannot open shared object file: No such file or directory"
I am unable to attach a debug log because it crashes with the same error when I tried to run "rssguard --log rssguard.log"

### How to reproduce the bug?

1. Execute Rssguard on an up to date version of manjaro

### What was the expected result?

RssGuard runs as expected

### What actually happened?

Crash while loading libQt6WebEngineWidgets.so.6

### Debug log

N/A

### Operating system and version

* OS: Manjaro linux
* RSS Guard version: 4.2.5-1
* RSS Guard build date: Fri 30 Sep 2022 02:39:08 AM CDT

**Comment by akinokonomi** [comment]
Do you run the AppImage? Or build from Manjaro repository?

**Comment by akinokonomi** [comment]
If you downloaded it from Manjaro repository, please report it to Manjaro bug tracker.

**Comment by generalsmithers** [comment]
Ok having done more research, I think that someone on the manjaro/arch side might have screwed something up - it looks like the package qt6-webengine only installs these files:

- /usr/lib/cmake/Qt6/FindGPerf.cmake
- /usr/lib/cmake/Qt6/FindGn.cmake
- /usr/lib/cmake/Qt6/FindNinja.cmake
- /usr/lib/cmake/Qt6/FindNodejs.cmake
- /usr/lib/cmake/Qt6/FindPkgConfigHost.cmake
- /usr/lib/cmake/Qt6/FindSnappy.cmake
- /usr/share/licenses/qt6-webengine/LICENSE.chromium
notaby absent are any .so files.

Grepping through the codebase I see that in src/librssguard/CMakeLists.txt on line 635 you're  linking against it correctly, so I'm guessing it's upstream, but I'm not a developer so I may be wrong.  I also have no idea how to report this to manjaro/arch/qt/whatever if it does turn out to be an upstream problem.

**Comment by generalsmithers** [comment]
> 

Gladly, how do I do that?

**Comment by akinokonomi** [comment]
> Gladly, how do I do that?

Sorry, I don't know.

FWIW, Arch Linux package has that file:
```bash
$ pacman -Ql qt6-webengine | grep libQt6WebEngineWidgets
qt6-webengine /usr/lib/libQt6WebEngineWidgets.prl
qt6-webengine /usr/lib/libQt6WebEngineWidgets.so
qt6-webengine /usr/lib/libQt6WebEngineWidgets.so.6
qt6-webengine /usr/lib/libQt6WebEngineWidgets.so.6.4.0
```
