### ISSUE TITLE
[FR]: "%1" Placeholder for URLs for external tools parameters

### ISSUE THREAD

**Issue by RetroAbstract** [martinrotter/rssguard#843]
### Brief description of the feature request

This feature would allow the user to use "%1" to place the URL of the article they're opening with an external tool at a specific point in the parameter string, just like you can already do when opening articles with an external browser.

Currently, the "%1" parameter that is a placeholder for URLs in the external web browser settings doesn't work in the external tools settings.

* **Expected result:** 

External tool parameter: [commands] %1 [other commands]
RSS Guard opening the article: [commands] [ARTICLE URL] [other commands]

- Current result:

External tool parameter [commands] %1 [other commands]
RSS Guard opening the article: [commands] %1 [other commands] [ARTICLE URL]

RSS Guard currently does not recognize the %1 as a placeholder for the article URL it's opening when opening it with an external tool, it always playing the article URL at the end of the command line when opening it with an external tool.

(Setting %1 in the parameter line with or without quotation marks doesn't change the current result)

**Comment by martinrotter** [comment]
Yes. At this point URL placeholder %1 is automatically **appended** to parameters string.

This is obviously problem as you described. Will look into that.

**Comment by martinrotter** [comment]
22de6444d

Added, I tested with "firefox.exe" but pls test. When using quotes make sure to use DOUBLE QUOTES (") to quote your placeholder or other parts of CLI line, this is because there is some extra parsing done on RSS Guard side.

**Comment by RetroAbstract** [comment]
> [22de644](https://github.com/martinrotter/rssguard/commit/22de6444db0c7ae9a2f3746a68850ef4b1a25798)
> 
> Added, I tested with "firefox.exe" but pls test. When using quotes make sure to use DOUBLE QUOTES (") to quote your placeholder or other parts of CLI line, this is because there is some extra parsing done on RSS Guard side.

I would like to test the dev build, however I'm on Windows and you forgot to include the Windows versions of the build.

**Comment by RetroAbstract** [comment]
Tested it, works great.
