### ISSUE TITLE
[BUG]: idented RSS can't be read by RSSGuard - errors

### ISSUE THREAD

**Issue by Owyn** [martinrotter/rssguard#845]
### Brief description of the issue

if xml is idented - rss guard errors, while other rss clients work fine (e.g. quiterss)

### How to reproduce the bug?

add https://realmscans.com/rss

### What was the expected result?

This:
![image](https://user-images.githubusercontent.com/1309656/203305858-df1afbc6-d1c9-471d-9e74-5da6512a1e07.png)

### What actually happened?

This: ![image](https://user-images.githubusercontent.com/1309656/203305572-8143156b-ff13-48fa-b325-f68f4b688e66.png)

### More Info

Simply adding `https://realmscans.com/rss` rss item should reproduce it, if not (in case site admin makes it compatible again - I reported the problem to there too) - here's the pastebin with its current state which causes RSSGuard to error: https://pastebin.com/n2ngqDTk

### Operating system and version

* OS: Win 10
* RSS Guard version: 4.2.2

**Comment by martinrotter** [comment]
The problem is that the XML simply was NOT valid. I do not really care if other programs manage to load invalid XMLs.

If you wish to overcome these invalid XMLs, you can easily do so with "xmllint.exe" tool setup as post-process script like this.

![image](https://user-images.githubusercontent.com/1255302/203486825-d1d85151-b593-4bb5-8050-cfd3ca3d905e.png)

You can download xmllint.exe from internet.

**Comment by Owyn** [comment]
> I do not really care if other programs manage to load invalid XMLs.

Neither do users care, they will just switch to a **working** program 🤷🏻

**Comment by martinrotter** [comment]
Also, now it works so apparently there was problem in the XML which was fixed.

**Comment by Owyn** [comment]
> Also, now it works so apparently there was problem in the XML which was fixed.

Yea, I wrote to the site admin and he benevolently fixed it, though previous such problem in another site was just ignored by the admin and never got fixed till the site got a major rework (new site simply doesn't have any RSS now)

**Comment by martinrotter** [comment]
It is fair to say that these problems are rather rare. Moreover, I proposed very good solution above which does not really require big PC skills.
