### ISSUE TITLE
[BUG]: Issue with duplicate feeds

### ISSUE THREAD

**Issue by linlinxza** [martinrotter/rssguard#846]
![Screenshot_20221128_143005](https://user-images.githubusercontent.com/11242593/204579275-362a9c8f-c252-47e2-889f-bcd8cdc97a93.png)
### Brief description of the issue

Experiencing duplicate feeds.

### How to reproduce the bug?

1. add filter.
`function filterMessage() {
  if (msg.isAlreadyInDatabase(MessageObject.SameTitle)) {
    return MessageObject.Ignore;
  }
  else {
    return MessageObject.Accept;
  }
}`

2. Add news feeds from similar sources. Ex. CTV.

### What was the expected result?

Feeds without duplicated titles. 

### What actually happened?

Got duplicate feeds.

### Debug log

NA

### Operating system and version

* OS: KDE Neon
* RSS Guard version: 4.2.5

**Comment by akinokonomi** [comment]
@martinrotter, At the time you aliased `isAlreadyInDatabase` to `isDuplicateWithAttribute` (ddb80543), you did not change logic
behind it, so that now it checks for an article attribute across *all* feeds in a database, right?

Because if so, duplicate attributes are only checked in a feed that filter is applied to 
(ie if article with attribute exists in that particular feed). 

The docs are a bit misleading here

> which allows you to perform runtime check **for existence of the article in RSS Guard's database**

**Comment by linlinxza** [comment]
> isDuplicateWithAttribute

So, what I am supposed to do? I don't understand Javascript that well.

**Comment by martinrotter** [comment]
> @martinrotter, At the time you aliased `isAlreadyInDatabase` to `isDuplicateWithAttribute` ([ddb8054](https://github.com/martinrotter/rssguard/commit/ddb805438f30e94e1e7c14986a5dc8170a8b6b1f)), you did not change logic behind it, so that now it checks for an article attribute across _all_ feeds in a database, right?
> 
> Because if so, duplicate attributes are only checked in a feed that filter is applied to (ie if article with attribute exists in that particular feed).
> 
> The docs are a bit misleading here
> 
> > which allows you to perform runtime check **for existence of the article in RSS Guard's database**

No, functionality is still the same, only name of function is updated.

If one ones to check duplicate across all feeds, then you must use `AllFeedsSameAccount` flag as stated in [docs](https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#duplicatecheck-enum).

So like this:

```js
function filterMessage() {
  if (msg.isAlreadyInDatabase(MessageObject.SameTitle | MessageObject.AllFeedsSameAccount)) {
    return MessageObject.Ignore;
  }
  else {
    return MessageObject.Accept;
  }
}
```

**Comment by martinrotter** [comment]
I updated docs a bit.

**Comment by linlinxza** [comment]
> I updated docs a bit.

Thanks. Well, hopefully this works.

**Comment by linlinxza** [comment]
> ```js
> function filterMessage() {
>   if (msg.isAlreadyInDatabase(MessageObject.SameTitle | MessageObject.AllFeedsSameAccount)) {
>     return MessageObject.Ignore;
>   }
>   else {
>     return MessageObject.Accept;
>   }
> }
> ```

Seems like this is working. And this solution seals it for me; I will be sticking to this app. I look forward to the future development of this handy app.  I'm so tired of watching the news (as it's very depressing) and just wanted to filter out everything I didn't want to see. This app does the trick. Thanks again.
