### ISSUE TITLE
[FR]: Localization

### ISSUE THREAD

**Issue by mryun135** [martinrotter/rssguard#847]
### Brief description of the feature request

I just used this software today and found that the localization language I want to use is not fully translated, so I spent some time today on string translation and finished translating the remaining untranslated parts, I don't know when the developer will add the fully translated Simplified Chinese localization to RssGuard

**Comment by martinrotter** [comment]
you translated via Transifex? if so i sync localizations from time to time, usually before each new version is released

**Comment by akinokonomi** [comment]
@mryun135 Translation was synced in one of the latest commits.

You can already check it out in the latest development build: https://github.com/martinrotter/rssguard/releases/tag/devbuild

Please don't forget to backup your config directory first (`C:\Users\<user>\AppData\Local\RSS Guard 4` on Windows), and restore it back after testing the dev build.
Development builds are there for testing purposes only.
