### ISSUE TITLE
[FR]: Option to limit/resize fetched feed icons to 48x48 resolution

### ISSUE THREAD

**Issue by RetroAbstract** [martinrotter/rssguard#853]
### Brief description of the feature request

This feature would allow the user to set RSS Guard to limit the feed favicons fetched when fetching feed metadata to 48x48 by downscaling all icons fetched being at a resultion superior to 48x48 down to 48x48. 

This feature idea came from fetching metadata for a feed from [this invidious instance](https://invidious.weblibre.org/), which downloads the youtube channel's profile picture from the invidious channel page which is [900x900 by default](https://invidious.weblibre.org/ggpht/ytc/AMLnZu_qOpMK0tGNMCnReaXVp4ZvmNEIXn9eKeBGA_x-wQ=s900-c-k-c0x00ffffff-no-rj).

This results in feeds individually weighing 1mb when the 900x900 channel profile picture from Invidious is downloaded and assigned to the feed.

By limiting fetched icons to 48x48, this allows the size of the feeds to remain minimal while maintaining good icon quality in the feed & article lists.

48x48 in my opinion is the best medium of picture size & quality.

**Comment by martinrotter** [comment]
Do you have exact URL feed for me to test?

**Comment by martinrotter** [comment]
Well, in my case RSS Guard does not download that orangey icon, but smaller one - 
![image](https://user-images.githubusercontent.com/1255302/205910981-d7fe48dc-a4c4-4e59-9af8-00f08102defc.png)

For you it really downloads other icon? If so, do you have any other testing feed URL for me?

**Comment by RetroAbstract** [comment]
> Well, in my case RSS Guard does not download that orangey icon, but smaller one - ![image](https://user-images.githubusercontent.com/1255302/205910981-d7fe48dc-a4c4-4e59-9af8-00f08102defc.png)

@martinrotter Strange, I just tried the same link and for me it downloads the channel icon:

![1](https://user-images.githubusercontent.com/103272301/205916749-ec2dc7b6-16bd-4731-8c05-307b2b43f40f.jpg)

> For you it really downloads other icon? If so, do you have any other testing feed URL for me?

Yes, as shown in screenshot above. [Another example URL](https://invidious.weblibre.org/feed/channel/UCRYOj4DmyxhBVrdvbsUwmAA) from [this channel](https://invidious.weblibre.org/channel/UCRYOj4DmyxhBVrdvbsUwmAA) that has[ this as channel profile picture](https://invidious.weblibre.org/ggpht/ytc/AMLnZu9m_XcDSQmTNELyfOqtD2CjxB2Kh-wI21a76Gn5EQ=s900-c-k-c0x00ffffff-no-rj).

Tested just now:

![2](https://user-images.githubusercontent.com/103272301/205917634-9a95c440-f425-4a17-b629-ed70c803e0ac.jpg)

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/205918116-69650de2-a5c1-484e-bdc2-64b01aa3a814.png)

**Comment by RetroAbstract** [comment]
> ![image](https://user-images.githubusercontent.com/1255302/205918116-69650de2-a5c1-484e-bdc2-64b01aa3a814.png)

Ok. When I export feeds with metadata fetched from https://invidious.weblibre.org/ and the exported feed list in Notepad++, it's the same rss:icon= format (string of numbers & characters) for the icon as the same feed(s) but with me manually adding the same icons but downsized to 48x48, just much shorter as the resolution is reduced from 900x900 to 48x48.

Even if it doesn't download the channel icon on your build, any chance the feature could still be implemented?

**Comment by martinrotter** [comment]
OK, I implemented the ticket. Pls test and report back.

**Comment by martinrotter** [comment]
Tweaking behavior, now it will only downscale TOO BIG icons (over 256x256).

**Comment by RetroAbstract** [comment]
I appreciate the quick implementation, however unfortunately the Invidious feed that fetched the channel profile pictures no longer does so:

![1](https://user-images.githubusercontent.com/103272301/206173827-cae4964d-7c17-42d9-a032-2b06209b4d05.jpg)

**Comment by martinrotter** [comment]
This is likely caused by some other change between RSS Guard versions, not related to this ticket.

**Comment by RetroAbstract** [comment]
> This is likely caused by some other change between RSS Guard versions, not related to this ticket.

Tried with both the version it worked on yesterday and the latest dev build, same result.
