### ISSUE TITLE
DB is sometimes "locked" and no data can be updated

### ISSUE THREAD

**Issue by martinrotter** [martinrotter/rssguard#86]
#### Brief description of the issue.

This is issue which is related to #70. It seems that DB sometimes cannot be used as it appears to be "locked".

**Comment by martinrotter** [comment]
@groentebroer I created this repository to solve the "locking DB" problem and not mixing two issues into #70.

**Comment by martinrotter** [comment]
After period of time, user gets:
``
[rssguard] WARNING: Failed to set custom ID for all messages: 'database is locked Unable to fetch row'.
"Use transactions" is not enabled in settings.
``

**Comment by groentebroer** [comment]
That is ok! Running in memory for about a day now and have not seen the issue(s).

**Comment by martinrotter** [comment]
I see. I will re-investigate nonetheless.

**Comment by groentebroer** [comment]
Just to update on the issue. Running in memory, has not shown this error since.

**Comment by martinrotter** [comment]
Yea, at least some kind of solution.

**Comment by martinrotter** [comment]
Closing, as it seems as a rare issue and working workaround exists.
