### ISSUE TITLE
[FR]: autostart with no window

### ISSUE THREAD

**Issue by gianmarcogg03** [martinrotter/rssguard#861]
### Brief description of the feature request

As far as I can tell there is no way to autostart the app at login without having the window appear on screen. It'd be nice if RSS Guard just started in the background so that I can open the window manually from the system tray whenever I want.

**Comment by akinokonomi** [comment]
Do you really need it autostart only?

What about `Settings -> User interface -> Tray area -> Start application hidden`?

**Comment by gianmarcogg03** [comment]
I didn't know that setting existed, thank you.
