### ISSUE TITLE
[BUG]: RSS Guard quit unexpectedly (macOS Ventura, M1)

### ISSUE THREAD

**Issue by highend** [martinrotter/rssguard#863]
### Brief description of the issue

As soon as I open RSS Guard v4.2.7 on macOS Ventura 13.1 (M1 processor) it crashes with "RSS Guard quit unexpectedly".

I tried both versions (mac64.dmg and nowebengine-mac64.dmg).

If you want to have the full crash log (that I could send to Apple), get it from here: https://www.dropbox.com/s/73rxakkakgodvau/rssguard.log?dl=0

### How to reproduce the bug?

I've installed it and started it, no special steps involved...

### What was the expected result?

That at least it shows the GUI

### What actually happened?

It crashed...

### Debug log

time="     0.137" type="debug" -> core: Initializing settings in '/Users/highend/Library/Preferences/RSS Guard 4/config/config.ini' (non-portable way).
time="     0.142" type="info" -> 

GL Type: core_profile
Surface Type: OpenGL
Surface Profile: CoreProfile
Surface Version: 4.1
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: yes

Init Parameters:
  *  application-name RSS%20Guard 
  *  browser-subprocess-path /Applications/RSS Guard.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess 
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-speech-api  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-smooth-scrolling  
  *  enable-threaded-compositing  
  *  in-process-gpu  
  *  use-gl core_profile 

time="     0.283" type="debug" -> database: File-based SQLite database connection 'DatabaseFactory' to file '/Users/highend/Library/Preferences/RSS Guard 4/database/database.db' seems to be established.
time="     0.284" type="debug" -> database: File-based SQLite database has version '4'.
time="     0.284" type="debug" -> gui: Available icon theme paths: QList(:/icons, :/graphics, /Users/highend/Library/Preferences/RSS Guard 4/icons, /Applications/RSS Guard.app/Contents/MacOS/icons)
time="     0.284" type="debug" -> gui: Installed icon themes are: '', 'Breeze', 'Breeze Dark', 'Faenza', 'Numix'
time="     0.284" type="debug" -> gui: Loading icon theme 'Breeze'.
time="     0.285" type="debug" -> gui: Found path of base skin: ':/skins/nudus-base'.
time="     0.285" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_wrapper.html' for the skin.
time="     0.285" type="debug" -> gui: Local file ':/skins/nudus-light/html_style.css' exists, using it for the skin.
time="     0.285" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_enclosure_image.html' for the skin.
time="     0.285" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_single_message.html' for the skin.
time="     0.285" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_enclosure_every.html' for the skin.
time="     0.285" type="debug" -> gui: Local file ':/skins/nudus-light/qt_style.qss' exists, using it for the skin.
time="     0.285" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_adblocked.html' for the skin.
time="     0.285" type="debug" -> gui: Setting style: 'Fusion'.
time="     0.285" type="debug" -> gui: Skin 'nudus-light' loaded.
time="     0.285" type="debug" -> network: Persistent web data storage path: '/Users/highend/Library/Preferences/RSS Guard 4/web/storage'.
time="     0.286" type="debug" -> network: Disabling application-wide proxy completely.
time="     0.288" type="warning" -> Failed to load libssl/libcrypto.
time="     0.288" type="debug" -> core: OpenSSL version: 'Secure Transport, macOS 13.1'.
time="     0.288" type="debug" -> core: OpenSSL supported: 'true'.
time="     0.288" type="debug" -> core: Starting RSS Guard 4.2.7.
time="     0.288" type="debug" -> core: Instantiated class  'Application'.
time="     0.289" type="debug" -> core: Starting to load active localization. Desired localization is 'en_DE'.
time="     0.289" type="warning" -> core: Application localization 'en_DE' was not loaded. Loading 'en_US' instead.
time="     0.289" type="warning" -> core: Qt localization 'en_US' WAS NOT loaded successfully.
time="     0.290" type="debug" -> database: SQLite database connection 'MessagesModel' to file '/Users/highend/Library/Preferences/RSS Guard 4/database/database.db' seems to be established.
time="     0.291" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, CASE WHEN length(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Labels.id IN (SELECT LabelsInMessages.label FROM LabelsInMessages WHERE LabelsInMessages.account_id = Messages.account_id AND LabelsInMessages.message = Messages.custom_id)) as msg_labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1;'.
time="     0.291" type="debug" -> core: Auto-download timer started with interval 10000 ms.
time="     0.291" type="debug" -> core: Creating FeedDownloader singleton.
time="     0.295" type="debug" -> gui: Creating main application form in thread: '0x1f25d3a80'.
time="     0.299" type="debug" -> gui: Current row changed - proxy 'QModelIndex(-1,-1,0x0,QObject(0x0))', source 'QModelIndex(-1,-1,0x0,QObject(0x0))'.
time="     0.302" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     0.376" type="debug" -> gui: Creating tray icon menu.
time="     0.376" type="warning" -> gui: Disabling native menu bar.
time="     0.382" type="debug" -> core: Showing the main window when the application is starting.

### Operating system and version

* OS: macOS Ventura 13.1
* RSS Guard version: 4.2.7

**Comment by guihkx** [comment]
If I understand correctly, the crash log you shared it's for the 'webengine' build. If so, can you please share the crash log of the 'nowebengine' build?

**Comment by highend** [comment]
Sure.

Here is the log for Apple: 
https://www.dropbox.com/s/rs65j1br80jwsyt/rssguard-nowebengine.log?dl=0

And here the one created with rssguard -l <file>:

time="     0.087" type="debug" -> core: Initializing settings in '/Users/highend/Library/Preferences/RSS Guard 4/config/config.ini' (non-portable way).
time="     0.092" type="debug" -> database: File-based SQLite database connection 'DatabaseFactory' to file '/Users/highend/Library/Preferences/RSS Guard 4/database/database.db' seems to be established.
time="     0.092" type="debug" -> database: File-based SQLite database has version '4'.
time="     0.092" type="debug" -> gui: Available icon theme paths: QList(:/icons, :/graphics, /Users/highend/Library/Preferences/RSS Guard 4/icons, /Applications/RSS Guard.app/Contents/MacOS/icons)
time="     0.092" type="debug" -> gui: Installed icon themes are: '', 'Breeze', 'Breeze Dark', 'Faenza', 'Numix'
time="     0.093" type="debug" -> gui: Loading icon theme 'Breeze'.
time="     0.093" type="debug" -> gui: Found path of base skin: ':/skins/nudus-base'.
time="     0.093" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_wrapper.html' for the skin.
time="     0.093" type="debug" -> gui: Local file ':/skins/nudus-light/html_style.css' exists, using it for the skin.
time="     0.093" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_enclosure_image.html' for the skin.
time="     0.093" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_single_message.html' for the skin.
time="     0.093" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_enclosure_every.html' for the skin.
time="     0.093" type="debug" -> gui: Local file ':/skins/nudus-light/qt_style.qss' exists, using it for the skin.
time="     0.093" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_adblocked.html' for the skin.
time="     0.093" type="debug" -> gui: Setting style: 'Fusion'.
time="     0.093" type="debug" -> gui: Skin 'nudus-light' loaded.
time="     0.093" type="debug" -> network: Disabling application-wide proxy completely.
time="     0.095" type="warning" -> Failed to load libssl/libcrypto.
time="     0.096" type="debug" -> core: OpenSSL version: 'Secure Transport, macOS 13.1'.
time="     0.096" type="debug" -> core: OpenSSL supported: 'true'.
time="     0.096" type="debug" -> core: Starting RSS Guard 4.2.7.
time="     0.096" type="debug" -> core: Instantiated class  'Application'.
time="     0.096" type="debug" -> core: Starting to load active localization. Desired localization is 'en_DE'.
time="     0.096" type="warning" -> core: Application localization 'en_DE' was not loaded. Loading 'en_US' instead.
time="     0.096" type="warning" -> core: Qt localization 'en_US' WAS NOT loaded successfully.
time="     0.097" type="debug" -> database: SQLite database connection 'MessagesModel' to file '/Users/highend/Library/Preferences/RSS Guard 4/database/database.db' seems to be established.
time="     0.098" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, CASE WHEN length(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Labels.id IN (SELECT LabelsInMessages.label FROM LabelsInMessages WHERE LabelsInMessages.account_id = Messages.account_id AND LabelsInMessages.message = Messages.custom_id)) as msg_labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1;'.
time="     0.098" type="debug" -> core: Auto-download timer started with interval 10000 ms.
time="     0.098" type="debug" -> core: Creating FeedDownloader singleton.
time="     0.102" type="debug" -> gui: Creating main application form in thread: '0x1f730ba80'.
time="     0.156" type="debug" -> gui: Current row changed - proxy 'QModelIndex(-1,-1,0x0,QObject(0x0))', source 'QModelIndex(-1,-1,0x0,QObject(0x0))'.
time="     0.159" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     0.159" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     0.163" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     0.182" type="debug" -> gui: Creating tray icon menu.
time="     0.183" type="warning" -> gui: Disabling native menu bar.
time="     0.188" type="debug" -> core: Showing the main window when the application is starting.

**Comment by guihkx** [comment]
Thanks.

I might be wrong, but this looks like a Qt bug: https://bugreports.qt.io/browse/QTBUG-102107

Sadly, I couldn't reproduce the crash on my Big Sur VM (it doesn't run on ARM, though)...

In any case, can you check if [this workaround](https://github.com/martinrotter/rssguard/compare/master...guihkx:rssguard:mac-crash-workaround) fixes the crash for you?

If you can't compile RSS Guard yourself, there are also macOS builds ready [here](https://github.com/guihkx/rssguard/releases/tag/devbuild).

**Comment by highend** [comment]
Thanks a lot!

I've downloaded `https://github.com/guihkx/rssguard/releases/download/devbuild/rssguard-devbuild-301a7663-nowebengine-mac64.dmg`

and this release works now :)

**Comment by martinrotter** [comment]
> Thanks.
> 
> I might be wrong, but this looks like a Qt bug: https://bugreports.qt.io/browse/QTBUG-102107
> 
> Sadly, I couldn't reproduce the crash on my Big Sur VM (it doesn't run on ARM, though)...
> 
> In any case, can you check if [this workaround](https://github.com/martinrotter/rssguard/compare/master...guihkx:rssguard:mac-crash-workaround) fixes the crash for you?
> 
> If you can't compile RSS Guard yourself, there are also macOS builds ready [here](https://github.com/guihkx/rssguard/releases/tag/devbuild).

Perhaps this should be merged?

**Comment by guihkx** [comment]
Sure. I'll open a PR.

**Comment by guihkx** [comment]
Ah, didn't noticed one was already open. :D

I've just adjusted the commit message a bit, should be ready to merge now.
