### ISSUE TITLE
[FR]: dark mode

### ISSUE THREAD

**Issue by griffintucker** [martinrotter/rssguard#868]
### Brief description of the feature request

i'll donate $6usd if you implement dark mode, because that's what i pay for my current rss feed manager

**Comment by griffintucker** [comment]
just found the setting for dark mode - will donate $6 next month

**Comment by martinrotter** [comment]
Hi, E there is dark mode, test and let know

**Comment by griffintucker** [comment]
dark mode works great, just not happy about ram usage, but i'll still donate $6usd when i get the chance, probably in 2-6weeks

**Comment by martinrotter** [comment]
@griffintucker  what file exactly did you install?

**Comment by griffintucker** [comment]
using 4.2.7

my mistake re: ram usage - i thought it was using 300mb+ of ram at one stage when i checked it, but i just relaunched it and it's only using <100mb - not sure if this is going to increase, but it if it does, i'll let you know in the appropriate area
