### ISSUE TITLE
RSS Guard v3.3.7 not working on XP SP3

### ISSUE THREAD

**Issue by ozziguy** [martinrotter/rssguard#87]
#### Brief description of the issue.

Version 3.3.7 does not run on XP SP3

The procedure entry point GetUserPreferredUILanguages could not be located in the dynamic link library KERNEL32.dll.

Apparently XP is not supported with QT5 but RSS Guard v3.3.5 still works even though it occasionally crashes and the 'show only unread items' does not always work as expected

**Comment by martinrotter** [comment]
XP is very old OS, more than 14 years. Qt dropped it support some time ago, it was only matter of time when it would finally stop working.

I confirm that on clean XP SP3 install (VirtualBox), RSS Guard really does not work and there is nothing I can do about this.

The reason why 3.3.5 worked is that 3.3.5 used Qt library version 5.7.x. RSS Guard 3.3.7 uses newest Qt library 5.8.0 which brings some new bug fixes and improvements and works best on all supported platforms.

So, I apologise, but I cannot support already obsolete and enterprise-unsupported operating system. :) You should upgrade to Windows 7 or newer operating system.
