### ISSUE TITLE
[BUG]: Window position after restart

### ISSUE THREAD

**Issue by p0k33m0n** [martinrotter/rssguard#871]
### Brief description of the issue

Hi,

Version: rssguard-4.2.7-0bbf91af-nowebengine-win10.exe 

After each restart application main window move into bottom of screen. It doesn't remember position.

### How to reproduce the bug?

1) restart application few times

### What was the expected result?

1) main program window move to bottom of screen

### What actually happened?

n/a

### Debug log

n/a

### Operating system and version

* OS: Windows 10 LTSC
* RSS Guard version: 4.2.7 (latest)

**Comment by martinrotter** [comment]
do you restart by quiting and launching again or via "Restart" feature?

**Comment by p0k33m0n** [comment]
The same situation.

**Comment by martinrotter** [comment]
I am really not able to reproduce the situation.

**Comment by p0k33m0n** [comment]
Fixed wit latest update 4.4.0.
