### ISSUE TITLE
[FR]: Limit database size to X mb/articles

### ISSUE THREAD

**Issue by RetroAbstract** [martinrotter/rssguard#876]
### Brief description of the feature request

This feature would allow users to set RSS Guard to permanently delete articles (from oldest to newest) when the database exceeds X articles or X mb.

Options would include:

- Limit database size to: X articles
- Limit database to: X mb
- Exclude unread articles (would allow database to exceed set database article/size limit): toggle
- Exclude feed(s) from this feature: list of all feeds to toggle desired feeds to exclude from this feature

**Comment by dwh367** [comment]
I would like to be able to limit the number of downloaded articles per feed.  When a person has numerous feeds they don't don't have time to read through a thousand articles total.  Thanks.
