### ISSUE TITLE
[BUG]: Some links (e.g. YouTube) are non-copyable?

### ISSUE THREAD

**Issue by danfe** [martinrotter/rssguard#880]
I've noticed that while I can copy most URLs in the articles via context menu (mouse right-click), **Copy Link Location** menu item is greyed-out on one YouTube video as shown on the attached screenshot.

![unselectable-link](https://user-images.githubusercontent.com/1132291/214495363-e8c48724-41f4-4edb-bf66-05465a4dc4f6.png)

* OS: FreeBSD 13.1
* RSS Guard version: 4.3.0

**Comment by martinrotter** [comment]
provide feed and article URL

**Comment by danfe** [comment]
[Feed](https://www.linux.org.ru/section-rss.jsp?section=1), [article](https://www.linux.org.ru/news/hardware/16694634).  Not sure if it's still there, the article is from 12/17/21, but I should be able to dig the feed item source from my `database.db` if needed.

**Comment by martinrotter** [comment]
> but I should be able to dig the feed item source from my `database.db` if needed.

could be helpful

**Comment by danfe** [comment]
```
sqlite3 database.db 'select contents from Messages where id = 365' > 365.html
gzip 365.html
```
[365.html.gz](https://github.com/martinrotter/rssguard/files/10497256/365.html.gz)

**Comment by martinrotter** [comment]
reported bug upstream not our bug

**Comment by danfe** [comment]
> not our bug

Well, still, tha's kind of violation of the Postel's law on our side.  Plus, your program _already_ displays the link correctly (as blue underlined text) and shows the proper URL in the status bar.  It just for some reason greys out the item in the context menu.  I don't see why it can't  be fixed. :-)
