### ISSUE TITLE
[FR]: Article Filters with full GUI interaction

### ISSUE THREAD

**Issue by Crehet** [martinrotter/rssguard#882]
### Brief description of the feature request

I'm not someone who knows how to code.

The lack of GUI interaction for something like Article Filters, having to add extra javascript code when the app is pretty much all GUI interactive feels odd to me.

So, questions like: How do I filter feeds from https://www.ghacks.net/feed/ to mark every 'Category' that contains 'Firefox' as Read while also giving it the Label of 'Update-Incoming'? Naturally arise. likely this info is already in the docs, but programming docs are Japanese words to me, i dunno english when i see them.

btw, I found this project because i was looking for a replacement for QuiteRSS. said project fills my needs but i had to move on.

**Comment by martinrotter** [comment]
It will not happen. I add prepared examples to article filters window, so describe your desired use case in general and I will add generalized example filter which you can start on.

As for "categories", this is so far supported only partially. I plan to focus on this exact thing in one of upcoming releases.

Filtering is advanced feature and no GUI "designer" will be made by me. Sorry.

**Comment by martinrotter** [comment]
I will make sample filter which does what you want tonight, OK? You will see yourself that it is very elegant and much much more able than hardcoded filters like in QuiteRSS.
