### ISSUE TITLE
[FR]: Two ways to search for articles

### ISSUE THREAD

**Issue by Cronos-lab** [martinrotter/rssguard#886]
### Brief description of the feature request

Hello,

It would be interesting to be able to search two things in the search bar:

- Search for a word only in the title of an article

- Search in the title and in the article.

(It's strange, I thought you could do it before the last update)

After that the software will be perfect! 

Thank you so much !

**Comment by martinrotter** [comment]
so you want to be able to choose if you want to search ONLY in titles or everywhere

**Comment by martinrotter** [comment]
working on this

![image](https://user-images.githubusercontent.com/1255302/218052743-cc8aa18b-8ca9-4e2a-b175-c8216196b2dd.png)

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/218074528-1041f038-0ee4-4526-8423-bbd073cf7f12.png)

**Comment by martinrotter** [comment]
fixed this, added same feature for feed list too
