### ISSUE TITLE
[FR]: Provide the app in .deb format

### ISSUE THREAD

**Issue by VladimirMikulic** [martinrotter/rssguard#887]
### Brief description of the feature request

Hi! I was wondering if it would be possible to provide this app in .deb package format?
Thanks!

**Comment by martinrotter** [comment]
There are no "official" .deb packages and will never be as this is pretty much out-of-scope for me. Providing distro-specific packages is duty of distro maintainers.

There are some packages for Debian/Ubuntu in their repos and bit newer ones here.

https://software.opensuse.org//download.html?project=home%3Anpreining%3Adebian-various&package=rssguard

You can kindly ask the maintainer to rebuild packages to newer release or build with those scripts by yourself. Not that hard really.

Or use Flatpaked RSS Guard which works perfectly fine and is up-to-date.

**Comment by VladimirMikulic** [comment]
I appreciate the fast reply @martinrotter - will ask the maintainer to re-build and release so it can be installed via apt.
