### ISSUE TITLE
[FR]: How to get the app to look native?

### ISSUE THREAD

**Issue by VladimirMikulic** [martinrotter/rssguard#888]
### Brief description of the feature request

I found this screenshot of RSS Guard running on KDE in 2017:
https://victorhckinthefreeworld.com/2017/11/08/rss-guard-un-lector-de-feeds-simple-y-potente/

![rss_guard](https://user-images.githubusercontent.com/35997844/215382734-bef82565-6a55-4b56-9ae0-6b244897783a.png)

This is how it looks like now on my system (AppImage/Flatpak)

![Screenshot_20230130_044153](https://user-images.githubusercontent.com/35997844/215382916-df7a683f-a498-444e-afe3-f221d6f3f430.png)

I tried tweaking "User Interface" in settings, but even after choosing breeze it still looks the same.

**Comment by martinrotter** [comment]
Latest RSS Guard is compiled with Qt 6. Sadly, Qt 6 does not offer "breeze" style so RSS Guard cannot blend into KDE that well.

This is known upstream bug. Your options:

* Recompile RSS Guard with Qt 5 which is supported.
* Switch to another style "engine" like QtCurve or Kvantum.
* Press KDE developers to update [breeze](https://invent.kde.org/plasma/breeze/-/tree/master) to support Qt 6.

As for icons not displaying on toolbar, that is worth of investigating as it seems that "qt6-svg" package is somehow missing in your distro.

**Comment by VladimirMikulic** [comment]
Thanks for a fast response @martinrotter.
That makes sense, the full Qt 6 support will come with KDE 6.

**Comment by Jieiku** [comment]
Ahh... first time user of Rss Guard... installed today and this is what I see:

![2023-05-10_15-03-03](https://github.com/martinrotter/rssguard/assets/106644/672b54d0-d322-4e35-ae83-01d7f996a4e5)

Can I simply install an older version of RSS Guard when QT5 was the default?

**Comment by martinrotter** [comment]
> Ahh... first time user of Rss Guard... installed today and this is what I see: (My theme is Breeze Dark)
> 
> ![2023-05-10_15-03-03](https://user-images.githubusercontent.com/106644/237525001-672b54d0-d322-4e35-ae83-01d7f996a4e5.png)
> 
> Can I simply install an older version of RSS Guard when QT5 was the default?

Please create separate issue.

**Comment by Rex000** [comment]
> Ahh... first time user of Rss Guard... installed today and this is what I see: (My theme is Breeze Dark)
> 
> ![2023-05-10_15-03-03](https://user-images.githubusercontent.com/106644/237525001-672b54d0-d322-4e35-ae83-01d7f996a4e5.png)
> 
> Can I simply install an older version of RSS Guard when QT5 was the default?

Breeze dark is for dark mode. Use Breeze.

**Comment by Jieiku** [comment]
> Breeze dark is for dark mode. Use Breeze.

Actually my operating system IS in dark mode, which is why I said Breeze Dark.

> jesus, simply change your icon theme in settings.

I installed the package from rssguard-git from the AUR instead of using pacman and it was no longer a problem.

**Comment by Jieiku** [comment]
It now looks as it should:

![2023-05-12_08-43-35](https://github.com/martinrotter/rssguard/assets/106644/bd53499f-b752-4f84-a848-2eff1aa2dbf6)

And these are the theme settings I chose:

![2023-05-12_08-37-16](https://github.com/martinrotter/rssguard/assets/106644/ac845ed8-55b2-4b03-92e0-9c4ae10fc2a8)
