### ISSUE TITLE
Feature Request: Multi-select feeds to adjust settings and display

### ISSUE THREAD

**Issue by ozziguy** [martinrotter/rssguard#89]
An option to multi-select feeds and adjust the update interval and other settings. Currently everything must be done individually per feed and is time consuming

**Comment by martinrotter** [comment]
- [ ] - multi select to display messages from all selected feeds
- [ ] - multi select to edit common properties

**Comment by Rex000** [comment]
+1 from my side

**Comment by martinrotter** [comment]
Fixed in latest development code, feature will be polished and related bugs fixed soon. PLS test.

**Comment by martinrotter** [comment]
https://github.com/martinrotter/rssguard/pull/1148
