### ISSUE TITLE
[FR]: Preserve feed names when importing/exporting opml.

### ISSUE THREAD

**Issue by 1bcb** [martinrotter/rssguard#891]
### Brief description of the feature request

Steps to reproduce:
1)Add some RSS feeds.
2)Right-click one of the RSS feeds, and select "edit item."
3)Change the name of the feed to something other than the default.
4)Export all your feeds as an OPML file.
5)Import your OPML file in RSS Guard on another computer.

Actual results: 
Any edits you made to the feed names are erased: all feeds now have their default names.

Desired results: 
Any changes you make to the feed names should be preserved when exporting and importing an OPML file.

Rationale: 
Many RSS feeds have default names which are not descriptive (such as "feed" or "posts.")  If you follow a lot of feeds, renaming is essential to keeping them organized.  I prefer to store all my RSS feeds locally and not use a centralized RSS syncing service, but I use OMPL files as a way to backup the feeds I follow, as well as to copy them between computers.  It would be really nice if this backup included user-entered feed names.

**Comment by martinrotter** [comment]
Take a close look on opml import dialog.

**Comment by 1bcb** [comment]
Ah, I see I just needed to uncheck the "fetch online metadata" button before importing.  Thanks!
