### ISSUE TITLE
[BUG]: Cleanup database will cause deleted recent articles to re-appear after fetching again

### ISSUE THREAD

**Issue by Bro-Account** [martinrotter/rssguard#895]
### Brief description of the issue

Hi,
I noticed that already deleted articles from a feed will re-appear after running the database cleanup using the options `Remove all articles from recycle bin` and `Optimize database file`.

### How to reproduce the bug?

1. Delete some or all of the recent articles from a feed
2. Run `Cleanup database` with options `Remove all articles from recycle bin` and `Optimize database file`
3. Fetch the feed again

### What was the expected result?

Already fetched and deleted articles should not re-appear

### What actually happened?

All articles in the current feed file will re-appear as unread articles, whether or not they have been downloaded/deleted before

### Debug log

No debug log

### Operating system and version

* OS: Win 11 22H2 / Ubuntu 22.10 Raspberry Pi
* RSS Guard version: 4.3.2

**Comment by akinokonomi** [comment]
This is exactly what cleanup database feature is for.

If you want to clean up the recycle bin but keep those articles in database to prevent them from reappearing, right click recycle bin in a feed list and click "Empty recycle bin".

**Comment by Bro-Account** [comment]
I would have expected that this is for reducing the database size and optimizing the application performance without changing the application behavior. At least this is how this is the result in other applications using similar functions.

**Comment by martinrotter** [comment]
it does exactly what it states, if you only check "optimize db....", then db will be "optimized" and nothing will be actually purged

**Comment by Bro-Account** [comment]
Where does it state so? You mean the recycle bin option? I don't think this is obvious that the recycle bin is also linked to the downloaded/processed state. At least in Thunderbird or RSSOwl(Nix) it is not.

For me this was kind of unexpected and I even checked if there was some kind of warning anywhere, but it's fine if this is by design.

**Comment by martinrotter** [comment]
i will add warning

**Comment by Bro-Account** [comment]
Ah, one more thing:
Before submitting the report I tested if deleting the articles from the recycle bin manually would do the same and it does not. Even if the articles are completely gone from the application, it's still remembering the downloaded state. This is why I saw nothing indicating the actual behavior in the cleanup dialog.
