### ISSUE TITLE
[BUG]: Excessive memory usage

### ISSUE THREAD

**Issue by Mitecon** [martinrotter/rssguard#898]
### Brief description of the issue

I'm another convert from QuiteRSS. I've used RSS Guard in the past but until the past couple of days I haven't had the time to begin using it properly. I exported my feeds from QuiteRSS and imported into RSS Guard. All has been fine. Performance is great so far - not that I have much in my database which is currently 8.6MB. Not exactly pushing the limits. However, RAM is filling up as time goes on.

![rssguard-Screenshot_2023-02-19_20-47-29](https://user-images.githubusercontent.com/125831943/219975754-66388e4e-01fd-4f4a-bb73-db6d8185ac9e.png)

I will say that during my conversion to RSS Guard I've gone through a few of the releases. As in:

A while back I installed the version from my repository (Manjaro) but I remember it being out of date with the latest release here. So I left it a continued with QuiteRSS as I didn't have the time to switch. RSS readers demand some attention - they're not simple set and forget programs. I'd assumed repo out of date thing was still the case a couple of days ago when I tried it again. So I downloaded the appimage and began using that. Then I realised it was the noweb version. You don't see all the versions available until you click to expand. So next I got the 'full' appimage and ran that. Then I thought to look at my repo and saw it was up to date and so I installed that instead.

The point is - this whole time I was simply 'continuing' to use RSS Guard. As in - I didn't delete my database between versions. However - is that enough to cause this problem?

### How to reproduce the bug?

There are no particular steps to reproduce. Simply run it and use it/leave it alone. I do notice memory usage creeps up whenever I mark a feed as read. But also sometimes not. These are feeds with a handful of articles in them so nothing heavy.

### What was the expected result?

I see issues where people say there's excessive memory usage and they mention something like 100MB or so. I'd be happy with that. At the moment, RSS Guard is far more memory hungry than QuiteRSS and that database is 708MB and I've had it forever. QuiteRSS is currently sitting at 711,280K after 3 days 10 hours and it has a ton of filters that run on everything in the database - not just new articles. So there's something clearly wrong when RSS Guard's database is 8.6MB and a handful of filters pulling feeds every 15 minutes and that's enough to eat all my RAM. I have a total (according to the log) of 96 feeds but a bunch of them are disabled and not active.

### What actually happened?

Sadness and disappointment. I was so full of hope.

### Debug log

I did grab a debug log which is 5.9MB from only a short time (~19 minutes) of running. At the end of the log I used the File menu to restart but it only continued to log to file. I exited properly to restart shortly after to stop logging.

Also, I've redacted the hell out of this thing but presumably you'll get the gist.

[rssguard.log](https://github.com/martinrotter/rssguard/files/10778014/rssguard.log)

### Operating system and version

* OS:
Operating System: Manjaro Linux
KDE Plasma Version: 5.26.5
KDE Frameworks Version: 5.102.0
Qt Version: 5.15.8
Kernel Version: 5.15.93-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 8 × AMD Ryzen 7 3700X 8-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GT 1030/PCIe/SSE2
Manufacturer: QEMU
Product Name: Standard PC (Q35 + ICH9, 2009)
System Version: pc-q35-4.2
(Yes, my system looks a bit funky but it's solid - the system is not the problem)

* RSS Guard version: 4.3.2

**Comment by martinrotter** [comment]
do you see any memory hungriness differences between "full" and "nowebengine" versions?

if you try to use "nowebengine" for some hours, do you see LOWER memory consumption?

**Comment by martinrotter** [comment]
> I'll run this for today but I'd rather not use nowebengine. When I view articles, I cannot zoom the text. Headlines in articles are the only things that seem to zoom so it makes the articles themselves unreadable because they're simply far too small. Also, I want to be able to see the full web page for certain things. So it's really 'Full' that I want but for testing purposes I'll continue to run 'Lite'.

Nowebengine version allows article text zooming the same way as "full" version - mouse wheel + CTRL. Also, links are normally clickable and websites are displayed with simpler formatting. Also, images can be displayed.

![image](https://user-images.githubusercontent.com/1255302/220120017-f01480db-067a-474d-979a-684b1302aaff.png)

To original problem - ok pls test and report back with findings.

**Comment by martinrotter** [comment]
Looked into this.
Issue is likely associated with some SQLite properties set by RSS Guard. I tried to mitigate the problem. Please, try latest development build if RAM usage is now better.
