### ISSUE TITLE
[BUG]: Can't read metadata

### ISSUE THREAD

**Issue by FreePaul** [martinrotter/rssguard#899]
### Brief description of the issue

https://coollib.net/new/rss
Can't read metadata and do not update feed
QuiteRSS succesfully read all data for this RSS

### How to reproduce the bug?

1. Right click on my category
2. Choose "Add new feed"
3. Fill all fields with red mark
4. Press OK button
5. Right click on new item, choose "Fetchmetadata"
6. Got error message
![RSSGuard](https://user-images.githubusercontent.com/21068457/220059130-e907d02a-859d-41dc-85ab-3bdbf49396f3.jpg)

Changing "Type" don't give needed result.

### What was the expected result?

Get RSS data

### What actually happened?

Nothing

### Debug log

[rssguard.log](https://github.com/martinrotter/rssguard/files/10782409/rssguard.log)

### Operating system and version

* OS: Windows 10
* RSS Guard version: 4.3.2

**Comment by martinrotter** [comment]
I checked https://coollib.net/new/rss and at that address there is no XML RSS/ATOM feed.

Also I checked with W3C feed validator which also does not see the feed.

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fcoollib.net%2Fnew%2Frss

**Comment by martinrotter** [comment]
No response, closing.
