### ISSUE TITLE
Problem syncing TTRSS feeds

### ISSUE THREAD

**Issue by lazypete365** [martinrotter/rssguard#9]
Hi, I'm not sure if this is a bug or if I have misconfigured something. I have a TTRSS setup in my home server, version 67f3e3f (API v.13), working normally with multiple accounts and the API enabled. When I configure RSSGuard to sync with it, I input my URL, user name and password and it passes the test. The account shows up in the feed list with all the folders and feeds and favicons in place, as it should.

But when I hit "update all items", most feeds turn red and appear empty. Only a few feeds sync properly, maybe 5 or 6 out of 72, different each time I try. The feeds that do update show the read and unread news items properly. I have tried to account for connection timeouts by setting RSSGuard to the maximum (15 seconds, I believe), but the feeds seem to give up much sooner then that. I have also tried to sync with a completely new account, with similar results.

I don't think RSSGuard generates any logs, so I'll add a few screenshots in case it helps clarify things:

This is the TTRSS account config. Test passes:
![rssguard-sync failure 2](https://cloud.githubusercontent.com/assets/9962097/13029711/f612c930-d293-11e5-8e9b-2524e6e86fbf.PNG)

This is the feed list, showing one of the feeds that have updated properly:
![rssguard-sync failure](https://cloud.githubusercontent.com/assets/9962097/13029681/13c84e1a-d293-11e5-9efc-4f219d91ae4d.PNG)

And this is one of the feeds that failed to update. It shows fully populated and updates without errors in TTRSS, but not in RSSGuard:
![rssguard-sync failure 3](https://cloud.githubusercontent.com/assets/9962097/13029726/747626e6-d294-11e5-823a-b676ef69f5b3.PNG)

After checking that feed in TTRSS and then trying to update it individually in RSSGuard it managed to sync, but I did the same thing with a different feed and sync still failed, so that could have been a fluke.

**Comment by martinrotter** [comment]
Hello. I discovered bug, that caused that custom HTTP timeout set in settings was ignore by TT-RSS plugin. Download of new messages fails when the request times out. I will fix the bug and let you know here.

**Comment by martinrotter** [comment]
Okay, check this out - https://github.com/martinrotter/rssguard/commit/558768870aca9627f65e0cb83cd12ac9a9e06369

Now remember also this. If you TT-RSS server checks for new messages by itself automatically, then UNCHECK option "Force server-side update...." in TT-RSS account settings in your RSS Guard. It will speed up updating of your feeds.

Timeout setting should now WORK, try to set higher values and try again. Let me know results

**Comment by lazypete365** [comment]
I can't install the tools to compile it in this computer. I'll test it as soon as I can, though.

**Comment by martinrotter** [comment]
Okay. I compiled test version for your.

http://wikisend.com/download/292320/rssguard-3.1.0-win32.zip

Let me know results.

**Comment by lazypete365** [comment]
Ok, tested and working perfectly, thanks. I've enabled again the "force server-side update" option and now it seems like the timeout is responding as it should. 

Leaving that option enabled is still inadvisable, though, because TTRSS often takes longer than the maximum of 15 seconds to refresh some slower feeds. No fault of RSSGuard, of course, but you might think of making that option unchecked by default when creating a new account, adding a warning to the new account dialog that the option may make updates slow and timeout for some feeds or increasing the maximum timeout as a workaround. I think any of those would help new users avoid that trap.

**Comment by martinrotter** [comment]
Yes, preferably slower TT-RSS instances are sometimes so slow that even 15 s timeout is not enough.

I will:

 * increase max timeout to 60 s,
 * make that checkbox by default unchecked,
 * add label with some info.

**Comment by gerroon** [comment]
I have this exact issue with 3.5.9 against ttrss 19.2 on Debian Buster with Apache and MySql
