### ISSUE TITLE
[BUG]: text body is wrapped without logic at the end of the window

### ISSUE THREAD

**Issue by Skywriter960** [martinrotter/rssguard#900]
### Brief description of the issue

Hello, 

the Westdeutscher Rundfunk, WDR Cologne, has been delivering RSS-feeds for some time, which are not wrapped in the usual lines.

The text body is wrapped without logic at the end of the window by RSS Guard. This results in character/word fragments without meaning.

This only happens with WDR Cologne. The problem does not occur with other RSS feed players:   

They are all WDR radio links. Here is an example:
https://www1.wdr.de/mediathek/audio/wdr5/quarks/wissenschaft-und-mehr-100.podcast

As a normal user I cannot judge if the problem is with the program or if the WDR feed is delivered incorrectly.

If it is the fault of WDR, please make it clear to WDR that this is absolutely not possible. There are RSS feed standards.

I don't want to have to look for a new feed program for the third time because of WDR!

Thanks in advance for the effort.

Greetings,
Skywriter960

Translated with www.DeepL.com/Translator (free version)

### How to reproduce the bug?

Yes, with news download RSS-Feeds

### What was the expected result?

same

### What actually happened?

same

### Debug log

How get I a log?

### Operating system and version

'Win 10 19045.xxxx
* RSS Guard version: 4.3.2

**Comment by akinokonomi** [comment]
@martinrotter Comment from me: No idea why it's happening.

Loaded the same page from article previewer in ff and chromium, no such problem there.

Then tried different values for properties `word-break` and `overflow-wrap` (and with neither of them) back in rss guard, the result is either this or the line overflows the screen.

Maybe it's a qtwebengine limitation, bug, etc. 
For now, I don't think it's possible to fix it properly from my side.

Tested with qtwebengine `6.4.2` only.

Side note: rss guard gets the article content from the `<content:encoded>` element, not `<description>` element (all feed items have both).

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/225598978-105be45f-2ec9-43fd-9a1e-97e3aa0c7e6f.png)

I do not see any defects. Please specify exactly, prefarably with pictures, what you see wrong.

**Comment by Skywriter960** [comment]
Thank you very much for your reaction.

Once again: I have your current programme version and have now made a screenshot:



Your example is from last year and my problem is only with the West German Broadcasting Corporation in D-Cologne! Text wrap is fine with other feeds! That's why I asked you in the last mail to contact WDR.

Unfortunately, I cannot say when exactly the problem occurred. But it has been going on for 'quite a few' weeks. Then it must be between your screenshots and mine.

Or you have a magic PC ... ;-)

Sorry for the trouble, but I am just a simple PC user and am basically happy that your programme exists.

Best regards
Skywriter

Translated with DeepL



Von: martinrotter
Gesendet: Donnerstag, 16. März 2023 12:08
An: martinrotter/rssguard
Cc: Skywriter960; Author
Betreff: Re: [martinrotter/rssguard] [BUG]: text body is wrapped without logicat the end of the window (Issue #900)


I do not see any defects. Please specify exactly, prefarably with pictures, what you see wrong.

**Comment by akinokonomi** [comment]
@martinrotter See words "vererben" "Ameisen" on your screenshot. 
Words should not break in the middle like that. 
Whole words should wrap.

**Comment by martinrotter** [comment]
@akinokonomi Yes, this has clearly something to do with "nudus-*" CSS? Can you perhaps fix?

**Comment by akinokonomi** [comment]
> Yes, this has clearly something to do with "nudus-*" CSS? Can you perhaps fix?

You missed my comment here https://github.com/martinrotter/rssguard/issues/900#issuecomment-1442850720

> No, problem was not in the skin itself. I found the problem.

Just checked 085d5be9, seems to be fixed for me too. Thanks!
