### ISSUE TITLE
[FR]: builds for raspberry

### ISSUE THREAD

**Issue by pipiscrew** [martinrotter/rssguard#901]
### Brief description of the feature request

is possible on next release to have : 

- armhf for ARMv7 (32-bit) 
- arm64 for ARMv8 (64-bit)

?

**Comment by guihkx** [comment]
GitHub Actions doesn't have native ARM runners, but in theory his should be doable with [QEMU](https://github.com/docker/setup-qemu-action#readme). The caveats are: being limited to Linux, and possibly taking a very long time to compile.

For aarch64, an easier way would be just using one of the official Flatpak packages: [Lite](https://flathub.org/apps/details/io.github.martinrotter.rssguard), [Regular](https://flathub.org/apps/details/io.github.martinrotter.rssguardlite).

**Comment by martinrotter** [comment]
Rssguard Is available on flathub which does have arm builds
