### ISSUE TITLE
[BUG]: Failing loading images from RSS feed with authentication enabled

### ISSUE THREAD

**Issue by lrea** [martinrotter/rssguard#909]
### Brief description of the issue

The tool fail loading images from authenticated Jira and Confluence RSS feeds, I suppose it's because authentication is only used to retrieve content of articles, not to load images.

### How to reproduce the bug?

add a feed which points to an RSS Feed with authentication enabled

### What was the expected result?

loading images inside articles

### What actually happened?

content of article is showed without images (they appear with a broken icon)

### Debug log

no relevant info

### Operating system and version

* OS: Windows 10
* RSS Guard version: 4.3.2

**Comment by martinrotter** [comment]
EDIT: Just checked with some Jira/Confluence acc I have. Personal activity stream feed is really behind authentication and Jira does have "personal access token" feature. The token can be generated on the website and then is passed to each auth request via "Authentication" feature.

**Comment by martinrotter** [comment]
started to work on this

![image](https://user-images.githubusercontent.com/1255302/225640934-7df8919d-7a0d-4125-ba48-26433d70d450.png)

**Comment by martinrotter** [comment]
checked with my Qt Bugreports acc and images work now, but this is now highly experimental feature

![image](https://user-images.githubusercontent.com/1255302/225641299-55ce7e91-acc8-4c43-95fd-f0482ad1963e.png)

**Comment by lrea** [comment]
Is there any chance to have a minor release with the issue fixed ?

**Comment by martinrotter** [comment]
Yes, but you can always download development build.
