### ISSUE TITLE
Feature Request: Show update time remaining

### ISSUE THREAD

**Issue by ozziguy** [martinrotter/rssguard#91]
Somewhere to show the next update time remaining. Maybe in the tray icon balloon and on the main window somewhere, such as a column ?

**Comment by martinrotter** [comment]
Where should such a time be displayed? In a feed's tooltip? Or directly in feeds list? Note that each feed can have different time remaining + there is one global time remaining (default setting).

**Comment by martinrotter** [comment]
I added a more complete tooltips for all feeds.

**Comment by martinrotter** [comment]
No response, I added more comprehensive tooltips. Therefore, this is done.
