### ISSUE TITLE
[BUG]: Intermittently locked out of fetching

### ISSUE THREAD

**Issue by God-damnit-all** [martinrotter/rssguard#910]
### Description of the issue

Seemingly at random, RSS Guard will stop fetching feeds after a while, and the ability to manually fetch feeds or add new feeds will be locked out, as if it thinks it's still fetching feeds in the background.

### Symptoms

1. Options that are disabled during feed fetching will be locked/grayed out, as if fetching is still happening in the background
2. The button to Stop ongoing fetching will be locked/grayed out, indicating that no feed fetching is currently happening
3. As expected, the progress bar shown during fetching won't be active

![image](https://user-images.githubusercontent.com/53661808/226140137-d939e7ca-08df-47aa-b62a-2314d9d8046e.png)
![image](https://user-images.githubusercontent.com/53661808/226140126-8aff44f9-88e5-4cd5-8a50-8dc4ade51b72.png)
![image](https://user-images.githubusercontent.com/53661808/226140114-edd1ae9a-b1a0-4986-be50-6ad8475b8467.png)

### Additional details

I'm using Python (3.11) scripts to convert certain HTML fetched pages to RSS feeds, so that might be related. Maybe RSS Guard's Web Engine is somehow it's getting stuck trying to retrieve a page (Cloudflare-related maybe?), or perhaps there's some sort of issue with the Python script (but if that's the case I'm not sure why the abort option is locked/grayed out).

### Debug log

I have a lot of personal feeds and I'd rather not post the full debug log publicly. If there is a place I can email a full debug log, I'll do so.

Here's what I believe is relevant, though:
```text
time=" 14403.808" type="debug" -> core: Filter accepts row 'User (RSS/ATOM/JSON)' and filter result is: 'true'.
time=" 14403.814" type="debug" -> CTRL is NOT pressed while sorting articles - sorting with standard mode.
time=" 14403.816" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, CASE WHEN length(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Labels.custom_id IN (SELECT LabelsInMessages.label FROM LabelsInMessages WHERE LabelsInMessages.account_id = Messages.account_id AND LabelsInMessages.message = Messages.custom_id)) as msg_labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE Feeds.custom_id IN ('59') AND Messages.is_deleted = 0 AND Messages.is_pdeleted = 0 AND Messages.account_id = 1 ORDER BY Messages.date_created DESC;'.
time=" 14403.817" type="debug" -> gui: Reloading of msg selections took 3 miliseconds.
time=" 14403.827" type="debug" -> gui: Hovered link: 'QUrl()'.
time=" 14403.828" type="debug" -> core: Silencing GUI message: ''.
time=" 14411.367" type="debug" -> feed-downloader: No feeds to update in worker thread, aborting update.
time=" 14411.367" type="debug" -> core: Notification for event '3' not found
time=" 14411.367" type="debug" -> core: Silencing GUI message: 'I will auto-download new articles for 1 feed.'.
time=" 14421.092" type="debug" -> core: Delaying scheduled feed auto-downloads and message state synchronization for one minute due to another running update.
time=" 14431.091" type="debug" -> core: Delaying scheduled feed auto-downloads and message state synchronization for one minute due to another running update.
time=" 14441.090" type="debug" -> core: Delaying scheduled feed auto-downloads and message state synchronization for one minute due to another running update.
time=" 14451.087" type="debug" -> core: Delaying scheduled feed auto-downloads and message state synchronization for one minute due to another running update.
time=" 14461.088" type="debug" -> core: Delaying scheduled feed auto-downloads and message state synchronization for one minute due to another running update.
time=" 14471.086" type="debug" -> core: Delaying scheduled feed auto-downloads and message state synchronization for one minute due to another running update.
time=" 14481.087" type="debug" -> core: Delaying scheduled feed auto-downloads and message state synchronization for one minute due to another running update.
time=" 14491.087" type="debug" -> core: Delaying scheduled feed auto-downloads and message state synchronization for one minute due to another running update.
time=" 14501.092" type="debug" -> core: Delaying scheduled feed auto-downloads and message state synchronization for one minute due to another running update.
time=" 14511.090" type="debug" -> core: Delaying scheduled feed auto-downloads and message state synchronization for one minute due to another running update.
time=" 14521.082" type="debug" -> core: Delaying scheduled feed auto-downloads and message state synchronization for one minute due to another running update.
time=" 14531.094" type="debug" -> core: Delaying scheduled feed auto-downloads and message state synchronization for one minute due to another running update.
time=" 14541.088" type="debug" -> core: Delaying scheduled feed auto-downloads and message state synchronization for one minute due to another running update.
```
_(It will continue to do the 'Delaying scheduled feed' line until I restart the program.)_

### Operating system and version

* OS: Windows 10 22H2
* RSS Guard version: 4.3.2 rev 085d5be9

**Comment by martinrotter** [comment]
> This hasn't happened in the past 24 hours (even though I haven't changed anything), whereas before it was happening at least once every three hours. I think it has to be related to the retrieval via WebEngine getting stuck on something, rather than anything to do with the Python scripts.

I see. Do you use anything "special" in your setup? Article filters, web scraping or?

**Comment by martinrotter** [comment]
I see. I was not able to replicate so far. Could you perhaps create some minimal setup (`data4` folder) and share the folder with me including scripts you use etc.?

**Comment by martinrotter** [comment]
Yes: rotter.martinos(at)gmail.com

**Comment by BoboGargle** [comment]
I've just installed a day or so ago, same issue. Does not update, cannot manually update. Only solution is a restart.,

**Comment by martinrotter** [comment]
Can you share your data folder?

**Comment by BoboGargle** [comment]
Setting the feeds to the global interval appears to have resolved the problem for me too.

**Comment by martinrotter** [comment]
Could anyone post config which triggers the issue?

**Comment by martinrotter** [comment]
OK, guys, it was beginner noobish classic programming fault. It should be fixed. Test and see and report back.
