### ISSUE TITLE
[FR]: Ability to organise list of Article Filters

### ISSUE THREAD

**Issue by RetroAbstract** [martinrotter/rssguard#912]
### Brief description of the feature request

Hi,

This feature would allow the user to organise their Article Filters by allowing them to move up or down any filter in the filter list, just like they can already do with their feeds.

The available options would be:

- GUI Up & Down arrows to move selected article filter(s)
- Ctrl + Up & Down keys to move selected article filter(s) up by 1
- Shift + Ctrl + Up & Down keys to move selected article filter(s) up to the top or botton of list
- Option to sort Article Filters alphabetically

Thanks

**Comment by martinrotter** [comment]
#908 is already filed. Post your complemental subfeatures there.
