### ISSUE TITLE
[BUG]: Feed problem when opening links

### ISSUE THREAD

**Issue by lancilloty** [martinrotter/rssguard#914]
### Brief description of the issue

When trying to open the links of news from the feed "https://photojournal.jpl.nasa.gov/rss/new" the URL is broken and in turn becomes "https://photojournal.jpl.nasa.gov/%20https://photojournal.jpl.nasa.gov/catalog/PIA25875" instead of being "https://photojournal.jpl.nasa.gov/catalog/PIA25875". 

### How to reproduce the bug?

1. Add the feed https://photojournal.jpl.nasa.gov/rss/new to RSS Guard.
2. Open "news" from the feed.
3. See the 404 error page from the broken link provided by RSS Guard.

### What was the expected result?

The webpage should be in this format: "https://photojournal.jpl.nasa.gov/catalog/PIA25875"

### What actually happened?

The webpage was in this format: "https://photojournal.jpl.nasa.gov/%20https://photojournal.jpl.nasa.gov/catalog/PIA25875"

### Debug log

io.github.martinrotter.rssguard.desktop[7546]: time=" 10595.231" type="debug" -> gui: Message list got focus with reason 'Qt::ActiveWindowFocusReason'.
io.github.martinrotter.rssguard.desktop[7546]: time=" 10633.714" type="debug" -> gui: Message list got focus with reason 'Qt::ActiveWindowFocusReason'.
io.github.martinrotter.rssguard.desktop[7546]: time=" 10703.893" type="debug" -> gui: Message list got focus with reason 'Qt::ActiveWindowFocusReason'.
io.github.martinrotter.rssguard.desktop[7546]: time=" 10705.133" type="debug" -> gui: Hovered link: 'QUrl(https://photojournal.jpl.nasa.gov/ https://photojournal.jpl.nasa.gov/catalog/PIA25875)'.
io.github.martinrotter.rssguard.desktop[7546]: time=" 10705.167" type="debug" -> gui: Hovered link: 'QUrl()'.
io.github.martinrotter.rssguard.desktop[7546]: time=" 10705.483" type="debug" -> gui: Hovered link: 'QUrl(https://photojournal.jpl.nasa.gov/ https://photojournal.jpl.nasa.gov/catalog/PIA25875)'.
io.github.martinrotter.rssguard.desktop[7546]: time=" 10706.377" type="debug" -> gui: Hovered link: 'QUrl()'.
io.github.martinrotter.rssguard.desktop[7546]: time=" 10708.525" type="debug" -> gui: Hovered link: 'QUrl()'.
io.github.martinrotter.rssguard.desktop[7546]: time=" 10708.988" type="warning" -> javascript: Uncaught TypeError: document.head.appendChild(...) is not a function (source: https://photojournal.jpl.nasa.gov/js/header.js:240)
io.github.martinrotter.rssguard.desktop[7546]: time=" 10754.509" type="debug" -> core: Saved data with auto-saver for 'CookieJar' and method 'saveCookies'.
io.github.martinrotter.rssguard.desktop[7546]: time=" 10780.506" type="debug" -> core: Delaying scheduled feed auto-download for some time since window is focused and updates while focused are disabled by the user and all account caches are empty.

### Operating system and version

* OS: Ubuntu 22
* RSS Guard version: 4.3.3 Flatpak

**Comment by martinrotter** [comment]
Hi, your feed contains semantic errors, specifically:

```xml
<link><![CDATA[ https://photojournal.jpl.nasa.gov/catalog/PIA25877]]></link>
```

It adds space in front of the article URL. But ok, I will fix these in rssguard additionally.

**Comment by martinrotter** [comment]
Fixed, clear your feed data and re-fetch your articles with fixed version.

**Comment by lancilloty** [comment]
@martinrotter I just updated to the latest version and it worked beautifully :) Thanks a lot
