### ISSUE TITLE
[FR]: Read a full article directly

### ISSUE THREAD

**Issue by Cronos-lab** [martinrotter/rssguard#916]
### Brief description of the feature request

Hello,
RSS Guard is really better now! I really like this program and your job!

I had an idea using the RSS feed application : Feeder. Available here:
https://f-droid.org/en/packages/com.nononsenseapps.feeder/
In this application, there is a function to read the article directly in the application.

Is it possible to create this function in RSS Guard?
That way you don't have to go to an external site to read the article. Of course this only works on free websites.

Thank you so much!

**Comment by martinrotter** [comment]
Hi.
In RSS Guard there is also option to read source articles directly. You simply click "URL" part of your article and its source full website/article will load. See video below.

![rssguard_qqXxkk5FE0](https://user-images.githubusercontent.com/1255302/232377794-7d338bb5-7064-4944-93da-31ad1ed9d864.gif)

You can even use what we call "reader mode" which will reflow and simply your article formatting for better readability.

Let me know if this is now solved.

**Comment by martinrotter** [comment]
Give some example feed and article from it and screenshot.

**Comment by martinrotter** [comment]
Yes, now I see that you actually use "nowebengine" variant of RSS Guard. Note that the output of reader mode is different between regular RSS Guard and  "nowebengine" RSS Guard because of some reasons out of RSS Guard's control.

Pls, try regular variant of RSS Guard and report back.

**Comment by martinrotter** [comment]
![rssguard_JfDpGJqfOt](https://user-images.githubusercontent.com/1255302/232478768-467d2b5c-818b-44c1-9900-a130d77fe442.png)

![rssguard_LsuNW2lsc3](https://user-images.githubusercontent.com/1255302/232478789-153eef9c-e0a6-41a8-adad-57a90d55a661.png)

**Comment by Saroumane** [comment]
> You can even use what we call "reader mode" which will reflow and simply your article formatting for better readability.
> 
> EDIT: There is even special hackable feature for advanced users which will let you fetch full article contents automatically and store it locally so it is available even when you are later offline etc.
> 

Hello, I'm looking for this "special hackable feature for advanced users". I would like to "force" reader mode for every article of some feeds (without having to click to the "reader mode" button mode each time I open an article of these feeds)
Thanks !

**Comment by AvivYaish** [comment]
@Saroumane, the following works for me (this is heavily based on @martinrotter's [solution](https://github.com/martinrotter/rssguard/discussions/553#discussioncomment-1820961)):
1. Install [NPM](https://www.npmjs.com/)
2. Open a shell and change the current location to the plugins folder of RSS Guard (Windows default is C:\RSS Guard\plugins), and then run: `npm install @extractus/article-extractor; npm install fetch-charset-detection`
3. In the main menu, select Articles -> Article filters, and add the following as an article filter called ExtractContent:
  ```javascript
  function filterMessage() {msg.contents = utils.runExecutableGetOutput("node", ["-e", `const { extractFromHtml } = await import('@extractus/article-extractor'); const { default: convertBody } = await import('fetch-charset-detection'); const url = '${msg.url}'; try { const res = await fetch(url); const body = await res.arrayBuffer(); const html = convertBody(body, res.headers); const article = await extractFromHtml(html, url); console.log(article.content); } catch (err) {console.log(err);}`]); return MessageObject.Accept;}
  ```
4. Check the feeds that you want to scrape the content for (this is a bit slow, so go over your feeds and make sure you know which ones do not include article content in their feed)
5. Click on "Process checked feeds" (this may take a while)
