### ISSUE TITLE
[FR]: Sort feeds Aa->Zz but not the categories

### ISSUE THREAD

**Issue by RonnyTNL** [martinrotter/rssguard#918]
### Brief description of the feature request

Current "Feed, Sort alphabetically" also sorts the Categories.
Would it be possible to get a "Sort alphabetically" per Category? e.g. in the right mouse context menu for a Category.

So that you can sort the feeds, but keep the Categories order in tact.

**Comment by martinrotter** [comment]
Well, so, in fact you do want to have all your items sorted "manually", but you only want to add action, which would re-sort children of item (feeds of category) alphabetically, but still in "manual" sort mode?
