### ISSUE TITLE
[BUG]: Settings, Feeds & Articles has focus on "Articles" tab while other tabs have focus on the first tab.

### ISSUE THREAD

**Issue by RonnyTNL** [martinrotter/rssguard#922]
### Brief description of the issue

[BUG]: Settings, Feeds & Articles has focus on "Articles" tab while other tabs have focus on the first tab.
So with that logic Feeds & Articles should open with focus on the "Feed fetching" tab.

### How to reproduce the bug?

Open Settings and check Tab focus for e.g. user interface, it's always on the first tab regardless of last selected tab state.

Open Feeds & Articles, notice the focus is on the 3rd tab "Articles".

### What was the expected result?

Focus on "Feed fetching"

### What actually happened?

Focus on "Articles"

### Debug log

N/A

### Operating system and version

* OS: Win10x64 22H2
* RSS Guard version: 4.3.4 - Portable.

**Comment by martinrotter** [comment]
yes, this sometimes happen when i am not focused enough
