### ISSUE TITLE
[BUG]: Regression in 4.3.4 over 4.3.3 regarding dark themes

### ISSUE THREAD

**Issue by koplo199** [martinrotter/rssguard#929]
### Brief description of the issue

The latest update broke dark variant of themes.
Here is the difference between 4.3.3 and 4.3.3 for the `Adwaita-Dark` variant:

![Screenshot from 2023-04-27 10-45-42](https://user-images.githubusercontent.com/85577251/234809992-53850174-9298-4a27-92c6-cd8a512f7a2c.png)
![Screenshot from 2023-04-27 10-46-54](https://user-images.githubusercontent.com/85577251/234810002-d9679cc9-34d9-4c82-8613-4ccc0f017947.png)

### How to reproduce the bug?

1. Use `Adwaita-Dark` on 4.3.3
2. Verify it is working correctly
3. Update to 4.3.4
4. Observe it is now broken

### What was the expected result?

-

### What actually happened?

-

### Debug log

-

### Operating system and version

* OS: ArchLinux
* RSS Guard version:  rssguard-lite-4.3.4-1

**Comment by martinrotter** [comment]
Provide full application log.

**Comment by koplo199** [comment]
[logs_4_3_4.txt](https://github.com/martinrotter/rssguard/files/11342867/logs_4_3_4.txt)
[logs_4_3_3.txt](https://github.com/martinrotter/rssguard/files/11342868/logs_4_3_3.txt)

**Comment by martinrotter** [comment]
Honestly I do not see any suspicious lines as those logs are almost identical. Well. I tried to lower Qt version from 5.15.4 to 5.15.2, it is compilling now.

Perhaps you can test after it compiles.

**Comment by koplo199** [comment]
Sure!

**Comment by martinrotter** [comment]
closing, no progress

**Comment by koplo199** [comment]
@martinrotter I'm sorry but how can it be tested? You said you've been compiling a version which revert the Qt version back but you never posted a link to download this version, which I was unable to find.

**Comment by martinrotter** [comment]
https://github.com/martinrotter/rssguard/releases/tag/devbuild

note that warning

**Comment by koplo199** [comment]
Seems like I survived the experimental build. Unfortunately I cannot reproduce, it seems the AppImage is unable to detect any system style as opposed to the [native package](https://archlinux.org/packages/extra/x86_64/rssguard-lite/), here are the logs:

`QT_DEBUG_PLUGINS=1 rssguard -d /tmp &> native.log`
[native.log](https://github.com/martinrotter/rssguard/files/11635983/native.log)

`QT_DEBUG_PLUGINS=1 ./rssguard-devbuild-ff7e52739-linux64.AppImage -d /tmp &> appimage.log`
[appimage.log](https://github.com/martinrotter/rssguard/files/11635984/appimage.log)

Forcing the style by exporting `QT_STYLE_OVERRIDE=Adwaita` only result in an additional line:
```
time="     0.111" type="warning" -> QApplication: invalid style override 'Adwaita' passed, ignoring it.
	Available styles: Windows, Fusion
```
Note: not using the `-d` parameter does not change anything to the issue

**Comment by koplo199** [comment]
I had more luck with local builds, it allowed me to find the offensive commit: [05b2a825595a803d9d4f298d0bdf959b44d693a1](https://github.com/martinrotter/rssguard/commit/05b2a825595a803d9d4f298d0bdf959b44d693a1)
Reverting it entirely solve the initial issue.

**Comment by koplo199** [comment]
@martinrotter Plese tell me if you need more testing from my side
