### ISSUE TITLE
[FR]: Ability to change color of unread articles

### ISSUE THREAD

**Issue by Rex000** [martinrotter/rssguard#931]
### Brief description of the feature request

Unread articles are bolded which is good, but still often times it's hard to spot an unread article among read articles. I know there is a separate "unread articles" section, but I like to keep an eye on all articles in one place. Hence an option to set unread articles to show in a different color would be very handy.

**Comment by Rex000** [comment]
Actually I'm using the dark theme and the unread articles just show as bolded white without any color:
![exmp0](https://user-images.githubusercontent.com/28770012/235722667-f008ab6c-3c59-46e7-8884-e0d13bad10a8.jpg)

I think mid or light yellow would be a good choice for it.

**Comment by akinokonomi** [comment]
@Rex000 See *Article highlighter* toolbar button. 
You can pick highlight unread articles there.

You can also pick the color which you want it to be highlighted in Settings -> User interface -> Custom skin colors -> Interesting stuff.

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/235833009-55e30c9f-6af4-4152-aa18-43a733d53821.png)

**Comment by Rex000** [comment]
Yes I did try that on dark theme but it still kept it white.

@akinokonomi I followed your instructions and it seems to do the job. Thanks!
