### ISSUE TITLE
[BUG]: Inconsistent window behavior

### ISSUE THREAD

**Issue by Rex000** [martinrotter/rssguard#933]
### Brief description of the issue

Window shows inconsistent behavior.

### How to reproduce the bug?

1. Click on tray icon to hide window
2. Click on tray icon again to bring it back

### What was the expected result?

Smooth fade-in effect when window appears

### What actually happened?

So if I click the "Close" button to close/hide the window then bring the window back by clicking on the tray icon, the window appears with a smooth fade-in effect.

But if I click on the tray icon to close/hide the window then click on it again, the window comes back BUT with a bright flash and no fade-in effect.

Btw the same issue also happens when minimizing the window using the "Hide main window when it is minimized" option in settings.

### Debug log

Don't think it's needed but let me know.

### Operating system and version

* OS: Win 10 x64
* RSS Guard version: 4.3.4

**Comment by martinrotter** [comment]
Fixed.
