### ISSUE TITLE
All items are re-queried after database cleanup

### ISSUE THREAD

**Issue by LiohMoeller** [martinrotter/rssguard#934]
### Brief description of the issue

If I move items to trash and even if I empty the trash (in recent versions), the items are not again fetched from the feed.

But if I do a database with just 'Remove all items from trash' set, the items are again fetched all. Even if the trash was already empty at that time.

### How to reproduce the bug?

1. delete items from feed
2. empty trash
3. optimize database
4. fetch feed

### What was the expected result?

Not all items should re-appear

### What actually happened?

All items are fetched again

### Debug log

-

### Operating system and version

* OS: Linux
* RSS Guard version: 4.0.4

**Comment by martinrotter** [comment]
Well, that feature is called "database cleanup".

This is intended behavior.
