### ISSUE TITLE
[FR]: Copy and paste a normal URL, parse and extract the RSS feed

### ISSUE THREAD

**Issue by shoulders** [martinrotter/rssguard#935]
### Brief description of the feature request

This is a feature that I was use to in RSSOwl and RSSOwlnix and save a lot of time and goes as follows:

- Goto the website you want the feed for, eg `https://www.bleepingcomputer.com/`
- Copy the URL `https://www.bleepingcomputer.com/`
- In RSS Guard add a new feed using the website URL `https://www.bleepingcomputer.com/` as the source
- RSS Guard would notice that it was not a RSS feed, parse the URL and extract the feed `https://www.bleepingcomputer.com/feed/` and then use this instead.

I am using the Firefox addon https://addons.mozilla.org/en-GB/firefox/addon/get-rss-feed-url/ to do the same job.

**Comment by martinrotter** [comment]
![rssguard_r721GlQXMQ](https://user-images.githubusercontent.com/1255302/235675335-6b61df89-70ed-45a2-8804-5bafeac0e5ba.png)

**Comment by martinrotter** [comment]
added as a feature, normally click "Add new feed" and paste URL, all feeds will be discovered
