### ISSUE TITLE
[FR]: 'Add new category' and 'Add newfeed' buttons should be in the toolbar by default

### ISSUE THREAD

**Issue by shoulders** [martinrotter/rssguard#936]
### Brief description of the feature request

On a new installation of RSS Guard I think it would be better to have **the two following buttons** in the toolbar by default. This is one of the first things I went looking for (and found). I would put them before the spacer and search box. I think it will add a little bit more usability for the newer user.
- Add new category
- Add new feed

![image](https://user-images.githubusercontent.com/319997/235672481-df5532c3-7cd6-486a-a5df-62dc3d494771.png)

![image](https://user-images.githubusercontent.com/319997/235672740-71df55ba-f4a5-48c0-9e65-e4c2222a55be.png)

Thanks for the software

**Comment by martinrotter** [comment]
> The parser would also extract the title and fill this in to the 'Feed Title' field.

What do you mean by this?

**Comment by shoulders** [comment]
> The parser would also extract the title and fill this in to the 'Feed Title' field.

This got posted to the wrong issue for some reason. So I have removed it.

**Comment by martinrotter** [comment]
Closing, I do not really want those buttons in toolbar by default. Default toolbar btns seem fine to me.
