### ISSUE TITLE
[BUG]: Tooltips unreadable in dark theme

### ISSUE THREAD

**Issue by Rex000** [martinrotter/rssguard#939]
### Brief description of the issue

Tooltips are dark and unreadable when using dark theme.

### How to reproduce the bug?

Hover the mouse on anything that has a tooltip

### What was the expected result?

Visible tooltips

### What actually happened?

Skin/style/theme: nudus dark/fusion/breeze dark

Currently using this setting and any tooltip shows all dark. They were fine before with the same settings.

![exmp0](https://user-images.githubusercontent.com/28770012/235745564-cd9ecb14-4abf-408d-b871-221c06d3f917.png)
![exmp01](https://user-images.githubusercontent.com/28770012/235745573-e1e5843a-7ea6-4bf7-9175-36cce2d2c4c7.png)

### Debug log

Not needed I believe

### Operating system and version

* OS: Win 10 x64
* RSS Guard version: 4.3.4

**Comment by Rex000** [comment]
Ok I 'fixed' it by switching "breeze dark" with "breeze" and then back to "breeze dark". But still this issue needs to be looked at perhaps.

**Comment by Rex000** [comment]
Ok I 'fixed' it by switching "breeze dark" with "breeze" and then back to "breeze dark". Still I suppose this issue needs to be looked at as to why it happened.

**Comment by akinokonomi** [comment]
Did you restart the first time after changing the style and/or checking "use skin colors"?

**Comment by Rex000** [comment]
I've actually been using this theme setting for a couple of days now. But this issue just happened today.

**Comment by Rex000** [comment]
It happened again. This time I restarted for a change and it got fixed.

**Comment by martinrotter** [comment]
Yes, you are not the first who sees this issue. It is completely random and I believe that the problem lies outside of my code. I believe this is upstream issue.

Does the problem persist if you try to use "win7" variant of RSS Guard?

**Comment by Rex000** [comment]
I haven't used it but I'll try.

**Comment by martinrotter** [comment]
thanks, it is just for debugging purposes

**Comment by akinokonomi** [comment]
@martinrotter FWIW I don't remember ever seeing it. Might be Windows only.

**Comment by martinrotter** [comment]
#926
