### ISSUE TITLE
[BUG]: Application restarts when highlighting an article

### ISSUE THREAD

**Issue by Rex000** [martinrotter/rssguard#940]
### Brief description of the issue

Upon first start of the app, when clicking on an article, it restarts.

### How to reproduce the bug?

1. Start the app
2. Click an article
3. The app restarts

### What was the expected result?

No restart

### What actually happened?

When you open the app for the first time and click on an article, the app restarts. Seems like the article preview window doesn't load for the first time for some reason, and the app then restarts to load it.

### Debug log

-

### Operating system and version

* OS: Win10 x64
* RSS Guard version: 4.3.4

**Comment by akinokonomi** [comment]
@martinrotter To clarify, it does not really restarts, it's just the application window disappears and appears again for some brief moment.
And yes, it happens only once, the first time any article is selected (either by clicking article in the list or hiding the feed list while some feed is selected).

It does not happen in 4.3.3.

**Comment by akinokonomi** [comment]
Yeah, sure enough, it happened between 9a25acea and 7197c9d0. 
Latter already had this problem, former didn't.

**Comment by martinrotter** [comment]
OK, I bisected wrong commit and likely found the problem and hopefully fixed. Please test.

**Comment by akinokonomi** [comment]
@martinrotter Seems fixed to me. Thanks!
