### ISSUE TITLE
[BUG]: Position reset while scrolling through articles

### ISSUE THREAD

**Issue by Rex000** [martinrotter/rssguard#941]
### Brief description of the issue

Position reset in the articles list while scrolling through articles

### How to reproduce the bug?

1. Click on an article in the list
2. Scroll manually through the list and go far from your selected article, then wait for the fetch operation to happen
3. Once the fetch happens, you'll be brought back to your selected article

### What was the expected result?

No position reset

### What actually happened?

While scrolling through the articles list, you are always brought back to your currently selected article after every fetch no matter where you were in the list. This doesn't happen if you don't have an article selected in the list.

### Debug log

-

### Operating system and version

* OS: Win10 x64
* RSS Guard version: 4.3.4

**Comment by martinrotter** [comment]
This is hard, for many technical reasons, sorry.
