### ISSUE TITLE
[BUG]: Multiple issues with Article Filter and Article Highlighter buttons

### ISSUE THREAD

**Issue by Rex000** [martinrotter/rssguard#943]
### Brief description of the issue

Strange behavior shown by these buttons.

### How to reproduce the bug?

Article highlighter button:
1. Select multiple options one after another then observe the dropdown menu

Article filter button:
1. Select multiple filters then observe the icon and its tooltip.
2. Select a filter or filters, then select "No extra filtering". Restart the app and check

### What was the expected result?

Normal behavior from both buttons

### What actually happened?

**Article highlighter button:**

A visual bug. Selecting a highlight option doesn't remove the selection from any previously selected option(s) in the dropdown menu unless you restart the app.
![ScreenShot_20230503225843](https://user-images.githubusercontent.com/28770012/236020729-92aa40a5-84bc-4418-b348-d19eedcea41b.jpeg)

**Article filter button:**
1. If you have multiple filters selected, it will only display one icon and description which can get really confusing. IMO there should be a separate unique icon for this case named something like "Multiple filters selected".
![ScreenShot_20230503221453](https://user-images.githubusercontent.com/28770012/236021237-d68acc23-e9c2-44ca-aa76-c4421cf4c1b1.jpeg)
![ScreenShot_20230503221941](https://user-images.githubusercontent.com/28770012/236021261-9fbd4d6a-0063-4fce-b498-b5ffca1932c9.jpeg)

2. Selecting "No extra filtering" removes all other filter selections (as it should), but upon restart of the app you'll find out that it doesn't do anything and your current filter choices remain unchanged.

### Debug log

-

### Operating system and version

* OS: Win 10 x64
* RSS Guard version: 4.3.4

**Comment by martinrotter** [comment]
![image](https://github.com/martinrotter/rssguard/assets/1255302/df21d7fc-9b93-4e6d-bf4d-fb3fbcb4e632)

Fixed both visually and as a feature.
