### ISSUE TITLE
[BUG]: Import feed window does not resize nicely

### ISSUE THREAD

**Issue by birdie-github** [martinrotter/rssguard#945]
### Brief description of the issue

Check the attached screenshot.

![import](https://user-images.githubusercontent.com/4958603/236175352-fc6aa5e3-cecc-401e-9d4a-b5271b6a8e63.png)

### How to reproduce the bug?

N/A

### What was the expected result?

N/A

### What actually happened?

N/A

### Debug log

N/A

### Operating system and version

* OS: Fedora 38
* RSS Guard version: 4.2.7
* Qt 5.15.12

**Comment by akinokonomi** [comment]
> Import feed window does not resize nicely

What do you mean by this?

You mean you can't make it smaller than that one in screenshot?
It resizes wonderfully for me.

What WM/DE is that? What screen?

**Comment by martinrotter** [comment]
Yes, if you stretch the window too much it does messy things. Will fix.
