### ISSUE TITLE
[FR]: Hide Zeros

### ISSUE THREAD

**Issue by birdie-github** [martinrotter/rssguard#946]
### Brief description of the feature request

This doesn't look nice: maybe don't show '(0)' at all?

![zeros](https://user-images.githubusercontent.com/4958603/236176083-f7de1792-0b48-43ca-8d45-4de636f23073.png)

**Comment by martinrotter** [comment]
feature is already there

![image](https://user-images.githubusercontent.com/1255302/236179047-f73bec46-b6e5-4379-9855-9f77c30f4bbe.png)
