### ISSUE TITLE
Default icons of categories in account "Standard online feeds" lost upon restart

### ISSUE THREAD

**Issue by pmattern** [martinrotter/rssguard#95]
#### Brief description of the issue.

At least on new user profiles the icons of categories within account "Standard online feeds" in the left pane of the main window disappear after restarting RSS Guard when the default set in terms of "Use default icons" of dialogue "Edit existing category" is selected.

#### How to reproduce the bug?

1. Make sure none of the directories `~/.cache/Martin Rotter`, `~/.local/share/Martin Rotter` and `~/.rssguard` preexists.
1. Launch RSS Guard. Add account "Standard online feeds", add a category to this account, optionally add a feed to the category. The default icon will be displayed left of the category in the left pane.
1. Restart RSS Guard. The icon as depicted in 2. will be gone, drop-down "Icon" in dialogue window "Edit existing category" will be empty.
1. Select "Use default icon" in the said drop-down. The icon will re-appear but again be gone after restarting RSS Guard.

#### What is the expected result?

Default icons should always display at the location as described in the steps to reproduce.

#### What actually happened?

Default icons disappear according to the steps to reproduce.

#### Other information (logs, see Wiki)

e88feff3 in an LXQt session on Arch Linux.
Custom icons in terms of "Load icon from file..." in drop-down "Icon" as mentioned above are not affected, icons of categories in accounts "Tiny Tiny RSS" or "ownCloud News", which don't seem to be customizable, aren't affected either ("ownCloud News" tested by [Nextcloud News app](https://github.com/nextcloud/news)).
An impact of the desktop environment wasn't tested but seems unlikely as the icons do come up the very first time RSS Guard is launched.

**Comment by martinrotter** [comment]
I was unable to reproduce this on Arch/MATE and on Windows 10. I agree that if those icons get lost, then it is a bug. In fact when you create new category, the icon is picked from your active icon theme and then is stored in DB with other category metadata.

It seems that either icon is not stored in the first place correctly in the DB or it is not loaded correctly after RSS Guard gets restarted.

Can you do this?

1. Run app with clean profile, create account, create one category.
2. Quit app.
3. Post here your database file & config. (See About -> Paths).

I will check if icon is saved in the DB. Also, it would nice to see logs from both runs of RSS Guard (before and after it is restarted).

**Comment by pmattern** [comment]
Meanwhile I saw that the problem does not exist in Xfce sessions here either. Yet I'm not sure whether really LXQt is to blame here as both [FeatherPad](https://github.com/tsujan/FeatherPad) and [Phototonic](https://github.com/oferkv/phototonic) which aren't really related to this desktop environment are adopting the icon theme as configured by `lxqt-config-appearance` even in real-time.
Now you're on Arch as well, so any chance you can quickly install LXQt and see whether you can reproduce in LXQt sessions? Probably doesn't even have to be that VCS stuff from the AUR but I guess 0.11 from community will do as well.

On a side note the icon theme in use does not seem to matter.
Both the malfunction and the lack thereof under LXQt and Xfce respectively were the same using either the GNOME Default Theme or Oxygen Icons.

As for the additional info you asked for configuration file and CLI output with debugging enabled are in [this GIST](https://gist.github.com/pmattern/25339dd8ac78c856bbb395a43c3a3069). In the logs there's some complaint about missing theme Faenza, but the findings are the same when it is installed. As for the database I didn't know how to upload a binary file like this so I took the liberty to send it to you by mail.

All current findings running 9a1b5037 on Arch Linux.

**Comment by martinrotter** [comment]
This is not probably related to particular desktop/icon theme. If you add category and its icon is right away visible in list, then the icon file was loaded from icon theme correctly. Newly added category should be now saved including the full icon file into the database.

When you start RSS Guard again, the icon file for the category is not fetched from icon theme, but fully from the database as the full icon file should be stored in it.

**Comment by martinrotter** [comment]
The log seems just fine. Will check the DB.

**Comment by martinrotter** [comment]
Well the icon is not even in DB. So it was not saved.

If it works with other DEs then there must be some problem with icon theme itself or the DE itself.

Can you send me the link to icon theme you are using? Can you try different icon theme (for example Faenza) to see if it works? Does you current icon theme work from different DE or you tried from Xfce with different theme?

**Comment by pmattern** [comment]
To compare LXQt and Xfce I made RSS Guard use [Oxygen Icons](https://www.archlinux.org/packages/extra/x86_64/oxygen/) and the [GNOME icon theme](https://www.archlinux.org/packages/extra/any/gnome-icon-theme/), both as provided by Arch Linux, from its settings. The problem could be seen with both on LXQt but with neither in Xfce sessions.
As for LXQt the problem can be seen with virtually all icon themes tested so far, aside from the two mentioned above these were in particular Faenza, Faience and Numix.
I have even tweaked the icon theme used by the desktop environments. This didn't seem to have an effect, basically to no surprise as RSS Guard seems to care about the icon theme as set in its own settings only.
That said, do you still need more information about themes?

Meanwhile I saw when a different icon theme is chosen in Settings - User Interface - Icons & skins - Icon theme, the corresponding icons are in fact used apparently everywhere in RSS Guard including the menu bar and drop-down "Icon" in dialogue window "Edit existing category" (which can still be used to make the icon temporarily re-appear as written in item "4." of the steps to reproduce above).

Btw. that whole thing is definitely a regression which didn't exist in earlier versions. Bit hard to track for me as I haven't used RSS Guard on a new profile for a while.

How about my proposal you look into this on LXQt, too? I figure this could speed things up quite a bit.

**Comment by martinrotter** [comment]
> I have even tweaked the icon theme used by the desktop environments. This didn't seem to have an effect, basically to no surprise as RSS Guard seems to care about the icon theme as set in its own settings only.

When you select "system/no theme" from RSS Guard settings, it should really use icon theme setup in your DE.

**Comment by martinrotter** [comment]
> Meanwhile I saw when a different icon theme is chosen in Settings - User Interface - Icons & skins - Icon theme, the corresponding icons are in fact used apparently everywhere in RSS Guard including the menu bar and drop-down "Icon" in dialogue window "Edit existing category"

Yes, of course, even the icon for "category" is of course loaded from your activated icon theme, all icons in RSS Guard are loaded from the theme.

**Comment by pmattern** [comment]
> When you select "system/no theme" from RSS Guard settings, it should really use icon theme setup in your DE.

I wasn't aware of this so far, but it works here as well. When "no icon theme/system icon theme" is selected virtually all icons are chosen from the icon theme selected e. g. by LXQt.
The problem we're discussing in this issue persists, though.

Meanwhile I had a look at LXQt release 0.11.x (I'm normally running recent VCS checkouts only). Same findings.

Atm. I don't know what else I could do to track this down. Maybe you can test at your side under LXQt 0.11.

**Comment by martinrotter** [comment]
I will try to test in live Lubuntu today.

**Comment by martinrotter** [comment]
But, this really seems like thing that is DE-related and not the actualy RSS Guard bug.

**Comment by pmattern** [comment]
> I will try to test in live Lubuntu today.

Up to you.
In case you want to have a look at LXQt note the support is poor in Lubuntu, they didn't even manage to get release 0.11 into 17.04. Once more, you seem to have an Arch Linux system at hand, so why can't you just quickly install stable LXQt and have a look? I mean we're on Linux and hence have proper package management; so you'll be able to clinically remove everything again once you're done testing.

@palinek, @tsujan
Any chance you can have a look at this absolute weirdness which may be caused by LXQt to some degree?
As for Arch Linux an AUR package [rssguard-git](https://aur.archlinux.org/packages/rssguard-git/) is available and allows for testing easily.
Steps to reproduce are stated in the initial comment. A menu bar can be enabled by simply hitting `M`, the default account can be added from menu "Accounts" and the test category using the default icon from "Feeds & categories" - "Add new item".

**Comment by martinrotter** [comment]
I will install lxqt on my Arch. I did not want to clutter my main machine Arch, but I will try it and remove lxqt after tests.

**Comment by pmattern** [comment]
Nah, you won't remove it any more after testing :)

**Comment by martinrotter** [comment]
OK, I tested it in LxQt and in MATE with icon themes: Oxygen, Faenza, Adwaita. They all work. I followed your steps to the letter, bro. :(

Therefore I can't reproduce the bug. I have no idea what might be causing this weird behavior.

**Comment by palinek** [comment]
Just confirming, that by following the steps by @pmattern, I've ended with the "noicon" for the newly added category (Test):
- after a clean startup and adding new account + new category
![screenshot](https://cloud.githubusercontent.com/assets/10990929/23849580/67a3975e-07dc-11e7-81e1-277ce201514c.png)

- after restarting the application
![screenshot](https://cloud.githubusercontent.com/assets/10990929/23849358/9e8bc882-07db-11e7-8e62-8906bbd48395.png)

(up-to-date Debian testing)

**Comment by martinrotter** [comment]
@palinek Can you now do exactly same steps with different DE?

**Comment by palinek** [comment]
The problem here seems to be the (de)serialization from/into data stream. I've added simple debugs for our purpose:
```diff
diff --git a/src/miscellaneous/databasequeries.cpp b/src/miscellaneous/databasequeries.cpp
index 1a2e48c1..44c30da3 100755
--- a/src/miscellaneous/databasequeries.cpp
+++ b/src/miscellaneous/databasequeries.cpp
@@ -1138,6 +1138,7 @@ int DatabaseQueries::addCategory(QSqlDatabase db, int parent_id, int account_id,
   q.bindValue(QSL(":icon"), qApp->icons()->toByteArray(icon));
   q.bindValue(QSL(":account_id"), account_id);
 
+qDebug() << Q_FUNC_INFO << title << icon << IconFactory::toByteArray(icon);
   if (!q.exec()) {
     qDebug("Failed to add category to database: '%s'.", qPrintable(q.lastError().text()));
 
@@ -1178,6 +1179,7 @@ bool DatabaseQueries::editCategory(QSqlDatabase db, int parent_id, int category_
   q.bindValue(QSL(":icon"), qApp->icons()->toByteArray(icon));
   q.bindValue(QSL(":parent_id"), parent_id);
   q.bindValue(QSL(":id"), category_id);
+qDebug() << Q_FUNC_INFO << title << icon << IconFactory::toByteArray(icon);
 
   return q.exec();
 }
@@ -1348,6 +1350,7 @@ Assignment DatabaseQueries::getCategories(QSqlDatabase db, int account_id, bool
     AssignmentItem pair;
     pair.first = q.value(CAT_DB_PARENT_ID_INDEX).toInt();
     pair.second = new StandardCategory(q.record());
+qDebug() << Q_FUNC_INFO << pair.second->title() << pair.second->icon() << IconFactory::toByteArray(pair.second->icon());
 
     categories << pair;
   }
```
and got this output:
```
[rssguard] DEBUG: static int DatabaseQueries::addCategory(QSqlDatabase, int, int, const QString&, const QString&, QDateTime, const QIcon&, bool*) "test" QIcon("folder",availableSizes[normal,Off]=(QSize(96, 96), QSize(16, 16), QSize(32, 32), QSize(64, 64), QSize(96, 96)),cacheKey=0x100000000) "AAAAJgBYAGQAZwBJAGMAbwBuAEwAbwBhAGQAZQByAEUAbgBnAGkAbgBlAAAADABmAG8AbABkAGUAcg=="
```
=>
```
echo 'AAAAJgBYAGQAZwBJAGMAbwBuAEwAbwBhAGQAZQByAEUAbgBnAGkAbgBlAAAADABmAG8AbABkAGUAcg==' | base64 -d | xxd
00000000: 0000 0026 0058 0064 0067 0049 0063 006f  ...&.X.d.g.I.c.o
00000010: 006e 004c 006f 0061 0064 0065 0072 0045  .n.L.o.a.d.e.r.E
00000020: 006e 0067 0069 006e 0065 0000 000c 0066  .n.g.i.n.e.....f
00000030: 006f 006c 0064 0065 0072                 .o.l.d.e.r
```

Loading icon from data stream is implemented in Qt here -> https://github.com/qt/qtbase/blob/dev/src/gui/image/qicon.cpp#L1365.

@luis-pereira There is no support in lxde/libqtxdg for the loading via `QIconEnginePlugin`... right?

**Comment by martinrotter** [comment]
@palinek See [this](https://github.com/martinrotter/rssguard/blob/master/src/miscellaneous/iconfactory.cpp#L32). RSS Guard uses standard QIcon (de)serialization here. I would be that this bug is icon theme-related, not DE-related.

As you can see, I am using `Qt_4_7` as version of serialization format. Perhaps you can try to change it to some other value? Which icon theme is known to trigger the issue for sure for you?

**Comment by martinrotter** [comment]
And indeed your test makes me believe that (de)serialization is really somehow fucked up. Interesting!

**Comment by palinek** [comment]
> Perhaps you can try to change it to some other value? Which icon theme is known to trigger the issue for sure for you?

The problem is not about theme.

> And indeed your test makes me believe that (de)serialization is really somehow fucked up. Interesting!

Nope. Your/rssguard's code is OK. Maybe I didn't say it clearly, but the problem is in lack of icon engine plugin in www.github.com/lxde/liblxqt. LXQt does provide its own plaform theme plugin which overrides the standard QIconEngine by the so called XdgIconLoaderEngine (www.github.com/lxde/libqtxdg). So in deserialization the QIcon code tries to create the XdgIconLoaderEngine here -> https://github.com/qt/qtbase/blob/dev/src/gui/image/qicon.cpp#L1380. But this fails because of lack of the plugin.

**Comment by palinek** [comment]
...got it working, but need to polish the solution a few.

**Comment by martinrotter** [comment]
> LXQt does provide its own plaform theme plugin which overrides the standard QIconEngine

I see, OK, now it's perfectly clear to me. :)

**Comment by martinrotter** [comment]
So should I mark this is "not our bug"?

**Comment by palinek** [comment]
> So should I mark this is "not our bug"?

I think so.

**Comment by palinek** [comment]
@martinrotter @pmattern FYI lxde/libqtxdg#118
