### ISSUE TITLE
[BUG]: Issue with database cleanup

### ISSUE THREAD

**Issue by Rex000** [martinrotter/rssguard#951]
### Brief description of the issue

Cleanup brings deleted articles back

### How to reproduce the bug?

Do a database cleanup

### What was the expected result?

Proper cleanup

### What actually happened?

Right after you do a database cleanup, the app re-fetches and marks unread many articles that were already read. Even those that were sent to recycle bin are brought back.

### Debug log

-

### Operating system and version

* OS: Win 10 x64
* RSS Guard version: 4.3.4

**Comment by martinrotter** [comment]
Hi.

What do you mean "proper" cleanup? The feature is called "DATABASE CLEANUP". Naturally, if you "clean" database, the data are CLEANED, meaning articles are removed physically according to your criteria.

**Comment by Rex000** [comment]
> Hi.
> 
> What do you mean "proper" cleanup? The feature is called "DATABASE CLEANUP". Naturally, if you "clean" database, the data are CLEANED, meaning articles are removed physically according to your criteria.

I'm honestly confused by this database cleanup function. Can you please explain what it specifically does? From what I've seen it deletes some stuff and it keeps some stuff. What is that criteria that it follows for doing that?

In my observation of the default options:

- Despite a check on "remove articles older than 14 days" it still keeps such articles.
- It marks many read articles as unread. This includes articles that were already sent to recycle bin. They are also brought back into the main window from recycle bin.

Is this all intended behavior?

**Comment by Rex000** [comment]
> Hi.
> 
> What do you mean "proper" cleanup? The feature is called "DATABASE CLEANUP". Naturally, if you "clean" database, the data are CLEANED, meaning articles are removed physically according to your criteria.

I'm honestly quite confused by this database cleanup function. Can you please explain what it specifically does? From what I've seen it deletes some stuff and it keeps some stuff. What is the criteria that it follows for doing that?

In my observation of the default options:
- Despite a check on "remove articles older than 14 days" it still keeps such articles.
- It marks many read articles as unread. 
- It removes all articles from recycle bin as it should. But then it brings them back into the main window and marks them unread as well.

Is this all intended behavior? Because I don't quite understand the point of a cleanup if everything comes back again.

Also I just noticed #934 highlights the same issue as well.

**Comment by martinrotter** [comment]
What it specifically does is that it purges/removes/deletes articles from database. Naturally, if article is removed AND it is still included in online RSS/ATOM feed file, it is-redownloaded again (and is unread now).

> It marks many read articles as unread

By itself it does not, but can as a result of my above statement.
