### ISSUE TITLE
[FR]: mass-change source url?

### ISSUE THREAD

**Issue by Owyn** [martinrotter/rssguard#954]
### Brief description of the feature request

I have few dozens nitter RSS sources, all from the same domain, but occasionally there arises a need to change the domain for every feed (nitter fork \\ version update, one instance closes - another opens etc)

would be nice if there was an easy way to mass replace source urls somehow (while keeping the feed database preferably)

**Comment by martinrotter** [comment]
Well, you can to this easily with SQliteBrowser app. Simply open database file and then run simple SQL

```sql
UPDATE
    Feeds
SET
    source = REPLACE(source, 'old', 'new');
WHERE
   source LIKE "%WHAT%";
```
