### ISSUE TITLE
[FR]: Folder improvements (make folders useful)

### ISSUE THREAD

**Issue by Owyn** [martinrotter/rssguard#956]
### Brief description of the feature request

1 Folder should turn red if all the feed sources inside are red
2 Setting an update interval for a whole folder would be nice
3 Disable the folder with everything inside
4 Have one post-proccess script for a whole folder in the folder setting?

**Comment by martinrotter** [comment]
Option 1 is already there, pls double check and remove from your ticket.

**Comment by Owyn** [comment]
> Option 1 is already there, pls double check and remove from your ticket.

No it's not there 
![image](https://github.com/martinrotter/rssguard/assets/1309656/558e3d7b-d53d-440e-9001-cc686bcc5609)

**Comment by martinrotter** [comment]
Oh, you mean "red", not "read".

**Comment by martinrotter** [comment]
This is now all possible with extended selection and "Edit child feed" option implemented for 4.5.3. As for "red" folders", yes, if you still need it, pls create separate ticket for it, i close this.
