### ISSUE TITLE
Please provide Linux builds

### ISSUE THREAD

**Issue by probonopd** [martinrotter/rssguard#96]
Possibly running https://github.com/probonopd/linuxdeployqt on Travis CI can simplify that.

**Comment by martinrotter** [comment]
RSS Guard is not packaged for your Linux distro?

**Comment by martinrotter** [comment]
No, response. Closing.

I do not see all those "fancy" flatpaks etc. stuff as good way to package SW for Linux anyway. Just package it appropriately for you distro.

**Comment by probonopd** [comment]
No, the latest version of RSS Guard is not available for my LTS distro.
