### ISSUE TITLE
[FR]: Add Feed URL to a feed details pane

### ISSUE THREAD

**Issue by shoulders** [martinrotter/rssguard#962]
### Brief description of the feature request

this is useful if you forget where a particular feed is from. I know you can edit the feed and have a look but this feature is for people with loads of RSS feeds and for looking at really quickly.

![url-in-details](https://github.com/martinrotter/rssguard/assets/319997/f92fbb88-5dd1-431d-8d87-e20f7930516c)

**Comment by martinrotter** [comment]
![image](https://github.com/martinrotter/rssguard/assets/1255302/113eae8d-5006-44af-bf75-9b7f12132a7c)

done
