### ISSUE TITLE
[FR]: Add option to view Feed ID in left pane and feed details

### ISSUE THREAD

**Issue by shoulders** [martinrotter/rssguard#965]
### Brief description of the feature request

Viewing the Feed ID in the left pane is useful if you are trying to find which feed and article belongs too for such things as chasing duplicates.

![image](https://github.com/martinrotter/rssguard/assets/319997/1ea232df-2cd7-4f1f-a370-04b3d95cfba8)

Having the Feed ID shown in the details of the feed makes sense.

![image](https://github.com/martinrotter/rssguard/assets/319997/c69c3b37-cc4f-4ed3-8869-d67ead84b243)

**Comment by martinrotter** [comment]
![image](https://github.com/martinrotter/rssguard/assets/1255302/2c896bb1-53e2-466a-8d6f-2b1122a0f901)

Added id to tooltip and to item details.
