### ISSUE TITLE
[FR]: Exclude feeds from "Remove all read articles from all feeds on application exit"

### ISSUE THREAD

**Issue by sn0utss** [martinrotter/rssguard#967]
### Brief description of the feature request

Currently all or none, would be useful to be able to retain read articles in the database from select feeds (for example those with poor archive/search functions that are not SEO optimized etc).

**Comment by martinrotter** [comment]
This is now kind of possible with #1270, closing this, cleaning policies are now possible to be set app-wide or/and feed-specific, this feature will be removed now
