### ISSUE TITLE
[FR]: Additional formats for external tools

### ISSUE THREAD

**Issue by RetroAbstract** [martinrotter/rssguard#969]
### Brief description of the feature request

Hi,

This feature would allow the user to use additional formats for external tools such as text format.

This request was created as currently I cannot open articles with yt-dlp in RSS Guard on Linux as yt-dlp is in text format (python) compared to an executable on Windows, thus resulting in RSS Guard displaying "External tool '[pathtoyt-dlp]/yt-dlp' could not be started" when trying to open an article with it.

Thanks

**Comment by RetroAbstract** [comment]
> This is not how it works. It does not matter if the executable is binary or not.
> 
> Just add the full path to executable in the external tool settings. Something like `/usr/bin/yt-dlp` It should work just fine.
> 
> Or you might try `/usr/bin/python3 /path/to/yt-dlp`, if the file does not have a shebang.
> 
> EDIT: In latter case, `/path/to/yt-dlp` should be added as the "parameter".

Thanks for the solution @akinokonomi.

Tried this on the AppImage version and it works fine, but not on the Flathub one. 

Initially the file selector is the system one in the Flathub version (which will set python's executable path as: /run/user/1000/doc/[numbers&letters]/python3 instead of /usr/bin/python3 when selecting the python binary) compared to the RSS Guard file selector in the AppImage one (which sets the python binary as /usr/bin/python3 when selecting it).   

Even when exporting the settings from the AppImage version and importing them to the Flathub one to have the python path set as "/usr/bin/python3" is doesn't work.

Any ideas?

Thanks

**Comment by martinrotter** [comment]
Perhaps this? 

https://github.com/martinrotter/rssguard/issues/917#issuecomment-1517525689

**Comment by akinokonomi** [comment]
> Even when exporting the settings from the AppImage version and importing them to the Flathub one to have the python path set as "/usr/bin/python3" is doesn't work.
> 
> Any ideas?

@RetroAbstract Sorry, I don't know how to make it work with Flatpak version.

**Comment by martinrotter** [comment]
This is likely related to Flatpak and not RSS Guard limitation at all.
