### ISSUE TITLE
[FR]: Pause fetching

### ISSUE THREAD

**Issue by Rex000** [martinrotter/rssguard#970]
### Brief description of the feature request

An ability to pause fetching via a button and/or a shortcut would be very convenient in adjusting any settings or adding a new feed, etc.,  especially in cases where feeds have small fetch intervals.

**Comment by martinrotter** [comment]
You mean to "pause" the already running feed fetching or just temporarily disabling feed fetching which might occur soon?

**Comment by Rex000** [comment]
Temporarily disabling feed fetching which might occur soon. But actually both would be pretty handy because then we won't have to wait for the ongoing feed fetching operation to complete so that we could temporarily disable the fetching.

**Comment by Rex000** [comment]
Temporarily disabling feed fetching. Having both functions would be even better.
