### ISSUE TITLE
[BUG]: 'Assigned labels' column shows incorrect value

### ISSUE THREAD

**Issue by Mitecon** [martinrotter/rssguard#976]
### Brief description of the issue

When the column 'Assigned labels' is enabled in the main window, the value for every article is shown as '1'.

### How to reproduce the bug?

Enable 'Assigned labels' in the main window and look at the value.

### What was the expected result?

I was expecting to see the names of the labels.

### What actually happened?

The 'Assigned label IDs' column shows correct values, which is what I expected. So it's not me being confused as to which columns are meant to display which values:

![assigned-labels-values](https://github.com/martinrotter/rssguard/assets/125831943/a39dc77c-a5c7-4687-bfbb-c4f032b30537)

The 'Assigned labels' column, I think, points to 'account_id' instead of 'name':

![db-browser-labels](https://github.com/martinrotter/rssguard/assets/125831943/b3143877-c30e-406e-81ac-3ef31d6347d3)

### Debug log

Not needed.

### Operating system and version

* OS: Manjaro
* RSS Guard version: rssguard-devbuild-a3442c182-linux64.AppImage

**Comment by martinrotter** [comment]
YES, the column is temporarily "disabled" due to performance testing reasons, the problem will be solved before new release.

**Comment by martinrotter** [comment]
this is now fixed
