### ISSUE TITLE
[BUG]: Tor Project blog does not display correctly

### ISSUE THREAD

**Issue by Mitecon** [martinrotter/rssguard#979]
### Brief description of the issue

The feed for Tor Project blog does not preview correctly.

Loading up the full web page renders incorrectly.

### How to reproduce the bug?

- Add the feed: https://blog.torproject.org/blog/feed
- Update the feed
- Click on any article

### What was the expected result?

Not to see any HTML and for the full web page to render correctly. I haven't seen this with other feeds.

### What actually happened?

When previewing, it shows HTML instead of a nicely formatted preview:

![tor-project-blog-preview](https://github.com/martinrotter/rssguard/assets/125831943/eca2fa17-a96f-411a-8f38-39ff1878bf42)

Compare with:

![tails-preview](https://github.com/martinrotter/rssguard/assets/125831943/a185f5db-dfeb-4ed7-9ecb-72cb9860ae59)

When loading up the full web page, it shows a version with the colours off (dark background here):

![tor-project-blog-loaded-page](https://github.com/martinrotter/rssguard/assets/125831943/82be20c1-6f07-414d-a39f-91a0de3134d1)

Compare with:

![tails-loaded-page](https://github.com/martinrotter/rssguard/assets/125831943/433c4a91-c40c-4b1d-ae47-ee793aaf91a9)

### Debug log

None needed.

### Operating system and version

* OS: Manjaro
* RSS Guard version: rssguard-devbuild-30a471a6f-linux64.AppImage

**Comment by martinrotter** [comment]
Yes, there is automatic detection whether feed is plain-text or XML/HTML-formatted. In some cases, some feeds are highly non-standard and auto-detection fails.

Will tweak. I also plan to add a switch to each feed where user could switch plaintext/html mode manually.

**Comment by martinrotter** [comment]
I do not have "Improving tails..." article in that feed. Even if I had, those source URLs are from completely differente websites:
- tails.boum.org
- blog.torproject.org
