### ISSUE TITLE
Group by option

### ISSUE THREAD

**Issue by pcause** [martinrotter/rssguard#98]
I have quite a few feeds that I track.  Some feeds are from forums.  When selecting a folder it helps to have the messages groups by feed and then sorted by time so one can follow a discussion.  The result would be all messages from feed a, newest/oldest first, then feed b messages, etc.

**Comment by martinrotter** [comment]
Can you share some picture of what it should like? I honestly do not exactly know what you want, your description of the problem is just too vague.

**Comment by pcause** [comment]
here is a screen shot of tt-rss web version.  on the right, the results for a category are displayed by feed and then within feed sorted by either oldest first or newest first

![rssscreen](https://cloud.githubusercontent.com/assets/1071479/23212877/a8accfaa-f8d6-11e6-8119-5add061a48f7.PNG)

**Comment by martinrotter** [comment]
Implementing this would require very new approach to how rssguard displays messages and very fast implementation. RSS Guard now uses sql table model which does not allow tree structures but is VERY fast. This is the priority of RSS Guard, I will mark this as postponed, but will implement maybe in a far future.

**Comment by pcause** [comment]
I don't think this needs a tree structure.  all you have to do is, when you get the article list make it group by feed and then sort by oldest/newest.

**Comment by martinrotter** [comment]
Well, if you need to group only by feed, then this is certainly the solution.

**Comment by martinrotter** [comment]
In that case, the problem is solved, because #97 was implemented today. Should I mark this as solved?

**Comment by pcause** [comment]
yes, just need to group the items (the right side of the example page above).  If the way you've implemented 97 allows me to group by AND then sort by terrific.  But even group by without then sorting is a win for my use case.  Thanks.  Will pull and build and try tonight or tomorrow.

**Comment by martinrotter** [comment]
I added proper mutlicolumn sorting in https://github.com/martinrotter/rssguard/commit/21fc8b087abec5323fa093db491aec6b89e0e804

Now, if you HOLD CTRL key, and then you click on columns to sort messages -> multicolumn reverse sorting is active. How it works?

Let's say you want to sort messages first by feed's title name, then by date/time:

1. Select some category.
2. Press and hold CTRL key.
3. Click on "Feed" column (now it gets sorted by feed).
4. Click on "Created on" column (now it gets sorted by date of message while previous feed sort is preserved).

**Comment by pcause** [comment]
this is great and thanks so much.
