### ISSUE TITLE
[BUG]: Suspicious behavior

### ISSUE THREAD

**Issue by Rex000** [martinrotter/rssguard#985]
### Brief description of the issue

Suspicious behavior of rssguard.exe detected by Windows

### How to reproduce the bug?

-

### What was the expected result?

-

### What actually happened?

Windows marked the rssguard.exe in the latest dev build as suspicious (Behavior:Win32/Persistence.A!ml) and quarantined it.

### Debug log

-

### Operating system and version

* OS: Win 10
* RSS Guard version: rssguard-devbuild-d866378df-win10

**Comment by martinrotter** [comment]
Just windows things
