### ISSUE TITLE
[BUG]: Potentially memory leak while resizing window

### ISSUE THREAD

**Issue by chromer030** [martinrotter/rssguard#989]
### Brief description of the issue

Resizing the application window , increases the memory : 

https://github.com/martinrotter/rssguard/assets/13361552/b9b0b0b7-91b4-4b9e-a9a7-77608e936f41

### How to reproduce the bug?

1- Monitor the app process
2- Resize the window

### What was the expected result?

Increase in RAM

### What actually happened?

Increase in RAM

### Debug log

time="     0.069" type="debug" -> core: Initializing settings in '/home/chromer/.config/RSS Guard 4/config/config.ini' (non-portable way).
time="     0.166" type="debug" -> database: File-based SQLite database connection 'DatabaseFactory' to file '/home/chromer/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.166" type="debug" -> database: File-based SQLite database has version '4'.
time="     0.166" type="debug" -> gui: Available icon theme paths: QList(/home/chromer/.local/share/icons, /usr/share/icons, :/icons, :/graphics, /home/chromer/.config/RSS Guard 4/icons, /usr/bin/icons)
time="     0.206" type="debug" -> gui: Icon theme 'breeze-dark' already loaded.
time="     0.207" type="debug" -> gui: Found path of base skin: ':/skins/nudus-base'.
time="     0.207" type="debug" -> gui: Local file ':/skins/nudus-dark/html_wrapper.html' exists, using it for the skin.
time="     0.207" type="debug" -> gui: Local file ':/skins/nudus-dark/html_style.css' exists, using it for the skin.
time="     0.207" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_enclosure_image.html' for the skin.
time="     0.207" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_single_message.html' for the skin.
time="     0.207" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_enclosure_every.html' for the skin.
time="     0.207" type="debug" -> gui: Local file ':/skins/nudus-dark/qt_style.qss' exists, using it for the skin.
time="     0.207" type="debug" -> gui: Trying to load base file ':/skins/nudus-base/html_adblocked.html' for the skin.
time="     0.207" type="debug" -> gui: OS defines color scheme: 'Qt::ColorScheme::Dark'.
time="     0.208" type="debug" -> gui: Setting style: 'Fusion'.
time="     0.208" type="debug" -> gui: Activating alternative palette.
time="     0.217" type="debug" -> gui: Skin 'nudus-dark' loaded.
time="     0.217" type="warning" -> network: Activating application-wide custom proxy, address: '127.0.0.1', type: '1'.
time="     0.255" type="debug" -> core: OpenSSL version: 'OpenSSL 3.1.1 30 May 2023'.
time="     0.255" type="debug" -> core: OpenSSL supported: 'true'.
time="     0.255" type="debug" -> core: Global thread pool has 4 threads.
time="     0.255" type="debug" -> core: Starting RSS Guard 4.3.4.
time="     0.255" type="debug" -> core: Instantiated class  'Application'.
time="     0.255" type="debug" -> core: Starting to load active localization. Desired localization is 'en_US'.
time="     0.265" type="debug" -> core: Application localization 'en_US' loaded successfully, specifically sublocalization 'en_US' was loaded.
time="     0.265" type="warning" -> core: Qt localization 'en_US' WAS NOT loaded successfully.
time="     0.282" type="debug" -> database: SQLite database connection 'MessagesModel' to file '/home/chromer/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.286" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, CASE WHEN length(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Labels.custom_id IN (SELECT LabelsInMessages.label FROM LabelsInMessages WHERE LabelsInMessages.account_id = Messages.account_id AND LabelsInMessages.message = Messages.custom_id)) as msg_labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1;'.
time="     0.287" type="debug" -> core: Auto-download timer started with interval 10000 ms.
time="     0.287" type="debug" -> core: Creating FeedDownloader singleton.
time="     0.334" type="debug" -> gui: Creating main application form in thread: '0x7f36c3300940'.
time="     0.422" type="debug" -> gui: Current row changed - proxy 'QModelIndex(-1,-1,0x0,QObject(0x0))', source 'QModelIndex(-1,-1,0x0,QObject(0x0))'.
time="     0.426" type="warning" -> network: Using application-wide proxy.
time="     0.426" type="warning" -> network: Used proxy address: '127.0.0.1', type: '1'.
time="     0.427" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     0.428" type="warning" -> network: Using application-wide proxy.
time="     0.428" type="warning" -> network: Used proxy address: '127.0.0.1', type: '1'.
time="     0.428" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     0.434" type="warning" -> network: Using application-wide proxy.
time="     0.434" type="warning" -> network: Used proxy address: '127.0.0.1', type: '1'.
time="     0.434" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     0.463" type="debug" -> gui: Creating tray icon menu.
time="     0.465" type="debug" -> CTRL is NOT pressed while sorting articles - sorting with standard mode.
time="     0.465" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, CASE WHEN length(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Labels.custom_id IN (SELECT LabelsInMessages.label FROM LabelsInMessages WHERE LabelsInMessages.account_id = Messages.account_id AND LabelsInMessages.message = Messages.custom_id)) as msg_labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1 ORDER BY Messages.id DESC;'.
time="     0.467" type="debug" -> gui: Reloading of msg selections took 2 miliseconds.
time="     0.478" type="debug" -> CTRL is NOT pressed while sorting articles - sorting with standard mode.
time="     0.478" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, CASE WHEN length(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Labels.custom_id IN (SELECT LabelsInMessages.label FROM LabelsInMessages WHERE LabelsInMessages.account_id = Messages.account_id AND LabelsInMessages.message = Messages.custom_id)) as msg_labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1 ORDER BY Messages.date_created DESC, Messages.id DESC;'.
time="     0.479" type="debug" -> core: Showing the main window when the application is starting.
time="     0.482" type="debug" -> database: SQLite database connection 'FeedReader' to file '/home/chromer/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.483" type="debug" -> database: SQLite database connection 'FeedlyEntryPoint' to file '/home/chromer/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.483" type="debug" -> database: SQLite database connection 'GmailEntryPoint' to file '/home/chromer/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.483" type="debug" -> database: SQLite database connection 'GreaderEntryPoint' to file '/home/chromer/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.484" type="debug" -> database: SQLite database connection 'OwnCloudServiceEntryPoint' to file '/home/chromer/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.484" type="debug" -> database: SQLite database connection 'StandardServiceEntryPoint' to file '/home/chromer/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.485" type="debug" -> core: Filter accepts row 'chromer (RSS/ATOM/JSON)' and filter result is: 'true'.
time="     0.485" type="debug" -> database: SQLite database connection 'StandardServiceRoot' to file '/home/chromer/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.485" type="debug" -> database: SQLite database connection 'RecycleBin' to file '/home/chromer/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.485" type="debug" -> database: SQLite database connection 'ImportantNode' to file '/home/chromer/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.485" type="debug" -> database: SQLite database connection 'RootItem' to file '/home/chromer/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.485" type="debug" -> database: SQLite database connection 'TtRssServiceEntryPoint' to file '/home/chromer/.config/RSS Guard 4/database/database.db' seems to be established.
time="     0.486" type="debug" -> gui: Feed list item expanded - chromer (RSS/ATOM/JSON)
time="     0.486" type="debug" -> core: Filter accepts row 'Recycle bin' and filter result is: 'true'.
time="     0.486" type="debug" -> core: Filter accepts row 'Important articles' and filter result is: 'true'.
time="     0.486" type="debug" -> core: Filter accepts row 'Unread articles' and filter result is: 'true'.
time="     0.486" type="debug" -> core: Filter accepts row 'Labels' and filter result is: 'true'.
time="     0.486" type="debug" -> gui: Feed list item expanded - Labels
time="     0.486" type="debug" -> core: No execution message received from other app instances.
time="     0.552" type="debug" -> core: Filter accepts row 'chromer (RSS/ATOM/JSON)' and filter result is: 'true'.
time="     0.552" type="debug" -> core: Filter accepts row 'Labels' and filter result is: 'true'.
time="     0.552" type="debug" -> core: Filter accepts row 'Important articles' and filter result is: 'true'.
time="     0.552" type="debug" -> core: Filter accepts row 'Unread articles' and filter result is: 'true'.
time="     0.552" type="debug" -> core: Filter accepts row 'Recycle bin' and filter result is: 'true'.
time="     2.214" type="debug" -> gui: Message splitter moved.
time="     2.290" type="debug" -> gui: Message splitter moved.
time="     2.357" type="debug" -> gui: Message splitter moved.
time="     2.432" type="debug" -> gui: Message splitter moved.
time="     2.515" type="debug" -> gui: Message splitter moved.
time="     2.591" type="debug" -> gui: Message splitter moved.
time="     2.667" type="debug" -> gui: Message splitter moved.
time="     2.751" type="debug" -> gui: Message splitter moved.
time="     2.843" type="debug" -> gui: Message splitter moved.
time="     2.934" type="debug" -> gui: Message splitter moved.
time="     3.019" type="debug" -> gui: Message splitter moved.
time="     3.095" type="debug" -> gui: Message splitter moved.
time="     3.171" type="debug" -> gui: Message splitter moved.
time="     3.246" type="debug" -> gui: Message splitter moved.
time="     3.321" type="debug" -> gui: Message splitter moved.
time="     3.405" type="debug" -> gui: Message splitter moved.
time="     3.497" type="debug" -> gui: Message splitter moved.
time="     3.590" type="debug" -> gui: Message splitter moved.
time="     3.648" type="debug" -> gui: Message splitter moved.
time="     3.723" type="debug" -> gui: Message splitter moved.
time="     3.797" type="debug" -> gui: Message splitter moved.
time="     4.024" type="debug" -> gui: Message splitter moved.
time="     4.262" type="debug" -> gui: Message splitter moved.
time="     4.451" type="debug" -> gui: Message splitter moved.
time="     4.533" type="debug" -> gui: Message splitter moved.
time="     4.602" type="debug" -> gui: Message splitter moved.
time="     4.676" type="debug" -> gui: Message splitter moved.
time="     4.865" type="debug" -> gui: Message splitter moved.
time="     4.943" type="debug" -> gui: Message splitter moved.
time="     5.011" type="debug" -> gui: Message splitter moved.
time="     5.078" type="debug" -> gui: Message splitter moved.
time="     5.155" type="debug" -> gui: Message splitter moved.
time="     5.222" type="debug" -> gui: Message splitter moved.
time="     5.297" type="debug" -> gui: Message splitter moved.
time="     5.381" type="debug" -> gui: Message splitter moved.
time="     5.465" type="debug" -> gui: Message splitter moved.
time="     5.557" type="debug" -> gui: Message splitter moved.
time="     5.645" type="debug" -> gui: Message splitter moved.
time="     5.746" type="debug" -> gui: Message splitter moved.
time="     5.825" type="debug" -> gui: Message splitter moved.
time="     5.900" type="debug" -> gui: Message splitter moved.
time="     5.984" type="debug" -> gui: Message splitter moved.
time="     6.154" type="debug" -> gui: Message splitter moved.
time="     6.234" type="debug" -> gui: Message splitter moved.
time="     6.310" type="debug" -> gui: Message splitter moved.
time="     6.392" type="debug" -> gui: Message splitter moved.
time="     6.469" type="debug" -> gui: Message splitter moved.
time="     6.545" type="debug" -> gui: Message splitter moved.
time="     6.613" type="debug" -> gui: Message splitter moved.
time="     6.671" type="debug" -> gui: Message splitter moved.
time="     6.729" type="debug" -> gui: Message splitter moved.
time="     6.805" type="debug" -> gui: Message splitter moved.
time="     6.872" type="debug" -> gui: Message splitter moved.
time="     6.948" type="debug" -> gui: Message splitter moved.
time="     7.024" type="debug" -> gui: Message splitter moved.
time="     7.091" type="debug" -> gui: Message splitter moved.
time="     7.166" type="debug" -> gui: Message splitter moved.
time="     7.250" type="debug" -> gui: Message splitter moved.
time="     7.325" type="debug" -> gui: Message splitter moved.
time="     7.393" type="debug" -> gui: Message splitter moved.
time="     7.473" type="debug" -> gui: Message splitter moved.
time="     7.543" type="debug" -> gui: Message splitter moved.
time="     7.619" type="debug" -> gui: Message splitter moved.
time="     7.702" type="debug" -> gui: Message splitter moved.
time="     7.778" type="debug" -> gui: Message splitter moved.
time="     7.862" type="debug" -> gui: Message splitter moved.
time="     7.954" type="debug" -> gui: Message splitter moved.
time="     8.046" type="debug" -> gui: Message splitter moved.
time="     9.055" type="debug" -> gui: Main window's close event
time="     9.055" type="debug" -> gui: Main window's hide event
time="     9.056" type="debug" -> core: Cleaning up resources and saving application state.
time="     9.056" type="debug" -> core: Close lock was obtained safely.
time="     9.056" type="debug" -> core: Stopping StandardServiceRoot instance.
time="     9.057" type="debug" -> feed-downloader: Destroying FeedDownloader instance.
time="     9.126" type="debug" -> gui: Destroying FormMain instance.
time="     9.126" type="debug" -> gui: Destroying TabWidget instance.
time="     9.126" type="debug" -> gui: Destroying FeedMessageViewer instance.
time="     9.126" type="debug" -> gui: Destroying BaseToolBar instance.
time="     9.127" type="debug" -> network: Destroying Downloader instance.
time="     9.127" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="     9.127" type="debug" -> network: Destroying Downloader instance.
time="     9.127" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="     9.127" type="debug" -> network: Destroying Downloader instance.
time="     9.127" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="     9.127" type="debug" -> gui: Destroying MessagesView instance.
time="     9.127" type="debug" -> gui: Destroying BaseToolBar instance.
time="     9.128" type="debug" -> gui: Destroying FeedsView instance.
time="     9.128" type="debug" -> gui: Destroying TabBar instance.
time="     9.128" type="debug" -> gui: Destroying StatusBar instance.
time="     9.129" type="debug" -> core: Destroying Application instance.
time="     9.129" type="debug" -> core: Destroying Mutex instance.
time="     9.129" type="debug" -> gui: Destroying IconFactory instance.
time="     9.129" type="debug" -> core: Destroying FeedReader instance.
time="     9.129" type="debug" -> feed-model: Destroying FeedsModel instance.
time="     9.129" type="debug" -> feed-model: Destroying FeedsProxyModel instance
time="     9.129" type="debug" -> message-model: Destroying MessagesModel instance.
time="     9.130" type="debug" -> message-model: Destroying MessagesProxyModel instance.

### Operating system and version

* OS: Arch Linux
* RSS Guard version: 4.3.4

**Comment by martinrotter** [comment]
Likely upstream bug, there is zero code in RSS Guard which would do this when resizing main dialog.
