### ISSUE TITLE
[BUG]: Dark theme broken on Linux since 4.3.4

### ISSUE THREAD

**Issue by koplo199** [martinrotter/rssguard#992]
### Brief description of the issue

Commit 05b2a825595a803d9d4f298d0bdf959b44d693a1 broke dark theme on Linux, reverting it make it work again

![Screenshot from 2023-04-27 10-45-42](https://user-images.githubusercontent.com/85577251/234809992-53850174-9298-4a27-92c6-cd8a512f7a2c.png)
![Screenshot from 2023-04-27 10-46-54](https://user-images.githubusercontent.com/85577251/234810002-d9679cc9-34d9-4c82-8613-4ccc0f017947.png)

### How to reproduce the bug?

1. Use a dark theme/variant like `Adwaita-dark`
2. Upgrade from 4.3.3

### What was the expected result?

UI to not be broken

### What actually happened?

UI is broken

### Debug log

Nothing different from the logs between versions

### Operating system and version

* OS: ArchLinux (installed from the package manager)
* RSS Guard version: Any version since 4.3.4 included

**Comment by martinrotter** [comment]
Can you please wait until ac69b119e compiles and then test with devbuild version?

**Comment by koplo199** [comment]
@martinrotter I'm not using the AppImage (the reason is that styling does not work at all with it, which would be an entirely different issue), instead for testing I'm compiling it locally using the upstream [PKGBUILD](https://gitlab.archlinux.org/archlinux/packaging/packages/rssguard/-/blob/4.4.0-1/PKGBUILD). Using Qt 6.5.1 does not resolve the issue unfortunately

**Comment by martinrotter** [comment]
OK, I disabled/reverted relevant piece, let me know if it works now.

**Comment by koplo199** [comment]
@martinrotter I compiled against master (649ea75ea801832fd5d9a55b280d49fd13f60d68) and I confirm it still isn't working properly, it behave the exact same as before 860ccdb

**Comment by koplo199** [comment]
It seems that `qApp->styleHints()->colorScheme()` is returning `Qt::ColorScheme::Unknown` which cause the breakage, would changing
```C
qApp->setPalette(qt_fusionPalette(qApp->styleHints()->colorScheme() == Qt::ColorScheme::Dark))
```
to
```C
qApp->setPalette(qt_fusionPalette(!(qApp->styleHints()->colorScheme() == Qt::ColorScheme::Light)))
```
be an acceptable solution for you? From my testing it resolve the issue

**Comment by martinrotter** [comment]
i see, provide PR pls

**Comment by koplo199** [comment]
@martinrotter The bug returned with aed4ba6639972fc77d4769141d223fc80e1db8d6 as it reverted what was done in #998
