### ISSUE TITLE
Using RSS Guard without an account (via OPML import)

### ISSUE THREAD

**Issue by vivadavid** [martinrotter/rssguard#993]
### Brief description of the feature request

Hi,

RSS Guard is new to me and maybe I'm requesting something that already exists. I was unable to find it and that's why I'm writing this message.

Would it be possible to use the programme without adding an account? It doesn't seem that simple to me and also I've read, for example, that Feedly has limitations for the free account.

So far, I'm using an RSS programme that allows me to just import my OPML file. Would it be possible to use RSS Guard this way, without an account, importing and exporting an OPML?

Thanks.

**Comment by martinrotter** [comment]
Hi, sure. "account" is just terminology we use. One of "accounts" is also classic RSS/ATOM as you know from other rss readers.

![image](https://github.com/martinrotter/rssguard/assets/1255302/8082dc0a-d335-438b-bb0c-cb5cd8cabcd1)
![image](https://github.com/martinrotter/rssguard/assets/1255302/1dc04c33-ef51-4dd2-894c-842d31851df4)

**Comment by vivadavid** [comment]
Thank you! It worked for me! 

P.S. I didn't know what "RSS/ATOM" meant. I thought it also implied some sort of account.

**Comment by Vinayak-kadu** [comment]
is there any way to use without account?

i dont want my pc username to be involved in rss reader..

**Comment by martinrotter** [comment]
What do you mean? PC username is not "stored" anywhere etc. Its just like any other RSS reader with classic RSS/ATOM, there is no "account" anywhere.
