### ISSUE TITLE
Empty application log

### ISSUE THREAD

**Issue by vivadavid** [martinrotter/rssguard#994]
### Brief description of the issue

On a local account, I have imported an OPML file that I had obtained from Newsflow. A message indicates that not all the feeds have been successfully imported and the programme prompts me to check the log, but the log is empty.

### How to reproduce the bug?

1. I create a local account.
2. I import an OPML file.
3. The programme says not all feeds have been successfully imported.
4. The programme prompts me to check the log.
5. When I click on Help > Display application log, it's empty.

### What was the expected result?

I expected to get a list of the feeds from my OPML file that hadn't been imported.

### What actually happened?

The log was empty.

### Debug log

I don't know what to do here.

### Operating system and version

* OS: Windows 11 (22H2).
* RSS Guard version: 4.4.0 (Windows 10 version).

**Comment by martinrotter** [comment]
No. The application writes to "log" all the time. If you want to see log in "Application log" dialog, you must open it first and THEN do your thing you want to debug. Also, as stated in documentation, you can redirect logging to text file which is usually better.

**Comment by vivadavid** [comment]
Sorry, I don't understand any of that.

I was hoping that I could learn to use RSS Guard intuitively at least for the basic stuff, but if this programme requires users to read a lot of documentation before doing anything else, I apologize for not having done that.

When I have some time, I'll try to find the documentation and see how things work. Everything seemed to be fine, except that some feeds weren't imported.

**Comment by vivadavid** [comment]
I managed to do it: than you!
