### ISSUE TITLE
[BUG]:  Display

### ISSUE THREAD

**Issue by Motocycle347** [martinrotter/rssguard#996]
### Brief description of the issue

pick a feed
select an item in the feed
The feed name becomes unreadable
![440 error](https://github.com/martinrotter/rssguard/assets/15929091/ab2d3817-8e24-42d0-a403-ecb16fe08ec4)

### How to reproduce the bug?

pick a feed
select an item in the feed
The feed name becomes unreadable
![440 error](https://github.com/martinrotter/rssguard/assets/15929091/ab2d3817-8e24-42d0-a403-ecb16fe08ec4)

### What was the expected result?

the description remains legible

### What actually happened?

see picture

### Debug log

un needed

### Operating system and version

* OS: win 11
* RSS Guard version: 4.4.0

**Comment by martinrotter** [comment]
Yes, pls re-test with latest development build. Should be fixed.

https://github.com/martinrotter/rssguard/commit/a10d6e2384915b047704eb2f227fa633b831a63e

**Comment by Motocycle347** [comment]
Not fixed

**Comment by martinrotter** [comment]
Provide your "config.ini" file.

**Comment by Motocycle347** [comment]
i sent you my config.ini still an issue

**Comment by Motocycle347** [comment]
Resolved latest .0 build

**Comment by Motocycle347** [comment]
Resolved latest .0 build
